src/OrleansProviders/SQLServer/CreateTables.sql

Updating the SQL server statistics publisher schema creation script to reflect column changes made in SqlStatisticsPublisher since the preview.

Fix for SqlStatisticsPublisher database schema changes

---

src/OrleansRuntime/MembershipService/MembershipOracleData.cs

Remove unused methods from MembershipOracleData: TryUpdateStatusesAndNotify and TryUpdateStatuses.

Remove unused methods from MembershipOracleData

---

src/Build.cmd

MSBUILDEXE Path Error

---

README.md

Add pointer to the .NET Contribution License Agreement to ReadMe.md

ReadMe-CLA

---

.gitignore

The binaries folder shouldn't be committed.

[Minor] Add Binaries/ folder to .gitignore

---

README.md

.. to make it obvious where to actually download the MSI from.

added link to the installer

---

src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamProvider.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingManager.cs
src/OrleansRuntime/Streams/QueueBalancer/AzureDelpoymentConfiguration.cs
src/OrleansRuntime/Streams/QueueBalancer/BestFitBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/ConsistentRingQueueBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/DeploymentBasedQueueBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/IDelpoymentConfiguration.cs
src/OrleansRuntime/Streams/QueueBalancer/StreamQueueBalancerFactory.cs

Added DeploymentBasedQueueBalancer that balances queues using deployment status.
Added AzureDeploymentBasedQueueBalancer that uses azure deployment information along with silo status for queue balancing.
Added BestFitBalancer generic resource balancing algorithm.
Updated StreamQueueBalancerFactory to include AzureDeploymentBasedQueueBalancer.

Add deployment based queue balancer #50 

---

src/Orleans/Core/GrainFactory.cs
src/Tester/ObserverTests.cs

Expose IGrainObserver factory methods through static GrainFactory.

---

src/OrleansVSTools/.nuget/NuGet.Config

Added nuget package sources for OrleansVSTools for both command line build and VS Online.

Added nuget package sources for OrleansVSTools

---

src/Orleans/AzureUtils/ClientMetricsTableDataManager.cs
src/Orleans/IDs/GrainId.cs
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Messaging/GatewayConnection.cs
src/Orleans/Messaging/IOutgoingMessage.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Messaging/SocketManager.cs
src/Orleans/Runtime/Constants.cs
src/Orleans/Runtime/IClientObserverRegistrar.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Statistics/ClientStatisticsManager.cs
src/OrleansRuntime/GrainDirectory/ClientObserverRegistrar.cs
src/OrleansRuntime/Messaging/Gateway.cs
src/OrleansRuntime/Messaging/GatewayAcceptor.cs
src/OrleansRuntime/Messaging/ISiloMessageCenter.cs
src/OrleansRuntime/Messaging/IncomingMessageAcceptor.cs
src/OrleansRuntime/Messaging/MessageCenter.cs

Unification of ClientId.

---

src/Orleans/AzureUtils/StatsTableDataManager.cs

This is a minor follow up to address some of the additional small improvements suggested in PR #95.

Minor follow up cleanup for StatsTableManager PK and RK rewrite.

---

Samples/AzureWebSample/AzureWebSample.sln
Samples/AzureWebSample/OrleansAzureSilos/OrleansAzureSilos.csproj
Samples/HelloWorld/HelloWorld.sln
Samples/HelloWorld/HelloWorld/HelloWorld.csproj
Samples/HelloWorld/HelloWorldGrains/HelloGrain.cs
Samples/HelloWorld/HelloWorldGrains/HelloWorldGrains.csproj
Samples/HelloWorld/HelloWorldGrains/Properties/AssemblyInfo.cs

Fix some naming typo's in HeloWorld grain directory names / projects /
code.
Fixes issue #77

HelloWorld Grains - Fix Spelling

---

src/Orleans/Orleans.csproj

Build-Cleanup-1
- Some minor refactoring and cleanup in Orleans.dll project / build
script, to prepare for easier integration of some later cross-plat build
changed.

Build-Cleanup-1

---

src/ClientGenerator/ClientGenerator.csproj
src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansProviders/OrleansProviders.csproj

- Fix some default namespace settings in .csproj to match source code in those projects.

Project-Default-Namespaces

---

src/Tester/Tester.csproj

Internal distributed tests expect them there.

Enabled CopyLocal for dependencies of Tester project

---

src/Orleans/AzureUtils/AzureStorageUtils.cs
src/Orleans/AzureUtils/AzureTableDataManager.cs
src/Orleans/AzureUtils/AzureTableDefaultPolicies.cs
src/Orleans/AzureUtils/OrleansSiloInstanceManager.cs
src/Orleans/Utils/Utils.cs
src/OrleansRuntime/ReminderService/RemindersTableManager.cs
src/TesterInternal/StorageTests/AzureTableDataManagerStressTests.cs
src/TesterInternal/StorageTests/AzureTableDataManagerTests.cs
src/TesterInternal/StorageTests/AzureTableErrorCodeTests.cs
src/TesterInternal/StorageTests/UnitTestAzureTableDataManager.cs
src/TesterInternal/TesterInternal.csproj

This PR includes a set of improvements to AzureTableDataManager wrapper for Azure Table access.:
1) Cleaned up APIs,
2) Proper batching for DeleteTableEntriesAsync.
3) Cleaned up all exception related APIs:
a) Added unit tests to all storage operations and validated that they all throw StorageException.
b) Updated all AzureStorageUtils exception handling methods to only analyze StorageException.
c) Still using AzureStorageUtils  wrappers around analyzing exceptions, although could have in theory just analyzed StorageException directly, mainly to minimize code churn in all other places and also leave the option to evolve exception parsing in the future, if ever needed
4) Optimized GetTableReference and TablePayloadFormat.JsonNoMetadata.

Azure table data manager improvements

---

Samples/AzureWebSample/OrleansAzureSilos/OrleansAzureSilos.csproj
Samples/AzureWebSample/WebRole/WebRole.csproj

- Fix typo in version of WindowsAzure.Configuration assembly reference.
Separating this change out from PR #144 since it is orthogonal to the config questions.

AzureWebSample - WindowsAzure.Configuration 2.0

---

Samples/AzureWebSample/OrleansAzureSilos/OrleansConfiguration.xml

This is the outstanding work item from previous PR #144

Cleanup azure web sample config

---

src/ClientGenerator/VBCodeGenerator.cs

Correcting a bug in the VB codegen.

Adjusting End Sub to End Function to fix a bug.

---

src/Orleans/Configuration/ProviderConfiguration.cs

Removed code duplication

---

src/Orleans/Async/AsyncExecutorWithRetries.cs
src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/IDs/ActivationId.cs
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Runtime/IClientObserverRegistrar.cs
src/Orleans/SystemTargetInterfaces/IRemoteGrainDirectory.cs
src/OrleansRuntime/GrainDirectory/ClientObserverRegistrar.cs
src/OrleansRuntime/GrainDirectory/GrainDirectoryPartition.cs
src/OrleansRuntime/Messaging/Gateway.cs
src/OrleansRuntime/Messaging/MessageCenter.cs
src/OrleansRuntime/Silo/Silo.cs

Register client pseudo grain id in the grain directory.
This is the next step in refactoring of Observers implementation.

Register client pseudo grain id in the grain directory.

---

src/Orleans/Async/ObserverSubscriptionManager.cs
src/Orleans/IDs/GrainId.cs
src/Orleans/IDs/UniqueKey.cs
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Messaging/Message.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Runtime/GrainReference.cs
src/Orleans/Runtime/IRuntimeClient.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Core/InsideGrainClient.cs
src/OrleansRuntime/GrainDirectory/ClientObserverRegistrar.cs
src/OrleansRuntime/Messaging/Gateway.cs
src/OrleansRuntime/Messaging/GatewayAcceptor.cs
src/OrleansRuntime/Messaging/ISiloMessageCenter.cs
src/OrleansRuntime/Messaging/MessageCenter.cs
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Placement/ClientObserversPlacementDirector.cs
src/OrleansRuntime/Placement/PlacementDirectorsManager.cs
src/OrleansRuntime/Placement/RandomPlacementDirector.cs
src/OrleansRuntime/Silo/Silo.cs
src/TesterInternal/General/Identifiertests.cs

Implementation of a new scalable protocol for Grain Observers.
No public API changes here yet.

New scalable protocol for Observers.

---

src/Tester/Tester.csproj

Added Client Generator to tester project so it would be available to load test code.

Added ClientGenerator to tester project

---

src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Configuration/ProviderConfiguration.cs
src/Orleans/Providers/IBootstrapProvider.cs
src/Orleans/Streams/Providers/StreamProviderManager.cs
src/OrleansRuntime/Core/BootstrapProviderManager.cs
src/OrleansRuntime/Storage/StorageProviderManager.cs

Just completed the work started by @yevhen's PR #205, to  do the same to storage and stream providers.

Added wrapper functions for stream and storage provider configurations, following @yevhen's PR #205.

---

src/OrleansRuntime/Silo/Silo.cs

Flagged by resharper and was indeed a bug.

Use SystemStatus.Equals instead of == and !=.

---

.gitignore

- Add patch.diff file to the .gitignore exclude list.

Ignore patch.diff

---

Samples/AzureWebSample/OrleansAzureSilos/OrleansAzureSilos.csproj
Samples/AzureWebSample/OrleansAzureSilos/app.config
Samples/AzureWebSample/OrleansAzureSilos/packages.config
Samples/AzureWebSample/WebRole/Web.config
Samples/AzureWebSample/WebRole/WebRole.csproj
Samples/AzureWebSample/WebRole/packages.config
Samples/GPSTracker/GPSTracker.GrainImplementation/GPSTracker.GrainImplementation.csproj
Samples/GPSTracker/GPSTracker.GrainImplementation/packages.config
Samples/GPSTracker/GPSTracker.Web/GPSTracker.Web.csproj
Samples/GPSTracker/GPSTracker.Web/packages.config
Samples/TicTacToe/OrleansXO.Web/TicTacToe.Web.csproj
Samples/TicTacToe/OrleansXO.Web/packages.config
Samples/TicTacToe/OrleansXO.WorkerRole/TicTacToe.WorkerRole.csproj
Samples/TicTacToe/OrleansXO.WorkerRole/app.config
Samples/TicTacToe/OrleansXO.WorkerRole/packages.config

Port all samples that use Azure to the new Azure Storage libraries

---

src/OrleansRuntime/Scheduler/WorkItemGroup.cs

As suggested here:(https://orleans.codeplex.com/discussions/606115)

Logging Improvements to WorkItemGroup stopped with orphan task warning.

---

Samples/TwitterSentiment/.gitignore
Samples/TwitterSentiment/ReadMe.md

More minor tweaks to Twitter sample.
- Updated ReadMe with pointer to node.js download location.
- Add .gitignore for transient Twitter data files.

Twitter sample 0324

---

misc/Projects-Applications-and-Companies-Using-Orleans.md

Added: Gassumo + NašeÚkoly.CZ to the companies, Sync.Today 2015 to the projects and Apps
related to #275 @gabikliot

Added: Sync.Today 2015 by Gassumo

---

src/ClientGenerator/CSharpCodeGenerator.cs
src/ClientGenerator/VBCodeGenerator.cs
src/Orleans/Core/GrainExtensions.cs
src/Orleans/Runtime/GrainReference.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingManager.cs

Fix to https://github.com/dotnet/orleans/issues/195.

Added  AsReference<TGrainInterface> and ported code gen.

---

src/Orleans/Configuration/ApplicationConfiguration.cs
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs
src/OrleansRuntime/GrainTypeManager/SiloAssemblyLoader.cs
src/OrleansRuntime/Silo/Silo.cs

Addresses this issue: http://orleans.codeplex.com/discussions/616456

Fixed a bug in silo config and type loading order that prevented per-type activation-GC setting to take effect.

---

src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/ClusterConfiguration.cs
src/Orleans/Configuration/ProviderConfiguration.cs
src/Tester/Extensions/TestConfigurationExtensions.cs
src/Tester/OrleansConfigurationForAQUnitTests.xml
src/Tester/StreamingTests/AQSubscriptionMultiplicityTests.cs
src/Tester/Tester.csproj
src/Tester/UnitTestSiloHost.cs

Added Subscription Multiplicity tests for Azure Queue Stream Provider.
Added DeploymentId overrides to providers in test deployments.

Subscription Multiplicty Tests for Azure Queue Stream Provider

---

src/Build/PostBuild.cmd
src/Chocolatey/CreateOrleansChocolateyPackage.bat
src/Chocolatey/orleans.nuspec
src/Orleans.sln
src/TesterInternal/TesterInternal.csproj

This PR enhances Orleans (see #275). It creates [Chocolatey](https://chocolatey.org/) package.

Chocolatey package create on build

---

src/Orleans/IDs/GuidId.cs
src/Orleans/Streams/PubSub/PubSubPublisherState.cs
src/Orleans/Streams/PubSub/PubSubSubscriptionState.cs

Json serialization support for PubSubRendevousGrain state

---

src/Orleans/Core/GrainFactory.cs

GrainFactory.GetGrain - pass grainClassNamePrefix to _MakeGrainReference

---

src/ClientGenerator/ClientGenerator.cs
src/Orleans/Runtime/RuntimeVersion.cs
src/OrleansRuntime/Counters/PerfCountersStatistics.cs
src/OrleansRuntime/Scheduler/WorkerPoolThread.cs
src/OrleansRuntime/Silo/Silo.cs

Some miscellaneous cleanup changes that proved useful while investigating Mono build / run scenarios, but are not directly related to Mono.

Cleanup 0418

---

src/Orleans/CodeGeneration/GrainFactoryBase.cs

Fixed the bug with handling of generic type information introduced while removing code duplication in grain factories.

Fixed the bug with handling of generic type information 

---

src/Tester/UnitTestSiloHost.cs
src/Tester/UnitTestSiloHostOptions.cs

Helps address https://github.com/dotnet/orleans/issues/48#issuecomment-96753041 - speeding up multiple silos startup.

Start silos in parallel in Unit Test Host.

---

src/ClientGenerator/ClientGenerator.cs
src/ClientGenerator/Serialization/SerializationGenerator.cs

Fixed code gen breaking with type without namespace (empty using statement emitted).

---

Samples/Chirper/1.Demo Start Silo.cmd
Samples/Chirper/ChirperClient/App.config
Samples/Chirper/ChirperClient/ChirperClient.csproj
Samples/Chirper/ChirperClient/packages.config
Samples/Chirper/ChirperGrainInterfaces/ChirperGrainInterfaces.csproj
Samples/Chirper/ChirperGrainInterfaces/packages.config
Samples/Chirper/ChirperGrains/ChirperGrains.csproj
Samples/Chirper/ChirperGrains/OrleansConfiguration.xml
Samples/Chirper/ChirperGrains/OrleansHost.exe.config
Samples/Chirper/ChirperGrains/app.config
Samples/Chirper/ChirperGrains/packages.config
Samples/Chirper/NetworkDriver/NetworkDriver.csproj
Samples/Chirper/NetworkDriver/app.config
Samples/Chirper/NetworkDriver/packages.config
Samples/Chirper/NetworkLoader/NetworkLoader.csproj
Samples/Chirper/NetworkLoader/packages.config

Updating the Chirper sample to use nuget instead of SDK.
I tried all the .cmd tests and they are working.

Modify chirper sample to use nuget packages instead of SDK

---

src/OrleansAzureUtils/AzureSilo.cs
src/OrleansHost/WindowsServerHost.cs
src/OrleansRuntime/Silo/SiloHost.cs

A draft that doesn't impact existing functionality. Extended a few methods with an extra CancellationToken param.

Support for CancellationToken in SiloHost, AzureSilo & WindowsServerHost

---

Samples/README.txt

User deadhand experienced problems which he wrote in Orleans Gitter were indicated by https://orleans.codeplex.com/discussions/543291 and https://orleans.codeplex.com/discussions/616249. Then I know private some have had trouble with firewall settings. This is an attempt to document some fixes in one potential place.

Added troubleshooting items to README.txt

---

src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs
src/TestGrains/MultipleSubscriptionConsumerGrain.cs
src/TestGrains/SampleStreamingGrain.cs
src/Tester/ClientConfigurationForUnitTests.xml
src/Tester/OrleansConfigurationForStreamingDeactivationUnitTests.xml
src/Tester/StreamingTests/DeactivationTestRunner.cs
src/Tester/StreamingTests/SMSDeactivationTests.cs
src/Tester/Tester.csproj
src/Tester/UnitTestUtils.cs

Minor improvements over @ca-ta PR #380 .

Minor improvements to SMSDeactivationTests.

---

src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs

This is a small improvement over #336.
It addresses an edge case where it is possible for a ```PubSubRendezvousGrain``` to remove all producers upon activation. 
If the grain has no consumers and the sole reason for activation is a call to ```GetAllSubscriptions``` (through a call to ```GetAllSubscriptionHandles``` on the corresponding stream),  the grain will fail to clear its (now empty) state from storage.
Note that I did not add a call to  DeactivateOnIdle() , as the reasons for the grain being activated may include adding consumers/producers.

PubSubRendezvousGrain: clear state from storage if it becomes empty upon activation

---

Samples/GPSTracker/GPSTracker.GrainImplementation/PushNotifierGrain.cs

Fix to https://github.com/dotnet/orleans/issues/254.

Fixed a bug in GPSTracker sample.

---

src/Orleans/Messaging/IGatewayListProvider.cs
src/Orleans/SystemTargetInterfaces/IMembershipTable.cs

Documented IMembershipTable.

---

src/Orleans/Async/AsyncBatchedContinuationQueue.cs
src/Orleans/Async/MultiTaskCompletionSource.cs
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Orleans.csproj
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/InsideGrainClient.cs
src/Tester/StreamingTests/SMSDeactivationTests.cs

Fixes https://github.com/dotnet/orleans/issues/378 and the tests in https://github.com/dotnet/orleans/pull/380 that reproduced the bug are now passing OK.
Thanks @ca-ta for spotting, reporting and reproducing the bug!

Deactivation deadlock bug fix

---

src/Orleans/Messaging/Message.cs
src/Orleans/Runtime/RequestContext.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/MembershipService/MembershipOracle.cs
src/OrleansRuntime/Messaging/IncomingMessageAcceptor.cs

Translated message header strings into byte enums.
Should reduce size and header access speed.

Minor compaction of message header data.

---

src/Orleans/Configuration/ApplicationConfiguration.cs
src/Orleans/Configuration/ConfigUtilities.cs

This is in addition to already existing SetCollectionAgeLimit(Type type, TimeSpan ageLimit).

Added SetCollectionAgeLimit(string grainTypeFullName, TimeSpan ageLimit) to use when Type is not available.

---

src/Orleans/Runtime/SiloStatus.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/ConsistentRing/ConsistentRingProvider.cs
src/OrleansRuntime/ConsistentRing/VirtualBucketsRingProvider.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/GrainDirectory/GrainDirectoryPartition.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs
src/OrleansRuntime/MembershipService/ISiloStatusOracle.cs
src/OrleansRuntime/MembershipService/MembershipOracle.cs
src/OrleansRuntime/MembershipService/MembershipOracleData.cs
src/OrleansRuntime/Placement/DeploymentLoadPublisher.cs

No logic change. 
A first step towards Gracefull Shutdown, related to:
https://github.com/dotnet/orleans/issues/381
https://github.com/dotnet/orleans/issues/320#issuecomment-101035028
http://orleans.codeplex.com/discussions/637820#post1425137

Refactored silo statuses to use IsTerminating and better encapsulation of usage of IsTerminating in various places.

---

src/Orleans/Orleans.csproj
src/Orleans/Streams/QueueAdapters/HashRingBasedStreamQueueMapper.cs
src/Orleans/Streams/QueueAdapters/IConsistentRingStreamQueueMapper.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs
src/OrleansProviders/Streams/AzureQueue/AzureQueueAdapter.cs
src/OrleansProviders/Streams/AzureQueue/AzureQueueAdapterFactory.cs
src/OrleansRuntime/Streams/QueueBalancer/ConsistentRingQueueBalancer.cs

Small improvements and cleanup to streaming APIs 
Change the default to FireAndForgetDelivery for SMS.
Refactor IStreamQueueMapper.

Streaming API improvements

---

Getting-Started-With-Orleans/Asynchrony-and-Tasks.md
Getting-Started-With-Orleans/Clients.md
Getting-Started-With-Orleans/Core-Concepts.md
Getting-Started-With-Orleans/Developing-a-Client.md
Getting-Started-With-Orleans/Developing-a-Grain.md
Getting-Started-With-Orleans/Grains.md
Getting-Started-With-Orleans/Observers.md
Getting-Started-With-Orleans/Running-the-Application.md
Getting-Started-With-Orleans/Silos.md

Made the following changes to the Step-by-step documentation
* Consistent treatment of file names, folder names and paths. All in italic e.g. _../Dir/file.ext_ as per [GitHub help](https://help.github.com/articles/create-a-repo/)
* Consistent marking up of inline code e.g. `Task`
* Consolidated on straight quotes (" & ') not curled quotes (“..” & ‘..’). i.e instead of “Factory”, now "Factory"
* Added footer links to take to next page
* Fixed missing/broken links
* Consistent usage of one line per sentence.
* replaced ALLCAPS with formatting e.g. MUST became _must_

Updating Getting started documentation

---

Documentation-Guidelines.md

As per @jthelin request in #434

Adding documentation guidelines. Closes #434

---

src/NuGet/Microsoft.Orleans.Client.nuspec
src/NuGet/Microsoft.Orleans.CounterControl.nuspec
src/NuGet/Microsoft.Orleans.OrleansAzureUtils.nuspec
src/NuGet/Microsoft.Orleans.OrleansHost.nuspec
src/NuGet/Microsoft.Orleans.OrleansManager.nuspec
src/NuGet/Microsoft.Orleans.OrleansProviders.nuspec
src/NuGet/Microsoft.Orleans.OrleansRuntime.nuspec
src/NuGet/Microsoft.Orleans.Server.nuspec
src/NuGet/Microsoft.Orleans.Templates.Grains.nuspec
src/NuGet/Microsoft.Orleans.Templates.Interfaces.nuspec
src/NuGet/Microsoft.Orleans.TestingHost.nuspec

This is to address the version discrepancy pointed to by @attilah.

Updated NuGet dependencies to match the current version - 1.0.7.

---

src/Tester/ObserverTests.cs

Changed 2 more tests to use await instead of Wait.

---

src/Orleans/Timers/ReminderRegistry.cs

Fix for a bug in the format string of ReminderRegistry.RegisterOrUpdateReminder

---

Samples/Chirper/ChirperClient/ChirperClient.csproj
Samples/Chirper/ChirperClient/packages.config
Samples/Chirper/ChirperGrainInterfaces/ChirperGrainInterfaces.csproj
Samples/Chirper/ChirperGrainInterfaces/packages.config
Samples/Chirper/ChirperGrains/ChirperAccount.cs
Samples/Chirper/ChirperGrains/ChirperGrains.csproj
Samples/Chirper/ChirperGrains/packages.config
Samples/Chirper/NetworkDriver/NetworkDriver.csproj
Samples/Chirper/NetworkDriver/packages.config
Samples/Chirper/NetworkLoader/NetworkLoader.csproj
Samples/Chirper/NetworkLoader/packages.config

Don't wipe out the state in OnActivateAsync,
Properly write the state back to store every time it changes.
Also update to Nugets 1.0.8.

Fixed Chirper sample to correctly use State

---

src/Orleans/Core/GrainExtensions.cs

Explicit error handling for cases when users explicitly instantiate a grain not via Orleans runtime and not via proper test mocking.
Will give more explicit exception message instead of NullRefExc.
Inspired by a real use case by one of the internal customers.

Explicit error handling for cases when users explicitly instantiate a grain not via Orleans runtime and not via proper test mocking.

---

src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Providers/IProviderRuntime.cs
src/Orleans/Providers/StatisticsProviderManager.cs
src/OrleansProviders/Storage/MemoryStorage.cs
src/OrleansRuntime/ReminderService/LocalReminderServiceFactory.cs
src/OrleansRuntime/ReminderService/ReminderTable.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Storage/StorageProviderManager.cs

This is to address https://github.com/dotnet/orleans/issues/456.

Add GrainFactory to IProviderRuntime

---

src/ClientGenerator/CSharpCodeGenerator.cs
src/ClientGenerator/VBCodeGenerator.cs
src/Orleans/Core/GrainFactory.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Runtime/GrainReference.cs
src/Orleans/SystemTargetInterfaces/IManagementGrain.cs
src/OrleansManager/Program.cs
src/OrleansRuntime/Core/InsideGrainClient.cs
src/OrleansRuntime/Core/ManagementGrain.cs
src/OrleansRuntime/GrainDirectory/AdaptiveDirectoryCacheMaintainer.cs
src/OrleansRuntime/GrainDirectory/GrainDirectoryPartition.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs
src/OrleansRuntime/GrainDirectory/RemoteGrainDirectory.cs
src/OrleansRuntime/MembershipService/MembershipFactory.cs
src/OrleansRuntime/MembershipService/MembershipOracle.cs
src/OrleansRuntime/Placement/DeploymentLoadPublisher.cs

Move system targets to use generic factories.

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/ConsistentRing/ConsistentRingProvider.cs
src/OrleansRuntime/Core/ManagementGrain.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs
src/OrleansRuntime/Scheduler/WorkItemGroup.cs

Fix logging issue + small stuff

Fix logging issue

---

src/ClientGenerator/NamespaceGenerator.cs
src/Orleans/CodeGeneration/GrainState.cs
src/Orleans/Core/Grain.cs
src/Orleans/Core/GrainStateStorageBridge.cs
src/Orleans/Core/IGrainState.cs
src/Orleans/Core/IStorage.cs
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/GrainRuntime.cs
src/Orleans/Runtime/IActivationData.cs
src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/GrainTypeManager/SiloAssemblyLoader.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs
src/OrleansTestingHost/OrleansConfigurationForTesting.xml
src/TestGrainInterfaces/ISimpleGrain.cs
src/TestGrainInterfaces/ISimplePersistentGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/SimplePersistentGrain.cs
src/TestGrains/TestGrains.csproj
src/Tester/ConcreteStateClassTests.cs
src/Tester/Tester.csproj

This is a rebased and partly squashed version of https://github.com/dotnet/orleans/pull/465 ready to be merged. I'll close https://github.com/dotnet/orleans/pull/465.

Add support for grain state classes

---

src/ClientGenerator/CSharpCodeGenerator.cs
src/ClientGenerator/VBCodeGenerator.cs
src/Orleans/CodeGeneration/GrainFactoryBase.cs
src/Orleans/CodeGeneration/TypeUtils.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs
src/TestGrainInterfaces/ISimpleGenericGrain.cs
src/TestGrains/ConcreteGrainsWithGenericInterfaces.cs
src/TestGrains/SimpleGenericGrain.cs
src/Tester/GenericGrainTests.cs

This is to fix the issue exposed by the GenericGrainTests_UseGenericFactoryInsideGrain test.

Fix handling of generic grain type codes

---

src/TestGrainInterfaces/IGenericInterfaces.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/GenericGrains.cs
src/TestGrains/TestGrains.csproj
src/Tester/GenericGrainTests.cs

Moved all internal generics-related tests to GitHub.

Migrated tests for generic grain interfaces and classes

---

Test.cmd
TestAll.cmd
src/Chocolatey/CreateOrleansChocolateyPackage.bat
src/NuGet/CreateOrleansPackages.bat

Fix some other places that are affected by directory paths with spaces in them.
This change is a follow on from PR #462 by @ElanHasson

Fix some other script files affected by dir paths with spaces

---

src/Orleans/CodeGeneration/GrainInterfaceData.cs
src/Orleans/Core/GrainClient.cs
src/Orleans/Core/GrainFactory.cs
src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Runtime/IGrainExtension.cs
src/Orleans/Streams/Internal/IStreamGrainExtensions.cs
src/Orleans/Utils/Utils.cs
src/OrleansRuntime/ReminderService/LocalReminderService.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs

Remove reflection factories

---

src/TesterInternal/StorageTests/AzureMembershipTableTests.cs
src/TesterInternal/StorageTests/MembershipTablePluginTests.cs
src/TesterInternal/StorageTests/SQLMembershipTableTests.cs
src/TesterInternal/StorageTests/ZookeeperMembershipTableTests.cs
src/TesterInternal/TesterInternal.csproj

This will also help @veikkoeeva in his efforts on #347.

Membership tests cleanup and restructuring.

---

src/Orleans/CodeGeneration/GrainInterfaceData.cs
src/Orleans/CodeGeneration/TypeUtils.cs

Refactored to remove redundant warnings during assembly load. simplified the previous fix to minimize changes.

Fixed the load warnings caused due to previous fix.

---

src/OrleansTestingHost/TestingSiloHost.cs

MS Test was throwing: "MSTest: Unit Test Adapter threw exception: Type is not resolved for member OrleansException".
Because of that we were basically losing the original exception in Tests if silo or client were throwing as part of their init or Stat sequence. That made debugging tests much harder. This will hopefully eliminate this problem all together. We will pass the exception as string details.

Do not include original Orleans exception type in TestingSiloHost constructor re-throw.

---

src/ClientGenerator/CSharpCodeGenerator.cs
src/ClientGenerator/VBCodeGenerator.cs
src/TestGrains/SimpleGenericGrain.cs

Last nail in the coffin of #469!

Deprecated code generation for concrete GetGrain factory methods.

---

src/Orleans/Serialization/BinaryTokenStreamReader.cs
src/Orleans/Serialization/BinaryTokenStreamWriter.cs
src/Tester/SerializationTests.cs

DateTime Serialization

---

src/Orleans/Utils/SafeRandom.cs

Updated SafeRandom to use a thread static instance instead of using locks, similar to http://blogs.msdn.com/b/pfxteam/archive/2014/10/20/9434171.aspx

Updated SafeRandom to use a thread static instance instead of locks

---

Runtime-Implementation-Details/Relational-Storage.md
Runtime-Implementation-Details/index.md

This adds relational data storage implementation documentation.

Added relational data storage documentation

---

Runtime-Implementation-Details/Cluster-Management.md

There were some spots which had only SQL Server mentioned or
weren't clear that other than SQL Server is supported too. A
few other inconsistencies fixed too.

Clarified that not only SQL Server but other vendors too

---

src/ClientGenerator/Serialization/SerializerGenerationManager.cs
src/TestGrainInterfaces/CodegenTestInterfaces.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj

Fixed a bug related to codegen fails for grain interface method with a param type defined on global namespace.

---

src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/ClusterConfiguration.cs
src/Orleans/Logging/LogWriters.cs
src/Orleans/Messaging/SocketManager.cs

work on replacing .close() with .dispose() for coreclr port.

changed close to dispose & changed of scoping with using

---

src/Orleans/Utils/SafeRandom.cs

Addressing https://github.com/dotnet/orleans/pull/595#issuecomment-121005051.

Switched RNGCryptoServiceProvider to RandomNumberGenerator, since it is coreclr complaint.

---

src/Orleans/Utils/Utils.cs

PR for Port Orleans to coreclr #368.
SHA256 API change

Coreclr compatibility: SHA256 Api change

---

src/Orleans/Configuration/OrleansConfiguration.xsd

updated all relevant documents.

updated xsd to include ZooKeeper

---

src/Orleans/Messaging/SqlMembershipTable.cs

Fixed NullRefExc in SqlMembershipTable.

---

src/OrleansAzureUtils/Hosting/AzureSilo.cs

Added back 'AzureSilo.Start' overload containing deploymentId

---

src/Orleans/Messaging/SqlMembershipTable.cs

Added missing InitializeOrleansQueriesAsync() to SQL.InitializeGatewayListProvider.

---

src/Orleans/Async/ObserverSubscriptionManager.cs
src/Orleans/Core/GrainClient.cs

Addresses https://github.com/dotnet/orleans/issues/662.

Added IsRunningInsideGrain check to GrainClient.GrainFactory.

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Messaging/GatewayProviderFactory.cs
src/Orleans/SystemTargetInterfaces/IReminderTable.cs
src/OrleansRuntime/Core/ManagementGrain.cs
src/OrleansRuntime/MembershipService/MembershipFactory.cs
src/OrleansRuntime/ReminderService/LocalReminderServiceFactory.cs
src/OrleansRuntime/ReminderService/ReminderTable.cs
src/OrleansRuntime/Silo/Silo.cs

Trying to write custom remindersTable and membershipTable storages 
related to #69

ReminderTableAssembly and MembershipTableAssembly in SystemStore Config

---

src/Orleans/Statistics/RuntimeStatisticsGroup.cs

Initialize RuntimeStatisticsGroup from Task due to hang of PerformanceCounter's ctor in IISExpress #671

Timeout for RuntimeStatisticsGroup initialization 

---

src/Orleans/Serialization/BuiltInTypes.cs
src/Orleans/Serialization/SerializationManager.cs

Added 'DateTimeOffset' as built-in type re #676

---

src/OrleansTestingHost/StorageEmulator.cs

Fixes #674 simply by checking first the newest known executable
and process name and then the older ones.

Adds a check for the newest Azure Storage Emulator exe name

---

src/Orleans/Streams/Core/StreamSubscriptionHandle.cs
src/Orleans/Streams/Internal/StreamSubscriptionHandleImpl.cs

Added unique public identifier to StreamSubscriptionHandle.

---

Orleans-Configuration-Guide/Typical-Configurations.md

A wrong XML element used in both client and silo configurations

Azure system store cluster configurations

---

src/Orleans/Messaging/GatewayManager.cs
src/Orleans/RelationalStorage/RelationalStorageExtensions.cs
src/OrleansAzureUtils/Storage/AzureGatewayListProvider.cs

Avoid using Linq.Any(), use Count property instead.

---

src/TestGrainInterfaces/IInitialStateGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/InitialStateGrain.cs
src/TestGrains/TestGrains.csproj
src/TesterInternal/StorageTests/MemoryStorageProviderTests.cs
src/TesterInternal/TesterInternal.csproj

expose issue with the memory storage provider and state initialization

---

Advanced-Concepts/Two-Way-Client-Observers.md
Advanced-Concepts/index.md

As per [questions](https://gitter.im/dotnet/orleans?at=55d154d39b45e15c42647e5d) and [request](https://gitter.im/dotnet/orleans?at=55d1557d3d8917890c1650a1) on Gitter by @andre-realroi.

Documented Two Way Client Observers.

---

src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Streams/Internal/IStreamGrainExtensions.cs
src/Orleans/Streams/Internal/StreamConsumer.cs
src/Orleans/Streams/Internal/StreamConsumerExtension.cs
src/Orleans/Streams/Internal/StreamSubscriptionHandleImpl.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans/Streams/PersistentStreams/QueueStreamDataStructures.cs
src/Orleans/Streams/PersistentStreams/StreamConsumerCollection.cs
src/Orleans/Streams/Providers/IStreamProviderRuntime.cs
src/Orleans/Streams/PubSub/IPubSubRendezvousGrain.cs
src/Orleans/Streams/PubSub/PubSubRuntime.cs
src/Orleans/Streams/PubSub/PubSubSubscriptionState.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProducerExtension.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingManager.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs

If a stream sequence token is provided while subscribing from an implicit stream consumer it will now be respected.

Added recoverability/rewinding to Implicit Subscriptions.

---

src/Orleans/IDs/QueueId.cs

Extending the work done in #702 .

Added more constructor options for QueueId, to support a wider range of queue ids scenarios.

---

src/Orleans/CodeGeneration/TypeUtils.cs
src/Tester/GenericGrainTests.cs

Fixes #707
Fix + test, all other tests pass.

Activate grains implementing interfaces that have generic type parameters

---

src/Orleans/Timers/ReminderRegistry.cs

Add a Guard.NotNullOrEmpty for the reminderName parameter.

---

src/Orleans/Messaging/Message.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Runtime/RequestContext.cs
src/Orleans/Runtime/RuntimeClient.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProducer.cs
src/Orleans/Streams/QueueAdapters/IBatchContainer.cs
src/Orleans/Streams/QueueAdapters/IQueueAdapter.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapter.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueBatchContainer.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/SimpleAzureQueueAdapter.cs
src/OrleansRuntime/Core/InsideGrainClient.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/TestGrains/MultipleSubscriptionConsumerGrain.cs
src/TestGrains/SampleStreamingGrain.cs

Propagate request context via persistent streams.

---

src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql

Improved explanations, added SQL Server 2016
to the matrix to signal it's accounted for.
Fixes partially #650.

Minor cleanup of SQL Server system store script

---

src/OrleansRuntime/Catalog/Catalog.cs

`StatelessWorkers` are not registered in the directory, so also do not need to be un-registered.

Do not unregister StatelessWorker in the directory.

---

src/Orleans/Async/TaskExtensions.cs
src/Orleans/Streams/Internal/IStreamGrainExtensions.cs
src/Orleans/Streams/Internal/StreamConsumerExtension.cs
src/Orleans/Streams/Internal/StreamSubscriptionHandleImpl.cs
src/Orleans/Streams/PersistentStreams/QueueStreamDataStructures.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProducerExtension.cs
src/OrleansAzureUtils/Providers/Streams/PersistentStreams/StreamDeliveryFailureEntity.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Enhanced stream producer consumer handshake protocol with an additional token to handle message failures, retries and be more robust.

Stream rewind handshake review

---

src/TestGrainInterfaces/ISimpleRequestContextGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/SimpleRequestContextGrain.cs
src/TestGrains/TestGrains.csproj
src/Tester/RequestContextTest.cs
src/Tester/Tester.csproj

This is the test that shows the problem

Test that fails to flow RequestContext info from callee to caller

---

src/Orleans/Streams/Internal/StreamSubscriptionHandleImpl.cs
src/OrleansProviders/Streams/Common/SimpleQueueCache.cs
src/TestGrains/MultipleSubscriptionConsumerGrain.cs
src/TestGrains/SampleStreamingGrain.cs
src/Tester/StreamingTests/AQSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/SMSSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/SubscriptionMultiplicityTestRunner.cs

The bug was causing us to loosing some events.
Also added another test and enhanced logging in those tests.

Fixed  a bug in the adapter cache around consumer subscription becoming active again after cache became empty.

---

src/Orleans/Statistics/StatisticNames.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans/Streams/Providers/IStreamProviderRuntime.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingManager.cs

Organized all Persistent Stream Provider Config values into one class.
Added more stat counters to stream pulling agent.

Unified Persistent Stream Provider Config and more stats counters.

---

src/Orleans/Statistics/IPerformanceMetrics.cs

They were already in Silo Metrics. Just added the 2 properties and modified the constructor.

Adding Received/Sent messages to Runtime stattistics 

---

src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/OrleansZooKeeperUtils/OrleansZooKeeperUtils.csproj
src/OrleansZooKeeperUtils/packages.config

**IMPORTANT FIX** - Fixed a race-condition bug when connecting to multiple servers

ZK MBR -  update ZooKeeperNetEx to 3.4.6.1006

---

src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
src/OrleansAzureUtils/Storage/AzureStorageUtils.cs
src/OrleansAzureUtils/Storage/RemindersTableManager.cs

Sanitized reminder row key.

---

src/OrleansRuntime/Catalog/Catalog.cs

- Can move some of the grain instance initialization logic outside lock.

Move some of the grain instance initialization logic outside lock.

---

src/Orleans/Core/Exceptions.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/TesterInternal/OrleansRuntime/ExceptionsTests.cs
src/TesterInternal/TesterInternal.csproj

Implemented proper serialization for 2 runtime exceptions.

---

src/Orleans/Messaging/Message.cs
src/Orleans/Runtime/CallbackData.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Runtime/RuntimeClient.cs
src/OrleansRuntime/Core/InsideGrainClient.cs

Removed static fields from CallbackData and RuntimeClient.

---

src/Orleans/Providers/ProviderLoader.cs

Addresses https://github.com/dotnet/orleans/issues/786#issuecomment-140419268

Added more helpful error msg.

---

src/Orleans/Streams/Internal/StreamConsumerExtension.cs
src/Orleans/Streams/Internal/StreamSubscriptionHandleImpl.cs
src/Orleans/Streams/PersistentStreams/IStreamFailureHandler.cs
src/Orleans/Streams/PersistentStreams/NoOpStreamFailureHandler.cs
src/OrleansAzureUtils/Providers/Streams/PersistentStreams/AzureTableStorageStreamFailureHandler.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Refactored and hardened error handling code in the pulling agent, including handle errors of GetSequenceToken calls.

Refactored and hardened error handling code in the pulling agent.

---

Getting-Started-With-Orleans/Developing-a-Grain.md
Getting-Started-With-Orleans/Grains.md
Step-by-step-Tutorials/Actor-Identity.md
What's-new-in-Orleans.md

Updated some of the docs. specifically these
- Fixed references to IGrain in Getting Started guides
- Fixed a few spelling errors which I encountered while reading the stuff.

Documentation fixes

---

src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql

Changed [StatValue] NVARCHAR(1024).

---

src/NuGet/Microsoft.Orleans.EventSourcing.nuspec
src/Orleans.EventSourcing/JournaledGrain.cs
src/Orleans.EventSourcing/OrleansEventSourcing.csproj
src/Orleans.sln
src/TestGrains/TestGrains.csproj

Added a nuspec file for event sourcing project.
Renamed the project - dot removed.

Event sourcing - NuGet package

---

src/Orleans/Configuration/NodeConfiguration.cs
src/OrleansProviders/OrleansProviders.csproj
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Startup/ConfigureServicesBuilder.cs
src/OrleansRuntime/Storage/MemoryStorageGrain.cs
src/OrleansRuntime/packages.config
src/TestGrainInterfaces/ISimpleDIGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/SimpleDIGrain.cs
src/TestGrains/TestGrains.csproj
src/Tester/DependencyInjectionGrainTests.cs
src/Tester/OrleansStartupConfigurationForTesting.xml
src/Tester/Tester.csproj

After deciding to use Asp.Net vNext DI, it seemed much simpler to go to stage two and add support for a Startup class, which supports DI in an Asp.Net vNext way.
Follow up on #709.

Asp.Net vNext DI implemented.

---

src/Orleans/Orleans.csproj
src/Orleans/Streams/Internal/IStreamGrainExtensions.cs
src/Orleans/Streams/Internal/StreamConsumerExtension.cs
src/Orleans/Streams/Internal/StreamHandshakeToken.cs
src/Orleans/Streams/Internal/StreamSubscriptionHandleImpl.cs
src/Orleans/Streams/PersistentStreams/QueueStreamDataStructures.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

See bug fix. #859
This is an alternative approach (same high level idea, a bit different code) to fixing the bug described in #859.

Stream event delivery data loss bug fix 2

---

src/Orleans/Providers/IOrleansProvider.cs
src/Orleans/Providers/IStorageProvider.cs
src/Orleans/Providers/StatisticsProviderManager.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans/Streams/Providers/IStreamProviderImpl.cs
src/Orleans/Streams/Providers/StreamProviderManager.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs
src/OrleansProviders/SQLServer/SqlStatisticsPublisher.cs
src/OrleansRuntime/Core/BootstrapProviderManager.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Storage/StorageProviderManager.cs

Close all providers when shutting down silo.

---

src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs

This fixes the related build warning.

Fix incorrect cref in XML comment

---

src/Orleans/RelationalStorage/QueryConstantsBag.cs

Fixed wrong reserved word escape indicators and a spelling error

---

src/Orleans/Serialization/BuiltInTypes.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansAzureUtils/Hosting/ServiceRuntimeWrapper.cs

Related to: Port Orleans to coreclr #368

Coreclr compatibility: Delegate.CreateDelegate -> MethodInfo.CreateDelegate 

---

src/Orleans/Orleans.csproj
src/Orleans/Streams/Internal/IStreamGrainExtensions.cs
src/Orleans/Streams/Internal/StreamConsumerExtension.cs
src/Orleans/Streams/Internal/StreamHandshakeToken.cs
src/Orleans/Streams/Internal/StreamSubscriptionHandleImpl.cs
src/Orleans/Streams/PersistentStreams/QueueStreamDataStructures.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Reapply fix that was lost.
Same PR as #860.

Stream event delivery data loss bug fix3

---

Who-Is-Using-Orleans.md

Could we please be added to the list of who is using Orleans.

Added Applicita to Who-Is-Using-Orleans

---

src/ClientGenerator/NamespaceGenerator.cs
src/Orleans/Core/Exceptions.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansAzureUtils/Hosting/AzureSilo.cs
src/OrleansAzureUtils/Hosting/ServiceRuntimeWrapper.cs
src/OrleansAzureUtils/Storage/AzureBasedReminderTable.cs

Coreclr compatibility: ApplicationException -> Exception

---

src/ClientGenerator/ClientGenerator.cs

Show F# compilation issues if found

---

src/Orleans/Configuration/ConfigUtilities.cs

CoreCLR compatibility: ToLower(CultureInfo.InvariantCulture) -> ToLowerInvariant()

---

src/Orleans/Serialization/BuiltInTypes.cs

Coreclr compatibility: UriTypeConverter -> TypeDescriptor.GetConverter

---

Frequently-Asked-Questions.md

Added a few more questions with their answers.

Updated FAQs

---

src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Configuration/OrleansConfiguration.xsd
src/Orleans/Runtime/Constants.cs
src/TesterInternal/RemindersTest/SqlRemindersTableTests.cs

Small PR but important if someone wants to use custom systemstore.

#753 Add DataConnectionStringForReminders & AdoInvariantForReminders to xml configs

---

src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/ClusterConfiguration.cs
src/Orleans/Configuration/ConfigUtilities.cs
src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Configuration/NodeConfiguration.cs
src/Orleans/Serialization/BuiltInTypes.cs

Coreclr compatibility: Dns.GetHostAddresses -> GetHostAddressesAsync

---

src/Orleans/Async/AsyncExecutorWithRetries.cs

Backoff policy contained mutable state.  Backoff policy is not immutable.

Stream delivery retry bug fix.

---

src/Orleans/Async/TaskExtensions.cs
src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Configuration/NodeConfiguration.cs
src/Orleans/Core/GrainClient.cs
src/Orleans/Messaging/GatewayManager.cs
src/Orleans/Messaging/GatewayProviderFactory.cs
src/Orleans/Messaging/IGatewayListProvider.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansAzureUtils/Storage/AzureGatewayListProvider.cs
src/OrleansAzureUtils/Storage/OrleansSiloInstanceManager.cs
src/OrleansManager/Program.cs
src/OrleansSQLUtils/Messaging/SqlMembershipTable.cs
src/OrleansZooKeeperUtils/ZooKeeperBasedMembershipTable.cs
src/TesterInternal/StorageTests/SiloInstanceTableManagerTests.cs

Turn IGatewayListProvider.GetGateways() into a Task-based method

---

src/Orleans/Async/TaskExtensions.cs

Related to https://github.com/dotnet/orleans/pull/928#discussion_r42577669; [Asynchronously wait for Task<T> to complete with timeout](http://stackoverflow.com/questions/4238345/asynchronously-wait-for-taskt-to-complete-with-timeout#comment31900829_11191070)

Add cancellation to the Task.Delay

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/Configuration/ConfigUtilities.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Utils/Utils.cs

Assembly loading: Assembly.Load(String) -> .Load(new AssemblyName(string))

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/AssemblyLoader/AssemblyLoaderReflectionCriterion.cs
src/Orleans/AssemblyLoader/AssemblyProcessor.cs
src/Orleans/CodeGeneration/TypeUtils.cs
src/OrleansCodeGenerator/CodeGeneratorCommon.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/TesterInternal/General/SerializationTests.cs

Assembly loading: Assembly.GetTypes() -> Assembly.DefinedTypes

---

src/Orleans/Configuration/ConfigUtilities.cs

Assembly loading: Assembly.CreateInstance -> Activator.CreateInstance

---

src/Orleans/Statistics/LogStatistics.cs

Don't publish empty statistics.

---

Documentation-Guidelines.md
Frequently-Asked-Questions.md

Added some docs regarding markdown editors to the documentation guide page. Also added a question to the FAQ regarding the possibility of having multiple activations of a grain.
Honestly speaking we should create a page and describe how the DHT works completely in it. Not only for the nirdy coolness of it but for the more experienced distributed developer which is choosing his next platform and is not sure of Orleans.

Added some documentation

---

src/OrleansRuntime/MembershipService/InMemoryMembershipTable.cs

Addresses https://github.com/dotnet/orleans/pull/979#issuecomment-153674962

Full copy of MembershipTableData for GrainBasedMembershipTable

---

src/Orleans/Core/GrainClient.cs

Provide more explicit error message when `GrainClient.GrainFactory` is used by mistake instead of `providerRuntime.GrainFactory` in the Bootstrap provider code.
User run into this issue on gitter: https://gitter.im/dotnet/orleans?at=5644fae396589f43386726a7

Provide better and more explicit error message upon wrong usage of GrainFactory.

---

src/Orleans/Serialization/BuiltInTypes.cs
src/Orleans/Serialization/SerializationManager.cs
src/TesterInternal/General/BuiltInSerializerTests.cs

Added <code>ReadOnlyCollection</code> and <code>ReadOnlyDictionary</code> built in serialization.

Read only collections built in serialization

---

src/Orleans/Runtime/AsynchAgent.cs

When we create agent threads (internal Orleans runtime threads), we register each thread to `AppDomain.CurrentDomain.DomainUnload` event (https://github.com/dotnet/orleans/blob/master/src/Orleans/Runtime/AsynchAgent.cs#L76), so in case we somehow forget to cleanup this thread we will do it in the `DomainUnload` handler.
However, we never unregister the thread from this event. This means that even if the thread was successfully stopped and cleaned up, its `DomainUnload` handler will be called when the domain is unloaded (potentially much much later, maybe when the process is stopped).
In the short term this late `DomainUnload` caused a double call to `AgentThread.Stop()`. 
More severely, I suspect (did not verify it) that this also caused memory and thread leakage. The agent thread was …

Unregister agent threads from DomainUnload event when stopped.

---

Getting-Started-With-Orleans/Observers.md
Step-by-step-Tutorials/A-Service-is-a-Collection-of-Communicating-Actors.md
Step-by-step-Tutorials/Interaction-with-Libraries-and-Services.md
index.md

Updated a few doc pages in step by step part.
Also according to issue:#1000 I added topics of getting started to the main page as the first step.

Updated doc pages

---

src/Build.cmd
src/Build/GlobalAssemblyInfo.fs
src/Orleans.sln
src/TestFSharp/Grains.fs
src/TestFSharp/TestFSharp.fsproj
src/TestFSharp/Types.fs
src/TestFSharp/packages.config
src/Tester/FSharpGrainTests.cs
src/Tester/SerializationTests.FSharpTypes.cs
src/Tester/Tester.csproj
src/Tester/packages.config

See #1056 and #1057 for background information

Repro for #1056 -replaces #1057

---

src/Orleans/Async/TaskExtensions.cs

Addresses #1074; implemented suggested by @ReubenBond  approach.

Optimization for TaskExtensions.Box

---

src/Orleans/Logging/TraceLogger.cs

Related to #368. Also increased  .Net framework version to 4.6.

Coreclr compatibility: Process.Handle -> Process.SafeHandle

---

src/OrleansRuntime/Silo/Silo.cs

Fixes #1110.
Start pulling agents that read msgs from queues after bootstrap provider is started.
The stream providers themselves are still loaded and initialized BEFORE bootstrap provider.

Start stream pulling agents after bootstrap provider is started.

---

Who-Is-Using-Orleans.md

trying to create correct pull request

Added Drawboard to the list of companies who is using Orleans

---

src/Orleans/Async/TaskExtensions.cs

Optimized PublicOrleansTaskExtentions.Ignore() to avoid going through the async state machine unnecessarily.
I had this code in my repo for very long, and since this is a heavily used method, I think it's worth optimizing.
I did run some benchmarks, and the improvements in perf are from 2 times to 16 times (depending on whether the preceding task completed synchronously or not, and whether it failed or not). The point is, in all situations I found improvements in perf.
The Benchmark results are as follows:
```
Method |     AvrTime |    StdDev |          op/s |
------------------------ |------------ |---------- |-------------- |
IgnoreUsingAwait | 137.0142 ns | 0.4176 ns |  7,298,515.37 |
IgnoreUsingContinueWith |  14.4233 ns | 0.0593 ns | 69,332,185.35 |
```
```
Method |    AvrTime | …
```

Optimized PublicOrleansTaskExtentions.Ignore()

---

src/Orleans/IDs/SiloAddress.cs

Addresses https://github.com/dotnet/orleans/pull/1109/files#r46889215

Proper implementation of SiloAddress.CompareTo.

---

src/NuGet/Microsoft.Orleans.OrleansTelemetryConsumers.AI.nuspec
src/Orleans.sln
src/OrleansTelemetryConsumers.AI/AITelemetryConsumer.cs
src/OrleansTelemetryConsumers.AI/OrleansTelemetryConsumers.AI.csproj
src/OrleansTelemetryConsumers.AI/Properties/AssemblyInfo.cs
src/OrleansTelemetryConsumers.AI/packages.config

To follow #992 added initial implementation for Azure Application Insights for Orleans Telemetry API.

Azure Application Insights Telemetry Consumer

---

src/TestGrains/ExternalTypeGrain.cs
src/Tester/CodeGenTests/GeneratorGrainTest.cs
src/Tester/DependencyInjectionGrainTests.cs
src/Tester/ExceptionPropagationTests.cs
src/Tester/GenericGrainTests.cs
src/Tester/GrainActivateDeactivateTests.cs
src/Tester/GrainInterfaceHierarchyTests.cs
src/Tester/ObserverTests.cs
src/Tester/SimpleGrainTests.cs

Fix build warnings

---

Getting-Started-With-Orleans/Running-the-Application.md
Samples-Overview/Hello-World.md
Step-by-step-Tutorials/A-Service-is-a-Collection-of-Communicating-Actors.md
Step-by-step-Tutorials/Declarative-Persistence.md
Step-by-step-Tutorials/Interaction-with-Libraries-and-Services.md
Step-by-step-Tutorials/My-First-Orleans-Application.md

More of these same small fixes.

more small doc fixes (OrleansClient -> GrainClient)

---

src/Orleans/Providers/IMemoryStorageGrain.cs
src/OrleansProviders/Storage/MemoryStorage.cs
src/OrleansRuntime/Storage/MemoryStorageGrain.cs
src/TestGrainInterfaces/IInitialStateGrain.cs
src/TestGrains/InitialStateGrain.cs
src/Tester/MemoryStorageProviderTests.cs

When looking into #1129 I looked in our Memory Store and found out it handles etags completely incorrectly. 
Fixed the etag handling in Memory Store.

Correct handling of etags in MemoryStore.

---

src/Orleans/AssemblyLoader/AssemblyLoaderPathNameCriterion.cs
src/Orleans/Logging/TraceLogger.cs
src/Orleans/Streams/Internal/StreamSubscriptionHandleImpl.cs
src/Orleans/Streams/Predicates/FilterPredicateWrapperData.cs
src/OrleansCodeGenerator/SerializerGenerator.cs
src/OrleansCodeGenerator/Utilities/SyntaxFactoryExtensions.cs

Coreclr compatibility: GetUnitializedObject -> Activator.CreateInstance

---

src/Orleans.sln

- OrleansSqlUtils.csproj -> /OrleansSQLUtils.csproj

Fix file name case sensitive bug.

---

src/TestInternalGrains/PersistenceTestGrains.cs

ReentrentGrainWithState does a lot of calls to write state async. 
Of course, concurrent calls from a **Reentrant** Grain could cause etag violations.
Scenario:
Imagine Reentrant grain A gets 2 grain calls that want to change and write its state. The previous state, before those 2 calls arrived, had etag 1.
First write goes out, with the etag 1.
The grain code is calling `await`, allowing the 2nd grain call to go in and execute, issuing the 2nd write, still with the etag 1, since write 1 did not finish yet.
The bug in this test was not revealed until now, since we had a bug in MemoryStore which did not check etag correctly, which was recently fixed via #1141.
The fix, in this test and in general in any Reentrant grain with state is **to serialize state writes: never issue more than one …

Fixed a bug in ReentrentGrainWithState Test, by serializing writes to store from a Reentrant grain.

---

src/Orleans/Core/GrainClient.cs

Currently, `GrainClient.Initialize` will throw an `AggregateException` which can be deeply nested, obscuring the actual cause of initialization failure.
This change flattens and simplifies the exception thrown to give users a chance at understanding & remedying them.

Simplify exceptions thrown from GrainClient.Initialize.

---

src/Orleans/Statistics/CounterStatistic.cs
src/TesterInternal/General/CounterStatisticTests.cs
src/TesterInternal/TesterInternal.csproj

@gabikliot  Hope this time all will work as expected

CounterStatistics improvment

---

src/Orleans/Logging/ErrorCodes.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapterReceiver.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Addresses #1140, comment: https://github.com/dotnet/orleans/issues/1140#issuecomment-165873615

Ignore failed MessagesDeliveredAsync calls.

---

src/Orleans/Serialization/SerializationManager.cs
src/OrleansBondUtils/BondSerializer.cs

modified some code that was using reflection to use compiled expressions.

Convert some reflection-based code to compiled expressions

---

src/Tester/SerializationTests/ProtobufSerializationTests/ProtobufSerializationTests.cs

- Wrong DLL name in [DeploymentItem]

Fix a warning during test run.

---

src/Tester/GrainActivateDeactivateTests.cs
src/TesterInternal/ErrorGrainTest.cs
src/TesterInternal/General/Identifiertests.cs
src/TesterInternal/GrainReferenceTest.cs
src/TesterInternal/StorageTests/PersistenceProviderTests.cs

- "Json" -> "JSON" to match other test case usage.
- Remove "General" tag - single item in category.
- Add tag to untagged test case.

Fix some incorrect test case tags

---

src/OrleansSQLUtils/Storage/DbConnectionFactory.cs

Currently, the code is loading all installed ADO factories, this works well when all factories are functioning properly. While testing in mono, we've encountered a misbehaving factory that caused the silo to crash on start. The change in this PR is to only try to load the requested factory and cache it.

Load ADO factories lazily

---

src/Orleans/Serialization/OrleansJsonSerializer.cs
src/Tester/SerializationTests/SerializationTests.JsonTypes.cs

Nested serialization of Guid with Json serializer.

---

Getting-Started-With-Orleans/Running-the-Application.md

grains are activated transparently, the client doesn't have any notion of create or find for a grain

documentation : the client doesn't create or finds grains

---

src/OrleansRuntime/Catalog/Catalog.cs

Stumbled upon this in a silo log sent to me. Trivial but misleading.

Fixed error message: "AsyncActivate" -> "OnActivateAsync".

---

src/Orleans/Streams/Internal/StreamConsumer.cs

Fixes #1254 (and #1228 which describes the same problem) and hopefully also #1010.
I was able to run the setup from #1254. It did not reproduce the problem on my box by itself (most probably since my laptop is slow with not enough CPUs).
I added `await Taskk.Delay(1000);` to https://github.com/dotnet/orleans/blob/master/src/Orleans/Streams/Internal/StreamConsumer.cs#L69
in between the lines that I suspected the race was and the bug reproduced 100% reliably every time.
The fix is basically 2 lines - change the order and undo on failure.

Fix a race in StreamConsumer.SubscribeAsync.

---

Advanced-Concepts/index.md
Contributing.md
Frequently-Asked-Questions.md

Documentation cleanups following #1264

Documentation cleanups following #1264

---

_includes/menu.html

well, it's getting started. doesn't seem right it is after installation :)

moved gettings-started-guide to top

---

src/Orleans/Configuration/ClusterConfiguration.cs
src/OrleansAzureUtils/Hosting/AzureSilo.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloHost.cs
src/OrleansTestingHost/TestingSiloHost.cs
src/Tester/StreamingTests/ControllableStreamGeneratorProviderTests.cs
src/Tester/StreamingTests/ControllableStreamProviderTests.cs
src/Tester/StreamingTests/EHSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/GeneratedStreamRecoveryTests.cs
src/Tester/StreamingTests/StreamGeneratorProviderTests.cs
src/TesterInternal/ConfigTests.cs
src/TesterInternal/LivenessTests/MembershipTablePluginTests.cs
src/TesterInternal/SchedulerTests/OrleansTaskSchedulerBasicTests.cs

Rename GetConfigurationForNode to GetOrAddConfigurationForNode.
Follow-up for comments in Stream Recovery Tests #1289

GetOrAddConfigurationForNode

---

src/OrleansSQLUtils/Storage/Provider/GrainIdentity.cs
src/OrleansSQLUtils/Storage/Provider/GrainStateMap.cs
src/OrleansSQLUtils/Storage/Provider/IGrainStateMapFactory.cs
src/OrleansSQLUtils/Storage/Provider/WriteEntry.cs

in order to be able to create a IGrainStateMapFactory in non orleans assembly I need these internals to be public.

Allowing for a IGrainStateMapFactory to be created in a external assembly

---

src/OrleansSQLUtils/Storage/Provider/GrainIdentity.cs
src/OrleansSQLUtils/Storage/Provider/GrainStateMap.cs
src/OrleansSQLUtils/Storage/Provider/IGrainStateMapFactory.cs
src/OrleansSQLUtils/Storage/Provider/WriteEntry.cs

Allowing for a IGrainStateMapFactory to be created in a external assembly.
Apply PR #1321 to master branch - cherry picked 16b50d9581e238f5e4d5eebd75fd201137edd5cf

Allowing for IGrainStateMapFactory to be created in a external assembly

---

src/OrleansSQLUtils/CreateOrleansTables_MySql.sql
src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql
src/OrleansSQLUtils/Storage/RelationalOrleansQueries.cs

this should also solve #1341. @veikkoeeva, please take a look.

Sql Scripts - removed two redundancies

---

src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs

Made SerializerGenerationManager non static

---

src/TesterInternal/General/ConsistentRingProviderTests_Silo.cs

We were sometimes not waiting enough for the failures to propagate. This change also makes the tests run much faster in average, albeit sometimes (rarely) waiting a little longer

Fix randomly failing ConsistentRingProvider tests

---

src/Orleans/Logging/TraceLogger.cs

Increment and DecrementMetric methods in Orleans.TraceLogger had same body

---

src/OrleansRuntime/Storage/MemoryStorageGrain.cs

Added missing throw keyword.

---

src/Orleans/AssemblyLoader/AssemblyProcessor.cs
src/Orleans/CodeGeneration/CodeGeneratorManager.cs
src/OrleansRuntime/Silo/Silo.cs

Fix: Azure silo fails to start under debugger

---

src/.nuget/packages.config
src/Orleans/AssemblyLoader/AssemblyProcessor.cs
src/Orleans/CodeGeneration/CodeGeneratorManager.cs
src/TestGrainInterfaces/IJsonEchoGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrainInterfaces/packages.config
src/TestGrains/JsonEchoGrain.cs
src/TestGrains/TestGrains.csproj
src/TestGrains/packages.config
src/TesterInternal/General/InterfaceRules.cs
test/Tester/General/JsonGrainTests.cs
test/Tester/Tester.csproj

- A test case for grains that use JSON JObject parameters for input / output.
- See #1368 for some related background discussion.

JSON Grains - Add test case to validate grains using JSON JObject parameters

---

src/OrleansCodeGenerator/CodeGeneratorCommon.cs

PVS-Studio: double check for the same condition

---

src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs

PVS-Studio: Fixes Double assignment of jsonSettings variable.

---

src/Orleans/Statistics/HistogramValueStatistic.cs
src/Orleans/Statistics/ThreadTrackingStatistic.cs
src/OrleansRuntime/Scheduler/WorkItemGroup.cs

PVS-Studio: Removes in-precise float comparisons.

---

src/Orleans/Configuration/ClientConfiguration.cs

PVS-Studio: Fixes missing CheckGatewayProviderSettings checks.

---

src/Test.cmd
src/TestAll.cmd

Fixed TestAll.cmd script to be able to run Tester's Functional tests in xUnit

Run functionals in xUnit

---

src/TesterInternal/General/ElasticPlacementTest.cs

Fixed Implicit cast from int to double .

---

src/Orleans/Messaging/Message.cs

PVS-Studio: switch statement

---

src/Orleans/IDs/Interner.cs

PVS-Studio: Fixes confusing if-else statement.

---

src/Build/GlobalAssemblyInfo.cs
src/Build/GlobalAssemblyInfo.fs
src/OrleansBondUtils/OrleansBondUtils.csproj
src/OrleansBondUtils/Properties/AssemblyInfo.cs
src/OrleansCodeGenerator/OrleansCodeGenerator.csproj
src/OrleansCodeGenerator/Properties/AssemblyInfo.cs
src/OrleansGoogleUtils/OrleansGoogleUtils.csproj
src/OrleansGoogleUtils/Properties/AssemblyInfo.cs
src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Properties/AssemblyInfo.cs
src/TestInterfaces/Properties/AssemblyInfo.cs
src/TestInterfaces/TestInterfaces.csproj

Updated file versions to match the NuGet version.
Fixed several projects to use GlobalAssemblyInfo.cs.

Cleanup of file and assembly version information

---

src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueStreamProviderUtils.cs
src/OrleansTestingHost/StorageEmulator.cs
test/TestExtensions/TestCategory.cs
test/Tester/StreamingTests/SampleStreamingTests.cs

... and some general cleanup of a few testing utilities

Fix more functionals

---

netci.groovy
src/Build.cmd
src/Test.cmd

Build using MSBuild 14 to support C# 6

---

src/OrleansAzureUtils/Storage/AzureTableDataManager.cs

Use TableOperation.Retrieve instead of query for single entry read

---

src/Orleans/Configuration/OrleansConfiguration.xsd

Added StreamProviders section

---

src/TestFSharp/AssemblyInfo.fs
src/TestInternalGrainInterfaces/ISerializerPresenceTest.cs
src/TestInternalGrainInterfaces/Properties/AssemblyInfo.cs
src/TestInternalGrainInterfaces/TestInternalGrainInterfaces.csproj
src/TestInternalGrainInterfaces/packages.config
src/TestInternalGrains/SerializerPresenceTestGrain.cs
src/TestInternalGrains/TestInternalGrains.csproj
src/TesterInternal/CodeGeneratorTests_KnownAssemblyAttribute.cs
src/TesterInternal/TesterInternal.csproj
src/TesterInternal/packages.config

Tests skipped to pass CI (search for #1424 in the code)

Repro for #1424 - KnownAssemblyAttribute does not generate serializers at runtime

---

src/OrleansCodeGenerator/CodeGeneratorCommon.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs

TypeUtils.GetTypesWithImplementations: validate and use parameter

---

src/Orleans/Messaging/IncomingMessageBuffer.cs

Optimizations maximizing the buffer read size lead to performance regression due to small block side.  These have been reverted.
We no longer network receive buffer if buffer was filled by read.
We adjust buffer after each message read, rather than after reading all messages.

Fixed performance regression in networking

---

src/Orleans/Serialization/OrleansJsonSerializer.cs
src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
src/OrleansAzureUtils/Storage/AzureStorageUtils.cs

...there should be no backward compatibility issues with the table storage provider, possible issues with blob storage.

normalise json serialization between azure storage providers

---

src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Logging/TraceLogger.cs
src/Orleans/Messaging/GatewayClientReceiver.cs
src/Orleans/Messaging/IncomingMessageBuffer.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Statistics/IPerformanceMetrics.cs
src/OrleansAzureUtils/Storage/AzureStorageUtils.cs
src/OrleansAzureUtils/Storage/AzureTableDefaultPolicies.cs
src/OrleansAzureUtils/Storage/RemindersTableManager.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs
src/OrleansRuntime/Messaging/IncomingMessageAcceptor.cs
src/OrleansRuntime/ReminderService/LocalReminderService.cs
src/OrleansRuntime/Silo/Silo.cs
src/TesterInternal/StorageTests/AzureTableErrorCodeTests.cs

The main fix here is https://github.com/sergeybykov/orleans/commit/6c4383971b0f0a48fbc6bb0157739164ce64b681 coupled with https://github.com/sergeybykov/orleans/commit/fc9b85f8e008a1656bf3bb92b367132db8f7e58c.

Cherry-picked fixes for 1.1.3 patch release

---

src/Orleans/AssemblyLoader/AssemblyProcessor.cs
src/Orleans/Serialization/SerializationManager.cs

These improvements are aimed at helping users better diagnose serializer mistakes.
(sorry for empty PR before this)

Serializer registration improvements (small)

---

src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueStreamProviderUtils.cs
src/TesterInternal/ClientInitTests.cs
src/TesterInternal/ConfigTests.cs
src/TesterInternal/StatsTests.cs
src/TesterInternal/StorageTests/PersistenceGrainTests.cs
src/TesterInternal/StreamingTests/AQStreamingTests.cs
src/TesterInternal/StreamingTests/AzureQueueAdapterTests.cs
src/TesterInternal/StreamingTests/HaloStreamSubscribeTests.cs
src/TesterInternal/StreamingTests/SMSStreamingTests.cs
src/TesterInternal/StreamingTests/StreamReliabilityTests.cs
test/Tester/HostedTestClusterBase.cs
test/Tester/StreamingTests/AQSubscriptionMultiplicityTests.cs
test/Tester/StreamingTests/EHImplicitSubscriptionStreamRecoveryTests.cs
test/Tester/StreamingTests/EHSubscriptionMultiplicityTests.cs
test/Tester/StreamingTests/SampleStreamingTests.cs
test/Tester/StreamingTests/StreamFilteringTests.cs

I took a few fixes from #1540 that apply to Functionals in general, not just in xUnit

Fixes to some Functional tests

---

src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs

Fixes https://github.com/dotnet/orleans/issues/1533.

Do not count responses for Activation GC activity.

---

src/Orleans/CodeGeneration/TypeUtils.cs

Fixes https://github.com/dotnet/orleans/issues/1219.

More flexible semantic assembly name comparison.

---

src/Orleans/Streams/PubSub/PubSubPublisherState.cs
src/Orleans/Streams/PubSub/PubSubSubscriptionState.cs

A step in https://github.com/dotnet/orleans/issues/1495 point 2.

Standardize Json serialization of PubSub state.

---

src/TesterInternal/CodeGeneratorTests_KnownAssemblyAttribute.cs
src/TesterInternal/StorageTests/RelationalStoreTests.cs
test/Tester/DuplicateActivationsTests.cs

Updated some remaining MsTest tests to xUnit from #1540 (which were failing the functional build).
Also attempt at fixing 1 randomly failing functional.

Fix functional run issues

---

Who-Is-Using-Orleans.md

Made the page more readable: http://richorama.github.io/orleans/Who-Is-Using-Orleans

converted the 'who is using orleans' table into a more readable list

---

src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
test/TesterInternal/StorageTests/PersistenceGrainTests_AzureTableStore.cs
test/TesterInternal/StorageTests/PersistenceProviderTests.cs

This reverts commit 1d412e4204cda666ef69ebd25be4d03d705537aa.
This is to revert https://github.com/dotnet/orleans/pull/1539/ that broke some of the persistence functionality.

Revert "Allow AzureTableStorage to store data larger than 64 KB"

---

Orleans-Configuration-Guide/Client-Configuration.md
Orleans-Configuration-Guide/Server-Configuration.md

I found that although this samples looks straightforward, it takes some time to figure out and configure both client and silo on azure from code.

Added 2 simple samples on how to configure and run client and silo on azure from code

---

src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
test/TesterInternal/StorageTests/LocalStoreTests.cs
test/TesterInternal/StorageTests/PersistenceGrainTests_AzureTableStore.cs
test/TesterInternal/StorageTests/PersistenceProviderTests.cs

This is basically the PR https://github.com/dotnet/orleans/pull/1539 with the fix https://github.com/dotnet/orleans/pull/1578 and more tests per the suggestions of @jason-bragg

Allow AzureTableStorage to store data larger than 64 KB (v2)

---

src/OrleansAzureUtils/Storage/AzureGatewayListProvider.cs

remove redundant lock in AzureGatewayListProvider

---

src/NuGet/Microsoft.Orleans.CounterControl.nuspec
src/OrleansCounterControl/CounterControl.cs
src/OrleansCounterControl/OrleansCounterControl.csproj
src/OrleansCounterControl/packages.config

fix for NullReferenceExceptions and missing dependencies

CounterControl bug fix

---

src/Orleans/CodeGeneration/CodeGeneratorManager.cs

Commit by Armon Avrahamy <armon.av@gigya-inc.com>
On branch: refs/heads/remove-code-generation-lazy
Regarding issue #1619

Remove usage of Lazy static values to allow GrainClient to run on Mono.

---

src/NuGet/BondSerializerInstall.ps1
src/NuGet/BondSerializerUninstall.ps1
src/Orleans/Serialization/SerializationManager.cs
src/OrleansGoogleUtils/ProtobufSerializer.cs

- bug fix for powershell installer
- scan types for use with external serializers

type registration for serializers

---

test/TesterInternal/StreamingTests/AzureQueueAdapterTests.cs

StreamNamespace wasn't being set correctly in streamId.

Fixed SendAndReceiveFromAzureQueue test.

---

src/OrleansTestingHost/Extensions/TestConfigurationExtensions.cs
test/Tester/StreamingTests/PullingAgentManagementTests.cs
test/Tester/StreamingTests/SMSSubscriptionMultiplicityTests.cs
test/Tester/StreamingTests/StreamFilteringTests.cs
test/Tester/StreamingTests/StreamGeneratorProviderTests.cs
test/TesterInternal/EchoTaskGrainTests.cs
test/TesterInternal/General/BootstrapProviderTests.cs
test/TesterInternal/General/LoggerTest.cs
test/TesterInternal/StreamingTests/StreamLifecycleTests.cs
test/TesterInternal/StreamingTests/StreamReliabilityTests.cs
test/TesterInternal/StreamingTests/StreamTestUtils.cs

Cleanup of some tests, in preparation to the upcoming TestingSiloHost change.

Tests cleanup

---

test/TesterInternal/StorageTests/PersistenceGrainTests.cs

It broke after the latest merged PRs (most likely #1429, but it could be #1610 too). I'll leave it up to @jason-bragg to review and merge

Fixed PersistenceGrainTests

---

src/Orleans.sln
test/TestInterfaces/ClassNotReferencingOrleansTypeDto.cs
test/TestInternalDtosRefOrleans/ClassReferencingOrleansTypeDto.cs
test/TestInternalDtosRefOrleans/Properties/AssemblyInfo.cs
test/TestInternalDtosRefOrleans/TestInternalDtosRefOrleans.csproj
test/TestInternalGrainInterfaces/ISerializerPresenceTest.cs
test/TestInternalGrains/SerializerPresenceTestGrain.cs
test/TesterInternal/CodeGeneratorTests_TakeSerializedData.cs
test/TesterInternal/TesterInternal.csproj

@sergeybykov: This is the new pull request which makes https://github.com/dotnet/orleans/pull/1508 obsolete.

Issue #1480 (https://github.com/dotnet/orleans/issues/1480)

---

src/Orleans/Runtime/GrainReference.cs
src/OrleansCodeGenerator/GrainReferenceGenerator.cs
test/Tester/GenericGrainTests.cs
test/Tester/ProviderTests.cs
test/TesterInternal/GrainReferenceCastTests.cs

Reverting #1604 per https://github.com/dotnet/orleans/issues/1624.
I opened https://github.com/dotnet/orleans/issues/1655 and https://github.com/dotnet/orleans/issues/1656 for the failing tests that I skipped here.
@dVakulen What I don't understand yet is why contrary to what you said in https://github.com/dotnet/orleans/pull/1625 `Generic_CastGenericInterfaceToNonGenericInterfaceBeforeActivation` is still failing - https://github.com/dotnet/orleans/issues/1656. Did I miss something?

Revert #1604

---

Getting-Started-With-Orleans/Observers.md

Just saw an issue and thought I'd contribute a quick fix. :-)

Minor spelling correction to the word look.

---

src/OrleansSQLUtils/CreateOrleansTables_MySql.sql
src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql
src/OrleansSQLUtils/Messaging/SqlMembershipTable.cs
src/OrleansSQLUtils/OrleansSQLUtils.csproj
src/OrleansSQLUtils/ReminderService/SqlReminderTable.cs
src/OrleansSQLUtils/Storage/DbConstantsStore.cs
src/OrleansSQLUtils/Storage/DbExtensions.cs
src/OrleansSQLUtils/Storage/DbStoredQueries.cs
src/OrleansSQLUtils/Storage/RelationalOrleansQueries.cs
src/OrleansSQLUtils/Storage/RelationalStorage.cs
src/OrleansSQLUtils/Storage/RelationalStorageExtensions.cs
src/OrleansSQLUtils/Storage/SqlStatisticsPublisher.cs
test/TesterInternal/ConnectionStringFixture.cs
test/TesterInternal/MembershipTests/AzureMembershipTableTests.cs
test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs
test/TesterInternal/MembershipTests/MySqlMembershipTableTests.cs
test/TesterInternal/MembershipTests/SqlServerMembershipTableTests.cs
test/TesterInternal/MembershipTests/ZookeeperMembershipTableTests.cs
test/TesterInternal/RemindersTest/AzureRemindersTableTests.cs
test/TesterInternal/RemindersTest/MySqlRemindersTableTests.cs
test/TesterInternal/RemindersTest/ReminderTableTestsBase.cs
test/TesterInternal/RemindersTest/SqlServerRemindersTableTests.cs
test/TesterInternal/SqlStatisticsPublisherTests/MySqlStatisticsPublisherTests.cs
test/TesterInternal/SqlStatisticsPublisherTests/SqlServerStatisticsPublisherTests.cs
test/TesterInternal/SqlStatisticsPublisherTests/SqlStatisticsPublisherTestsBase.cs
test/TesterInternal/StorageTests/RelationalStoreTests.cs
test/TesterInternal/TesterInternal.csproj

This continues the work started with #1488. 
The main changed are:
* Minimized the SQL scripts (MySQL & SQL Server), fixed some minor bugs along the way.
* Refactored `RelationalOrleansQueries` to be short and readable.
I hope @veikkoeeva will have some time to review.

another relational storage refactoring

---

src/Orleans/Configuration/ConfigurationExtensions.cs
src/Orleans/Streams/Internal/IStreamGrainExtensions.cs
src/Orleans/Streams/Internal/StreamConsumerExtension.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProducer.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProducerExtension.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs
test/TestGrainInterfaces/IStreamingImmutabilityTestGrain.cs
test/TestGrainInterfaces/TestGrainInterfaces.csproj
test/TestInternalGrains/StreamingImmutabilityTestGrain.cs
test/TestInternalGrains/TestInternalGrains.csproj
test/TesterInternal/Config_StreamProviders.xml
test/TesterInternal/StreamingTests/SMSStreamingTests.cs
test/TesterInternal/StreamingTests/SingleStreamTestRunner.cs

Adding an attribute `EnforceItemsImmutability` for SimpleMessageStream with a default value of `true`. Also adding a unit test to validate this behavior.

Fixes #1645 by introducing ENFORCE_ITEMS_IMMUTABILITY

---

src/NuGet/Microsoft.Orleans.OrleansConsulUtils.nuspec
src/OrleansConsulUtils/OrleansConsulUtils.csproj
src/OrleansConsulUtils/packages.config

Updates the Consul package reference to latest 0.6.4.1 to try to get this into 1.2.0 as per https://github.com/dotnet/orleans/pull/1267#issuecomment-213013532.

Update Consul package to latest

---

src/OrleansVSTools/OrleansVSTools/source.extension.vsixmanifest

Fixes https://github.com/dotnet/orleans/issues/1706.

Change version of VSIX from "1.2.0-beta" to "1.2.0".

---

src/Test.cmd
src/TestAll.cmd

This is to be able to fail the build in VSO.

Set exit code on failing tests

---

src/OrleansSQLUtils/Storage/DbStoredQueries.cs

newbie mistake
this PR replaces #1733 for #1726

allow for extraneous keys in OrleanQuery table

---

src/NuGet/Microsoft.Orleans.OrleansProviders.nuspec
src/NuGet/Microsoft.Orleans.OrleansRuntime.nuspec
src/OrleansDependencyInjection/OrleansDependencyInjection.csproj
src/OrleansProviders/OrleansProviders.csproj
src/OrleansProviders/Storage/MemoryStorage.cs
src/OrleansProviders/Storage/ShardedStorageProvider.cs
src/OrleansRuntime/OrleansRuntime.csproj

turn on XML doc creation and add xml files to nuspecs

Xml doc files for OrleansRuntime and OrleansProvider nupkgs

---

src/OrleansRuntime/ReminderService/LocalReminderService.cs

This is a proposed fix for #1746.
I've yet to test it with multiple silos, first I wanted to get some input.

Fix race condition bugs in LocalReminderService

---

src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/SystemTargetInterfaces/IMembershipTable.cs
src/OrleansRuntime/ReminderService/LocalReminderService.cs
test/Tester/GenericGrainTests.cs

Suggested fixes to include in v1.2.1.

Suggested fixes for v1.2.1

---

Runtime-Implementation-Details/Runtime-Tables.md

Corrected a couple of misspellings.

Spelling correction on Runtime-Tables.md

---

Samples/Chirper/ChirperGrains/ChirperAccount.cs

... not being able to load graph due to eTag violations

Fixed issue with Chirper sample 

---

Step-by-step-Tutorials/My-First-Orleans-Application.md

Clarification in the My-First-Orleans-Application instructions

Small clarification on key types

---

src/OrleansCodeGenerator/Utilities/SyntaxFactoryExtensions.cs
src/OrleansProviders/Storage/MemoryStorage.cs
src/OrleansProviders/Storage/MemoryStorageWithLatency.cs
src/OrleansProviders/Storage/ShardedStorageProvider.cs
src/OrleansProviders/Streams/Common/PooledCache/CachedMessagePool.cs
src/OrleansProviders/Streams/Common/PooledCache/FixedSizeObjectPool.cs
src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/MultiClusterNetwork/IGossipChannel.cs
src/OrleansRuntime/Silo/IStartupBuilder.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloHost.cs
src/OrleansRuntime/Storage/MemoryStorageGrain.cs
src/OrleansTestingHost/Extensions/ConfigurationExtensions.cs
src/OrleansTestingHost/Extensions/TestConfigurationExtensions.cs

- Fix some minor xml code doc glitches causing build warnings.
- Fix some other minor non-functional code quality warnings.
- TODO: Also lots of other missing code docs on public API artifacts in these projects:
- OrleansAzureUtils
- OrleansProviders
- OrleansServiceBus
- OrleansTestingHost
- OrleansZooKeeperUtils

Fix some minor xml code doc glitches causing build warnings.

---

src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Catalog/GrainCreator.cs

Updated  #1792 to include stateful grains.

Test Helpers - Stateful Grains

---

Orleans-Streams/index.md
Step-by-step-Tutorials/A-Service-is-a-Collection-of-Communicating-Actors.md
Step-by-step-Tutorials/Cloud-Deployment.md
Step-by-step-Tutorials/Custom-Storage-Providers.md
Step-by-step-Tutorials/Declarative-Persistence.md
Step-by-step-Tutorials/Minimal-Orleans-Application.md
Step-by-step-Tutorials/My-First-Orleans-Application.md
Step-by-step-Tutorials/Running-in-a-Stand-alone-Silo.md
Step-by-step-Tutorials/Unit-Testing-Grains.md

There were some minor issues in the step-by-step tutorials, which are fixed in the pull-request.

Updated step-by-step tutorials

---

src/NuGet/Microsoft.Orleans.OrleansServiceBus.nuspec
src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/packages.config
test/Tester/Tester.csproj
test/Tester/packages.config

From 3.2.0 which has become unlisted.

ServiceBus upgrade to 3.2.2

---

src/Orleans/Statistics/RuntimeStatisticsGroup.cs

Fixes a bug reported in https://github.com/dotnet/orleans/commit/f1c47d2d8cd8b83792c0ec658421a1315372b32c#commitcomment-17707777.

Fixed a bug of using 11204 instead of 1024 in RuntimeStatisticsGroup.

---

src/Orleans/IDs/GuidId.cs

To help investigate https://github.com/dotnet/orleans/issues/1819#issuecomment-224766547.

Print full Guid in GuidId.

---

Advanced-Concepts/Relational-Storage-Design-Rationale.md
Advanced-Concepts/index.md

The current documentation lacks explanation of the goals and the factors of the of the relational storage sub-system, [OrleansSQLUtils](https://github.com/dotnet/orleans/tree/master/src/OrleansSQLUtils), design. This lack of documentation makes it needlessly difficult to:
1. Realize the potential use cases in one’s problem domain.
2. Increases effort to make a contribution.
This patch addresses these problems and partially addresses #1810.

Add relational storage design rationale

---

src/Orleans/Runtime/IClientObserverRegistrar.cs
src/OrleansRuntime/GrainDirectory/ClientObserverRegistrar.cs
src/OrleansRuntime/Silo/Silo.cs

Fix to https://gitter.im/dotnet/orleans?at=5758edb72eaa837d71e7b64a.

Fixed a NullRefExc bug in ClientObserverRegistrar.

---

Step-by-step-Tutorials/Declarative-Persistence.md

Just removed the inheritance which wasn't needed anymore. The text did not reference it so it was partially updated I guess.

Fixed the code in the declarative persistence documentation page.

---

src/Orleans/Statistics/CounterStatistic.cs
src/Orleans/Statistics/IPerformanceMetrics.cs
src/Orleans/SystemTargetInterfaces/IMembershipTable.cs
src/Orleans/SystemTargetInterfaces/IReminderTable.cs

move Runtime-Tables.md to code

---

src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Catalog/Catalog.cs

Fix to https://github.com/dotnet/orleans/issues/1837.

Do not deactivate Stateless Workers upon grain directory partition shutdown.

---

test/TesterInternal/General/GrainPlacementTests.cs

This change adds some additional test cases for failure modes around [PreferLocalPlacement] grains. They use the existing `PreferLocalPlacementTestGrain` already in the code base.
- Test case PreferLocalPlacementGrain_ShouldMigrateWhenHostSiloKilled
- Test case PreferLocalPlacementGrain_ShouldNotMigrateWhenOtherSiloKilled
I think these test cases should always work ok, but they currently they only work intermittently.
__i believe these failures are being caused by some unrelated bug(s) in gateway routing that I would like to check the community wisdom about.__
The underlying problem looks like the test client is trying to route the message through the gateway on the silo that was killed, but does throws back the underlying `SiloUnavailableException` when it cannot communicate with that …

Testing for PreferLocalPlacement grain failure handling

---

Samples-Overview/Hello-World.md
Step-by-step-Tutorials/Cloud-Deployment.md
Step-by-step-Tutorials/Concurrency.md
Step-by-step-Tutorials/Declarative-Persistence.md
Step-by-step-Tutorials/Front-Ends-for-Orleans-Services.md
Step-by-step-Tutorials/Interaction-with-Libraries-and-Services.md
Step-by-step-Tutorials/Unit-Testing-Grains.md

Changed things to Guid from long
Fixed typos
data is declared incorrectly in AddDirectReport()
Fixed some improper code

Some step by step tutorial fixes

---

src/Orleans/Logging/LogManager.cs
src/Orleans/Logging/Logger.cs
src/Orleans/Logging/LoggerExtensions.cs
src/Orleans/Logging/LoggerImpl.cs
src/Orleans/Streams/QueueAdapters/IQueueAdapter.cs
src/Orleans/Streams/QueueAdapters/IQueueAdapterFactory.cs
src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
src/OrleansProviders/Streams/Generator/GeneratorAdapterFactory.cs
src/OrleansProviders/Streams/Generator/GeneratorPooledCache.cs
src/OrleansServiceBus/ErrorCode.cs
src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Providers/Streams/EventHub/EventDataExtensions.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubQueueCache.cs
src/OrleansTestingHost/OrleansTestingHost.csproj
src/OrleansTestingHost/Utils/NoOpTestLogger.cs
test/Tester/TestStreamProviders/EventHub/StreamPerPartitionEventHubStreamProvider.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs

This addresses log/metrics logging infrastructure in stream provider as well as some high priority cases.  More error logging will likely be needed.  
Added logging and metrics from eventhub receiver.
Added logging from eventhub message cache.

EventHub stream provider logging/monitoring

---

Orleans-Streams/index.md

Added how to consume streams from the client

Fixed Stream Sample

---

Step-by-step-Tutorials/Declarative-Persistence.md
index.md

Added two small sections to declarative persistence and fixed a spelling error in index.md

Documentation improvement regarding declarative persistence

---

src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/OrleansZooKeeperUtils/OrleansZooKeeperUtils.csproj
src/OrleansZooKeeperUtils/packages.config

* Support .NET Standard 1.3
* Fixed a bug found in #1917

update ZooKeeperNetEx to 3.4.8.5

---

src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs

Begin reading from most recent EventHub data using latest offset rather than UtcNow

Begin reading from most recent EventHub data using latest offset

---

src/OrleansCodeGenerator/RoslynCodeGenerator.cs

See discussion in #1888. Minor cleanup for clarity
cc @jdom

Refactor ConsiderType to make parameters clearer

---

src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs

Minor cleanup (this one compiles :stuck_out_tongue:) mostly to fix some naming.
Two fields moved to RoslynCodeGenerator since that's the only place they are used.

Fix field name casing in SerializerGenerationManager

---

src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs

Flow control wasn't working because calculations were being done per read, not leaving enough time for consumers to accumulate enough meaningful input.
Now backpressure accumulates over two second intervals.

Fixed EventHub stream provider flow control.

---

src/Orleans/Core/GrainExtensions.cs
src/Orleans/IDs/GrainId.cs

In order to make primary key discovery a bit easier I exposing IsLongKey property

Expose property IsLongKey for IAddressable

---

Samples/Tutorial.Minimal/GrainCollection/GrainCollection.csproj
Samples/Tutorial.Minimal/GrainCollection/HelloGrain.cs
Samples/Tutorial.Minimal/GrainCollection/Properties/AssemblyInfo.cs
Samples/Tutorial.Minimal/GrainCollection/app.config
Samples/Tutorial.Minimal/GrainCollection/packages.config
Samples/Tutorial.Minimal/GrainInterfaces/GrainInterfaces.csproj
Samples/Tutorial.Minimal/GrainInterfaces/IHello.cs
Samples/Tutorial.Minimal/GrainInterfaces/Properties/AssemblyInfo.cs
Samples/Tutorial.Minimal/GrainInterfaces/app.config
Samples/Tutorial.Minimal/GrainInterfaces/packages.config
Samples/Tutorial.Minimal/Host/App.config
Samples/Tutorial.Minimal/Host/Host.csproj
Samples/Tutorial.Minimal/Host/OrleansConfiguration.xml
Samples/Tutorial.Minimal/Host/Program.cs
Samples/Tutorial.Minimal/Host/Properties/AssemblyInfo.cs
Samples/Tutorial.Minimal/Host/packages.config
Samples/Tutorial.Minimal/Orleans.sln

Basic functioning Orleans application described in tutorial http://dotnet.github.io/orleans/Step-by-step-Tutorials/Minimal-Orleans-Application.

Porting OrleansContrib/Orleans.Tutorials.Minimal

---

src/Orleans/Timers/SafeTimerBase.cs

https://github.com/dotnet/orleans/pull/1951#issuecomment-233183132

Remove timer's logger allocations

---

Samples/Presence/1.Demo Start Silo.cmd
Samples/TicTacToe/Host/Host.csproj
Samples/TicTacToe/Host/packages.config
Samples/TicTacToe/OrleansXO.Azure/TicTacToe.Azure.ccproj
Samples/TicTacToe/OrleansXO.GrainInterfaces/TicTacToe.GrainInterfaces.csproj
Samples/TicTacToe/OrleansXO.GrainInterfaces/packages.config
Samples/TicTacToe/OrleansXO.Grains/TicTacToe.Grains.csproj
Samples/TicTacToe/OrleansXO.Grains/packages.config
Samples/TicTacToe/OrleansXO.Web/TicTacToe.Web.csproj
Samples/TicTacToe/OrleansXO.Web/packages.config
Samples/TicTacToe/OrleansXO.WorkerRole/TicTacToe.WorkerRole.csproj
Samples/TicTacToe/OrleansXO.WorkerRole/packages.config
Samples/TicTacToe/TicTacToe.sln

- Fix Presense Service silo startup script
- Upgrade TicTacToe to Azure SDK 2.8 and update Orleans packages

Small fixes in samples:

---

Advanced-Concepts/Interceptors.md

Original PR was against the wrong branch

Fixed code formatting in the interceptors page.

---

src/NuGet/Microsoft.Orleans.OrleansAzureUtils.nuspec
src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansAzureUtils/app.config
src/OrleansAzureUtils/packages.config
src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/app.config
src/OrleansServiceBus/packages.config
test/Tester/App.config
test/Tester/Tester.csproj
test/Tester/packages.config
test/TesterInternal/TesterInternal.csproj
test/TesterInternal/packages.config

Update to WindowsAzure.Storage 7.0.0

---

src/OrleansCounterControl/OrleansCounterControl.csproj
src/OrleansCounterControl/packages.config

Fix some dependencies:
- removed unneeded dependencies in OrleansCounterControl
- fixed several issues in OrleansVSTools

Fix package dependencies

---

src/NuGet/Microsoft.Orleans.Client.nuspec
src/NuGet/Microsoft.Orleans.Core.nuspec
src/NuGet/Microsoft.Orleans.CounterControl.nuspec
src/NuGet/Microsoft.Orleans.EventSourcing.nuspec
src/NuGet/Microsoft.Orleans.OrleansAzureUtils.nuspec
src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.Build.nuspec
src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.nuspec
src/NuGet/Microsoft.Orleans.OrleansHost.nuspec
src/NuGet/Microsoft.Orleans.OrleansManager.nuspec
src/NuGet/Microsoft.Orleans.OrleansProviders.nuspec
src/NuGet/Microsoft.Orleans.OrleansRuntime.nuspec
src/NuGet/Microsoft.Orleans.OrleansServiceBus.nuspec
src/NuGet/Microsoft.Orleans.OrleansTelemetryConsumers.AI.nuspec
src/NuGet/Microsoft.Orleans.OrleansTelemetryConsumers.NewRelic.nuspec
src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/NuGet/Microsoft.Orleans.Serialization.Bond.nuspec
src/NuGet/Microsoft.Orleans.Server.nuspec
src/NuGet/Microsoft.Orleans.Templates.Grains.nuspec-NoSymbols
src/NuGet/Microsoft.Orleans.Templates.Interfaces.nuspec-NoSymbols
src/NuGet/Microsoft.Orleans.TestingHost.nuspec

Just update the nuspecs to use the new icons from #1989

Updated all nuspec to use new icon.

---

src/NuGet/CreateOrleansPackages.bat

Fix for #1984 using powershell to get the date

Make CreateOrleansPackages.bat work on non en-US locale

---

src/OrleansRuntime/GrainDirectory/GrainDirectoryPartition.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs

The check for silo validity is already being performed at https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/GrainDirectory/GrainDirectoryPartition.cs#L342

Remove Addresses new list allocations

---

README.md

Context: https://github.com/dotnet/orleans/pull/2016#issuecomment-237547121

Change readme.md header style

---

Prerequisites.md
Runtime-Implementation-Details/Cluster-Management.md

Added AWS docs for both cluster management and pre-req pages.

More Docs on AWS

---

test/TesterInternal/ActivationsLifeCycleTests/DeactivateOnIdleTests.cs
test/TesterInternal/TesterInternal.csproj

Migrate the remaining activation tests from VSO

More activation tests

---

src/OrleansAWSUtils/Storage/DynamoDBStorage.cs
test/Tester/MembershipTests/LivenessTests.cs
test/TesterInternal/HostedTestClusterBase.cs
test/TesterInternal/MembershipTests/DynamoDBMembershipTableTest.cs
test/TesterInternal/RemindersTest/DynamoDBRemindersTableTests.cs
test/TesterInternal/StorageTests/AWSUtils/AWSTestConstants.cs
test/TesterInternal/StorageTests/AWSUtils/Base_PersistenceGrainTests_AWSStore.cs
test/TesterInternal/StorageTests/AWSUtils/DynamoDBStorageProviderTests.cs
test/TesterInternal/StorageTests/AWSUtils/DynamoDBStorageStressTests.cs
test/TesterInternal/StorageTests/AWSUtils/DynamoDBStorageTestFixture.cs
test/TesterInternal/StorageTests/AWSUtils/DynamoDBStorageTests.cs
test/TesterInternal/StorageTests/AWSUtils/PersistenceGrainTests_AWSDynamoDBStore.cs
test/TesterInternal/StorageTests/AWSUtils/UnitTestDynamoDBStorage.cs
test/TesterInternal/StreamingTests/SQSAdapterTests.cs
test/TesterInternal/StreamingTests/SQSStreamTests.cs

AWS Tests now skippable

---

src/Documentation/Runtime-Implementation-Details/Relational-Storage.md

Added missing /Documentation/ to some broken links

---

src/OrleansRuntime/Silo/SiloHost.cs
test/Tester/SiloInitializationTests.cs
test/Tester/Tester.csproj

Fixes #2119 and adds a simple test to demonstrate the issue.

Fix #2119 by allowing full uninitialization in SiloHost

---

README.md

Fix doc links in readme.md.

---

src/OrleansGoogleUtils/ProtobufSerializer.cs

dynamic has a bad performance......

decode protobuff using MessageParser, not dynamic

---

.gitignore
src/OrleansRuntime/Catalog/ActivationCollector.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Storage/MemoryStorageGrain.cs

These are small fixes in preparation for the .NET Standard projects

Cleanup in preparation for .NET Standard

---

src/Orleans/Logging/LoggerExtensions.cs
src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
src/OrleansProviders/Streams/Memory/MemoryAdapterFactory.cs
src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Providers/Streams/EventHub/DefaultEventHubReceiverMonitor.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubReceiverMonitor.cs
src/OrleansTestingHost/TestStorageProviders/FaultInjectionStorageProvider.cs

Cleaned up EventHub receiver metrics reporting and put reporting behind an abstraction.

EventHub receiver metrics reporting abstraction

---

test/TestServiceFabric/OrleansCommunicationListenerTests.cs
test/TestServiceFabric/TestServiceFabric.csproj

Thanks for pointing this out, @jdom

Add ServiceFabric category to TestServiceFabric tests

---

src/Tutorials/toc.yml

Articles are now on the right level, in the right order and with the right name.

Synchronized Tutorials TOC with the article

---

src/OrleansProviders/Streams/Memory/IMemoryStreamQueueGrain.cs
src/OrleansProviders/Streams/Memory/MemoryAdapterConfig.cs
src/OrleansProviders/Streams/Memory/MemoryAdapterFactory.cs
src/OrleansProviders/Streams/Memory/MemoryEventData.cs
src/OrleansProviders/Streams/Memory/MemoryPooledCache.cs
src/OrleansProviders/Streams/Memory/MemoryStreamQueueGrain.cs
test/Tester/StreamingTests/MemoryStreamProviderClientTests.cs

Added XML comments for memory stream provider related files.

Added XML comments for memory stream provider related files.

---

src/OrleansZooKeeperUtils/ZooKeeperBasedMembershipTable.cs

I just copied comments from the interface, since the documentation doesn't support inheritance :(

Add XML comments in ZooKeeperBasedMembershipTable

---

index.html

Build the documentation for the index page.

Rebuilt index page documentation

---

src/NuGet/Microsoft.Orleans.Core.nuspec
src/NuGet/Microsoft.Orleans.CounterControl.nuspec
src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.nuspec

Updated nuspec files to match versions of codegen related NuGets in #2205.

Updated nuspec files to match versions of codegen related NuGets in #2205

---

src/Parallel-Tests.ps1
src/Test.cmd
test/Tester/Tester.csproj
test/TesterInternal/TesterInternal.csproj
test/TesterInternal/TestingHost/TestingSiloHostTests.cs

Using background jobs to start xunit console, one per test assembly.

Add powershell script to run tests in parallel in build

---

test/Tester/SerializationTests/SerializationTests.DifferentTypes.cs
vNext/.nuget/NuGet.Config
vNext/.nuget/packages.config
vNext/src/Orleans.vNext.sln
vNext/test/NonSiloTests/Orleans.NonSiloTests.csproj
vNext/test/NonSiloTests/project.json
vNext/test/TestExtensions/TestExtensions.csproj
vNext/test/TestExtensions/project.json

Added plumbing needed by other test projects too

Add test project for non-Silo tests in .NET Standard

---

src/OrleansCodeGenerator/GrainMethodInvokerGenerator.cs

When generating `IGrainMethodInvoker.Invoke` methods, don't emit `.Box()` calls for grain methods which already return `Task<object>`, just pass the result as-is.

Invoker codegen: methods returning Task<object> do not need Box() calls

---

vNext/src/OrleansCodeGenerator/project.json

To copy the update made in the main solution

Update Roslyn dependency in vNext

---

src/Orleans/Serialization/SerializationManager.cs

This PR fixes an issue with enum serialization, allowing enums which are backed by 64bit fields (long, ulong) to be serialized.
Currently, serialization assumes enums are backed by 32bit ints.
Perhaps it could be optimized by registering a specialized serializer for each enum type as they're discovered.

Support serialization of enums backed by 64bit fields

---

src/Orleans/Core/GrainCasterFactory.cs
vNext/src/Orleans/Orleans.csproj
vNext/src/OrleansRuntime/project.json

Compiling broke after changes from #2238

Fix vNext solution

---

src/OrleansRuntime/GrainDirectory/GrainDirectoryPartition.cs

Due to large amount of operations under the lock <code>LookUpActivations</code> is one of the main points of contention.

Remove contention point in GrainDirectoryPartition

---

src/OrleansAzureUtils/Hosting/AzureSilo.cs
src/OrleansGoogleUtils/ProtobufSerializer.cs
test/Tester/SerializationTests/ProtobufSerializationTests/ProtobufSerializationTests.cs

Two cherry-picked commits to include in 1.3.0 final

Two cherry-picked commits to include in 1.3.0 final

---

src/Orleans/Configuration/MessagingConfiguration.cs

Fix error message when type in <FallbackSerializationProvider type="..."/> cannot be loaded.

Fix error message when type in FallbackSerializationProvider cannot be loaded.

---

src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Placement/IPlacementContext.cs
src/OrleansRuntime/Placement/PreferLocalPlacementDirector.cs

this is intended to fix the problems described in issue #2272.

Make PreferLocalPlacement revert to RandomPlacement on non-active silos

---

test/Benchmarks/OrleansBenchmarks/App.config

Forgot to add this initially, got tired of adding it ever since.

Adjust benchmarks app configuration

---

src/Documentation/Advanced-Concepts/Interceptors.md

Documents have been enhanced to show how to workaround issue #1865.

Issue #1865: Documentation: "exception conversion" using interceptors.

---

test/Tester/Forwarding/ShutdownSiloTests.cs
test/Tester/Tester.csproj

Adding test to reproduce forward issue

---

src/OrleansRuntime/Messaging/IncomingMessageAcceptor.cs

Logging durring error handling in networking layer could request the enpoint from a disposed socket, causing silo to cycle.
We now store the enpoint in the connection context durring socket assignment and use that value for error logging.

Object Disposed exception in networking layer.

---

src/Orleans/Runtime/RequestContext.cs

Addresses #2197. 
A couple of references: [AsyncLocal tests](https://github.com/dotnet/corefx/blob/master/src/System.Threading/tests/AsyncLocalTests.cs), [AsyncLocal backing storage structure](http://referencesource.microsoft.com/#mscorlib/system/threading/executioncontext.cs,189).

Replace CallContext.LogicalSetData with AsyncLocal

---

test/TesterInternal/General/ConsistentRingProviderTests_Silo.cs
test/TesterInternal/General/ElasticPlacementTest.cs
test/TesterInternal/General/GrainPlacementTests.cs
test/TesterInternal/General/LoadSheddingTest.cs
test/TesterInternal/HostedTestClusterBase.cs
test/TesterInternal/StreamingTests/AQStreamingTests.cs
test/TesterInternal/StreamingTests/SQSStreamTests.cs
test/TesterInternal/StreamingTests/StreamLifecycleTests.cs
test/TesterInternal/StreamingTests/StreamLimitTests.cs
test/TesterInternal/StreamingTests/StreamReliabilityTests.cs
test/TesterInternal/StreamingTests/StreamTestUtils.cs

Next installment of #2232 
changes HostedTestClusterPerTest from TestSiloHost to Testcluster.

HostedTestClusterPerTest to TestCluster

---

src/OrleansProviders/Storage/HierarchicalKeyStore.cs
test/TestExtensions/DefaultClusterFixture.cs
vNext/src/Orleans.vNext.sln
vNext/src/OrleansProviders/OrleansProviders.csproj
vNext/src/OrleansProviders/Properties/AssemblyInfo.cs
vNext/src/OrleansProviders/project.json
vNext/test/TestExtensions/TestExtensions.csproj

fixed DefaultClusterFixture.cs
port over OrleansProviders project to vNext

port over OrleansProviders project to vNext

---

src/Orleans/Core/Grain.cs

As described in Issue #2337, provide either default behavior or useful exceptions when IGrainRuntime or IGrainIdentity are null either because of using the default constructor or passing null to the constructor that sets them (only applies in the context of unit testing).

Provide better handling of null GrainRuntime in Grain code

---

src/Orleans/Providers/IStorageProvider.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeData.cs

Easy to miss. @jdom's work to enable vNext sln builds in CI will help us avoid this in future ☺

Fix breakages in .NET Standard build

---

src/OrleansSQLUtils/OrleansSQLUtils.csproj
src/OrleansSQLUtils/Storage/AdoNetConfigurationExtensions.cs

The ADO.NET functionality should utilities such
as some other providers (e.g. AzureUtils).

Adds helper methods to ease ADO.NET configuration

---

src/OrleansSQLUtils/CreateOrleansTables_MySql.sql

addresses the first part of https://github.com/dotnet/orleans/pull/2288#issuecomment-254070763.
Tested on MySql 5.6.34 and 5.7.15

MySQL Script: Minor syntax tweak to support previous server versions

---

src/Documentation/Getting-Started-With-Orleans/Grain-Persistence.md

<code>IStorageProvider</code> usage example has been updated too.

Remove usage of obsolete GrainState

---

src/Documentation/Advanced-Concepts/StatelessWorker.md

It's invalid and looks messy - good docs = good impression :-)

Removing class braces.

---

src/Orleans/IDs/JenkinsHash.cs
src/Orleans/IDs/SiloAddress.cs
src/Orleans/IDs/StreamId.cs
src/Orleans/IDs/UniqueKey.cs
src/Orleans/Runtime/HashRing.cs
src/Orleans/Serialization/ILBasedSerializer.cs
src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs
src/OrleansProviders/Streams/Memory/MemoryAdapterFactory.cs
src/OrleansSQLUtils/Storage/Provider/OrleansDefaultHasher.cs
test/NonSiloTests/General/Identifiertests.cs

Modify JenkinsHash to be stateless.

Modify JenkinsHash to be stateless.

---

src/Orleans/IDs/JenkinsHash.cs
src/Orleans/IDs/SiloAddress.cs
src/Orleans/IDs/StreamId.cs
src/Orleans/IDs/UniqueKey.cs
src/Orleans/Runtime/HashRing.cs
src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs
src/OrleansProviders/Streams/Memory/MemoryAdapterFactory.cs
src/OrleansRuntime/Streams/LoadShedQueueFlowController.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql
src/OrleansSQLUtils/Storage/Provider/AdoGrainKey.cs
src/OrleansSQLUtils/Storage/Provider/AdoNetStorageProvider.cs
src/OrleansSQLUtils/Storage/Provider/IStorageHashPicker.cs
src/OrleansSQLUtils/Storage/Provider/OrleansDefaultHasher.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
test/TesterInternal/General/Identifiertests.cs
test/TesterInternal/StorageTests/AWSUtils/DynamoDBStorageProviderTests.cs
test/TesterInternal/StorageTests/Relational/AdotNetProviderFunctionalityTests.cs
test/TesterInternal/StorageTests/Relational/CommonStorageTests.cs
test/TesterInternal/StorageTests/Relational/MySqlStorageTests.cs
test/TesterInternal/StorageTests/Relational/RelationalStorageTests.cs
test/TesterInternal/StorageTests/Relational/SqlServerStorageTests.cs
test/TesterInternal/TesterInternal.csproj

These are two fixes for https://github.com/dotnet/orleans/issues/2393

Additional commits for 1.3.1: fixes to SQL storage provider and Jenkins hash

---

test/TesterInternal/ActivationsLifeCycleTests/DeactivateOnIdleTests.cs

MissingActivation_1 = MissingActivation_WithoutDirectoryLazyDeregistration_MultiSilo
MissingActivation_2 = MissingActivation_WithDirectoryLazyDeregistration_SingleSilo
Added new test to repro the random bug of MissingActivation_2, test name: MissingActivation_WithoutDirectoryLazyDeregistration_MultiSilo_SecondaryFirst.
If we've 2 silos and the grain is created in the secondary for the first time, then we're removing it via TestHooks from all Silos and then the next call to the same grain happens to be in the Primary Silo, then the grain is not healing and every subsequent calls is failing to it.

MissingActivation Test renames and new test added to repro a multi silo bug alike.

---

vNext/src/Orleans/Orleans.csproj
vNext/src/OrleansCodeGenerator/OrleansCodeGenerator.csproj
vNext/src/OrleansProviders/OrleansProviders.csproj
vNext/src/OrleansRuntime/OrleansRuntime.csproj
vNext/src/OrleansTestingHost/OrleansTestingHost.csproj

Add documentation generation flags to vNext project files.

Add documentation generation flags.

---

vNext/src/Build.cmd
vNext/src/NuGet/CreateOrleansPackages.bat
vNext/src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.Build.nuspec

Fix nuget package building for vNext.

Fix nuget package building for vNext.

---

src/OrleansRuntime/Messaging/IncomingMessageAcceptor.cs

Remove logging statement, RemoteEndPoint property is throwing exception at that point.

Remove faulty logging statement.

---

src/Community/Who-Is-Using-Orleans.md

Updating who is using orleans

---

src/OrleansTelemetryConsumers.NewRelic/NRTelemetryConsumer.cs

According to NR docs https://docs.newrelic.com/docs/agents/manage-apm-agents/agent-data/custom-metrics if is required to prefix all custom metrics with `"Custom/"`.

Add "Custom/" prefix for NewRelic metrics

---

src/Test.cmd
vNext/src/Test.cmd
vNext/test/Tester/App.config
vNext/test/TesterAzureUtils/App.config
vNext/test/TesterInternal/App.config
vNext/test/TesterInternal/TesterInternal.csproj

- add binding redirects
- add remove PersistenGrainTests from vNext, since it uses
AppDomainTestHooks, which isn't fulling working in vNext yet
- update test.cmd

fix failing functional tests

---

vNext/test/Tester/App.config
vNext/test/TesterAzureUtils/App.config
vNext/test/TesterInternal/App.config
vNext/test/TesterSQLUtils/TesterSQLUtils.csproj

-get FluentAssertions version consistent to 4.17.0

fix vnext functional tests

---

src/.nuget/packages.config
test/TestFSharp/TestFSharp.fsproj
test/TestFSharp/packages.config
test/TestFSharpInterfaces/TestFSharpInterfaces.fsproj
test/TestFSharpInterfaces/packages.config

The used F# build tools was pretty outdated (1.5 years old).

Update F# Build Tools to latest version.

---

src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Scheduler/OrleansTaskScheduler.cs
test/NonSiloTests/SchedulerTests/OrleansTaskSchedulerBasicTests.cs
test/TestInternalGrains/PersistenceTestGrains.cs
test/TestInternalGrains/Properties/AssemblyInfo.cs
vNext/test/TestInternalGrains/Properties/AssemblyInfo.cs
vNext/test/TestInternalGrains/TestInternalGrains.csproj

Plus an extra commit to consolidate the "TaskScheduler" test category with the "Scheduler" test category.
Working outside in for #467 :)

Remove OrleansTaskScheduler.Instance

---

src/Community/Who-Is-Using-Orleans.md

Since it is used in production at Lebara for some time now

Added Lebara to "Who Is Using Orleans"

---

src/Orleans/Configuration/GrainServiceConfiguration.cs
src/OrleansRuntime/ReminderService/LocalReminderService.cs
src/OrleansRuntime/Services/GrainService.cs
src/OrleansRuntime/Silo/Silo.cs
test/TestGrainInterfaces/IGrainServiceTestGrain.cs
test/TestGrains/GrainService/CustomGrainService.cs
test/TestGrains/GrainService/GrainServiceTestGrain.cs
test/Tester/GrainServiceTests/CustomGrainService.cs
test/Tester/GrainServiceTests/GrainServiceTests.cs

Wired passing of config properties to grain services

---

test/TestInternalGrains/ReminderTestGrain2.cs

I broke these tests with #2511, which I didn't run functionals on after rebasing - many apologies!
The fix is obvious: add a reminder registry which does not perform timer validation.

Fix IReminderRegistry tests

---

src/Tutorials/Unit-Testing-Grains.md

Added a missing NuGet package (`Microsoft.Orleans.OrleansTelemetryConsumers.Counters`) and fixed some code formatting.

Unit-Testing-Grains.md: NuGet-package and fixed some formatting

---

src/Documentation/Runtime-Implementation-Details/Scheduler.md
src/Documentation/Runtime-Implementation-Details/toc.yml
src/Documentation/toc.yml

Initial documentation of the internal design and implementation of the Scheduler.

Documentation of Orleans Scheduler internal design and implementation.

---

src/Orleans/Configuration/GlobalConfiguration.cs
test/NonSiloTests/ConfigTests.cs
test/NonSiloTests/Config_TableGrain.xml
test/NonSiloTests/Orleans.NonSiloTests.csproj

In config XML, when SystemStoreType is set to MembershipTableGrain, set ReminderServiceType to ReminderTableGrain

---

src/Test.cmd
test/BondUtils.Tests/App.config
test/BondUtils.Tests/BondUtils.Tests.csproj
test/GoogleUtils.Tests/App.config
test/GoogleUtils.Tests/GoogleUtils.Tests.csproj
test/PSUtils.Tests/App.config
test/PSUtils.Tests/PSClient/PSClientTests.cs
test/PSUtils.Tests/PSUtils.Tests.csproj
vNext/test/NonSiloTests/Orleans.NonSiloTests.csproj

add new test assembly to test.cmd

---

src/OrleansRuntime/Core/InsideRuntimeClient.cs

Small fix on PrepareToRemote #2600

---

src/Community/Who-Is-Using-Orleans.md

Also, update link to en version of new promo site

Update info on Orleans use in YouScan

---

Samples/Chirper/ChirperClient/App.config
Samples/Chirper/ChirperClient/ChirperClient.csproj
Samples/Chirper/ChirperClient/packages.config
Samples/Chirper/ChirperGrainInterfaces/ChirperGrainInterfaces.csproj
Samples/Chirper/ChirperGrainInterfaces/packages.config
Samples/Chirper/ChirperGrains/ChirperGrains.csproj
Samples/Chirper/ChirperGrains/app.config
Samples/Chirper/ChirperGrains/packages.config
Samples/Chirper/Host/App.config
Samples/Chirper/Host/Host.csproj
Samples/Chirper/Host/packages.config
Samples/Chirper/NetworkDriver/NetworkDriver.csproj
Samples/Chirper/NetworkDriver/app.config
Samples/Chirper/NetworkDriver/packages.config
Samples/Chirper/NetworkLoader/App.config
Samples/Chirper/NetworkLoader/ChirperNetworkLoader.cs
Samples/Chirper/NetworkLoader/NetworkLoader.csproj
Samples/Chirper/NetworkLoader/packages.config

As part of resolving #2634 
Also removed unecessary Assembly bindings that were there from earlier

Update Chirper Sample project to Orleans 1.3.1

---

src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs
src/OrleansRuntime/MembershipService/MembershipOracleData.cs

These issues were discovered via https://github.com/dotnet/orleans/issues/2463.

Fix code copy-paste errors discovered by Coverity

---

src/Orleans/Core/GrainStateStorageBridge.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Catalog/GrainCreator.cs

I rebased #1918, fixed it, so that it builds, and made minor adjustments to the code on top of @dsarfati's commit.

#1918 from @dsarfati rebased and fixed

---

test/TesterInternal/ActivationsLifeCycleTests/ActivationCollectorTests.cs
test/TesterInternal/MembershipTests/ClientIdPartitionDataRebuildTests.cs

These tests fail intermittently. Likely test issues. Need to investigate them, but for now skip them for more stable test results.

Skip flaky tests

---

Samples/FSharpHelloWorld/Grains/Grains.fsproj
Samples/FSharpHelloWorld/Grains/packages.config
Samples/FSharpHelloWorld/HelloWorld/App.config
Samples/FSharpHelloWorld/HelloWorld/HelloWorld.csproj
Samples/FSharpHelloWorld/HelloWorld/packages.config
Samples/FSharpHelloWorld/HelloWorldInterfaces/FSharpWorldInterfaces.csproj
Samples/FSharpHelloWorld/HelloWorldInterfaces/packages.config

Bump fsharp sample to 1.3.1

---

src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs

Fix: assign correct value to grainState.Etag when ClearStateAsync is called

---

src/Orleans/CodeGeneration/GenericMethodInvoker.cs

Trivial commit to improve comments for the IL generation part of the recently added `GenericMethodInvoker`

Improve comments for GenericMethodInvoker

---

src/OrleansRuntime/Silo/SiloProviderRuntime.cs

Fixes https://github.com/dotnet/orleans/issues/2605

Throw explicit exception when using streams not in Orleans Context.

---

src/NuGet/Microsoft.Orleans.Serialization.Bond.nuspec
src/OrleansBondUtils/project.json

Fixes: https://github.com/dotnet/orleans/issues/2689

Update Bond dependency to 5.1.0.

---

Samples/AzureWebSample/HelloEnvironmentGrains/HelloEnvironmentGrains.csproj
Samples/AzureWebSample/HelloEnvironmentGrains/HelloEnvironmentHelloGrain.cs
Samples/AzureWebSample/HelloEnvironmentGrains/packages.config
Samples/AzureWebSample/HelloEnvironmentInterfaces/HelloEnvironmentInterfaces.csproj
Samples/AzureWebSample/HelloEnvironmentInterfaces/packages.config
Samples/AzureWebSample/OrleansAzureSilos/OrleansAzureSilos.csproj
Samples/AzureWebSample/OrleansAzureSilos/WorkerRole.cs
Samples/AzureWebSample/OrleansAzureSilos/app.config
Samples/AzureWebSample/OrleansAzureSilos/packages.config
Samples/AzureWebSample/WebRole/Web.config
Samples/AzureWebSample/WebRole/WebRole.cs
Samples/AzureWebSample/WebRole/WebRole.csproj
Samples/AzureWebSample/WebRole/packages.config

Update AzureWebSample to orleans 1.3.1

---

Samples/ServiceFabric/Stateless/StatelessCalculatorClient/StatelessCalculatorClient.csproj
Samples/ServiceFabric/Stateless/StatelessCalculatorService/StatelessCalculatorService.csproj
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansServiceFabricUtils/OrleansServiceFabricExtensions.cs

Fixes issues with the Service Fabric providers. Reported by @Kwal (thanks!)

Fix DI registrations for ServiceFabric

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs

Fix build warnings (`ex variable was not used`, and `CA2202: Do not dispose objects multiple times`) as well as removed an unused line of code.

Fix build warnings and dead code

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/Messaging/GatewayProviderFactory.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Statistics/ClientStatisticsManager.cs
src/OrleansAzureUtils/Storage/StatsTableDataManager.cs
src/OrleansRuntime/Counters/SiloStatisticsManager.cs
src/OrleansRuntime/MembershipService/MembershipTableFactory.cs
src/OrleansRuntime/MultiClusterNetwork/MultiClusterGossipChannelFactory.cs
src/OrleansRuntime/ReminderService/LocalReminderServiceFactory.cs
src/OrleansRuntime/ReminderService/ReminderTable.cs
src/OrleansRuntime/Streams/QueueBalancer/StreamQueueBalancerFactory.cs
test/TesterInternal/MembershipTests/ClientIdPartitionDataRebuildTests.cs
test/TesterZooKeeperUtils/ZookeeperMembershipTableTests.cs
vNext/test/ServiceBus.Tests/ServiceBus.Tests.csproj

This ought to fix functional tests, which I recently broke (pretty bad at git).
Providers which are loaded from external libraries should be given access to the IoC container so that they  can access other services without resorting to globals

Construct providers using DI

---

src/NuGet/Microsoft.Orleans.Core.nuspec
src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/project.json
src/OrleansRuntime/GrainTypeManager/GenericGrainTypeData.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubBatchContainer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubSequenceTokenV2.cs
test/DefaultCluster.Tests/GenericGrainTests.cs
test/ServiceBus.Tests/TestStreamProviders/StreamPerPartitionEventHubStreamProvider.cs
test/TestGrainInterfaces/IGenericInterfaces.cs

Bugfix - EventHubSequenceToken not used consistently (#2724)
Support grains with generic state where the state param do not match the grain type params (#2715)

Cherry-pick two more fixes for 1.4.0

---

src/OrleansRuntime/Catalog/Catalog.cs

Not sure what I had in mind when I wrote the first implementation...

More straightforward implementation of AssumeHomogenousSilosForTesting

---

src/Orleans/IDs/UniqueKey.cs

Low fruit but I noticed this as I was checking out the code

fix typo in NewKey parameter check

---

src/Orleans/CodeGeneration/CodeGeneratorManager.cs

Fix for review feedback by @jdom on #2737

Reduce severity of ~"codegen asm not present" message from Warn to Info

---

Samples/HelloWorld.NetCore/HelloWorld.NetCore.sln
Samples/HelloWorld.NetCore/NuGet.Config
Samples/HelloWorld.NetCore/Readme.md
Samples/HelloWorld.NetCore/src/HelloWorld.Grains/HelloArchiveGrain.cs
Samples/HelloWorld.NetCore/src/HelloWorld.Grains/HelloGrain.cs
Samples/HelloWorld.NetCore/src/HelloWorld.Grains/HelloWorld.Grains.csproj
Samples/HelloWorld.NetCore/src/HelloWorld.Interfaces/HelloWorld.Interfaces.csproj
Samples/HelloWorld.NetCore/src/HelloWorld.Interfaces/IHello.cs
Samples/HelloWorld.NetCore/src/HelloWorld.Interfaces/IHelloArchive.cs
Samples/HelloWorld.NetCore/src/OrleansClient/OrleansClient.csproj
Samples/HelloWorld.NetCore/src/OrleansClient/Program.cs
Samples/HelloWorld.NetCore/src/SiloHost/OrleansHostWrapper.cs
Samples/HelloWorld.NetCore/src/SiloHost/Program.cs
Samples/HelloWorld.NetCore/src/SiloHost/SiloHost.csproj

Sample using Orleans 2.0 (preview) to run a hello world in .NET Core.

Orleans HelloWorld sample targeting .NET Core

---

src/Documentation/Advanced-Concepts/Powershell-Client.md

should need an await before accessing the result

Wait (for await)

---

src/OrleansCodeGenerator/SerializerGenerator.cs
src/OrleansCodeGenerator/Utilities/SyntaxFactoryExtensions.cs
test/DefaultCluster.Tests/GrainReferenceTest.cs
test/NonSiloTests/Serialization/BuiltInSerializerTests.cs
test/TestGrainInterfaces/CodegenTestInterfaces.cs
test/TestGrainInterfaces/IChainedGrain.cs
test/TestGrains/ChainedGrain.cs

Fix AsReference() in generated code for null values

---

src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Serialization/SerializationManager.cs

#2769  Avoid a NullReferenceException in SerializationManager.Register(...).

Cherry-pick #2769 for 1.4.1

---

test/DefaultCluster.Tests/GrainReferenceTest.cs
test/NonSiloTests/Serialization/BuiltInSerializerTests.cs

This PR migrates a few more tests from the VSO repository so that they can be removed from that repo and we can work towards merging the two.

Migrate some tests from VSO repository

---

test/TesterInternal/StorageTests/CommonStorageTests.cs

Fixes #2790. Details in that issue.

Fix failing test due to collisions with other tests

---

src/Documentation/Getting-Started-With-Orleans/Developing-a-Client.md
src/Documentation/Getting-Started-With-Orleans/Grain-Persistence.md
src/Documentation/Getting-Started-With-Orleans/Grains.md
src/Documentation/Getting-Started-With-Orleans/Observers.md
src/Documentation/Getting-Started-With-Orleans/Running-the-Application.md
src/Tutorials/Cloud-Deployment.md
src/Tutorials/Front-Ends-for-Orleans-Services.md
src/Tutorials/My-First-Orleans-Application.md
src/Tutorials/On-Premise-Deployment.md

- Update the `Next` links to follow the Step-by-Step guide on the left side.

Fixes #2367 Updates Next links to be consistent with Step by Step guide

---

test/TesterInternal/StorageTests/CommonStorageTests.cs

* Avoids stressing the storage on the INSERT call by limiting parallelization on the first write.
* Avoids starving the thread pool while doing concurrent updates, but still force the store to be stressed a little bit.
Fixes #2790

Fix stress issues with a test

---

src/Before.Orleans.sln.targets
src/Build.cmd

Make master possible to be built without having Visual Studio installed on the build agents.

Build master on VSO agent without having VS installed.

---

src/Orleans/Messaging/GatewayConnection.cs
test/Tester/ClientConnectionTests/GatewayConnectionTests.cs
test/Tester/Tester.csproj

Avoid reconnection to gateway no longer in the list returned by IGatewayListProvider 

---

test/Tester/ClientConnectionTests/GatewayConnectionTests.cs

GrainClient is not initialized for every test since we use ClientBuilder now.

Fix NoReconnectionToGatewayNotReturnedByManager test

---

src/.nuget/packages.config
src/Build.cmd
src/OrleansVSTools/.nuget/packages.config
src/OrleansVSTools/VSItemTemplateGrainImplementationFSharp/VSItemTemplateGrainImplementationFSharp.fsproj
src/OrleansVSTools/VSProjectTemplateGrainImplementationFSharp/VSProjectTemplateGrainImplementationFSharp.fsproj
test/TestFSharp/TestFSharp.fsproj
test/TestFSharp/packages.config
test/TestFSharp/project.json
test/TestFSharpInterfaces/TestFSharpInterfaces.fsproj
test/TestFSharpInterfaces/packages.config
test/TestFSharpInterfaces/project.json

* Download VSWhere into git-ignored build folder
* Consolidate FSharp.Compiler.Tools version
* Switch FSharp projects to project.json, as the new tools package supports it.

Build tool fixes

---

src/Orleans/Core/ClientBuilder.cs
src/Orleans/Streams/Core/IStreamSubscriptionManager.cs
src/Orleans/Streams/Core/IStreamSubscriptionManagerAdmin.cs
src/Orleans/Streams/Core/StreamSubscriptionManager.cs
src/Orleans/Streams/Core/StreamSubscriptionManagerAdmin.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans/Streams/PubSub/StreamSubscriptionManagerExtensions.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs
src/OrleansRuntime/Silo/Silo.cs
test/TestGrainInterfaces/ProgramaticStreamSubscribe/IStateless_ConsumerGrain.cs
test/TestGrains/ProgrammaticSubscribe/Stateless_ConsumerGrain.cs
test/TestGrains/ProgrammaticSubscribe/SubscribeGrain.cs
test/TestGrains/ProgrammaticSubscribe/TypedProducerGrain.cs
test/Tester/StreamingTests/ProgrammaticSubscribeTests/ProgrammaticSubcribeTests.cs
test/Tester/StreamingTests/ProgrammaticSubscribeTests/ProgrammaticSubscribeTestsWithDynamicProviderConfiguration.cs
test/Tester/Tester.csproj

Programmatic Subscribe round2:
Decouple subscription setup with StreamProvider set up
Add tests to test it

Decouple subscription setup with StreamProvider set up

---

src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.Build.nuspec

Thanks, @attilah, for finding this issue :)

Include Orleans dependencies in OrleansCodeGenerator.Build package

---

netci.groovy

This will run Functional tests for every PR that is opened. It will explicitly skip Azure related tests.

Run functionals in Jenkins for every PR

---

test/TesterInternal/ActivationsLifeCycleTests/DeactivateOnIdleTests.cs

This way the test chance for failure is reduced.
Removed usage of the logger for test related output.

Give some extra chances for the test to find an appropriate grain

---

src/OrleansServiceBus/Providers/Streams/EventHub/CachePressureMonitors/AveragingCachePressureMonitor.cs
src/OrleansServiceBus/Providers/Streams/EventHub/CachePressureMonitors/SlowConsumingPressureMonitor.cs

added /// <inheritdoc /> tag to inherit xml comments

fix xml warnings

---

src/Tutorials/Minimal-Orleans-Application.md

* Added link for getting started with Orleans
* Fixed typos and grammar
* Corrected link for Running in a stand alone silo

Performed literary review and added/fixed links for "Minimal Orleans Application"

---

src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
test/ServiceBus.Tests/ServiceBus.Tests.xunit.runner.json

getNodeConfig is not available in client side

---

src/Documentation/Runtime-Implementation-Details/Cluster-Management.md

Just making it flow better so that it does not get in the way of a good read :)

Grammer fix

---

src/Orleans/Async/AsyncExecutorWithRetries.cs

This change serves multiple purposes:
1. Fixes https://github.com/dotnet/orleans/issues/2966
2. <s>Using exception filters instead of rethrowing the original exception keeps the stack unwound (http://www.thomaslevesque.com/2015/06/21/exception-filters-in-c-6/)</s>
3. <s>Executes the underlying task with timeout to quit faster.</s>
4. <s>In the previous version, we check the timeout after the delay, but I think it is better to do it vice versa - in that case we won't wait the extra delay (which could be significant in case of an exponential retry, for instance) if there is timeout already.</s>
5. <s>Eliminates code duplicates with helper private methods.</s>

Improve ExecuteWithRetries helper

---

src/Orleans/Logging/ErrorCodes.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs

regards to #2968, add ability to remove faulted subscription from pubsub

Add ability to remove faulted subscription

---

src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs

fix for #3000 
The cause of this bug : producer was shut down ungracefully (silo process was killed) ->consumer grain wants to unsubscribe on the stream the producer was producing on ->   unsubscribe request went to pubsub system and pubsub system tries to activate procuder grain and try to notify its ProducerExtension of the removed subscriber -> producer grain wakes up without the ProducerExtension, because the extension only installed when producer calls onNextAsync, so the application gets a GrainExtensionNotInstalledException. 
Fix: ignore the exception in this case. Producer will lost its subscriber list when deactivate and will repopulate its consumer list when it tries to produce again after activating, so no need to clean it.

make pubsub more robust when facing ungraceful shutdown of producers

---

src/OrleansRuntime/GrainDirectory/ClientObserverRegistrar.cs
src/OrleansRuntime/Placement/DeploymentLoadPublisher.cs

Cleaning some "high" impacts issues raised by Coverity.
Not sure if they were really important, but it seems to be cleaner to stop/dispose timers when the silo stops.

[Coverity] Dispose timers when silo stopping

---

src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Providers/EventDataGeneratorStreamProvider/EventDataGeneratorStreamProvider.cs
src/OrleansServiceBus/Providers/EventDataGeneratorStreamProvider/MockEventHubSettings.cs
src/OrleansServiceBus/Providers/EventDataGeneratorStreamProvider/NoOpCheckpointer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
test/ServiceBus.Tests/SlowConsumingTests/EHSlowConsumingTests.cs
test/ServiceBus.Tests/StatisticMonitorTests/EHStatisticMonitorTests.cs

So that we don't need to configure anything eventhub specific to use EventDataGeneratorStreamProvider.

Mock out eventhub from EventDataGeneratorStreamProvider

---

src/Orleans/Configuration/GlobalConfiguration.cs
src/OrleansRuntime/Silo/Silo.cs

Add flag to disable FastKill on CTRL-C

---

src/Documentation/Advanced-Concepts/Configuring-.NET-Garbage-Collection.md

- update with .NET Core config
- fix a grammer issue

configure .net garbage collection for .net core

---

src/NuGet/Microsoft.Orleans.OrleansServiceBus.nuspec
src/OrleansServiceBus/OrleansServiceBus.2017.csproj
src/OrleansServiceBus/project.json
test/ServiceBus.Tests/ServiceBus.Tests.csproj

Upgrade WindowsAzure.ServiceBus to 4.1.0

---

src/Orleans/Core/Exceptions.cs
src/Orleans/Runtime/GrainReference.cs
src/Orleans/Runtime/SiloStatus.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs
test/TesterInternal/ActivationsLifeCycleTests/DeactivateOnIdleTests.cs
test/TesterInternal/StorageTests/PersistenceGrainTests.cs
test/TesterInternal/StreamingTests/StreamPubSubReliabilityTests.cs

Catch rejected messages to producers and remove the producer if those rejections come from dead, dying, or missing silos.
This should address #3056?

Cleanup stream producers on dead or missing silos.

---

src/Orleans/Cancellation/GrainCancellationToken.cs
src/Orleans/Cancellation/ICancellationSourcesExtension.cs
src/OrleansRuntime/Cancellation/CancellationSourcesExtension.cs
test/Tester/CancellationTests/GrainCancellationTokenTests.cs

A *bit* late fix for https://github.com/dotnet/orleans/issues/1891/ 
Description of the fix can be found in comment at https://github.com/dotnet/orleans/pull/3168/files#diff-ad4d2634c223caffc7ddb1eddec5ca43R95

Fix race condition on cancelling of gcts

---

src/NuGet/Microsoft.Orleans.Core.nuspec
src/NuGet/Microsoft.Orleans.OrleansSqlUtils.nuspec
src/NuGet/Microsoft.Orleans.ServiceFabric.nuspec
src/Orleans/Orleans.2017.csproj
src/Orleans/Serialization/OrleansJsonSerializer.cs
src/Orleans/project.json
src/OrleansServiceFabricUtils/OrleansServiceFabricUtils.2017.csproj
src/OrleansServiceFabricUtils/project.json
test/NonSilo.Tests/project.json
test/Tester/project.json
test/TesterAzureUtils/Tester.AzureUtils.2017.csproj
test/TesterAzureUtils/project.json
test/TesterSQLUtils/project.json
test/TesterZooKeeperUtils/project.json
vNext/src/Orleans/Orleans.csproj
vNext/test/ServiceBus.Tests/ServiceBus.Tests.csproj
vNext/test/TestGrains/TestGrains.csproj
vNext/test/TesterAzureUtils/Tester.AzureUtils.csproj

This fixes some issues with FormatterAssemblyStyle when using the .NET Standard version of the library

Update Newtownsoft.Json to 10.0.3

---

src/Orleans/Versions/Compatibility/ICompatibilityDirector.cs
src/Orleans/Versions/Selector/IVersionSelector.cs
src/OrleansManager/Program.cs

Only works with built-in director and selector. If the developer want to implement his own, he will need to build his own tool to support them

Add compatibility director and version selector change in OrleansManager

---

src/Orleans/Orleans.csproj
src/Orleans/Providers/ILeaseProvider.cs

The ILeaseProvider interface. Which is optional to be included in 1.5

ILeaseProvider interface

---

src/Orleans/IDs/ActivationAddress.cs
src/Orleans/Messaging/RequestInvocationHistory.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs

Very small cleanup in preparation of moving some types to Orleans.Core.Abstractions

Abstractions preparation cleanup

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs

Add workaround, when as a side-effect we can receive BadImageFormatException when processing the loading failures.
Add process compatibility check for the "preloading" phase of assemblies.
Fix filename based filtering to include only .dll files and not files anything after .dll in their filename.

AssemblyLoader filtering and precheck fixes

---

src/Documentation/Installation/NuGets.md

Update NuGet Packages pages for 1.5.0

---

src/Documentation/Installation/Prerequisites.md

Updated some basic information and links.

Update Prerequisites page

---

src/Documentation/Getting-Started-With-Orleans/Grains.md

Rewrote first page of Getting Started.
You can see the result at http://sergeybykov.github.io/orleans/Documentation/Getting-Started-With-Orleans/Grains.html.

Rewrote first page of Getting Started

---

src/OrleansServiceFabricUtils/OrleansCommunicationListener.cs
src/OrleansServiceFabricUtils/OrleansServiceListener.cs

Just some minor thing which annoyed me during testing

Support custom silo names in Service Fabric integration

---

src/OrleansCodeGenerator/SerializerGenerator.cs

Avoid serializing delegates and other non-portable types.

---

src/Documentation/Getting-Started-With-Orleans/Developing-a-Grain.md

I rewrote parts of the Developing a Grain page for, hopefully, better clarity.

Update Developing a Grain page

---

src/Orleans/Providers/ILeaseProvider.cs
src/Orleans/Streams/PersistentStreams/IDeploymentConfiguration.cs
src/Orleans/Streams/PersistentStreams/IStreamQueueBalancer.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans/Streams/Providers/IStreamProviderRuntime.cs
src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansAzureUtils/Providers/Lease/AzureBlobLeaseProvider.cs
src/OrleansAzureUtils/QueueBalancers/AzureDeployemntQueueBalancer.cs
src/OrleansAzureUtils/QueueBalancers/StreamQueueBalancerType.cs
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingManager.cs
src/OrleansRuntime/Streams/QueueBalancer/ConsistentRingQueueBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/DeploymentBasedQueueBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/LeaseBasedQueueBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/QueueBalancerBaseClass.cs
src/OrleansRuntime/Streams/QueueBalancer/StreamQueueBalancerType.cs
test/Tester/StreamingTests/PlugableQueueBalancerTests/LeaseBasedQueueBalancer.cs
test/Tester/StreamingTests/PlugableQueueBalancerTests/PluggableQueueBalancerTestBase.cs
test/TesterAzureUtils/Lease/AzureBlobLeaseProviderTests.cs
test/TesterAzureUtils/Lease/LeaseBasedQueueBalancerTests.cs
test/TesterAzureUtils/TesterAzureUtils.csproj

1. added LeaseBasedQueueBalancer, it will try to renew its leases and acquire or release leases to meet its responsibility, in initialization,  every 30 sec, when received siloStatusChangeNotification
2. added AzureBlobLeaseProvider, it will need to be configured through DI, see test as example
3. added tests for both

Lease based queue balancer

---

src/NuGet/Microsoft.Orleans.Core.nuspec
src/Orleans/Serialization/BuiltInTypes.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/project.json
test/NonSilo.Tests/SerializationTests/SerializationTests.DifferentTypes.cs
vNext/src/Orleans/Orleans.csproj

Add built-in serialization support for ValueTuple

---

src/Documentation/Advanced-Concepts/Powershell-Client.md

thanks @sergeybykov for uploading to PowerShell gallery

Docs - Update from Orleans to OrleansPSUtils

---

src/Documentation/Advanced-Concepts/Interceptors.md

Add documentation for Grain Call Filters

---

src/Orleans/Core/ClusterClient.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Streams/Internal/StreamDirectory.cs
src/OrleansCodeGenerator/CodeGeneratorCommon.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueAdapterCache.cs
src/OrleansRuntime/GrainTypeManager/TypeManager.cs
src/OrleansRuntime/Silo/Silo.cs
test/NonSilo.Tests/OrleansRuntime/AsyncSerialExecutorTests.cs
test/NonSilo.Tests/SerializerTests/MessageSerializerTests.cs
test/Tester/StreamingTests/SampleStreamingTests.cs
test/TesterInternal/MembershipTests/ClientIdPartitionDataRebuildTests.cs

I included some of the test fixes to reduce the noise while testing.
I think the last thing we want to bring is a fix to https://github.com/dotnet/orleans/issues/3273 before we can release 1.5.1.

More fixes cherry-picked for 1.5.1

---

src/Orleans/Streams/PersistentStreams/IStreamQueueBalancer.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/SystemTargetExtensions.cs
src/OrleansRuntime/GrainDirectory/ILocalGrainDirectory.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs
src/OrleansRuntime/MultiClusterNetwork/MultiClusterOracle.cs
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Placement/DeploymentLoadPublisher.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingManager.cs

This will probably be the latest commit that we need for 1.5.1
- Fix scheduling of notification interfaces (#3290)

Cherrypick commits for 1.5.1

---

src/Orleans/Core/ClientBuilder.cs
src/Orleans/Providers/ProviderLoader.cs
src/Orleans/Providers/ProviderTypeLoader.cs
src/Orleans/Providers/StatisticsProviderManager.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Streams/Providers/StreamProviderManager.cs
src/OrleansRuntime/Core/BootstrapProviderManager.cs
src/OrleansRuntime/Hosting/DefaultSiloServices.cs
src/OrleansRuntime/LogConsistency/LogConsistencyProviderManager.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Storage/StorageProviderManager.cs
test/AWSUtils.Tests/StorageTests/DynamoDBStorageProviderTests.cs
test/TesterAzureUtils/Persistence/PersistenceProviderTests.cs
test/TesterSQLUtils/StorageTests/Relational/CommonFixture.cs

Package static state in ProviderTypeLoader into a separate class LoadedProviderTypeLoader, and inject it into DI. 
Prep work for logging migration

Remove static state in ProviderTypeLoader 

---

netci.groovy

Change to latest-or-auto

---

changelog.md

After this is merged, I'll update in master also

Update changelog for 1.5.1

---

src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs

The workaround itself can cause issues when building complex graphs, as it is not a conforming container.
Since Orleans 1.5.0, the IServiceProvider is already always non-null.

Remove unnecessary DI workaround in client

---

.gitignore
Build-Core.cmd
netci.groovy

Update build to generate the new binary logs (new MSBuild 15.3 feature)
Update build to generate unique log files per build flavor per config per stage (restore, build, pack)
Modify CI script to archive the binlog files
Info on binary logs: http://msbuildlog.com

Change build process to produce binary logs

---

netci.groovy

Remove build flavor building from CI file, preparing for Legacy code removal from code base.

Remove build flavor building from CI file.

---

src/OrleansRuntime/GrainDirectory/GrainDirectoryHandoffManager.cs

This is the result of finding `System.InvalidOperationException`: `Collection was modified; enumeration operation may not execute.`  in our logs on ApplicationInsights.
The following is not the prettiest formatting but I don't know of a prettier way to get callstacks out of AI off hand:
```
[  
{  
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
"method":"System.ThrowHelper.ThrowInvalidOperationException",
"level":0,
"line":0
},
{  
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
"method":"System.Collections.Generic.List`1+Enumerator.MoveNextRare",
"level":1,
"line":0
},
{  
"assembly":"OrleansRuntime, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null", …
```

Fix locks in GrainDirectoryHandoffManager 1/2

---

src/Orleans.Transactions/Orleans.Transactions.csproj
src/Orleans.Transactions/State/TransactionalState.cs

Tighten up transactional state recovery logic
Use proper service provider in transactional state

Transactions tweaks

---

src/Documentation/Deployment-and-Operations/Heterogeneous-Silos.md

Thanks to @shlomiw  and @benjaminpetit  
The docs were not mentioning a few good to know and necessary facts which are added.

Heterogeneous silo docs fixes

---

Samples/NuGet.Config
Samples/ServiceFabric/README.txt

There was a local NuGet repo configured for samples which was causing issues when trying to upgrade, removed it

Fixed the sample NuGet issue

---

src/OrleansRuntime/Timers/TimerRegistry.cs

See https://github.com/dotnet/orleans/commit/b9bad19cbf58c0570f590cc2eaceace366183325#commitcomment-24577719 for details

Fix memory leak in timers

---

Build.cmd

* Fix build script for when there are errors
* Make Debug configuration add the suffix based on build time

Fix Build script

---

Samples/HelloWorld.NetCore/HelloWorld.NetCore.sln
Samples/HelloWorld.NetCore/Readme.md
Samples/HelloWorld.NetCore/src/HelloWorld.Grains/HelloArchiveGrain.cs
Samples/HelloWorld.NetCore/src/HelloWorld.Grains/HelloGrain.cs
Samples/HelloWorld.NetCore/src/HelloWorld.Grains/HelloWorld.Grains.csproj
Samples/HelloWorld.NetCore/src/HelloWorld.Interfaces/HelloWorld.Interfaces.csproj
Samples/HelloWorld.NetCore/src/OrleansClient/OrleansClient.csproj
Samples/HelloWorld.NetCore/src/OrleansClient/Program.cs
Samples/HelloWorld.NetCore/src/SiloHost/OrleansHostWrapper.cs
Samples/HelloWorld.NetCore/src/SiloHost/Program.cs
Samples/HelloWorld.NetCore/src/SiloHost/SiloHost.csproj

Upgrade to .NET Core 2 (fix solution since it wasn't building with .NET CORE 1 and Orleans Preview 3)
Used latest packages for Client and Silo (`Microsoft.Orleans.Server` and `Microsoft.Orleans.Client`)
Updated Orleans `Client` to start using `IClusterClient` instead of `GrainClient.GrainFactory`

HelloWorld.NetCore Sample: upgrade to dotnet core 2.0 and use latest orleans packages

---

test/ServiceBus.Tests/EvictionStrategyTests/EHPurgeLogicTests.cs

It was disabled under non-legacy build condition.  So re-enable it

Enable EHPurgeLogicTests

---

Samples/HelloWorld.NetCore/BuildAndRun.ps1
Samples/HelloWorld.NetCore/BuildAndRun.sh
Samples/HelloWorld.NetCore/HelloWorld.NetCore.sln
Samples/HelloWorld.NetCore/NuGet.Config
Samples/HelloWorld.NetCore/Readme.md
Samples/HelloWorld.NetCore/src/HelloWorld.Grains/HelloArchiveGrain.cs
Samples/HelloWorld.NetCore/src/HelloWorld.Grains/HelloGrain.cs
Samples/HelloWorld.NetCore/src/OrleansClient/Program.cs
Samples/HelloWorld.NetCore/src/SiloHost/OrleansHostWrapper.cs
Samples/HelloWorld.NetCore/src/SiloHost/Program.cs

* Update build and run code and instructions to publish first
* Normalize all code to use spaces, as it's currently mixed

Update run instructions for HelloWorld.NetCore sample

---

test/Orleans.Transactions.Azure.Test/GoldenPathTests.cs
test/Orleans.Transactions.Azure.Test/GrainFaultTests.cs
test/Orleans.Transactions.Azure.Test/OrchestrationTests.cs

~* Include transactions tests in CI~
* Skip tests if Azure is unavailable

Validate Azure environment preconditions for tests

---

test/Orleans.Transactions.Tests/Runners/OrchestrationsTransactionsTestRunner.cs

Two fixes:
- Transaction calls return when transaction is complete, but the transactional resource itself may not have been told that the transaction completed yet, so this change waits a little while for that to occur.
- Transactional resources will (eventually) be told about the highest committed transaction, but will not necessarily be told about every committed transaction, so we test only against the highest.

Fixed intermitent transaction orchestration test failures

---

src/Orleans.CodeGeneration.Build/Orleans.CodeGeneration.Build.csproj

As it's not related to Bootstrap, and it's impacting signing

Move PublishDir from Bootstrap folder

---

Samples/HelloWorld.NetCore/Readme.md
Samples/HelloWorld.NetCore/src/OrleansClient/Program.cs
Samples/HelloWorld.NetCore/src/SiloHost/Program.cs

Cleanup now that #3578 was released to myget

Sample: Cleanup assembly parts usage with latest preview4 fix

---

Samples/HelloWorld.NetCore/BuildAndRun.ps1
Samples/HelloWorld.NetCore/BuildAndRun.sh

It is no longer needed as of preview4

NetCore Sample cleanup: Do not publish when running

---

src/Orleans.CodeGeneration.Build/Program.cs

Force InvariantCulture in code generator startup

---

test/Benchmarks/BenchmarkGrainInterfaces/BenchmarkGrainInterfaces.csproj
test/Benchmarks/BenchmarkGrains/BenchmarkGrains.csproj
test/Benchmarks/Benchmarks/Benchmarks.csproj
test/Benchmarks/Benchmarks/Program.cs

Fix Benchmark app code  gen
Make it a console app

Fix Benchmark app code  gen

---

Samples/HelloWorld.NetCore/src/HelloWorld.Grains/HelloGrain.cs
Samples/HelloWorld.NetCore/src/HelloWorld.Grains/HelloWorld.Grains.csproj

I would have find helpful if the new way of logging in the 2.0 version was included in some of the samples.

Add logging to grain in HelloWorld.NetCore

---

Documentation/Advanced-Concepts/Powershell-Client.html
src/Documentation/Advanced-Concepts/Powershell-Client.md

From OrleansPSUtil to OrleansPSUtils

Corrected Nuget package names in Powershell-Client.html

---

test/Benchmarks/Benchmarks/Benchmarks.csproj
test/Benchmarks/Benchmarks/Program.cs
test/Benchmarks/Benchmarks/TransactionManager/TransactionManagerBentchmarks.cs

Benchmarks of transction manager for development purposes.  Usefull for targeted optimization.
Currently seeing:
In Memory ~ 200k/sec
Agains Azure ~ 4k/sec

Transaction manager benchmarks

---

src/Documentation/Deployment-and-Operations/Configuration-Guide/Typical-Configurations.md

This is a bug, I believe microsoft is working on a patch, but they did not give me an ETA
#3605

Added disclaimer about ACS firewall limitation

---

src/Documentation/Deployment-and-Operations/Using-Azure-Web-Apps.md

Firewall limitation note

---

src/Documentation/Frequently-Asked-Questions.md

Fix typo in FAQ

---

src/Orleans.Transactions/ErrorCodes.cs
src/Orleans.Transactions/State/TransactionalState.cs
test/Orleans.Transactions.Tests/Grains/SingleStateTransactionalGrain.cs
test/Orleans.Transactions.Tests/Memory/GoldenPathTransactionManagerMemoryTests.cs
test/Orleans.Transactions.Tests/Runners/GoldenPathTransactionTestRunner.cs

Fixed intermittent transaction test failures.
Added new transaction test to reproduce community reported issue.
see Consecutive transactions on grains can cause rollbacks #3681

Fixed intermittent transaction test failures.

---

Orleans.sln
OrleansCrossPlatform.sln
src/Azure/Orleans.Transactions.AzureStorage/Hosting/SiloBuilderExtensions.cs
src/Azure/Orleans.Transactions.AzureStorage/Orleans.Transactions.AzureStorage.csproj
src/Azure/Orleans.Transactions.AzureStorage/Storage/AzureTransactionLogConfiguration.cs
src/Azure/Orleans.Transactions.AzureStorage/Storage/AzureTransactionLogOptions.cs
src/Azure/Orleans.Transactions.AzureStorage/Storage/AzureTransactionLogStorage.cs
test/Benchmarks/Benchmarks/Benchmarks.csproj
test/Benchmarks/Benchmarks/TransactionManager/TransactionManagerBentchmarks.cs
test/Orleans.Transactions.Azure.Test/GoldenPathTests.cs
test/Orleans.Transactions.Azure.Test/GoldenPathTransactionManagerTest.cs
test/Orleans.Transactions.Azure.Test/GrainFaultTests.cs
test/Orleans.Transactions.Azure.Test/OrchestrationTests.cs
test/Orleans.Transactions.Azure.Test/Orleans.Transactions.Azure.Test.csproj
test/Orleans.Transactions.Azure.Test/TestFixture.cs

To address https://github.com/dotnet/orleans/pull/3719#issuecomment-349464479.

Rename Orleans.Transactions.Azure to Orleans.Transactions.AzureStorage

---

test/Tester/StreamingTests/ClientStreamTestRunner.cs

Make it pass more often by increase waiting time

Make client stream test run more deterministic

---

src/Documentation/2.0/Codegen.md
src/Documentation/2.0/New.md
src/Documentation/2.0/Transactions.md
src/Documentation/2.0/toc.yml

Update What's New in 2.0.
Add placeholder pages for codegen and transactions.

Update What's New and add placeholders

---

src/Documentation/2.0/New.md

- Scoped services
- Abstractions package
- Logging changes

Add to What's new in Orleans 2.0

---

src/Azure/Orleans.Reminders.AzureStorage/Storage/AzureBasedReminderTable.cs
src/Orleans.Runtime/Core/GrainRuntime.cs
src/Orleans.Runtime/Hosting/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/MultiClusterNetwork/MultiClusterGossipChannelFactory.cs
src/Orleans.Runtime/Silo/Silo.cs
src/Orleans.Runtime/Silo/SiloInitializationParameters.cs
src/Orleans.Runtime/Silo/SiloProviderRuntime.cs
src/Orleans.Runtime/Silo/TestHooks/TestHooksSystemTarget.cs
src/OrleansAWSUtils/Reminders/DynamoDBReminderTable.cs
src/OrleansSQLUtils/ReminderService/SqlReminderTable.cs
test/AWSUtils.Tests/Reminder/DynamoDBRemindersTableTests.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs
test/TesterAzureUtils/Reminder/ReminderTests_Azure_Standalone.cs
test/TesterInternal/RemindersTest/ReminderTableTestsBase.cs
test/TesterSQLUtils/MySqlRemindersTableTests.cs
test/TesterSQLUtils/PostgreSqlRemindersTableTests.cs
test/TesterSQLUtils/SqlServerRemindersTableTests.cs

- Move ServiceId to SiloOptions

Move some configuration to typed options

---

src/Orleans.Runtime/Core/InsideRuntimeClient.cs
test/Tester/GrainCallFilterTests.cs

Fix potential dependency cycles with user-supplied IGrainCallFilter implementations

---

src/Orleans.Core/Providers/GrainStorageExtensions.cs

Include required provider name in GetStorageProvider exception message.

---

Samples/AccountTransfer.NetCore/src/OrleansClient/Program.cs
Samples/AccountTransfer.NetCore/src/SiloHost/Program.cs

Updated transactions sample to work with Orleans 2.0 beta 2

Update transactions sample.

---

Samples/Docker-Simple/Client/Client.csproj
Samples/Docker-Simple/Client/Program.cs
Samples/Docker-Simple/GrainInterfaces/GrainInterfaces.csproj
Samples/Docker-Simple/GrainInterfaces/IPingGrain.cs
Samples/Docker-Simple/Grains/Grains.csproj
Samples/Docker-Simple/Grains/PingGrain.cs
Samples/Docker-Simple/Silo/Program.cs
Samples/Docker-Simple/Silo/Silo.csproj

- Update to beta 3
- Client is now pinging grain in a 'infinite' loop until it is asked to stop by docker

[Samples] Update docker-simple

---

src/Orleans.Core/AssemblyLoader/CachedTypeResolver.cs
src/Orleans.Core/Serialization/BinaryFormatterSerializer.cs
src/Orleans.Core/Serialization/OrleansJsonSerializationBinder.cs
src/Orleans.Core/Serialization/OrleansJsonSerializer.cs

Support resolving 1.5.x type names to 2.x types.

---

src/Tutorials/Failure-Handling.md

* fixed spelling mistakes
* Ensured consistency by adding "the" where required and changing DB to database
* Reworded certain phrases
*  Fixed grammar

Fix grammar, spelling and consistency of document

---

src/Orleans.Core.Abstractions/IDs/GrainId.cs

Display GrainId/type of SystemGrain and SystemTarget in GrainId.ToStringImpl

---

src/Documentation/Deployment-and-Operations/Configuration-Guide/Configuring-SQL-Tables.md

Fix links to SQL scripts

---

src/Orleans.Core/Placement/PlacementTarget.cs
src/Orleans.Runtime/Core/Dispatcher.cs
test/TestGrainInterfaces/CustomPlacement.cs
test/TestGrains/CustomPlacementGrains.cs
test/TestGrains/TestPlacementStrategyFixedSiloDirector.cs
test/Tester/Placement/CustomPlacementTests.cs

Related issue: #3896 
That was more easy that I expected :)

Expose RequestContextData in PlacementTarget

---

src/Orleans.Core/Configuration/Legacy/LegacyConfigurationExtensions.cs
src/Orleans.Core/Configuration/Options/TelemetryOptions.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
src/Orleans.Core/Telemetry/TelemetryManager.cs
src/Orleans.Runtime/Hosting/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/Silo/Silo.cs
src/Orleans.Runtime/Silo/SiloHost.cs

I tested locally, but unfortunately I don't have unit tests for this, since it is a Windows specific features...
We should be able to add some testing in the future I think.

Add TelemetryOptions to configure Telemetry consumers

---

src/Orleans.Core/Providers/ProviderTypeLoader.cs

Remove locks in LoadedProviderTypeLoaders and ProviderTypeLoader that appear unnecessary and caused occasional deadlocks in tests.

Remove locks in LoadedProviderTypeLoaders and ProviderTypeLoader

---

src/Documentation/Advanced-Concepts/Activation-Garbage-Collection.md

Updated activation GC page to document and emphasize programmatic configuration and, hopefully, for better clarity.

Update activation GC page

---

src/Orleans.Core.Abstractions/IDs/UniqueIdentifier.cs
src/Orleans.Core.Abstractions/Orleans.Core.Abstractions.csproj
test/TestGrainInterfaces/TestGrainInterfaces.csproj
test/TesterInternal/GeoClusterTests/MultiClusterNetworkTests.cs

Per https://github.com/dotnet/orleans/issues/3913

Remove Newtonsoft.JSON Dependency from core abstractions

---

Samples/HelloWorld.NetCore/Directory.Build.props
Samples/HelloWorld.NetCore/src/SiloHost/SiloHost.csproj

Update Orleans version to 2.0.0-beta*.
Add ServerGarbageCollection=true to SiloHost project.

Update HelloWorld.NetCore sample

---

src/Orleans.Runtime/Messaging/IInboundMessageQueue.cs
src/Orleans.Runtime/Messaging/InboundMessageQueue.cs
src/Orleans.Runtime/Messaging/MessageCenter.cs

 Dispose InboundMessageQueue during MessageCenter disposal 

---

src/Documentation/Advanced-Concepts/Interceptors.md

Adding grain calls from interceptors as a useful use case.

 Updating Interceptors.md to include graincalls made from interceptors

---

src/Orleans.Core/Logging/ILoggerExtensions.cs
src/Orleans.Core/Serialization/SerializationManager.cs
src/Orleans.Runtime/ReminderService/InMemoryRemindersTable.cs
test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs

PR fixing the issue https://github.com/dotnet/orleans/issues/3909
Removed  some logging code seems to be left from testing
Test for big 1-dimensional array of primitive type serialization, showing off the issue

Fix logger exceptions

---

src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/Orleans.Core.Legacy/Configuration/NodeConfiguration.cs
src/Orleans.Core/Configuration/Options/LoadSheddingOptions.cs
src/Orleans.Core/Configuration/Options/SiloStatisticsOptions.cs
src/Orleans.Runtime.Legacy/Configuration/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/Counters/SiloPerformanceMetrics.cs
src/Orleans.Runtime/Counters/SiloStatisticsManager.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/OrleansProviders/Streams/LoadShedQueueFlowController.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerBasicTests.cs
test/ServiceBus.Tests/EvictionStrategyTests/EHPurgeLogicTests.cs

This is a preparation step for #3948 and a useful cleanup step in general.

Move load shedding settings to LoadSheddingOptions

---

src/AWS/Orleans.Clustering.DynamoDB/Membership/LegacyDynamoDBGatewayListProviderConfigurator.cs
src/AdoNet/Orleans.Clustering.AdoNet/Messaging/LegacyAdoNetGatewayListProviderConfigurator.cs
src/Azure/Orleans.Clustering.AzureStorage/AzureGatewayListProvider.cs
src/Azure/Orleans.Clustering.AzureStorage/LegacyAzureTableGatewayListProviderConfigurator.cs
src/Azure/Orleans.Clustering.AzureStorage/Orleans.Clustering.AzureStorage.csproj
src/Azure/Orleans.Streaming.EventHubs/Orleans.Streaming.EventHubs.csproj
src/Orleans.Clustering.Consul/LegacyConsulGatewayListProviderConfigurator.cs
src/Orleans.Clustering.ZooKeeper/LegacyZooKeeperGatewayListProviderConfigurator.cs
src/Orleans.Core.Legacy/Messaging/LegacyGatewayListProviderConfigurator.cs
src/Orleans.Core/Configuration/Options/GatewayOptions.cs
src/Orleans.Core/Messaging/GatewayManager.cs
src/Orleans.Core/Messaging/ILegacyGatewayListProviderConfigurator.cs
src/Orleans.Core/Messaging/StaticGatewayListProvider.cs
src/Orleans.Runtime.Abstractions/MembershipService/ILegacyMembershipConfigurator.cs
test/TesterAzureUtils/AzureMembershipTableTests.cs
test/TesterInternal/GatewaySelectionTest.cs
test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs

Removed Orleans.Core.Legacy dependency from:
Orleans.Cluster.AzureStorage
Orleans.Reminders.AzureStorage
Orleans.Streaming.Eventhubs

Removed Core.Legacy dependency some azure extension pacakges

---

src/Azure/Orleans.Streaming.AzureStorage/Storage/AzureQueueDataManager.cs

Did a simple pass on sanitizing azure queue name which I think is pretty safe. 
@sebastianburckhardt  have you found the sanitization code you mentioned? Can you paste it here? 
Don't merge it yet. I want to compare the code which @sebastianburckhardt mentioned and make a decision.

Sanitize azure queue name

---

src/Orleans.Core.Abstractions/Core/Grain.cs

Fixes #3911 except for `Participate`.

Make most methods of Grain class non-virtual

---

src/Orleans.Core/Messaging/ClientMessageCenter.cs
src/Orleans.Core/Messaging/GatewayConnection.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs

Rename `ProxiedMessageCenter` to `ClientMessageCenter`

Rename ProxiedMessageCenter to ClientMessageCenter

---

src/Orleans.Runtime.Legacy/Configuration/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/Configuration/Validators/EndpointOptionsValidator.cs
src/Orleans.Runtime/Hosting/EndpointOptions.cs
test/NonSilo.Tests/SiloHostBuilderTests.cs

* Add default values for `EndpointOptions`
* Add ip value check in the validator

Endpointoptions default values

---

test/TesterAzureUtils/GenericGrainsInAzureStorageTests.cs
test/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureBlobStore.cs
test/TesterAzureUtils/Persistence/PersistenceProviderTests.cs

Only config/initialization issues in functional tests

Fix various AzureStorage tests

---

src/Orleans.Core/Lifecycle/LifecycleObservable.cs
src/Orleans.Runtime/Silo/Silo.cs

Attempt to address performance issues related to silo lifecycle.
- Silo lifecycle actions are not run in lifecycle context.

Silo lifecycle performance fix

---

src/AWS/Orleans.Clustering.DynamoDB/AWSUtilsHostingExtensions.cs
src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBGatewayListProvider.cs
src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBMembershipTable.cs
src/AWS/Orleans.Clustering.DynamoDB/Membership/LegacyDynamoDBGatewayListProviderConfigurator.cs
src/AWS/Orleans.Clustering.DynamoDB/Membership/LegacyDynamoDBMembershipConfigurator.cs
src/AWS/Orleans.Clustering.DynamoDB/Options/DynamoDBClusteringOptions.cs
src/AWS/Orleans.Clustering.DynamoDB/Options/DynamoDBGatewayOptions.cs
src/AWS/Orleans.Persistence.DynamoDB/Hosting/DynamoDBSiloBuilderExtensions.cs
src/AWS/Orleans.Persistence.DynamoDB/Options/DynamoDBStorageOptions.cs
src/AWS/Orleans.Persistence.DynamoDB/Orleans.Persistence.DynamoDB.csproj
src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
src/AWS/Orleans.Reminders.DynamoDB/LegacySiloReminderConfigurationAdapter.cs
src/AWS/Orleans.Reminders.DynamoDB/Properties/AssemblyInfo.cs
src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDBReminderTable.cs
src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDbReminderStorageOptions.cs
src/AWS/Orleans.Reminders.DynamoDB/SiloHostBuilderReminderExtensions.cs
src/AWS/Shared/Storage/DynamoDBStorage.cs
src/Orleans.Core.Abstractions/Properties/AssemblyInfo.cs
test/AWSUtils.Tests/LivenessTests.cs
test/AWSUtils.Tests/MembershipTests/DynamoDBMembershipTableTest.cs
test/AWSUtils.Tests/Reminder/DynamoDBRemindersTableTests.cs
test/AWSUtils.Tests/StorageTests/AWSTestConstants.cs
test/AWSUtils.Tests/StorageTests/DynamoDBStorageProviderTests.cs
test/AWSUtils.Tests/StorageTests/PersistenceGrainTests_AWSDynamoDBStore.cs
test/AWSUtils.Tests/StorageTests/UnitTestDynamoDBStorage.cs
test/AWSUtils.Tests/Streaming/SQSStreamTests.cs
test/TesterInternal/ReentrancyTests.cs

This updates the AWS libraries use options and lifecycle rather than the legacy provider model.
Work was done by @galvesribeiro, I'm just shepherding it through the process.

Port AWS libraries to use options/lifecycle.

---

Samples/README.txt

Add missing **l** in Loca**l**host

Fix typo in Samples/README.txt

---

src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Versions/GrainVersionStore.cs

Start GrainVersionStore later at runtime

---

src/Orleans.Core/Configuration/Options/ClusterOptions.cs
src/Orleans.Core/Core/ClientBuilderExtensions.cs
src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
src/Orleans.Runtime/MembershipService/GrainBasedMembershipTable.cs
src/Orleans.Runtime/Silo/Silo.cs
test/DefaultCluster.Tests/StatelessWorkerTests.cs
test/NetCore.Tests/ExceptionTests.cs
test/TestExtensions/DefaultClusterFixture.cs
test/Tester/LocalhostSiloTests.cs
test/TesterAdoNet/Persistence/PersistenceGrainTests_AdoNetSql.cs
test/TesterInternal/ClientInitTests.cs
test/TesterInternal/TesterInternal.csproj

Fixes most of #4086
Fixes #4084

Improve usability of dev cluster

---

src/Orleans.Runtime/Utilities/SiloUnobservedExceptionsHandler.cs

To be consistent with other extension methods

Make UseSiloUnobservedExceptionsHandler return ISiloHostBuilder

---

src/Orleans.Core/Runtime/OutgoingCallInvoker.cs

This shouldn't have been included originally.

Remove unsupported functionality from OutgoingCallInvoker

---

src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs
test/TesterInternal/TestRunners/GrainPersistenceTestRunner.cs

Fixes #3418
The ADO.NET storage provider was unable to correctly handle nested generic types.
This PR adds support for nested generics.
An ad-hoc test to compare the modified method with the existing method indicates that the modified method is backwards-compatible for simple generics. The string I tested was:
`UnitTests.Grains.GrainStorageGenericGrain`1[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]`
I'd prefer if we didn't have to go down this route of converting a Type into a string and then parsing it and reformatting it into a slightly prettier string.
Note that both the existing method and the modified method are unable to correctly distinguish arrays. I don't think we should add array support in this PR - it means fundamentally changing …

ADO.NET: Fix formatting of generic class names in storage provider

---

src/AdoNet/Orleans.Persistence.AdoNet/MySQL-Persistence.sql

MySQL-Persistence.sql execution error   ([4126](https://github.com/dotnet/orleans/issues/4126))

Update MySQL-Persistence.sql 

---

src/Orleans.Core/Configuration/Options/StaticGatewayListProviderOptions.cs
src/Orleans.Core/Messaging/StaticGatewayListProvider.cs

Use List instead of IList in StaticGatewayListProviderOptions
