vNext/src/Orleans.vNext.sln
vNext/test/TestGrainInterfaces/TestGrainInterfaces.csproj
vNext/test/TestGrains/TestGrains.csproj
vNext/test/TestInternalGrainInterface/Properties/AssemblyInfo.cs
vNext/test/TestInternalGrainInterface/TestInternalGrainInterfaces.csproj
vNext/test/TestInternalGrainInterface/project.json
vNext/test/Tester/Tester.csproj

This lives on top of #2322 . will need to wait for #2322 to be pushed and then rebase. 
Move tests in Tester which uses HostedTestClusterEnsureDefaultStarted to vNext Tester project. 
Some tests test persistence, so we will need to port over OrleansProviders project soon.

Move tests in Tester which uses HostedTestClusterEnsureDefaultStarted to vNext

---

vNext/test/TestInternalGrains/project.json

upgrade xunit.assert to be 2.1.0 in TestInternalGrains to inline with Tester dependency

 upgrade xunit.assert to be 2.1.0 in TestInternalGrains

---

test/TesterInternal/StorageTests/PersistenceGrainTests.cs

Reduce number of loops of perf test. This was taking too long at max CPU and making AppDomains stop responding and stall the entire test run.
It's not a test marked BVT or Functional, so it's almost never run, but in the cases where we did manually run it, it was not working even in a very powerful desktop with lots of cores and RAM.

Avoid manual perf test to stall the entire test run

---

src/Orleans/Serialization/BuiltInTypes.cs
src/Orleans/Serialization/SerializationManager.cs
test/NonSiloTests/Serialization/BuiltInSerializerTests.cs
test/TestGrainInterfaces/CodegenTestInterfaces.cs

The first commit ensures that the fallback serializer is not available for most of the tests in BuiltInSerializerTests - most tests should pass without the fallback.
The second commit registers a serializer for `RuntimeType` (the runtime type of `Type` 😉), aligns the serializer with the deserializer, and adds a test.

RuntimeType serialization

---

src/Orleans/Core/GrainAttributes.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeData.cs
test/TestExtensions/HostedTestClusterBase.cs
test/TestGrainInterfaces/IReentrancyGrain.cs
test/TestGrains/ReentrantGrain.cs
test/TesterInternal/ReentrancyTests.cs

Hi guys!
As you know Orleankka provides a functional message-based style API for Orleans and all grains have a uniform interface like: 
```cs
interface IActor
{
Task<object> Receive(object msg);
}
```
To support some advanced scenarios like ability to specify message interleaving in a more granular way (per-message type) which is incredibly valuable feature we extended this interface with additional method:
```cs
interface IActor
{
Task<object> Receive(object msg);
[AlwaysInterleave] Task<object> ReceiveReentrant(object msg);
}
```
So when sending a message via actor reference we were selecting one method ot the other depending on the configuration for this message/actor type.
I'm preparing next big and updated release (1.0, ya finally!) and most anticipated feature is to be able to send …

Ability to specify interleaving per message type

---

Build.cmd
src/Orleans.SDK.targets
src/Orleans/Runtime/RequestContext.cs
vNext/src/Build.cmd
vNext/src/Orleans.SDK.targets
vNext/src/Orleans/Shims/AppDomain.cs
vNext/src/OrleansProviders/OrleansProviders.csproj
vNext/src/OrleansProviders/project.json
vNext/src/OrleansRuntime/OrleansRuntime.csproj
vNext/src/OrleansRuntime/project.json
vNext/test/NonSiloTests/project.json
vNext/test/Tester/project.json

This PR supersedes #2215.
There's several fixes to how we build the vNext solution.
Also added a build script for the command line that can be used from CI (although it's not enabled by the CI build yet, since the build agent doesn't support .NET 4.6.2 but will soon).

Several build fixes for vNext solution and support command line

---

src/Orleans/Serialization/ILSerializerGenerator.cs

Small PR which just reduces the scope of an optimization used for serializing values which BinaryTokenStreamReader/Writer can read/write directly.
The issue (found by @attilah in a case where the fallback shouldn't've been used anyhow) arises when fields of those types are `null`, since BinaryTokenStreamReader/Writer expect that to be handled at a layer above, so `NullReferenceException` is thrown.
This could be handled in IL, but I don't want to make either the generator or the emitted code complex at this stage.
After this PR, only value types will be directly serialized.

ILBasedSerializer: remove direct serializers for class types

---

vNext/src/Build.cmd
vNext/src/NuGet/ClientInstall.ps1
vNext/src/NuGet/CreateOrleansPackages.bat
vNext/src/NuGet/Microsoft.Orleans.Client.nuspec
vNext/src/NuGet/Microsoft.Orleans.Core.nuspec
vNext/src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.Build.nuspec
vNext/src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.nuspec
vNext/src/NuGet/Microsoft.Orleans.OrleansProviders.nuspec
vNext/src/NuGet/Microsoft.Orleans.OrleansRuntime.nuspec
vNext/src/NuGet/Microsoft.Orleans.Server.nuspec
vNext/src/NuGet/Microsoft.Orleans.TestingHost.nuspec
vNext/src/NuGet/ServerInstall.ps1
vNext/src/Orleans.vNext.sln
vNext/src/Orleans/Orleans.csproj

This builds the packages for the vNext solution

Build NuGet packages for Orleans 2.0 (.NET Standard)

---

test/TestGrains/ExternalTypeGrain.cs
test/Tester/ExternalTypesTests.cs
vNext/src/Orleans/Shims/AppDomain.cs

- Load referenced assemblies.
- Use application base path, as when using .NET Core the relative path is not where the application is deployed, but it is in the probing path as expected.

Fix AppDomain shim to work well in .NET Core

---

test/TestServiceFabric/TestServiceFabric.csproj

Mark TestServioceFabric as a testing project.
Visual Studio [2015] on my machine keeps adding this annotation to the `TestServiceFabric.csproj` file to mark it as a project containing test cases to detect / run.
``` xml
<ItemGroup>
<Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
</ItemGroup>
```
More info about this is available in this Stack Overflow question / answer:
http://stackoverflow.com/questions/18614342/what-is-service-include-in-a-csproj-file-for

Mark TestServioceFabric as a testing project.

---

README.md

The issue stats badges have been broken for a while and they don't seem to be coming back (site is 503'ing). The build status badge is also broken.
We could add build status for .NET Standard, but I feel we should wait until we are almost ready to release it.

Fix README Badges

---

vNext/test/Tester/Tester.csproj

This allows us to continue porting tests to the .NET Standard project.
Required for #2364, since it requires a separately configured cluster to function correctly.

Enable xUnit text settings in .NET Standard Tester project

---

src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/OrleansServiceBus/Providers/Streams/EventHub/DefaultEventHubReceiverMonitor.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubReceiverMonitor.cs
test/Tester/TestStreamProviders/EventHub/StreamPerPartitionEventHubStreamProvider.cs

* Block writes on readonly stream providers.
* Support monitoring of initialization and shutdown of EventHub stream provider receivers.
* Support customization of EventHub stream provider direction.
* Fix incomplete EventHubStreamProvider receiver monitoring. User could not specify custom monitoring.
* Support custom data comparer in EventHubStreamProvider cache.

EventHubStreamProvider improvements

---

src/OrleansCodeGenerator/GrainReferenceGenerator.cs

Low pri.
Response to [a comment](https://github.com/dotnet/orleans/pull/2383/files#r86830788) on #2383.
Fixes a corner case: we do not support concrete `Grain` classes as the static type of a grain method parameter. We current attempt to cast grain instances to grain class types.
This fixes that. It does not add any new functionality, but the runtime error will now say "Cannot pass a grain object ...." instead of ~"Cannot find generated GrainReference class for interface '<your grain class type here>'".

GrainReferenceGenerator should not call .AsReference<T>() where T is a class

---

src/OrleansRuntime/Placement/ActivationCountPlacementDirector.cs

Small tweak to simplify usage of `ActivationCountPlacementDirector` in our internal load tests

ActivationCountPlacementDirector: allow null DeploymentLoadPublisher

---

src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql
src/OrleansSQLUtils/Storage/Provider/AdoGrainKey.cs
src/OrleansSQLUtils/Storage/Provider/AdoNetStorageProvider.cs
src/OrleansSQLUtils/Storage/Provider/IStorageHashPicker.cs
src/OrleansSQLUtils/Storage/Provider/OrleansDefaultHasher.cs
test/TesterInternal/StorageTests/AWSUtils/DynamoDBStorageProviderTests.cs
test/TesterInternal/StorageTests/Relational/AdotNetProviderFunctionalityTests.cs
test/TesterInternal/StorageTests/Relational/CommonStorageTests.cs
test/TesterInternal/StorageTests/Relational/MySqlStorageTests.cs
test/TesterInternal/StorageTests/Relational/RelationalStorageTests.cs
test/TesterInternal/StorageTests/Relational/SqlServerStorageTests.cs
test/TesterInternal/TesterInternal.csproj

* Removes deadlocking on rapid insert of initial
grain states by rearranging locking functionality.
* Removes a problem that was mainly seen in highly
concurrent grain state hashing where the hash of
the state grain type was corrupted in some minor ratio.
This basically led some grain states to be unretrievable.
* Adds a directive to prohibit lock escalation. This could
become a problem if the Storage table gets large and concurrent
operations exceed the threshold (5000) locks in which case
SQL Server reacts by tacking a table lock for operations. On
a large table this would be very problematic.
* Minor clean up on logging where the grain ID was logged twice
concatenated and testing where "MySQL" was applied to SQL Server tests
and some tests added to ensure some helper classes function …

Removes deadlocking and corrupted hashing

---

src/OrleansRuntime/Streams/LoadShedQueueFlowController.cs

Math cleanup for improved usability introduced cast bug, where percentage calculation was alway zero.
Percision math is used for calculation and cast to integer afterwards.

LoadShedQueueFlowControl cast fix

---

src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs

Allow event hub cache users to specify max read count and flow control threshold.

EventHub flow control customization knobs

---

src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapter.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapterFactory.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapterReceiver.cs
src/OrleansAzureUtils/Storage/AzureQueueDataManager.cs
test/TesterInternal/StorageTests/AzureQueueDataManagerTests.cs
test/TesterInternal/StreamingTests/AzureQueueAdapterTests.cs

When using the Azure Queue based stream provider, I occasionally see both warnings about queue message deletes being slow coupled with errors related to message deletes failing. The errors appear to be happening because, while waiting to be deleted, the message visibility timeout expires and the message becomes visible in the queue again which renders the poprecipt invalid and causes a 404 on delete. This change allows for configuring the message visibility timeout value to allow for a larger window for both processing and deletes to be completed. Setting the timeout to 2min (vs 30sec default) has eliminated these errors for me, even in cases where I still see the slowness warnings.

Azurequeueprovider messagevisibilityconfig

---

src/Orleans/Messaging/IncomingMessageBuffer.cs
src/Orleans/Messaging/Message.cs
src/OrleansRuntime/Messaging/IncomingMessageAcceptor.cs
test/NonSiloTests/SerializerTests/MessageSerializerTests.cs
test/TestGrainInterfaces/IExceptionGrain.cs
test/TestGrains/MessageSerializationGrain.cs
test/TestGrains/TestGrains.csproj
test/Tester/ExceptionPropagationTests.cs
vNext/test/TestGrains/TestGrains.csproj

In some cases, a message body cannot be deserialized and so the message is dropped without notifying the caller. The call will eventually fail with a timeout exception but with no indication of why that timeout occurred.
This PR propagates body deserialization exceptions back to the caller.
Instead of deserializing the body in the `Message` constructor, this PR moves the assignment of the body to a separate method. This way, the partially-deserialized message is still valid and has correctly deserialized headers, so a failure response can be constructed.

Propagate exceptions during message body deserialization

---

src/Orleans/CodeGeneration/TypeUtils.cs

Do not generate serializers for types that have all serialization methods regardless of their visibility

Do not generate serializers if non-public serializer methods are defined

---

test/Tester/MembershipTests/SilosStopTests.cs

SiloUngracefulShutdown_OutstandingRequestsBreak fails randomly on Functional tests, this fix make the test more robust.

Make SiloUngracefulShutdown_OutstandingRequestsBreak more resilient

---

src/OrleansCodeGenerator/SerializerGenerator.cs
test/TestGrainInterfaces/IChainedGrain.cs
test/TestGrains/ChainedGrain.cs
test/TesterInternal/GrainReferenceTest.cs

Modified CodeGenerator to check if the item being DeepCopied is an IAddressable before DeepCopying, converting to IGrainReference if so.
Details provided in https://github.com/dotnet/orleans/issues/2382

Check IAddressable before DeepCopy

---

changelog.md
src/Orleans/Serialization/SerializationManager.cs
src/OrleansAWSUtils/Streams/SQSBatchContainer.cs
src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansAzureUtils/Properties/AssemblyInfo.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueBatchContainer.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueBatchContainerV2.cs
src/OrleansProviders/OrleansProviders.csproj
src/OrleansProviders/Streams/Common/EventSequenceTokenV2.cs
src/OrleansProviders/Streams/Generator/GeneratorPooledCache.cs
src/OrleansProviders/Streams/Generator/Generators/SimpleGenerator.cs
src/OrleansProviders/Streams/Memory/MemoryPooledCache.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubBatchContainer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubSequenceTokenV2.cs
test/NonSiloTests/Orleans.NonSiloTests.csproj
test/NonSiloTests/SerializationTests/ExternalSerializerTest.cs
test/NonSiloTests/SerializationTests/StreamTypeSerializationTests.cs
test/Tester/TestStreamProviders/EventHub/StreamPerPartitionEventHubStreamProvider.cs
test/TesterInternal/OrleansRuntime/Streams/CachedMessageBlockTests.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs
test/TesterInternal/StreamingTests/AzureQueueAdapterTests.cs
test/TesterInternal/StreamingTests/SQSAdapterTests.cs
vNext/src/OrleansProviders/OrleansProviders.csproj

- implement serializers for AzureQueueBatchContainer and EventSequenceToken.  They were routed to the fallback serializer which caused them to be incompatible with external serializers
- added unit tests to verify serialization/deserialization with external serializers.

Modified stream types to not use fallback serializer and allow external

---

src/ClientGenerator/ClientGenerator.cs

ClientGenerator: do not emit error.txt after failed codegen

---

src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueBatchContainer.cs

V2 messaging is Compatible with V1, but V2 containers expect V2 tokens, so we musta always generate v2 tokens.
This should fix the failing azure queue functional tests.

Azure queue stream provider silo to silo serialization bug.

---

src/Orleans/Logging/ErrorCodes.cs
src/OrleansRuntime/Silo/SiloHost.cs

As part of #2145, in order to make the `SiloHost` to start without problem, we have to not rely on `EventWaitHandle` since it is not available on linux because named mutexes are not supported in it.
For the crawl phase, we are just catching `PlatformNotSupportedException`, logging and moving forward. In walk phase, we should implement event signaling for graceful shutdown on linux by using POSIX semaphores or SIGNALs.
This is a fix for #2366.

Ignore EventWaitHandle when not available

---

src/OrleansCodeGenerator/CodeGeneratorCommon.cs

When using runtime codegen in .NET Core, there are some issues with duplicate types being exposed by the .NET Core runtime. We are temporarily using a workaround to avoid linking to those duplicate types that are outside of the exposed façades.

Avoid getting duplicate type errors when using runtime codegen.

---

src/OrleansCodeGenerator/CodeGeneratorCommon.cs

Make generated code to produce portable PDB to support cross-platform initiatives.

Enable Portable PDBs for generated assembly

---

src/Orleans/CodeGeneration/TypeUtils.cs
test/NonSiloTests/CodeGeneratorTests.cs

fix test UnitTests.CodeGeneration.CodeGeneratorTests.ServiceInterface_IsGrainClass
full name of `Orleans.Runtime.SystemTarget` is "Orleans.Runtime.SystemTarget" instead of "Orleans.Runtime.SystemTarget, OrleansRuntime"

fix test UnitTests.CodeGeneration.CodeGeneratorTests.ServiceInterface_IsGrainClass

---

test/TesterAzureUtils/Persistence/PersistenceProviderTests.cs
vNext/test/TesterAzureUtils/App.config

For when tests are run in a single output folder where runtime codegen DLL is available.

Fix binding redirects for functional tests

---

vNext/src/Build.cmd

This makes the release packages also contain a build date for now.
For example packages will now be called something like:
`Microsoft.Orleans.OrleansRuntime.2.0.0-preview1-201612021300`
instead of just:
`Microsoft.Orleans.OrleansRuntime.2.0.0-preview1`

Make Release nuget packages also contain build date in vNext

---

src/Orleans/Serialization/TypeUtilities.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
test/TestGrainInterfaces/CodegenTestInterfaces.cs
test/TesterInternal/CodeGeneratorTests_AccessibilityChecks.cs
test/TesterInternal/TesterInternal.csproj

Runtime codegen cannot support `internal` grain interfaces, whereas compile-time codegen can.
This change makes the code generator take that into account and adds a test to verify the correct behavior.

CodeGen: runtime codegen should check accessibility of grain interfaces.

---

src/OrleansCodeGenerator/RoslynCodeGenerator.cs

Eliminates some unnecessary constraints on the kinds of generic type implementations which codegen will consider implementing serializers for.
The expectation is that this should not hurt code generation performance significantly and that it removes some uneccessary dependencies on other classes from the code generator.
@attilah this is for you.

CodeGen: Eliminate unnecessary constraints on generic types

---

src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Configuration/NodeConfiguration.cs
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Runtime/GrainInterfaceMap.cs
src/Orleans/Runtime/ITypeManager.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs
src/OrleansRuntime/GrainTypeManager/SiloAssemblyLoader.cs
src/OrleansRuntime/GrainTypeManager/TypeManager.cs
src/OrleansRuntime/Placement/ActivationCountPlacementDirector.cs
src/OrleansRuntime/Placement/IPlacementContext.cs
src/OrleansRuntime/Placement/PreferLocalPlacementDirector.cs
src/OrleansRuntime/Placement/RandomPlacementDirector.cs
src/OrleansRuntime/Silo/Silo.cs
test/Tester/ExceptionPropagationTests.cs
test/Tester/HeterogeneousSilosTests/HeterogeneousTests.cs
test/Tester/MembershipTests/SilosStopTests.cs
test/Tester/Tester.csproj
test/TesterInternal/General/ElasticPlacementTest.cs

This is a PR for #2379 
Currently, the GrainInterfaceMap is built on each silo, and is sent to clients when they connect to a gateway.
I tried to divide the PR in logical commits so it is easier to review:
- To test this functionality easily, I added a list of grain types that are ignored by the AssemblyLoader. (bbc118d and f793f2f). 
- Add a notion of “cluster wide” GrainInterfaceMap, that is a merge of all GrainInterfaceMaps built locally on each silo. (568cf00, 4bdc77a and 3aab754)
- Expose this new global GrainInterfaceMap to the clients (3aab754)
- Rebuild the global GrainInterfaceMap when new silos join the cluster (a259b31 and adf6ea1)
- Modify PlacementDirector to only consider “compatible”silos. (83057de and 77e80d8)
To avoid race conditions and complicated error handling, we …

Heterogenous silos support 

---

src/Orleans/Logging/LoggerExtensions.cs

`params` has a cost associated even when no parameters are passed, so this adds overloads to `LoggerExtensions` methods in order to provide non-allocating alternatives.

Reduce allocations when logging

---

src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Streams/Providers/IStreamProviderRuntime.cs
src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs
src/OrleansRuntime/Cancellation/CancellationSourcesExtension.cs
src/OrleansRuntime/Catalog/GrainCreator.cs
src/OrleansRuntime/Core/BootstrapProviderManager.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Core/ISiloRuntimeClient.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/GrainTypeManager/TypeManager.cs
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Storage/StorageProviderManager.cs
src/OrleansRuntime/Streams/StreamProviderManagerAgent.cs
test/NonSiloTests/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs
test/TestInternalGrains/ExtensionTestGrain.cs
test/TestInternalGrains/PersistenceTestGrains.cs
test/TestInternalGrains/Properties/AssemblyInfo.cs
test/TestInternalGrains/StreamLifecycleTestGrains.cs
test/TestInternalGrains/StreamLifecycleTestInternalGrains.cs
test/TestInternalGrains/TestExtension.cs
test/Tester/SimpleGrainTests.cs
test/TesterAzureUtils/Persistence/PersistenceProviderTests.cs
test/TesterInternal/StorageTests/AWSUtils/DynamoDBStorageProviderTests.cs
test/TesterSQLUtils/StorageTests/Relational/CommonFixture.cs

* Removed `SiloProviderRuntime.Instance` global
* Adds a new interface, `ISiloRuntimeClient`, which contains methods moved from `SiloProviderRuntime`.
* `GrainCreator` now always uses `ActivatorUtilities.CreateFactory` instead of `Activator.CreateInstance`, meaning that grain classes with multiple public constructors cannot be constructed unless they are explicitly registered. @jdom are you fine with this? This behavior is consistent with ASP.NET as far as I know.
* Some methods on `SiloProviderRuntime` are now forwarded to `InsideRuntimeClient` where I think they are a more natural fit. We can move them elsewhere if desired.
This is working towards #467. The idea is to make multiple smaller commits to remove globals so that we can implement support for multiple distinct grain clients per …

Reduce use of globals in SiloProviderRuntime

---

Samples/AzureWebSample/OrleansAzureSample/OrleansAzureSample.ccproj

Fix issue: #2475 
VS Debugger cannot attach to the web role process because of the conflicting setting of using IISExpress or IIS between the Web role and the Web project itself.

Fix conflicthing VS setting which makes debugging stalls

---

src/NuGet/Microsoft.Orleans.OrleansConsulUtils.nuspec
src/OrleansConsulUtils/project.json

Consul 0.7.0.0 introduced the usage of ```CancellationToken``` arguments for all remote calls, this caused a ```MethodNotFoundException``` as described and discovered in #2488, this PR fixes that by upgrading to newer package.

Update to Consul 0.7.0.3 package, fixed #2488

---

src/Orleans/CodeGeneration/GrainInterfaceUtils.cs
src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/ITraceConfiguration.cs
src/Orleans/Configuration/NodeConfiguration.cs
src/Orleans/Logging/ConsoleText.cs

Issue #2464 
By default in the config we output log to the console (`TraceToConsole` set to `true`). The proposed fix is to check if a console is available and use that value as the default for `TraceToConsole`

Fix for "Console output caused Orleans Worker Role to restart"

---

src/Orleans/CodeGeneration/GrainInterfaceUtils.cs
src/Orleans/Core/InterceptedMethodInvokerCache.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Core/SystemTarget.cs
test/NonSiloTests/CodeGeneratorTests.cs
test/TestGrainInterfaces/IMethodInterceptionGrain.cs
test/TestGrains/MethodInterceptionGrain.cs
test/Tester/MethodInterceptionTests.cs

Fixes #2358. 
* Previously there were two methods used to get an id for a grain interface, with slightly different behaviour. That seemed to be erroneous and so `ComputeInterfaceId` was removed in favour of `GetGrainInterfaceId`.
* `GetGrainInterfaceId` must take into account whether or not the grain is a constructed generic. A constructed generic cannot be a grain interface as specified in code. Therefore its generic type definition is used instead.
* The `Type.GetRuntimeInterfaceMap(Type)` method does not take into account inherited interfaces, only the current interface. This would cause interceptors to receive `null` instead of the implementation's `MethodInfo`.
* Mapping between methods on a generic interface and their counterparts on a concrete class is not entirely obvious, but it …

Fix #2358: Invoke interceptor broken for generic grains

---

src/Orleans/Core/GrainAttributes.cs
src/Orleans/Streams/Internal/IStreamGrainExtensions.cs
test/TestInternalGrainInterfaces/IClientAddressableTestClientObject.cs
test/TestInternalGrainInterfaces/IClientAddressableTestGrain.cs
test/TestInternalGrainInterfaces/IClientAddressableTestProducer.cs

Removes the unused `[Factory(factoryType)]` attribute, which is a remnant from the old code generator.

Remove unused [Factory] attribute

---

src/Orleans/Core/Grain.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/IActivationData.cs
src/Orleans/Runtime/IGrainTimer.cs
src/Orleans/Runtime/IRuntimeClient.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/SystemTargetInterfaces/ISystemTarget.cs
src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Core/GrainRuntime.cs
src/OrleansRuntime/Core/GrainTimer.cs
src/OrleansRuntime/Core/IInvokable.cs
src/OrleansRuntime/Core/ISiloRuntimeClient.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Core/SystemTarget.cs
src/OrleansRuntime/GrainDirectory/ClientObserverRegistrar.cs
src/OrleansRuntime/MultiClusterNetwork/MultiClusterOracle.cs
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/ReminderService/LocalReminderService.cs
src/OrleansRuntime/ReminderService/LocalReminderServiceFactory.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs
test/TestInternalGrains/PersistenceTestGrains.cs

More of the same. I'm very wary of making any of these PRs large, so this isn't a huge step forward.
Generally speaking, this moves additional members from `IRuntimeClient` to `ISiloRuntimeClient` and entirely removes some members.
This also removes some of the usages of `RuntimeClient.Current`, which is one of the main goals of this series of PRs.
* Introduces an interface, `IGrainTimer` from the class `GrainTimer` in order to cleanly separate existing `IActivationData` interface from its only implementation, `ActivationData` (we could remove `IActivationData` if we don't think it's useful and use `ActivationData` instead)
* `IInvokable` was moved from `Orleans` to `OrleansRuntime` and `GrainTypeManager` was added as a parameter. I felt adding a parameter here was better than requiring …

Reduce usage of statics in IRuntimeClient implementation & usage

---

src/OrleansRuntime/Core/InsideRuntimeClient.cs
test/Tester/InvocationInterceptTests.cs

I broke the `PreInvocationCallbackWithStreamTest` test with #2502.
The test checks that `IGrainExtension`s can have their methods intercepted by grains. Previously we were passing a `null` `MethodInfo` parameter to the interceptor, since the correct implementation method could not be found.
#2502 broke that by throwing an exception in the event that an implementation method cannot be found.
This PR fixes it again by mapping the interface method to the extension method in the event that the incoming request is destined for the extension object.
As you can see, it's a very simple fix. Functionals are running.

Fix invocation interception for grain extensions

---

src/Orleans/Runtime/CallbackData.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs

Saves 2 allocations per message sent

Reduce allocations when creating CallbackData instances

---

test/DefaultCluster.Tests/TimerOrleansTest.cs
test/TestGrainInterfaces/ITimerGrain.cs
test/TestInternalGrains/TimerGrain.cs

Fix #2517 by removing that test (it doesn't add any coverage and it's flaky).
Clean up timer tests:
* Make them async
* Remove unused types
* `TimerOrleansTest_Parallel` runs the test in parallel now.

Fix #2517 & cleanup timer tests

---

src/OrleansRuntime/GrainDirectory/AdaptiveDirectoryCacheMaintainer.cs
src/OrleansRuntime/GrainDirectory/GrainDirectoryCacheFactory.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs

Fixes an error in `AdaptiveDirectoryCacheMaintainer` which was performing a type check which would never succeed. `TValue` in the below code is always `IReadOnlyList<Tuple<SiloAddress, ActivationId>>`, but the type check assumed it was `List<Tuple<SiloAddress, ActivationId>>`.
See the `//TODO:` below for the source of the error.
This removes the check and pushes the responsibility onto the caller.

Fix type assertion in AdaptiveDirectoryCacheMaintainer

---

src/Orleans/Runtime/IRuntimeClient.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Timers/IRemindable.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/ReminderService/ReminderRegistry.cs
test/TestInternalGrains/ReminderTestGrain2.cs

The guts of `ReminderRegistry` are in `InsideRuntimeClient`. `ReminderRegistry` adds some additional guards around those methods and calls into `InsideRuntimeClient` via the global `RuntimeClient.Current`.
The intention of this PR is to remove those globals and clean up the code a little bit.
* Shifts most of the reminder-related parts from `InsideRuntimeClient` and into `ReminderRegistry`
* Removes usage of globals from `ReminderRegistry`
* Removes the reminder-related methods from `IRuntimeClient` (they were not applicable for external clients), replacing them with a single `GetReminderService` method on `ISiloRuntimeClient`
* Removes some unused properties from `InsideRuntimeClient`
Related to #467

Extract ReminderRegistry implementation from InsideRuntimeClient

---

src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Configuration/GrainServiceConfiguration.cs
test/Tester/GrainServiceTests/GrainServiceTests.cs

A follow-up to #2459 and #2531. Removed unused ClientType property from GrainServiceConfiguration.
@jamescarter-le, any objections?

Removed unused ClientType from GrainServiceConfiguration

---

src/OrleansRuntime/MembershipService/MembershipTableFactory.cs

This fixes an issue introduced in #2515 whereby `IMembershipTable` instances were not being correctly initialized.
For `MembershipTableGrain`, `WaitForTableGrainToInit` is called before `InitializeMembershipTable` when running on the primary. For other providers, only `InitializeMembershipTable` is called. Since #2515, it wasn't being called.

MembershipTableFactory should call InitializeMembershipTable on tables

---

src/Orleans/Async/AsyncExecutorWithRetries.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

The recursion in AsyncExecutorWithRetries is converted by the generated async state machine to a task/continuation. Each level of the recursion generates a new continuation on the current Task to the next retry iteration. If infinite retries are specified, and the operation fails on each try, then new tasks/continuations are created indefinitely. They as well as all intermediate state (e.g. exceptions attached to previous tasks) are rooted and evade GC until either one of the retries succeeds or all virtual memory is consumed. #2533
This change does the retries in a loop instead of using recursion, allowing intermediate tasks to examined and released for GC.

Make AsyncExecutorWithRetries non-recursive

---

src/Orleans/Messaging/IGatewayListProvider.cs
src/Orleans/Runtime/ILocalSiloDetails.cs
src/OrleansRuntime/Core/IHealthCheckParticipant.cs
src/OrleansRuntime/MembershipService/IMembershipOracle.cs
src/OrleansRuntime/MembershipService/ISiloStatusListener.cs
src/OrleansRuntime/MembershipService/ISiloStatusOracle.cs
test/NonSiloTests/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs

This PR exposes the interfaces required for external implementations of `IMembershipOracle`.
It also exposes `ILocalSiloDetails`, because it's useful to have when implementing `IMembershipOracle`.
Required by #2542.
cc @galvesribeiro

Expose IMembershipOracle & related interfaces

---

vNext/src/NuGet/Microsoft.Orleans.PlatformServices.nuspec

When using project.json + full framework, the pre-release Orleans.PlatformServices nuget fails installation with the message:
```
System.Runtime.Loader 4.3.0 provides a compile-time reference assembly for System.Runtime.Loader on .NETFramework,Version=v4.6.2, but there is no run-time assembly compatible with win.
One or more packages are incompatible with .NETFramework,Version=v4.6.2 (win).
System.Runtime.Loader 4.3.0 provides a compile-time reference assembly for System.Runtime.Loader on .NETFramework,Version=v4.6.2, but there is no run-time assembly compatible with win-anycpu.
One or more packages are incompatible with .NETFramework,Version=v4.6.2 (win-anycpu).
```
This PR fixes that by explicitly specifying that no dependencies are required in the PlatformServices nuget when using the …

Explicitly specify no deps for net462 in Orleans.PlatformServices nuget

---

src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Serialization/TypeUtilities.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs
test/TestGrainInterfaces/CodegenTestInterfaces.cs

Fixes #2433.
The issue was that our check to see if a type already has a serializer wasn't checking if each of the generic type parameters also had serializers, so accessibility checks were broken for those types.

CodeGen: fix check on parameters to generic types with serializers

---

src/Orleans/IDs/ActivationId.cs
src/Orleans/IDs/GrainId.cs
src/Orleans/IDs/GuidId.cs
src/Orleans/IDs/Interner.cs
src/Orleans/IDs/QueueId.cs
src/Orleans/IDs/StreamId.cs
src/Orleans/Logging/LogManager.cs
test/NonSiloTests/General/Identifiertests.cs

Cleans up the `Interner` class so that allocations do not occur on the hot path.
* Avoid allocating a closure for the `createFunc` parameter if possible
* Avoid closure allocations within `Interner.FindOrCreate`
* Converted to `WeakReference<T>` instead of `WeakReference` in order to simplify the code.

Reduce allocations in Interner

---

src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Startup/StartupBuilder.cs
src/OrleansRuntime/Utilities/ServiceCollectionExtensions.cs

Simple change to pre-construct & add services to the DI container before passing it to the startup builder, rather than passing a lambda to add the services to it.
Since we're constructing the container and passing it to the user, 'TryAdd' was misleading, so we're calling 'Add' now.

Simplify initialization of DI container

---

src/Orleans/Runtime/GrainReference.cs

Until https://github.com/dotnet/roslyn/issues/5835 is implemented, every grain call will currently perform 1 allocation for the response callback method group delegate.
This simply caches that in a static field.
```
// [350 13 - 350 131]
IL_0087: call         class Orleans.Runtime.IRuntimeClient Orleans.Runtime.RuntimeClient::get_Current()
IL_008c: ldarg.0      // this
IL_008d: ldarg.1      // 'request'
IL_008e: ldloc.1      // resolver
// allocate for the method group
IL_008f: ldnull       
IL_0090: ldftn        void Orleans.Runtime.GrainReference::ResponseCallback(class Orleans.Runtime.Message, class [mscorlib]System.Threading.Tasks.TaskCompletionSource`1<object>)
IL_0096: newobj       instance void class [mscorlib]System.Action`2<class Orleans.Runtime.Message, class …
```

Cache ResponseCallback delegate in GrainReference to reduce allocs

---

src/Orleans/Configuration/GlobalConfiguration.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansTestingHost/TestClusterOptions.cs
test/Tester/HeterogeneousSilosTests/HeterogeneousTests.cs

Add flag for test to assume that all silos in the cluster share the same set of grain types at startup
Some tests are failing because all silos didn't refreshed the cluster interface map in time before the test started. 
To avoid introducing delay in the test startup, we assume that all silos not in the cluster type map support the same set of types as the local one.

Add flag for test to assume that all silos in the cluster share the same set of grain types at startup

---

src/OrleansRuntime/GrainDirectory/ClientObserverRegistrar.cs
src/OrleansRuntime/Silo/Silo.cs
test/TestGrainInterfaces/ISimpleObserverableGrain.cs
test/TestGrains/SimpleObserverableGrain.cs
test/TesterInternal/MembershipTests/ClientIdPartitionDataRebuildTests.cs
test/TesterInternal/TesterInternal.csproj

From #2519 
When a silo stop is dead, we loose all data that was on its directory, including client entries. We already have a mechanism that refresh these entries every `ClientRegistrationRefresh` in `ClientObserverRegistrar`.
To improve reliability in this case, `ClientObserverRegistrar` we could listen to membership change, and force a refresh of the clientId entries that are connected to the gateway, without waiting for the timer to fire.

Trigger registration of clients connected to the gateways in the directory when a silo is dead

---

src/Orleans/Configuration/GlobalConfiguration.cs
test/NonSiloTests/ConfigTests.cs
test/NonSiloTests/Config_Custom_Membership_No_Reminders.xml
test/NonSiloTests/Orleans.NonSiloTests.csproj

Fix for #2527 
In XML config we only have one setting `SystemStoreType` that set both `LivenessType` and `ReminderServiceType`, so we cannot set `LivenessType` to Custom and `ReminderServiceType` to disabled.
To work around this, now if `SystemStoreType` is set to Custom and that no `ReminderTableAssembly` are provided, we set `ReminderServiceType` to disabled

in XML config, if SystemStoreType set to Custom but no ReminderTableAssembly are specified, assume that ReminderServiceProviderType is set to Disabled

---

src/Tutorials/Unit-Testing-Grains.md

Quick fix for #1600.  Samples are now ```Fact```s rather than ```TestClass``` and ```TestMethod```.  Also renamed the test method to more closely follow the xUnit naming conventions

Update Unit-Testing-Grains to feature XUnit

---

src/Orleans/Serialization/SerializationManager.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansCodeGenerator/SerializerGenerator.cs
test/DefaultCluster.Tests/JsonGrainTests.cs

* When we encounter a type, eg `SerializerType`, with a `[Serializer(typeof(TargetType))]` attribute, we register the type as the serializer for `TargetType`. I.e, `SerializationManager.Register(typeof(TargetType), typeof(SerializerType))`
* Avoid generating `Register` methods
* Avoid adding `[RegisterSerializer]` attribute
* Avoid generating non-generic "master registerer" class for generic types
This code was extracted from #2592
This is a non-breaking change

Serialization/CodeGen: Avoid generating Register methods

---

vNext/src/ClientGenerator/BootstrapCodegen.proj

Apparently when building in VS things are still different, so building the projects one-by-one was re-added to proj file.

Fix building in VS2017 RC2.

---

src/Orleans/Configuration/ClientConfiguration.cs

Spotted this very small typo whilst having a look through the tutorials.

Fix xml doc typo

---

src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs

When logging was added to EventHubQueueCache purge the base class purge function, which triggers checkpoint logic, was not called.  This broke periodic checkpointing.

BugFix: EventHubQueueCache failing to write checkpoints on purge.

---

src/OrleansSQLUtils/CreateOrleansTables_MySql.sql

Adds native JSON support to MySQL
MySQL 5.7.8 added a native JSON type, release notes
https://dev.mysql.com/doc/refman/5.7/en/json.html.
As we currently support only the latest version, this
could be included without regard to older versions. A small
problem is the official packet was released already and the
type there is plain text.
This alter to the table is backwards compatible, but for very
large tables can be time consuming.

Adds native JSON support to MySQL

---

src/Orleans/Core/GrainStateStorageBridge.cs
src/Orleans/Providers/IStorageProvider.cs
src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
src/OrleansAzureUtils/Storage/Exceptions.cs
src/OrleansAzureUtils/Storage/StorageExceptionExtensions.cs

Azure table storage throws InconsistentStateException upon a write conflict.
See issue "Storage providers have to throw an InconsistentStateException upon a write conflict #1609"

Azure table storage throws InconsistentStateException

---

src/NuGet/Microsoft.Orleans.Core.nuspec
src/NuGet/Microsoft.Orleans.CounterControl.nuspec
src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.nuspec
src/NuGet/Microsoft.Orleans.OrleansHost.nuspec
src/NuGet/Microsoft.Orleans.OrleansManager.nuspec
src/NuGet/Microsoft.Orleans.OrleansProviders.nuspec
src/NuGet/Microsoft.Orleans.OrleansRuntime.nuspec
src/NuGet/Microsoft.Orleans.OrleansServiceBus.nuspec
src/NuGet/Microsoft.Orleans.OrleansTelemetryConsumers.Counters.nuspec
src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/NuGet/Microsoft.Orleans.TestingHost.nuspec
src/OrleansCounterControl/Microsoft.Orleans.CounterControl.targets
src/OrleansCounterControl/OrleansCounterControl.csproj
src/OrleansHost/Microsoft.Orleans.OrleansHost.targets
src/OrleansHost/OrleansHost.csproj
src/OrleansManager/Microsoft.Orleans.OrleansManager.targets
src/OrleansManager/OrleansManager.csproj

- Modify Nuget packages to copy executable and other tool files to output directory.
- Fix file order in nuspec files (cosmetic).

Fix "*.exe.config" file usage in nuspec files. Fixes #2616.

---

src/Orleans/Streams/QueueAdapters/IQueueCacheCursor.cs
src/OrleansProviders/Streams/Common/EventSequenceToken.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCache.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCacheCursor.cs
src/OrleansProviders/Streams/Generator/GeneratorPooledCache.cs
src/OrleansProviders/Streams/Memory/MemoryPooledCache.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
test/TesterAzureUtils/Streaming/AzureQueueAdapterTests.cs

SimpleQueueCache has a hard dependency on EventSequenceToken.  This is bad, as it's intended to be a generic cache and should not be dependent on specific batch containers or sequence tokens.
The original compromise was made to manage cursor location in the cache, which was originally, unset, set, or idle.  To help manage cursor position for idle cursors, we'd needed to know the sequence token of the next message.  We used the state of the EventSequenceToken to get the next sequence token, which introduced the dependency.
This change treats unset and idle cursors the same, with a special case for cursors set in the future.

Removed SimpleQueueCache dependecy on EventSequenceToken

---

src/Orleans/CodeGeneration/ActivationAttribute.cs
src/Orleans/Core/GrainAttributes.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueBatchContainerV2.cs
src/OrleansProviders/Streams/Common/EventSequenceTokenV2.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubSequenceTokenV2.cs
test/NonSiloTests/SerializationTests/SerializationTests.DifferentTypes.cs
test/NonSiloTests/SerializationTests/StreamTypeSerializationTests.cs
test/Tester/SerializationTests/SerializationTests.JsonTypes.cs
test/TesterAzureUtils/StreamTypeSerializationTests.cs

Part of the work to obviate `SerializationManager.Register` methods. See #2610
Simple fix to allow a single static serializer class to support multiple types, as can be seen with the JSON serializer below.
`[RegisterSerializer]` is still available and this PR adds a test to ensure it's still being called, but it's marked as obsolete in order to set expectations.

Allow serializers to have multiple [Serializer(...)] attributes

---

Samples/Adventure/AdventureClient/AdventureClient.csproj
Samples/Adventure/AdventureClient/packages.config
Samples/Adventure/AdventureGrainInterfaces/AdventureGrainInterfaces.csproj
Samples/Adventure/AdventureGrainInterfaces/packages.config
Samples/Adventure/AdventureGrains/AdventureGrains.csproj
Samples/Adventure/AdventureGrains/packages.config
Samples/Adventure/AdventureSetup/AdventureSetup.csproj
Samples/Adventure/AdventureSetup/App.config
Samples/Adventure/AdventureSetup/packages.config

This is the first PR to resolve #2359 
Bumping System.Collections.Immutable to 1.1.37 seems to pull all the System.* dependencies listed under DotNet5.0 (see [System.Collection,Immutable 1.1.3.7](https://www.nuget.org/packages/System.Collections.Immutable/1.1.37))  
These are already available in the target framework, so I removed them manually from packages.config since they are unecessary.   
Any update would pull them again though.

Updating Adventure Sample to Orleans 1.3.1

---

test/ServiceBus.Tests/Streaming/EHStreamProviderCheckpointTests.cs

Somewhere along the line the azure storage connection string used in the checkpointer was changed to the eventhub connection string.
This change sets it back.

Checkpointer tests wrong checkpointer connection string - bugfix

---

test/DefaultCluster.Tests/TimerOrleansTest.cs
test/TestInternalGrains/TimerGrain.cs

This test has been unreliable, causing failures in many CI passes.
The crux of the issue is that the test grain starts a timer which fires its first tick immediately (confirmed by in testing).
The asserts which were removed don't really make sense to have in the first place, in my opinion. They're flaky because of how time-sensitive they are.
Fixes #2625

Improve reliability of TimerOrleansTest_Migration test

---

src/OrleansRuntime/Services/GrainService.cs
src/OrleansRuntime/Silo/Silo.cs
test/TestGrainInterfaces/IGrainServiceTestGrain.cs
test/TestGrains/GrainService/CustomGrainService.cs
test/TestGrains/GrainService/GrainServiceTestGrain.cs
test/Tester/GrainServiceTests/CustomGrainService.cs
test/Tester/GrainServiceTests/GrainServiceTests.cs

Previously GrainServices which were added never called Startup, Reminder service worked because it is being created and started up discretely.

GrainServices are now Started by the Silo on Startup

---

src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

-Reduced duplicate logging during errors.
-Fixed null reference exception that occur durring shutdown.
Addresses "EventHubStreamProviders exceptions #2477"

Harden persistent stream provider pulling agent.

---

src/Orleans/Messaging/ByteArrayBuilder.cs
src/Orleans/Messaging/Message.cs
src/Orleans/Orleans.csproj
src/Orleans/Serialization/BinaryTokenStreamWriter.cs
src/Orleans/Serialization/ILBasedExceptionSerializer.cs
src/Orleans/Serialization/ILBasedSerializer.cs
src/Orleans/Serialization/ILSerializerGenerator.cs
src/Orleans/Serialization/RemoteNonDeserializableException.cs
src/Orleans/Serialization/TypeSerializer.cs
test/NonSiloTests/Orleans.NonSiloTests.csproj
test/NonSiloTests/Serialization/ILBasedExceptionSerializerTests.cs
vNext/test/NonSiloTests/Orleans.NonSiloTests.csproj

This is an implementation of failsafe Exception serialization.
Features:
* Serializes Exceptions so that they can be deserialized even if the original exception type is not available.
* A fallback type, `RemoteNonDeserializableException`, is used in place of the original exception type when the original is not available. In this case, the message and stack trace are preserved, but any additional fields on sub-classes of `Exception` cannot be inspected.
* Exceptions are round-tripped without any loss of fidelity, regardless of whether or not one of the parties does not have access to the original exception type.
Caveats:
* Currently it does not support referential transparency for the exception itself.
* This is an extension to `ILBasedSerializer` and therefore will only be enabled if that …

Failsafe Exception serialization (#2310)

---

test/AWSUtils.Tests/project.json
test/BondUtils.Tests/project.json
test/Consul.Tests/project.json
test/DefaultCluster.Tests/project.json
test/GoogleUtils.Tests/project.json
test/PSUtils.Tests/project.json
test/ServiceBus.Tests/project.json
test/Tester/project.json
test/TesterAzureUtils/project.json
test/TesterSQLUtils/project.json
test/TesterZooKeeperUtils/project.json
vNext/test/Consul.Tests/Consul.Tests.csproj
vNext/test/Tester/Tester.csproj
vNext/test/TesterSQLUtils/Tester.SQLUtils.csproj
vNext/test/TesterZooKeeperUtils/Tester.ZooKeeperUtils.csproj

vNext and mainline projects were using different versions of FluentAssertions.
This just consolidates all versions to the latest. I was seeing some errors during some test runs because of this mismatch.

Consolidate FluentAssertions version used in test projects

---

src/Orleans/Core/GrainClient.cs
src/Orleans/Messaging/GatewayConnection.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
test/Tester/ClientConnectionTests/ClientDisconnectionEventTests.cs
test/Tester/Tester.csproj

Fix for "Access to grain client connection status" #2551 
Now `ProxiedMessageCenter` keeps a counter of opened gateway connection. When this counter reach 0, we send an event to the client to notify that the client might have been disconnected from the cluster.
I think we still can have race condition like this:
- Client connected to GW1 (counter set to 1)
- GW1 connection lost (but no update to the counter yet)
- GW2 connection established (but no update to the counter yet)
- GW2 updates the opened connection counter (counter set to 2)
- GW1 updates the opened connection counter (counter set to 1)
But the windows seems small enough for me, so this fix seems still useful for now

Client cluster disconnection

---

src/Orleans/Core/GrainClient.cs
src/Orleans/Logging/ErrorCodes.cs

Following up on #2628
Safer implementation of GrainClient.NotifyClusterConnectionLost and add logging in case of failure when calling event subscriber

Follow up on "Client cluster disconnection #2628"

---

src/Orleans/CodeGeneration/GrainInterfaceUtils.cs
src/Orleans/Core/GrainAttributes.cs
test/TestGrainInterfaces/IMethodInterceptionGrain.cs
test/TestGrains/MethodInterceptionGrain.cs

Implements #2659.
This slightly improves the upgrade story by removing the restriction that method names and method parameter type names cannot be changed without breaking existing clients/silos.
Users can add the `[MethodId(x)]` attribute to methods to override the default algorithm for generating ids.

Allow overriding MethodId using [MethodId(id)] on interface methods

---

src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Runtime/IRuntimeClient.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Core/ISiloRuntimeClient.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs

`IRuntimeClient.Identity` is a confusing property, since the name implies it's the identity of the runtime client (which might be interpreted as client/silo id).

Rename IRuntimeClient.Identity to CurrentActivationIdentity

---

src/Orleans/CodeGeneration/GenericMethodInvoker.cs
src/Orleans/CodeGeneration/GrainInterfaceUtils.cs
src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/Orleans.csproj
src/Orleans/Serialization/ILSerializerGenerator.cs
src/Orleans/Serialization/IlDelegateBuilder.cs
src/OrleansCodeGenerator/GrainMethodInvokerGenerator.cs
src/OrleansCodeGenerator/GrainReferenceGenerator.cs
src/OrleansCodeGenerator/Utilities/SyntaxFactoryExtensions.cs
test/DefaultCluster.Tests/CodeGenTests/GeneratorGrainTest.cs
test/DefaultCluster.Tests/CodeGenTests/IRuntimeCodeGenGrain.cs

This PR adds support for generic methods on grains in a pay-for-what-you-use fashion, so any additional cost is only incurred for generic methods. The cost should be quite low anyway because the invoker stub is generated using (simple) IL.
Supports methods with constraints, overloads, generic methods inside generic grains, upcasting arguments, grain observers, and grain extensions (last one not tested). We can address anything I missed as they come.
This is what a generated `GrainReference` method looks like for a generic method:
```C#
public global::System.Threading.Tasks.Task<global::System.Type[]> @GetTypesInferred<T, U>(T @t, U @u, global::System.Int32 @v)
{
return base.@InvokeMethodAsync<global::System.Type[]>(-1221167187, new global::System.Object[]{typeof (T), typeof (U), @t, @u, …
```

Support for grains with generic methods

---

src/OrleansAWSUtils/Membership/SiloInstanceRecord.cs
test/AWSUtils.Tests/AWSUtils.Tests.csproj
test/AWSUtils.Tests/MembershipTests/DynamoDBMembershipTableTest.cs
test/AWSUtils.Tests/MembershipTests/SiloInstanceRecordTests.cs
test/Consul.Tests/ConsulMembershipTableTest.cs
test/TesterAzureUtils/AzureMembershipTableTests.cs
test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs
test/TesterSQLUtils/MySqlMembershipTableTests.cs
test/TesterSQLUtils/PostgreSqlMembershipTableTests.cs
test/TesterSQLUtils/SqlServerMembershipTableTests.cs
test/TesterZooKeeperUtils/ZookeeperMembershipTableTests.cs
vNext/test/AWSUtils.Tests/AWSUtils.Tests.csproj

(@galvesribeiro - as per chat on Gitter)
When using DynamoDB for the membership store, I was seeing `ConditionalCheckFailedException` errors when trying to update the `IAmAlive` field in the database. 
This was because the key being used to locate the record always had a value of "-0-0" rather than the expected "_IP-Port-Generation_". This was because it was being built using the `Address`, `Port`, and `Generation` values on the `SiloInstanceRecord` object, but on this code path these values are not assigned. Only the `SiloIdentity` property gets set by the `MembershipOracle` (see `OnIAmAliveUpdateInTableTimer`).
I have added new unit tests for the `GetKeys` call on `SiloInstanceRecord`, and fixed the issue.
I also added integration tests for all the membership stores, to exercise …

DynamoDB silo identity fix

---

src/OrleansAWSUtils/Membership/DynamoDBGatewayListProvider.cs
test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs

The DynamoDB gateway provider was not filtering out silos with a proxy-port of 0.
All other providers only consider Active silos, sharing the current DeploymentId, with a non-zero proxy port (e.g. https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/OrleansSiloInstanceManager.cs#L235)
Added test coverage and fixed using additional predicate on query.
I've not been able to re-run all the membership provider tests for other providers locally, but have examined the code for all of them, and they all appear to include this correct check.

DynamoDB Gateway Provider fix: was including non-gateway silos

---

src/Orleans/Messaging/GatewayConnection.cs
src/Orleans/Messaging/Message.cs
src/Orleans/Messaging/MessageFactory.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/IRuntimeClient.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProducer.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans/Utils/ServiceCollectionExtensions.cs
src/Orleans/project.json
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Messaging/Gateway.cs
src/OrleansRuntime/Messaging/GatewayAcceptor.cs
src/OrleansRuntime/Messaging/IncomingMessageAcceptor.cs
src/OrleansRuntime/Messaging/IncomingMessageAgent.cs
src/OrleansRuntime/Messaging/MessageCenter.cs
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Silo/Silo.cs
test/NonSiloTests/General/RequestContextTestsNonSiloRequired.cs
test/NonSiloTests/SerializerTests/MessageSerializerTests.cs
test/TestExtensions/SerializationTestEnvironment.cs

Prep for non-static SerializationManager.
Purpose is to give ourselves a way to inject `SerializationManager`/`RequestContextUtil` when creating messages. We could add an extra field to `Message`, but I believe it's best to keep POCOs as data-only (no services), since that makes serialization/deserialization obvious.
Only the last commit is unique to this PR: the others have their own PRs.

Extract MessageFactory from Message class.

---

test/NonSiloTests/SchedulerTests/OrleansTaskSchedulerBasicTests.cs

A timeout of 1 second assumes the test host isn't slow or overloaded.

Tweak timeouts to improve test reliability

---

src/Orleans/Core/GrainFactory.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/IGrainReferenceConverter.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansAWSUtils/Reminders/DynamoDBReminderTable.cs
src/OrleansAzureUtils/Storage/AzureBasedReminderTable.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansSQLUtils/Messaging/SqlMembershipTable.cs
src/OrleansSQLUtils/ReminderService/SqlReminderTable.cs
src/OrleansSQLUtils/Storage/DbStoredQueries.cs
src/OrleansSQLUtils/Storage/RelationalOrleansQueries.cs
src/OrleansSQLUtils/Storage/SqlStatisticsPublisher.cs
test/AWSUtils.Tests/Reminder/DynamoDBRemindersTableTests.cs
test/AWSUtils.Tests/StorageTests/DynamoDBStorageProviderTests.cs
test/NonSiloTests/General/Identifiertests.cs
test/TesterAzureUtils/AzureRemindersTableTests.cs
test/TesterAzureUtils/Reminder/ReminderTests_Azure_Standalone.cs
test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs
test/TesterSQLUtils/MySqlMembershipTableTests.cs
test/TesterSQLUtils/MySqlRemindersTableTests.cs
test/TesterSQLUtils/PostgreSqlMembershipTableTests.cs
test/TesterSQLUtils/PostgreSqlRemindersTableTests.cs
test/TesterSQLUtils/SqlServerMembershipTableTests.cs
test/TesterSQLUtils/SqlServerRemindersTableTests.cs
test/TesterSQLUtils/SqlStatisticsPublisherTests/SqlStatisticsPublisherTestsBase.cs
test/TesterSQLUtils/StorageTests/Relational/CommonFixture.cs
test/TesterZooKeeperUtils/ZookeeperMembershipTableTests.cs

Prep for non-static SerialziationManager.
Purpose: adds a non-static point for us to inject `IRuntimeClient` into `GrainReferences` as they're deserialzied from the 'key strings' used with various storage providers.
Check the last commit. The previous commits are from other pending PRs

Add IGrainReferenceConverter for converting 'key strings' to GrainReference

---

src/OrleansVSTools/OrleansVSTools/OrleansVSTools.csproj

This is causing build failures of OrleansVSTools on VSO.
Unchecked the DeployExtension property to turn off automatic deployment of the VSIX.

Turn off deployment of VSIX at build time

---

src/Orleans/Statistics/RuntimeStatisticsGroup.cs
src/OrleansAzureUtils/Providers/AzureConfigurationExtensions.cs
test/Tester/StreamingTests/PullingAgentManagementTests.cs
test/TesterAzureUtils/Streaming/DelayedQueueRebalancingTests.cs

Suppress a set of warnings stemming from us having deprecated `AzureQueueStreamProvider`.
Suppress a false positive warning about not disposing a timer.

Suppress noise build warnings

---

src/Orleans/Statistics/RuntimeStatisticsGroup.cs
src/OrleansAzureUtils/Providers/AzureConfigurationExtensions.cs
src/OrleansVSTools/OrleansVSTools/OrleansVSTools.csproj
test/Tester/StreamingTests/PullingAgentManagementTests.cs
test/TesterAzureUtils/Streaming/DelayedQueueRebalancingTests.cs

DeployExtension is breaking VSO build of the VSIX.
Superfluous warnings pollute build log.

Merge a couple of commits from master to 1.4.0

---

src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Providers/Streams/EventHub/EventDataExtensions.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubBatchContainer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubCheckpointer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubConstants.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubPartitionCheckpointEntity.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubQueueCache.cs
test/ServiceBus.Tests/CollectionFixtures.cs
test/ServiceBus.Tests/ServiceBus.Tests.csproj
test/ServiceBus.Tests/Streaming/EHImplicitSubscriptionStreamRecoveryTests.cs
test/ServiceBus.Tests/Streaming/EHStreamPerPartitionTests.cs
test/ServiceBus.Tests/Streaming/EHStreamProviderCheckpointTests.cs
test/ServiceBus.Tests/Streaming/EHSubscriptionMultiplicityTests.cs
test/ServiceBus.Tests/TestStreamProviders/StreamPerPartitionEventHubStreamProvider.cs
vNext/src/NuGet/Microsoft.Orleans.OrleansServiceBus.nuspec
vNext/src/Orleans.vNext.sln
vNext/src/OrleansServiceBus/OrleansServiceBus.csproj
vNext/src/OrleansServiceBus/Properties/AssemblyInfo.cs
vNext/src/OrleansServiceBus/app.config
vNext/src/Test.cmd
vNext/test/ServiceBus.Tests/App.config
vNext/test/ServiceBus.Tests/ServiceBus.Tests.csproj
vNext/test/ServiceBus.Tests/ServiceBus.Tests.xunit.runner.json
vNext/test/Tester/Tester.csproj

As part of #2145 this PR add EventHub stream provider support to vNext solution supporting `netstandard1.5`.
The new `netstandard1.5` project rely on the new nugets [Microsoft.Azure.EventHubs](https://www.nuget.org/packages/Microsoft.Azure.EventHubs/0.0.4-preview) and [Microsoft.Azure.EventHubs.Processor](https://www.nuget.org/packages/Microsoft.Azure.EventHubs.Processor/0.0.4-preview) which will deprecate the old ones once they are released. There were namespace changes and a bit of API changes on those nugets and they were addressed with some `#if`s among other small changes. 
For now those nugets were only used at vNext and should only be updated on master when we merge the solutions.
cc: @jason-bragg

EventHubs Stream provider ported to netstandard

---

src/OrleansRuntime/GrainTypeManager/GenericGrainTypeData.cs
test/DefaultCluster.Tests/GenericGrainTests.cs
test/TestGrainInterfaces/IGenericInterfaces.cs

Current support for generic grains with generic state assumes that the type parameter to the grain is also the type parameter of the state class.
This PR relaxes that assumption by navigating the concrete grain type's hierarchy until it reaches the `Grain<TState>` level and extracting the concrete value of `TState`.
/cc @lwansbrough who [reported this issue on Gitter](https://gitter.im/dotnet/orleans?at=589d05abaa800ee52c75e6de) - thank you, Loch!

Improve support for generic grains with generic state

---

src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Messaging/IncomingMessageAgent.cs
src/OrleansRuntime/Scheduler/InvokeWorkItem.cs
src/OrleansRuntime/Silo/Silo.cs

By implementing `ISchedulingContext` in `ActivationData` we can remove at least one allocation per call.
I did not perform the same optimization for `SystemTarget` at this stage because there are comparatively very few `SystemTarget`s and we already allocate just one `SchedulingContext` per `SystemTarget` (i.e, not per-call).
I chose to implement this explicitly in `ActivationData` rather than adding a `SchedulingContext` member because it's simple and results in less GC pressure without adding any fields.
Fixes #2677.

Reduce SchedulingContext allocs for grain activations

---

src/OrleansServiceBus/Providers/Streams/EventHub/EventHubBatchContainer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubSequenceTokenV2.cs
test/ServiceBus.Tests/TestStreamProviders/StreamPerPartitionEventHubStreamProvider.cs

EventSequenceToken was being used instead of EventHubSequenceToken.

Bugfix - EventHubSequenceToken not used consistently

---

src/OrleansRuntime/Catalog/Catalog.cs

The param `grainType` can be null or empty: in this case we take the value from the TypeMap. 
This check was done only if this was a new placement and if the silo was not stopping, now we do it every time so the logging after will always be complete.

Fix (very) small logging issue in Catalog

---

src/OrleansEventSourcing/JournaledGrain.cs
test/TestGrains/EventSourcing/AccountGrain.cs
test/TestGrains/EventSourcing/ChatGrain.cs
test/TestGrains/EventSourcing/CountersGrain.cs
test/TestGrains/LogTestGrain.cs

While writing documentation, I noticed another mistake in the JournaledGrain API, which is likely to confuse many users unless fixed.
Previously, the grain did NOT wait until the latest state is loaded on activation. Users had to override OnActivateAsync to make sure the grain has loaded the latest version before it starts executing calls.
*But this is exactly backwards*: the simple, common scenario is that we always wait for the load to complete before the grain starts taking calls; the advanced, uncommon scenario is to skip the wait (there are very few cases where you would want to do this).
**So this PR swaps the default behavior to be more in line with standard expectations.**
Now, we wait by default during activation; but users can still override OnActivateAsync if they want a …

Choose more reasonable default when activating JournaledGrain

---

test/TestGrains/EventSourcing/CountersGrain.cs

I introduced this bug accidentally (forgot to rename State to TentativeState). This bug made two of the CountersGrain testcases fail frequently.

fix bug in TestGrains.CountersGrain 

---

test/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureBlobStore.cs
test/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureTableStore.cs

Make AzureUtils PersistenceGrainTests to use AzureTable as membership provider, as a more reliable solution when one test case restarting primary silo.

fix AzureUtils PersistenceGrainTests

---

src/OrleansTestingHost/AppDomainSiloHandle.cs
src/OrleansTestingHost/TestCluster.cs

Cleanup logic threw another exception that ended up masquerading the real exception and potentially leaking an initialized silo

Fix a cleanup issue in TestCluster after a failure

---

src/ClientGenerator/ClientGenerator.cs
src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/AssemblyLoader/AssemblyProcessor.cs
src/Orleans/AssemblyLoader/TypeMetadataCache.cs
src/Orleans/CodeGeneration/CodeGeneratorManager.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansRuntime/Silo/Silo.cs

In preparation for non-static grain clients and non-static SerializationManager, we need to also make this class non-static.
Simple change, functionals pass.

Change CodeGen classes to be non-static

---

src/Tutorials/index.md
src/Tutorials/toc.yml

According to the links on the page preceding the unit test page and the page linked after the unit test page, I have changed the ordering of the unit test page in both the toc.md and the Index.md

Changed ordering of Table of Contents to put Unit Tests last

---

src/Orleans/Runtime/GrainReference.cs
src/Orleans/Serialization/BinaryFormatterSerializer.cs
src/Orleans/Serialization/OrleansJsonSerializer.cs
src/OrleansAWSUtils/Storage/Provider/DynamoDBStorageProvider.cs
src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
src/OrleansSQLUtils/Storage/Provider/AdoNetStorageProvider.cs
src/OrleansTestingHost/Utils/TestingUtils.cs
test/DefaultCluster.Tests/GrainReferenceTest.cs
test/NonSiloTests/General/Identifiertests.cs
test/NonSiloTests/General/InternalSerializationTests.cs
test/NonSiloTests/OrleansRuntime/ExceptionsTests.cs
test/NonSiloTests/Serialization/BuiltInSerializerTests.cs
test/NonSiloTests/SerializationTests/SerializationTests.DifferentTypes.cs

BinaryFormatter and Json.NET have a facility to pass context to types being deserialized. This PR plumbs `IGrainFactory` through that context and makes use of it during deserialization of GrainReference.
Originally I was intending to plumb some new `IExternalSerializerContext`, but figured it's best to be lightweight - we can add some new interface later if needed.
Unfortunately, while `StreamingContext` does exist on .NET Core, it's defined as a struct with no members. In other words, it's totally useless and exists only to keep method signatures consistent with Full Fx.
Functionals pass.

Improve GrainReference deserialization for BinaryFormatter & Json.NET

---

src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Silo/Silo.cs

This registration causes a "Circular Reference" error when used with Autofac (#2747) and seems unnecessary as the DI framework provides it automatically.

Remove unnecessary service registration of IServiceProvider to itself

---

src/NuGet/Microsoft.Orleans.OrleansGoogleUtils.nuspec
src/OrleansGoogleUtils/OrleansGoogleUtils.csproj
vNext/src/OrleansGoogleUtils/OrleansGoogleUtils.csproj

Add a NuGet package for OrleansGoogleUtils.dll.
Remove unnecessary reference to OrleansRuntime.dll.

Add a NuGet package for OrleansGoogleUtils.dll

---

src/NuGet/Microsoft.Orleans.OrleansGoogleUtils.nuspec

OrleansConsulUtils.dll -> OrleansGoogleUtils.dll.

Fix copy-paste error in OrleansGoogleUtils.nuspec

---

src/Documentation/Event-Sourcing/Configuration.md
src/Documentation/Event-Sourcing/Diagnostics.md
src/Documentation/Event-Sourcing/GrainStateAPI.md
src/Documentation/Event-Sourcing/LogConsistencyProviders.md
src/Documentation/Event-Sourcing/MultiInstance.md
src/Documentation/Event-Sourcing/MultiVersion.md
src/Documentation/Event-Sourcing/Overview.md
src/Documentation/Event-Sourcing/Subscribe.md
src/Documentation/toc.yml

A first draft of the documentation as promised in #2598.
This is not yet complete, as it does not yet discuss the samples which I will add soon.
Also, we most likely want to not merge this until #2651 is completed in case there are more changes to the API.
However, I thought it may be good to at least start this PR as it may be quite helpful to everyone involved to have some coherent documentation.

event-sourcing documentation

---

src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Serialization/SerializationManager.cs

Currently, a NullReferenceException will be thrown in `SerializationManager.Register(Type, Type)` for custom serializers which are missing the serialization attributes/methods.
Reported by @kogir [in chat](https://gitter.im/dotnet/orleans?at=58ae6727de504908220331d0).
This will log a warning instead.
We ought to fix this by using Roslyn Analyzers instead of runtime errors.

Avoid a NullReferenceException in SerializationManager.Register(...)

---

src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/Serialization/ILSerializerGenerator.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs
src/OrleansCodeGenerator/SerializerGenerator.cs
test/NonSiloTests/Serialization/BuiltInSerializerTests.cs
test/NonSiloTests/Serialization/ILBasedSerializerTests.cs

Our implementation which made our NonSerializedAttribute check build on .NET Core was not correct.
This fix is quite simple - and I'm silly for not knowing it earlier. Instead of looking for the `[NonSerialized]` attribute on fields, we check for the `FieldAttributes.NotSerialized` flag on the `FieldInfo.Attributes` property.
Our tests don't run on .NET Core, but I tested this method manually using a .NET Core project.
This should fix #2597 
cc @galvesribeiro. You ran into this issue when porting ClientGenerator to .NET Core - we saw some fields in the generated code which should not have been there.

Fix [NonSerialized] on .NET Core

---

src/OrleansRuntime/Silo/TestHooks/ITestHooksSystemTarget.cs
src/OrleansRuntime/Silo/TestHooks/TestHooksSystemTarget.cs
test/TestExtensions/MockStorageProvider.cs
test/TesterInternal/ErrorInjectionStorageProvider.cs
test/TesterInternal/General/BootstrapProviderTests.cs
test/TesterInternal/General/TestingBootstrapProviders.cs
test/TesterInternal/StorageTests/PersistenceGrainTests.cs
test/TesterInternal/StreamingTests/StreamPubSubReliabilityTests.cs

Remove usage of AppDomainTestHook on BootstrapProviderTests.cs , PersistenceGrainTests.cs, and StreamPubSubReliabilityTests. 
leaving GeoClusterTests the only tests using AppDomainTestHook

migrate off AppDomainTestHook

---

Samples/HelloWorld.NetCore/BuildAndRun.ps1
Samples/HelloWorld.NetCore/BuildAndRun.sh
Samples/HelloWorld.NetCore/NuGet.Config
Samples/HelloWorld.NetCore/Readme.md

Removed `publish` instructions, since #2772 fixed an issue with serialization that caused the need for that side effect.
Also fixed cascading NuGet.config inconsistencies, to pick up the right nuget packages from the local build.
Created build scripts for PowerShell and Bash to simplify the process even more, for people new to .NET Core.

Simplify instructions for running HelloWorld.NetCore

---

test/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureTableStore.cs

When using TestClusterOptions it is best to first fully initialize the cluster configuration and then client one, because it will copy stuff from the former on first access.
In this case, the connection string is one of the things it copies, so it is unnecessary. But because of it is was failing to copy the membership config, and the tests were sometimes getting `No gateway available`

Fix test issue that created client configuration prematurely

---

src/Orleans/Configuration/MessagingConfiguration.cs
src/Orleans/Messaging/GatewayConnection.cs
src/Orleans/Messaging/SocketManager.cs
src/Orleans/Runtime/Constants.cs

Fix for #2788 
It seems that the value by default is around 20 seconds.
I added a method in `SocketManager` to be able to specify a timeout from the configuration, and use it for client->gw and silo->silo socket connect.

Add a timeout for socket connection

---

src/Orleans/Statistics/RuntimeStatisticsGroup.cs

The analyzer doesn't understand the new syntax yet.
This disables the warning for this method in its entirety.
```
Warning	CA2213	'RuntimeStatisticsGroup' contains field 
'RuntimeStatisticsGroup.availableMemoryCounterPF' that is of IDisposable
type: 'PerformanceCounter'. Change the Dispose method on
'RuntimeStatisticsGroup' to call Dispose or Close on this field.
Orleans	RuntimeStatisticsGroup.cs	242	Active
```

Fix build warnings in RuntimeStatisticsGroup

---

src/OrleansRuntime/Silo/Silo.cs

This is a fix for the bug observed in #2774.
The problem was that cluster-id was picking deployment-id as a default, but deployment-id can be null or empty. This PR adds a check to catch this and use an appropriate default in all cases.

fix missing check for empty deployment id

---

src/Orleans/Core/GrainExtensions.cs
src/Orleans/Runtime/GrainReference.cs

Removed `RuntimeClient.Current` in favour of using `grainRef.RuntimeClient`.
`Cast<T>` & `AsReference<T>` were almost identical. Now `Cast` simply calls `AsReference`.
Note that calling `GrainFactory.Cast(gref)` already calls the `AsWeaklyTypedReference()` extension method from the IL, so the bodies of these methods were already functionally equivalent.
Should we deprecate one of them? Is there supposed to be a difference between them?

GrainExtensions: remove RuntimeClient.Current usage

---

vNext/Build.cmd
vNext/Directory.Build.props

Can use `Build.cmd Pack` to continue the packing process after signing the binaries

Split packing into a separate build step to account for build signing

---

src/ClientGenerator/ClientGenerator.csproj
src/Orleans/Orleans.csproj
src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansCounterControl/OrleansCounterControl.csproj
src/OrleansHost/OrleansHost.csproj
src/OrleansManager/OrleansManager.csproj
src/OrleansProviders/OrleansProviders.csproj
src/OrleansRuntime/OrleansRuntime.csproj
test/TestGrainInterfaces/TestGrainInterfaces.csproj
test/TestGrains/TestGrains.csproj

Add missing Microsoft.Common.props import to projects, this fixes the error of building the solution from VS2017.

Add missing imports to make solution build in VS2017 too.

---

vNext/test/TesterInternal/TesterInternal.csproj

Can move BootstrapProviderTests, PersistenceGrainTests and StreamPubSubReliabilityTests to vNext now since they already moved away AppDomainTeskHook in #2743, which doesn't work in netstandard

Move more tests

---

src/OrleansServiceFabricUtils/Utilities/ErrorCode.cs

The value of ServiceFabricBase defined in ErrorCodes.cs for the OrleansServiceFabricUtils is different and collides with the values defined in Orleans Logging ErrorCodes.cs

fixed ServiceFabricBase

---

vNext/Build.cmd

Useful when signing binaries and then continuing the packing process

Do not build projects when only packing

---

src/OrleansRuntime/GrainTypeManager/GrainTypeData.cs

Some usages of `GrainTypeData` are from outside of the silo, where a sensible `MultiClusterRegistrationStrategy` is not available.
For example, it's used in CounterControl.

Allow null MultiClusterRegistrationStrategy in GrainTypeData

---

src/OrleansConsulUtils/ConsulBasedMembershipTable.cs
src/Test.cmd
test/AWSUtils.Tests/MembershipTests/DynamoDBMembershipTableTest.cs
test/AWSUtils.Tests/Reminder/DynamoDBRemindersTableTests.cs
test/Consul.Tests/CollectionFixtures.cs
test/Consul.Tests/Consul.Tests.csproj
test/Consul.Tests/ConsulMembershipTableTest.cs
test/Consul.Tests/ConsulTestUtils.cs
test/TesterAzureUtils/AzureMembershipTableTests.cs
test/TesterAzureUtils/AzureRemindersTableTests.cs
test/TesterInternal/ConnectionStringFixture.cs
test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs
test/TesterInternal/RemindersTest/ReminderTableTestsBase.cs
test/TesterSQLUtils/MySqlMembershipTableTests.cs
test/TesterSQLUtils/MySqlRemindersTableTests.cs
test/TesterSQLUtils/PostgreSqlMembershipTableTests.cs
test/TesterSQLUtils/PostgreSqlRemindersTableTests.cs
test/TesterSQLUtils/SqlServerMembershipTableTests.cs
test/TesterSQLUtils/SqlServerRemindersTableTests.cs
test/TesterSQLUtils/SqlStatisticsPublisherTests/SqlStatisticsPublisherTestsBase.cs
test/TesterZooKeeperUtils/CollectionFixtures.cs
test/TesterZooKeeperUtils/TesterZooKeeperUtils.csproj
test/TesterZooKeeperUtils/ZookeeperMembershipTableTests.cs
vNext/Test.cmd

Add missing fixture in Consul and ZooKeeper tests, and skip them if environment is not set up.
Make GetConnectionString allowed to fail and skip its tests (for several providers).

Skip some environment-dependent tests.

---

src/Orleans/Runtime/GrainInterfaceMap.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs

See #2808 for more explanations.
The fix is simple: add the "open generic" version of the interface in the `GrainInterfaceMap` so we can lookup information with the value returned by the `GrainReference` and the `InvokeMethodRequest` that are used by this implementation.

When adding a concrete implementation of a generic interface, add also the generic version in the GrainInterfaceMap

---

src/Build.cmd
src/Test.cmd
vNext/Build.cmd
vNext/Test.cmd

If the `_echo` environment variable is set (regardless of its value), then echo is not turned off. We were already doing it in some of the scripts, but not all. This is the exact same mechanism that http://github.com/dotnet/corefx uses

Allow echoing build script commands

---

src/OrleansTestingHost/TestingSiloHost.cs
test/NonSilo.Tests/ConfigTests.cs
test/TesterInternal/GatewaySelectionTest.cs

Minor test fixes for non-static client.

---

src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/GrainDirectory/ClientObserverRegistrar.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs
src/OrleansRuntime/Messaging/MessageCenter.cs
src/OrleansRuntime/Silo/Silo.cs

Minor cleanup to use the abstraction (interface) instead of the concrete object when it's not required

Use ILocalSiloDetails abstraction

---

test/DefaultCluster.Tests/BasicActivationTests.cs
test/DefaultCluster.Tests/EchoTaskGrainTests.cs
test/DefaultCluster.Tests/StatelessWorkerTests.cs
test/DefaultCluster.Tests/TimerOrleansTest.cs
test/Tester/ClientConnectionTests/ClientDisconnectionEventTests.cs

This way they can be skipped more easily when doing local development (they are still always ran in CI though).

Re-categorize some BVTs as slow

---

src/OrleansEventSourcing/LogStorage/LogViewAdaptor.cs
src/OrleansEventSourcing/StateStorage/LogViewAdaptor.cs

Fix typos in format strings

---

src/Before.Orleans.sln.targets

Fix before targets to download NuGet 4.0 so NuGet.exe will have no MSBuild 14 dependency.

Update targets file to use released NuGet 4.0 always.

---

test/AWSUtils.Tests/StorageTests/DynamoDBStorageProviderTests.cs
test/TesterInternal/StorageTests/CommonStorageTests.cs
test/TesterSQLUtils/StorageTests/Relational/MySqlStorageTests.cs
test/TesterSQLUtils/StorageTests/Relational/RelationalStorageTests.cs
test/TesterSQLUtils/StorageTests/Relational/SqlServerStorageTests.cs

This would hopefully fix the non-deterministic failure on Relational_WriteReadWriteRead100StatesInParallel once and for all.

Avoid parallelization on INSERT

---

src/Orleans.SDK.targets

Since 1.4.0 our projects have been failing to build incrementally in both Visual Studio 2015 and MSBuild when we change a grain interface because of out-of-date codegen files. I tracked the problem down to the build target changes, and adding the @(Compile) list back to the inputs of the OrleansCodeGeneration target allows incremental builds to work again sice the codegen files are correctly rebuilt. It looks like this input was removed when the orleans.codegen.cs file was removed and changed into the target-specific files.
I'm not sure if this has any other side effects, however... I am not a build targets expert at all. :) I am not sure why it was removed with the codegen changes.

Change to OrleansCodeGeneration target to fix incremental builds when grain interfaces change

---

vNext/test/AWSUtils.Tests/App.config
vNext/test/BondUtils.Tests/App.config
vNext/test/Consul.Tests/App.config
vNext/test/DefaultCluster.Tests/App.config
vNext/test/GoogleUtils.Tests/App.config
vNext/test/NonSilo.Tests/App.config
vNext/test/NonSilo.Tests/NonSilo.Tests.csproj
vNext/test/ServiceBus.Tests/App.config
vNext/test/Tester/App.config
vNext/test/Tester/Tester.csproj
vNext/test/TesterAzureUtils/App.config
vNext/test/TesterInternal/App.config
vNext/test/TesterSQLUtils/App.config
vNext/test/TesterZooKeeperUtils/App.config

I noticed that since we merged #2861, a lot of tests fail to be discovered in the vNext solution.
This was due to a missing binding redirect. This change should make SkippableFact test methods discoverable again.

Fix binding redirects so that SkippableFact works in vNext

---

vNext/src/Orleans.SDK.targets

This is the same change as in #2865, but in the vNext tree.

Handle absolute path in IntermediateOutputPath to address issue #2864 in vNext

---

src/ClientGenerator/ClientGenerator.cs
src/Orleans.SDK.targets
src/Orleans/Orleans.2017.csproj
src/Orleans/Orleans.csproj
vNext/src/Orleans.SDK.targets
vNext/src/Orleans/Orleans.csproj

StyleCop and potentially other analyzers will skip files that are contain .g. or .generated. in the name.

Rename codegen file to be excluded from analyzers

---

src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/Providers/ProviderTypeLoader.cs

Also improve logging for errors in `TypeUtils.GetDefinedTypes(...)` so that loader exceptions are made apparent.
Intention is to make debugging issues like #2840 more obvious

ProviderTypeLoader: do not enumerate types in ReflectionOnly assembly.

---

src/OrleansHost/app.config

Add missing entries to app.config. This fix makes it possible to run OrleansHost.exe without manual modifications when added from ```Microsoft.Orleans.Server``` nuget package to a project.
Fixes #2795.

Add missing entries to app.config for OrleansHost.exe. Fixes #2795

---

src/Orleans/CodeGeneration/TypeUtils.cs
test/TestGrainInterfaces/IGenericInterfaces.cs
test/TestGrains/GenericGrains.cs
test/TesterAzureUtils/GenericGrainsInAzureStorageTests.cs

While I was doing this minor cleanup, I encountered that this is still failing on the call to ClearState.
@Maarten88 do you know if this is still related to the grain type name or is this a new bug?
Both tests (with long and short name) are now failing, these are the details:
```
Test Name:  UnitTests.General.GenericGrainsInAzureStorageTests.Generic_OnAzureTableStorage_LongNamedGrain_EchoValue
Test FullName:  UnitTests.General.GenericGrainsInAzureStorageTests.Generic_OnAzureTableStorage_LongNamedGrain_EchoValue
Test Source:    D:\projects\OrleansVso\test\Tester\GenericGrainsInAzureStorageTests.cs : line 28
Test Outcome:   Failed
Test Duration:  0:00:00.286
Result StackTrace:  
Server stack trace: 
at Orleans.Core.GrainStateStorageBridge.<ClearStateAsync>d__7.MoveNext() in …
```

Add coverage for generic state parameter using Azure Storage (after #1897)

---

src/Orleans/Runtime/AsynchQueueAgent.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Silo/Silo.cs

- Dispose service provider when shutting down Silo and Client (which in turns disposes all disposable services in it).
- Close log after fully shutting down.
- Do not throw when calling Stop on AsynchQueueAgent after it was disposed.

Improve service cleanup

---

src/OrleansHost/app.config

The original change (#2806) broke our distributed tests because of the version mismatch. I suggest we revert it for now.
This reverts commit f5d6ee15ca2e637a42e7b78443fdb7d36b0e0a40.

Revert binding redirects in OrleanHost.exe.config

---

src/Orleans/Streams/PubSub/ImplicitStreamPubSub.cs

Technically, consumer grain which use implicit subscribe shouldn't call UnSubscribeAsync to trigger implicitPubsub.UnRegisterConsumer. But throw a exception is a bit harsh, so change implicitPubsub UnRegisterConsumer to preserve its original logic

Fix functionals 

---

src/Orleans/Streams/QueueAdapters/DataNotAvailableException.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCache.cs

Simple queue cache was not rate limiting correctly, leading to messages being removed outside the expected cache purge behavior.  This led to null references in cache cursors under load.
Rate limiting fixed..
Code block which removed messages from cache outside the context of the expected purge behavior was removed.

Fix null reference exception in simple queue cache.

---

test/Tester/StreamingTests/ProgrammaticSubscribeTests/ProgrammaticSubscribeTestsWithDynamicProviderConfiguration.cs

I want to see if this can make it pass more stable in Jenkins. will run it 5 times . 
if not, I will just skip the test

Temporarily skip failing test

---

test/DefaultCluster.Tests/ErrorGrainTest.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerBasicTests.cs
test/TestGrains/EventSourcing/PersonGrain.cs
test/TestGrains/ProgrammaticSubscribe/Stateless_ConsumerGrain.cs

These tests were failing randomly (and relatively frequently) in both our BVT and Functional runs

Fix test timing issues

---

src/Orleans/Orleans.csproj
src/Orleans/Utils/IKeyedServiceCollection.cs
src/Orleans/Utils/ServiceCollectionExtensions.cs
test/Tester/DependencyInjectionDisambiguationTests.cs
test/Tester/Tester.csproj

Since we're limited to features provided by Microsoft.Extensions.DependencyInjection.Abstractions, neither we nor our users that don't use more advanced DI, have a means of acquiring a service from a service provider by name or key.  This PR introduces a minimal implementation for this.
To register a keyed or named service in the service collection:
// add keyed services
services.AddTransient<Zero>().WithKey<int, IValue<int>, Zero>(0);
services.AddTransient<One>().WithKey<int, IValue<int>, One>(1);
// add named services
services.AddTransient<This>().WithName<IValue<string>, This>("this");
services.AddTransient<That>().WithName<IValue<string>, That>("that");
To acquire these from a service provider:
// get by key
IValue<int> intValue = ServiceProvider.GetServiceByKey<int,IValue<int>>(0); …

Minimal disambiguation of service types over DependencyInjection.Abstractions

---

test/TestExtensions/TestDefaultConfiguration.cs
test/TestInternalGrains/StreamingGrain.cs
test/Tester/TestUtils.cs
test/TesterAzureUtils/Streaming/DelayedQueueRebalancingTests.cs
test/TesterAzureUtils/Streaming/HaloStreamSubscribeTests.cs
test/TesterAzureUtils/Streaming/SampleAzureQueueStreamingTests.cs
test/TesterAzureUtils/Streaming/StreamLifecycleTests.cs
test/TesterInternal/General/ElasticPlacementTest.cs
test/TesterInternal/GeoClusterTests/BasicMultiClusterTest.cs
test/TesterInternal/GeoClusterTests/GlobalSingleInstanceClusterTests.cs
test/TesterInternal/GeoClusterTests/MultiClusterNetworkTests.cs
test/TesterInternal/GeoClusterTests/MultiClusterRegistrationTests.cs
test/TesterInternal/StreamProvidersTests.cs
test/TesterInternal/StreamingTests/SMSStreamingTests.cs

- Remove Azure dependency on some tests that do not require it
- Have a way to entirely opt out from using Azure (either real service or emulator) if the DataConnectionString is set to empty.
- Add some SkippableFact attribute that were missing from tests that require Azure.

Run functionals without Azure requirement

---

test/NonSilo.Tests/ConfigTests.cs
test/TestExtensions/SerializationTestEnvironment.cs
test/Tester/StreamingTests/PullingAgentManagementTests.cs
test/TesterAzureUtils/GenericGrainsInAzureStorageTests.cs
test/TesterAzureUtils/Streaming/StreamLimitTests.cs
test/TesterInternal/StreamingTests/StreamPubSubReliabilityTests.cs

Some tests that verify the configuration (but not attempt to connect) were updated to contain a non-empty connection string regardless of defaults.
Disable unnecessary console tracing in several tests.

Skip remaining Azure tests if connection string not set

---

README.md

Added a section in README to introduce Orleans blog. Words mostly copied from our first Blog post:
https://blogs.msdn.microsoft.com/orleans/2016/12/01/welcome-to-orleans-blog/

add blog link to README

---

src/Orleans/Configuration/ClientConfiguration.cs

A minor change, this property is only used for logging.
This global is mutated in load tests, so I will have to follow up with a change to them in VSO

Make ClientConfiguration.ClientName an instance property

---

src/Parallel-Tests.ps1
vNext/Parallel-Tests.ps1

Limit parallelism to 3 test assemblies at a time.
Display test results as they come in, useful to see partial results as the test run finishes each of the test assemblies without having to wait for the entire run to finish.

Limit test parallelization to avoid timing issues in few core machines

---

src/OrleansTestingHost/TestCluster.cs
test/Tester/HeterogeneousSilosTests/UpgradeTests.cs

- Change test categories
- Increase waiting time after silo started/stopped
- Remove usage of static client

UpgradeTests fixes

---

src/OrleansTestingHost/AppDomainSiloHandle.cs
src/OrleansTestingHost/TestCluster.cs
src/OrleansTestingHost/TestingSiloHost.cs

This fixes non-deterministic issues when a silo is stopped and another one started in parallel, such as in `Ring_1F1J`

Account for additional assemblies being updated while in use

---

src/OrleansTestingHost/TestingSiloHost.cs
test/Tester/CollectionFixtures.cs
test/TesterAzureUtils/CollectionFixtures.cs
test/TesterInternal/GeoClusterTests/BasicLogTestGrainTests.cs
test/TesterInternal/GeoClusterTests/GlobalSingleInstanceClusterTests.cs
test/TesterInternal/GeoClusterTests/LogConsistencyTestFixture.cs
test/TesterInternal/GeoClusterTests/LogConsistencyTestsFourClusters.cs
test/TesterInternal/GeoClusterTests/LogConsistencyTestsTwoClusters.cs
test/TesterInternal/GeoClusterTests/MultiClusterNetworkTests.cs
test/TesterInternal/GeoClusterTests/MultiClusterRegistrationTests.cs
test/TesterInternal/GeoClusterTests/TestingClusterHost.cs
vNext/test/TesterInternal/TesterInternal.csproj

Migrate TestingClusterHost to use TestCluster.
Mark some tests as skippable.

Make TestingSiloHost obsolete

---

src/Orleans/Messaging/GatewayManager.cs

It seems that VS complains because `GatewayManager.gatewayRefreshTimer` is not properly disposed. Switching "to "explicit null check" seems to remove the warning.

Remove warning in GatewayManager

---

src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCacheFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubQueueCacheFactory.cs
test/ServiceBus.Tests/TestStreamProviders/EHStreamProviderWithCreatedCacheList.cs
test/ServiceBus.Tests/TestStreamProviders/StreamPerPartitionEventHubStreamProvider.cs

Related to https://github.com/dotnet/orleans/issues/2844. In the current form, it is quite problematic to extend `EventHubAdapterFactory`, so these changes should make it easier a bit

Add extension points to EventHubAdapterFactory

---

test/ServiceBus.Tests/SlowConsumingTests/EHSlowConsumingTests.cs
test/ServiceBus.Tests/Streaming/EHImplicitSubscriptionStreamRecoveryTests.cs
test/ServiceBus.Tests/Streaming/EHStreamPerPartitionTests.cs
test/ServiceBus.Tests/Streaming/EHStreamProviderCheckpointTests.cs
test/ServiceBus.Tests/Streaming/EHSubscriptionMultiplicityTests.cs

TestEnvironmentFixture might interfere with OrleansTestingBase. 
It maybe the reason causing EHSlowConsumingTests.cs  to fall intermittently. Since removing it make EHSlowConsumingTests.cs  succeed 6 times in a row in VSO(main and vNext). I used it by mimic other EH tests. 
Not sure if other EH tests needs to use TestEnvironmentFixture . But TestEnvironmentFixture is designed to set up serialization env for non-silo tests. So I removed TestEnvironmentFixture  for other EH tests too. Stop me if they actually need it.

remove TestEnvironmentFixture annotation from EH tests

---

src/Orleans/Core/GrainAttributes.cs
src/Orleans/Serialization/SerializationManager.cs
test/Tester/SerializationTests/SerializationTests.JsonTypes.cs

Removes the deprecated & obsolete `[RegisterSerializer]` attribute and support for the corresponding `Register` method.
Also fixed the formatting in GrainAttributes.cs since I dislike always having to undo the auto-formatting whenever I make a change.
Fixes #2610

Remove [RegisterSerializer] and support for correspondig Register method

---

src/Documentation/Getting-Started-With-Orleans/Observers.md

Variable name mismatch and return type was not define for Subscribe & UnSubscribe methods

Improvements in Observers docs.

---

src/Orleans/Runtime/RingRange.cs
src/OrleansRuntime/ReminderService/LocalReminderService.cs

Added ISingleRange interface to be exposed externally. Also exposed helper method NextTimeSpan from StandardExtensions as well as some helper methods in RangeFactory.

SingleRange Begin/End needs to be exposed for GrainServices

---

vNext/test/AWSUtils.Tests/AWSUtils.Tests.csproj
vNext/test/BondUtils.Tests/BondUtils.Tests.csproj
vNext/test/Consul.Tests/Consul.Tests.csproj
vNext/test/GoogleUtils.Tests/GoogleUtils.Tests.csproj
vNext/test/ServiceBus.Tests/ServiceBus.Tests.csproj

using wild card include in vNext test csproj, so that new tests added to Main sln will be added to vNext sln automatically.

using wild card include in vNext test csproj

---

src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCacheFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubQueueCacheFactory.cs
test/ServiceBus.Tests/SlowConsumingTests/EHSlowConsumingTests.cs
test/ServiceBus.Tests/TestStreamProviders/EHStreamProviderWithCreatedCacheList.cs

This is a following up PR for PR 2930 , to fix issues we didn't notice in PR 2930 .
1. Add missing xml comments for EventHubQueueCacheFactory and related
2. Add back necessary config for EHSlowConsuming_ShouldFavorSlowConsumer's EH stream provider, and also tune the test to make it pass more consistently.

add necessary xml comment and make test EHSlowConsuming_ShouldFavorSlowConsumer more reliable

---

src/Orleans/IDs/UniqueKey.cs
test/DefaultCluster.Tests/KeyExtensionTests.cs

This removes a limitation in the how keys are parsed, allowing keys which contain `+` symbols.
This is in response to #2943, however I do not believe that this alone would solve that issue - a configuration change to the JSON serializer being used is also likely needed.

Support grains with key extensions containing + symbols

---

Samples/StorageProviders/StorageProviders/BaseJSONStorageProvider.cs
Samples/StorageProviders/StorageProviders/Samples.StorageProviders.csproj
Samples/StorageProviders/StorageProviders/packages.config
Samples/StorageProviders/Test.Client/Test.Client.csproj
Samples/StorageProviders/Test.Client/packages.config

Updates StorageProviders sample projects to use Orleans 1.4.1 so that they can demonstrate using correct JsonSerializerSettings for serializing grain references.
Fix for #2943 alongside #2956
/cc @AwsomeCode

Update StorageProviders sample

---

src/Orleans/Messaging/GatewayProviderFactory.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansServiceFabricUtils/FabricGatewayProvider.cs
src/OrleansServiceFabricUtils/OrleansServiceFabricExtensions.cs

Fixes #2940.
* Check that a gateway provider is correctly configured only if it's not injected (enables injecting gateway providers)
* Configure Service Fabric support via `IClientBuilder`. The previous method was not actually valid since we didn't have client-side DI when it was implemented. It was just there as an example/stub for future use :)
There will be a separate PR which updates the samples to demonstrate this and make use of `ClientBuilder`, that relies on v1.5.0 NuGet packages (which don't exist yet)

Allow Service Fabric FabricClient to be injected

---

src/Orleans/Messaging/GatewayConnection.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Runtime/AsynchQueueAgent.cs

These came up during the debugging of client disconnect:
- AsynchQueueAgent.QueueRequest: NullReferenceException
- AsynchQueueAgent.RunNonBatching: NullReferenceException
- GatewayConnection.PrepareMessageForSend: NullReferenceException
- ProxiedMessageCenter.Disconnect: Collection was modified
- ProxiedMessageCenter.Stop: Collection was modified

Fix various unhandled exceptions happening during client close.

---

test/ServiceBus.Tests/SlowConsumingTests/EHSlowConsumingTests.cs

Since this test has been failing for too long due to timing issues, I'm removing it for now, and @xiazen can re-add it at a later point, potentially by re-adding several other EventHub tests too.

Remove Functional category in failing test

---

src/OrleansAWSUtils/OrleansAWSUtils.csproj
src/OrleansBondUtils/OrleansBondUtils.csproj
src/OrleansPSUtils/OrleansPSUtils.csproj
src/OrleansTelemetryConsumers.AI/OrleansTelemetryConsumers.AI.csproj
src/OrleansTelemetryConsumers.NewRelic/OrleansTelemetryConsumers.NewRelic.csproj
src/OrleansTestingHost/OrleansTestingHost.csproj
test/TestServiceFabric/TestServiceFabric.csproj
test/TesterZooKeeperUtils/LivenessTests.cs
test/TesterZooKeeperUtils/TesterZooKeeperUtils.csproj
test/TesterZooKeeperUtils/ZookeeperMembershipTableTests.cs
test/TesterZooKeeperUtils/ZookeeperTestUtils.cs

- Remove some unneeded assembly references that were causing warnings.
- Skip ZooKeeper tests if ZooKeper is not running (approach copied from Consul tests).

Fix warnings and skip some tests

---

src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
src/OrleansAzureUtils/Storage/StorageExceptionExtensions.cs

Update AzureTableStorage and AzureBlobStorage to consistently throw InconsistentStateException when there are conflicting eTags when updating the store.
- Update AzureTableStorage provider to throw InconsistentStateException also on Clear (it was only doing it on Write).
- Update AzureBlobStorage provider to throw InconsistentStateException on both Write and Clear (previously it was just bubbling up the StorageException).

Throw InconsistenStateException in Azure storage providers

---

src/OrleansProviders/OrleansProviders.csproj
src/OrleansProviders/Streams/Common/PooledCache/CachedMessageBlock.cs
src/OrleansProviders/Streams/Common/PooledCache/FixedSizeBuffer.cs
src/OrleansProviders/Streams/Common/PooledCache/ICacheDataAdapter.cs
src/OrleansProviders/Streams/Common/PooledCache/IEvictionStrategy.cs
src/OrleansProviders/Streams/Common/PooledCache/ObjectPool.cs
src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
src/OrleansProviders/Streams/Generator/GeneratorPooledCache.cs
src/OrleansProviders/Streams/Memory/MemoryPooledCache.cs
src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Properties/AssemblyInfo.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubCacheEvictionStrategy.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubStreamProviderSettings.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/TimePurgePredicate.cs
test/ServiceBus.Tests/EvictionStrategyTests/EHPurgeLogicTests.cs
test/ServiceBus.Tests/EvictionStrategyTests/TestMocks.cs
test/ServiceBus.Tests/ServiceBus.Tests.csproj
test/ServiceBus.Tests/TestStreamProviders/EHStreamProviderWithCreatedCacheList.cs
test/ServiceBus.Tests/TestStreamProviders/StreamPerPartitionEventHubStreamProvider.cs
test/TesterInternal/OrleansRuntime/Streams/CachedMessageBlockTests.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs
vNext/src/OrleansServiceBus/Properties/AssemblyInfo.cs

Fix low traffic queue share pool with high traffic queue bug in EventhubQueueCache… 
-increase TimeBasedPurge frequency on EventHubQueueCache
-for EventHubQueueCache, don't purge the block when message is still valid, based on its TimePurgePredicate
-prevent EventHubQueueCache to purge if it's under pressure, to ensure its rewindability

Eviction strategy and fix Low traffic queue bug

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs

If the user registered a concrete provider in the service collection for DI, then it will use the registration resolve it. Otherwise it falls back to activating a new instance as it was before (still using the container to fulfill dependencies).

Allow registering a provider in DI

---

src/Orleans/Core/GrainFactory.cs
src/Orleans/Core/IGrainFactory.cs

This PR moves GrainFactory XML doc comments to the interface and replaces them with `<inheritdoc />` on the class.
The side effect is that `IClusterClient` will also have documentation for those methods now.

GrainFactory XML documentation cleanup

---

src/Orleans/Core/Grain.cs
src/Orleans/Core/GrainAttributes.cs
src/Orleans/Core/GrainExtensions.cs
src/Orleans/Core/IGrainIdentity.cs
src/Orleans/Orleans.csproj
src/Orleans/Placement/HashBasedPlacement.cs
src/Orleans/Runtime/IGrainRuntime.cs
src/OrleansRuntime/Core/GrainRuntime.cs
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Placement/HashBasedPlacementDirector.cs
src/OrleansRuntime/Silo/Silo.cs
test/TestGrainInterfaces/CustomPlacement.cs
test/TestGrains/CustomPlacementGrains.cs
test/TestInternalGrains/HashBasedPlacementGrain.cs
test/TestInternalGrains/TestInternalGrains.csproj
test/Tester/Placement/CustomPlacementTests.cs

Add `HashBasedPlacement` placement strategy.
Add `HashBasedPlacementAttribute` for assigning `HashBasedPlacement` to grain classes.
Expose `GetUniformHashCode` via `IGrainIdentity`.
Add `HashBasedPlacementDirector` that leverages `GetUniformHashCode` to calculate hashes of `GrainIdentity.IdentityString` of target grains.
This partly implements #2167, and provides a way to collocate grains of different classes with same keys.

Add support for hash-based grain placement

---

src/OrleansRuntime/GrainTypeManager/SiloAssemblyLoader.cs

This will make 3rd party container adapters less brittle if they don't fully pass all the tests in https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Specification.Tests/

Remove unneeded extra constructor

---

src/Orleans/Async/TaskExtensions.cs

TaskDone.Done is obsolete. remove the remaining one. 0 warmings !

fix warnings

---

src/Orleans/Serialization/DeserializationContext.cs
src/Orleans/Serialization/ILBasedExceptionSerializer.cs
src/Orleans/Serialization/SerializationContext.cs
src/Orleans/Serialization/SerializationManager.cs
test/NonSilo.Tests/Serialization/ILBasedExceptionSerializerTests.cs

The [initial PR](https://github.com/dotnet/orleans/pull/2633#issue-203027973) for failsafe exception serialization came with the caveat that it did not support self-referential exceptions.
Unfortunately, this deficiency has affected @josiahdecker (see #2997), so it should be fixed.
This PR fixes the issue by adding support for nested `IDeserializationContext` instances. It's quite simple:
* Instead of reading position from the stream reader/writer, read it from a property on the context.
* Add an extension method to nest contexts, where the nested context is created with a specified offset from its parent.

Support exceptions with reference cycles in ILBasedExceptionSerializer

---

src/Orleans/Core/GrainAttributes.cs
src/Orleans/Orleans.csproj
src/Orleans/Streams/Predicates/AllStreamNamespacesPredicate.cs
src/Orleans/Streams/Predicates/ExactMatchStreamNamespacePredicate.cs
src/Orleans/Streams/Predicates/IStreamNamespacePredicate.cs
src/Orleans/Streams/Predicates/RegexStreamNamespacePredicate.cs
src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs
test/TestGrainInterfaces/IFilteredImplicitSubscriptionGrain.cs
test/TestGrainInterfaces/TestGrainInterfaces.csproj
test/TestGrains/FilteredImplicitSubscriptionGrain.cs
test/TestGrains/TestGrains.csproj
test/Tester/StreamingTests/SampleStreamingTests.cs

My attempt to address https://github.com/dotnet/orleans/issues/1747

Allow complex filters for ImplicitStreamSubscriptionAttribute

---

src/Orleans/Core/GrainAttributes.cs
src/OrleansCodeGenerator/GrainReferenceGenerator.cs
test/DefaultCluster.Tests/DefaultCluster.Tests.csproj
test/DefaultCluster.Tests/OneWayCallTests.cs
test/TestGrainInterfaces/ITestGrain.cs
test/TestInternalGrains/TestGrain.cs

This is an implementation of my take on #2893. I don't necessarily intend for this to be implemented, but maybe it demonstrates what's required and how it might look.
When a grain interface has a method is marked with `[OneWay]`, that method will be completed synchronously from the caller's perspective and the remote silo will not send a response message.
An alternative implementation could use a different return type as a marker, like `IOneWay` or `OneWayCall`.

Support one-way grain calls using [OneWay] method attribute

---

.gitignore
Samples/Orleans-Docker/.vscode/launch.json
Samples/Orleans-Docker/.vscode/tasks.json
Samples/Orleans-Docker/NuGet.config
Samples/Orleans-Docker/Orleans-Docker.sln
Samples/Orleans-Docker/docker-compose.override.yml
Samples/Orleans-Docker/docker-compose.yml
Samples/Orleans-Docker/src/OrleansClient/Dockerfile
Samples/Orleans-Docker/src/OrleansClient/Dockerfile.Debug
Samples/Orleans-Docker/src/OrleansClient/OrleansClient.csproj
Samples/Orleans-Docker/src/OrleansClient/Program.cs
Samples/Orleans-Docker/src/OrleansGrainInterfaces/IGreetingGrain.cs
Samples/Orleans-Docker/src/OrleansGrainInterfaces/OrleansGrainInterfaces.csproj
Samples/Orleans-Docker/src/OrleansGrains/GreetingGrain.cs
Samples/Orleans-Docker/src/OrleansGrains/OrleansGrains.csproj
Samples/Orleans-Docker/src/OrleansSilo/Dockerfile
Samples/Orleans-Docker/src/OrleansSilo/Dockerfile.Debug
Samples/Orleans-Docker/src/OrleansSilo/OrleansHostWrapper.cs
Samples/Orleans-Docker/src/OrleansSilo/OrleansSilo.csproj
Samples/Orleans-Docker/src/OrleansSilo/Program.cs

Initial Orleans-Docker sample

---

test/TestGrainInterfaces/IFilteredImplicitSubscriptionGrain.cs
test/TestGrains/FilteredImplicitSubscriptionGrain.cs

Tests were passing when the binaries are all placed in a single output folder (such as in Jenkins) but it fails when they are not (such as in VS), since when the client connect, it sends all the implicit subscriptions, and since that one is not in the interfaces project, deserialization fails

Move contract to interfaces project

---

src/OrleansAWSUtils/AWSUtils.cs

I have an Orleans project that worked fine in commercial AWS, but I kept getting "bad credentials" warnings for GovCloud when interfacing with a DynamoDB table.  It turns out, it was authenticating my GovCloud credentials against RegionEndpoint.USWest2, as us-west-2 is the default in this file, and RegionEndpoint.USGovCloudWest1 was not listed in this 'switch' statement.
This change adds us-gov-west-1 as a possible region.  http://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/T_Amazon_RegionEndpoint.htm

Added us-gov-west-1 as a possible region endpoint

---

src/Tutorials/Minimal-Orleans-Application.md

The links in the *Further Reading* section were broken.
Kind regards,
Emiel Koning

Links fixed

---

src/Orleans/Core/GrainExtensions.cs
src/Orleans/Orleans.csproj
src/Orleans/Streams/Core/ImplicitConsumerGrainExtensions.cs
src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs
test/TestGrainInterfaces/IFilteredImplicitSubscriptionWithExtensionGrain.cs
test/TestGrainInterfaces/TestGrainInterfaces.csproj
test/TestGrains/FilteredImplicitSubscriptionGrain.cs
test/TestGrains/FilteredImplicitSubscriptionWithExtensionGrain.cs
test/TestGrains/RedStreamNamespacePredicate.cs
test/TestGrains/TestGrains.csproj
test/Tester/StreamingTests/SampleStreamingTests.cs

Per discussion in https://github.com/dotnet/orleans/issues/2987

Allow IGrainWithGuidCompoundKey as implicit subscription grain

---

src/OrleansServiceBus/Providers/EventDataGeneratorStreamProvider/EventDataGeneratorStreamProvider.cs
src/OrleansServiceBus/Providers/EventDataGeneratorStreamProvider/EventHubPartitionDataGenerator.cs
src/OrleansServiceBus/Providers/EventDataGeneratorStreamProvider/EventHubPartitionGeneratorReceiver.cs
src/OrleansServiceBus/Providers/EventDataGeneratorStreamProvider/EventHubUtils.cs
src/OrleansServiceBus/Providers/EventDataGeneratorStreamProvider/IEventDataGenerator.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubBatchContainer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubReceiver.cs
test/ServiceBus.Tests/SlowConsumingTests/EHSlowConsumingTests.cs
test/ServiceBus.Tests/TestStreamProviders/EHStreamProviderWithCreatedCacheList.cs

Add more extensibility to EventDataGeneratorStreamProvider 
Open data generating infra to public, so user can create GeneratorStreamProvider with other behavior for event hub

Add more  extensibility to EventDataGeneratorStreamProvider 

---

src/Tutorials/Unit-Testing-Grains.md

Hello,
I noticed when working through the [unit testing tutorial](https://dotnet.github.io/orleans/Tutorials/Unit-Testing-Grains.html) that it uses `TestingSiloHost` which is [marked as obsolete](https://github.com/dotnet/orleans/pull/2919).
I have rewritten this tutorial to use `TestCluster`, and also added a bit of detail about mocking. I have tried to incorporate as much of the relevant content from the previous version as possible.
Hope this helps. Feed / suggestions / requests more than welcome

Update unit test tutorial to use TestCluster

---

src/Orleans.sln
src/Orleans/Serialization/BuiltInTypes.cs
src/Orleans/Serialization/SerializationManager.cs
test/NonSilo.Tests/SerializationTests/SerializationTests.DifferentTypes.cs

I know that each and every type cannot be added as a built-in type for Orleans serialization, but I think `CultureInfo` deserves that as widely used system type. Json.Net also supports it out of the box meaning that most storage providers in Orleans already support `CultureInfo` for the grain state serialization. So let's have it supported for messaging as well.

Support CultureInfo as built-in type

---

src/OrleansServiceBus/Providers/Streams/EventHub/CachePressureMonitors/AveragingCachePressureMonitor.cs
src/OrleansServiceBus/Providers/Streams/EventHub/CachePressureMonitors/SlowConsumingPressureMonitor.cs
test/ServiceBus.Tests/SlowConsumingTests/EventHubStreamProviderSettingsTests.cs

-Turn on Info on pressure monitor logging, so get more valuable trouble shooting information without changing logging config and reproduce. Just three more line of logging 
-Fix double division bug in pressure monitor settings

Turn on Info on pressure monitor logging

---

src/Orleans/Serialization/TypeUtilities.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs
test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs

A regression introduced after 1.3.1 meant that serializers were not being generated for types which have fields with generic types which use specialized, hand-coded serializers.
This fixes the regression and adds more coverage.

Fix #3030: Serializers not being generated for some types

---

src/OrleansServiceBus/Providers/Streams/EventHub/DefaultEventHubReceiverMonitor.cs

We should respect order defined in the interface :)

[Coverity] Wrong argument order for DefaultEventHubReceiverMonitor.TrackAgeOfMessagesRead

---

src/OrleansServiceBus/Providers/Streams/EventHub/EventHubStreamProviderSettings.cs

Since AvgPressureMonitorThreshold has a default value 
and EventHubStreamProvider repopulate its setting from IProviderConfig when initializing,  so just set it to null won't turn it off, it would just set it back to its default value. 
This will fix it.

fix bug on ability to turn off AvgPressureMonitor using EventHubStreamProviderSettings

---

src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProducer.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs

In #3043, @danvanderboom highlighted an issue in the current SMS stream provider whereby the thread can be yielded before an item is copied.
The cleanest fix to this which minimizes overhead and doesn't add unwanted complexity is to eagerly copy the item before we know the thread will be yielded.

Ensure items are copied before yielding the thread in SMS stream provider

---

src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProducer.cs

Fixes a minor test breakage introduced in #3048.
A test was relying on data not being copied if the optimization for immutable data was set. In reality this isn't an issue, since we don't guarantee consumers and producers are on the same silo, but the fix is trivial. I didn't realize previously that this field was available, my mistake.

SMS: avoid copy in OnNextAsync if user has specified immutable data optimization

---

src/Documentation/Getting-Started-With-Orleans/Grain-Persistence.md

The type name in the configuration example appears to be incorrect - I could find no type named `Orleans.SqlUtils.StorageProvider.SqlStorageProvider` in the `Microsoft.Orleans.SqlUtils` package. I believe the correct type name is `Orleans.Storage.AdoNetStorageProvider` and have updated the example.

Fix provider type for ADO.Net storage provider in config example

---

src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Catalog/DefaultGrainActivator.cs
src/OrleansRuntime/Catalog/GrainCreator.cs
src/OrleansRuntime/Catalog/IGrainActivationContext.cs
src/OrleansRuntime/Catalog/IGrainActivator.cs
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Silo/Silo.cs
test/TestGrainInterfaces/ISimpleDIGrain.cs
test/TestGrains/SimpleDIGrain.cs
test/Tester/DependencyInjectionGrainTests.cs
test/Tester/GrainActivatorTests.cs
test/Tester/Tester.csproj

This will instantiate grains preserving the current behavior (which is using `ActivatorUtilities`, similar to MVC
s `DefaultControllerActivator`), but allows replacing this service with a custom activator.
This enables less constraining integration with some 3rd party containers, or even manually instantiating grains.
In the future, I envision the `IGrainActivationContext` instance be resolved as a scoped service as defined in #2856.

Add extensibility point to replace the grain activator

---

src/Orleans/Configuration/ClusterConfiguration.cs

Fix resolve ip address.
We have a problem when configuring silo hosts. If I setup in hosts file network name (for example 'orleans') with IP 127.0.0.1 and set it as Address in SeedNode, Networking or ProxyingGateway the load configuration will trow `ArgumentException`. The host name 'orleans' is a valid host with valid loopback IP in this case.
So this fix checks any valid host name from hosts file, DNS entries (including case whena DNS responds 'localhost' or '127.0.0.1'). In additional I add parsing IP addresses (IPv4 and IPv6). So it possible to set not only 127.0.0.1, but any valid IP address.

Fix resolve ip address.

---

src/Orleans/Orleans.csproj
src/Orleans/Serialization/OrleansSerializer.cs
src/Orleans/Serialization/SerializationManager.cs

Hi,
As discussed with @ReubenBond in #3064 , I'm exposing `IsOrleansShallowCopyable` for external custom serializer.
Background: I've created a custom serializer for `ObservableCollection`, and copied the logic of copying `List<T>` from `BuiltInTypes.DeepCopyList()`, it uses this method to allow quick shallow copy.

Exposing internal IsOrleansShallowCopyable to for external custom serializers 

---

src/OrleansRuntime/Catalog/ActivationData.cs
test/TestGrainInterfaces/IStuckGrain.cs
test/TestGrains/StuckGrain.cs
test/TesterInternal/OrleansRuntime/StuckGrainTests.cs

A Grain can be blocked on the Deactivating state. The following PR extends the logic implemented in #2387 to detect such case.

Blocked grains in "Deactivating" state detection and mitigation 

---

src/Tutorials/Unit-Testing-Grains.md

As per the comments on #3028 fix the `Dispose()` method on `ClusterFixture` so that it calls `StopAllSilos()`.

Correct ClusterFixture's Dispose() method in unit testing tutorial

---

src/Documentation/Getting-Started-With-Orleans/Grain-Persistence.md

I have rewritten the ADO .NET and MemoryStorage provider sections in the Grain Persistence documentation page. The samples and tables are mainly taken from my [ADO .NET Grain Persistence](http://gigi.nullneuron.net/gigilabs/orleans-grain-persistence-with-the-ado-net-storage-provider/) and [Introduction to Grain persistence](http://gigi.nullneuron.net/gigilabs/introduction-to-grain-persistence-with-microsoft-orleans/) articles.
Some things worth noting:
* I have added samples for both XML configuration and code configuration.
* I have added tables listing all the properties you can set.
* I have removed references to PostgreSQL since this is not actually supported (partly addresses #3085).
* I have removed examples of SQL Server specific connection strings as well as a code block showing …

Rewrote sections on ADO .NET and MemoryStorage providers

---

src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
src/OrleansAzureUtils/Storage/StorageExceptionExtensions.cs

We observe the following scenario from time to time - the grain writes its state for the first time, the server returns `ServerTimeoutError` (no eTag returned), then the next time the grain tries to write its state, the server returns `Conflict` because the first insert actually happened.
I think it should follow the same pattern as with Precondition Failed and use the logic added in https://github.com/dotnet/orleans/pull/2959

Wrap Blob/Table Storage Conflict error into InconsistentStateException

---

src/OrleansServiceFabricUtils/FabricMembershipOracle.cs
src/OrleansServiceFabricUtils/Utilities/ErrorCode.cs
test/TestServiceFabric/FabricMembershipOracleTests.cs

Instead of setting a no-longer-present silo's status to `SiloStatus.None`, leave a tombstone declaring it `Dead`.
Related to #3056

Service Fabric: Mark removed silos as Dead indefinitely

---

Samples/ServiceFabric/Stateless/StatelessCalculatorService/Program.cs
Samples/ServiceFabric/Stateless/StatelessCalculatorService/StatelessCalculatorService.cs
src/OrleansServiceFabricUtils/FabricMembershipOracle.cs
test/TestServiceFabric/FabricMembershipOracleTests.cs

Fix for #3057, in which @rikbosch is experiencing threading issues caused by the `FabricMembershipOracle` not executing cluster status notifications on an Orleans thread.
Proposed solution is to capture the `OrleansTaskScheduler` in the `IMembershipOracle.Start` call and later use it to schedule notifications.

Service Fabric: execute cluster update notifications on an Orleans thread

---

src/Orleans/Configuration/ConfigUtilities.cs
src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
test/NonSilo.Tests/ConfigTests.cs

Mask DynamoDB and ServiceBus connection strings, as well as SAS tokens in Azure Storage.

Redact more connection strings when logging

---

src/docfx.json

Gif file are not copied in docfx, I had to add a rule for that.
Without that we cannot see the beautiful gif I made for the rolling upgrade. It would be a shame, isn't it?

Add rule in docfx to copy gif in output folder

---

src/Documentation/Getting-Started-With-Orleans/Observers.md

Improved observer docs a bit, next step is to create a section for communication in the system which will contain streams, observers and grain-grain and client-grain communication and will have a page comparing observers and SMS streams

Observer doc improvements

---

src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs

GlobalConfig and NodeConfig is not available in client side. So those two shouldn't be required.

Fix client side EHStreamProvider init

---

test/TestGrains/StreamInterceptionGrain.cs

Apparently, I missed this one in #3083 and introduced a build warning

Remove IGrainInvokeInterceptor obsoletion warning in test

---

src/Orleans/Statistics/StatisticNames.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansTelemetryConsumers.Counters/PerfCounterConfigData.cs
test/NonSilo.Tests/OrleansRuntime/ExceptionsTests.cs
test/TestGrainInterfaces/ICatalogTestGrain.cs
test/TestGrains/CatalogTestGrain.cs
test/Tester/DuplicateActivationsTests.cs

This PR resolves #2733.
The fix focuses on the logic in `Catalog.InitActivation(...)` and how it interacts with `Catalog.RegisterActivationInGrainDirectoryAndValidate(...)`. Specifically, it removes the `DuplicateActivationException` thrown by the latter and caught by the former. Doing that required slightly reworking the control flow in `InitActivation` so that exceptions aren't the only means of error handling.
* Move recovery logic in `InitActivation` from `catch` to a new method which is called from the `finally` block.
* Return a new `ActivationRegistrationResult` struct from `RegisterActivationInGrainDirectoryAndValidate` which replaces `DuplicateActivationException`.
* When an activation fails to register, return early from `InitActivation` so that the `finally` block can clean up …

Replace DuplicateActivationException with a strongly-typed return value

---

src/OrleansRuntime/Catalog/Catalog.cs

If a `LogConsistencyProvider` is configured with the name `Default` then a `JournaledGrain` without a `LogConsistencyProviderAttribute` will use that provider. However, a bug in a logging statement resulted in a `NullReferenceException`. The name of the provider was retrieved from the variable `attr` that is `null` when no attribute is specified.
The fix is to get the name of the provider from the provider itself.
It took me some time to pinpoint the location of this bug in the source code. Interestingly, when I opened the file in Visual Studio ReSharper flagged the exact statement I had located by code inspection with a green squiggly to indicate a possible `NullReferenceException`.

Fix NullReferenceException when no LogConsistencyProvider attribute is provided

---

test/TestServiceFabric/FabricMembershipOracleTests.cs

This test has proved to be non-deterministic during functional runs. This makes the test sequencing more obvious & explicit.

Improve reliability of Service Fabric HandlesSiloAdditionAndRemoval test

---

src/OrleansSQLUtils/Storage/DbConstantsStore.cs

This allocates and extra task so as not to block the calling
thread and Orleans scheduler if the ADO.NET library has synchronous
functionality. This shouldn't have a major performance impact.
Fixes https://github.com/dotnet/orleans/issues/3141

Flags PostgreSQL as synchronous to avoid locking in DB thread

---

test/ServiceBus.Tests/StatisticMonitorTests/CacheMonitorForTesting.cs
test/ServiceBus.Tests/StatisticMonitorTests/EHStatisticMonitorTests.cs
test/ServiceBus.Tests/TestStreamProviders/EHStreamProviderForMonitorTests.cs

EHStatictiscMonitorTests fail intermittently, because the test is taking a way to trigger cache pressure changing, which depends a lot on timing. Change this way to a more predictable model, which is  directly injecting cache pressure status.

Make EHStatisticMonitorTests more predictable

---

src/OrleansRuntime/Core/ManagementGrain.cs
src/OrleansServiceFabricUtils/OrleansServiceFabricExtensions.cs

This PR fixes #3159 
It explicitly adds implementation for ISiloStatusOracle, based on already registered IMembershipOracle.

Add ISiloStatusOracle registration to servicecollection

---

src/OrleansServiceFabricUtils/FabricMembershipOracle.cs
src/OrleansServiceFabricUtils/OrleansCommunicationListener.cs
src/OrleansServiceFabricUtils/OrleansServiceFabricUtils.csproj
src/OrleansServiceFabricUtils/Utilities/WaitHandleExtensions.cs
test/TestServiceFabric/FabricMembershipOracleTests.cs

There is some flakiness in the `HandlesSiloAdditionAndRemoval` test which was caused by non-deterministic execution order of the notifications since we started scheduling those on the task scheduler (see #3059). 
Tests use the default task scheduler (multi-threaded, no strict ordering), real deployments use single-threaded task scheduler. So this PR tightens up the ordering of notifications and fixes a few other issues:
* Starts an async worker using the captured task scheduler to process all notifications. The worker awaits an `AutoResetEvent` and pulls notifications from a queue and delivers them in order.
* `KillMyself` is always called to destroy the oracle, and it's always called last, so finalization logic has been moved from `Stop` and `Shutdown`.
* #3061 introduced an issue …

Service Fabric: make cluster change notifications determinsitic

---

src/Orleans/Providers/IStorageProvider.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
test/TestGrainInterfaces/IPersistenceTestGrains.cs
test/TestInternalGrains/PersistenceTestGrains.cs
test/TesterInternal/StorageTests/PersistenceGrainTests.cs

As pointed out by @jdom, if a grain allows an `InconsistentStateException` to escape, then every grain in the call chain will be deactivated.
This fixes that by introducing a flag onto the exception itself. The flag is reset when the exception first passes through the invoker and the current activation is deactivated.

Only allow InconsistentStateException to deactivate the current activation

---

src/OrleansTestingHost/TestCluster.cs
test/TesterInternal/MembershipTests/ClientIdPartitionDataRebuildTests.cs

Increase ProbeTimeout to reduce chances of failures in slower machines.
Speed up test setup by restarting client instead of entire cluster.

Make ReconstructClientIdPartitionTest_Request test more reliable

---

Samples/ServiceFabric/GrainInterfaces/GrainInterfaces.csproj
Samples/ServiceFabric/GrainInterfaces/app.config
Samples/ServiceFabric/GrainInterfaces/packages.config
Samples/ServiceFabric/Grains/Grains.csproj
Samples/ServiceFabric/Grains/app.config
Samples/ServiceFabric/Grains/packages.config
Samples/ServiceFabric/Stateless/StatelessCalculatorApp/StatelessCalculatorApp.sfproj
Samples/ServiceFabric/Stateless/StatelessCalculatorApp/app.config
Samples/ServiceFabric/Stateless/StatelessCalculatorApp/packages.config
Samples/ServiceFabric/Stateless/StatelessCalculatorClient/StatelessCalculatorClient.csproj
Samples/ServiceFabric/Stateless/StatelessCalculatorClient/app.config
Samples/ServiceFabric/Stateless/StatelessCalculatorClient/packages.config
Samples/ServiceFabric/Stateless/StatelessCalculatorService/StatelessCalculatorService.csproj
Samples/ServiceFabric/Stateless/StatelessCalculatorService/app.config
Samples/ServiceFabric/Stateless/StatelessCalculatorService/packages.config

In order to work with version 1.5 there was a need to update the
dependecies for the abstraction so I took the time to also update the
other dependencies. I did upgrade the Service fabric host to the most
recent version of the service fabric.

Updating the SF sample to version new packages

---

changelog.md

Made 1 commit with the additions since 1.5.0-RC, and a second commit collapsing and getting rid of the intermediate pre-releases. I also removed the stuff already shipped in 1.4.2 (which was after the beta1 was releases), so that it;s clear for end users planning to upgrade from 1.4.2 to 1.5.0

Changelog for 1.5.0 final

---

src/Build.cmd

Skip VSIX build unless BuildOrleansVSIX env variable is set to true

---

src/Orleans/Core/ClientBuilder.cs
src/Orleans/Core/GrainExtensions.cs
src/Orleans/Core/GrainFactory.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/GrainReference.cs
src/Orleans/Runtime/GrainReferenceRuntime.cs
src/Orleans/Runtime/IGrainReferenceRuntime.cs
src/Orleans/Runtime/IRuntimeClient.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Serialization/GrainReferenceSerializer.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansCodeGenerator/GrainReferenceGenerator.cs
src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Scheduler/InvokeWorkItem.cs
src/OrleansRuntime/Silo/Silo.cs
test/DefaultCluster.Tests/KeyExtensionTests.cs
test/NonSilo.Tests/General/Identifiertests.cs

In preparation to move `GrainReference` to an Abstractions assembly, but still keep the logic inside the Orleans implementation.
- `GrainReference` is now bound to `IGrainReferenceRuntime` instead of `IRuntimeClient`. The new runtime abstraction includes all the logic that was previously part of `GrainReference`, and it's a much more reduced surface area compared to `IRuntimeClient`, to expose to the public.
- Moved Orleans-specific serialization outside the base abstraction.

Separate logic from base GrainReference

---

src/OrleansPSUtils/OrleansPSUtils.csproj
src/OrleansPSUtils/OrleansPSUtils.psd1
vNext/src/OrleansPSUtils/OrleansPSUtils.csproj

Need to do this for publishing OrleansPSUtils.dll to the PS Gallery (#131).
I already published 1.5.0 version of it manually. This is to update the sources to match what I had to change by hand.

Rename Orleans.psd1 to OrleansPSUtils.psd1

---

src/Documentation/Advanced-Concepts/Cancellation-Tokens.md

While on https://github.com/dotnet/orleans/blob/gh-pages/src/Documentation/Advanced-Concepts/Cancellation-Tokens.md/#L1 everything is fine with formatting, generated by DocFx page at http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Cancellation-Tokens.html#description has issues with dispaying of code-blocks. This change attempts to address that.

Fix cancellation tokens page formatting

---

src/Documentation/Advanced-Concepts/toc.yml

Went missing after https://github.com/dotnet/orleans/commit/ab62666347d2e0c23dcadb50b511fc574c20b64b

Add link to Cancellation Tokens page

---

src/OrleansAWSUtils/Storage/DynamoDBStorage.cs

OrleansAwsUtils currently requires explicit credentials to connect to DynamoDB. These are supplied via the Orleans SystemStore DataConnectionString in the silo config.
This change introduces support for implicit authentication via EC2 IAM Roles, which avoids the need to have explicit credentials in the config files.
If no 'AccessKey' and 'SecretKey' attributes are included in the connection string, the AmazonDynamoDBClient is created without any credentials supplied, which results in the AWS SDK checking the usual locations for credentials (including the EC2 instance profile service):
http://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/MDynamoDBv2DynamoDBctorDynamoDBConfig.html
This is not a breaking change - the present behaviour will remain the same for any users already …

OrleansAwsUtils: support implicit authentication to DynamoDB (e.g. via IAM Roles)

---

src/Orleans/CodeGeneration/GeneratedAssembly.cs
src/OrleansCodeGenerator/CodeGeneratorCommon.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs

Fixes #3233
* Embed debug info into the asm instead of emitting a separate PDB
* Fix `EmitOptions` for the recent breakage in Roslyn 2.3.0. Technically, only `WithEmitMetadataOnly(false)` is needed, but `WithIncludePrivateMembers(true)` is added just to be explicit about it
* Cleanup redundancies
* I added `WithTolerateErrors(true)`, but I'm not sure entirely what it does. The way I see it, if Roslyn can ignore some kinds of errors (eg, obsolete member accesses), then that's good.

Update EmitOptions used during runtime codegen

---

src/Orleans/Runtime/OutsideRuntimeClient.cs

`IServiceProvider` implementations do not necessarily implement `IDisposable`, but most do.

Dispose IServiceProvider during client shutdown.

---

src/OrleansHost/app.config
src/OrleansRuntime/Silo/Silo.cs
src/OrleansServiceFabricUtils/App.config
test/AWSUtils.Tests/App.config
test/Benchmarks/Benchmarks/App.config
test/BondUtils.Tests/App.config
test/Consul.Tests/App.config
test/DefaultCluster.Tests/App.config
test/GoogleUtils.Tests/App.config
test/PSUtils.Tests/App.config
test/ServiceBus.Tests/App.config
test/TestServiceFabric/App.config
test/Tester/App.config
test/TesterAzureUtils/App.config
test/TesterInternal/App.config
test/TesterSQLUtils/App.config
test/TesterZooKeeperUtils/App.config

Tests on .NET 4.6.2 show that performance with concurrent GC enabled is the same or better than without it. Time to change the recommendation.

Switch to gcConcurrent=true

---

src/Orleans/Serialization/SerializationManager.cs

There is room for confusion and error when developers write custom serializers when it comes to passing the correct value for `expectedType` in both `SerializationManager.DeserializeInner(...)` and `SerializationManager.SerializeInner(...)`. The `expectedType` values passed to those methods must correspond and must be equal to the static type of each field (not the runtime type).
This PR introduces a generic `SerializeInner` variant: `void SerializeInner<T>(T obj, ISerializationContext context)` to match with the existing generic `DeserializeInner` method, `T DeserializeInner<T>(IDeserializationContext context)`.
The intention is to use this method in samples in the custom serializer documentation. For example:
```C#
public class User
{
public User BestFriend { get; set; }
public string …
```

Add generic SerializeInner variant

---

src/Orleans/Serialization/SerializationManager.cs

While working on #3281, I've noticed that there is implemented support for 7-component tuples in `BuiltInTypes` (see `DeepCopyTuple7`/`SerializeTuple7`/`DeserializeTuple7`), but it is not registered in `SerializationManager`

Added missing registration for 7-component tuple serialization

---

test/NonSilo.Tests/OrleansRuntime/AsyncSerialExecutorTests.cs

Fixed intermittent test failure in AsyncSerialExecutorTests_ParallelSubmit related to multithreaded manipulation of a list.

AsyncSerialExecutor ParallelSubmit test fix

---

src/Orleans/Lifecycle/ILifecycleObservable.cs
src/Orleans/Lifecycle/ILifecycleObserver.cs
src/Orleans/Lifecycle/ILifecycleParticipant.cs
src/Orleans/Lifecycle/LifecycleExtensions.cs
src/Orleans/Lifecycle/LifecycleObservable.cs
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/IGrainActivationContext.cs
src/Orleans/Runtime/IGrainLifeCycle.cs
src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Catalog/GrainLifecycle.cs
src/OrleansRuntime/OrleansRuntime.csproj
test/Tester/Lifecycle/LifecycleTests.cs
test/Tester/Tester.csproj

This PR is a prerequisite of Orleans Facet System #3223 and introduces a grain lifecycle framework to allow facets to participate in exposed aspects of the grain lifecycle.
**Lifecycle Management Pattern**
This PR introduces a general component lifecycle management pattern wherein participants in a component's lifecycle are notified as the component is started and stopped.
Component startup notifications are handled in order of the stages of the lifecycle.
Component shutdown notifications are handled in the reverse order of the stages, starting at the highest stage reached during startup.
This lifecycle management is intended to provide a more testable, maintainable, modular and extensible means of managing grain, silo, and possibly cluster startup and shutdown logic, all of which are …

Component lifecycle pattern, and preliminary grain lifecycle hooks.

---

src/Orleans/Streams/Internal/StreamDirectory.cs
test/Tester/StreamingTests/SampleStreamingTests.cs

Improve thrown NullReferenceException when calling `GetStream<T>`, by throwing a more understanable exception. 
Stream is typed, but stream id isn't. If application reference a stream with a different type, but using the same stream id, then `GetStream<T>` will throw a `NullReferenceException`. Because runtime is casting a `IAsyncStream<T1>` to a `IAsyncStream<T2>`
This is confusing to users. So throw a more understandable exception to help user fixing their application code.

Improve thrown NullReferenceException when calling GetStream<T>

---

test/TesterAzureUtils/Lease/LeaseBasedQueueBalancerTests.cs

-set leaseLength to be 15 sec, which is the new minimum allowable lease length for azure blob lease.

Fix LeaseBasedQueueBalancerTests

---

src/OrleansRuntime/GrainTypeManager/TypeManager.cs
src/OrleansRuntime/Silo/Silo.cs
test/Tester/HeterogeneousSilosTests/UpgradeTests/RuntimeStrategyChangeTests.cs

Replace PR #3256
> In Silo.DoStart() we should be scheduling TypeManager.Initialize() on the TypeManager's context (it's a system target), since it starts a timer which potentially makes grain calls.
> The timer started there also needs to invoke its callback on the TypeManager's context.
Also `TypeManager.Initialize` should be call after the Silo joined the cluster, otherwise the silo that is starting cannot talk to silo that are already active in the cluster. It means that we can have a very small window where a silo that join cluster can make placement without respecting versioning strategies. 
A more complete fix will be implemented in 2.0 since it will likely be a breaking change

Execute TypeManager timers in the correct runtime context 

---

src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueAdapterCache.cs

Fix for #3300 
holding reference of created caches in SimpleQueueAdapterCache would cause problems when queue shifting in a cluster auto-scale event. Since that cache reference wasn't cleared when its queue shifted to other silo, if that queue is ever shifted back to previous silo, legacy data in the cache cause problems.

SimpleQueueAdapterCache shouldn't cache reference of created caches

---

src/Orleans/Serialization/SerializationManager.cs

Fixes #3268
This is not blocking for 1.5.1, but it's small and low risk to include.

SerializationManager: register additional generic collection interfaces

---

src/Orleans/Core/ClusterClient.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs

As per recommendation here https://github.com/dotnet/orleans/issues/3299#issuecomment-322528018
Note that:
* `Dispose()` is equivalent to `Abort()`
* `Abort()` is equivalent to a blocking call to `Stop(graceful: false)`
* `Close()` is equivalent to `Stop(graceful: true)`
(`Stop(bool)` is private)

ClusterClient: Dispose() is equivalent to Abort()

---

src/Orleans/Core/Exceptions.cs
src/Orleans/Messaging/MessageFactory.cs
src/Orleans/Runtime/GrainReferenceRuntime.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs
test/DefaultCluster.Tests/BasicActivationTests.cs
test/DefaultCluster.Tests/GrainActivateDeactivateTests.cs
test/TesterInternal/StorageTests/PersistenceGrainTests.cs
test/TesterInternal/StreamingTests/StreamPubSubReliabilityTests.cs

Fixes #3213
* Failures in `OnActivateAsync` will be propagated directly back to the caller.
* Calls will be retried up to `IMessagingConfiguration.MaxResendCount` times (default is 0) because the rejection is marked as `Transient`.
* Other message rejections which include an exception will also be propagated directly back to the caller, but this doesn't seem undesirable. The difference is that previously the exception would be discarded in favor of a generic exception (`OrleansMessageRejectionException`) which typically contained the original exception's `Message` in its `Message` property.

Directly propagate OnActivateAsync failures to callers

---

src/Orleans/Streams/PersistentStreams/IStreamQueueBalancer.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/SystemTargetExtensions.cs
src/OrleansRuntime/GrainDirectory/ILocalGrainDirectory.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs
src/OrleansRuntime/MultiClusterNetwork/MultiClusterOracle.cs
src/OrleansRuntime/Placement/DeploymentLoadPublisher.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingManager.cs

Fixes #3273
Implementations of `ISiloStatusListener` and `IRingRangeListener` must correctly marshall calls onto their own execution context in order to preserve correct scheduling semantics.
* Add `.ScheduleTask(...)` extension methods to `SystemTarget` so that implementations can easily schedule these callbacks.
* ~~Add `IAddressableContextScheduler` which provides methods for executing actions on an addressable scheduling context (so that grain calls can be made). It can be injected via `Factory<IAddressableContextScheduler>`.~~
* Remove `IAddressable` from `IStreamQueueBalanceListener` and have `PersistentStreamPullingManager` subscribe to ring range change notifications directly (instead of via a ref, `.AsReference<IStreamQueueBalanceListener>()`)
* Verified locally using Service …

Fix scheduling of notification interfaces

---

src/Orleans/Core/ClientBuilder.cs
src/Orleans/Core/ClientBuilderExtensions.cs
src/Orleans/Core/IClientBuilder.cs
src/Orleans/Hosting/DelegateServiceProviderFactory.cs
src/Orleans/Hosting/IServiceProviderFactoryAdapter.cs
src/Orleans/Hosting/ServiceProviderBuilder.cs
src/Orleans/Hosting/ServiceProviderFactoryAdapter.cs
src/OrleansRuntime/Hosting/DefaultSiloServices.cs
src/OrleansRuntime/Hosting/ISilo.cs
src/OrleansRuntime/Hosting/ISiloBuilder.cs
src/OrleansRuntime/Hosting/SiloBuilder.cs
src/OrleansRuntime/Hosting/SiloBuilderExtensions.cs
src/OrleansRuntime/Hosting/SiloWrapper.cs
src/OrleansRuntime/Silo/Silo.cs

* ClientBuilder supports custom containers in the same fashion as SiloBuilder
* Extracted common logic from ClientBuilder and SiloBuilder into internal ServiceProviderBuilder
* ClientBuilder adds its default services after the user-configured services. Default services are only added if the user did not configure an implementation for a given service (using TryAdd*) - this unifies it with SiloBuilder

Support custom DI container in ClientBuilder and unify with SiloBuilder

---

src/Orleans/IDs/UniqueKey.cs
test/NonSilo.Tests/General/Identifiertests.cs

Since this is a potentially dangerous change, please review this CR carefully.
~~This PR will consist of 2 commits:~~
- the first will remove the dependency to serialization in `UniqueKey` by duplicating the existing logic from `BinaryTokenStreamWriter.Write(UniqueKey key)`. I added a test to check that the value returned by the new method is consistent with the previous method.
- ~~the second (to come after this first commit pass the build) will remove the code duplication in `BinaryTokenStreamWriter` by calling the method added in the first commit.~~
~~Basically this will "invert" the dependency.~~
After thoughts, I don't think we should to the 2nd commit, since they are not supposed to share the same logic after all. But I will keep the test to show that the value used for the hash is …

[Abstractions] Remove dependency from Serialization in UniqueKey

---

Build-Core.cmd
src/ClientGenerator/ClientGenerator.csproj

- Fix ClientGenerator nuget to include every dll from the output folder (netstandard 2.0 was left out after update)
- Add a possibility to override build flags if needed (for example to enable parallel build)

Fix ClientGenerator nuget pack, add possibility to override build flags

---

Directory.Build.props
test/Directory.Build.props

- Update nuget package versions for 2.0 to align with .NET Core 2.0 release and other minor upgrades based on NetStandard compatibility and/or features.
- Change Debug type to full for test projects, so Test Explorer source code navigation and CodeLens will work again in VS.

NuGet updates and Debug type change for test projects

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/AssemblyLoader/CachedReflectionOnlyTypeResolver.cs
src/Orleans/CodeGeneration/TypeUtils.cs

This quick fix should allow loading on .NET Core 2.0. It's not ideal, but it ought to allow us to perform a 2.0 Technical Preview refresh

Quick fix for .NET Core PNSE on ReflectionOnlyType

---

src/OrleansSQLUtils/CreateOrleansTables_PostgreSql.sql
test/TesterSQLUtils/StorageTests/Relational/PostgreSqlStorageTests.cs

Fix Postgresql CreateOrleansTables script
Add PostgreSqlStorageTests.
Huge thanks to @halfnelson for getting the SQL script working. Tests seem to be passing except for those referenced in  https://github.com/dotnet/orleans/pull/3163#issuecomment-313326305.
See screenshot:

Get Postgres Storage Provider Working

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/CodeGeneration/TypeUtils.cs
test/NonSilo.Tests/AssemblyLoaderTests.cs

If ReflectionOnly assembly loading is not supported by the platform (which is the case in .NET Core), then fall back to fully loading every assembly for scanning.
In the future we will avoid this loading entirely, and only scan assemblies that were explicitly passed in (and pre-loaded) by the application developer.
In the meantime, the old behavior is preserved (by using ReflectionOnly) if the application is running in .NET.
This is a follow up from the PR https://github.com/dotnet/orleans/pull/3389 that was reverted

Fall back to full loading on .NET Core

---

src/OrleansRuntime/Catalog/ActivationCollector.cs
test/TesterInternal/ActivationsLifeCycleTests/ActivationCollectorTests.cs

Fix for #3165 and #3352 
When an `Activation.ScanAll` is called, we do not remove the `ActivationData` from the bucket, instead we set the value to `null`, that can cause `NullReferenceException` when we iterate again the `ActivationData` from the bucket.
I removed completely the `Bucket.TryCancel` method and merged the logic in `Bucket.TryRemove`. I am not sure what was the idea behind setting this to null instead of removing it (freeing some memory when iterating on the bucket?), but I don't think it was necessary.

Remove Bucket.TryCancel and use Bucket.TryRemove instead

---

src/Orleans/Runtime/OutsideRuntimeClient.cs

Fixes #3363 
Prevents clients from becoming zombies if a failure occurs in `RunClientMessagePump`

Improve resiliency in OutsideRuntimeClient.RunClientMessagePump

---

src/Orleans/Serialization/OrleansJsonSerializer.cs

making the JsonCoverters public classes so they can be re-used by custom external serializers. This is following the discussion in issue #3298

making JsonConverters inside OrleansJsonSerializer public

---

src/Orleans/Serialization/OrleansJsonSerializer.cs

controlling the type name handling in the json serializer by optional configuration property, in continuation of discussion in issue #3298

OrleansJsonSerializer sets TypeNameHandling settings according to config

---

src/OrleansServiceFabricUtils/FabricServiceSiloResolver.cs

We were seeing a steadily increasing CPU usage on our service-fabric hosted silos & orleans clients. We tracked this down to Fabric Data Collection Agent, which writes ETW trace logs to disk (among other things, i assume). 
After 3 days of uptime on our cluster, we were seeing about 700,000 events with the id 55639 per minute in the ETW logs and even though these events contain basically no useful information, we tracked this down to RegisterServicePartitionResolutionChangeHandler. Every time FabricServiceSiloResolver.Refresh() was called, the ETW logs would be spammed with all the current handler IDs as well as the new one. 
I believe one should not re-register for the notifications, especially if not cleaning up the old handler IDs for those partitions.
I opted to change the code to not …

Fix leak in registration of partition notifications

---

src/Orleans/SystemTargetInterfaces/ISiloControl.cs
src/OrleansRuntime/Hosting/DefaultSiloServices.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloControl.cs
src/OrleansRuntime/Streams/StreamProviderManagerAgent.cs

Remove usages of Silo class that were being resolved from the container.
This reduces the exposure of this big class as a dependency to other components.
It enables silo builders that do not register `Silo` in the container, which is useful as we experiment with the generic HostBuilder in Microsoft.Extensions.Hosting (pre-release)

Remove usages of Silo class from the container

---

src/OrleansRuntime/GrainDirectory/GrainDirectoryHandoffManager.cs

This pull request is something uncovered while trying to fix the issue outlined in #3419
While we have not experienced an issue or seen any exceptions regarding this, it felt like a good opportunity to tackle this one as well.
Inside `GrainDirectoryHandoffManager` there are modifications made to `directoryPartitionsMap` while not holding a lock.
The suggested fix is straight forward, wrap the function bodies in a lock.
I opted to wrap the entire body in a lock() instead of trying to minimize the time the lock is held. This is done to mirror the style the rest of the code in this class.

Fix locks in GrainDirectoryHandoffManager 2/2

---

src/Orleans.Core.Abstractions/Exceptions/OrleansException.cs
src/Orleans.Core.Abstractions/Orleans.Core.Abstractions.csproj
src/Orleans/Core/Exceptions.cs

.NET Standard < 2.0 does not have the exception constructor with serialization stuff, so I had to update the target framework
A lot of exceptions are in `Exceptions.cs` in Orleans. As `OrleansException` is the base exception, it needs to be moved first.
I created a folder in Abstractions to move all exceptions from `Exceptions.cs`.

[Abstractions] Update abstractions to .NET Standard 2.0 and move OrleansException

---

Build.cmd
Test.cmd
netci.groovy

Build only 1 configuration instead of both Debug and Release in Build.cmd
Default local development environment to Debug, but CI environment to Release.

Build only one configuration in Build.cmd

---

src/OrleansRuntime/Development/DevelopmentSiloBuilderExtensions.cs
src/OrleansRuntime/Development/InMemoryLeaseProvider.cs
test/DefaultCluster.Tests/Lease/GoldenPathInMemoryLeaseProviderTests.cs
test/TestExtensions/Runners/GoldenPathLeaseProviderTestRunner.cs
test/TestExtensions/TestExtensions.csproj
test/TesterAzureUtils/Lease/AzureBlobLeaseProviderTests.cs

- Added in-memory lease provider for dev/test use.
- Moved lease provider tests to a test runner so lease provider implementation can be uniformly verified.
- Added tests for in-memory lease provider.

In memory Lease provider (for development/test)

---

src/ClientGenerator/ClientGenerator.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs

During build-time code generation, perform an early check that an assembly references Orleans.dll and avoid the existing check.

CodeGen: Check reference to Orleans.dll earlier

---

Directory.Build.props
src/ClientGenerator/ClientGenerator.cs
src/Orleans/Configuration/Legacy/LegacyConfigurationExtensions.cs
src/Orleans/Configuration/MessagingConfiguration.cs
src/Orleans/Configuration/Options/ClientMessagingOptions.cs
src/Orleans/Configuration/Options/MessagingOptions.cs
src/Orleans/Configuration/Options/SerializationProviderOptions.cs
src/Orleans/Configuration/Options/SiloMessagingOptions.cs
src/Orleans/Core/ClientBuilder.cs
src/Orleans/Messaging/BufferPool.cs
src/Orleans/Messaging/GatewayConnection.cs
src/Orleans/Messaging/Message.cs
src/Orleans/Messaging/OutgoingMessageSender.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/AsynchQueueAgent.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Counters/SiloStatisticsManager.cs
src/OrleansRuntime/Hosting/DefaultSiloServices.cs
src/OrleansRuntime/Messaging/Gateway.cs
src/OrleansRuntime/Messaging/SiloMessageSender.cs
src/OrleansRuntime/MultiClusterNetwork/MultiClusterOracle.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloInitializationParameters.cs
test/NonSilo.Tests/OrleansRuntime/ExceptionsTests.cs
test/TesterAzureUtils/Streaming/AzureQueueAdapterTests.cs
test/TesterInternal/LivenessTests/ConsistentRingProviderTests.cs
test/TesterInternal/StorageTests/HierarchicalKeyStoreTests.cs

This PR is first of the n PRs which will add IOptions based configuration system for Orleans 2.0, replacing the old one.
The first class that was added is the divided version of IMessagingConfiguration. It is separated into its Client and Silo counterparts, SerializationProviderOptions was extracted into a separate class.
For easier transition LegacyConfigurationExtensions adds 1-1 extension method to support the mapping of old configuration objects to their IOptions counterpart for client and silo.
That is not a goal of the OR to replace every reference to IMessagingConfiguration and MessagingConfiguration, those changes will be applied incrementally to the codebase.
After the full migration of the old configuration system, the configuration classes and legacy support extension methods …

Move configuration system to an IOptions based one

---

src/Orleans/Messaging/GatewayConnection.cs
src/Orleans/Messaging/IMessageCenter.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Messaging/SocketManager.cs
src/Orleans/Runtime/CallbackData.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Messaging/Gateway.cs
src/OrleansRuntime/Messaging/MessageCenter.cs
src/OrleansRuntime/Messaging/OutboundMessageQueue.cs

- Remove references to IMessagingConfiguration interface
- Remove IMessagingconfiguration dependency in various classes like GatewayConnection, IMessageCenter, ProxiedMessageCenter
- Pass or store single property from options where only it was the only purpose of storing the whole configuration class in field variable

Cleanup IMessagingConfiguration usage

---

test/TesterAzureUtils/Deployment/AzureSiloTests.cs

- Remove test that forcibly runs in the emulator from the Functional category.
- Add a test that validates configuration if the connection string is set.

Disable test that forcibly runs in the emulator in CI environments

---

src/OrleansRuntime/Development/InMemoryLeaseProvider.cs

Bugfix - In-memory lease provider used timestamp as token, which failed to be unique in some fast running tests.
The fix is to always generate a new guid for the token.

Bugfix - In-memory lease provider

---

src/OrleansAWSUtils/Storage/SQSStorage.cs

You can now use connection strings like: `Service=http://localhost:20003`.
It allows usage of elasticmq (SQS drop in replacement) which is useful for local development.
Code for it I took from DynamoDBStorage with minimal changes.
Didn't know if I should make a test for it.
Works for me.

AWSUtils SQS allow localhost connection

---

src/OrleansTestingHost/OrleansTestingHost.csproj
src/OrleansTestingHost/Utils/TestingUtils.cs

Make `DefaultSiloBuilderFactory` to be just configured with a `FileLoggerProvider`. Orleans tests are just configured with a FileLoggerProvider also. 
If user want to turn on console logging on TestCluster, they can configure it through `ISiloBuilder` or `IClientBuilder` and `ISiloBuilderFactory`. Or they can turn on `TraceToConsole` in `TestClusterOptions`, if we bring this feature back using #3486

Turn off console logging on tests

---

test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs

Skip serialization test for ValueTuple which behaves erratically depending on the test host version

Skip test in 1.5.2

---

Directory.Build.props
test/Directory.Build.props

Disable doc generation explicitly for tests and disable docgen warning

Update xUnit to latest vertion (VS test discovery perf boost)

---

src/ClientGenerator/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets

When `CodeGeneratorEnabled` is `true`, we also include `OutputFile` as a `<Compile>` item, so this just makes sure that it's always included as long as it exists.
Result is that users can navigate to generated code in Visual Studio and presumably other IDEs.

Re-enable intellisense for generated code

---

src/OrleansProviders/Streams/Common/Monitors/PeriodicAction.cs
src/OrleansProviders/Streams/Common/PooledCache/ChronologicalEvictionStrategy.cs
src/OrleansProviders/Streams/Common/PooledCache/ObjectPool.cs
src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
src/OrleansProviders/Streams/Common/RecoverableStreamProviderSettings.cs
src/OrleansProviders/Streams/Generator/GeneratorPooledCache.cs
src/OrleansProviders/Streams/Memory/MemoryPooledCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubCacheEvictionStrategy.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubQueueCache.cs
test/ServiceBus.Tests/EvictionStrategyTests/EHPurgeLogicTests.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs

Problems:
- Monitoring for message caches used timers which were not being cleaned up when caches were no longer in use.  This lead to duplicate monitoring calls on disposed caches.
- Caches not disposed, but not active, continue to periodically log state metrics.
Fix
- Clean up caches correctly on receiver shutdown and reinitialize (due to failure).
- No longer rely on timers to log periodically, instead allow activity to drive periotic metrics logging.  This removes the need to dispose of timers, and eliminates state metrics from inactive caches.

Fixed duplicate stream message cache monitoring bug.

---

src/OrleansProviders/Streams/Common/PooledCache/CachedMessagePool.cs

Problem:
Cached message blocks are eligible for purge when full.  Cached message pool was holding onto a block, even if full, until new messages showed up.  This meant it could be holding onto a block that had already been purged.
Fix:
Check block capacity after adding message, and get new block if full.

CachedMessageBlock disposed while in use bug fix.

---

src/Orleans/Core/Grain.cs
src/Orleans/Runtime/IGrainRuntime.cs
src/Orleans/Streams/Providers/StreamProviderManager.cs
src/OrleansRuntime/Core/GrainRuntime.cs
src/OrleansRuntime/Hosting/DefaultSiloServices.cs
src/OrleansRuntime/Silo/Silo.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs
test/TestInternalGrains/StreamingGrain.cs

`IStreamProviderManager` is depending on too many elements, so we don't want to pull it into Abstraction.
The modification proposed here is to use `IKeyedServiceCollection , like it is done for the `StorageProviderManager`.

Implement IKeyedServiceCollection in StreamProviderManager and remove it from GrainRuntime

---

test/ServiceBus.Tests/TestStreamProviders/EHStreamProviderWithCreatedCacheList.cs

Cache is single threaded and adapter factory execute command is not performed in a protected context (perhaps it should be..?) so logic needs to be thread safe.  Cache read is now thread safe because we cache the pressure conclusion and cache list container is now thread safe.
_Note:  Was not able to reproduce the problem, so cannot verify that this addresses it.  Fix is based off of speculation._

Fixed null ref exception in EHSlowConsuming_ShouldFavorSlowConsumer test

---

src/Orleans/Core/Grain.cs
src/Orleans/Runtime/IGrainRuntime.cs
src/OrleansRuntime/Core/GrainRuntime.cs

Move logic to construct the storage bridge in the `GrainRuntime` to remove some dependencies in `Grain<T>`.
I chose to use `GrainRuntime` since it was already there. But if the opposition is strong, I could introduce a new factory for that.

[Abstractions] Remove dependency of IStorageProvider in Grain<T>

---

src/Orleans.Runtime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Add logging to report pulling agent readFromQueue Failure
Also readFromQueue automatically retry 6 times before breaking out the loop, instead of infinite times.

Add logging to report pulling agent readFromQueue Failure

---

src/Orleans.Core.Abstractions/Core/IStorage.cs
src/Orleans.Core/Core/StateStorageBridge.cs
src/Orleans.Transactions/Abstractions/INamedTransactionalStateStorageFactory.cs
src/Orleans.Transactions/Abstractions/ITransactionalStateStorage.cs
src/Orleans.Transactions/Abstractions/ITransactionalStateStorageFactory.cs
src/Orleans.Transactions/Hosting/SiloBuilderExtensions.cs
src/Orleans.Transactions/Properties/AssemblyInfo.cs
src/Orleans.Transactions/State/NamedTransactionalStateStorageFactory.cs
src/Orleans.Transactions/State/TransactionalState.cs
src/Orleans.Transactions/State/TransactionalStateStorageProviderWrapper.cs
test/Orleans.Transactions.Tests/Grains/SingleStateTransactionalGrain.cs
test/Orleans.Transactions.Tests/Grains/TransactionOrchestrationGrain.cs

Added a storage abstraction tuned towards the transaction state transactional resource.
If a storage specific or application specific implementation is not provided, the transactional state storage will default to using storage providers.

Transactional state storage abstraction

---

test/TesterInternal/GeoClusterTests/GlobalSingleInstanceClusterTests.cs

All_Small test is time sensitive, timeout raised for the conflict resolution part to make it pass on VSO

All_Small non-deterministic test failure fix

---

Directory.Build.targets
Orleans.sln

Since we now allow grain projects to only reference Core.Abstractions (https://github.com/dotnet/orleans/pull/3548), the codegenator is not always pre-built be the time we want to run codegen on the project.
This fixes the failure we are sometimes seeing in CI of this nature:
```
error MSB3073: The command ""D:\j\workspace\functional_pr---83d31c72\Bootstrap/Release/Orleans.CodeGeneration.Build.exe" "@obj\Release\net461\win10-x64\codegen\TestGrainInterfaces.orleans.g.args.txt"" exited with code 9009. [D:\j\workspace\functional_pr---83d31c72\test\TestGrainInterfaces\TestGrainInterfaces.csproj]
```

Add build dependency to Orleans.CodeGeneration.Build.Bootstrap for codegen-enabled projects

---

src/Orleans.Runtime/Core/Dispatcher.cs
test/TesterInternal/DeadlockDetectionTests.cs

The exception didn't have its `CallChain` property populated, causing some functionals to fail.
Changed test code to use `ThrowsAsync<T>` since we want to ensure that the test does throw.

Fix deadlock exception + tweak tests

---

src/Orleans.Membership.ServiceFabric/OrleansCommunicationListener.cs
src/Orleans.Membership.ServiceFabric/Utilities/ISiloHost.cs
src/Orleans.Membership.ServiceFabric/Utilities/SiloHostWrapper.cs
src/Orleans.Runtime/Silo/SiloHost.cs

This is my suggestion to fix two things
1) Service Fabric CloseAsync expects us to wait async for shutdown so we don't block. I added async shutdown code paths, using a thread to do the actual shutdown, and waiting for the terminated wait event to fire. I picked thread here because that's what the other, existing event triggered background shutdown seemed to be doing as well.
2) Service Fabric integration should in my opinion call shutdown instead of stop on the silo, so that OnDeactivateAsync for grains gets called when SF moves/scales/messes with the silo service in general.

Service Fabric: Async shutdown support for CloseAsync

---

Directory.Build.props
src/Directory.Build.props
src/Directory.Build.targets

This PR enables the [SourceLink](https://github.com/ctaggart/SourceLink) feature or Portable PDBs, which enables the debugging of Orleans code from consumed NuGet packages.
A blog about source link debugging configuration for AspNetCore 2.0 can be found [here](https://www.stevejgordon.co.uk/debugging-asp-net-core-2-source).

Add SourceLink support for easier debugging of nuget packages

---

src/Orleans.Membership.ServiceFabric/FabricMembershipOracle.cs
src/Orleans.Membership.ServiceFabric/FabricServiceSiloResolver.cs
src/Orleans.Membership.ServiceFabric/IFabricServiceSiloResolver.cs
src/Orleans.Membership.ServiceFabric/OrleansCommunicationListener.cs
src/Orleans.Membership.ServiceFabric/OrleansServiceFabricExtensions.cs
src/Orleans.Membership.ServiceFabric/ServiceFabricMembershipOptions.cs
src/Orleans.Membership.ServiceFabric/UnknownSiloMonitor.cs
src/Orleans.Membership.ServiceFabric/Utilities/ErrorCode.cs
src/Orleans.Membership.ServiceFabric/Utilities/FabricQueryManager.cs
test/TestServiceFabric/FabricMembershipOracleTests.cs
test/TestServiceFabric/TestOutputLogger.cs
test/TestServiceFabric/UnknownSiloMonitorTests.cs

Unlike other membership providers, the Service Fabric provider does not record a total set of all silos which ever attempted to join a cluster. Because of this, there are cases where a silo might query the membership oracle for silos which were never before seen by the oracle.
This PR adds an `UnknownSiloMonitor` which attempts to alleviate issues which arise because of this. It records queries for the status of unknown silos and tracks those silos until:
* The silo is determined to be alive by a membership update
* The silos is determined to be dead because:
* A silo with the same IP:Port exists with a later generation
* A silo with the same IP (but different port) exists with a later generation in a singleton partition (max 1 silo per IP) **Note: this won't work on development clusters …

Service Fabric: ensure all silos reach a terminal state.

---

Directory.Build.props

Microsoft Symbol Servers does not support Portable PDBs yet, but Source Link supports Windows PDBs, so to get the full debugging experience straight from consumed NuGet packages we're changing to this format.
Since the Source Link support on other platform IDEs are not in a good shape, we'll not affect the xplat developer's in a bad way.
Once Microsoft Symbol Servers will support Portable PDBs we'll move back to it.

Change symbol type to full from the default portable

---

Directory.Build.props
Directory.Build.targets

The git hash logic variable set logic was taken from: https://github.com/dotnet/roslyn/blob/master/build/Targets/Versions.props#L56

Add commit hash generation to assemblies

---

src/Orleans.Core.Abstractions/Streams/Predicates/RegexStreamNamespacePredicate.cs
src/Orleans.Core/Logging/FileLogger.cs
src/Orleans.EventSourcing/JournaledGrain.cs
src/Orleans.Logging.Legacy/EventBulkingLoggerProvider.cs
src/Orleans.Logging.Legacy/LegacyOrleansLogger.cs
src/Orleans.Membership.Consul/LegacyConsulMembershipConfigurator.cs
src/Orleans.Membership.ZooKeeper/LegacyZooKeeperMembershipConfigurator.cs
src/Orleans.Streaming.EventHubs/Providers/EventDataGeneratorStreamProvider/EventHubPartitionDataGenerator.cs
src/Orleans.Streaming.EventHubs/Providers/EventDataGeneratorStreamProvider/EventHubPartitionGeneratorReceiver.cs
src/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansAWSUtils/Membership/LegacyDynamoDBMembershipConfigurator.cs
src/OrleansAzureUtils/Storage/LegacyAzureMembershipConfigurator.cs
src/OrleansProviders/Streams/Common/Monitors/DefaultBlockPoolMonitor.cs
src/OrleansProviders/Streams/Common/Monitors/DefaultCacheMonitor.cs
src/OrleansSQLUtils/Messaging/LegacySqlMembershipConfigurator.cs

It is not needed, and most of these usages are incorrect as they just refer to the type but not the correct member in that base type.

Remove cref attribute in inheritdoc comments

---

src/Orleans.Core/ApplicationParts/ApplicationPartManagerExtensions.cs
src/Orleans.Runtime/Hosting/SiloBuilderApplicationPartExtensions.cs

- AddApplicationPartsFromReferences was not adding the specified assembly as a part, but it should, so it's doing that now.
- Fix extension method to target ISiloHostBuilder

AddApplicationPartsFromReferences includes the specified assembly

---

src/Orleans.Client/Orleans.Client.csproj
src/Orleans.PowerShell/Orleans.PowerShell.csproj
src/Orleans.Server/Orleans.Server.csproj

Since there is no runtime code generation happening now, we are not building the Orleans.CodeGenerator nuget package and there is no need to reference that outside of the build time codegenerator.

Remove unused Orleans.CodeGenerator project references

---

src/Orleans.Core/Async/TaskExtensions.cs
src/Orleans.Core/CodeGeneration/GenericMethodInvoker.cs
src/Orleans.Core/Runtime/GrainReferenceRuntime.cs

This is a follow-on from #3559 which I almost forgot about. I didn't include these changes in that PR to keep things simple.
Box & Unbox are unintuitive names and OrleansTaskExtensions could use a little cleanup.
Low pri

Rename Box/Unbox to ToUntypedTask/ToTypedTask & cleanup OrleansTaskExtensions

---

test/TestGrains/RequestContextTestGrain.cs
test/TesterInternal/General/RequestContextTest.cs

RequestContextTests_Silo.RequestContext_LegacyActivityId_Simple seems to be failing intermittently.  It's unclear if the issue is on the client or silo side.  This PR adds more checks to the test to help identify root cause, as the issue does not reproduce locally.

Added more checks to RequestContext_LegacyActivityId_Simple

---

src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets

This change fixes an issue when AspNet.Core Mvc is used in a project together with Orleans Build time code generation.
GetDotNetHost task name is conflicted with their GetDotNetHost task.
[Here](https://github.com/aspnet/MvcPrecompilation/blob/311c52b12efa92f46e19529f0335b8150a28ede3/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets#L33) is the conflicting line.

Fix used task name in targets file

---

src/OrleansAzureUtils/Hosting/AzureSilo.cs
src/OrleansAzureUtils/MultiClusterNetwork/AzureTableBasedGossipChannel.cs
src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
src/OrleansAzureUtils/Storage/AzureQueueDataManager.cs
src/OrleansAzureUtils/Storage/AzureStorageUtils.cs
src/OrleansAzureUtils/Storage/AzureTableDataManager.cs
src/OrleansAzureUtils/Storage/RemindersTableManager.cs
test/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureTableStore.cs
test/TesterAzureUtils/Persistence/PersistenceProviderTests.cs

Remove internal usage of Logger in AzureUtils.
There's still usage of Logger in public methods, which is non-trivia. We talked about marking them as obsolete or move them to a legacy package. This can be addressed in another PR.

Remove internal usage of Logger in AzureUtils

---

Directory.Build.props
changelog.md
netci.groovy

- Move note about SourceLink to beta1
- When building locally, use `dev` version suffix

Changelog update and small build cleanup

---

src/index.md

Remove references to 'actors' from index page, so that it only talks about grains. This is to address one of the concerns expressed in #3608.

Remove references to 'actors' from index page

---

src/Orleans.Core/Logging/LoggerWrapper.cs
src/OrleansAWSUtils/Storage/Provider/DynamoDBStorageProvider.cs
src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
test/AWSUtils.Tests/StorageTests/PersistenceGrainTests_AWSDynamoDBStore.cs

braindead PR to remove internal usage of Orleans.Runtime.Logger from AwsUtils, except for usage of Logger in `IStorageProvider` interface, which can be addressed in another PR.

Remove internal usage of Logger from AWsUtils

---

src/Orleans.Core/Async/UnobservedExceptionsHandler.cs
src/Orleans.Core/Configuration/ApplicationConfiguration.cs
src/Orleans.Core/Core/ClientBuilder.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Silo/Silo.cs
src/Orleans.Runtime/Silo/SiloHost.cs
src/Orleans.Runtime/Utilities/SiloUnobservedExceptionsHandler.cs
src/Orleans.Runtime/Utilities/UnobservedExceptionsHandler.cs

PR for issue #3293 . 
This PR makes interception of unhandled exceptions non-static, as well as it doesn't listen to unobserved task exceptions in the client library (as the client is not a hosting runtime).
Still may need another PR to make interception of unhandled exceptions completely optional on the Silo too, if that's desired.

Remove static UnobservedExceptionsHandlerClass and detach from client library

---

src/Orleans.Core/Serialization/BinaryFormatterSerializer.cs
src/Orleans.Core/Serialization/IExternalSerializer.cs
src/Orleans.Core/Serialization/ILBasedSerializer.cs
src/Orleans.Core/Serialization/OrleansJsonSerializer.cs
src/Orleans.Core/Serialization/SerializationManager.cs
src/Orleans.Serialization.Bond/BondSerializer.cs
src/Orleans.Serialization.Protobuf/ProtobufSerializer.cs
src/OrleansSQLUtils/Storage/Provider/AdoNetStorageProvider.cs
src/OrleansSQLUtils/Storage/SqlStatisticsPublisher.cs
test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs
test/NonSilo.Tests/SerializationTests/ConfigurationTests/SerializationProviderTests.cs
test/TestExtensions/SerializationTestEnvironment.cs
test/TestGrains/MessageSerializationGrain.cs
test/TestInternalGrains/SerializationTestTypes.cs
test/Tester/FakeSerializer.cs

- Remove internal usage of Logger in extension projects
- Remove `Initialize(Logger logger)` method from `IExternalSerializer` interface

Remove internal usage of Logger in extension projects and remove Initialize(Logger) from IExternalSerializer

---

src/Orleans.CodeGeneration.Build/AssemblyResolver.cs
src/Orleans.CodeGeneration.Build/CodeGenerator.cs
src/Orleans.CodeGeneration/SerializerGenerator.cs
src/Orleans.Core/CodeGeneration/TypeUtils.cs

Enhance the error message we produce in case of an assembly loading error in a call to GetDefinedTypes. Fixes #3619

Enhance error handling on GetDefinedTypes

---

src/Orleans.CodeGeneration/Utilities/StringExtensions.cs
test/TestGrains/MultipleGenericParameterInterfaceImpl.cs

While Roslyn may generate some types that their names may contain ','.
For example, when implement an interface which has more than one generic parameters and the method is async.
When orleans codegen generating code, it produces some code like:
```c#
feature.AddKnownType("UnitTests.Grains.AFactory+<UnitTests-Grains-IFactory<System-Int32\,System-Double>-Product>d__0,TestGrains", "UnitTests.Grains.<UnitTests-Grains-IFactory<System-Int32\,System-Double>-Product>d__0");
```
The `\,` in the string literals will cause compiler errors. (unrecognized escape sequence)
Convert them to verbatim string literals will solve the issue.
```c#
feature.AddKnownType(@"UnitTests.Grains.AFactory+<UnitTests-Grains-IFactory<System-Int32\,System-Double>-Product>d__0,TestGrains", …
```

Fixing codegen when a type's name contains comma

---

src/Orleans.CodeGeneration/RoslynCodeGenerator.cs
test/TestGrains/MultipleGenericParameterInterfaceImpl.cs

Follow-on from #3639.
These classes either can't or shouldn't be referenced, so we should not generate code referring to them.

CodeGen: do not generate KnownTypes for nested private or compiler-generated classes

---

Directory.Build.props
src/Orleans.Core.Abstractions/Serialization/FieldUtils.cs
test/DefaultCluster.Tests/DefaultCluster.Tests.csproj
test/DefaultCluster.Tests/SerializationTests/SerializationTests.cs

Fixes #2979
Associates DynamicMethods for private field getters & setters with the (non-strong-named) Orleans assembly instead of the (possibly strong-named) assembly containing the type or the field type.
From [these docs](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/security-issues-in-reflection-emit), under the *Dynamic Methods Associated with Existing Assemblies*  section:
> In addition, you can use a constructor that specifies the ability to skip the visibility checks of the JIT compiler. **Doing so gives your dynamic method access to all types and members in all assemblies, regardless of access level.**
So we're associating the `DynamicMethod` with the module emitting it and specifying that visibility checks should be skipped.

Fix serialization of fields types from strong named assemblies

---

src/Orleans.Core/Serialization/TypeUtilities.cs
test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs

Addresses https://github.com/dotnet/orleans/issues/3640/
Change is to consider exceptions (immutable objects) as shallow copyable types.

Make Exceptions shallow copyable

---

src/Orleans.Core/Utils/PeriodicAction.cs
src/Orleans.Runtime/Transactions/TransactionAgent.cs

Add metrics to monitor transaction agent batch TM calls
Metric monitor configured through NodeConfig.StatisticsMetricsTableWriteInterval as reporting frequency

Add metrics to monitor transaction agent batch calls

---

src/Orleans.CodeGeneration.Build/CodeGenOptions.cs
src/Orleans.CodeGeneration.Build/CodeGenerator.cs
src/Orleans.CodeGeneration.Build/Program.cs
src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets

Adds a property which can be set in user's .csproj files to configure the log level of the build-time code generator. Log levels are defined in the `LogLevel` enum from `Microsoft.Extensions.Logging`. If the user specifies an invalid log level, they'll see a message like this in the build log: `error : "Trakjjkjkce" is not a valid log level. Valid values are Trace, Debug, Information, Warning, Error, Critical, None` and the build will fail. Default level is `Warning`.
Example, to set log to `Trace`.
```xml
<PropertyGroup>
<OrleansCodeGenLogLevel>Trace</OrleansCodeGenLogLevel>
</PropertyGroup>
```

CodeGen: Allow per-project log level configuration

---

src/Orleans.Core.Abstractions/Lifecycle/IGrainLifecycle.cs
src/Orleans.Core.Abstractions/Runtime/GrainLifecycleStage.cs
src/Orleans.Core/Lifecycle/LifecycleObservable.cs
src/Orleans.Runtime/Catalog/ActivationData.cs
src/Orleans.Runtime/Catalog/GrainLifecycle.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Hosting/Generic/SiloWrapper.cs
src/Orleans.Runtime/Lifecycle/ISiloLifecycle.cs
src/Orleans.Runtime/Lifecycle/SiloLifecycle.cs
src/Orleans.Runtime/Lifecycle/SiloLifecycleExtensions.cs
src/Orleans.Runtime/Lifecycle/SiloLifecycleStage.cs
src/Orleans.Runtime/Silo/Silo.cs

Added staged startup of silo via Lifecycle.
This work is still primitive and minimal.
Stages are preliminary, and will need to be further refined.
We still need to modify components to interact direct with the lifecycle rather than requiring silo to know about and start all components.  Only component modified so far, for proof of concept purposes, is the InsideRuntimeClient.  These changes can be made in future passes.

Minimal silo lifecycle

---

test/Benchmarks/BenchmarkGrainInterfaces/Ping/ILoadGrain.cs
test/Benchmarks/BenchmarkGrainInterfaces/Ping/IPingGrain.cs
test/Benchmarks/BenchmarkGrains/Ping/LoadGrain.cs
test/Benchmarks/BenchmarkGrains/Ping/PingGrain.cs
test/Benchmarks/Benchmarks/Ping/PingBenchmark.cs
test/Benchmarks/Benchmarks/Program.cs

Simple 2 silo ping benchmark.
Useful for prototyping optimizations of Orleans actor framework.

Ping Benchmark

---

src/Orleans.Core.Abstractions/Core/Grain.cs

When unit testing a grain that uses streams a NullReferenceException will occur as the IActivationData on the grain will be null. This appears to be introduced with 2.0 beta 1. 
I have put a null check on the Grain IActivationData so that under unit testing scenarios it will defer to the injected IGrainRuntime to get a ServiceProvider.

fix null reference exception when unit testing grains that use streams

---

src/Orleans.Core/Hosting/Options/ConfigureNamedOptions.cs
src/Orleans.Core/Hosting/Options/OptionsBuilder.cs
src/Orleans.Core/Hosting/Options/PostConfigureOptions.cs
src/Orleans.Runtime/Hosting/LegacyClusterConfigurationExtensions.cs

Replace our custom `ServiceBasedConfigurator` with a copy of Microsoft.Extensions.Options extension methods to fulfill the same goal. We can remove our copy once 2.1 of Options ship.
The copied code comes from this PR: https://github.com/aspnet/Options/pull/239
This addition will be even more useful in upcoming changes where I need to bring 2 dependencies instead of 1, so `ServiceBasedConfigurator` is not enough as it is.

Include OptionsBuilder.Configure<TDep> extension methods

---

src/Orleans.Core.Abstractions/Core/Grain.cs

I guess `ArgumentNullException` is more suitable exception instead of `NullReferenceException` for case when developer does mistake and call Grain methods by passing null

Add ArgumentNullException in Grain

---

src/Orleans.Core/Configuration/ClusterConfiguration.cs
src/Orleans.Core/Configuration/NodeConfiguration.cs
src/Orleans.Runtime/Silo/SiloInitializationParameters.cs

The information was set only when initially building the node, but not updated if the Endpoint changed. This way it could be stale (and it was in many cases) by the time the silo starts

Initialize primary node and seed information when the silo is about to start

---

Samples/AzureWebSample/OrleansAzureSilos/WorkerRole.cs
Samples/GPSTracker/GPSTracker.Web/WebRole.cs
Samples/HelloGeoSample/Orleans.Silos/WorkerRole.cs
Samples/ReplicatedChatGrainSample/Orleans.Silos/WorkerRole.cs
Samples/ReplicatedEventSample/Orleans.Silos/WorkerRole.cs
Samples/TicTacToe/OrleansXO.WorkerRole/WorkerRole.cs

- remove misleading code in samples to configure ServicePointManager
- [ServicePointManager.DefaultConnectionLimit gets set in Silo initialization](https://github.com/dotnet/orleans/blob/1591fd13a2868336bd111d01251f20aba503dbf3/src/Orleans.Runtime/Silo/Silo.cs#L657) with value from
ClusterConfiguration.Defaults.DefaultConnectionLimit (defaults to 200)

Improve samples: remove misleading code to configure ServicePointManager

---

src/Orleans.Core/Messaging/SocketManager.cs
src/Orleans.Runtime/Messaging/IncomingMessageAcceptor.cs
test/Tester/ClientConnectionTests/StallConnectionTests.cs

First fix for #3715 
Basically reusing the connection timeout value from the configuration in the Socket configuration for synchronous call to `Socket.Receive` (when waiting connections preamble).
This do not interfere with the asynchronous receive that we do thereafter : https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.receivetimeout(v=vs.110).aspx
> **Remarks**
> This option applies to synchronous Receive calls only

Set a timeout value for the synchronous socket read operations

---

src/Orleans.Core/Messaging/GatewayClientReceiver.cs
src/Orleans.Core/Messaging/GatewayConnection.cs
src/Orleans.Core/Messaging/IOutgoingMessage.cs
src/Orleans.Core/Messaging/Message.cs
src/Orleans.Core/Runtime/AsynchAgent.cs
src/Orleans.Core/Runtime/AsynchQueueAgent.cs
src/Orleans.Core/Runtime/ExecutorService.cs
src/Orleans.Core/Runtime/QueuedExecutor.cs
src/Orleans.Core/Runtime/SingleTaskAsynchAgent.cs
src/Orleans.Core/Runtime/ThreadPerTaskExecutor.cs
src/Orleans.Runtime/GrainDirectory/AdaptiveDirectoryCacheMaintainer.cs
src/Orleans.Runtime/GrainDirectory/MultiClusterRegistration/GlobalSingleInstanceActivationMaintainer.cs
src/Orleans.Runtime/Messaging/Gateway.cs
src/Orleans.Runtime/Messaging/IncomingMessageAcceptor.cs
src/Orleans.Runtime/Messaging/IncomingMessageAgent.cs
src/Orleans.Runtime/Scheduler/WorkerPoolThread.cs
src/Orleans.Runtime/Silo/Watchdog.cs
test/NonSilo.Tests/AsynchAgentRestartTest.cs

Continuation of https://github.com/dotnet/orleans/pull/3663
- Introduced `IExecutor` interface with work queuing API compatible to .NET `ThreadPool`.
-  `ExecutorService` now returns suitable executors based on stage type. In future  `ExecutionPlan` could be introduced, allowing fine grained control over executor - stage assignment.
- Moved queuing logic (blocking collection, its processing loop and statistics gathering) from `AsynchQueueAgent` into newly created `QueuedExecutor`. It resulted in separation of descendants of `AsynchAgent` and `AsynchQueueAgent`, as the former one schedules single long running work on start, while the latter - multiple short running tasks during execution. Stages with single task were made inheritors of  new `SingleTaskAsynchAgent` which contains extracted …

Move queuing logic from AsynchQueueAgent into Executor

---

src/Orleans.Core/Configuration/OrleansConfiguration.xsd

- [It's possible to specify `MaxSocketAge`](https://github.com/dotnet/orleans/blob/2c8e524a23d0f97fdb4476cab4716f70bac04270/src/Orleans.Core/Configuration/MessagingConfiguration.cs#L222-L226) in the `Messaging` element of `OrleansConfiguration.xml`. However this was missing from the xsd file. This PR just adds that element and [it's documentation](https://github.com/dotnet/orleans/blob/2c8e524a23d0f97fdb4476cab4716f70bac04270/src/Orleans.Core/Configuration/MessagingConfiguration.cs#L33-L36) to the xsd file.
- Using something like `<Messaging MaxSocketAge="230s"/>` in `Globals` in `OrleansConfiguration.xml` might be a way to workaround a problem of a router or firewall dropping an Orleans TCP connection without notification (no RST is sent and the connection just hangs around, Azure …

Add MaxSocketAge to OrleansConfiguration.xsd

---

src/Orleans.Runtime/Core/Dispatcher.cs
src/Orleans.Runtime/Messaging/IncomingMessageAgent.cs
src/Orleans.Runtime/Scheduler/ClosureWorkItem.cs
src/Orleans.Runtime/Scheduler/SchedulerExtensions.cs
src/Orleans.Runtime/Scheduler/WorkItemBase.cs

By creating a couple of specialised versions of `ClosureWorkItem` to handle specific usages, we can reduce allocations by around 1 or 2 per invocation.
* Change the name property from a `Func<string>` to a `string` to avoid allocating a closure.
* Introduce `AsyncClosureWorkItem` for simple `Func<Task>` cases.
* Introduce `AsyncClosureWorkItem<T>` for `Func<Task<T>>` cases.

Reduce allocations in usages of ClosureWorkItem

---

test/TestServiceFabric/FabricMembershipOracleTests.cs
test/TesterInternal/GeoClusterTests/TestingClusterHost.cs

Previously it was inferred only if ClusterId was set. Now ClusterId is always set (as it was collapsed with DeploymentId), so there is an explicit setting for multi-cluster.

Re-enable multi-cluster setting in tests that require it

---

src/Orleans.Core/Messaging/GatewayConnection.cs
src/Orleans.Core/Messaging/ProxiedMessageCenter.cs
src/Orleans.Core/Runtime/AsynchAgent.cs
src/Orleans.Core/Runtime/AsynchQueueAgent.cs

After merge of https://github.com/dotnet/orleans/pull/3683 the null reference exceptions started to appear in `ProxiedMessageCenter.SendMessage` method. ([test fail 1](
https://ci.dot.net/job/dotnet_orleans/job/master/job/functional_prtest/654/consoleFull), [test fail 2](https://ci.dot.net/job/dotnet_orleans/job/master/job/functional_prtest/664/consoleFull )) 
Their cause seems to be in race condition between [adding](https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Messaging/ProxiedMessageCenter.cs#L194) of just created `GatewayConnection` (which is `AsynchQueueAgent`) to the list of connections, and [it's start](https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Messaging/ProxiedMessageCenter.cs#L273) , thus dictionary contains not ready to use connection for …

Fix null reference exceptions on not started AsynchQueueAgent usage attempt

---

src/Orleans.Runtime/Core/InsideRuntimeClient.cs

Clear transaction context in top level transaction to prevent context from being passed back to the caller.
Context returned to the caller created a dependency on the transaction assembly for Orleans clients.  That assembly should be silo only.

Clear transaction context in top level transaction

---

src/Orleans.Core/Runtime/AsynchAgent.cs

Continuation of https://github.com/dotnet/orleans/pull/3732. 
Remaining exception https://github.com/dotnet/orleans/pull/3732#issuecomment-349162519 most likely is caused by attempt to access  `AsynchAgent` after it's disposing. But before fixing it should be confirmed.  With this change `ObjectDisposedException` should be thrown instead of `NullReferenceException`.

Add throw on disposed AsynchAgent usage attempt

---

src/Orleans.Runtime/Messaging/IncomingMessageAgent.cs

We use limits to avoid overloading individual activations.
When these limits are hit, messages are immediately rejected instead of enqueuing them for processing.
We should avoid dropping `Response` messages since activations usually await responses before continuing to process other messages. Therefore, dropping a response may cause an activation to block processing until its timeout is reached, causing cascading timeouts for its callers.

Avoid overload checks for response messages

---

src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
test/DefaultCluster.Tests/ObserverTests.cs

Ref #3744
Cleans up a minor potential API usage error.

CreateObjectReference: disallow creating a reference to a Grain class

---

src/Orleans.Core/Logging/ErrorCodes.cs
src/Orleans.Core/Messaging/GatewayManager.cs

When a client runs out of gateways (all are marked as dead), we can force-retry all gateways which were previously marked as dead.
Hopefully this would improve reconnect times in development/on-prem scenarios in cases where a cluster reboot is not coordinated, especially in single silo scenarios.
Low pri

Expedite gateway retries when gateway list is exhausted

---

src/ClientGenerator/AssemblyResolver.cs
src/ClientGenerator/ClientGenerator.cs
src/ClientGenerator/ClientGenerator.csproj
src/ClientGenerator/project.json
src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.Build.nuspec
src/Orleans.SDK.targets

Backported codegen fixes to 1.5.x branch.
Supports resolving assemblies using `*.deps.json` file.
This includes some divergences from the current master, notably:
* We ensure the deps is generated via `AfterTargets="GenerateBuildDependencyFile"`
* We copy the generated deps file to sit next to the intermediate assembly, since I couldn't see any other way to make MSBuild emit the deps file to that location (not without triggering the target manually).

CodeGen: support builds which use reference assemblies

---

src/Documentation/2.0/Codegen.md

Simple docs on codegen in 2.0, mostly about how it differs from 1.5 and the user's options.

Docs: Code Generation in Orleans 2.0

---

src/Orleans.CodeGeneration/SerializerGenerationManager.cs
src/Orleans.Core/Serialization/BinaryFormatterISerializableSerializer.cs
src/Orleans.Core/Serialization/DotNetSerializableUtilities.cs
src/Orleans.Core/Serialization/ILSerializerGenerator.cs
src/Orleans.Core/Serialization/IlDelegateBuilder.cs
test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs
test/NonSilo.Tests/Serialization/ILBasedSerializerTests.cs
test/TestFSharp/Types.fs
test/Tester/SerializationTests/DeepCopyTests.cs
test/Tester/SerializationTests/SerializationTests.FSharpTypes.cs

Fixes #3650
Adds support for serialization hooks in `ILBasedSerializer` and avoids generating C#-based serializers for types which use serialization hooks such as `[OnDeserializing]`, etc.
Hopefully this doesn't break anyone, but it does have the potential to break in a persistence scenario.
Note that the ILBasedSerializer will still use the default constructor or no constructor (GetUnformattedObject) and will not use the serialization constructor. Support for serialization constructors/`ISeralizable` requires a different strategy (essentially serializing object as name-value pairs). I can add code for that in a separate PR.
Fixes F# serialization.
Includes @cata's PR commit since that PR was a failing test & it's best if we can commit it alongside a fix. Thanks, @cata!

Support serialization lifecycle hooks

---

test/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureStore.cs

* Tests were failing with a serialization error.
* The error indicated that a placement strategy could not be deserialized.
* The root cause is that the strategy is not included in the ApplicationParts
Fix: include everything deployed alongside the test as an ApplicationPart

Fix Azure Storage tests

---

src/Orleans.CodeGeneration/SerializerGenerationManager.cs

Thanks to @cata for finding this.

Do not generate serializers for classes which require the use of serization hooks

---

src/Orleans.Runtime/Counters/SiloStatisticsManager.cs
src/Orleans.Runtime/Hosting/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/MultiClusterNetwork/MultiClusterOracle.cs
src/Orleans.Runtime/Silo/Silo.cs
src/Orleans.Runtime/Silo/SiloHost.cs
src/Orleans.Runtime/Silo/SiloProviderRuntime.cs

- Remove legacy initialization from Silo class.
- Remove most usages of `SiloInitializationParameters` concrete type.
This is in preparation for getting rid of the legacy configuration objects as a Core dependency

Remove legacy initialization from Silo class

---

src/Orleans.Core/Serialization/BinaryFormatterISerializableSerializer.cs
test/NetCore.Tests/ExceptionTests.cs
test/TestGrainInterfaces/IExceptionGrain.cs
test/TestGrains/ExceptionGrain.cs

Very small fix + some QoL test changes. I was unable to `dotnet xunit` the NetCore.Tests project without specifying `<RuntimeFrameworkVersion>`. It seems related to [these](https://github.com/dotnet/cli/issues/7901) [three](https://github.com/dotnet/core-setup/issues/3462) [issues](https://github.com/dotnet/core-setup/issues/3469).
Need to get NetCore.Tests running in CI - I'll experiment

Fix Exception serialization on .NET Core

---

src/Orleans.Core/Messaging/SocketManager.cs
src/Orleans.Runtime/Messaging/IncomingMessageAcceptor.cs

Related to #3621 
Two fixes here:
- First, do not try to restart the listening socket when the silo is stopping
- Second, for some reason, in Linux calling `Socket.Disconnect` on a Socket that is not connected completely blow up the process instead of just throwing an exception. So check if the socket is connected before calling this method.

Fix shutdown sequence in linuxcontainer

---

src/Orleans.Core/Configuration/Options/NetworkingOptions.cs
src/Orleans.Core/Runtime/ILocalSiloDetails.cs
src/Orleans.Hosting.ServiceFabric/OrleansCommunicationListener.cs
src/Orleans.Runtime/Counters/SiloStatisticsManager.cs
src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Hosting/EndpointOptions.cs
src/Orleans.Runtime/Hosting/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/MembershipService/DevelopmentMembershipOptions.cs
src/Orleans.Runtime/MembershipService/GrainBasedMembershipTable.cs
src/Orleans.Runtime/MembershipService/ILegacyMembershipConfigurator.cs
src/Orleans.Runtime/MembershipService/MembershipOracle.cs
src/Orleans.Runtime/MembershipService/MembershipOracleData.cs
src/Orleans.Runtime/Messaging/Gateway.cs
src/Orleans.Runtime/Messaging/GatewayAcceptor.cs
src/Orleans.Runtime/Silo/LegacyConfigurationWrapper.cs
src/Orleans.Runtime/Silo/LocalSiloDetails.cs
src/Orleans.Runtime/Silo/Silo.cs
src/Orleans.Runtime/Silo/SiloHost.cs
src/Orleans.Runtime/Silo/SiloInitializationParameters.cs
src/Orleans.Runtime/Silo/SiloOptions.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs
test/TestServiceFabric/FabricMembershipOracleTests.cs

- Add GatewayAddress to ILocalSiloDetails
- Read endpoints information from EndpointOptions
- Break dependency between LocalSiloDetails and legacy configuration (and get rid of SiloInitializationParameters)
Note to reviewers:
- I did find a few more usages of the legacy configuration to configure endpoints that can be eventually migrated to not rely on the legacy config (mainly in the ServiceFabric code), but it's not required for this PR.
- Kept separate commits to make diff simpler. Please squash anyway and keep the PR description as the commit message description (without the note to reviewers of course).

Strongly typed endpoint options

---

src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/MultiClusterRegistration/GlobalSingleInstanceActivationMaintainer.cs
src/Orleans.Runtime/GrainDirectory/MultiClusterRegistration/GlobalSingleInstanceRegistrar.cs
src/Orleans.Runtime/LogConsistency/ProtocolServices.cs
src/Orleans.Runtime/Messaging/MessageCenter.cs
src/Orleans.Runtime/MultiClusterNetwork/MultiClusterOracle.cs
src/Orleans.Runtime/Silo/LegacyConfigurationWrapper.cs
src/Orleans.Runtime/Versions/GrainVersionStore.cs
test/TestServiceFabric/OrleansCommunicationListenerTests.cs
test/TesterInternal/ActivationsLifeCycleTests/DeactivateOnIdleTests.cs

- Remove incorrect usages of `NodeConfiguration`
- Replace usages of `SiloOptions` with `ILocalSiloDetails`
First commit is the important one, which removes some incorrect usages of `NodeConfiguration.Generation`.
The other commit are some opportunistic cleanup code.

Fix wrong config usages

---

src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBGatewayListProvider.cs
src/Azure/Orleans.Clustering.AzureStorage/AzureGatewayListProvider.cs
src/Azure/Orleans.Statistics.AzureStorage/Storage/ClientMetricsTableDataManager.cs
src/Orleans.Clustering.Consul/ConsulGatewayListProvider.cs
src/Orleans.Clustering.ZooKeeper/ZooKeeperGatewayListProvider.cs
src/Orleans.Core/Configuration/Legacy/LegacyConfigurationExtensions.cs
src/Orleans.Core/Configuration/Options/ClusterClientOptions.cs
src/Orleans.Core/Core/ClientBuilderExtensions.cs
src/Orleans.Core/Statistics/ClientStatisticsManager.cs
src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
src/Orleans.Runtime/Hosting/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/Silo/SiloOptions.cs
src/OrleansSQLUtils/Messaging/SqlGatewayListProvider.cs
test/AWSUtils.Tests/MembershipTests/DynamoDBMembershipTableTest.cs
test/Consul.Tests/ConsulMembershipTableTest.cs
test/TesterAzureUtils/AzureMembershipTableTests.cs
test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs
test/TesterSQLUtils/MySqlMembershipTableTests.cs
test/TesterSQLUtils/PostgreSqlMembershipTableTests.cs
test/TesterSQLUtils/SqlServerMembershipTableTests.cs

* Add ClusterClientOptions to configure ClusterId
* Add extension methods to configure general options
Enables clientBuilder.ConfigureClusterClient(...) and hostBuilder.ConfigureOrleans(...)

Add ClusterClientOptions to configure ClusterId

---

src/Orleans.Runtime/Messaging/IncomingMessageAcceptor.cs
test/Tester/ClientConnectionTests/StallConnectionTests.cs

Second fix for #3715
Basically, start a new ignored task for reading and validating the connection just accepted on the silo.

Wrap the connection preamble read check in a task

---

src/Orleans.Core/Transactions/OrleansTransactionException.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
src/Orleans.Runtime/Transactions/TransactionAgent.cs
src/Orleans.Runtime/Transactions/TransactionInfo.cs
src/Orleans.Transactions/InClusterTM/TransactionManager.cs
src/Orleans.Transactions/State/TransactionalState.cs
test/Orleans.Transactions.Tests/Grains/TransactionOrchestrationGrain.cs
test/Orleans.Transactions.Tests/Runners/GoldenPathTransactionManagerTestRunner.cs

in preparation for the distributed TM implementation, some straightforward modifications of the application-visible exceptions:
- use string instead of long for transaction ids (since distributed TM algorithm uses Guid, not long)
- add some constructor overloads to some exceptions, so we can specify message and inner exception
- add several new exception that describe failures specific to the distributed TM algorithm

Add transaction exceptions for distributed TM

---

src/Orleans.CodeGeneration.Build/CodeGenerator.cs
src/Orleans.CodeGeneration.Build/Program.cs
src/Orleans.CodeGeneration/ApplicationPartManagerCodeGenExtensions.cs
src/Orleans.Core/Logging/ErrorCodes.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
src/Orleans.Runtime/Silo/Silo.cs
test/RuntimeCodeGen.Tests/RuntimeCodeGenTests.cs
test/Tester/OrleansLoggingTests.cs

Add processing time measure 
- silo start up
- built time code gen
- runtime code gen
AFAIK, there's only two participants on silo lifecycle now, which is silo itself, and InsideRuntimeClient. So I added processing time measure to their OnRuntimeInitializeStart and OnRuntimeServicesStart methods. 
Let me know if I missed anything on silo start up sequence

Add processing time measure on silo start up sequence and code gen

---

test/Orleans.Transactions.Tests/Runners/GoldenPathTransactionManagerTestRunner.cs

This test fails frequently, causing our nightly to fail frequently. Disable it for now so nightly would succeed and produce builds for load test

Disable frequent failing test

---

src/Orleans.Core/Logging/ErrorCodes.cs
src/Orleans.Runtime/Messaging/IncomingMessageAcceptor.cs
test/Tester/ClientConnectionTests/InvalidPreambleConnectionTests.cs

Currently it's possible to DoS Orleans by sending bytes that cause the current connection preamble handling to allocate a large buffer. This PR sets an upper bound for the buffer size.

Make buffer size bounded when reading connection preamble

---

src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Utilities/SiloUnobservedExceptionsHandler.cs

Make SiloUnObservedExceptionHandler optional, turn it off for silo by default. User can op it in by call `UseSiloUnobservedExceptionsHandler` on `ISiloHostBuilder` 
related issue #3293

Make SiloUnObservedExceptionHandler optional

---

src/Orleans.Core/AssemblyLoader/TypeMetadataCache.cs
src/Orleans.Core/Core/ApplicationPartValidator.cs
src/Orleans.Core/Core/ClientBuilder.cs
src/Orleans.Core/Core/ClientBuilderExtensions.cs
src/Orleans.Core/Core/DefaultClientServices.cs
src/Orleans.Core/Serialization/SerializationManager.cs
src/Orleans.Runtime/GrainTypeManager/GrainTypeManager.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Hosting/Generic/SiloHostBuilderExtensions.cs
src/Orleans.Runtime/Silo/Silo.cs

We were referencing application part manager directly in many places, forfeiting the advantages of the abstraction.  Only code creating the manager now references the concrete class.

Clean up abstraction of ApplicationPartsManager

---

src/Orleans.Core/Streams/Core/StreamSubscriptionManager.cs
src/Orleans.Core/Streams/PubSub/ImplicitStreamPubSub.cs
src/Orleans.Core/Streams/PubSub/ImplicitStreamSubscriberTable.cs
src/Orleans.Core/Streams/PubSub/StreamPubSubImpl.cs
test/TestGrains/ProgrammaticSubscribe/SubscribeGrain.cs
test/Tester/StreamingTests/ProgrammaticSubscribeTests/ProgrammaticSubcribeTests.cs

Fix bugs 
- #3843 
- use `StreamSubscriptionManager.RemoveSubscription` with custom `IStreamIdentity` implementation throws casting exception

Fix programatic subscribe bugs

---

src/Orleans.Core/Runtime/GrainReferenceRuntime.cs

Debug context which consists of [interface  + method names](https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Runtime/GrainReferenceRuntime.cs#L197) takes ~70 bytes of space on average. 
It's passing as part of message results in ~10% increased wire footprint. 
This change is to tests performance implications of such behavior, and in case of observable difference -  can be either merged as is, or adjusted for debug context to be computed on target silo.

Turn off default of debug context usage

---

src/Orleans.Core/Configuration/OrleansConfiguration.xsd

In doing some reading on some configuration elements I ran into a spelling error and clarified some grammar.

Corrected some spelling and clarified some grammar

---

src/Documentation/Deployment-and-Operations/Configuration-Guide/index.md

Found the XSD source was dead linking to a 404 page.  Found the correct link and corrected it.
Any chance there is a [linting tool for docs](https://github.com/markdownlint/markdownlint) that could be run as part of the build process to ensure links still work?  (The linked tool does some other cool stuff with Markdown verification, but does not appear to check links for validity!)
Anyway, this link is fixed for now. ;-)

Fixed Dead Link to XSD Source

---

src/AWS/Shared/Storage/DynamoDBStorage.cs

These need to be nullable so the parse routine can properly setup the AmazonDynamoDBClient with implicit auth.

Allow for null access/secret for EC2 provisioned credentials.

---

src/Orleans.Core/Logging/FileLogger.cs
src/Orleans.Core/Telemetry/Consumers/FileTelemetryConsumer.cs
src/Orleans.Logging.Legacy/LegacyFileLogConsumer.cs

- Make FileLogger, FileLogConsumer and FileTelemetryConusmer all use UTF8 encoding
- Remove read lock on log file so that file can be read when messages is writing to the file.

Make FileLogger, LegacyFileLogConsumer and FileTelemetryConusmer all use UTF8 encoding.

---

test/ServiceBus.Tests/Streaming/EHProgrammaticSubscribeTests.cs
test/Tester/StreamingTests/ProgrammaticSubscribeTests/ProgrammaticSubcribeTestsRunner.cs
test/TesterAzureUtils/Streaming/AQProgrammaticSubscribeTest.cs

`Dispose` method was in the wrong place. 
It should be called after all the tests finished, so it should be in its `Fixture`'s `Dispose()`, instead of in the testclass level Dispose(), which is called whenever per test finished.

Move dispose method inside fixture class

---

src/Orleans.Runtime/Core/InsideRuntimeClient.cs

Currently the `GrainTypeResolver` returned by `InsideRuntimeClient` is the local version of the `GrainInterfaceMap`. It should be the cluster version.
It seems that it is only used by `GrainReferenceRuntime` to check if the Grain call should be marked as `InvokeMethodOptions.Unordered` is  so the impact of this bug is pretty limited.

Return Cluster GrainInterfaceMap in InsideRuntimeClient

---

src/Orleans.Core/Messaging/ProxiedMessageCenter.cs
src/Orleans.Core/Runtime/GrainClassData.cs
src/Orleans.Core/Runtime/GrainInterfaceData.cs
src/Orleans.Core/Runtime/GrainInterfaceMap.cs
src/Orleans.Core/Runtime/GrainTypeResolver.cs
src/Orleans.Core/Runtime/ITypeManager.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
src/Orleans.Runtime/GrainTypeManager/GrainTypeManager.cs
src/Orleans.Runtime/GrainTypeManager/TypeManager.cs

Related issue: #3138 
I extracted the `IGrainTypeResolver` logic to another class, that will be used by the client and for grain to grain calls.
`GrainInterfaceMap` stil has the "merge" logic along with some silos only infos (placement, registration). At some point in the future I think we could merge `GrainTypeManager` and `GrainInterfaceMap`.

Streamline IGrainTypeResolver

---

src/Azure/Orleans.Statistics.AzureStorage/Storage/ClientMetricsTableDataManager.cs
src/Azure/Orleans.Statistics.AzureStorage/Storage/SiloMetricsTableDataManager.cs
src/Orleans.Core.Abstractions/Statistics/IAppEnvironmentStatistics.cs
src/Orleans.Core.Abstractions/Statistics/IHostEnvironmentStatistics.cs
src/Orleans.Core/Core/DefaultClientServices.cs
src/Orleans.Core/Shims/RuntimeStatisticsGroup.cs
src/Orleans.Core/Statistics/AppEnvironmentStatistics.cs
src/Orleans.Core/Statistics/ClientStatisticsManager.cs
src/Orleans.Core/Statistics/ClientTableStatistics.cs
src/Orleans.Core/Statistics/IPerformanceMetrics.cs
src/Orleans.Runtime/Counters/SiloPerformanceMetrics.cs
src/Orleans.Runtime/Counters/SiloStatisticsManager.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.TelemetryConsumers.Counters/Orleans.TelemetryConsumers.Counters.csproj
src/Orleans.TelemetryConsumers.Counters/Statistics/HostBuilderExtensions.cs
src/Orleans.TelemetryConsumers.Counters/Statistics/PerfCounterEnvironmentStatistics.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerBasicTests.cs
test/TesterSQLUtils/SqlStatisticsPublisherTests/DummyPerformanceMetrics.cs

Related issues: #3567 #3586
I added abstractions to get the total physical memory and the cpu/memory usage (`IAppEnvironmentStatistics` and `IHostEnvironmentStatistics`), and refactored the old `PerfCounterEnvironmentStatistics` to implement `IAppEnvironmentStatistics`, as a Windows-only solution. This class also now follow the lifecycle pattern.
The built-in implementation of  `IAppEnvironmentStatistics` should be cross-platform, but the developer can make a custom implementation if needed.
A Linux-specific implementation of `IHostEnvironmentStatistics` could be done in the future,

Bring back PerfCounterEnvironmentStatistics 

---

src/Orleans.Runtime/Silo/SiloHost.cs
src/Orleans.Transactions/InClusterTM/ActiveTransactionsTracker.cs
test/TesterInternal/GeoClusterTests/GlobalSingleInstanceClusterTests.cs

Docs on Foreground vs Background threads: https://docs.microsoft.com/en-us/dotnet/standard/threading/foreground-and-background-threads : 
> A managed thread is either a background thread or a foreground thread. Background threads are identical to foreground threads with one exception: a background thread does not keep the managed execution environment running. Once all foreground threads have been stopped in a managed process (where the .exe file is a managed assembly), the system stops all background threads and shuts down. 
> If you use a thread to monitor an activity, such as a socket connection, set its IsBackground property to true so that the thread does not prevent your process from terminating. 
I believe that it's good hygiene for us to ensure that all of our threads are created …

Mark all created threads as background & name all threads

---

src/Orleans.Core.Abstractions/Lifecycle/LifecycleExtensions.cs
src/Orleans.Core/Configuration/Legacy/LegacyConfigurationExtensions.cs
src/Orleans.Core/Configuration/OptionLogger/IOptionFormatter.cs
src/Orleans.Core/Configuration/OptionLogger/IOptionsLogger.cs
src/Orleans.Core/Configuration/OptionLogger/OptionFormatterExtensionMethods.cs
src/Orleans.Core/Configuration/Options/ClientMessagingOptions.cs
src/Orleans.Core/Configuration/Options/ClusterClientOptions.cs
src/Orleans.Core/Configuration/Options/MessagingOptions.cs
src/Orleans.Core/Configuration/Options/MultiClusterOptions.cs
src/Orleans.Core/Configuration/Options/NetworkingOptions.cs
src/Orleans.Core/Configuration/Options/SerializationProviderOptions.cs
src/Orleans.Core/Configuration/Options/SiloMessagingOptions.cs
src/Orleans.Core/Configuration/Options/StaticGatewayListProviderOptions.cs
src/Orleans.Core/Configuration/Options/StatisticsOptions.cs
src/Orleans.Core/Configuration/ServiceCollectionExtensions.cs
src/Orleans.Core/Core/ClientBuilderExtensions.cs
src/Orleans.Core/Core/DefaultClientServices.cs
src/Orleans.Core/Hosting/Options/OptionsServiceCollectionExtensions.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Hosting/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/Lifecycle/SiloLifecycleStage.cs
src/Orleans.Runtime/OptionsLogger/OptionsLogger.cs
test/Tester/LogFomatterTests.cs

- Add IOptionFormatter and IOptionResolver interfaces
- Add extension methods to provide better usability to configure option and option formatter together 
- Added option formatter for some options as a starting point
Didn't end up adding interface `IOptionsLogger` for two reasons
- not many people will be interested in writing their own IOptionsLogger, we should be wary to add an public interface which no user expressed need for
-  the interface is mostly just a marker interface, as a marker interface it doesn't really bring any constraints or guidance on how user should be using it. 
So I end up just created two internal class `SiloOptionsLogger` and `ClientOptionsLogger` which share the same base class `OptionsLogger`. SiloOptionsLogger subscribed to silo lifecycle, and …

Add IOptionFormatter and IOptionResolver interfaces

---

test/TesterInternal/GeoClusterTests/MultiClusterNetworkTests.cs

Skip TestMultiClusterConf_3_3 because it fails intermittently and needs to be investigated.

Skip TestMultiClusterConf_3_3

---

Directory.Build.props
Samples/ServiceFabric/Stateless/StatelessCalculatorApp/StatelessCalculatorApp.sfproj
Samples/ServiceFabric/Stateless/StatelessCalculatorApp/packages.config
Samples/ServiceFabric/Stateless/StatelessCalculatorService/BootstrapProvider.cs
Samples/ServiceFabric/Stateless/StatelessCalculatorService/StatelessCalculatorService.csproj
src/Orleans.Clustering.ServiceFabric/Orleans.Clustering.ServiceFabric.csproj
src/Orleans.Hosting.ServiceFabric/Orleans.Hosting.ServiceFabric.csproj
src/Orleans.ServiceFabric/Orleans.ServiceFabric.csproj

I'm not sure if running the sample requires VS 15.5.6 (which includes SF SDK 6.1), but if you have trouble running the sample then that might be why.

Update Service Fabric to support .NET Standard

---

src/Orleans.Core/Utils/Utils.cs
test/NonSilo.Tests/General/UtilsTests.cs

Use UriBuilder instead of String.Format in ToGatewayUri()

---

src/AdoNet/Orleans.Clustering.AdoNet/SqlUtilsHostingExtensions.cs
src/Orleans.Clustering.Consul/ConsulUtilsHostingExtensions.cs
src/Orleans.Clustering.ZooKeeper/ZooKeeperHostingExtensions.cs
src/Orleans.TestingHost/LegacyTestClusterConfiguration.cs
src/Orleans.TestingHost/TestCluster.cs
src/Orleans.TestingHost/TestClusterBuilder.cs
src/Orleans.TestingHost/TestClusterHostFactory.cs
src/Orleans.TestingHost/TestClusterOptions.cs
test/AWSUtils.Tests/StorageTests/Base_PersistenceGrainTests_AWSStore.cs
test/AWSUtils.Tests/Streaming/SQSClientStreamTests.cs
test/AWSUtils.Tests/Streaming/SQSStreamTests.cs
test/AWSUtils.Tests/Streaming/SQSSubscriptionMultiplicityTests.cs
test/Tester/MembershipTests/LivenessTests.cs
test/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureBlobStore.cs
test/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureStore.cs
test/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureTableStore.cs
test/TesterAzureUtils/Streaming/AQClientStreamTests.cs
test/TesterAzureUtils/Streaming/AQProgrammaticSubscribeTest.cs
test/TesterAzureUtils/Streaming/AQStreamFilteringTests.cs
test/TesterAzureUtils/Streaming/AQStreamingTests.cs
test/TesterAzureUtils/Streaming/AQSubscriptionMultiplicityTests.cs
test/TesterAzureUtils/Streaming/DelayedQueueRebalancingTests.cs
test/TesterAzureUtils/Streaming/HaloStreamSubscribeTests.cs
test/TesterAzureUtils/Streaming/SampleAzureQueueStreamingTests.cs
test/TesterAzureUtils/Streaming/StreamReliabilityTests.cs
test/TesterInternal/StreamProvidersTests.cs

- fix some tests
- remove `ServiceId` and `ClusterId` getter from `TestCluster`, since they are misleading. They only reflect values you set using `TestClusterOptions`, may not reflect values if you configure cluster using legacy `ClusterConfiguration`. 
- turn on file logger for TestCluster by default

Fix tests. Remove ServiceId and ClusterId getter, turn on file logging

---

src/Orleans.Core/CodeGeneration/GrainInterfaceUtils.cs
src/Orleans.Runtime/Catalog/ActivationData.cs

`IsStatelessWorker` check was iterating through type attributes.

Remove reflection usage from hot path

---

src/Orleans.Core.Legacy/Configuration/GlobalConfiguration.cs
src/Orleans.Core.Legacy/Configuration/NodeConfiguration.cs
src/Orleans.Core/Configuration/Options/ClientMessagingOptions.cs
src/Orleans.Core/Configuration/Options/ClientStatisticsOptions.cs
src/Orleans.Core/Configuration/Options/GrainDirectoryOptions.cs
src/Orleans.Core/Configuration/Options/GrainPlacementOptions.cs
src/Orleans.Core/Configuration/Options/MessagingOptions.cs
src/Orleans.Core/Configuration/Options/SchedulingOptions.cs
src/Orleans.Core/Configuration/Options/SiloMessagingOptions.cs
src/Orleans.Core/Configuration/Options/SiloStatisticsOptions.cs
src/Orleans.Core/Configuration/Options/StatisticsOptions.cs
src/Orleans.Core/Configuration/Options/ThreadPoolOptions.cs
src/Orleans.Core/Configuration/Options/TypeManagementOptions.cs
src/Orleans.Core/Configuration/Options/VersioningOptions.cs
src/Orleans.Runtime.Abstractions/Silo/SiloOptions.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs

Added formatters for grain directory options, grain placement options, schedualling options, thread pool options, type managment options, versioning options and silo options.
Fixed formatting of messaging options.
Fixed some options defaults.

More options formatting, and related cleanup

---

src/AdoNet/Shared/Storage/RelationalStorage.cs
test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs
test/TesterInternal/RemindersTest/ReminderTableTestsBase.cs
test/TesterInternal/RetryHelper.cs
test/TesterInternal/StorageTests/CommonStorageTests.cs
test/TesterInternal/StorageTests/RandomUtilities.cs
test/TesterSQLUtils/MySqlRemindersTableTests.cs
test/TesterSQLUtils/PostgreSqlRemindersTableTests.cs
test/TesterSQLUtils/SqlServerRemindersTableTests.cs
test/TesterSQLUtils/SqlStatisticsPublisherTests/MySqlStatisticsPublisherTests.cs
test/TesterSQLUtils/SqlStatisticsPublisherTests/PostgreSqlStatisticsPublisherTests.cs
test/TesterSQLUtils/SqlStatisticsPublisherTests/SqlServerStatisticsPublisherTests.cs
test/TesterSQLUtils/StorageTests/Relational/CommonFixture.cs
test/TesterSQLUtils/StorageTests/Relational/SqlServerStorageTests.cs
test/TesterSQLUtils/StorageTests/RelationalStoreTests.cs

This works so that
- Fixes cancellation test by unwrapping the real exception
The reason for the cancellation test failure is due to the test arrangement where the .Wait wraps the exception into an AggregateException and the real exception needs to be unwrapped first.
- Lowers database stress level to avoid deadlocking in tests (maybe not needed).
The test failures were due to deadlocks in the database where reads and writes were waiting for the same resource. As an intermediary resolution the test stress level was lowered to be more in line with the other persistence storage test.
Indexing would greatly improve the situation, but even better fix would be to rearrange the table. Indexing can be applied by anyone running a system without correctness problems with regards to Orleans, so …

Adds to Roman's fix the test fixes

---

src/Orleans.Core/Configuration/Options/SchedulingOptions.cs

Fixes #3814
We want this enabled by default for 2.0.0-rc1

Enable call-chain reentrancy by default

---

src/Orleans.Runtime/Placement/HashBasedPlacementDirector.cs
test/Tester/Placement/CustomPlacementTests.cs

Sort list of available compatible silos before picking a target one based on the grain ID hash.
Fixes non-deterministic behavior of HashBasedPlacementDirector and related tests.

Sort list of silos in HashBasedPlacementDirector

---

test/Tester/Placement/CustomPlacementTests.cs

Make sorting of silos in the custom placement tests match the order used in the placement director.

Fix intermittent failures in custom placement tests

---

src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBStorageProvider.cs
src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetStorageProvider.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorage.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
src/Orleans.Core/Runtime/IRuntimeClient.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
src/Orleans.Core/Serialization/OrleansJsonSerializer.cs
src/Orleans.Core/Serialization/SerializationManager.cs
src/Orleans.Core/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
test/DefaultCluster.Tests/GrainReferenceTest.cs
test/NonSilo.Tests/Serialization/ExternalSerializerTest.cs
test/NonSilo.Tests/Serialization/OrleansJsonSerializerTests.cs
test/TestExtensions/SerializationTestEnvironment.cs

Fixes #3853
Problem: `SerializationManager` attempts to create all configured serialization providers in its constructor, but `OrleansJsonSerializer` has a constructor dependency on `SerializationManager`. This causes a DI cycle and subsequently a `StackOverflowException`.
This PR fixes that issue.
* Removes `SerializationManager` property from `IRuntimeClient` (I'm really happy about this)
* Modifies the constructors of `InsideRuntimeClient`, `OutsideRuntimeClient`, and `OrleansJsonSerializer` to no longer take `SerializationManager`

Allow OrleansJsonSerializer to be used as an external serialization provider

---

test/TesterAzureUtils/Streaming/DelayedQueueRebalancingTests.cs

Skip DelayedQueueRebalancingTests_* for now.
#3993 is tracking fixing of these tests.

Skip faling tests until they are fixed

---

test/TesterInternal/TimeoutTests.cs

#3995 is tracking failures of the test.

Skip CallThatShouldHaveBeenDroppedNotExecutedTest for now

---

src/Azure/Orleans.Persistence.AzureStorage/Hosting/SiloBuilderExtensions.cs
src/Orleans.Core/Configuration/OptionLogger/IOptionsLogger.cs
src/Orleans.Core/Configuration/OptionLogger/OptionFormatterExtensionMethods.cs
src/Orleans.Core/Configuration/Options/ClientMessagingOptions.cs
src/Orleans.Core/Configuration/Options/ClientStatisticsOptions.cs
src/Orleans.Core/Configuration/Options/ClusterClientOptions.cs
src/Orleans.Core/Configuration/Options/GrainVersioningOptions.cs
src/Orleans.Core/Configuration/Options/LoadSheddingOptions.cs
src/Orleans.Core/Configuration/Options/MembershipOptions.cs
src/Orleans.Core/Configuration/Options/MultiClusterOptions.cs
src/Orleans.Core/Configuration/Options/NetworkingOptions.cs
src/Orleans.Core/Configuration/Options/SerializationProviderOptions.cs
src/Orleans.Core/Configuration/Options/ServicePointOptions.cs
src/Orleans.Core/Configuration/Options/StaticGatewayListProviderOptions.cs
src/Orleans.Core/Configuration/Options/TelemetryOptions.cs
src/Orleans.Core/Configuration/Options/ThreadPoolOptions.cs
src/Orleans.Core/Configuration/Options/TypeManagementOptions.cs
src/Orleans.Runtime.Abstractions/Silo/SiloOptions.cs
src/Orleans.Runtime/Configuration/Options/ConsistentRingOptions.cs
src/Orleans.Runtime/Configuration/Options/GrainCollectionOptions.cs
src/Orleans.Runtime/Configuration/Options/GrainDirectoryOptions.cs
src/Orleans.Runtime/Configuration/Options/GrainPlacementOptions.cs
src/Orleans.Runtime/Configuration/Options/GrainServiceOptions.cs
src/Orleans.Runtime/Configuration/Options/SchedulingOptions.cs
src/Orleans.Runtime/Configuration/Options/SiloMessagingOptions.cs
src/Orleans.Runtime/Configuration/Options/SiloStatisticsOptions.cs
test/Tester/LogFomatterTests.cs

Removed catalog, as it was deemed unnecessary.
Order logging by formatter name.  Helps with grouping of related options when using default formatters.
Allow user override of formatters before or after defaults.
Fixed issues with named options not reporting correctly.
Updated tests to verify by confirming expected log output.

Options formating improvements.

---

src/Orleans.Runtime/MembershipService/MembershipOracleData.cs
src/Orleans.Runtime/MultiClusterNetwork/MultiClusterOracle.cs
test/TesterInternal/GeoClusterTests/MultiClusterNetworkTests.cs

It turned out to be a simple oversight in the test construction - need to sort the silo addresses in the test so they match the order used by the multi-cluster gateway selection.
There are three commits here:
- an easy fix for the test
- while trying to find the root cause, I came across a small bug
- added tracing  that I needed to track this down

Fix multicluster test (#3929)

---

src/Orleans.Core/Configuration/Validators/ApplicationPartValidator.cs
src/Orleans.Core/Configuration/Validators/ClientClusteringValidator.cs
src/Orleans.Core/Core/DefaultClientServices.cs
src/Orleans.Runtime/Configuration/Validators/SiloClusteringValidator.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
test/NonSilo.Tests/SiloHostBuilderTests.cs

Validates that a clustering provider has been configured on the client and silo.

Add a configuration validator for cluster membership providers

---

src/Orleans.Core/Configuration/Validators/ApplicationPartValidator.cs
src/Orleans.Runtime/Configuration/Validators/EndpointOptionsValidator.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Hosting/EndpointOptions.cs

@benjaminpetit this might also need a default value for `AdvertisedIPAddress`, but I'm not sure if the default should be `Any`, `Localhost`, or something else.

Add a configuration validator and options formatter for EndpointOptions

---

src/AdoNet/Orleans.Clustering.AdoNet/Orleans.Clustering.AdoNet.csproj

Remove dependency on Runtime.Legacy from Orleans.Clustering.AdoNet. It is not needed there.

Remove dependency on Runtime.Legacy from Orleans.Clustering.AdoNet

---

src/Orleans.Core/Runtime/Constants.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Lifecycle/IStartupTask.cs
src/Orleans.Runtime/Lifecycle/SiloBuilderStartupExtensions.cs
src/Orleans.Runtime/Silo/Silo.cs
test/Tester/StartupTaskTests.cs

Resolves #4014
Developers can register an implementation of `IStartupTask` and perform operations such as calling grains from within the `OnStarted()` method.
Added a new `SystemTarget` for the purpose of scheduling startup tasks. I didn't extend scheduling to all lifecycle participants because the scheduler itself is only started at a certain silo lifecycle stage and therefore wont pump tasks before then. If this is an issue, maybe someone has an idea for how to solve it?
See the tests at the bottom for usage.

Add startup tasks to replace deprecated bootstrap providers

---

src/Azure/Orleans.Persistence.AzureStorage/Hosting/SiloBuilderExtensions.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorageOptions.cs
test/Orleans.Transactions.Azure.Test/TestFixture.cs
test/TesterAzureUtils/GenericGrainsInAzureStorageTests.cs
test/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureTableGrainStorage.cs
test/TesterAzureUtils/Persistence/PersistenceProviderTests.cs
test/TesterAzureUtils/Streaming/AQStreamingTests.cs
test/TesterAzureUtils/Streaming/HaloStreamSubscribeTests.cs
test/TesterAzureUtils/Streaming/StreamLifecycleTests.cs
test/TesterAzureUtils/Streaming/StreamLimitTests.cs
test/TesterAzureUtils/Streaming/StreamReliabilityTests.cs
test/TesterInternal/GeoClusterTests/BasicLogTestGrainTests.cs

- Add more logging to AzureTableGrainStorage init to improve debugging experience
- Add Configuration validator to  `AzureTableGrainStorageOptions`
- rename `DataConnectionString` to be `ConnectionString`. To be consistent with the `ConnectionString` in AzureGatewaylistprovider and AzureMembershipProvier

Add more logging to AzureTableGrainStorage init, Add ConfiguratorValidator

---

src/Orleans.Core.Legacy/Configuration/GlobalConfiguration.cs
src/Orleans.Runtime.Abstractions/Silo/ProcessExitHandlingOptions.cs
src/Orleans.Runtime.Abstractions/Silo/SiloOptions.cs
src/Orleans.Runtime.Legacy/Configuration/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Silo/Silo.cs

- Remove FastKillOnCancelKeyPress setting from SiloOptions and also legacy configuration, per #3957 
- Add ProcessExitHandlingOptions to configure whether to fast kill on process exit. per #4016

Remove FastKillOnCancel setting, add ProcessExitHandlingOptions

---

src/AdoNet/Orleans.Clustering.AdoNet/Messaging/AdoNetClusteringTable.cs
src/Orleans.Core/AssemblyLoader/AssemblyLoader.cs
src/Orleans.Core/Async/AsyncExecutorWithRetries.cs
src/Orleans.Core/Async/TaskExtensions.cs
src/Orleans.Core/Messaging/GatewayClientReceiver.cs
src/Orleans.Core/Messaging/GatewayConnection.cs
src/Orleans.Core/Messaging/GatewayManager.cs
src/Orleans.Core/Messaging/OutgoingMessageSender.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
src/Orleans.Core/Statistics/ThreadCycleStopWatch.cs
src/Orleans.Core/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans.Runtime/Catalog/ActivationDirectory.cs
src/Orleans.Runtime/Core/Dispatcher.cs

Migrate part of our logging message to use string template, instead of String.Format 
Reasons:
- String.Format is error prone. You may miss one arg or give extra arg. While string template doesn't have that problem
- Easy to use the logger extension method in a wrong way. See #4015 for more info.

Migrate to use string template, instead of String.Format

---

src/Orleans.Core/Configuration/Options/MembershipOptions.cs

How Found:
Set silo to startup via code without using legacy mode.  Exception thrown due to TimeSpan being set to 0.
SafeRandom.NextTimeSpan timeSpan must be a positive number.
Parameter name: timeSpan
Actual value was 00:00:00.
Code that fails on MembershipOracle.Start()
```
// randomly delay the startup, so not all silos write to the table at once.
// Use random time not larger than MaxJoinAttemptTime, one minute and 0.5sec*ExpectedClusterSize;
var random = new SafeRandom();
var maxDelay = TimeSpan.FromMilliseconds(500).Multiply(this.membershipOptions.ExpectedClusterSize);
maxDelay = StandardExtensions.Min(maxDelay, StandardExtensions.Min(this.membershipOptions.MaxJoinAttemptTime, TimeSpan.FromMinutes(1)));
var randomDelay = random.NextTimeSpan(maxDelay);
await Task.Delay(randomDelay); …
```

BUG: Some MembershipOptions default values were not being set causing errors.

---

src/AdoNet/Orleans.Persistence.AdoNet/Options/AdoNetGrainStorageOptions.cs

fix bad merge between #4045 and #4022 
#4045 removed SiloLifeCycle while #4022 is using it. #4022 got merged first. But #4045 didn't get merge conflicts maybe because they are not touching the same file. 
But anyway master doesn't build now. This PR shall fix it

Fix bad merge

---

src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBGatewayListProvider.cs
src/AWS/Orleans.Clustering.DynamoDB/Orleans.Clustering.DynamoDB.csproj
src/AdoNet/Orleans.Clustering.AdoNet/Messaging/AdoNetGatewayListProvider.cs
src/AdoNet/Orleans.Clustering.AdoNet/Orleans.Clustering.AdoNet.csproj
src/AdoNet/Orleans.Persistence.AdoNet/Orleans.Persistence.AdoNet.csproj
src/Azure/Orleans.Persistence.AzureStorage/Orleans.Persistence.AzureStorage.csproj
src/Orleans.Clustering.Consul/ConsulGatewayListProvider.cs
src/Orleans.Clustering.Consul/Orleans.Clustering.Consul.csproj
src/Orleans.Clustering.ZooKeeper/Orleans.Clustering.ZooKeeper.csproj
src/Orleans.Clustering.ZooKeeper/ZooKeeperClusteringClientOptions.cs
test/AWSUtils.Tests/MembershipTests/DynamoDBMembershipTableTest.cs
test/Consul.Tests/ConsulMembershipTableTest.cs
test/TesterAdoNet/MySqlMembershipTableTests.cs
test/TesterAdoNet/PostgreSqlMembershipTableTests.cs
test/TesterAdoNet/SqlServerMembershipTableTests.cs

Removed from:
- Orleans.Cluster.AdoNet
- Orleans.Persistence.AdoNet
- Orleans.Clustering.DynomoDb
- Orleans.Persistence.AzureStorage
- Orleans.Clustering.Consul
- Orleans.Clustering.ZooKeeper

Removed more legacy dependencies.

---

test/Tester/StartupTaskTests.cs

Execution order is not guaranteed - my bad.

Fix StartupTask tests

---

src/BootstrapBuild/Orleans.Core/Orleans.Core.Bootstrap.csproj
src/Orleans.Core.Legacy/Core/GrainClient.cs
src/Orleans.Core/ApplicationParts/ApplicationPartManagerExtensions.cs
src/Orleans.Core/Core/ClientBuilder.cs
src/Orleans.PowerShell/StartGrainClient.cs
src/Orleans.Runtime.Legacy/Hosting/SiloHost.cs
src/Orleans.Runtime/Hosting/Generic/SiloHostBuilder.cs
src/Orleans.TelemetryConsumers.Counters/OrleansPerformanceCounterInstaller.cs
src/Orleans.TestingHost/TestClusterHostFactory.cs
src/OrleansCounterControl/CounterControl.cs
src/OrleansManager/Program.cs
test/NetCore.Tests/ExceptionTests.cs
test/NonSilo.Tests/ClientBuilderTests.cs
test/NonSilo.Tests/SiloHostBuilderTests.cs
test/TestExtensions/SerializationTestEnvironment.cs
test/TesterInternal/GeoClusterTests/TestingClusterHost.cs
test/Versions/TestVersionGrains/VersionGrainsSiloBuilderfactory.cs

* Adds `IApplicationPartManager.AddFromDependencyContext()` to add app parts from the application's deps.json file.
* Adds `IApplicationPartManager.ConfigureDefaults()` to add parts from dependency context, app domain, and application base directory if no non-framework assemblies have been added yet. Called by SiloHostBuilder and ClientBuilder just before building the container.

Configure default application parts if no assemblies have been added

---

src/Orleans.Runtime/Hosting/EndpointOptions.cs

@benjaminpetit please review.
Instead of using this code:
```
.Configure<EndpointOptions>(o =>
{
o.AdvertisedIPAddress = Dns.GetHostAddresses(Dns.GetHostName()).First(s => s.AddressFamily == AddressFamily.InterNetwork);
o.SiloPort = 22222;
o.GatewayPort = 40000;
o.SiloListeningEndpoint = new IPEndPoint(IPAddress.Any, 22222);
o.GatewayListeningEndpoint = new IPEndPoint(IPAddress.Any, 40000);
})
```
I'd like it simplified with this:
```
.ConfigureEndpoints(22222, 40000, AddressFamily.InterNetwork, IPAddress.Any)
```

Added optional listenerAddress parameter to ConfigureEndpoints()

---

src/Orleans.Core.Abstractions/Core/IGrainCallFilter.cs
src/Orleans.Core/Configuration/ServiceCollectionExtensions.cs
src/Orleans.Core/Core/ClientBuilderGrainCallFilterExtensions.cs
src/Orleans.Core/Core/InterfaceToImplementationMappingCache.cs
src/Orleans.Core/Runtime/GrainReferenceRuntime.cs
src/Orleans.Core/Runtime/OutgoingCallInvoker.cs
src/Orleans.Runtime.Abstractions/Hosting/Generic/SiloHostBuilderExtensions.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
src/Orleans.Runtime/Hosting/Generic/SiloHostBuilderGrainCallFilterExtensions.cs
src/Orleans.Runtime/Orleans.Runtime.csproj
src/Orleans.TestingHost/Orleans.TestingHost.csproj
test/TestGrainInterfaces/IMethodInterceptionGrain.cs
test/TestGrains/MethodInterceptionGrain.cs
test/Tester/GrainCallFilterTests.cs
test/Tester/Tester.csproj

Fixes #3214 
Fixes #2125 
* Adds `IOutgoingGrainCallFilter` as a replacement for the current client-side interceptors (which are too low-level and less powerful than their counterpart, `IGrainCallFilter`).
* Rename `IGrainCallFilter` to `IIncomingGrainCallFilter` and add `IGrainCallFilter : IIncomingGrainCallFilter` as `[Obsolete]`
* Add methods to configure incoming/outgoing call filters to `IServiceCollection`, `IClientBuilder`, `ISiloHostBuilder`
* Mark existing `AddGrainCallFilter` methods as `[Obsolete]`, pointing to the new methods.
Need to perform perf test

Outgoing grain call filters

---

src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubStreamOptions.cs
src/Orleans.Core.Legacy/Configuration/ConfigurationExtensions.cs
src/Orleans.Core/Streams/ClientStreamExtensions.cs
src/Orleans.Core/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs
src/Orleans.Core/Streams/SimpleMessageStream/SimpleMessageStreamProviderOptions.cs
src/Orleans.Runtime.Abstractions/Hosting/StreamHostingExtensions.cs
test/AWSUtils.Tests/Streaming/SQSStreamTests.cs
test/GoogleUtils.Tests/Streaming/PubSubStreamTests.cs
test/Tester/GrainCallFilterTests.cs
test/Tester/StreamingTests/ProgrammaticSubscribeTests/ProgrammaticSubscribeTestSMSStreamProvider.cs
test/Tester/StreamingTests/ProgrammaticSubscribeTests/ProgrammaticSubscribeTestsWithImplicitSubscrbingGrains.cs
test/Tester/StreamingTests/SMSClientStreamTests.cs
test/Tester/StreamingTests/SMSDeactivationTests.cs
test/Tester/StreamingTests/SMSSubscriptionMultiplicityTests.cs
test/Tester/StreamingTests/SampleStreamingTests.cs
test/Tester/StreamingTests/StreamFilteringTests_SMS.cs
test/TesterAzureUtils/Streaming/AQStreamingTests.cs
test/TesterAzureUtils/Streaming/HaloStreamSubscribeTests.cs
test/TesterAzureUtils/Streaming/StreamLifecycleTests.cs
test/TesterAzureUtils/Streaming/StreamLimitTests.cs
test/TesterAzureUtils/Streaming/StreamReliabilityTests.cs
test/TesterInternal/GeoClusterTests/MultiClusterRegistrationTests.cs
test/TesterInternal/GeoClusterTests/TestingClusterHost.cs
test/TesterInternal/StreamProvidersTests.cs
test/TesterInternal/StreamingTests/SMSStreamingTests.cs
test/TesterInternal/StreamingTests/StreamPubSubReliabilityTests.cs

The SMS stream provider was refactored to use options and lifecycle, and is no longer an IProvider.
This work was done by @xiazen.  Published by me because it depends on my branch, and she's working on other tasks atm.

Sms stream provider to lifecycle

---

test/TesterAzureUtils/Streaming/AQStreamingTests.cs

Need a memory store provider named "MemoryStore" instead of the default one.

Fix test configuration bug in AzureQueue tests introduced in #4067

---

src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
src/Orleans.Runtime/Hosting/Generic/SiloHostBuilder.cs
src/Orleans.TestingHost/TestClusterHostFactory.cs
test/NonSilo.Tests/SiloHostBuilderTests.cs

Rename `ConfigureOrleans` methods to `Configure` to avoid having the project name in method names.

Rename ConfigureOrleans methods to Configure

---

src/Orleans.Core/ApplicationParts/AssemblyPart.cs
src/Orleans.Core/ApplicationParts/IApplicationPart.cs

In the discussion on #4084, we decided to make `IApplicationPart` explicitly implement `IEquatable<IApplicationPart>`

Make equality requirements of IApplicationPart explicit.

---

Samples/docker-aspnet-core/.dockerignore
Samples/docker-aspnet-core/API/API.csproj
Samples/docker-aspnet-core/API/Controllers/ValuesController.cs
Samples/docker-aspnet-core/API/Dockerfile
Samples/docker-aspnet-core/API/Program.cs
Samples/docker-aspnet-core/API/Properties/launchSettings.json
Samples/docker-aspnet-core/API/Startup.cs
Samples/docker-aspnet-core/API/appsettings.Development.json
Samples/docker-aspnet-core/API/appsettings.json
Samples/docker-aspnet-core/API/wwwroot/StyleSheet.css
Samples/docker-aspnet-core/API/wwwroot/index.html
Samples/docker-aspnet-core/GrainInterfaces/GrainInterfaces.csproj
Samples/docker-aspnet-core/GrainInterfaces/IValueGrain.cs
Samples/docker-aspnet-core/Grains/Grains.csproj
Samples/docker-aspnet-core/Grains/ValueGrain.cs
Samples/docker-aspnet-core/NuGet.Config
Samples/docker-aspnet-core/Silo/Dockerfile
Samples/docker-aspnet-core/Silo/Program.cs
Samples/docker-aspnet-core/Silo/Silo.csproj
Samples/docker-aspnet-core/docker-aspnet-core.sln
Samples/docker-aspnet-core/docker-compose.ci.build.yml
Samples/docker-aspnet-core/docker-compose.dcproj
Samples/docker-aspnet-core/docker-compose.override.yml
Samples/docker-aspnet-core/docker-compose.yml

The idea is to have a basic sample combining Docker, Orleans and ASP.NET Core.
This sample is pretty simple: a single grain identified by a integer, that can hold a string value. A basic webpage allow user to get and set these grain values.
It uses ASP.NET Docker tooling, so you can build and debug using Docker containers, which is nice. But it seems that if the containers are started with VS, the silo doesn't shutdown gracefully. I validated that if started from Docker CLI the silo shutdowns properly.
I am not an expert in ASP.NET Core, so I may have made mistake here and there.

Add basic sample using docker and asp.net core

---

src/AdoNet/Orleans.Clustering.AdoNet/AdoNetHostingExtensions.cs
src/AdoNet/Orleans.Clustering.AdoNet/Messaging/AdoNetClusteringTable.cs
src/AdoNet/Orleans.Clustering.AdoNet/Messaging/AdoNetGatewayListProvider.cs
src/AdoNet/Orleans.Clustering.AdoNet/Messaging/LegacyAdoNetClusteringConfigurator.cs
src/AdoNet/Orleans.Clustering.AdoNet/Messaging/LegacyAdoNetGatewayListProviderConfigurator.cs
src/AdoNet/Orleans.Clustering.AdoNet/Options/AdoNetClusteringClientOptions.cs
src/AdoNet/Orleans.Clustering.AdoNet/Options/AdoNetClusteringClientOptionsValidator.cs
src/AdoNet/Orleans.Clustering.AdoNet/Options/AdoNetClusteringSiloOptions.cs
src/AdoNet/Orleans.Clustering.AdoNet/Options/AdoNetReminderTableOptionsValidator.cs
src/AdoNet/Orleans.Persistence.AdoNet/Options/AdoNetGrainStorageOptions.cs
src/AdoNet/Orleans.Reminders.AdoNet/LegacySiloReminderConfigurationAdapter.cs
src/AdoNet/Orleans.Reminders.AdoNet/ReminderService/AdoNetReminderTableOptionsValidator.cs
src/AdoNet/Orleans.Reminders.AdoNet/SiloHostBuilderReminderExtensions.cs
test/TesterAdoNet/MySqlMembershipTableTests.cs
test/TesterAdoNet/PostgreSqlMembershipTableTests.cs
test/TesterAdoNet/SqlServerMembershipTableTests.cs

* Consolidate naming of ADO.NET invariant option: now it's `Invariant` in all places, instead of being `AdoInvariant` in clustering and `Invariant` everywhere else.
* Add configuration validators for clustering and reminders and improve grain storage validator to check that `Invariant` is set.
* Propagate invariant value from legacy configuration to reminder configuration.
* Add `invariant` parameter on reminder config extension method which takes a connection string.

Improve configuration validators for ADO.NET configuration

---

src/Orleans.Runtime/Placement/ActivationCountPlacementDirector.cs

It's possible that when using `ActivationCountBasedPlacement` strategy, the silo will try to choose a place for an activation before the cache used in the director is populated.
The proposed fix is just to place locally until the cache is ready.

In ActivationCountPlacementDirector, place locally if the cache is not ready

---

src/Orleans.Clustering.ServiceFabric/FabricMembershipOracle.cs
src/Orleans.Hosting.ServiceFabric/Orleans.Hosting.ServiceFabric.csproj
src/Orleans.Hosting.ServiceFabric/OrleansCommunicationListener.cs
src/Orleans.Hosting.ServiceFabric/ServiceFabricConfigurationExtensions.cs
test/TestServiceFabric/FabricMembershipOracleTests.cs
test/TestServiceFabric/OrleansCommunicationListenerTests.cs

Fixes #4109
The method for configuring endpoint options changes from
```C# 
clusterConfig.Defaults.ConfigureServiceFabricSiloEndpoints(this.serviceContext);
builder.UseConfiguration(clusterConfig);
```
to 
```C#
builder.Configure<EndpointOptions>(options =>
options.ConfigureFromServiceContext(serviceContext));
```

Remove legacy configuration requirement from Service Fabric hosting

---

src/AWS/Orleans.Clustering.DynamoDB/Membership/LegacyDynamoDBMembershipConfigurator.cs
src/AWS/Orleans.Reminders.DynamoDB/LegacySiloReminderConfigurationAdapter.cs
src/AdoNet/Orleans.Clustering.AdoNet/Messaging/LegacyAdoNetClusteringConfigurator.cs
src/AdoNet/Orleans.Reminders.AdoNet/LegacySiloReminderConfigurationAdapter.cs
src/Azure/Orleans.Clustering.AzureStorage/LegacyAzureMembershipConfigurator.cs
src/Azure/Orleans.Reminders.AzureStorage/LegacySiloReminderConfigurationAdapter.cs
src/Orleans.Clustering.Consul/LegacyConsulMembershipConfigurator.cs
src/Orleans.Clustering.ZooKeeper/LegacyZooKeeperMembershipConfigurator.cs
src/Orleans.Runtime.Abstractions/MembershipService/ILegacyMembershipConfigurator.cs
src/Orleans.Runtime.Legacy/Configuration/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime.Legacy/Configuration/LegacyMembershipConfigurator.cs
src/Orleans.Runtime.Legacy/Configuration/LegacyRemindersConfigurator.cs
src/Orleans.TestingHost.Legacy/LegacyTestClusterBuilderExtensions.cs

This removes some duplication in the legacy configuration methods.
By making legacy configuration use `ISiloHostBuilder`, there is less dependence on using `IServiceCollection` methods for provider configuration, as well as less duplication.
This will conflict with #4097, so I'll need to rebase whichever comes second.

Consolidate legacy configuration methods

---

src/Orleans.TelemetryConsumers.Counters/Statistics/HostBuilderExtensions.cs
src/Orleans.TelemetryConsumers.Counters/Statistics/PerfCounterEnvironmentStatistics.cs

Fix for PerfCounterEnvironmentStatistics never reports CpuUsage

---

src/Orleans.Runtime.Legacy/Configuration/LegacyMembershipConfigurator.cs

Fix implicit overriding of cluster ID in legacy membership configuration.

Fix legacy configuration

---

test/TesterInternal/General/ElasticPlacementTest.cs

Skip elasticity tests until their intermittent failures are investigated

---

src/Orleans.Runtime/Silo/Silo.cs

When the silo shutdown, deactivate grain activations at an earlier stage

---

test/Tester/HeterogeneousSilosTests/HeterogeneousTests.cs

Due to timing issue in test, `ActivationCountBasedPlacement` can be unreliable

Do not run MergeGrainResolverTests with ActivationCountBasedPlacement

---

src/Orleans.Runtime/Services/GrainService.cs

Fixes #4128.
This should help prevent mistakes of not setting the status to started, which leads to not receiving cluster repartitioning notifications.

Set GrainService.Status to Started in the base implementation of StartInBackground()

---

test/TesterInternal/GeoClusterTests/BasicMultiClusterTest.cs
test/TesterInternal/GeoClusterTests/TestingClusterHost.cs

This is a follow-up tp #4160 to fix multi-cluster tests.

Configure cluster ID in multi-cluster tests

---

src/Orleans.TestingHost.Legacy/Orleans.TestingHost.Legacy.csproj

I don't think we want to publish this package, as the assembly is only used for our legacy tests, and may easily confuse people.

Do not build a NuGet package for Orleans.TestingHost.Legacy

---

test/ServiceBus.Tests/Streaming/EHStreamProviderCheckpointTests.cs

Its dispose method was failing because wrong connection string parsed.

Fix EHStreamProviderCheckpointTests

---

src/Orleans.TestingHost.Legacy/LegacyTestClusterConfiguration.cs
src/Orleans.TestingHost/TestClusterOptions.cs
test/Tester/StreamingTests/SystemTargetRouteTests.cs

Added test demonstrating that system target calls are not routed correctly from the client.  The test demonstrates this by showing persistent streams fail to work when Gateways are not defined on every silo.

Gateways route system target calls correctly - test

---

src/Orleans.Runtime/Hosting/DefaultSiloServices.cs

Fix #4203 
The issue is that `SiloClusteringValidator` get `IMembershipOracle` and `IMembershipTable` from DI, and they require themselves a lot of other components in DI...
So if this validator is called before the validators from the options used in these membership constructors, it will fail without a good error message.
I think we should move these "advanced" check in the silo startup to avoid any trouble in the future, but for now it should fix the issue.

Fix validator ordering

---

src/Orleans.CodeGeneration/ApplicationPartManagerCodeGenExtensions.cs
test/RuntimeCodeGen.Tests/RuntimeCodeGenTests.cs

Otherwise we can't log diagnostic information about code generation.

WithCodeGeneration: accept ILoggerFactory instead of ILogger

---

src/Orleans.Core/CodeGeneration/GrainInterfaceUtils.cs

Spotted while trying to repro #4206
Without this, the build output will show a serialization exception in VS when an interface rule is violated.

Add serialization methods to RulesViolationException

---

src/Orleans.Core/Async/TaskExtensions.cs
src/Orleans.Core/Messaging/Message.cs
src/Orleans.EventSourcing/StateStorage/LogViewAdaptor.cs
src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/MultiClusterRegistration/GlobalSingleInstanceActivationMaintainer.cs
src/Orleans.Runtime/GrainDirectory/MultiClusterRegistration/GlobalSingleInstanceRegistrar.cs
src/Orleans.Runtime/LogConsistency/ProtocolServices.cs
src/Orleans.Runtime/MultiClusterNetwork/IMultiClusterOracle.cs
src/Orleans.Runtime/MultiClusterNetwork/MultiClusterOracle.cs
src/Orleans.Runtime/MultiClusterNetwork/MultiClusterOracleData.cs
src/Orleans.TestingHost.Legacy/LogConsistencyProviderConfiguration.cs
test/TesterInternal/GeoClusterTests/BasicLogTestGrainTests.cs
test/TesterInternal/GeoClusterTests/LogConsistencyTestFixture.cs
test/TesterInternal/GeoClusterTests/LogConsistencyTestsTwoClusters.cs
test/TesterInternal/GeoClusterTests/MultiClusterRegistrationTests.cs
test/TesterInternal/GeoClusterTests/TestingClusterHost.cs

It's been a while since we added multi-cluster support. Running all the tests, I found some bugs:
- when running with at least three clusters, and activating a grain concurrently, messages could get forwarded excessively, causing activation to fail (due to the forward count limit). I fixed this by forwarding only to destinations that are known to be the owner.
- Message.cs contained a bug that made the IsReturnedFromRemoteCluster flag not work correctly. This could also cause excessive forwarding, and failure to remove stale directory cache entries.
- in two places, NullReferenceExceptions were thrown when multi-clusters had no gateways reporting. I put in the proper handling of these situations.
- some tests were failing because the gsi-directory-maintenance was happening too late. To …

Fixes for Multi-Cluster Support

---

src/Orleans.Core/Core/ClusterClient.cs
src/Orleans.Core/Core/IClusterClient.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
test/Tester/ClientConnectionTests/ClusterClientTests.cs

For review only.
I didn't propagate the retry delegate all the way up to the API surface, but this is roughly what it might look like.

Support retries in ClusterClient.Connect(...)

---

src/AdoNet/Orleans.Clustering.AdoNet/Microsoft.Orleans.Clustering.AdoNet.targets
src/AdoNet/Orleans.Clustering.AdoNet/Orleans.Clustering.AdoNet.csproj
src/AdoNet/Orleans.Persistence.AdoNet/Microsoft.Orleans.Persistence.AdoNet.targets
src/AdoNet/Orleans.Persistence.AdoNet/Orleans.Persistence.AdoNet.csproj
src/AdoNet/Orleans.Reminders.AdoNet/Microsoft.Orleans.Reminders.AdoNet.targets
src/AdoNet/Orleans.Reminders.AdoNet/Orleans.Reminders.AdoNet.csproj

Currently since they're split and located in Nuget cache directory "far away"
from the project. Using nuget locals all -list, reveals the location is
something such as
C:\Users\<username>\.nuget\packages\microsoft.orleans.*.adonet\2.0.0-beta3\lib\netstandard2.0.
This improves the situation such that upon Nuget restore the files re copied to
project directory to \OrleansAdoNetContent where each supported ADO.NET provider
has its own directory.
Further, this makes it easier later to implement helper methods, such as automatic
database deployment, schema naming, filegroup additions and layout updates even with
large amounts of data.
Fixes #3864.

Improves ADO.NET script finding by moving them to project directory

---

src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
src/Orleans.Runtime/MembershipService/MembershipOracle.cs

The startup time is heavily increased by the delay in the membership oracle. For development we can set the clustersize to 1 and also do not wait. Reduced my startup time from 15 to 3 seconds.

Improve startup time for localhost cluster.

---

src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets

It turns out that the NuGet packages produced after #4224 contain non-codegen'd assemblies.
We will revert it for now while we attempt to rectify the issue

Revert #4224

---

src/Orleans.Core/Logging/ErrorCodes.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
test/Tester/HeterogeneousSilosTests/HeterogeneousTests.cs

Fix for #4096 and #4028 
Right now, clients get the grain type map only once when they first connect to the cluster. If there is any change in this map during the lifetime of the client, it will not be propagated.
With this fix, client will get an updated typemap every `TypeManagementOptions.TypeMapRefreshInterval` (by default 1 minute). It should help developer who are using in-place updgrade that cannot ensure that new clients do not start before new silos.

Client typemap refresh

---

src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets

Fixes #4189 again
Un-reverts #4256 
The differences between this and #4224 are:
* Only includes the .CoreCompileInputs.cache file if it exists (which was a problem during Pack)
* Fixes the codegen target between ResolveReferences & AssignTargetPaths instead of ResolveReferences & CoreCompile
I'll add a comment when load tests have finished, since they consume the NuGet packages and are what tipped us off last time.

Conditionally include @(Compile) cache file

---

src/Orleans.Core/Messaging/ClientMessageCenter.cs
src/Orleans.Runtime/Messaging/Gateway.cs
src/Orleans.TestingHost/ClientExtensions.cs
test/Tester/StreamingTests/SystemTargetRouteTests.cs
test/TesterInternal/ActivationsLifeCycleTests/DeactivateOnIdleTests.cs
test/TesterInternal/TestUtils.cs

Fix for #1069 
Currently, gateways override the value of `Message.SendingSilo` by their own `GatewayAddress` when sending message to clients, so they can always trust this value when responding to messages.
This is an issue when clients need to send a response to a SystemTarget activation when this activation is not on a silo that has a gateway (or when the client is not connected to that gateway).
This is a workaround, and more work should be done on client messaging routing in the future, but the idea is:
- Gateways will not override `Message.SendingSilo` value if they are proxying a message from a SystemTarget activated on another silo
- Client will no longer trust blindly the value received from `Message.SendingSilo`, so they will check that this is a valid gateway address. If this is …

Enable SystemTarget routing in the Gateway

---

test/DefaultCluster.Tests/ErrorGrainTest.cs

Related issue: #4221 
I was not able to reproduce this issue locally, my guess is that the build machine is sometimes a bit overloaded. I increased the test timeout value to see if it fix this issue.

Increase StressHandlingMultipleDelayedRequests reliability

---

src/Orleans.Core/Messaging/ClientMessageCenter.cs

Fix for #3171 
We could add code to make request fail quicker (not waiting the default timeout) but it a very edge case so I don't think it is worth it.

Fix race condition in ClientMessageCenter

---

src/Orleans.Core/Configuration/Options/MessagingOptions.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs

Fix for #3830 
Please let me know if what I did is not "option" compatible, but I think this is the cleanest way to implement such flag.

Add config option to override MessagingOptions.ResponseTimeout when the debugger is attached

---

src/Orleans.Core.Legacy/Configuration/ClientConfiguration.cs
src/Orleans.Core.Legacy/Configuration/ConfigurationExtensions.cs
src/Orleans.Core.Legacy/Configuration/GlobalConfiguration.cs
src/Orleans.Core.Legacy/Core/GrainClient.cs
src/Orleans.Core.Legacy/Logging/LegacyClass/ILogConsumer.cs
src/Orleans.Core.Legacy/Logging/LegacyClass/Logger.cs
src/Orleans.Core.Legacy/Logging/LegacyClass/LoggerExtensions.cs
src/Orleans.Core.Legacy/Logging/LegacyClass/LoggerWrapper.cs
src/Orleans.Core.Legacy/Logging/LegacyClass/TelemetryLogConsumer.cs
src/Orleans.Core.Legacy/Logging/LegacyFileLogConsumer.cs
src/Orleans.Core.Legacy/Logging/LegacyOrleansLogger.cs
src/Orleans.Core.Legacy/Logging/LegacyOrleansLoggerProvider.cs
src/Orleans.Core.Legacy/Logging/LegacyOrleansLoggingFactoryExtensions.cs
src/Orleans.Core.Legacy/Logging/LoggerExtensionMethods.cs
src/Orleans.Core.Legacy/Logging/OrleansLoggingUtils.cs

Fixes #4252.
I only left ` [Obsolete]` on `StatisticsWriteLogStatisticsToTable`, `StatisticsProviderName`, and `StatisticsWriteLogStatisticsToTable` because the underlying functionality has been removed; and on `ClientConfiguration.DeploymentId` and `GlobalConfiguration.DeploymentId` to disambiguate `DeploymentId` vs. `ClusterId`.

Remove [Obsolete] attributes from most legacy types

---

src/Orleans.Core/Streams/ClusterClientPersistentStreamConfigurator.cs
src/Orleans.Runtime.Abstractions/Streams/SiloPersistentStreamConfigurator.cs
src/Orleans.Runtime/Silo/SiloProviderRuntime.cs

- Add more logging about queuebalancer type created for a stream
- configure option formatter for options by default when `Configure<TOptions>` is called.

Add more logging to streaming

---

src/AdoNet/Orleans.Persistence.AdoNet/Orleans.Persistence.AdoNet.csproj
src/AdoNet/Orleans.Reminders.AdoNet/Orleans.Reminders.AdoNet.csproj

This is a follow-up to #4243.
There are currently build warnings while building `Orleans.Persistence.AdoNet/Orleans.Persistence.AdoNet.csproj` and `Orleans.Reminders.AdoNet/Orleans.Reminders.AdoNet.csproj` complaining about duplicate references to `Microsoft.Orleans.Persistence.AdoNet.targets`. This change seems to make build happy, and the content files still get copied to the project folder.
@veikkoeeva Could you double-check please.

Remove duplicate references to AdoNet.targets

---

src/Orleans.Runtime.Abstractions/Streams/SiloPersistentStreamConfigurator.cs

Persistent streams which has Explicit pubsub configured requires a grain storage with name `PubSubStore` configured with silo. But this is not obvious to users. So in this PR, adding a validation for this if user forget to configure one. 
Fix for #4196

Add validation for pubsubstore when using persistent streams

---

src/Azure/Orleans.Streaming.AzureStorage/Providers/Lease/AzureBlobLeaseProvider.cs
src/Orleans.Core/Providers/ILeaseProvider.cs
src/Orleans.Core/Streams/PersistentStreams/IStreamQueueBalancer.cs
src/Orleans.Runtime/Development/InMemoryLeaseProvider.cs
src/Orleans.Runtime/Streams/PersistentStream/PersistentStreamPullingManager.cs
src/Orleans.Runtime/Streams/QueueBalancer/ConsistentRingQueueBalancer.cs
src/Orleans.Runtime/Streams/QueueBalancer/DeploymentBasedQueueBalancer.cs
src/Orleans.Runtime/Streams/QueueBalancer/LeaseBasedQueueBalancer.cs
src/Orleans.Runtime/Streams/QueueBalancer/QueueBalancerBaseClass.cs
src/Orleans.Runtime/Timers/TimerRegistry.cs
test/NonSilo.Tests/OrleansRuntime/Streams/ResourceSelectorTestRunner.cs
test/NonSilo.Tests/OrleansRuntime/Streams/RoundRobinSelectorTests.cs
test/ServiceBus.Tests/PluggableQueueBalancerTests.cs
test/TestExtensions/Runners/GoldenPathLeaseProviderTestRunner.cs
test/Tester/StreamingTests/PlugableQueueBalancerTests/LeaseBasedQueueBalancer.cs
test/Tester/StreamingTests/PlugableQueueBalancerTests/LeaseManagerGrain.cs
test/Tester/StreamingTests/PlugableQueueBalancerTests/PluggableQueueBalancerTestBase.cs
test/Tester/StreamingTests/PlugableQueueBalancerTests/PluggableQueueBalancerTestsWithMemoryStreamProvider.cs

- Timers were not on orleans thread so couldn't make grain calls.
- Aqure logic could be too greedy
- logging and spelling cleanup (can you believe -I- fixed spelling?)
- prevented possible devide by 0 issues.

Lease based queue balancer fixes

---

src/Orleans.Runtime/ReminderService/ReminderRegistry.cs

Alternative implementation of #4280
Fixes #4278

Reminders: Improve error message when using reminders without a reminder table

---

src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
src/Orleans.Core/Utils/KeyedService.cs

Another prototype, like #4276, which allows override of options, by registering names services to override an option.

Overridable options

---

src/AWS/Orleans.Streaming.SQS/Streams/SQSAdapterFactory.cs
src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueAdapterFactory.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubCheckpointer.cs
src/Orleans.Core/Configuration/OptionsOverrides.cs
src/Orleans.Core/Utils/KeyedService.cs
src/Orleans.Runtime/Configuration/Overrides/SiloOptionsOverrides.cs
src/Orleans.Streaming.GCP/Providers/Streams/PubSub/PubSubAdapterFactory.cs

- Added registration functions that use named options and register the options for logging
- Updated named components that use cluster options to support the overrides.
Unclear what to do about unnamed components that use cluster options.  At this time they are not being overridden.  Maybe we can use the component name, or abstraction name?  (IReminderTable?, for instance).  What to do with unnamed components is for discussion and planning possible additional pass, should not block this PR.

Second pass at options overrides

---

src/Community/Links.md

I've updated my ~150 slide promo infodeck (a combined
presentation/cheatsheet/tutorial) for v2.0. Though some chapters are not
finished (DI, config, ...), the others are quite accurate and detailed.

New link in docs to a contribution

---

src/Orleans.Core/Configuration/Options/MessagingOptions.cs

Follow up #4193 
Thanks @lmagyar for catching this

Fix Add config option to override MessagingOptions.ResponseTimeout when the debugger is attached 

---

src/Tutorials/Declarative-Persistence.md
src/Tutorials/toc.yml

- Used original 1.5 Declarative Persistence tutorial as a template
- Rewrote sections relating to how the Silo and Client are configured
- Added references to where packages for storage providers can be found
- Potentially addresses #4298 
- Will likely need to be slightly edited to fit the rest of the tutorial series if they deviate too much from the 1.5 examples

Add Declarative Persistence Tutorial for 2.0

---

test/TesterInternal/GeoClusterTests/LogConsistencyTestsTwoClusters.cs

Until we resolve https://github.com/dotnet/orleans/issues/4293

Skipping LogConsistencyTestsTwoClusters tests.

---

Directory.Build.props

Without this fix, final builds of 2.0.0 are marked as "2.0.0-dev".

Do not add "-dev" version suffix to Release build if suffix isn't set.

---

src/Orleans.Streaming.GCP/Orleans.Streaming.GCP.csproj

Stop packaging Microsoft.Orleans.OrleansGCPUtils because it depends on a pre-released version of Google.Cloud.PubSub.V1.
Also rename the package to the proper name.

Stop packaging Microsoft.Orleans.OrleansGCPUtils

---

src/Documentation/2.0/Migration1.5.md

Add a note about the change in provider configuration in 2.0 and the potential implications.
We should probably lift the general Cluster/Service ID part to the configuration section after we rewrite it for 2.0

Add a note about the change in provider configuration in 2.0

---

src/Orleans.ServiceFabric/Orleans.ServiceFabric.csproj

Remove reference to `Microsoft.Orleans.Clustering.ServiceFabric` from `Microsoft.Orleans.ServiceFabric` meta-package because we pulled the former in 2.0.0 final. Otherwise, `Microsoft.Orleans.ServiceFabric` is trying to pull the non-existing 2.0.0 package.
Fixes #4350.

Remove reference to Orleans.Clustering.ServiceFabric from Orleans.ServiceFabric

---

src/Orleans.ServiceFabric/Orleans.ServiceFabric.csproj

Fix reference to Microsoft.Orleans.Hosting.ServiceFabric in Microsoft.Orleans.ServiceFabric to 2.0.0 version of the package, so that it doesn't point to a non existing version of the package (2.0.1 or 2.0.2).

Fix reference to Microsoft.Orleans.Hosting.ServiceFabric in Microsoft.Orleans.ServiceFabric to 2.0.0

---

Directory.Build.props

Fix assembly version to 2.0.0, so that assemblies stay compatible.
Bump up build default version to 2.0.3 (because we already published [2.0.2 version of Microsoft.Orleans.ServiceFabric](https://www.nuget.org/packages/Microsoft.Orleans.ServiceFabric/2.0.2).

Fix assembly version to 2.0.0 & increment build version

---

Samples/2.0/ChatRoom/ChatRoom.sln
Samples/2.0/ChatRoom/GrainImplementation/Channel.cs
Samples/2.0/ChatRoom/GrainImplementation/GrainImplementation.csproj
Samples/2.0/ChatRoom/GrainInterfaces/GrainInterfaces.csproj
Samples/2.0/ChatRoom/GrainInterfaces/IChannel.cs
Samples/2.0/ChatRoom/GrainInterfaces/Model/ChatMsg.cs
Samples/2.0/ChatRoom/OrleansClient/OrleansClient.csproj
Samples/2.0/ChatRoom/OrleansClient/Program.cs
Samples/2.0/ChatRoom/OrleansClient/StreamObserver.cs
Samples/2.0/ChatRoom/OrleansServer/OrleansServer.csproj
Samples/2.0/ChatRoom/OrleansServer/Program.cs
Samples/2.0/ChatRoom/ReadMe.md
Samples/2.0/ChatRoom/Utils/Constants.cs
Samples/2.0/ChatRoom/Utils/PrettyConsole.cs
Samples/2.0/ChatRoom/Utils/Utils.csproj

This is a simple sample using [Orleans Streaming feature](http://dotnet.github.io/orleans/Documentation/Orleans-Streams/index.html) to build a simple chatroom application. In this application, each client can 
- set its user name for ther chatroom application
- join a channel by channel name
- send messages to the channel
- query history messages in the channel
- query members in the channel
- leave the channel
Each client will
- receive messages sent to the channel by other clients and itself after joined a channel
- stop receive messages after leaved the channel
For the purpose to make this sample simple, one client can only join one channel. It cannot join multiple channels at the same time. So to join another channel, the client need to leave the current channel first.
From Visual …

Add a chatroom app which uses SMS stream as a streaming sample

---

src/Orleans.TelemetryConsumers.AI/AITelemetryConsumer.cs
src/Orleans.TelemetryConsumers.NewRelic/NRTelemetryConsumerConfigurationExtensions.cs
src/Orleans.TelemetryConsumers.NewRelic/NewRelicTelemetryConsumerOptions.cs

- Delete NewRelicTelemetryConsumerOptions.cs , since NewRelicTelemetryConsumer had a zero arg constructor in 1.5, so not sure why this option is here.
- Wire AITelemetryConsumer with its options 
fix for #4391

Fix telemetry consumer construction

---

src/Orleans.Runtime/Silo/TestHooks/ITestHooksSystemTarget.cs
src/Orleans.Runtime/Silo/TestHooks/TestHooksSystemTarget.cs
src/Orleans.TestingHost/TestCluster.cs
src/Orleans.TestingHost/TestClusterBuilder.cs

This PR adds a check in `TestCluster` to verify that each silo has observed the expected number of active silos

TestCluster: wait for cluster stabilization before starting tests

---

src/Orleans.Core.Abstractions/IDs/ActivationAddress.cs
src/Orleans.Core.Abstractions/Internal/Interner.cs

This is a minor improvement, one in a string of several to come. This change reduces the allocs for each call by approximately 300 bytes and reduces RTT (in proc) by ~21us on my machine.
Allocations are like paper cuts: too many and you bleed out.
For this and the other allocation related PRs, the targets are found by profiling, looking at hot spots, and picking the low-hanging fruit.
Before:
Method |     Mean |    Error |   StdDev |  Gen 0 | Allocated |
------- |---------:|---------:|---------:|-------:|----------:|
Ping | 375.3 us | 166.1 us | 9.387 us | 3.4180 |  15.83 KB |
After "Reduce allocs in Interner" commit:
Method |     Mean |    Error |   StdDev |  Gen 0 | Allocated |
------- |---------:|---------:|---------:|-------:|----------:|
Ping | 360.5 us | 200.2 us | 11.31 us | 3.4180 …

Reduce allocs in Interner

---

src/Orleans.Core.Abstractions/Runtime/RequestContext.cs

https://github.com/dotnet/orleans/issues/4313 
Approach proposed in the ticket couldn't be done. Even if we use AsyncLocal, Value that is stored is a reference type, so when we enter a new thread and AsyncLocal copies Value of instance from previous thread, it copies a link. So when we edit dictionary, we edit the same dictionary that was used in previous thread. That's why need to reallocate dictionary each time we call Set.
It would be great if we could understand that this call of Set method is the first per current thread, but AsyncLocal class doesn't provide such feature. So allocating a dictionary each time we call Set is the only way to make sure that it doesn't depend on dictionaries from other threads. 
But I found similar case in CoreClr repository. They also reallocate …

Improve Dictionary allocation

---

src/Orleans.Core.Abstractions/IDs/ActivationAddress.cs
src/Orleans.Core.Abstractions/Internal/Interner.cs

This reverts commit 10c3834c61c59f9285d525617926d2533c87654c.
Looks like #4395 caused a performance regression.

Revert "Reduce allocs in Interner (#4395)"

---

Samples/1.x/Chirper/ChirperGrains/ChirperAccount.cs
Samples/1.x/Presence/PresenceGrains/GameGrain.cs

This updates a couple of Samples to match the `IsSubscribed()` calls added to the docs in PR #4489. There wasn't a good Sample under 2.0, so maybe we still want to add a good Observer sample for 2.0, as I held off on updating too much of this 1.5 sample (such as updating all of the deprecated `TaskDone.Done` calls to `Task.CompletedTask`, which might make sense as part of a separate issue).

Update samples to match docs for Observers (#4061)

---

src/Orleans.CodeGeneration/RoslynCodeGenerator.cs
src/Orleans.CodeGeneration/SerializerGenerationManager.cs
src/Orleans.Core/CodeGeneration/TypeUtils.cs

Adds log lines to explain why a serializer is generated for a particular type.
Only enabled when logging is set to `Trace`, eg via the csproj property `<OrleansCodeGenLogLevel>Trace</OrleansCodeGenLogLevel>`

Increase diagnostic logging in code generator

---

src/Documentation/Orleans-Streams/index.md

"Stream Processing" link is currently using incorrect url, updated link to point to existing blog article on Confluent weblog.

Update "Stream Processing" link on Orleans Streams overview page

---

Samples/2.0/ChatRoom/GrainImplementation/GrainImplementation.csproj
Samples/2.0/ChatRoom/GrainInterfaces/GrainInterfaces.csproj
Samples/2.0/ChatRoom/OrleansClient/OrleansClient.csproj
Samples/2.0/ChatRoom/OrleansServer/OrleansServer.csproj
Samples/2.0/ChatRoom/ReadMe.md
Samples/2.0/ChatRoom/Utils/Utils.csproj

The example uses .NET Framework 4.6.2. Changing it makes it easier for
others to get started; updated readme to reflect changes.
Signed-off-by: Mike Lloyd <mike@reboot3times.org>

changed framework to netcoreapp2.0

---

src/Orleans.Core/Configuration/Options/ClusterOptions.cs
src/Orleans.Core/Core/ClientBuilderExtensions.cs
src/Orleans.Runtime.Legacy/Configuration/LegacyMembershipConfigurator.cs
src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
test/Tester/LocalhostSiloTests.cs

Clarify UseDevelopmentClustering and UseLocalhostClustering

---

src/Documentation/Deployment-and-Operations/Configuration-Guide/Options-List.md

`ClientOptionsLogger` and `SiloOptionsLogger` are not configuration options and could not be used as ASP.NET `IOptions<T>` options.

ClientOptionsLogger and SiloOptionsLogger are not configuration options

---

src/Orleans.Runtime/GrainDirectory/AdaptiveDirectoryCacheMaintainer.cs
src/Orleans.Runtime/MembershipService/MembershipOracle.cs
src/Orleans.Runtime/Messaging/SiloMessageSender.cs
test/TesterInternal/ErrorInjectionStorageProvider.cs
test/TesterInternal/StreamingTests/SingleStreamTestRunner.cs

Related issue: #4507 
This is the bare minimum fix to avoid any exception at runtime because of logging in Orleans. We will need to do several passes to remove entirely numbered format string.

Fix Exception thrown in MembershipOracle.TryToSuspectOrKill

---

src/Orleans.Core.Abstractions/Runtime/GrainReference.cs
src/Orleans.Core/Utils/Utils.cs
src/Orleans.Transactions/DistributedTM/Protocol/TransactionParticipantExtensionExtensions.cs

Revert `GrainReference.FromKeyString()` back to internal and expose it via `Utils.FromKeyString()` instead, so that Orleans.Abstractions don't need to get updated.
This is a follow-up to #3820. It changed `GrainReference.FromKeyString()` from `internal` to `public`, and that now requires us to update the `Core.Abstractions` package, which we'd prefer not to.
This change is a workaround that allows us to avoid updating abstractions unnecessarily.

Revert GrainReference.FromKeyString() back to internal

---

test/Transactions/Orleans.Transactions.Azure.Test/DistributedTM/GrainFaultTests.cs
test/Transactions/Orleans.Transactions.Tests/Runners/TransactionTestRunnerBase.cs

Disable multi-state transactional grain tests for singleton transaction manager tests.

Disable multi-state transactional grain tests

---

src/Orleans.TestingHost/Utils/TestingUtils.cs
src/Orleans.Transactions/InClusterTM/TransactionManagerGrain.cs
test/Transactions/Orleans.Transactions.Azure.Test/DistributedTM/TestFixture.cs
test/Transactions/Orleans.Transactions.Azure.Test/DistributedTM/TransactionRecoveryTests.cs
test/Transactions/Orleans.Transactions.Azure.Test/TestFixture.cs
test/Transactions/Orleans.Transactions.Azure.Test/TransactionRecoveryAzureTests.cs
test/Transactions/Orleans.Transactions.Tests/DistributedTM/MemoryTransactionsFixture.cs
test/Transactions/Orleans.Transactions.Tests/DistributedTM/TransactionRecoveryMemoryTests.cs
test/Transactions/Orleans.Transactions.Tests/Memory/MemoryTransactionsFixture.cs
test/Transactions/Orleans.Transactions.Tests/Memory/TransactionRecoveryMemoryTests.cs
test/Transactions/Orleans.Transactions.Tests/Orleans.Transactions.Tests.csproj
test/Transactions/Orleans.Transactions.Tests/Runners/TransactionRecoveryTestsRunner.cs

- Add transaction recoverability test runners. 
- Add transaction recoverability tests running against single TM. currently isn't included into functional or bvt, because single TM has recoverability problems , so the tests isn't passing. But it is higher priority to get the test runner merged in so we can test the new distributed TM. If you don't like it, I can remove the actual tests.

Add transaction recoverbility test runner

---

Directory.Build.props

Bump up versions of legacy packages for partial builds due to changes in #4515

Bump up versions of legacy packages for partial builds

---

src/Orleans.Core/Logging/CrashUtils.cs
src/Orleans.Core/Logging/ErrorCodes.cs
src/Orleans.Core/Logging/ILoggerExtensions.cs

Fixes #4545.
Remove saving of minidumps because that functionality is platform specific.

Remove saving of minidumps

---

src/Azure/Orleans.Transactions.AzureStorage/Hosting/AzureTableTransactionsSiloBuilderExtensions.cs
src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/DistributedTM/AzureTableTransactionalStateStorage.cs
src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/DistributedTM/AzureTableTransactionalStateStorageFactory.cs
src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/DistributedTM/KeyEntity.cs
src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/DistributedTM/StateEntity.cs
src/Orleans.Transactions/DistributedTM/Factories/INamedTransactionalStateStorageFactory.cs
src/Orleans.Transactions/DistributedTM/Factories/ITransactionalStateStorageFactory.cs
src/Orleans.Transactions/DistributedTM/Factories/NamedTransactionalStateStorageFactory.cs
src/Orleans.Transactions/DistributedTM/ITransactionalStateStorage.cs
src/Orleans.Transactions/DistributedTM/Implementation/StorageBatch.cs
src/Orleans.Transactions/DistributedTM/Implementation/TransactionParticipant.cs
src/Orleans.Transactions/DistributedTM/Implementation/TransactionalState.cs
src/Orleans.Transactions/DistributedTM/Implementation/TransactionalStateStorageProviderWrapper.cs
test/Transactions/Orleans.Transactions.Azure.Test/DistributedTM/TestFixture.cs

New implementation for Azure table transactional storage for distributed TM.
Supports arbitrarily sized batches.
Passes existing transactions tests (NOTE: fails on devstorage, must use actual Azure table).
Testing is somewhat incomplete, we still need more tests to exercise all the recovery situations.

Azure table transactional storage for distributed TM

---

src/Orleans.Transactions/Abstractions/Extensions/TransactionParticipantExtensionExtensions.cs

TransactionParticipantExtensionWrapper is serialized as part of StorageBatch Metadata, need to generate correct serializer for it otherwise gets serialization exception when trying to (de)serialization StorageBatch Metadata

Generate correct serializer for TransactionParticipantExtensionWrapper

---

src/Orleans.Transactions/State/TransactionalStateStorageProviderWrapper.cs
test/Transactions/Orleans.Transactions.Azure.Test/TestFixture.cs
test/Transactions/Orleans.Transactions.Tests/Memory/MemoryTransactionsFixture.cs
test/Transactions/Orleans.Transactions.Tests/TransactionTestConstants.cs

Fix a bug in TransactionalStateStorageProviderWrapper. This was a very plain bug causing an IndexOutOfRangeException; interestingly, it made it past the original unit tests. 
This bug was caught yesterday by the concurrency tests (#4595). That's exactly why we need those.
In this same PR I am also making a small change to reorganize the tracing configuration for transaction test cases to make it easier to control.

Fix Transactional StorageProvider Wrapper

---

src/Orleans.EventSourcing/Common/RecordedConnectionIssue.cs

The class is RecordedConnectionIssue never assigns the Issue property which causes DelayBeforeRetry() to never delay.

Fix bug where Issue is never assigned and retry delays never happen

---

src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/AzureTableTransactionalStateStorageFactory.cs

the similar partition keys are to each other, the more possible they will be put on the same node which is served by the same partition server(according to https://docs.microsoft.com/en-us/rest/api/storageservices/designing-a-scalable-partitioning-strategy-for-azure-table-storage) . So make azure tx state store more scalable, update the partition key to be more different.

Change azure tx state partition key to improve scalability

---

src/Orleans.Transactions/State/TransactionParticipant.cs

These checks were accidentally removed at some point. The point is to create a reasonable error message when a transactional state is accessed from outside a transactional context.

fix missing error message when accessing facets

---

test/Transactions/Orleans.Transactions.Azure.Test/TransactionRecoveryAzureTests.cs
test/Transactions/Orleans.Transactions.Tests/Memory/TransactionRecoveryMemoryTests.cs

I see this failing a lot in VSO

Skip TransactionWillRecoverAfterRandomSiloUnGracefulShutdown (see #4617)

---

src/Azure/Orleans.Hosting.AzureCloudServices/Hosting/AzureClient.cs
src/Azure/Orleans.Hosting.AzureCloudServices/Hosting/AzureSilo.cs
src/Orleans.Core.Legacy/Core/GrainClient.cs
src/Orleans.Runtime.Legacy/Hosting/SiloHost.cs
test/TesterInternal/ClientInitTests.cs

Since now providers need to be configured using the builder pattern, developer stuck with the legacy Silo and GrainClient can no longer configure thingks like storage, or stream providers.
This PR enable them to configure it so transition is more easy.

Add Client/SiloHost builder delegate to legacy GrainClient and SIlo/AzureSilo

---

Directory.Build.props
src/Orleans.Client/Directory.Build.props
src/Orleans.Server/Directory.Build.props

Fixes #4601.
With this, we should be able to publish just 2.0.3 versions of the Client and Server meta-packages without incrementing version to 2.0.4.

Update Client and Server packages to 2.0.3

---

Build.cmd
Test.cmd

Currently, if a recent sdk version is installed, the latest version will be used instead of the version specified in the `DotnetCLIVersion.txt`. Setting `DOTNET_MULTILEVEL_LOOKUP` to 0 fix this issue

Disable multilevel lookup

---

src/Orleans.Runtime.Legacy/Configuration/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/Configuration/Options/SchedulingOptions.cs
src/Orleans.Runtime/Scheduler/OrleansTaskScheduler.cs

MaxPendingWorkItemsHardLimit is not used. No reason for it to be exposed through SchedulingOptions

Remove unused settings MaxPendingWorkItemsHardLimit in SchedulingOptions

---

src/Build.cmd

Forcing TLS 1.2 seems to fix the issue encountered when downloading `vswhere.exe`

Fix vswhere tool download in Build.cmd

---

src/Tutorials/Custom-Grain-Storage.md

This is a tutorial on how to create a custom grain storage for 2.0.
It is taking as base the previous document on storage provider 1.5, but updated to follow the current grain storage implementation found in Azure persistence and AWS persistence
It is explaining implementation of `IGrainStorage` and `ILifecycleParticipant<ISiloLifecycle>`. It also explains how to create the factory and the extensions in order to make the grain storage registration available on the `ISiloHostBuilder`.
_I am not sure if this is the right place to merge, could you please advise and I will move the tutorial. Thanks!_

Tutorial on Custom Grain Storage for 2.0

---

src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets

#4673 introduced a regression: when using the command `dotnet build` to build project that target the full .NET framework, the variable for `CoreAssembly` is not set, and the variable `TaskAssembly` depends on it.
The easiest workaround here is to always fallback to 2.0 dll
Maybe we could instead removing this task dependency, and rely on the fact that we should find the `dotnet` command in the path @ReubenBond ?

Use netcoreapp2.0 for msbuild target dll if using dotnet core msbuild but targeting full .net

---

src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/AzureTableTransactionalStateStorageFactory.cs
src/Orleans.Transactions/Abstractions/Extensions/TransactionParticipantExtensionExtensions.cs
src/Orleans.Transactions/State/StorageBatch.cs
src/Orleans.Transactions/State/TransactionParticipant.cs
src/Orleans.Transactions/State/TransactionParticipantExtension.cs
src/Orleans.Transactions/State/TransactionalState.cs
src/Orleans.Transactions/State/TransactionalStateFactory.cs
test/Transactions/Orleans.Transactions.Azure.Test/TestFixture.cs
test/Transactions/Orleans.Transactions.Tests/Memory/SerializationTests.cs

- removed static `MetaData.SerializerSettings`. Now serializer settings are parsed through constructors
- fixed serialization settings. Should use `TypeNameHandling.All`, instead of `Auto`
- fixed inconsistent serialization settings used in `AzureTableTransactionStateStorage` and `TransactionalState`, `StorageBatch`
- add `[JsonProperty]` attr to `TransactionParticipantExtensionWrapper ` fields
The first bullet point is refactoring. The remaining is there to fix the issue of `TransactionParticipantExtensionWrapper` is serialized into a "{}" before persist into storage, which is a json string represents empty instance. This causes transaction recovery failing when restore transaction state from storage.

Fix TransactionParticipantExtensionWrapper serialization issues

---

test/Transactions/Orleans.Transactions.Tests/Runners/GoldenPathTransactionTestRunner.cs

Tests where unnessessarily fanning out to 64 transactional states when only 8 where necessary for testing.  This led to intermittent failures due to timeouts.  They now only run against the targeted 8 transactional states.

Fixed intermittent Transaction test failures

---

src/Orleans.Runtime/Scheduler/WorkQueue.cs

Fixes #4505 
This implements a workaround for some divergent behavior between .NET Core and .NET Framework tracked by https://github.com/dotnet/corefx/issues/30781
Note that this is intended for a 2.0.4 release.

Workaround for CoreFx/#30781 (Fixes #4505)

---

test/TesterInternal/DeadlockDetectionWithAllowCallChainReentrancyTests.cs
test/TesterInternal/DeadlockDetectionWithoutAllowCallChainReentrancyTests.cs

Added deadlock detection testing when allow call chain reenterancy is turned off.
Testing added to help track down PerformDeadlockDetection not working in 2.0 #4706

DeadlockDetectionWithoutAllowCallChainReentrancyTests

---

src/Orleans.Transactions/Abstractions/Extensions/TransactionParticipantExtensionExtensions.cs

Transaction wrapper was not serializing the participant when using json.

Transaction participant wrapper json serialization fix

---

README.md

- Fixes #4783
- May be beneficial to make `Microsoft.Orleans.OrleansCodeGenerator.Build` depend on `Microsoft.Orleans.Core.Abstractions` as to not require it as a separate package installation.
- Changes as per #4783 and discussion on gitter starting at https://gitter.im/dotnet/orleans?at=5b51f88bf9ffc4664bef9663

Adds additional dependencies for Grain.Impl and Grain.Interface projects

---

Directory.Build.props

We recently introduced a breaking change in Core.Abstraction, which means we need to bump every package version to 2.1 as well. More info in #4776

Bump orleans package version to 2.1

---

test/Benchmarks/Serialization/SerializationBenchmarks.cs

Serialization benchmarks will throw `Orleans.Runtime.OrleansConfigurationException` for lack of clustering configuration.

Fix serialization benchmarks

---

test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionCoordinatorGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/MultiStateTransactionalGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/TransactionCoordinatorGrain.cs
test/Transactions/Orleans.Transactions.Tests/Runners/GrainFaultTransactionTestRunner.cs

Verify exception handling logic when multiple particiant throw. The expected logic is only one exception is picked as the inner exception of OrleansTransactionAbortException

Verify exception handling logic when multiple particiant throw

---

src/Orleans.Transactions/State/ReaderWriterLock.cs
src/Orleans.Transactions/State/TransactionParticipant.cs
src/Orleans.Transactions/State/TransactionalState.cs

As mentioned by @xiazen a couple weeks ago, the transactional state does not quite do the right thing when catching `InconsistentStateException`. 
This PR adds the following behavior to a transactional state facet that catches an `InconsistentStateException`:
1. calls `DeactivateOnIdle`
2. aborts all transactions in the wait queue (i.e. transactions that have not accessed the state yet but are queued up waiting to enter the lock)

fix/improve transactional state behavior after InconsistentStateException

---

src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueAdapter.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueAdapterFactory.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueAdapterReceiver.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueStreamBuilder.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueStreamOptions.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueStreamProviderUtils.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureStreamQueueMapper.cs
src/Azure/Orleans.Streaming.AzureStorage/Storage/AzureQueueDataManager.cs
test/Extensions/TesterAzureUtils/AzureQueueDataManagerTests.cs
test/Extensions/TesterAzureUtils/Streaming/AQClientStreamTests.cs
test/Extensions/TesterAzureUtils/Streaming/AQProgrammaticSubscribeTest.cs
test/Extensions/TesterAzureUtils/Streaming/AQStreamFilteringTests.cs
test/Extensions/TesterAzureUtils/Streaming/AQStreamingTests.cs
test/Extensions/TesterAzureUtils/Streaming/AQSubscriptionMultiplicityTests.cs
test/Extensions/TesterAzureUtils/Streaming/AzureQueueAdapterTests.cs
test/Extensions/TesterAzureUtils/Streaming/DelayedQueueRebalancingTests.cs
test/Extensions/TesterAzureUtils/Streaming/HaloStreamSubscribeTests.cs
test/Extensions/TesterAzureUtils/Streaming/SampleAzureQueueStreamingTests.cs
test/Extensions/TesterAzureUtils/Streaming/StreamLifecycleTests.cs
test/Extensions/TesterAzureUtils/Streaming/StreamLimitTests.cs
test/Extensions/TesterAzureUtils/Streaming/StreamReliabilityTests.cs
test/Extensions/TesterAzureUtils/Tester.AzureUtils.csproj
test/Extensions/TesterAzureUtils/Utilities/AzureQueueUtilities.cs
test/Tester/StreamingTests/PullingAgentManagementTests.cs

-make azure queue name prefix configuration through `AzureQueueOptions`
-if not set, then default to its original value , which is serviceId-providerName
For issue #4577

Make azure queue name configurable

---

src/Orleans.Transactions/Abstractions/ITransactionAgentStatistics.cs
src/Orleans.Transactions/DistributedTM/TransactionAgent.cs
src/Orleans.Transactions/DistributedTM/TransactionAgentStatistics.cs
src/Orleans.Transactions/DistributedTM/TransactionAgentStatisticsReporter.cs
src/Orleans.Transactions/DistributedTM/TransactionOverloadDetector.cs
src/Orleans.Transactions/Hosting/SiloBuilderExtensions.cs
test/Benchmarks/Program.cs
test/Benchmarks/Transactions/TransactionBenchmark.cs
test/Grains/BenchmarkGrainInterfaces/Transaction/ILoadGrain.cs
test/Grains/BenchmarkGrains/Transaction/LoadGrain.cs
test/Transactions/Orleans.Transactions.Tests/TransactionOverloadDetectorTests.cs

Added more transaction metrics, and benchmark tests for transaction throttling.

More Transaction Metrics

---

src/Orleans.Runtime.Abstractions/Hosting/HostingGrainExtensions.cs
src/Orleans.Runtime/Catalog/ActivationData.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
test/DefaultCluster.Tests/ProviderTests.cs
test/Grains/TestGrainInterfaces/IExtensionTestGrain.cs
test/Grains/TestGrainInterfaces/ITestExtension.cs
test/Grains/TestGrains/NoOpTestGrain.cs
test/Grains/TestInternalGrains/TestExtension.cs

Grains can now load grain extension from the container upon request rather than requiring the grain to register them during activation.

Auto-installing grain extensions

---

src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/AzureTableTransactionalStateStorage.cs
src/Orleans.Transactions/State/TransactionQueue.cs

Found two bugs using my consistency tests w/ randomized fault injection.
- fix bug in azure table transactional storage implementation: fails to recover state that was read, but never updated
- fix bug in transaction recovery: did not correctly restore the information in prepare records to indicate this transaction was updating the state

Fixes to transactional storage and recovery

---

README.md

When I access the documentation using http://dotnet.github.io/orleans/Documentation/Introduction.html I am missing the navigation bar. The https version works fine.

Changed link to documentation to use https instead of http

---

src/Orleans.Transactions/Abstractions/ITransactionManager.cs
src/Orleans.Transactions/Abstractions/ITransactionManagerExtension.cs
src/Orleans.Transactions/Abstractions/ITransactionalResource.cs
src/Orleans.Transactions/Abstractions/ITransactionalResourceExtension.cs
src/Orleans.Transactions/DistributedTM/ParticipantId.cs
src/Orleans.Transactions/DistributedTM/TransactionAgent.cs
src/Orleans.Transactions/DistributedTM/TransactionInfo.cs
src/Orleans.Transactions/DistributedTM/TransactionRecord.cs
src/Orleans.Transactions/State/TransactionManager.cs
src/Orleans.Transactions/State/TransactionManagerExtension.cs
src/Orleans.Transactions/State/TransactionalResource.cs
src/Orleans.Transactions/State/TransactionalResourceExtension.cs
src/Orleans.Transactions/State/TransactionalState.cs
test/Transactions/Orleans.Transactions.Tests/Memory/SerializationTests.cs

Only one priority transaction manager is allowed per transaction.  Priority TM be used to detect TOC in future changes.
Also moved ReadonlyCommit to resource interface from tm interface.  Call was placed in wrong interface when split.

Added support for priority transaction manager. 

---

src/Orleans.Core/Threading/ThreadPoolExecutor.cs

I hit a `NullReferenceException` here while debugging #4617.
The root cause was the order of initialization of `log` and `executingWorkTracker` in the `ThreadPoolExecutor` constructor.
This PR fixes that, adds some defensiveness, and cleans up the code a little.

Fix NullReferenceException in ExecutingWorkItemsTracker

---

src/Orleans.Transactions/Properties/AssemblyInfo.cs
src/Orleans.Transactions/State/TransactionalState.cs
test/Transactions/Orleans.Transactions.Azure.Test/TestFixture.cs
test/Transactions/Orleans.Transactions.Azure.Test/TransactionDeactivationTests.cs
test/Transactions/Orleans.Transactions.Tests/DeactivationTransaction/DeactivatingTransactionCoordinatorGrain.cs
test/Transactions/Orleans.Transactions.Tests/DeactivationTransaction/DeactivationTransactionReource.cs
test/Transactions/Orleans.Transactions.Tests/DeactivationTransaction/DeactivationTransactionState.cs
test/Transactions/Orleans.Transactions.Tests/DeactivationTransaction/DeactivationTransactionStateAttribute.cs
test/Transactions/Orleans.Transactions.Tests/DeactivationTransaction/HostingExtensions.cs
test/Transactions/Orleans.Transactions.Tests/DeactivationTransaction/SingleStateDeactivatingTransactionalGrain.cs
test/Transactions/Orleans.Transactions.Tests/Runners/DeactivationTransactionTestRunner.cs

- implemented DeactivationTransactionalState facet which can inject deactivation command into different phase of a transaction
- implemented DeactivationTransactionTestRunner and AzureDeactivationTransactionTests which uses the runner. This runner contains a minimum scenario which can happen during our recovery tests
The goal of this test runner is to break down transaction recovery tests into more granular test cases. Our current recovery test is a end to end test, we shutdown a silo (non)gracefully during the test, and see if transaction recovered. It is failing now, and it is very hard to debug since test may fail due to a different reason each time, and there's a broad range of possibilities to explore. This test runner introduced a list of possible scenarios which can happen in …

Add deactivation injection transaction tests 

---

src/Orleans.Runtime/Catalog/ActivationData.cs
test/Grains/TestGrainInterfaces/ITimerGrain.cs
test/Grains/TestInternalGrains/TimerGrain.cs
test/Tester/Forwarding/ShutdownSiloTests.cs

Fix for #4774 
Thanks @yevhen , I was able to repro this issue 100% with this test. Like said in the issue, this will fix only part of the issue.

When deactivating a grain, do not stop timers if there are running requests 

---

src/Orleans.Core/Async/MultiTaskCompletionSource.cs
src/Orleans.Runtime/Catalog/Catalog.cs
src/Orleans.Runtime/Configuration/Options/GrainCollectionOptions.cs
test/Grains/TestGrainInterfaces/ITimerGrain.cs
test/Grains/TestInternalGrains/TimerGrain.cs
test/Tester/Forwarding/ShutdownSiloTests.cs

It's not the fix I intended to write, but I thinks used in conjunction with #4875, it should fix the issues encountered in #4774 and #4757

Add timeout mecanism for grain deactivation

---

src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/StateEntity.cs
src/Orleans.Transactions/DistributedTM/TransactionAgent.cs

Discovered two bugs yesterday and today.
- the table storage does not correctly read state back because the long.Parse does not expect hex format. D'oh. A bit surprising that we didn't notice this earlier.
- (as discussed in meeting on 8/23) fix bug introduced by #4831: only write-participants are eligible for TM selection.

two transaction fixes (table storage, TM selection)

---

src/Orleans.Runtime/Transactions/DisabledTransactionAgent.cs
src/Orleans.Transactions/Abstractions/ITransactionCommitter.cs
src/Orleans.Transactions/Abstractions/ITransactionCommitterConfiguration.cs
src/Orleans.Transactions/Abstractions/ITransactionCommitterFactory.cs
src/Orleans.Transactions/Abstractions/ITransactionalState.cs
src/Orleans.Transactions/Abstractions/TransactionCommitterAttribute.cs
src/Orleans.Transactions/DistributedTM/ContextResourceFactoryExtensions.cs
src/Orleans.Transactions/DistributedTM/TransactionManagerExtension.cs
src/Orleans.Transactions/DistributedTM/TransactionalResourceExtension.cs
src/Orleans.Transactions/Hosting/SiloBuilderExtensions.cs
src/Orleans.Transactions/Hosting/TransactionCommitterAttributeMapper.cs
src/Orleans.Transactions/State/TransactionQueue.cs
src/Orleans.Transactions/TOC/TocTransactionQueue.cs
src/Orleans.Transactions/TOC/TransactionCommitter.cs
src/Orleans.Transactions/TOC/TransactionCommitterFactory.cs
test/Transactions/Orleans.Transactions.Azure.Test/TestFixture.cs
test/Transactions/Orleans.Transactions.Azure.Test/TocGoldenPathTests.cs
test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionCommitterTestGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionCoordinatorGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/RemoteCommitService.cs
test/Transactions/Orleans.Transactions.Tests/Grains/TransactionCommitterTestGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/TransactionCoordinatorGrain.cs
test/Transactions/Orleans.Transactions.Tests/Memory/MemoryTransactionsFixture.cs
test/Transactions/Orleans.Transactions.Tests/Memory/TocGoldenPathMemoryTests.cs
test/Transactions/Orleans.Transactions.Tests/Runners/TOCGoldenPathTestRunner.cs
test/Transactions/Orleans.Transactions.Tests/TransactionTestConstants.cs

Minimal transfer of coordintation support for transactions.
- TransactionCommitter facet
- Changed to commit logic to commit only upon successfull remot service call.
- Minima golden path tests

Minimal TOC

---

src/Documentation/index.md
src/index.md

… from Orleans Overview to main landing page, (to keep content about documentation itself together)
- made some grammar and sentence structure edits
- verified links

Moved the "This documentation is for the 2.0 release" section... 

---

src/Orleans.Runtime/Hosting/DefaultSiloServices.cs

Do not try to register GrainVersionStore if an implementation of IVersionStore is already registered

---

README.md

The link to documentation in the readme went to a page which does not exists. It's been updated to link to the root path for the documentation site.

Fix README.md documentation link

---

src/Orleans.Core/Messaging/ClientMessageCenter.cs
src/Orleans.Core/Messaging/GatewayConnection.cs
src/Orleans.Core/Runtime/InvokableObjectManager.cs
src/Orleans.Runtime/Messaging/Gateway.cs
src/Orleans.Runtime/Messaging/SiloMessageSender.cs
test/Grains/TestGrainInterfaces/IExceptionGrain.cs
test/Grains/TestGrains/MessageSerializationGrain.cs
test/Tester/ExceptionPropagationTests.cs

Fixes #4793 
There are 6 scenarios being tested, which can be summed up as `{Serialization, Deserialization} exception sending to a {client, grain} from a {client, grain}` except I didn't add tests for the client-to-client cases (they go via silo anyway).
In the end, there's similar logic for handling these exceptions in:
* `GatewayConnection.OnMessageSerializationFailure` - client to gateway (request)
* `InvokableObjectManager.LocalObjectMessagePumpAsync` - client to gateway (response)
* `Gateway.GatewaySender.OnMessageSerializationFailure` - gateway to client
* `SiloMessageSender.OnMessageSerializationFailure` - silo to silo
The client-to-gateway response scenarios are a little contrived, since client objects are not supposed to be able to return `Task` or `Task<T>`, only `void`. The …

Propagate message serialization exceptions to callers

---

src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCache.cs

Related to #4935 
- Cursor was allowed to be in a state dependent on a token
while allowing the containing bucket to be purged

#4935 Fixing race condition with simple queue cache

---

src/Documentation/toc.yml

Remove 'Who's using Orleans" file from table of contents.

---

src/Orleans/Messaging/GatewayConnection.cs
src/Orleans/Messaging/MessageFactory.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Messaging/Gateway.cs
src/OrleansRuntime/Messaging/SiloMessageSender.cs
test/TestGrainInterfaces/IExceptionGrain.cs
test/TestGrains/MessageSerializationGrain.cs
test/Tester/ExceptionPropagationTests.cs

This is a port of #4907 to the 1.5.x branch
The [previous revision](https://github.com/dotnet/orleans/pull/4916) had some build-breaking merge issues.

[1.5.5] Propagate message serialization errors to callers 

---

src/Orleans.Core/Serialization/TypeUtilities.cs
test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs

- `Guid` is shallow copyable and primitive.
- `Nullable<T>` is shallow copyable if the wrapped type is shallow copyable.
- `Tuple<T,...>` is shallow copyable if all the element types are shallow copyable.
- Value types are shallow copyable if all public and private instance fields are shallow copyable.
Previously private fields were ignored and public static fields were checked instead and generic types were not allowed.
- Changed the static constructor to a field initializer for better performance (static constructors enforce precise initialization timing which can be expensive).

IsOrleansShallowCopyable fixes

---

src/Orleans.TestingHost/Utils/TestingUtils.cs

some azure streaming tests failed due to diff introduced to WaitUntilAsync in pr #4923 . It is not necessarily the changes in WaitUtilAcync is wrong, is how those tests uses it is slightly wrong IMO. For a quick fix, let's revert WaitUtilAsync's behavior to its original when `delayOnFail` is not set. @jason-bragg let me know if this affects the tx recovery fix you put in #4923 . 
The azure steaming tests failed due to that timing become hasher after WaitUtilAsync change. Before the pr, WaitUtilAsync would be waiting 1 sec regardless, but after the pr, it won't if predicate succeed. For tests such as `StreamingTests_Consumer_Producer_UnSubscribe`, the test use WaitUtilAsync to ensure producer produced. After the pr, producer would produce far less, leaving little time for consumer to react …

Fix azure streaming tests

---

src/Documentation/deployment/handling_failures.md
src/Documentation/deployment/toc.yml

Also changes from wording for clarity.
File was previously in the 1.5 Tutorials  section.

Move Handling Failures document to Deployment section.

---

src/Azure/OrleansAzureUtils/Directory.Build.props

Fixes #4800.
Add `Microsoft.Orleans.Streaming.AzureStorage` as a dependency to `Microsoft.Orleans.OrleansAzureUtils`.

Add Microsoft.Orleans.Streaming.AzureStorage as a dependency to AzureUtils

---

src/Azure/Orleans.Clustering.AzureStorage/AzureBasedMembershipTable.cs
src/Azure/Orleans.Clustering.AzureStorage/AzureGatewayListProvider.cs
src/Azure/Orleans.Clustering.AzureStorage/Options/AzureStorageClusteringOptions.cs
src/Azure/Orleans.Clustering.AzureStorage/Options/AzureStorageGatewayOptions.cs
src/Azure/Orleans.Clustering.AzureStorage/OrleansSiloInstanceManager.cs
src/Azure/Orleans.Hosting.AzureCloudServices/Hosting/AzureSilo.cs
src/Azure/Orleans.Reminders.AzureStorage/Storage/AzureBasedReminderTable.cs
src/Azure/Orleans.Reminders.AzureStorage/Storage/AzureTableReminderStorageOptions.cs
src/Azure/Orleans.Reminders.AzureStorage/Storage/RemindersTableManager.cs
test/Extensions/TesterAzureUtils/SiloInstanceTableManagerTests.cs

This resolves: https://github.com/dotnet/orleans/issues/4971
As it is implemented here, it solves our needs.
As far as I could see there are no validators for these options, but I can whip some up in a separate PR.
One open question: Should this also be made configurable for AzureSilo and the tests?

Add TableName to Azure Storage clustering and reminders config

---

src/Documentation/Orleans-2.0.md
src/Documentation/toc.yml

Fixes #4528 
Orleans-2.0.md was removed during the first round of reorganization. 
This adds the link to the file back to the table of contents and makes the Markdown code more compliant.

Adds Orleans-2.0 file back to table of contents and makes Markdown more compliant.

---

src/Orleans.CodeGenerator.MSBuild.Tasks/Orleans.CodeGenerator.MSBuild.Tasks.csproj

This project generates an unneeded NuGet package that we don't need to and cannot publish to nuget.org.

Prevent packaging of Orleans.CodeGenerator.MSBuild.Tasks.csproj

---

src/Orleans.CodeGenerator.MSBuild/CodeGeneratorCommand.cs
src/Orleans.CodeGenerator/Analysis/CompilationAnalyzer.cs
src/Orleans.CodeGenerator/CodeGenerator.cs
src/Orleans.CodeGenerator/Model/SerializationTypeDescriptions.cs
src/Orleans.CodeGenerator/WellKnownTypes.cs
src/Orleans.Core.Abstractions/CodeGeneration/OrleansCodeGenerationTargetAttribute.cs

Fixes #5021 
Tells the code generator to track assemblies which have already had code/metadata generated for them so that duplicate metadata is not generated.

CodeGen: Reduce duplication for assembly metadata generation

---

src/Orleans.Core.Legacy/Configuration/ClientConfiguration.cs
src/Orleans.Core.Legacy/Configuration/LegacyConfigurationExtensions.cs
src/Orleans.Core/Configuration/MessagingConfiguration.cs
src/Orleans.Core/Configuration/Options/MessagingOptions.cs
src/Orleans.Core/Core/DefaultClientServices.cs
src/Orleans.Core/Serialization/SerializationManager.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
test/TestInfrastructure/Orleans.TestingHost.Legacy/LegacyTestClusterConfiguration.cs

Add LargeMessageWarningThreshold back to Silo(Client)MessagingOptions and also legacy configuration objects

Add LargeMessageWarningThreshold back to Silo(Client)MessagingOptions

---

src/Orleans.Core/Runtime/AsynchAgent.cs
test/Grains/TestInternalGrainInterfaces/IAgentTestGrain.cs
test/Grains/TestInternalGrains/AgentTestGrain.cs
test/TesterInternal/AgentTests.cs

AsyncAgents were not restarting on fault when configured to do so.
- Added test to repro
- Fixed in AsyncAgent

Ensure AsyncAgent restarts on fault

---

src/Orleans.Core/Configuration/Options/NetworkingOptions.cs
src/Orleans.Core/Messaging/SocketManager.cs

Make MaxSockets in SocketManager configurable.
Raise the default from 200 to 500.
With clusters larger than 200 silos the hardcoded limit on the number of sockets causes massive churn of sockets that get constantly closed and reopened.

Make MaxSockets in SocketManager configurable

---

src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/AzureTableTransactionalStateStorage.cs
src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/StateEntity.cs
src/Orleans.Transactions/Abstractions/ITransactionalStateStorage.cs
src/Orleans.Transactions/State/StorageBatch.cs
src/Orleans.Transactions/State/TransactionQueue.cs
src/Orleans.Transactions/State/TransactionalStateStorageProviderWrapper.cs
test/Transactions/Orleans.Transactions.Azure.Test/FaultInjection/FaultInjectionAzureTableTransactionStateStorage.cs
test/Transactions/Orleans.Transactions.Azure.Test/GoldenPathTests.cs
test/Transactions/Orleans.Transactions.Tests/Memory/SerializationTests.cs

Participated of transaction manager and metadata are now passed to storage by structure, not string values.

Cleanup types in transaction state storage interface

---

Directory.Build.props
src/Azure/Orleans.ServiceFabric/Orleans.ServiceFabric.csproj

Increase package versions to 2.2.0, so that we don't need to update it for every patch release.
Also add a missing nuget packaging condition for Service Fabric meta-package.

Increase package versions to 2.2.0

---

src/Orleans.Core.Abstractions/Placement/PlacementStrategy.cs
src/Orleans.Core.Abstractions/Placement/StatelessWorkerPlacement.cs
src/Orleans.Runtime/Catalog/ActivationData.cs
src/Orleans.Runtime/Catalog/Catalog.cs

Changes to support placement directors which do not use the grain directory. In short, adds an `IsUsingGrainDirectory` prop to `PlacementStrategy` and removes some existing special-casing around `StatelessWorkerPlacement` being the only placement strategy which can bypass the directory.
This is a supporting PR for Service Fabric Stateful Service hosting #5073

Allow placement strategies to skip directory registration

---

src/Orleans.Core/Messaging/ClientMessageCenter.cs
src/Orleans.Runtime/Messaging/IInboundMessageQueue.cs
src/Orleans.Runtime/Messaging/InboundMessageQueue.cs
src/Orleans.Runtime/Messaging/MessageCenter.cs

In the shutdown procedure, the message center thread is blocked for waiting for
new inbound messages. Meanwhile, the shutdown procedure also dispose 
the in-used objects (BlockingCollection), which cause unexpected throw
(ArgumentNullException) in message center thread.
The original decision that avoiding passing cancellation to
`BlockingCollection.Take` was in consideration of performance.
But I can't see any regression in my benchmark program.
see also:
https://github.com/dotnet/corefx/issues/14320#issuecomment-266128170
fix #4965

IMessageCenter.WaitMessage support cancellation

---

src/Orleans.Core/Messaging/CorrelationId.cs
src/Orleans.Core/Messaging/Message.cs
src/Orleans.Runtime/Catalog/ActivationData.cs
src/Orleans.Runtime/Core/Dispatcher.cs
test/Grains/TestGrainInterfaces/IReentrancyGrain.cs
test/Grains/TestGrains/ReentrantGrain.cs
test/TesterInternal/ReentrancyTests.cs

It seems that #4382 introduced some regressions (see #5080, #5059, maybe other weird behavior).
I propose we revert it, to be able to quickly publish a new 2.1 version. We can then work to bring it back in 2.2.0 once the issue is fixed.

Revert "Don't enforce reentrancy for one way requests" #4382

---

src/Orleans.Core/Messaging/CorrelationId.cs
src/Orleans.Core/Messaging/Message.cs

My previous revert might break backward compatibility, let's restore previous version of `CorrelationId` and `Message`

Revert some revert changes to fix backward compatibility

---

src/Orleans.Core.Abstractions/Placement/PlacementStrategy.cs
src/Orleans.Core/Placement/PlacementResult.cs
src/Orleans.Runtime/Placement/PlacementDirectorsManager.cs

When grains are placed using the (upcoming) Service Fabric Stateful Service strategy, there is no grain directory involvement and hence we need a mechanism to determine which activation id to use when routing messages.
This PR enables that functionality but keeps it *`internal`* so that it will only be exposed to the SF library for now. The reasoning here is that it's unlikely anyone else will need it and if someone stumbles upon this they may opt-in to it for their placement strategy without understanding the consequences.
If `PlacementStrategy.IsDeterministicActivationId` is `true`, then all activations for a particular grain will have an `ActivationId` whose `Key` is equal to the grain's `GrainId.Key`. If `false`, then no behavior changes and `ActivationId` is randomly generated. …

Allow placement strategies to specify deterministic activation ids

---

src/docfx.json

_gitContribute branch setting needs to point to the conceptual documents, which are now in the docs branch.
https://github.com/dotnet/docfx/issues/482

Fixes "Improve this Doc Link"

---

src/Orleans.Runtime/MembershipService/MembershipOracle.cs

While it can be fine to run with this setting set to true in test environment, it's generally a very bad idea to use it in production.
This PR just add a warning when a silo tries to join a cluster with this setting enabled.

Log warning when ClusterMembershipOptions.ValidateInitialConnectivity=true

---

src/Documentation/streaming/index.md

Looks like some code was moved around at some point, correcting link.

Corrected link to sample grain for streams

---

src/Documentation/implementation/testing.md
src/Documentation/implementation/toc.yml
src/Documentation/toc.yml

PR contains the following changes:
+ unit-testing guide for v2 version has been added to the menu;
+ trailing whitespaces have been removed from the testing document;
+ the example with mocks has been fixed to reflect worker grain mock + fixed typo in `verify` method;

[Docs] Add unit-testing guide to the menu

---

src/Orleans.Core/Async/BatchWorker.cs
src/Orleans.Core/Threading/RecursiveInterlockedExchangeLock.cs
src/Orleans.Core/Timers/TimerManager.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Transactions/State/ConfirmationWorker.cs
src/Orleans.Transactions/State/TransactionQueue.cs
src/Orleans.Transactions/State/TransactionalState.cs
src/Orleans.Transactions/TOC/TocTransactionQueue.cs
src/Orleans.Transactions/TOC/TransactionCommitter.cs

This is an alternative timer implementation for use in Transactions to reduce the lock contention on the `Timer` queue caused by `Task.Delay` inside transaction management code.
How it works:
* Each thread which registers a timer does so by adding a `DelayTimer` node to a linked list of `DelayTimer` instances. That list is stored in a thread local structure, `ThreadLocalQueue`.
* `TimerManager` maintains an array of all threads' `ThreadLocalQueue` instances in `allQueues`.
* Every 50 milliseconds, a .NET `Timer` (`QueueChecker`) fires to service all queues via `CheckQueues()`. The timer enumerates all thread-local queues in `allQueues`. For each queue:
* Try to obtain a lock on the queue (using `queue.Lock`)
* If the lock fails, increment `queue.Starvation` and if the queue is starved …

Add TimerManager as Task.Delay replacement

---

src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/AzureTableTransactionalStateStorage.cs
src/Orleans.Transactions.Testkit.Xunit/TransactionalStateStorageTestRunner.cs
src/Orleans.Transactions.TestkitBase/ITestState.cs
src/Orleans.Transactions.TestkitBase/TransactionalStateStorageTestRunner.cs
test/Transactions/Orleans.Transactions.Azure.Test/AzureTransactionalStateStorageTests.cs

Adds a bunch of tests. This is not necessarily a complete suite yet, but it covers much of the (prepare/confirm/cancel) logic including some batching.

add tests to the transactional state storage test kit

---

src/Orleans.Core/Messaging/GatewayConnection.cs
test/Tester/MembershipTests/SilosStopTests.cs

`GatewayConnection` is supposed to reroute not-yet-sent message to another Gateway, and messages already sent should be forwarded by the silos that is shutting down.
Calling `MsgCenter.RuntimeClient.BreakOutstandingMessagesToDeadSilo` cause to throw `SiloUnavailbleException` to ALL pending messages.
We shouldn't do this. Not doing it may cause some timeouts, but I think it's better to gice a chance to pending request to complete instead of throwing an exception for all of them.

Don't throw SiloUnavailableException when a gateway stops

---

src/Orleans.Runtime/Core/Dispatcher.cs
test/TesterInternal/GeoClusterTests/MultiClusterRegistrationTests.cs

Fixes issue #4265.
- adjust the forward limit on messages to properly account for GSI case.
- fix a race condition in the testcase that occasionally caused the test to fail.
- re-enable the test that was being skipped.

Fix intermittent failures of MultiClusterRegistrationTests.ThreeClusterBattery

---

src/Orleans.Core/Messaging/RequestInvocationHistory.cs
src/Orleans.Runtime/Core/Dispatcher.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs

#5145 was a breaking change (my bad)
Removing the added type `RequestInvocationHistorySummary` and using the previous `RequestInvocationHistory` implementation fix the bc issue while keeping the fix from #5145

Remove RequestInvocationHistorySummary to fix backward compatibility

---

test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionalBitArrayGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/MultiStateTransactionalBitArrayGrain.cs
test/Transactions/Orleans.Transactions.Tests/Runners/TransactionRecoveryTestsRunner.cs

TransactionWillRecoverAfterRandomSiloFailure test failed on the first assert, where we send transaction request to grains for the first time, before we shutdown or kill silo. Failure are prepareTimeout and break lock. So I suspect it is because grains are taking too long to activate or grains logging are too verbose. So in order to make TransactionWillRecoverAfterRandomSiloFailure passing more consistent,  added a ping method to the grain interface and call Ping() to activate grains before transaction calls, and reduce grain logging level.

Add warm up to transaction recovery tests and reduce grain logging

---

src/Orleans.Runtime/GrainTypeManager/TypeManager.cs

Fixes #5178
**NOTE:** This is two commits, please squash/rebase to merge. Review the first commit. I did it that way to make reviewing much easier, the second commit is purely a whitespace change.
When a silo joins the cluster, other silos will not start sending new activations to it immediately. Activations will only be sent to silos after the `TypeManager` on each silo refreshes its type map. Currently that refresh is on a fixed timer (default 1 minute), but we can do better by refreshing immediately whenever a silo is added.

 Expedite TypeManager refresh upon cluster membership change 

---

src/Orleans.Runtime/Core/Dispatcher.cs

Adds the `Exception` to the existing log message.

Include exception in TryForwardRequest info log

---

src/Orleans.Runtime.Legacy/Configuration/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/Hosting/EndpointOptionsExtensions.cs
src/Orleans.Runtime/Silo/LocalSiloDetails.cs

Propagates the `ProxyGatewayEndpoint` setting from legacy `NodeConfiguration` to `EndpointOptions`. The silo-to-silo endpoint options are being propagated correctly and don't need to change.
~~`GatewayPort` is redundant and should not be used if `GatewayEndpoint` is set, but it shouldn't hurt to explicitly set it anyway.~~ EDIT: setting gateway port here `GatewayPort` wasn't redundant: it was being used to determine whether or not to start a gateway, etc. I added changes to fix that.

Support ProxyGatewayEndpoint from legacy configuration

---

src/Orleans.Core/SystemTargetInterfaces/IClusterGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/MultiClusterRegistration/ClusterGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/MultiClusterRegistration/GlobalSingleInstanceActivationMaintainer.cs
src/Orleans.Runtime/GrainDirectory/MultiClusterRegistration/RegistrarManager.cs
src/Orleans.TestingHost/SiloHandle.cs
test/TesterInternal/GeoClusterTests/GlobalSingleInstanceClusterTests.cs
test/TesterInternal/GeoClusterTests/MultiClusterRegistrationTests.cs

Fixes the problem where a global-single-instance grain becomes permanently unavailable on a cluster because its directory entry points to a remote cluster that is no longer responsive, even if that cluster has been removed from the multi-cluster.
I added tests to expose the problem behavior, and code that implements a fix.
**Tests:**
The tests use two clusters A and B, create a grain in A, then access it from B (which means cluster B now caches the reference to the grain in A). Then I block communication from A to B (to simulate cluster A going down), and change the multi-cluster configuration to remove A from the multi-cluster (to simulate an admin responding to the outage). Then I try to access the grain from B. Without the fix, this times out trying to contact a non-responding silo in …

Add GSI cache maintentance and tests

---

src/Orleans.CodeGeneration/CodeGeneratorCommon.cs
src/Orleans.CodeGeneration/RoslynCodeGenerator.cs

Fixes #5265
This is a change for the reflection-based code generator to not add GeneratedCodeAttribute at the assembly level. It's unneeded and semantically incorrect - the assembly is (probably) not just generated code.

Avoid emitting assembly-level GeneratedCodeAttribute

---

src/Orleans.CodeGeneration/Utilities/SyntaxFactoryExtensions.cs

Fixes #5244
Trivial, non-critical fix for the reflection-based code generator.

Use alias-qualified name in GetBindingFlagsParenthesizedExpressionSyntax

---

README.md

fix #5245 , #5257
update CodeGenerator from Microsoft.Orleans.OrleansCodeGenerator.Build to Microsoft.Orleans.CodeGenerator.MSBuild for working netcore 2.2

update readme.md for updating CodeGenerator package name

---

src/Orleans.Runtime/Configuration/Options/SiloMessagingOptions.cs
src/Orleans.Runtime/Messaging/IOutboundMessageQueue.cs
src/Orleans.Runtime/Messaging/MessageCenter.cs
src/Orleans.Runtime/Messaging/OutboundMessageQueue.cs
src/Orleans.Runtime/Silo/Silo.cs
test/Grains/TestGrainInterfaces/IGenericInterfaces.cs
test/Grains/TestGrains/GenericGrains.cs
test/Tester/Forwarding/ShutdownSiloTests.cs

On my local test for "forwarding messages during silo graceful shutdown", one of the reasons for message forwarding failure is 
- OutboundMessageQueue stopped before queued message being forwarded to other silo. 
The causes can be
- application messages weren't queued into OutboundMessageQueue before OutboundMessageQueue  stopped
- messages queued into OutboundMessageQueue didn't finish forwarding before it stopped
This PR tries to address the two causeses by 
- adding a 2 sec delay after `catalog.DeactivateAllActivations()`, this hopefully give enough time for the messages (queued messages for deactivated activations) to be queued into OutboundMessageQueue 
- adding a RerouteQueuedMessagesOnSiloShutdownTimeout as the max wait time for OutboundMessageQueue to finish forwarding before …

Add configurable timeout to wait for queued messages being forwarded

---

src/Orleans.Runtime/Catalog/Catalog.cs
src/Orleans.Runtime/GrainDirectory/AdaptiveDirectoryCacheMaintainer.cs
src/Orleans.Runtime/GrainDirectory/GrainDirectoryHandoffManager.cs
src/Orleans.Runtime/GrainDirectory/ILocalGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
src/Orleans.Runtime/MembershipService/MembershipOracle.cs
src/Orleans.Runtime/Silo/Silo.cs
test/Tester/Forwarding/ShutdownSiloTests.cs

- move LocalGrainDirectory stop to `silo.OnBecomeActiveStop` after `MembershipOracle.shutdown`, instead being trigged by MembershipOracleShutdown -> Sent notification to its SiloStatatusListeners about its shuttingdown -> LocalGrainDirectory.Stop(). and not awaiting the call. 
- sort out its shutdown sequence to be : 
1. exclude itself from GrainDirectoryPartition calculation, since it is shutting down and cannot serve as as GrainDirectoryPartition anymore
2. Stop Mantainers
3. GrainPartition handoff and we are awaiting this call 
4. Clear local activation cache
5. MarkStopPreparationCompleted

Sort out LocalGrainDirectory shutdown sequence

---

src/Orleans.Transactions/Abstractions/ITransactionalResource.cs

Should say `committed transaction` instead of `aborted transaction` in Confirm method documentation

Typo in documentation

---

src/Orleans.Core/LogConsistency/LogConsistentGrain.cs

Found this low hanging fruit around the Orleans.Core project.
The original intent of this code is to have two possible error messages:
1.  `$"Cannot find consistency provider with Name={attr.ProviderName} for grain type {this.GetType().FullName}"`
2.  `$"No consistency provider manager found loading grain type {this.GetType().FullName}";`
However, the wrapping `if`statement above that says:
`if (attr != null && defaultFactory == null)`
...makes the expression below to always fall into the first error message because it evaluates always to `true`, thus, making impossible for the error message to be the second one.
Furthermore, there is another safety check below that ultimately ensures `defaultFactory` is not null and throws an exception if so.

Fix defensive check in LogConsistentGrain

---

src/Orleans.Core/Serialization/BinaryTokenStreamWriter.cs
src/Orleans.Core/Utils/RuntimeTypeHandlerEqualityComparer.cs

The `BinaryTokenStreamWriter` uses dictionaries with `RuntimeTypeHandle` keys to lookup appropriate `SerializationTokenType` and serialization action for every field in an object graph. 
Since `RuntimeTypeHandle` does not implement IEquatable interface (even though it has `Equals(RuntimeTypeHandle)` method) dictionaries are using `ObjectEqualityComparer` which in turn uses `Equals(object)` and that causes a boxing allocation to occur at every lookup of a dictionary.
In this PR I'm proposing a usage of a custom `RuntimeTypeHandlerEqualityComparer` to eliminate allocation.

Optimize memory allocation with custom EqualityComparer

---

test/Extensions/ServiceBus.Tests/CollectionFixtures.cs
test/Extensions/ServiceBus.Tests/Streaming/EHClientStreamTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHImplicitSubscriptionStreamRecoveryTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHProgrammaticSubscribeTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHStreamPerPartitionTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHStreamProviderCheckpointTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHSubscriptionMultiplicityTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHSubscriptionObserverWithImplicitSubscribingTests.cs
test/TestInfrastructure/TestExtensions/TestUtils.cs

Enable EventHub streaming tests 
- will be skipped on check in 
- will be in run in vso
vso event hub connection string  updated to the new one.

Enable EventHub streaming tests

---

src/Orleans.Runtime/Messaging/IncomingMessageAcceptor.cs

When rejecting a message which was addressed to an older generation of this silo, add the target activation to the cache invalidation headers.

Invalidate activation cache entries from old epochs

---

src/Orleans.Runtime.Abstractions/Facet/Persistent/IPersistentState.cs
src/Orleans.Runtime.Abstractions/Facet/Persistent/IPersistentStateConfiguration.cs
src/Orleans.Runtime.Abstractions/Facet/Persistent/IPersistentStateFactory.cs
src/Orleans.Runtime.Abstractions/Facet/Persistent/PersistentStateAttribute.cs
src/Orleans.Runtime/Facet/Persistent/PersistentStateAttributeMapper.cs
src/Orleans.Runtime/Facet/Persistent/PersistentStateStorageFactory.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
test/Extensions/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureStore.cs
test/Extensions/TesterAzureUtils/Persistence/PersistenceStateTests_AzureBlobStore.cs
test/Extensions/TesterAzureUtils/Persistence/PersistenceStateTests_AzureTableGrainStorage.cs
test/Grains/TestInternalGrains/PersistentStateTestGrains.cs
test/TesterInternal/TestRunners/GrainPersistenceTestRunner.cs

This change Introduces a storage facet IPersistentState<T> which allows grains to define state which can be stored in using the existing IGrainStorage implementations.

Persistent state facet

---

src/Orleans.Runtime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Pulling agent could lose subscriptions if a subscription was added after the subscription cache was cleared.  We now always go to the pubsub system for subscriptions and only add new ones if the stream is active and in the pubsub cache.

Pulling agent losing subscriptions fix

---

src/Orleans.Core/Configuration/Options/LoadSheddingOptions.cs

- Must have a registered implementation of `IHostEnvironmentStatistics` for `LoadShedding` to function.

Updates XML documentation to call out prereq of `LoadShedding`.

---

src/Documentation/clusters_and_clients/configuration_guide/list_of_options_classes.md

I'm not sure if this really belongs here, but didn't see much otherwise regarding `LoadShedding` in the docs.  `LoadShedding` appears to only be functional once a `IHostEnvironmentStatistics` implementation has been registered - calling that out in the "Used for" column.

Prereqs information for `LoadSheddingOptions`

---

src/Azure/Orleans.Hosting.AzureCloudServices/Hosting/AzureClient.cs
src/Azure/Orleans.Hosting.AzureCloudServices/Hosting/AzureSilo.cs
src/Orleans.Core.Legacy/Configuration/ClientConfiguration.cs
src/Orleans.Core.Legacy/Configuration/ClusterConfiguration.cs
src/Orleans.Core.Legacy/Configuration/GlobalConfiguration.cs
src/Orleans.Core.Legacy/Configuration/NodeConfiguration.cs
src/Orleans.Core.Legacy/Core/GrainClient.cs
src/Orleans.Core.Legacy/Orleans.Core.Legacy.csproj
src/Orleans.PowerShell/StartGrainClient.cs
src/Orleans.Runtime.Legacy/Hosting/SiloHost.cs
src/Orleans.Runtime.Legacy/Orleans.Runtime.Legacy.csproj
src/Orleans.Runtime/Silo/Silo.cs
test/Directory.Build.props

Fixes #5221
I disabled legacy type warnings for the `test` subtree, maybe that's questionable. The alternative is to either:
1. Port all tests away from `[Obsolete]` types
2. Individually mark every file with the right `#pragma` incantation
3. Individually surround every usage with the right `#pragma`
I figured:
* 1 is too much work for now (especially between rc and final)
* 2 offers little benefit over the chosen approach with more cost
* 3 would make code ugly since it requires many changes which will eventually need to be undone before (presumably) 3.0.

Mark key legacy types/methods as [Obsolete]
