src/Orleans/Configuration/ConfigUtilities.cs

Currently, ConfigUtilities.ParseTimeSpan parses values into a string before multiplying them into milliseconds and passing them into TimeSpan.FromMilliseconds, which expects a double.
Multiplying the parsed value into milliseconds can cause it to overflow, resulting in a negative TimeSpan.
By parsing directly into double, these overflows can be largely avoided.

ConfigUtilities.ParseTimeSpan overflows too easily: use double instead of int

---

src/OrleansAzureUtils/AzureClient.cs

Changed fields MaxRetries and TimeSpan to read-only.

fix warning CA2211 in AzureClient

---

src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamProvider.cs

Removed an unnecessary check for null reference which is causing a warning during compilation:
CS0472: The result of the expression is always 'false' since a value of type 'System.Guid' is never equal to 'null'.

Fix for warning CS0472: The result of the expression is always 'false' 

---

src/Orleans/Core/GrainExtensions.cs

A convenience method (and for completeness) to get a grain's primary key as a string when the grain inherits `IGrainWithStringKey`.

added extension method to get a grain's primary key as a string

---

src/OrleansProviders/Storage/HierarchicalKeyStore.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs
src/OrleansRuntime/Silo/Silo.cs

This commit fixes warning CA2002. HierarchicalKeyStore extends
MarshalByRefObject which allows code code running in one AppDomain
to lock on an object in another AppDomain. Fix is to lock on a private
object which only HierarchicalKeyStore is knowledgeable about.

Fix warning CA2002: Do not lock on objects with weak identity

---

src/TestGrains/SimpleGrain.cs
src/TestGrains/SimpleObserverableGrain.cs

The third argument wasn't referenced.

Fixed a typo in string format

---

README.md

- Add details of the Contributing Guidelines for .NET projects on GitHub.
- Add pointer to the .NET Framework Design Guidelines.
- Add link to the original MSR Project Orleans web pages, for historical context.

ReadMe - .NET Contribution Guides

---

README.md

The .NET Developer Guide might be confusing in relation to Orleans due
to current use of mstest rather than xunit.

Drop Link to Developer Guide

---

src/Orleans/Logging/TraceLogger.cs

Minor formatting change... just something I noticed and jumped in on. Thanks!

Fixed spelling error (trancated -> truncated) and reformatted call to String.Format().

---

src/OrleansProviders/SQLServer/CreateTables.sql
src/OrleansRuntime/ReminderService/SqlReminderTable.cs

The hash is an unsigned integer in the grain, but was previously represented as
an integer in the SQL script. This caused an ArgumentException when
DbType.UInt32 was attempted to be converted to an SqlDbType as there is no
mapping from DbType.UInt32 to a corresponding SqlDbType value.
To accomodate the unsigned integer, the hash in the reminder table has been
changed to a bigint, and the calling code now uses DbType.Int64 instead.

SqlReminderTable: Fix hash type mapping to database (issue12)

---

src/Orleans/Configuration/ClientConfiguration.cs

ClientConfiguration.Load
- Make ClientConfiguration.Load method public, so that it is symmetrical
with ClusterConfiguration.Load.

ClientConfiguration.Load

---

src/OrleansProviders/SQLServer/CreateTables.sql
src/OrleansRuntime/ReminderService/SqlReminderTable.cs

The use of 64-bit integers in SQL Server has been reduced to 32-bit signed
integers by casting the grain hashes to int as there is no external dependencies
to the SqlReminderTable that depends on the values.
Fixes #12.
Supercedes change from unsigned 32-bit integers to 64-bit signed integers in
77ba17804a67b2948dc7043805b1b41804d92474.
Updated with comments from @gabikliot on https://github.com/dotnet/orleans/pull/52. Tested manually in project using SqlServer-based reminder service.

SqlReminderTable: Reduce storage requirement for hashes

---

README.md

We are re-arranging the flow of our readme files in .NET Core land, preferring engagement oriented content to come before license info. Here is a PR to apply that approach to Orleans.

Improve flow of readme

---

src/Build.cmd
src/Test.cmd

- Allow Build.cmd and Test.cmd to be run from Git Shell when
GitForWindows shell option is set to use PowerShell [+PoshGit]
- Add quotes around EXE paths to avoid any problems with spaces in
directory names.
- Use full path for MsTest.exe
- Run tests against the Release build rather than Debug, because that is
what people will most likely want to install.

Allow Build.cmd to run in GfW PowerShell

---

src/.gitignore
src/Orleans/Configuration/ProviderConfiguration.cs

Don't add a property to provider configuration if it is already there.
The bug was exposed by our internal unit test that adjusted the stream provider configuration to add a storage account key.
The change to .ignore was committed by mistake, but it doesn't really matter. I can't undo it now. Will be more careful next time.

Fix add to configuration

---

src/Build/OrleansSetup.wxs

Added Newtonsoft.Json.dll to SDK because OrleansProviders.dll has a dependency on it.

Added Newtonsoft.Json.dll to SDK

---

src/TestAll.cmd

CI tests should be short and have no external dependencies (like on Azure Storage emulator). 
Thus modified Test.cmd, that runs automatically in CI, to run only BVT tests.
Add  a new file TestAll.cmd to run all tests.

Modify Test.cmd to run only BVT tests (runs automatically in CI). Add TestAll.cmd to run all tests.

---

src/ClientGenerator/VBCodeGenerator.cs

I've updated the VBCodeGeneratortor replace an invalid line which doesn't compile.
Simple switch Sub to Function to match the c# version of the C#CodeGenerator

Changed Sub to Function in codegen to match c# version.

---

src/TesterInternal/OrleansRuntime/Streams/BestFitBalancerTests.cs
src/TesterInternal/StorageTests/AzureMembershipTableTests.cs
src/TesterInternal/StorageTests/AzureQueueDataManagerTests.cs
src/TesterInternal/StorageTests/AzureTableDataManagerTests.cs
src/TesterInternal/StorageTests/AzureTableErrorCodeTests.cs
src/TesterInternal/StorageTests/SiloInstanceTableManagerTests.cs
src/TesterInternal/StorageTests/StorageTestConstants.cs
src/TesterInternal/StorageTests/UnitTestAzureTableDataManager.cs
src/TesterInternal/TesterInternal.csproj

Include the test cases in AzureTableErrorCodeTests in the BVT suite,
because they all run locally and have no external dependency on Azure
storage.

Include AzureTableErrorCodeTests in BVT

---

src/Build/PostBuild.cmd
src/NuGet/ClientInstall.ps1
src/NuGet/Microsoft.Orleans.Client.nuspec
src/NuGet/Microsoft.Orleans.Server.nuspec
src/NuGet/Microsoft.Orleans.Templates.Grains.nuspec
src/NuGet/Microsoft.Orleans.Templates.Interfaces.nuspec
src/NuGet/ServerInstall.ps1
src/Orleans.sln

Fix <i>Microsoft.Orleans.Templates.Grains</i> and <i>Microsoft.Orleans.Templates.Interfaces</i> nuspecs to import targets and props to the target project.
Fix <i>Microsoft.Orleans.Client</i> and <i>Microsoft.Orleans.Server</i> nuspecs to copy configuration files to the root of target project

Fix nuspecs

---

Build.cmd
Test.cmd
TestAll.cmd
src/Test.cmd
src/TestAll.cmd

- For easier discovery, add Build.cmd and Test.*cmd scripts at root of
repo which just redirect to the "real" ones in src/ directory.
- Combine test cases from Tester.dll and TesterInternal.dll into a
single MsTest.exe run, for easier tracking.

Build-scripts

---

src/Orleans.SDK.targets

MSBuild-HasTrainlingSlash
- The value passed to HasTrainlingSlash() [and Exists()] should be
enclosed in single quotes according to
https://msdn.microsoft.com/en-us/ibrary/7szfhaft.aspx
- Remove some spurious colon character cruft.

MSBuild-HasTrainlingSlash

---

src/Orleans/Orleans.csproj

Build-XmlPeek
- Remove use of XmlPeek because it is not supported by mono xbuild, and
replace by use of explicit ItemGroup / PropertyGroup code instead.

Build-XmlPeek

---

src/Orleans.SDK.targets
src/Orleans/Orleans.csproj

[No functional changes]
- For clarity, rename "client-gen" related comments and variables in build scripts to be "code-gen tool"
- Code-gen exe name remains unchanged for now - ClientGenerator.exe

CodeGenTool Build Script Variable Names

---

src/Orleans/IDs/GuidId.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/GrainReference.cs
src/Orleans/Serialization/BinaryTokenStreamReader.cs
src/TesterInternal/General/Identifiertests.cs

Added support for an additional ObserverId to be stored inside GrainReference.
This is the next step in the bigger feature of improving Observers scalability and perf.

Added support for Observers in GrainReference.

---

src/Build/PostBuild.cmd
src/NuGet/CreateOrleansPackages.bat
src/Tester/Tester.csproj

- Make NuGet package creation fail the build if it fails
- Removes the extra copy from /Binaries/Release/*.nupkg to
/Binaries/NuGet.Packages/ to prevent excess disk I/O
- Only build NuGet packages from within Build.cmd (not within Visual
Studio). Decreases the build time withing Visual Studio. Packages built
within Visual Studio weren't correct anyways (they were missing
*.exe.config)

NuGet package build improvements

---

src/ClientGenerator/CSharpCodeGenerator.cs
src/ClientGenerator/ClientGenerator.cs
src/ClientGenerator/CodeGeneratorBase.cs
src/ClientGenerator/FSharpCodeGenerator.cs
src/ClientGenerator/NamespaceGenerator.cs
src/ClientGenerator/Serialization/SerializationGenerator.cs
src/ClientGenerator/Serialization/SerializerGenerationManager.cs
src/ClientGenerator/VBCodeGenerator.cs
src/Orleans/CodeGeneration/GrainInterfaceData.cs
src/Orleans/CodeGeneration/Language.cs
src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/Orleans.csproj

To fix VB code generation bugs (issue #43), a Language parameter was added to many of the TypeUtils methods and
CodeGeneration language files.
Reproduced and resolved cases mentioned in bug.

Code generation VB fixes #43

---

src/Orleans/Configuration/ProviderConfiguration.cs

Basically, made one method public instead of internal plus protection against null ref in a couple of places.

Minor tweaks to allow to programmatically configure providers.

---

src/OrleansVSTools/OrleansVSTools/source.extension.vsixmanifest

* support Visual Studio 2015
* support .NET 4.6 (otherwise it won't install on Windows 10 by default)
* fix the extension title (not only for Visual Studio 2012)

Update Visual Studio Extension manifest:

---

src/ClientGenerator/ClientGenerator.cs
src/Orleans.SDK.targets

* [Orleans.SDK.targets] add a case in FSharpCompilerPath resolution
* [ClientGenerator.cs] output error message when fsharp compiler path is not set when /fsharp: argument is passed but don't have any value

ClientGenerator support for F# 4.0 / Visual Studio 2015

---

src/Build.cmd

- Specify main solution file in one place.
- Fix some quoting and param insonsistencies in Build.cmd
- Only build VSIX and WIX packages from Release bits.

Clean up Build.cmd script

---

src/ClientGenerator/ClientGenerator.csproj
src/CounterControl/CounterControl.csproj
src/Orleans/Orleans.csproj
src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansHost/OrleansHost.csproj
src/OrleansHost/packages.config
src/OrleansManager/OrleansManager.csproj
src/OrleansProviders/OrleansProviders.csproj
src/OrleansRuntime/OrleansRuntime.csproj
src/TestGrainInterfaces/Properties/AssemblyInfo.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/Properties/AssemblyInfo.cs
src/TestGrains/TestGrains.csproj
src/Tester/Properties/AssemblyInfo.cs
src/Tester/Tester.csproj
src/TesterInternal/Properties/AssemblyInfo.cs
src/TesterInternal/TesterInternal.csproj

- Clean out various old cruft from the .csproj files and normalize contents for consistency.
- Use same ProductVersion and ToolsVersion in all proj files.
- Remove blank TFS Scc* elements no longer used.
- Include GlobalAssemblyInfo.cs in all projects, for common assembly attributes.
- Specify assembly references to NuGet packages the same way they would be if added as new package entry [No explicit version number info in the assembly name which is then undone by SpecficVersion=False --> the HintPath is the thing that points to the version we use.]
- Remove empty elements, for example ApplicationIcon.
- Added packages.config to OrleansHost for consistency, ready for later use [will be in separate PR]
- Remove old NET45_OR_GREATER define constants no longer required.
- Turn on package …

Csproj Cleanup

---

src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs

Also fixed a bug in the init logic InitImplicitStreamSubscribers.

Do not serialize the GrainFactory.Cast<IStreamConsumerExtension> function in ImplicitStreamSubscriberTable

---

src/NuGet/Microsoft.Orleans.OrleansProviders.nuspec

Removed dependency on Microsoft.Orleans.Runtime, as OrleansProviders.dll does not depend on OrleansRuntime.dll anymore.

Removed dependency on Microsoft.Orleans.Runtime

---

src/OrleansAzureUtils/AzureSilo.cs
src/OrleansRuntime/Silo/SiloHost.cs

@javier-alvarez reported that this improved the silo startup time significantly in his deployment.
This setting controls the exponential backoff algorithm in the membership oracle, significantly reduces contention on the Azure Silo Instance table and improves start up time for large deployments.

SetExpectedClusterSize in AzureHost to the number of instances in the current role.

---

src/ClientGenerator/NamespaceGenerator.cs
src/Orleans/Runtime/GrainReference.cs

Make GrainReference.InterfaceName property public instead of protected, so other application code can extract InterfaceName from it.
Asked by @jesuspsalas.

Make GrainReference.InterfaceName property public instead of protected, so other application code can extract InterfaceName from it.

---

src/NuGet/Microsoft.Orleans.OrleansAzureUtils.nuspec
src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansAzureUtils/packages.config
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/packages.config
src/Tester/Tester.csproj
src/Tester/packages.config

Downgrade dependency on Microsoft.WindowsAzure.ServiceRuntime from 2.5 to 2.4 to be consistent with the "-1" rule for Azure SDK dependencies. We recently ran into issues upgrading Orleans-based solutions because of this version inconsistency.

Downgrade dependency on Microsoft.WindowsAzure.ServiceRuntime to 2.4

---

src/ClientGenerator/ClientGenerator.csproj
src/CounterControl/CounterControl.csproj
src/Orleans.sln
src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansHost/OrleansHost.csproj
src/OrleansManager/OrleansManager.csproj
src/OrleansProviders/OrleansProviders.csproj
src/OrleansRuntime/OrleansRuntime.csproj
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/TestGrains.csproj
src/Tester/Tester.csproj
src/TesterInternal/TesterInternal.csproj

- Remove direct 'include' dependencies on the ClientGenerator project which are not required at compile time.
- Ensure project build order is set correctly so that ClientGenerator project is always built before any projects that need to run it for a code-gen build step.
- Remove unused references in projects, as suggested by ReSharper, except where reference is pulled in as a NuGet sub-dependency from WindowsAzure.Store package reference.
- This seems to give a small but significant reduction in build time [on my machine at least].

Project build dependencies and references

---

src/Orleans/Streams/Providers/StreamProviderManager.cs

The IStreamProviderImpl is an internal interface - not accessible to stream provider implementers. 
Since only internal Orleans providers can (and do) implement IStreamProviderImpl, attempting to call Start() on stream providers implemented outside Orleans binaries crashes the silo at start-up.

Call Start() only for stream providers that implement IStreamProviderImpl

---

Samples/AzureWebSample/OrleansAzureSilos/OrleansAzureSilos.csproj
Samples/HelloWorldNuget/HelloWorldNuget.sln
Samples/HelloWorldNuget/HelloWorldNuget/App.config
Samples/HelloWorldNuget/HelloWorldNuget/DevTestClientConfiguration.xml
Samples/HelloWorldNuget/HelloWorldNuget/DevTestServerConfiguration.xml
Samples/HelloWorldNuget/HelloWorldNuget/HelloWorldNuget.csproj
Samples/HelloWorldNuget/HelloWorldNuget/OrleansConfiguration.xml
Samples/HelloWorldNuget/HelloWorldNuget/OrleansConfiguration.xsd
Samples/HelloWorldNuget/HelloWorldNuget/OrleansHostWrapper.cs
Samples/HelloWorldNuget/HelloWorldNuget/Program.cs
Samples/HelloWorldNuget/HelloWorldNuget/Properties/AssemblyInfo.cs
Samples/HelloWorldNuget/HelloWorldNuget/packages.config
Samples/HelloWorldNuget/HelloWorldNugetGrains/ClientConfiguration.xml
Samples/HelloWorldNuget/HelloWorldNugetGrains/HelloGrain.cs
Samples/HelloWorldNuget/HelloWorldNugetGrains/HelloWorldNugetGrains.csproj
Samples/HelloWorldNuget/HelloWorldNugetGrains/Properties/AssemblyInfo.cs
Samples/HelloWorldNuget/HelloWorldNugetGrains/packages.config
Samples/HelloWorldNuget/HelloWorldNugetInterfaces/ClientConfiguration.xml
Samples/HelloWorldNuget/HelloWorldNugetInterfaces/HelloWorldNugetInterfaces.csproj
Samples/HelloWorldNuget/HelloWorldNugetInterfaces/IHello.cs
Samples/HelloWorldNuget/HelloWorldNugetInterfaces/Properties/AssemblyInfo.cs
Samples/HelloWorldNuget/HelloWorldNugetInterfaces/packages.config
Samples/README.txt

Adds HelloWorldNuget example to the repository
This PR adds HelloWorldNuget example to use the publicly available
1.0.3 Nuget packages. Other than the Nuget packages and the hello
message this is exactly the same example as the HelloWorld one based
on the MSI package.
* This makes verifying #174 easy as the sample is small. First the silo
starts, after running "Update-Package" from the Package Manager
Console the silo won't start anymore.
* This uses the current Nugets which have a dependency to Azure SDK 2.5.
It may be necessary to update this example after the new packages are public.
* This conversion may help others with issues as described in #192, with
reference to conversion instructions currently at
https://github.com/dotnet/orleans/wiki/Convert-Orleans-v0.9-csproj-to-Use-v1.0-NuGe …

Ports HelloWorld sample to use Nuget packages

---

Samples/AzureWebSample/OrleansAzureSilos/OrleansAzureSilos.csproj
Samples/AzureWebSample/OrleansAzureSilos/OrleansConfiguration.xml
Samples/AzureWebSample/OrleansAzureSilos/WorkerRole.cs

Examples of how to configure providers programmatically.
3 examples of a code to change an existing storage provider configuration, add a new storage provider configuration and add a new bootstrap provider configuration.
Follow from issue #19.

Examples of how to configure providers in Azure Web Sample.

---

src/Orleans/Logging/ConsoleText.cs
src/Orleans/Orleans.csproj
src/OrleansHost/OrleansHost.csproj
src/OrleansManager/OrleansManager.csproj
src/OrleansProviders/OrleansProviders.csproj
src/Tester/Tester.csproj

Avoid some unnecessary rebuilds being forced during F6 incremental build
due to CopyAlways=True on some static files.
This change gets things to the stead state of 4 projects force rebuild
and 8 up-to-date for normal F6 incremental builds in VS.
Remaining 4 forced rebuilts occur from this error symptom in build log:
1>Project 'OrleansRuntime' is not up to date. Error (0x8000FFFF).

Avoid extra forced project rebuilds during Incremental

---

src/Orleans.SDK.targets

Touch - orleans.codegen.cs 
- Pre-create the orleans.codegen.cs file otherwise a new project created from Orleans VSIX templates will not build first time [CSC complains about missing file]

Touch - orleans.codegen.cs

---

src/Build/PostBuild.cmd

- Don't generate NuGet packages in Debug builds. Only the Release versions are ever used.
- Also still allow NuGet package creation to be disabled for Release build through the BuildOrleansNuGet build variable.

Don't Generate NuGet Pkgs for Debug Builds

---

src/Orleans/Streams/PersistentStreams/StreamConsumerCollection.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs

This is part of preparation towards changing AsReference to be strongly typed.

Cleanup redundant usages of "public static GrainReference AsReference(this Runtime.IAddressable grain)".

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/AssemblyLoader/CachedReflectionOnlyTypeResolver.cs

Apply binding redirect policy before loading an assembly into reflection-only context.
Try to pre-load all dlls in the target folder into reflection-only context as a workaround for ReflectionOnlyLoad/ReflectionOnlyLoadFrom not resolving them properly.

Applying of binding redirectys & a fix for reflection-only assembly load

---

Samples/HelloWorld/HelloWorld/Program.cs
Samples/HelloWorldNuget/HelloWorldNuget/Program.cs

- Add #define USE_INPROC_SILO to make it easier to swithc from in-process to external standalone silo demo.
- Based on user feedback on http://dotnet.github.io/orleans/Step-by-step-Tutorials/Running-in-a-Stand-alone-Silo

HelloWorld-USE_INPROC_SILO

---

src/Orleans/Configuration/ClientConfiguration.cs

- Fix build warning about api-doc comments on ClientConfiguration.RegisterStreamProvider method.

codedocs-ClientConfiguration

---

Samples/AzureWebSample/OrleansAzureSilos/WorkerRole.cs
src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Configuration/ProviderConfiguration.cs
src/Orleans/Providers/IOrleansProvider.cs

1) Added: TryGetProviderConfiguration and GetAllProviderConfigurations
2) Added constructor to ProviderConfiguration class.
3) Added more functions to IProviderConfiguration: Type, SetProperty, RemoveProperty, ReadOnlyDictionary<string, string> Properties.
4) Updated examples in AzureWebSample.
The important new parts are in:
1) IProviderConfiguration.cs
2) public bool TryGetProviderConfiguration(string providerTypeFullName, string providerName, out IProviderConfiguration config) 
3) public IEnumerable<IProviderConfiguration> GetAllProviderConfigurations()

More programmatic support to provider configuration.

---

src/Orleans/Configuration/ClusterConfiguration.cs
src/OrleansRuntime/Core/ManagementGrain.cs

There are (at least) two mild resource leaks:
* [ManagementGrain on line 187](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Core/ManagementGrain.cs#L187) doesn't dispose the writer objects.
* [ClusterConfiguration on line 148](https://github.com/dotnet/orleans/blob/master/src/Orleans/Configuration/ClusterConfiguration.cs#L148) doesn't dispose the writer objects.
Fixes #256.
I also ran a few regex searches and didn't find any others.

Fix to ClusterConfiguration and ManagementGrain resource leaks

---

src/Tester/Tester.csproj
src/TesterInternal/TesterInternal.csproj

- Move the call to PostBuild.cmd from Tester to TesterInternal project because that has build order dependency on Tester.
Failure symptoms:
Building the WIX installer fails to find OrleansConfiguration.xml during first-time build of fresh checkout or after deleting the Binaries output directory.

Call PostBuild.cmd from final project built in solution.

---

src/Tester/StreamingTests/SMSSubscriptionMultiplicityTests.cs

Failure mode:
StreamingTests\SMSSubscriptionMultiplicityTests.cs(53,32): warning CS0109:
The member 'Tester.StreamingTests.SMSSubscriptionMultiplicityTests.MyClassCleanup()' does not hide an inherited member. The new keyword is not required.

Fix build warning in SMSSubscriptionMultiplicityTests.cs

---

src/Orleans/Streams/Core/IAsyncStream.cs
src/Orleans/Streams/Internal/IInternalAsyncObservable.cs
src/Orleans/Streams/Internal/StreamConsumer.cs
src/Orleans/Streams/Internal/StreamImpl.cs
src/Orleans/Streams/Internal/StreamSubscriptionHandleImpl.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans/Streams/Providers/IStreamProviderRuntime.cs
src/Orleans/Streams/PubSub/IPubSubRendezvousGrain.cs
src/Orleans/Streams/PubSub/PubSubRuntime.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs
src/TestGrainInterfaces/IMultipleSubscriptionConsumerGrain.cs
src/TestGrains/MultipleSubscriptionConsumerGrain.cs
src/Tester/StreamingTests/SMSSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/SubscriptionMultiplicityTestRunner.cs

The new IAsyncStream.GetAllSubscriptionHandles call returns the list of active subscription handles that the caller currently has on the stream.  This is useful in recovering after silo crashes scenarios or other errors.  It is also useful for stream processing grains that do not wish to persist state.

Added GetAllSubscriptionHandles to IAsyncStream

---

src/Tester/Tester.csproj
src/TesterInternal/TesterInternal.csproj

Minor cleanup in TesterInternal.csproj
- Mark TesterInternal.csproj as a Test project type, same as Tester.csproj.

Mark TesterInternal.csproj as a Test project type

---

Step-by-step-Tutorials/My-First-Orleans-Application.md
_config.yml
_includes/themes/twitter/default.html
assets/themes/twitter/css/syntax.css

Current version of Orleans documentation on github pages does not have source code syntax highlighting enabled. I've made a few changes so it can be added:
- changed default markdown rendering engine to "redcarpet" as [AFAIK](https://github.com/blog/832-rolling-out-the-redcarpet) it is a precursor of the engine used on github (however, not in github pages by default) and [set some options](http://stackoverflow.com/a/28114624/3568443) to make it close to the one from github.
- added simple css file for syntax highlighter similar to default Visual Studio style. I used following command:
```pygmentize -S vs -f html > assets/themes/twitter/css/syntax.css```
- set csharp syntax for highlighter on My-First-Orleans-Application page to prove it worked
You can check final effect …

Prepare syntax highlighting in orleans documentation on github pages.

---

Advanced-Concepts/Activation-Garbage-Collection.md
Advanced-Concepts/Application-Bootstrap-within-a-Silo.md
Advanced-Concepts/Configuring-.NET-Garbage-Collection.md
Advanced-Concepts/Timers-and-Reminders.md
Convert-Orleans-v0.9-csproj-to-Use-v1.0-NuGet.md
Orleans-Configuration-Guide/Client-Configuration.md
Orleans-Configuration-Guide/Server-Configuration.md
Orleans-Configuration-Guide/Typical-Configurations.md

Pygments syntax highlighter also supports xml code (although in a kind of limited way). I added it for some documentation files. I've also normalized xml indentation in a few places (to use 2 spaces as it seems to be most frequently used value and it is a default setting in VS).
Example: https://ksuszka.github.io/orleans/Orleans-Configuration-Guide/Typical-Configurations

Enable syntax highlighing on more files (mostly for xml snippets)

---

src/OrleansAzureUtils/AzureConfigUtils.cs

The code was throwing an exception in my client (a WorkerRole) because HttpContext.Current is null.
I think the fix is simple (just add a check for null). Since these directory locations are just a  best-effort search, there is no harm in excluding one of the locations.

avoid NullReferenceException in FindAppDirectoryLocations()

---

src/Orleans/Configuration/ConfigUtilities.cs

That was a fun one!
We had the check for minimal allowed Activation CG AgeLimit  when config is loaded (causing silo to fail to start early if misconfigured), but the check was performed only under DEBUG for some reason. As a result silo started misconfigured and was failing to activate new grains later on.

Re-enabled check for minimal allowed Activation CG AgeLimit that was enabled only in DEBUG mode.

---

README.md

The image shows the latest version of Microsoft.Orleans.Core package, while the link points to all NuGets. Not sure if this is the right way. Maybe it would be better if the link pointed to Microsoft.Orleans.Core.
[Copied from https://github.com/Microsoft/bond/blob/master/README.md]

Added direct link to Orleans NuGets.

---

src/Orleans/Orleans.csproj
src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs
src/Orleans/Streams/PubSub/PubSubRuntime.cs
src/Orleans/Streams/PubSub/SubscriptionMarker.cs
src/TesterInternal/OrleansRuntime/Streams/SubscriptionMarkerTests.cs
src/TesterInternal/TesterInternal.csproj

Implicit subscription Ids are currently the same as the streamId's guid.  This will break if there is more than one grain configured to implicitly subscribe to a stream with the same namespace.  To solve this, we generate implicit subscription ids unique per streamId (Guid and namespace) + grainTypeCode combination.

generate implicit subscription ids

---

src/ClientGenerator/CSharpCodeGenerator.cs
src/ClientGenerator/VBCodeGenerator.cs

Fixed handling of generic parameter names in the generated code that converts references to grain activation objects into grain references. This is a fix for https://github.com/dotnet/orleans/issues/287.
Updated the previous version of this PR with support for generic types used as type arguments.

Fixed handling of generic parameter names

---

src/Orleans/AzureUtils/OrleansSiloInstanceManager.cs
src/Orleans/SystemTargetInterfaces/IMembershipTable.cs
src/OrleansRuntime/MembershipService/AzureBasedMembershipTable.cs
src/TesterInternal/StorageTests/SiloInstanceTableManagerTests.cs
src/TesterInternal/TesterInternal.csproj

Removed a Primary column in Silo Instance table.
It was deprecated years ago, but never removed. Found it while writing documentation for Runtime table.
In Orleans, all silos are equal, but some are more equal than others.

Removed a Primary column in Silo Instance table.

---

src/Orleans/Configuration/ClusterConfiguration.cs

Handle the case when Dns.GetHostName returns "localhost", which appears to have happened in https://orleans.codeplex.com/discussions/616249.

Handle the case when Dns.GetHostName returns "localhost"

---

src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs
src/Orleans/Streams/PubSub/PubSubRuntime.cs

Stream PubSub system was returning the wrong subscriptionId to stream producers for Implicit subscriptions.
Stream PubSub system now creates the correct subsriptionId

Bugfix: Stream PubSub system now creates the correct subsriptionId.

---

src/Orleans/Configuration/MessagingConfiguration.cs
src/Orleans/Messaging/BufferPool.cs
src/Orleans/Serialization/SerializationManager.cs
src/Tester/SerializationTests.cs
src/Tester/Tester.csproj

Addresses https://github.com/dotnet/orleans/issues/299.

Serialization test for JObject

---

src/Orleans/Streams/PersistentStreams/StreamQueueBalancerType.cs
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Streams/QueueBalancer/AzureDeploymentConfiguration.cs
src/OrleansRuntime/Streams/QueueBalancer/DeploymentBasedQueueBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/IDeploymentConfiguration.cs
src/OrleansRuntime/Streams/QueueBalancer/StaticClusterDeploymentConfiguration.cs
src/OrleansRuntime/Streams/QueueBalancer/StreamQueueBalancerFactory.cs

Added new type of deployment configuration for DeploymentBasedQueueBalancer, StaticClusterDeploymentConfiguration.
Added new queue balancer type, StaticClusterDeploymentBalancer, which uses cluster configuration to balance queues.
Made queue balancer types public so stream provider configurations can set them.

Cluster deployment queue balancer

---

src/ClientGenerator/CSharpCodeGenerator.cs
src/ClientGenerator/VBCodeGenerator.cs
src/Orleans/CodeGeneration/GrainInterfaceData.cs
src/Orleans/Core/GrainAttributes.cs
src/Orleans/Core/IGrain.cs
src/Orleans/Streams/PubSub/IPubSubRendezvousGrain.cs

Removed the ExtendedPrimaryKeyAttribute class
and replaced it with a couple of IGrainWithCompoundKey
interfaces to unify the API and remove the inconsistency
with the new design.
Fix #326

Change ExtendedPrimaryKey to IGrainWith Interface

---

src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs

Clear ```PubSubRendevousGrain``` state from storage when there are no consumers or subscribers.
Helpful when using a large number of transient, one-time-use, streams.

Clear empty PubSubRendevousGrain state from storage

---

src/OrleansAzureUtils/AzureConfigUtils.cs

1) Hardened the code against potential null ref exception (put every location search attempt into a try catch). Otherwise, lazy evaluated IEnumarble may throw null ref exception which is hard to debug.
2) Add more locations to search at, as suggested by @ReubenBond and @maiorfi in https://github.com/dotnet/orleans/issues/323.
Fixes https://github.com/dotnet/orleans/issues/323

Fix potential Null Ref Exception in AzureConfigUtils.ClientConfigFileLocation and also add more places to search.

---

src/Orleans/CodeGeneration/GrainFactoryBase.cs
src/Orleans/Core/GrainFactory.cs
src/Orleans/IDs/TypeCodeMapper.cs
src/Orleans/Streams/PubSub/PubSubRuntime.cs

Added 2 new overloads, as discussed in https://github.com/dotnet/orleans/pull/330
* Removed code duplication between GrainFactory and TypeCodeMapper (not clear why it was duplicated). More opportunities to cleanup exist there.
* Ported PubSubGrain to use the new factory method, which validated the approach.
* Interestingly, the compiler could not automatically pick the right overload. It got confused between IGrainWithGuidKey (Guid, string = null) and IGrainWithGuidCompoundKey (Guid, string, string=null) overload, since they have similar args (2nd arg is string). I had to help it with explicit arg names.

Support ExtendedPrimaryKey GetGrain from generic Factory.

---

src/Orleans/CodeGeneration/GrainFactoryBase.cs
src/Orleans/Core/GrainFactory.cs

GrainFactory is a generic factory used to create grain references.
GrainFactoryBase is a base class used by all code generated concrete factories to create grain references.
Both factories are very similar.
The main logic is in method GrainFactory_MakeGrainReference which is almost identical to GrainFactoryBase.MakeGrainReference. Therefore:
1) I moved GrainFactory_MakeGrainReference into GrainFactoryBase and renamed to GrainFactoryBase.MakeGrainReference_FromType
2) The only difference now between GrainFactoryBase.MakeGrainReference_FromType and the old GrainFactoryBase.MakeGrainReference is that the former used the Interface Type while the latter used the Interface Id hash code.
3) But both ways are actually equivalent! Therefore, changed MakeGrainReference  to use the Type and not to …

Cleaning up the code duplication in GrainFactory.

---

src/ClientGenerator/CSharpCodeGenerator.cs
src/Orleans/Runtime/GrainReference.cs
src/Orleans/Serialization/BuiltInTypes.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Serialization/TypeUtilities.cs
src/Orleans/SystemTargetInterfaces/IMembershipTable.cs

Implemented a number of optimizations in the serialization code:
1) Removed a duplicate call to IsOrleansShallowCopyable
2) Optimized grain methods with zero args to code gen null instead of zero size object array, which speeds up a bunch of code paths.
3) Optimized t.GetCustomAttributes(typeof (ImmutableAttribute)) to use t.GetCustomAttributesData.

Serialization code optimizations

---

src/Orleans/CodeGeneration/GrainFactoryBase.cs
src/Orleans/IDs/TypeCodeMapper.cs
src/Orleans/Runtime/GrainInterfaceMap.cs
src/OrleansManager/Program.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs
src/TestGrainInterfaces/IGenericGrain.cs
src/TestGrainInterfaces/ISimpleGenericGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/ConcreteGrainsWithGenericInterfaces.cs
src/TestGrains/SimpleGenericGrain.cs
src/TestGrains/SpecializedSimpleGenericGrain.cs
src/TestGrains/TestGrains.csproj
src/Tester/GenericGrainTests.cs
src/Tester/Tester.csproj

Fixes #338, Replaces #342
Hi guys, this a one-commit version  of #342, with further changes and tests addressing a couple of edge cases. The one significant change from #342  is that I was forced to serialize the ```isGeneric``` field in  ```GrainClassData```. This is required so that the client can create the correct ```GrainId```. Otherwise trying to obtain references to different generic interfaces of the same grain creates one activation per generic interface - see the tests for details, more specifically ```GenericGrainTests_ConcreteGrainWithMultipleGenericInterfacesMultiplicity2```.
Another change is that the grain reference creation process now passes along an instance of ```GrainCassData``` instead of just the grain type code. This should be just fine, as ```GrainCassData``` can …

Instantiating grains that directly implement generic interfaces (+ tests)

---

Who-Is-Using-Orleans.md
index.md

Add "Who is Using Orleans" page to gh-pages web site rather just text file in master branch.
Cleaned up some old links & text.
TODO: Delete old copy from master branch:
~/misc/Projects-Applications-and-Companies-Using-Orleans.md

Add "Who is Using Orleans" page to gh-pages web site.

---

src/Build/PostBuild.cmd
src/Chocolatey/orleans.nuspec

Silo Binaries Package
- Only need the binaries for silo execution in deployment package -- client nuget packages already handle client binaries separately.
- Cleanup the silo deployment package metadata to align with the development / client nuget packages.
- Add silo deployment package dependency on DotNet 4.5

Silo Binaries Package

---

src/Tester/StorageTestConstants.cs
src/Tester/StreamingTests/AQSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/SampleStreamingTests.cs
src/TesterInternal/StorageTests/AzureMembershipTableTests.cs
src/TesterInternal/StorageTests/AzureQueueDataManagerTests.cs
src/TesterInternal/StorageTests/AzureTableDataManagerStressTests.cs
src/TesterInternal/StorageTests/AzureTableDataManagerTests.cs
src/TesterInternal/StorageTests/MembershipTablePluginTests.cs
src/TesterInternal/StorageTests/SiloInstanceTableManagerTests.cs

Fixed streaming tests that were failing due to connection string initialization issues.
Resolved by moved StorageTestConstants initialization to static initializer.

Storage connection string test fix

---

src/Build/PostBuild.cmd
src/Chocolatey/CreateOrleansChocolateyPackage.bat
src/NuGet/CreateOrleansPackages.bat

- Use 'choco pack' to build Chocolatey pkg rather than 'cpack.exe' which gets confused with exe from cmake on some build servers.
- Show location of choco exe if found.
- VS variables %SolutionDir% and %TargetDir% already have trailing back slash.
- Tweak some progress messages for easier readability of build output.
- Version value was not being passed in correctly to Choco pack
- Give explicit exit codes form success (0) or print-usage (-1)
More Cleanup
- Reduce verbosity of nuget & choco pkg cmd
- Use different error code if Choco Pack fails rather than NuGet Pack cmd
- Fix choco pack --Version param passing.
BTW, this problem first showed up in my repo build stream on Appveyer.
https://ci.appveyor.com/project/jthelin/orleans
P.S. Looking at the Jenkins build logs, master build is …

Choco Build Cleanup

---

src/OrleansProviders/Storage/MemoryStorageGrain.cs

Memory storage grains are only to be used for testing. If activation GC is set to a short period of time, those grain will also be collected, potentially leading to wrong test results. They should be viewed as "fake system grains".

Do not ever collect activations of memory storage grains.

---

src/Build/PostBuild.cmd

- Requires Chocolatey packager v0.9.9+ for using version substitution.
- Print choco packager version info [for debugging]

Chocolatey packager

---

src/TestGrainInterfaces/ISampleStreamingGrain.cs
src/TestGrains/MultipleSubscriptionConsumerGrain.cs
src/TestGrains/SampleStreamingGrain.cs
src/Tester/ClientConfigurationForUnitTests.xml
src/Tester/OrleansConfigurationForStreamingDeactivationUnitTests.xml
src/Tester/StreamingTests/PubSubDeactivationTestRunner.cs
src/Tester/StreamingTests/SMSDeactivationTests.cs
src/Tester/Tester.csproj

Repro for #378: Run ```SMSDeactivationTest```
Notes:
* The test is marked as BVT, but it takes 3+ minutes to execute - you may want to relegate it to nightly runs only
* I haven't created a similar test for the AQ streams - it's trivial to add one, though.
* The test shows that the deactivation cycle hangs and that subsequent calls to one of the grains involved in the deadlock hang. Adding more tests assessing the extent of the silo degradation may make sense (e.g. trying to activate an unrelated grain, etc.).
* I've observed that if one waits further (minutes?) the silo eventually commits suicide.

Repro for #378

---

src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs
src/OrleansRuntime/GrainDirectory/RemoteGrainDirectory.cs
src/OrleansRuntime/Messaging/IncomingMessageAcceptor.cs
src/OrleansRuntime/Messaging/OutboundMessageQueue.cs
src/OrleansRuntime/Silo/Silo.cs

Code cleanup
- Some minor code cleanup suggested by some internal code walkthroughs + ReSharper.
- The only significant change is likely to be Line 450 in IncomingMessageAcceptor.cs
Changed from: ``` msg.SendingGrain != Constants.SystemMembershipTableId ```
To: ``` !Constants.SystemMembershipTableId.Equals(msg.SendingGrain) ```
ReSharper pointed out a "possible unintended reference comparison" warning, and i think they are right.
Although GrainId's _should_ all be interned so ref-compare should / may work ok,
i think it safest to use .Equals comparison to ensure we really do get the semantics we expect.

Code cleanup 05/05

---

src/OrleansRuntime/Messaging/MessageCenter.cs

Use .Equals() rather than == for comparing GrainId's
- This is a follow-on fix from PR #391 to fix the same problem in MessageCenter.SendMessage.

Use .Equals() rather than == for comparing GrainId's

---

src/Orleans/Serialization/SerializationManager.cs

This fixes a bug where grain interface method parameters  fail to de-serialize. 
The specific situation I've encountered is this (I haven't run additional tests, but I think the bug is more general that this):
Given a grain interface method ```Task a( A<B> parameter)``` where **A** is an arbitrary generic type  and **B** is an F# discriminated union, the call fails if the compiler-generated class representing the F# union is not an abstract class (the F# compiler may generate abstract or concrete classes for representing F# unions, based on rules that presently escape me).
All existing tests pass and the change is trivial - we're simply ensuring that ```Serializable``` classes in non-system assemblies are registered with the ```SerializationManager```.

SerializationManager: register serializable types in non-system assemblies

---

src/Orleans/AzureUtils/OrleansSiloInstanceManager.cs
src/Orleans/Logging/TraceLogger.cs
src/OrleansRuntime/ReminderService/RemindersTableManager.cs
src/TesterInternal/StorageTests/MembershipTablePluginTests.cs

- Don't crash silo process (eg mstest agent process) if unable to connect to Azure table -- return exception back to caller for logging and handling.
[See failure mode below found in Windows Application Error Log]
- Add check for null config object passed to Logger.Initialize
- Use shorter initialization timeout during Azure MT test cases -- don't need to wait a full 2 minutes before each of those test cases report failure.
Failure Mode from Windows Application Error Log:
```
Application: QTAgent.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Unrecoverable failure: Exception trying to create or connect to the Azure table: Microsoft.WindowsAzure.Storage.StorageException:
Unable to …
```

Azure Table Connection Init Error Handling

---

Step-by-step-Tutorials/A-Service-is-a-Collection-of-Communicating-Actors.md
Step-by-step-Tutorials/Actor-Identity.md
Step-by-step-Tutorials/Cloud-Deployment.md
Step-by-step-Tutorials/Concurrency.md
Step-by-step-Tutorials/Custom-Storage-Providers.md
Step-by-step-Tutorials/Declarative-Persistence.md
Step-by-step-Tutorials/Front-Ends-for-Orleans-Services.md
Step-by-step-Tutorials/Interaction-with-Libraries-and-Services.md
Step-by-step-Tutorials/My-First-Orleans-Application.md
Step-by-step-Tutorials/On-Premise-Deployment.md
Step-by-step-Tutorials/Running-in-a-Stand-alone-Silo.md
Step-by-step-Tutorials/index.md

Made the following changes to the Step-by-step documentation
* Consistent treatment of file names, folder names and paths. All in italic eg _../Dir/file.ext_ as per [GitHub help](https://help.github.com/articles/create-a-repo/)
* Consistent marking up of inline code e.g. `Employee`
* Consolidated on straight quotes (" & ') not curled quotes (“..” & ‘..’). i.e instead of ‘y’, now 'y' and instead of “Version: 2.0”, now "Version: 2.0"
* Keys to be quoted  e.g. "AttributeValue". 
* Use H3 \### style heading instead of \** bold headings
* Added home link on last page
* Marked missing links to API documentation with a TODO comment
* Made the usage of GUID to consistently use the upper case variant (not guid or Guid)
* Corrected table layouts
* Fixed missing/broken links
* Corrected legacy usage …

Updating Step-by-Step documenation

---

src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

We were logging when the adapter cache was under pressure, but were not backing off.

BugFix - Enforce back pressure.

---

.gitignore
src/Tester/ClientConfigurationForStreamTesting.xml
src/Tester/StreamingTests/SMSDeactivationTests.cs
src/Tester/Tester.csproj

Fixes bug in Nightly test suite introduced by PR #408 
Failure case was: SMSDeactivationTest_ClientConsumer
Change:
- Need a different client config for testing client-side streams.
This PR replaces #420 and #421 which got into a bit of a mess!

Testing Host Part 3

---

src/ClientGenerator/ClientGenerator.cs

In Orleans 1.0.7, compiler generated errors no longer appear in the Visual Studio Error List -- only a generic ClientGenerator encountered compilation errors message is displayed, and one would need to parse the raw output to determine the source of the compilation error(s).
It looks like in c5f76715b78764a53f5416069d8419540af46d81, a Console.WriteLine of the raw compiler error string was removed. This patch is to add that back in, which Visual Studio will parse and display in the Error List window as expected. In general, the error reporting changes in that commit seem extraneous, as they display the same data as writing out the MSBuild formatted error string, but in a custom format which Visual Studio cannot parse. Can the team provide any background on this change?

Show Compiler Errors in Visual Studio Error List

---

src/Build.cmd
src/Build/GlobalAssemblyInfo.cs
src/Build/OrleansSetup.wixproj
src/NuGet/CreateOrleansPackages.bat

Also, manually updated AssemblyFileVersion and AssemblyInformationalVersion (but not AssemblyVersion) in GlobalAssemblyInfo.cs to 1.0.7.
This is to address https://github.com/dotnet/orleans/issues/430.

Use version from Build\Version.txt for msi's product version.

---

src/Build.cmd
src/OrleansProviders/OrleansProviders.csproj
src/OrleansRuntime/OrleansRuntime.csproj
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/TestGrains.csproj

- Fixes problems building Orleans.sln with msbuild directly, rather than using the Build.cmd script.
- This fix sets `builduri` variable in Build.cmd to mimic the way TFS build works when $TargetDir points to separate Binaries folder.
- All other situations (including Visual Studio build and running `msbuild Orleans.sln` directly from comment line) use in-tree per-project locations for $TargetDir, so need to look in $SolutionDir\ClientGenerator\bin\$Configuration to locate code-gen tool.

msbuild Orleans.sln

---

src/OrleansTestingHost/TestingSiloHost.cs
src/TestGrains/SimpleObserverableGrain.cs
src/Tester/ObserverTests.cs
src/Tester/SimpleGrainTests.cs
src/Tester/StreamingTests/DeactivationTestRunner.cs
src/Tester/StreamingTests/SampleStreamingTests.cs
src/Tester/StreamingTests/SubscriptionMultiplicityTestRunner.cs
src/TesterInternal/StorageTests/AzureMembershipTableTests.cs
src/TesterInternal/StorageTests/AzureQueueDataManagerTests.cs

It would make sense to refactor all the code to be async-await too. Some of the testing code arguably is as it returns ``TaskDone.Done``, though using .Result and Wait() on the caller side making it more difficult to detect and pushes one into investigating in more detail. But not all code is asynchronous.

Refactoring tests to async-await

---

src/OrleansTestingHost/AsyncResultHandle.cs
src/OrleansTestingHost/OrleansTestingHost.csproj
src/Tester/ObserverTests.cs

Follow up on @veikkoeeva comment in https://github.com/dotnet/orleans/pull/441 about ResultHandle: 
"ResultHandle is hazardous looking construct. I appreciate  WaitFor  operates only on arguments, but still, and the internal  Thread.Sleep  could be converted to  Task.Delay  too (though the  ref  parameter creates some work to do)."

Renamed ResultHandle to AsyncResultHandle and made it use await.

---

src/Orleans/Logging/ErrorCodes.cs
src/OrleansAzureUtils/AzureSilo.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/InsideGrainClient.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloHost.cs
src/OrleansTestingHost/TestingSiloHost.cs

Call Silo.Shutdown  from Azure Orleans Silo host and regular Orleans Silo host Stop() methods.
Deactivate all grains in this silo properly upon Silo.Shutdown call.
This is a 2nd step towards Gracefull Shutdown, related to:
#381
#320 (comment)
http://orleans.codeplex.com/discussions/637820#post1425137
Continues the work in #413.
Still a bit more work is required, to properly unsure that silo does not accept any new grain requests after the grains were deactivated and before silo is fully dead (so that we don't reactivate some grains again). This PR definitely leaves us in a better state than before we Deactivated all grains, so I feel like it can be merged even before the next level of improvements is done.

Added Silo.Shutdown call.

---

src/OrleansTestingHost/OrleansTestingHost.csproj
src/OrleansTestingHost/StorageEmulator.cs
src/TestGrainInterfaces/ISimpleBootstrapGrain.cs
src/TesterInternal/StorageTests/AzureMembershipTableTests.cs
src/TesterInternal/StorageTests/AzureQueueDataManagerTests.cs
src/TesterInternal/StorageTests/AzureTableDataManagerStressTests.cs
src/TesterInternal/StorageTests/AzureTableDataManagerTests.cs
src/TesterInternal/StorageTests/AzureTableErrorCodeTests.cs
src/TesterInternal/StorageTests/MembershipTablePluginTests.cs
src/TesterInternal/StorageTests/SiloInstanceTableManagerTests.cs

Currently the test start to fail some time after startup if the storage emulator is not on. This patch provides a thin, programmatic wrapper to start or stop Storage Emulator process and a class to start the emulator before any tests are run.
This looks like being a nice convenience feature, as noted at [PR #412](https://github.com/dotnet/orleans/pull/412#issuecomment-101672812).
This approach might be suitable for refactoring to check if other processes are on too (e.g. database engines) if dependency external libraries such as Fake is not desired.

Added storage emulator auto-start before any tests are run

---

src/OrleansTestingHost/StorageEmulator.cs

Removed 'x' at the end of storage emulator friendly name ("WAStorageEmulatorx" -> ""WAStorageEmulator")

Removed 'x' at the end of storage emulator friendly name

---

src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Messaging/IncomingMessageAgent.cs
src/OrleansRuntime/Placement/IPlacementContext.cs
src/OrleansRuntime/Placement/RandomPlacementDirector.cs
src/OrleansRuntime/Silo/Silo.cs

This is a 3rd step towards Gracefull Shutdown, related to:
#381
#320 (comment)
http://orleans.codeplex.com/discussions/637820#post1425137
Continues the work in #413.
Continues the work in #448.
Essentially, the silo was already largely handling this logic correctly. I merely simplified a couple of places, to make more clear what will actually happen. At a high level:
1) Once silo is shutting down, it first updates its membership state. This will cause all other silos not to place new activation on it, not to use this silo as grain directory and not as reminder service. This logic was already handled correctly before. No change.
2) Silo refuses to create any new activations, throws Non-existent activation and tries to forward the request. The activation will be placed on a different silo. …

Make sure we handle all in flight requests correctly when silo is shutting down.

---

src/OrleansTestingHost/StorageEmulator.cs

Process.Start was throwing in our nightly tests breaking them. This is a replacement for https://github.com/dotnet/orleans/pull/464.

Added a try/catch to StorageEmulator.TryStart()

---

src/Orleans/Runtime/GrainRuntime.cs
src/Orleans/Runtime/IActivationData.cs
src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Silo/Silo.cs

Changed GrainRuntime.SiloIdentity to be a silo address and not silo name.
It used to be silo address and not silo name before the DI change, which accidently changed it.
Also remove some redundantly exposed properties on IActivationData.

Changed GrainRuntime.SiloIdentity to be a silo address and not silo name.

---

src/Orleans.sln
src/TestAll.cmd
src/Tester/ConcreteStateClassTests.cs
src/Tester/GenericGrainTests.cs
src/Tester/ObserverTests.cs
src/Tester/SerializationTests.cs
src/Tester/SimpleGrainTests.cs
src/Tester/StreamingTests/AQSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/SMSDeactivationTests.cs
src/Tester/StreamingTests/SMSSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/SampleStreamingTests.cs
src/TesterInternal/General/Identifiertests.cs
src/TesterInternal/OrleansRuntime/Streams/BestFitBalancerTests.cs
src/TesterInternal/StorageTests/AzureMembershipTableTests.cs
src/TesterInternal/StorageTests/AzureQueueDataManagerTests.cs
src/TesterInternal/StorageTests/AzureTableDataManagerTests.cs
src/TesterInternal/StorageTests/AzureTableErrorCodeTests.cs
src/TesterInternal/StorageTests/MembershipTablePluginTests.cs
src/TesterInternal/StorageTests/SiloInstanceTableManagerTests.cs

Renamed test category "Nightly" to "Functional" to better reflect its purpose.
A rebased replacement for https://github.com/dotnet/orleans/pull/484.

Renamed test category "Nightly" to "Functional"

---

src/Orleans/Messaging/GatewayClientReceiver.cs
src/Orleans/Messaging/IncomingMessageBuffer.cs
src/Orleans/Messaging/Message.cs
src/Orleans/Orleans.csproj
src/OrleansRuntime/Messaging/IncomingMessageAcceptor.cs

Modified network receive code to perform bulk receive in order to reduce the number of socket receive system calls.
The original networking code made 3 socket receive calls per message.
This change modifies the receive code to perform a bulk socket read into a buffer, then parses all messages that were received.  This should greatly reduce the number of socket receive system calls.

Modified network receive to perform bulk receive.

---

Build.cmd
src/Build.cmd

You should now be able to run Build.cmd from a path with spaces in it.
This is for #461

Wrapped build paths with quotes

---

src/Orleans.sln
src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/AssemblyLoader/AssemblyLoaderCriteria.cs
src/Orleans/AzureUtils/AzureGatewayListProvider.cs
src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/ClusterConfiguration.cs
src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Messaging/GatewayProviderFactory.cs
src/Orleans/Messaging/IGatewayListProvider.cs
src/Orleans/Messaging/SqlMembershipTable.cs
src/Orleans/SystemTargetInterfaces/IMembershipTable.cs
src/Orleans/Utils/Utils.cs
src/OrleansRuntime/MembershipService/AzureBasedMembershipTable.cs
src/OrleansRuntime/MembershipService/GrainBasedMembershipTable.cs
src/OrleansRuntime/MembershipService/MembershipFactory.cs
src/OrleansTestingHost/StorageTestConstants.cs
src/OrleansZooKeeperUtils/MembershipSerializerSettings.cs
src/OrleansZooKeeperUtils/OrleansZooKeeperUtils.csproj
src/OrleansZooKeeperUtils/Properties/AssemblyInfo.cs
src/OrleansZooKeeperUtils/ZooKeeperBasedMembershipTable.cs
src/OrleansZooKeeperUtils/packages.config
src/TesterInternal/StorageTests/AzureMembershipTableTests.cs
src/TesterInternal/StorageTests/MembershipTablePluginTests.cs
src/TesterInternal/StorageTests/ZookeeperMembershipTableTests.cs
src/TesterInternal/TesterInternal.csproj

You can now run Orleans with a zookeeper membership table:
```xml
<SystemStore
DataConnectionString="192.168.1.1;192.168.1.2;192.168.1.3"
DeploymentId="BestDeploymentEver"
SystemStoreType="ZooKeeper"/>
```
For testing, please copy [ZooKeeper 3.4.6 release](http://www.apache.org/dyn/closer.cgi/zookeeper/) to some local folder. then go to "conf" folder and rename zoo_sample.cfg to zoo.cfg. then go to the bin folder and run zkServer.cmd. this runs the server at 127.0.0.1:2181, which is the default address for the tests.
While integrating I came across some issues:
my first instinct was to create an "OrleansZooKeeperUtils" project, but that created circular dependencies since IMembershipTable & IGatewayListProvider live in Orleans.dll. . so for now it's where the SqlMembershipTable, in the …

ZooKeeper 3.4.6 as a membership provider

---

src/TestGrains/GenericGrains.cs

Tests
* Generic_SimpleGrainControlFlow3
* Generic_SelfManagedGrainControlFlow
are now locale dependent and both fail with message "Result Message: Assert.AreEqual failed. Expected:<3x1.25>. Actual:<3x1,25>." on systems where dot is not a decimal separator. The fix is to use ``CultureInfo.InvariantCulture`` when serializing floating point numbers.

Fixes two tests that fail due to culture specific string

---

Samples/AzureWebSample/AzureWebSample.sln
Samples/AzureWebSample/HelloEnvironmentGrains/HelloEnvironmentGrains.csproj
Samples/AzureWebSample/HelloEnvironmentGrains/HelloEnvironmentHelloGrain.cs
Samples/AzureWebSample/HelloEnvironmentGrains/Properties/AssemblyInfo.cs
Samples/AzureWebSample/HelloEnvironmentGrains/packages.config
Samples/AzureWebSample/HelloEnvironmentInterfaces/HelloEnvironmentInterfaces.csproj
Samples/AzureWebSample/HelloEnvironmentInterfaces/IHelloEnvironment.cs
Samples/AzureWebSample/HelloEnvironmentInterfaces/Properties/AssemblyInfo.cs
Samples/AzureWebSample/HelloEnvironmentInterfaces/packages.config
Samples/AzureWebSample/OrleansAzureSilos/OrleansAzureSilos.csproj
Samples/AzureWebSample/OrleansAzureSilos/WorkerRole.cs
Samples/AzureWebSample/OrleansAzureSilos/app.config
Samples/AzureWebSample/WebRole/Default.aspx
Samples/AzureWebSample/WebRole/Default.aspx.cs
Samples/AzureWebSample/WebRole/Default.aspx.designer.cs
Samples/AzureWebSample/WebRole/WebRole.csproj
Samples/HelloWorld/HelloWorldGrains/HelloWorldGrains.csproj
Samples/HelloWorld/HelloWorldInterfaces/HelloWorldInterfaces.csproj

This PR accomplishes two things.
- Fixes the HelloWorld sample so that it no longer references packages in the AzureWebSample project
- Creates standalone sample projects in AzureWebSample so that it no longer references the HelloWorld sample.
This is to help new users being able to open a sample and press F5 to get going.  
This fixes #505

New Samples

---

src/Tester/Tester.csproj

Make Tester project reference OrleansCounterControl and OrleansZooKeeperUtils, so that they get copied for internal tests.

Make Tester project reference OrleansCounterControl and OrleansZooKeeperUtils

---

src/ClientGenerator/CodeGeneratorBase.cs
src/Orleans/CodeGeneration/GrainInterfaceData.cs
src/TestGrainInterfaces/GrainInterfaceHierarchyIGrains.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/GrainInterfaceHierarchyGrains.cs
src/TestGrains/TestGrains.csproj
src/Tester/GrainInterfaceHierarchyTests.cs
src/Tester/Tester.csproj

this is a small change in code, but big on implications. IMHO this should be the default.

codegen for IGrain interface inherited methods

---

Runtime-Implementation-Details/index.md

Fix the index that referred to old codeplex pages.

Fix runtime implementation details documentation index page.

---

src/Orleans/Runtime/IConsistentRingProviderForGrains.cs
src/Orleans/SystemTargetInterfaces/IMembershipTable.cs
src/Orleans/SystemTargetInterfaces/IReminderTable.cs
src/OrleansRuntime/ConsistentRing/EquallyDevidedRangeRingProvider.cs
src/OrleansRuntime/MembershipService/GrainBasedMembershipTable.cs
src/OrleansRuntime/MembershipService/MembershipFactory.cs
src/OrleansRuntime/ReminderService/GrainBasedReminderTable.cs
src/OrleansRuntime/ReminderService/ReminderTable.cs
src/OrleansRuntime/Streams/QueueBalancer/ConsistentRingQueueBalancer.cs

Refactoring IReminderTable and IMembershipTable interfaces to remove
dependce on IGrain interface. This cleans up the code so that only grain based implementations are marked as IGrain and others such as Azure or SQL are not. 
Also, removed IGrain inheritance for IGrainRingRangeListener since it no longer requires that and renamed it to IAsyncRingRangeListener.

Refactored IMembershipTable and IReminderTable hierarchy to remove dependence on IGrain where not required.

---

src/ClientGenerator/ClientGenerator.cs
src/Orleans/CodeGeneration/GrainInterfaceData.cs
src/Orleans/CodeGeneration/TypeUtils.cs

Fixes #492. The fix validate during code generation (for grain implementations) if all grain classes extend Grain or Grain<T> base classes, otherwise issue a compile time warning.
As a result of the fix, there were some compile warning in the orleans runtime:
1. IReminderTable is marked as IGrain because one of the implementations (GrainBasedReminderTable) is a grain while others e.g. Azure, SQL based are not.
2. Similarly for IMembershipTable interface.
Refactored the code so that the base IReminderTable and IMembershipTable interfaces are not IGrain and created a IReminderTableGrain and IMembershipTableGrain interfaces which are used by the GrainBased classes.
There was also an interface:
internal interface IGrainRingRangeListener : IGrain
Need to confirm with @gabikliot  if this really …

Issue a compile time warning if a class implements IGrain but does not extend the base Grain or Grain<T> class.

---

src/Orleans/Configuration/ClusterConfiguration.cs
src/Orleans/Configuration/GlobalConfiguration.cs
src/OrleansRuntime/Core/InsideGrainClient.cs
src/OrleansRuntime/Silo/Silo.cs

Disable Reminders if ZK is used for system store.
This is instead of #535.
As opposite to #535, this code will throw earlier, on the caller, if reminders are used from the grain when running with ZK system store.

Set Reminder Type to Disabled in case of Zookeper System store.

---

src/OrleansZooKeeperUtils/OrleansZooKeeperUtils.csproj
src/OrleansZooKeeperUtils/ZooKeeperBasedMembershipTable.cs
src/OrleansZooKeeperUtils/packages.config

* Updated ZooKeeperNetEx. (the new version fixes several bugs that came up in testing)
* Only set maxStaleness for GatewayListProvider. from #530
* Use CultureInfo.InvariantCulture when converting ZK rowVersion to string eTag. from #530
* Added lots of documentation
* Using ETags instead of table versions.
* Some implementation tweaks, no logic was changed

ZK MBR documentation,tweaks and new ZooKeeperNetEx

---

src/Orleans/CodeGeneration/GrainInterfaceData.cs

Currently IGrainWith* interfaces are counted as grain interfaces while IGrain is not. This is clearly wrong.

Fix IsGrainInterface to not consider IGrainWith* interfaces as grain interfaces.

---

src/Orleans/Core/GrainClient.cs
src/Orleans/Core/GrainExtensions.cs
src/Orleans/Core/GrainFactory.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Runtime/IRuntimeClient.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs
src/OrleansManager/Program.cs
src/OrleansRuntime/Core/InsideGrainClient.cs
src/OrleansRuntime/Core/ManagementGrain.cs
src/OrleansRuntime/GrainDirectory/AdaptiveDirectoryCacheMaintainer.cs
src/OrleansRuntime/GrainDirectory/GrainDirectoryPartition.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs
src/OrleansRuntime/GrainDirectory/RemoteGrainDirectory.cs
src/OrleansRuntime/MembershipService/MembershipFactory.cs
src/OrleansRuntime/MembershipService/MembershipOracle.cs
src/OrleansRuntime/Placement/DeploymentLoadPublisher.cs
src/OrleansRuntime/ReminderService/LocalReminderService.cs
src/OrleansRuntime/Silo/Silo.cs

Make GrainFactory.Cast and GetSystemTarget non static.
Make caster collections inside GrainFactory non static.
Add IRuntimeClient.InternalGrainFactory to expose GrainFactory.GetSystemTarget
Switch to use IAddressable.Cast instead of Orleans.GrainFactory.Cast.
A step towards making GrainClient non static and allowing multiple grain clients to connect to multiple clusters.

Remove statics from GrainFactory.

---

src/Build.cmd

This adds a multicore, /m, switch to MSBuild arguments.
Unscientific measurement indicates increased processor utilization and mildly
decreased compilation times (also MSBuild won't print a suggestion to add "/m" anymore).

Multicore compilation switch added to build script

---

Samples/StorageProviders/StorageProviders/Samples.StorageProviders.csproj
Samples/StorageProviders/Test.Client/DevTestServerConfiguration.xml
Samples/StorageProviders/Test.Client/Test.Client.csproj
Samples/StorageProviders/Test.Client/packages.config
Samples/StorageProviders/Test.Implementation/Test.Implementation.csproj
Samples/StorageProviders/Test.Implementation/packages.config
Samples/StorageProviders/Test.Interfaces/Test.Interfaces.csproj
Samples/StorageProviders/Test.Interfaces/packages.config

- Changed the Storage Providers sample to use Orleans NuGet v1.0.8 packages.
- Cleaned up the test client hosting quirks so that dev-test silo runs in-place rather than requiring LocalSilo from SDK drop.

Storage Provider Samples use NuGet packages

---

src/Orleans/Messaging/GatewayClientReceiver.cs
src/Orleans/Runtime/AsynchAgent.cs
src/OrleansRuntime/Scheduler/WorkerPool.cs
src/OrleansRuntime/Scheduler/WorkerPoolThread.cs

Remove static collections from AsynchAgent. 
Fix thread names allocation to ensure unique thread names.
On the path of solving #467.

Remove static collections from AsynchAgent. 

---

src/Orleans/CodeGeneration/TypeUtils.cs

Bug reported by @ReubenBond on gitter:
"Okay, someone tell me I'm tripping, but is the existing codegen emitting the namespace twice in string forms of the names? eg, GrainReferenceAttribute("Orleans.Storage.Orleans.Storage.IMemoryStorageGrain") and the InterfaceName property.
(check orleans.codegen.cs from the Orleans project for that particular ref)"

Fixed a bug of double namespace in codegen.

---

src/ClientGenerator/ClientGenerator.cs
src/ClientGenerator/NamespaceGenerator.cs
src/ClientGenerator/Serialization/SerializerGenerationManager.cs
src/Orleans/Logging/ConsoleText.cs

Report "no StorageProvider attribute" as an error.
Remove duplicate reporting of errors.
Report an error and don't throw.

Improve error reporting in codegen

---

src/OrleansRuntime/GrainTypeManager/GenericGrainTypeData.cs
src/Tester/GenericGrainTests.cs

Call `stateObjectType.GetGenericTypeDefinition().MakeGenericType(typeArgs)` instead of `stateObjectType.MakeGenericType(typeArgs)`.
This bug surfaces in trying to migrate from generic grain state interfaces to generic state classes.

Fix instantiation of generic state objects

---

src/ClientGenerator/NamespaceGenerator.cs
src/Orleans/CodeGeneration/GrainState.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs
src/TestGrains/GenericGrains.cs
src/TestGrains/SimplePersistentGrain.cs
src/Tester/ConcreteStateClassTests.cs

Converted  PubSubRendezvousGrain and all tests grains to use state classes instead of interfaces.
Added a compile time warning for usage of grain state interfaces.
The goal here is to deprecate grain state interfaces in 1.0.9, and then remove support for them and code generation of state classes in 1.0.10.

Migrate to using grain state classes instead of interfaces

---

src/Orleans/CodeGeneration/GrainState.cs
src/Orleans/Core/IGrainFactory.cs

Both GrainState and IGrainFacttory are supposed to be used in common scenarios now, and having then in sub-namespaces creates unnecessary friction through lower discoverability and the need for extra using statements.

Move GrainState and IGrainFactory to the root Orleans namespace 

---

src/OrleansAzureUtils/Storage/AzureTableDataManager.cs

This change removes schema initialization of azure tables.  
Earlier versions of azure table storage required schema initialization when using local developer storage.  This is no longer the case, and this schema initialization can leave junk in the table.

Removed schema initialization from table creation

---

src/OrleansZooKeeperUtils/OrleansZooKeeperUtils.csproj
src/OrleansZooKeeperUtils/packages.config
src/TesterInternal/MembershipTests/MembershipTablePluginTests.cs

changes in ZooKeeperNetEx:
* code is 100% CoreCLR compliant
* purely task based, removed usage of explicit threads
* fixed a bug with session shutdown
* improved "ZooKeeper.Using" implementation
* documented all public surface methods and classes
* removed dependency on log4net
also, fixed a minor bug in the membership tests, correct me if I'm wrong.

update ZK nuget & minor fix to membership tests

---

src/Orleans/Statistics/FloatValueStatistic.cs

This fixes float statistics values to culture invariant form,
especially forces the decimal separator to be dot.
fixes decimal separator to use invariant culture separator
This is done to avoid problems when reading data from a storage
and it is converted back to floating point values.
Fixes #573.

Fixes float statistics to culture invariant form

---

src/Build/OrleansSetup.wixproj
src/Build/OrleansSetup.wxs

Removed Binaries and LocalSilo folders from SDK.
Removed "Preview" from the registry key.
Now the SDK will only install the VSIX and docs, license, links. Orleans binaries will only come through NuGet packages.

Removed binaries from SDK.

---

src/OrleansVSTools/VSProjectSiloHost/OrleansHostWrapper.cs
src/OrleansVSTools/VSProjectSiloHost/Program.cs
src/OrleansVSTools/VSProjectSiloHost/ProjectTemplate.csproj
src/OrleansVSTools/VSProjectTemplateGrainImplementation/Grain1.cs
src/OrleansVSTools/VSProjectTemplateGrainImplementation/ProjectTemplate.csproj
src/OrleansVSTools/VSProjectTemplateGrainImplementationFSharp/ProjectTemplate.fsproj
src/OrleansVSTools/VSProjectTemplateGrainImplementationVB/ProjectTemplate.vbproj
src/OrleansVSTools/VSProjectTemplateGrainInterface/IGrain1.cs
src/OrleansVSTools/VSProjectTemplateGrainInterface/ProjectTemplate.csproj
src/OrleansVSTools/VSProjectTemplateGrainInterfaceVB/ProjectTemplate.vbproj

Removed references to %OrleansSDK% environment variable and dependencies on Orleans SDK.
Removed post-build steps of copying files to LocalSilo folder of Orleans SDK.
Fixed paths to NuGet packages to work correctly when .sln and project files are in the same folder.
Added "using System.Threading.Tasks;" to .cs files.

Remove dependencies on Orleans SDK from project templates

---

src/OrleansRuntime/Messaging/IOutboundMessageQueue.cs
src/OrleansRuntime/Messaging/OutboundMessageQueue.cs

- The `SendMessage` method in `OutboundMessageQueue` is declared as returning a `bool`, but the returned value is always `true` and the returned value is never used anywhere.
Changing return type to `void` to avoid confusion.
- Throw NullArgumentException if SendMessage is every passed a null message [never happens in current code base], rather than silently ignore.
Replaces #586

OMQ-SendMessage

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/Runtime/Constants.cs

This is a fix for https://github.com/dotnet/orleans/issues/593.
Changed AssemblyLoader.LoadAndCreateInstance<T> to use Assembly.Load() instead of Assembly.LoadFrom() because of the assembly layout in ASP.NET where every such assembly is put in its own folder.

Switched loading of plugin assemblies from Assembly.LoadFrom() to Assembly.Load()

---

src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/OrleansZooKeeperUtils/ZooKeeperBasedMembershipTable.cs
src/OrleansZooKeeperUtils/packages.config

This PR contains two fixes:
* ZK MBR - fix packaging
* added ZooKeeperNetEx dependency to the OrleansZooKeeperUtils.nuspec
* added Newtonsoft.Json to packages.config of OrleansZooKeeperUtils project
* ZK MBR - filter active gateways
* filter only active gateways with ProxyPort !=0
* replace Port with ProxyPort in returned SiloAddress

ZK MBR - fix packaging and filter active gateways

---

src/Orleans/Logging/TraceLogger.cs

new StreamReader(string) is listed in the .NET Portability Report as none compatible; this change corrects this.

StreamReader correction for coreclr

---

src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Providers/IProviderRuntime.cs
src/Orleans/Providers/StatisticsProviderManager.cs
src/Orleans/Runtime/GrainRuntime.cs
src/Orleans/Runtime/IGrainRuntime.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Storage/StorageProviderManager.cs

Silo runtime identity - align runtime id values exposed to sub-components through IProviderRuntime and IGrainRuntime
Currently slightly different facets of "runtime identity" information is exposed in the `IProviderRuntime` and `IGrainRuntime` interfaces.
This change set is to normalize that so that both interfaces contain the same set of runtime identity info - both `Guid ServiceId` and `string SiloIdentity`.
Main changes are:
- Add `SiloIdentity` property to `IProviderRuntime` interface [it already contains `ServiceId`]
- Add `ServiceId` property to `IGrainRuntime` interface [it already contains `SiloIdentity`]

Silo runtime identity

---

src/ClientGenerator/ClientGenerator.cs

Codegen puts way too much information in the build logs!

Turn down default verbosity of code-gen status logging.

---

src/ClientGenerator/NamespaceGenerator.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansTestingHost/OrleansConfigurationForTesting.xml
src/TestGrains/SimplePersistentGrain.cs

Currently, adding `[StorageProvider]` to a grain is equivalent to adding `[StorageProvider(ProviderName = "Default")]` to that grain. The provider named "Default" will be used in either case.
This change removes the requirement for `[StorageProvider]` on a grain altogether: a grain with no`StorageProviderAttribute` is treated identically to a grain with a default `[StorageProvider]`.

Remove requirement for [StorageProvider] on stateful grains

---

src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Messaging/GatewayClientReceiver.cs
src/Orleans/Messaging/GatewayConnection.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/OrleansAzureUtils/Storage/OrleansSiloInstanceManager.cs
src/OrleansTestingHost/TestingSiloHost.cs
src/Tester/MembershipTests/LivenessTests.cs
src/Tester/Tester.csproj
src/TesterInternal/TesterInternal.csproj

Addressing an issue reported in http://orleans.codeplex.com/discussions/641601, where in a sequence of graceful shutdowns of silos a client would sometimes loose an occasional  message.
No messages should be lost in failure free scenarios, including graceful shutdowns.
Also, created a test scenario following the scenario sequence described in http://orleans.codeplex.com/discussions/641601 (test name `Liveness_Grain_5_ShutdownRestartZeroLoss`) and was able to repro the problem and validate the fix. Did not enable this test yet, due to some weirdness in the TestInitialize/TestCleanup sequence by MSTest. Will enable once we switch to NUint, as planned according to #575.

Fixed a bug in GW-client shutdown sequence that caused an occasional message from a client to shutting down silo to be dropped.

---

src/Orleans/Configuration/ConfigUtilities.cs

The existing code had a bug on Line 216.  The `!Directory.Exists(traceFileDir)` clause would never be true since to even set the traceFileDir on line 213 `Directory.Exists(traceFileDir)` must be true.
I also cleaned up the code to be more readable in my opinion showing intent by only performing the search if the original folder is not found.
Now when the trace file does not exist, it will fall back on an "appdir" subdirectory if it exists, and finally the current directory.

Fix alternate folder code for when trace file folder does not exist.

---

src/Orleans/Core/GrainClient.cs
src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Streams/Internal/StreamDirectory.cs
src/OrleansRuntime/Storage/StorageProviderManager.cs

Make `ClientProviderRuntime` non-singleton, since there was really no need for that (also helps with # 467).
Properly initialize and reset `ClientProviderRuntime`  when `OutsideGrainClient` is uninitialized.
As part of `ClientProviderRuntime.Reset()` calls `StreamDirectory.Cleanup`. This will cause all client side producers to unsubscribe from the pub sub. 
That way old client side producers will be cleaned up from the pubsub, in a non-failure clean-shutdown case of Orleans client.

Cleanup client side stream producers automatically when Orleans client is uninitialized.

---

src/TesterInternal/General/InterfaceRules.cs
src/TesterInternal/TesterInternal.csproj

These tests check that violations of the grain interfaces rules are detected and reported properly.

Migrate interface rules tests

---

src/Tester/SerializationTests.cs
src/Tester/SerializationTests_InnerTypes.cs
src/Tester/Tester.csproj

Investigated issue reported in #651.
Found that there is no problem with Orleans's serialization, it works correctly as expected.

Added a serialization test for json serialization of complex types.

---

src/Orleans/Core/GrainFactory.cs

GetSystemTarget-Cast
- If a system target implements multiple interfaces, the copy of the reference that the `GrainFactory` has cached may not be for the correct interface, so may need to to explicit `Cast(..)` to get the correct typed reference we asked for.

GetSystemTarget-Cast

---

src/NuGet/Microsoft.Orleans.OrleansProviders.nuspec
src/OrleansProviders/OrleansProviders.csproj
src/OrleansProviders/packages.config

Hi guys!
I've started cleaning up references to Azure SDK after upgraded to 1.0.9. You did a great job on consolidating azure dependencies to only OrleansAzureUtils.dll. While working on the upgrade I've noticed that OrleansProviders package still have references to Azure SDK. Thus this PR!
Yevhen

Remove confusing dependencies on Azure SDK

---

src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Streams/Internal/IInternalAsyncObservable.cs
src/Orleans/Streams/Internal/IInternalStreamProvider.cs
src/Orleans/Streams/Internal/IStreamControl.cs
src/Orleans/Streams/Internal/StreamConsumer.cs
src/Orleans/Streams/Internal/StreamConsumerExtension.cs
src/Orleans/Streams/Internal/StreamDirectory.cs
src/Orleans/Streams/Internal/StreamImpl.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProducer.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProducer.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs
src/OrleansRuntime/Catalog/ActivationData.cs

This is a follow up work on #642.

Unsubscribe all client side stream consumers when Orleans client gracefully shuts down.

---

src/TesterInternal/TesterInternal.csproj

- Missing some project references in TesterInternal, which is the tailgate project that runs the PostBuild.cmd script to build the output packages.
- TesterInternal should contain project reference dependencies to all other project in the solution.

Missing some project references required for package build.

---

src/Orleans/IDs/ActivationId.cs
src/Orleans/Utils/Utils.cs
src/OrleansRuntime/GrainDirectory/ClientObserverRegistrar.cs

When a client connects to a silo GW, GW registers his own address as a fake "activation" in the grain directory for this client GrainId. That is used later on to find the GW that is proxying for this client to send observer and stream messages to it. If client connects to multiples GW, each has to register as a different activation, so we can send observer notifications via different GWs. 
The bug was in the way we calculate activation id for this "fake GW activation", which caused all GWs to use the same activation id. As a result, only one GW would be used to send observer notifications to this client, potentially reducing reliability and throughput for this client.
The fix generates a unique deterministic activation id for each client GrainId and GW silo address pair.

Fixed a bug in client GW registration protocol.

---

src/Orleans/Configuration/ConfigUtilities.cs
src/Orleans/Configuration/NodeConfiguration.cs

Not a real bug, just different expected result in our tests. Was caused by #638.

Fixed the way we set trace file name that was breaking our internal tests.

---

src/OrleansAzureUtils/Hosting/AzureSilo.cs

Adds the ability to provide DataConnectionString to an Azure silo on start, instead of through configuration. This way the connection string can be stored elsewhere (e.g., AzureKeyVault) and retrieved at runtime.
Note: I'm not sure why the changed lines have extra indentations. It is only showing on GitHub, not VS.

Added optional connectionString in AzureSilo.Start

---

src/Tester/SerializationTests.cs

A unit test case for DateTimeOffset serialization.
Closes #676.

SerializationTests_DateTimeOffset

---

src/OrleansZooKeeperUtils/OrleansZooKeeperUtils.csproj
src/OrleansZooKeeperUtils/ZooKeeperBasedMembershipTable.cs
src/OrleansZooKeeperUtils/packages.config

Improvements :
* Watcher interface method returns Task
* Taking better care of disposables
* Globalization of all strings
* Added async Recipes. [Nuget available](https://www.nuget.org/packages/ZooKeeperNetEx.Recipes)
* Support both .NET 4.5 and .NET 4.6 in nuget packages
* Published code & pdb & xml doc files with the nuget packages. go [here](http://www.symbolsource.org/Public/Home/VisualStudio) for instructions.

ZK MBR - update ZooKeeperNetEx to 3.4.6.1002

---

src/Orleans/Core/GrainAttributes.cs
src/TestGrainInterfaces/CodegenTestInterfaces.cs
src/TestGrainInterfaces/IMultipleImplicitSubscriptionGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/MultipleImplicitSubscriptionGrain.cs
src/TestGrains/MultipleSubscriptionConsumerGrain.cs
src/TestGrains/TestGrains.csproj
src/Tester/StreamingTests/SampleStreamingTests.cs

By mistake ImplicitStreamSubscriptionAttribute doesn't have AllowMultiple=true set. This adds it and also adds a test for two implicit stream subscriptions on a grain class.

Allow multiple implicit subscriptions

---

src/Orleans/Core/GrainAttributes.cs
src/Orleans/Placement/GrainStrategy.cs
src/Orleans/Placement/StatelessWorkerPlacement.cs
src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeData.cs
src/OrleansRuntime/Placement/StatelessWorkerDirector.cs
src/TestGrainInterfaces/IStatelessWorkerGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/StatelessWorkerGrain.cs
src/TestGrains/TestGrains.csproj
src/Tester/StatelessWorkerTests.cs
src/Tester/Tester.csproj

Stateless worker placement was not guaranteeing that we never go above the exact specified number of  stateless worker activations in a single silo. We could sometimes overshoot, due to a race between lookup and multiple concurrent activate calls. This was especially bad when stateless worker count of "1" was specified.
This fix fixes the issue, by essentially re-using the DuplicateActivation logic to deal with races between concurrent activate attempts.

Stateless worker ensure exact count

---

src/Orleans/IDs/QueueId.cs

We need this for implementation of KafkaStreamProvider. In our implementation, we map each Queue to a certain Kafka topic partition. A partition is represented by a uint. In order to get which partition belongs to which Queue it is simplest for us to get the queueId value from QueueId which is also a uint, and as their inner ids were created sequentially so it perfectly matched to use it in order to get the right partition.

Exposed the queueId data member with a new function: QueueId.GetNumericId

---

src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Streams/PersistentStreams/IPersistentStreamPullingAgent.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans/Streams/Providers/IStreamProviderImpl.cs
src/Orleans/Streams/Providers/IStreamProviderRuntime.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs
src/OrleansRuntime/Core/ManagementGrain.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingManager.cs

For low/zero downtime upgrade scenarios we need an ability to start a silo/cluster without starting its pulling agents, so that we can switch from old to new cluster and avoid parallel delivery of events by two sets of pulling agents in two clusters.
This is a first step towards controllable management of stream pulling agents, allowing to stop/start/resume/suspend them based on config or external command.

Add a config option to start silos with pulling agents stopped.

---

src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/OrleansZooKeeperUtils/OrleansZooKeeperUtils.csproj
src/OrleansZooKeeperUtils/packages.config

**New Features**
* Support the new [dotnet](https://oren.codes/2015/07/29/targeting-net-core/) target for .NET Core
* Support .NET 4

ZK MBR -  update ZooKeeperNetEx to 3.4.6.1004

---

src/OrleansProviders/Storage/MemoryStorage.cs
src/TestGrains/InitialStateGrain.cs
src/Tester/MemoryStorageProviderTests.cs
src/Tester/Tester.csproj
src/TesterInternal/TesterInternal.csproj

Fixed  a bug reported in #696 and reproduced in #697.
Moved the test from TesterInternal to Tester.

Fixed a bug of MemoryStorageProvider does not respect grain state default constructor upon initialization.

---

src/Orleans/Orleans.csproj
src/Orleans/Providers/IControllable.cs
src/Orleans/Providers/StatisticsProviderManager.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans/Streams/Providers/StreamProviderManager.cs
src/Orleans/SystemTargetInterfaces/IManagementGrain.cs
src/OrleansRuntime/Core/ManagementGrain.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloControl.cs
src/OrleansRuntime/Storage/StorageProviderManager.cs
src/Tester/StreamingTests/PullingAgentManagementTests.cs
src/Tester/Tester.csproj

Added IControllable interface for providers ().
Store all providers in the Silo, for fast lookup and retrieval.
Added an ability to send a command to a controllable provider via management grain and ISiloControl system target.
Made PersistentStreamProvider controllable.
Unit test.

Allow to send external control commands to providers

---

src/OrleansZooKeeperUtils/OrleansZooKeeperUtils.csproj

- Turn on compiler errors for missing await calls (CS4014 warning), same as for other Orleans project files.

Turn on WarningsAsError for CS4014

---

src/Orleans/Core/GrainAttributes.cs

- Clarify usage scope of the [AlwaysInterleave] attribute -- it is placed on methods in grain interface, not methods in implementation class.
- Remove attribute usage scopes of "Property". because properties in grain interfaces are no longer supported.

Clarify usage scope of the [AlwaysInterleave] attribute.

---

src/Orleans/Streams/Providers/IStreamProviderRuntime.cs

Now that pubsub type is configurable, types should be public

PubSubType public

---

src/OrleansAzureUtils/Hosting/ServiceRuntimeWrapper.cs

When building list of all silo instance names, we weren't accounting for deployment Id.

Azure Queue Balancer failed when deploymentId was set.

---

src/OrleansAzureUtils/Storage/AzureBasedMembershipTable.cs

We don't need that timeout there, we have a 5 min timeout guard on the whole operation.
[Reported on Gitter](https://gitter.im/dotnet/orleans?at=55d7b10f71a13606576b13f0) by @galvesribeiro .

Removed redundant InitializeMembershipTable  WithTimeout(AzureTableDefaultPolicies.TableOperationTimeout).

---

src/TesterInternal/MembershipTests/ZookeeperMembershipTableTests.cs

The Initialize method in ZookeeperMembershipTableTests is marked as [TestInitialize] method, but it is private.
The method is actually called explicitly at the beginning of each test case, so just remove [TestInitialize] attribute because we don't want / need test framework to call that method.
Failure mode:
Method UnitTests.MembershipTests.ZookeeperMembershipTableTests.Initialize has wrong signature.  The method should be marked public.

Wrong method signature for [TestInitialize] method.

---

src/OrleansAzureUtils/Hosting/AzureSilo.cs

Otherwise, use what was already specified instead of always forcing ReminderServiceProviderType.AzureTable.

SetReminderServiceType in AzureSilo only if NotSpecified or ReminderTableGrain.

---

src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql

Updating the `MembershipReadRowKey` query to properly filter by DeploymentId. Today, if multiple DeploymentId's are present in the database, the query would return a rows for all DeploymentId's, leading to Orleans startup errors.

Fix SQL Query for Multiple Deployment ID's

---

src/TesterInternal/TesterInternal.csproj

This cleans up the build + test process a few more baby steps....
With VsTest getting the right "extra" binaries / files available during the tests is now all done through [DeploymentItem] attributes. 
With NUnit, it is all done with ShadowCopy and CopyToOutputDirectory settings.
The TestInput directory is no longer needed / used.

The TestInput directory is not needed / used any longer.

---

src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Messaging/SqlMembershipTable.cs
src/Orleans/Runtime/Constants.cs
src/Orleans/SystemTargetInterfaces/IReminderTable.cs
src/OrleansAzureUtils/Storage/AzureBasedReminderTable.cs
src/OrleansProviders/SQLServer/SqlStatisticsPublisher.cs
src/OrleansRuntime/ReminderService/GrainBasedReminderTable.cs
src/OrleansRuntime/ReminderService/LocalReminderService.cs
src/OrleansRuntime/ReminderService/MockReminderTable.cs
src/OrleansRuntime/ReminderService/ReminderTable.cs
src/OrleansRuntime/ReminderService/SqlReminderTable.cs
src/OrleansRuntime/Silo/SiloHost.cs
src/TesterInternal/RemindersTest/SqlRemindersTableTests.cs

This also solves #569.
Main changes :
* Kept the current defaults (SQL server as the default invariant name)
* Kept the current behavior when reading config from xml
* Changes in **GlobalConfiguration**
* Added AdoInvariant
* Added DataConnectionStringForReminders & AdoInvariantForReminders which, if set, overrides DataConnectionString & AdoInvariant only for reminders.
* Changes in **ClientConfiguration**
*  Added AdoInvariant

add ado invariant and reminders overrides to config

---

src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/OrleansZooKeeperUtils/OrleansZooKeeperUtils.csproj
src/OrleansZooKeeperUtils/packages.config

This update removes redundant package dependencies from the .NETPlatform5.0 target platform.

ZK MBR -  update ZooKeeperNetEx to 3.4.6.1005

---

src/Orleans/Streams/PubSub/PubSubPublisherState.cs
src/Orleans/Streams/PubSub/PubSubSubscriptionState.cs
src/OrleansTestingHost/Extensions/TestConfigurationExtensions.cs

Json serialization of PubSub state classes was broken by mistake in #687 (as part of fixing Orleans's serialization). Reported in #752.

Fixed broken Json serialization of PubSub state classes.

---

src/Orleans/Streams/PersistentStreams/StreamQueueBalancerType.cs
src/OrleansRuntime/Streams/QueueBalancer/BestFitBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/DeploymentBasedQueueBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/StreamQueueBalancerFactory.cs

Updated deployment based queue balancer to support not rebalancing queues when silos are unavailable.  This mode always uses the ideal distribution of queues, regardless of cluster state.
This PR also reduced the state stored in the deployment based queue balancer to make it more resilient to missing silo status updates.

Static stream queue distribution

---

src/Orleans/RelationalStorage/DbExtensions.cs
src/Orleans/RelationalStorage/OrleansRelationalExtensions.cs
src/Orleans/RelationalStorage/QueryConstantsBag.cs
src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql

While integrating MySql as a reminders provider I came across a problem with DateTime2.
This type is MS SQL specific. Some ADO providers like Oracle seems to be ok with it. Unfortunately, MySql doesn't handle that well. My solution is to replace DbType.DateTime2 with DbType.DateTime. The underlying DB table can have DateTime2 or DateTime column type, I tested this on SQL Server.
I am not a db expert, but it seems to me that this isn't a MySql specific issue, and also that some milliseconds precision loss is irrelevant in Orleans. I am sure @veikkoeeva can shed some light.
Currently, I've conveted only the reminders related script, so I wasn't sure if it's PR worthy. Also, I haven't added the constants needed for testing. I plan to provide the full script with all the testing constants in …

DateTime2->DateTime and Adding constants for MySql

---

src/Orleans/Streams/QueueAdapters/IQueueCacheCursor.cs
src/OrleansProviders/Streams/Common/SimpleQueueCache.cs
src/OrleansProviders/Streams/Common/SimpleQueueCacheCursor.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Stream consumer cursor (for persistent streams) has a field  State , which tracks if this cursor is active or not (Active means points to a valid data in the cache, Inactive means points outside the cache, waiting for the new data to arrive). That state field was updated in a different turn in the pulling agent from where the actual pointer into the cache was updated. As a result, due to interleaving of turns in the agent, we could get into a rare inconsistent situation, where the cursor will not be updated correctly.
Fixed by Refreshing the cursor state, to prevent the interleaving bug.
That is a different fix to the problem reported in  #759.

Added Refresh to cache cursor to solve cursor reentrancy bug.

---

src/Orleans/Streams/QueueAdapters/IQueueAdapterReceiver.cs
src/Orleans/Streams/QueueAdapters/IQueueCache.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapterReceiver.cs
src/OrleansProviders/Streams/Common/SimpleQueueCache.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

This fixes an old standing bug reported in #166 about Azure Queue stream provider not guaranteeing at-least-once delivery. The old code used to delete msgs from the queue after they have been pulled but before they have been delivered and processed.
This PR fixes that. Now the msg is retrieved from the queue, put in the cache, delivered to all stream consumers of that stream and only after all consumers have processed this msg it will be deleted from the underlying Azure Queue.

Delete msgs from Azure Queue only after they have been delivered and processed.

---

src/Orleans/Configuration/ClusterConfiguration.cs

Using the `ClusterConfiguration(TextReader input)` constructor would throw an exception at a later time because the `listeners` field only was initialized in the default constructor. Initialization of `listeners` has been moved to the field initializer.

Fix bug in ClusterConfiguration(TextReader input) constructor

---

src/OrleansAzureUtils/Storage/AzureStorageUtils.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloHost.cs

Changed `NonExistentActivation`  from `Warning` to `Info`.
More details in` DeactivateActivationOnIdle` logging.
Move preamble logging from `SiloHost` to `Silo` object, so works always for all hosts.
Warn upon `!GCSettings.LatencyMode.Equals(GCLatencyMode.Batch))`

Improved logging in multiple places.

---

src/Orleans/Streams/Providers/IStreamProviderRuntime.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapterReceiver.cs
src/OrleansRuntime/MembershipService/ISiloStatusOracle.cs
src/OrleansRuntime/MembershipService/MembershipOracle.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingManager.cs
src/OrleansRuntime/Streams/QueueBalancer/BestFitBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/DeploymentBasedQueueBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/StreamQueueBalancerFactory.cs
src/Tester/OrleansConfigurationForStreaming4SilosUnitTests.xml
src/Tester/StreamingTests/DelayedQueueRebalancingTests.cs
src/Tester/StreamingTests/SampleStreamingTests.cs
src/Tester/StreamingTests/StreamTestsConstants.cs
src/Tester/Tester.csproj

Implemented delayed repartitioning of queues in queue balancer. 
When silo start up, they divide the multiple streaming queues between themselves, by using a dynamic queue balancing algorithm. The algorithm assigns queue to silos such that:
1) every queue is assigned to exactly one silo.
2) the number of queues per silo are equal (up to rounding).
3) in case of silo failures or additions, queue are dynamically rebalanced to adhere to the above 2 conditions.
4) the number of queue responsibility reassignments is minimized such that we try to minimize movements of a queues from one silo to another to as less as possible.
The previous implementation tried to achieve all those goals, but was not doing a good job on the last requirement. Specifically, in the case of all silos staring at …

Delayed repartitioning of stream queues

---

src/Build/GlobalAssemblyInfo.cs
src/ClientGenerator/CSharpCodeGenerator.cs
src/ClientGenerator/ClientGenerator.cs
src/ClientGenerator/CodeGeneratorBase.cs
src/ClientGenerator/FSharpCodeGenerator.cs
src/ClientGenerator/NamespaceGenerator.cs
src/ClientGenerator/Program.cs
src/ClientGenerator/Properties/AssemblyInfo.cs
src/ClientGenerator/Serialization/SerializationGenerator.cs
src/ClientGenerator/Serialization/SerializerGenerationManager.cs
src/ClientGenerator/Serialization/SerializerGenerationUtilities.cs
src/ClientGenerator/VBCodeGenerator.cs
src/Orleans.sln.DotSettings

ReSharper Code Cleanup Settings
This is a first attempt to address some of the outstanding issues with code normalization / auto-cleanup that @attilah mentioned in PR #709 
> It is a habit that pushing Ctrl+K, Ctrl+D to reformat the code and since no solution level settings exists for the project it will be different for everyone. I'll try to not to reformat the code, but having a Resharper code formatting setting for the solution in place would help a lot for situations like this.
I could not find any specific guidance on a "best-practice" set of code cleanup settings for ReSharper, so this is my strawman best-guess to start some community discussion. :)
Feel free to chime in if you have any suggestions or experience about a good set of settings to use.
I also ran ReSharper code-cleanup …

ReSharper code cleanup settings

---

src/NuGet/CreateOrleansPackages.bat
src/NuGet/Microsoft.Orleans.Client.nuspec
src/NuGet/Microsoft.Orleans.Core.nuspec
src/NuGet/Microsoft.Orleans.CounterControl.nuspec
src/NuGet/Microsoft.Orleans.OrleansAzureUtils.nuspec
src/NuGet/Microsoft.Orleans.OrleansHost.nuspec
src/NuGet/Microsoft.Orleans.OrleansManager.nuspec
src/NuGet/Microsoft.Orleans.OrleansProviders.nuspec
src/NuGet/Microsoft.Orleans.OrleansRuntime.nuspec
src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/NuGet/Microsoft.Orleans.Templates.Grains.nuspec
src/NuGet/Microsoft.Orleans.Templates.Interfaces.nuspec
src/NuGet/Microsoft.Orleans.TestingHost.nuspec

These will let us easily build and publish NuGets with symbols to SymbolSource.org.
I added OrleansConfiguration.xsd to the Client package because it was failing to build as is for no obvious reason. It won't hurt to have the xsd in the Client package I think.

Add building of symbols NuGets

---

src/OrleansRuntime/Streams/QueueBalancer/BestFitBalancer.cs
src/TesterInternal/OrleansRuntime/Streams/BestFitBalancerTests.cs

Initial Ideal distribution algorithm was naïve.  It assigned upper bound queues per silos until queues run out.  With 100 queues and 30 silos, upper bound would be 4.  With 4 queues per silo, we’d run out of queues after 25 silos.  This means 5 remaining silos would get 0 queues.
Ideal distribution now assigns upper bound of queues per silo to as many silos as it can, then the upper bound -1 to the rest.  This will produce a more even distribution.

Best fit balancer ideal distribution fix

---

src/OrleansProviders/Streams/Common/EventSequenceToken.cs

I need it in order to implement my own QueueCache solution.
Thanks.

Made EventSequenceToken.NextSequenceNumber public

---

src/OrleansRuntime/Streams/QueueBalancer/BestFitBalancer.cs
src/TesterInternal/OrleansRuntime/Streams/BestFitBalancerTests.cs

Best Fit Balancer did not balance resources correctly when resource count was evenly divisible by silo count.
There was a bug in the test that let this slide through.
Balancer fixed, test fixed, more tests added.

Best Fit Balancer - divisible resource fix

---

src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql

Although omission of these commad do not cause a bugs,
it is nevertheless better to adhere to a stricter comma rules.

A fix to add missing commas to SQL clauses

---

src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Core/GrainTimer.cs

Also, Clear RequestContext  before DeactivateAsync and Timers callbacks.

Set RequestContext before ActivateAsync.

---

src/Orleans/Configuration/NodeConfiguration.cs
src/Orleans/Logging/ErrorCodes.cs
src/OrleansRuntime/Silo/SiloHost.cs

This is needed when a silo runs as a separate process and needs to be told to gracefully shutdown.

Added a manual reset event that signals to silo to shut down

---

src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Catalog/Catalog.cs

Usually, activation is removed from the `ActivationCollector` when the collector itself decides to deactivate it (based on the idle period).
But there are also the cases of `DeactivateActivationOnIdle` called by grain code itself or bulk deactivation in the shutdown scenario. In those cases we mark the activation as `ActivationState.Deactivating`, do the whole multi step deactivation process and only at the end remove this activation from the collector [here](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Catalog/Catalog.cs#L346). 
This could cause [this warning](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Catalog/ActivationCollector.cs#L246) to fire in the ActivationCollector, catching a race when the collector finds an activation which is already …

Remove activation from the ActivationCollector early upon call to DeactivateActivationOnIdle.

---

src/Orleans/CodeGeneration/TypeUtils.cs
src/TestGrains/MyObserverSubscriptionManager.cs
src/TestGrains/TestGrains.csproj

This should fix https://github.com/dotnet/orleans/issues/837 by defaulting to full type names in serializer code generation.

Default to full type names in codegen in TypeUtils.GetTemplatedName()

---

src/Tester/SerializationTests.cs

This Serialization test will throw an exception during deserialization.
It is because the "input" object is inlcuded in the inner collection.  Thus when deserializing, the Deserializer thinks that it has already deserialized the object when in fact it is technically still doing it.
The test works fine when using the .NET serializer.
The Serialization classes included were based off the auto-generated classes in my project where I discovered this bug.

Recursive Serialization Issue

---

src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Startup/ConfigureServicesBuilder.cs
src/OrleansRuntime/Startup/ConfigureStartupBuilder.cs
src/Tester/DependencyInjectionGrainTests.cs

Small set of changes (completely syntactical, no logic change) to DI PR #827.
Moved Startup Builder methods into a separate class.
Addressed @veikkoeeva 's comment https://github.com/dotnet/orleans/pull/827#discussion_r40240424.

Small DI refactoring.

---

src/Orleans/Runtime/IRuntimeClient.cs
src/Orleans/Runtime/ISchedulingContext.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Core/GrainTimer.cs
src/OrleansRuntime/Core/InsideGrainClient.cs
src/OrleansRuntime/Core/SystemTarget.cs
src/OrleansRuntime/Scheduler/SchedulingContext.cs
src/OrleansRuntime/Scheduler/ShedulerExtensions.cs
src/OrleansRuntime/Scheduler/WorkItemGroup.cs
src/OrleansRuntime/Scheduler/WorkerPoolThread.cs

Capture correctly executing work item for all workitem in the worker thread (used to capture only non work item groups).
Print more details of `WorkItemGroup` status (`DumpStatus()`), available via `SchedulingContext.DetailedStatus()`:
* for activation data: detailed status report, including currently executing request.
* for system target: detailed status report, including currently executing request.
* for timers: timer name (needed to pipe timer name via scheduler to `ClosureWorkItem`).

More details diagnostics in the Scheduler.

---

src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs

`PubSubRendezvousGrain`'s continuation of `AddSubscriber` will be cancelled in the success case, which causes an exception when it is awaited below. This is not affecting tests currently because of #847.
This PR removes the `OnlyOnFaulted` condition from that continuation and adds `ExecuteSynchronously` for good measure.

PubSubRendezvousGrain: always execute AddSubscriber continuation

---

src/TestGrainInterfaces/IExceptionGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/ExceptionGrain.cs
src/TestGrains/TestGrains.csproj
src/Tester/ExceptionPropagationTests.cs
src/Tester/Tester.csproj

This tests that task cancellations are correctly propagated from grain methods to the caller.
Issue open in #847.

Add broken test for grain method task cancellation.

---

src/OrleansProviders/Streams/Common/EventSequenceToken.cs

We need this is well to implement our custom cache for our PersistentStreamProvider.

Exposed the SequenceNumber in the EventSequenceToken

---

src/OrleansProviders/Streams/Common/SimpleQueueCache.cs
src/OrleansProviders/Streams/Common/SimpleQueueCacheCursor.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/TestGrainInterfaces/IMultipleSubscriptionConsumerGrain.cs
src/TestGrains/MultipleSubscriptionConsumerGrain.cs
src/Tester/StreamingTests/AQSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/SubscriptionMultiplicityTestRunner.cs

The cache cursor for the first stream is becoming inactive while there is data still being delivered on the second stream. Since data is being delivered on the second stream the cache is moving forward in time and when we try to refresh the cache cursor for the first stream, it is older than any of the data in the cache, so it throws a cache miss.
When we refresh a cursor, if it's token is no longer in the cache, we start from the oldest data in the cache.

QueueCacheMissException #844 Fix

---

src/OrleansAzureUtils/Hosting/AzureSilo.cs

Host.Config is always loaded and is safe to use, config isnt safe in case using AzureSilo Start() method.

 Fixed AzureSilo config null reference exception

---

src/Orleans/Messaging/ByteArrayBuilder.cs

Issue https://github.com/dotnet/orleans/pull/843 exposed 2 bugs in the serializer related to cyclic data structures (data structure that has a cycle of references).
This PR fixes the first, minor bug: `ByteArrayBuilder`  used to [initialize currentOffset to -1] (https://github.com/dotnet/orleans/blob/master/src/Orleans/Messaging/ByteArrayBuilder.cs#L68), which caused the [`ByteArrayBuilder.Leght`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Messaging/ByteArrayBuilder.cs#L120) property to be -1 as the the first object used in the [`SerializationContext.RecordObject`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/SerializationContext.cs#L119).
As a result, the wrong offset (-1) was recorded when serializing cyclic data structure into a byte array. …

Fixed a bug in ByteArrayBuilder about setting initial offset to -1 instead of 0

---

src/Tester/DeactivationTests.cs
src/Tester/Tester.csproj

This is just to confirm there is no crazy long time between deactivation and reactivation of a grain.

Added a test to validate deactivation-reactivation time

---

src/Orleans/Streams/PubSub/ImplicitStreamPubSub.cs
src/Orleans/Streams/PubSub/PubSubSubscriptionState.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs

The filter is passed to ctor and then added again by calling `AddFilter(filter)` few lines later. The logic inside `AddFilter()` happily creates `OrFilter` which now contains exact same filters, leading to filter called twice,

Fix bug with creation of duplicate filter

---

src/OrleansProviders/Streams/Common/EventSequenceToken.cs

In our consumer grains we persist the received `EventSequenceToken` in a JSON based storage. Replaced the private members with public properties for the serialization to work.
`GetSequenceToken` was removed as it's not needed anymore after this change.

Changed EventSequenceToken private members to public properties

---

README.md

Installation is typically performed via NuGet, so this adds references to the required packages.
The MSI is gone, so references to that were removed.

Remove reference to MSI, add references to NuGet.

---

src/Orleans/Core/Grain.cs

This will allow grain subclasses to add or replace grain behaviour. This
can be useful for testing, monitoring or adding new functionality.

Make Grain methods virtual

---

src/Orleans/Configuration/ClusterConfiguration.cs
src/OrleansRuntime/Core/ManagementGrain.cs

This reverts commit 75dd8e1d26418cb97b506063b93ba0b1efa01c9b.
This commit broke functional tests. `text.ToString();` for some reason returns a empty string. Reverting the commit for now.

Revert "Replaced XmlTextWriter with XmlWriter.Create"

---

src/Orleans/Configuration/ClusterConfiguration.cs
src/OrleansRuntime/Core/ManagementGrain.cs

#916. The reason of empty string being returned was missing call to flush.

Coreclr compatibility:XmlTextWriter -> XmlWriter.Create

---

src/OrleansSQLUtils/Messaging/SqlMembershipTable.cs

The rational is explained at https://github.com/aspnet/Security/issues/59.
"One last remark: you should avoid using Task.Result and Task.Wait as
much as possible as they always encapsulate the inner exception in an
AggregateException and replace the message by a generic one (One or
more errors occurred), which makes debugging harder. Even if the
synchronous version shouldn't be used that often, you should strongly
consider using Task.GetAwaiter().GetResult() instead."
This leaves aside another possibility to refactor, namely that of
making the interface method asynchronous.

Refactor .Result to .GetAwaiter().GetResult() to preserve stacktrace

---

src/OrleansRuntime/Core/Dispatcher.cs

Avoid unobserved task exception when logging a message rejection without an exception.

Avoid unobserved task exception when logging in RejectMessage

---

src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql

The silo and client metrics update queries are missing where clauses to scope the update to the appropriate rows.

Fix SQL Server Metrics Update Queries

---

README.md

The documentation header in the readme should be clickable, linking to the documentation.

README: Documentation heading link

---

src/Orleans/Serialization/BuiltInTypes.cs
src/Orleans/Serialization/DeserializationContext.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansCodeGenerator/SerializerGenerator.cs
src/TestGrainInterfaces/ICircularStateTestGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/CircularStateTestGrain.cs
src/TestGrains/TestGrains.csproj
src/Tester/GenericGrainTests.cs
src/Tester/SerializationTests.cs
src/TesterInternal/General/BuiltInSerializerTests.cs

This fix for #852 is based on @gabikliot's suggestions in that thread.
I have also included @galvesribeiro's tests for that bug. @galvesribeiro's test uses generated code, unlike the existing `SerializationTests_RecursiveSerialization`. I am not sure if the latter should be kept given it needed to be modified to pass the test.

Fix #852 - record deserialized objects before deserialization has completed

---

src/OrleansRuntime/Messaging/Gateway.cs

Code assumed that exception thrown was something other than ObjectDisposedException, socket had not been disposed.  This is not a safe assumption.  Calling RemoteEndPoint on a disposed socket can throw, breaking us out of he expected error handling path, so we now ignore any exceptions from that call.

Ignore exceptions when getting endpoint on socket error.

---

src/Orleans/CodeGeneration/GrainState.cs

Fixing #951  - incorrect handling of read-only properties in GrainState SetAll and ResetProperties

Fix for #951 - attempt to set read-only properties

---

src/OrleansRuntime/GrainDirectory/GrainDirectoryPartition.cs

This is a fix for https://github.com/dotnet/orleans/issues/954.

Fixed the maturity check condition in the directory cleanup logic.

---

src/Orleans/Orleans.csproj
src/Orleans/Streams/Predicates/DefaultStreamFilterPredicateWrapper.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

We were only checking to see if the batch should be delivered if there was a filter specified.  Batch can now be filtered even if no filter is applied.

Check to see if stream batches should be delivered even if no filter is provided.

---

src/TestGrainInterfaces/Properties/AssemblyInfo.cs

This is a leftover from https://github.com/dotnet/orleans/pull/910.

Remove strong name left behind in [InternalsVisibleTo]

---

src/Orleans/CodeGeneration/CodeGeneratorManager.cs
src/OrleansCodeGenerator/CodeGeneratorCommon.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs

There was not a clearly defined order in the execution of the following:
* The AssemblyLoad hook which registers assemblies which have had their code generated at compile-time; and
* The AssemblyLoad hook which ensures that all assemblies have been passed to the code generator.
This fix removes the registration hook from `RoslynCodeGenerator` and registers assemblies just before considering them for code generation. The ordering is now more clearly defined and closer to being "obviously not deficient" rather than "not obviously deficient"
The fix also improves logging around failed code generation.

Ensure codegen registers all assemblies before generating new code

---

src/ClientGenerator/ClientGenerator.cs
src/Orleans.SDK.targets
src/Orleans/Orleans.csproj

This fix cleans up the ClientGenerator project somewhat (as a part of the post-#528 work) and also implements a quick fix to Orleans.csproj's bootstrap process whereby the command line was too long and characters would randomly be dropped.
The bootstrap process does not need to pass a list of source files to the code generator since it no longer compiles assemblies itself.

Cleanup ClientGenerator & Orleans.csproj bootstrap

---

src/NuGet/Microsoft.Orleans.Client.nuspec
src/NuGet/Microsoft.Orleans.OrleansRuntime.nuspec
src/NuGet/Microsoft.Orleans.Server.nuspec
src/Orleans/CodeGeneration/CodeGeneratorManager.cs
src/Orleans/CodeGeneration/ICodeGeneratorCache.cs
src/Orleans/Orleans.csproj
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs
src/OrleansRuntime/OrleansRuntime.csproj
src/OrleansRuntime/Silo/Silo.cs
src/Tester/CodeGenTests/RuntimeCodeGenerationTests.cs
src/Tester/Tester.csproj

As the title suggests.
We can include OrleansCodeGenerator in one of the NuGet meta-packages to save the end-user the hassle/confusion of having to manually pull it in. Users who wish to use compile-time code generation then have the option of avoiding the Roslyn dependency altogether.

Remove static dependency on OrleansCodeGenerator in OrleansRuntime

---

src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql

As discussed with @veikkoeeva in #932, removing the MembershipReadAll view in the SQL Server storage provider. This ensures all Orleans table and view names are prefixed with "Orleans". In addition, this provides consistency between the MembershipReadRowKey and MembershipReadAllKey queries.

Remove MembershipReadAll View in SQL Provider

---

src/OrleansTestingHost/TestingSiloHost.cs
src/Tester/CodeGenTests/RuntimeCodeGenerationTests.cs
src/Tester/ExceptionPropagationTests.cs

Commit by Maxim Terletsky <maxim@gigya-inc.com>
On branch: refs/heads/feature/MakingGrainFactoryStaticInTestingSiloHost
According to issue
https://github.com/dotnet/orleans/issues/962

Make GrainFactory static in TestingSiloHost

---

src/Tester/UnitTestSiloHost.cs

- Add missing `[DeploymentItem]` to ensure the `OrleansCodeGenerator.dll` assembly is shadow copied into the tests runtime directory.
Failure Mode:
```
[2015-11-08 05:55:09.462 GMT    19 WARNING 101722 CodeGenerator ] Could not load file or assembly 'OrleansCodeGenerator' or one of its dependencies.
The system cannot find the file specified.
Exc level 0: System.IO.FileNotFoundException: Could not load file or assembly 'OrleansCodeGenerator' or one of its dependencies.
The system cannot find the file specified.
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at …
```

OrleansCodeGenerator.dll not found during test runs.

---

src/Orleans/Serialization/SerializationManager.cs
src/Tester/SerializationTests.cs

SerializationManager - The Register method must be public static void.
- Classes marked with a `[RegisterSerializer]` attribute need to provide a `public static void Register()` method.
- The test code for `JsonSerializationExample2` class incorrectly had `private` Register() method, so this PR fixes that (SerializationTests.cs line 305).
Failure Mode:
```
[2015-11-08 04:31:06.643 GMT    15 WARNING 102402 SerializationManager ] Type JsonSerializationExample2 from assembly Tester has the RegisterSerializer attribute but no Register static method
```
- The SerializationManager error message printed in the silo log [above] is slightly ambiguous because it does not mention that the `Register()` method needs to be `public`, so fixed that to be more explicit and clear.
- Added "JSON" tag to the …

[RegisterSerializer] - Register method must be public static void.

---

src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql
src/OrleansSQLUtils/Storage/OrleansRelationalExtensions.cs

I'm currently completing the MySQL ADO Invariant implementation in Orleans.
This includes creating a complete MySQL setup script as available in MSSQL and adding relevant tests.
While converting *CreateOrleansTables_SqlServer.sql* to MySQL I came across what IMHO is a bug.
In current implementation, the **UpdateIAmAlivetimeKey** script updates the **ETag** field.
The **IAmAliveTime** is a purely informative field and isn't a part of the membership protocol.
This will cause silos to unnecessarily fail periodically when trying to update the membership table.
My solution is to use the MSSQL 2000 implementation for all versions of MSSQL, with the minor change of not updating the **ETag** in **UpdateIAmAlivetimeKey**.
@veikkoeeva what do you think?

MSSQL Script - Fields defaults and Updating IAmAlive without ETag

---

src/ClientGenerator/ClientGenerator.cs
src/Orleans/ApiPortabilityAnalysis.htm
src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/AssemblyLoader/AssemblyLoaderCriteria.cs
src/Orleans/CodeGeneration/GrainFactoryBase.cs
src/Orleans/CodeGeneration/GrainInterfaceData.cs
src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/Configuration/ApplicationConfiguration.cs
src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Core/GrainFactory.cs
src/Orleans/Providers/ProviderTypeLoader.cs
src/Orleans/Runtime/GrainInterfaceMap.cs
src/Orleans/Serialization/BuiltInTypes.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Serialization/TypeUtilities.cs
src/Orleans/Utils/Utils.cs
src/OrleansCodeGenerator/GrainMethodInvokerGenerator.cs
src/OrleansCodeGenerator/GrainReferenceGenerator.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs
src/OrleansCodeGenerator/SerializerGenerator.cs
src/OrleansCodeGenerator/Utilities/SyntaxFactoryExtensions.cs
src/OrleansRuntime/GrainTypeManager/GenericGrainTypeData.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs
src/OrleansRuntime/GrainTypeManager/SiloAssemblyLoader.cs
src/TesterInternal/General/SerializationTests.cs

Moved calls from Type -> TypeInfo to comply with CoreCLR API compatibility at #368
For now, just moved all calls made directly to Type.XXX to TypeInfo.XXX in order to be compatible with CoreCLR apis.
The idea was to keep current Orleans code as is, and only change what is necessary. Later on, I'll create another PR (after coreclr is fully supported on Orleans) and change all APIs that uses Type to use TypeInfo since everything from Type can be accessible from TypeInfo members. (refactor task)
Feedback is always welcome.

[CoreCLR port] Type -> TypeInfo 

---

src/Clean.cmd
src/Orleans/Streams/Predicates/FilterPredicateWrapperData.cs
src/Test.cmd
src/TestAll.cmd
src/TestGrainInterfaces/IActivateDeactivateWatcherGrain.cs
src/TestGrainInterfaces/IStreamLifecycleTestGrains.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/ActivateDeactivateWatcherGrain.cs
src/TestGrains/StreamLifecycleTestGrains.cs
src/TestGrains/TestGrains.csproj
src/Tester/OrleansConfigurationForStreamingTesting_SMS.xml
src/Tester/StreamingTests/StreamFilteringTests.cs
src/Tester/Tester.csproj
src/Tester/packages.config

Add StreamFilteringTests to GitHub test suite.
- Add StreamFilteringTests test cases from Orleans Functional test suite.
- Use FluentAssertions package for easier way to express expected outcomes in test cases.
- Changed default namespaces set in TestGrains.csproj and TestGrainInterfaces.csproj to match the current naming convention we use.

Add Stream Filter tests from Functional Test Suite.

---

src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Runtime/ISchedulingContext.cs
src/Orleans/Statistics/StatisticsCollector.cs
src/OrleansRuntime/Scheduler/IWorkItem.cs
src/OrleansRuntime/Scheduler/OrleansTaskScheduler.cs
src/OrleansRuntime/Scheduler/WorkItemBase.cs
src/OrleansRuntime/Scheduler/WorkItemGroup.cs
src/OrleansRuntime/Scheduler/WorkQueue.cs

This is a bug fix to the bug reported in #930.
Explanation:
In the silo shutdown sequence we:
a) stop application
b) stop providers
c) stop the system
Pulling agents are used by the persistent stream providers. Those agents are implemented as "low priority system targets". That means they are just like regular system targets from all perspectives except that in the scheduler they are handled the same way as application (grains) - they have regular priority (they do not receive a special high priority treatment as regular system targets). It was done this way so that pulling agents could not starve the high priority system activities.
The bug was that when we stop application turns and all application work items groups in the scheduler, we also stop the low priority system targets. As a …

Do not stop low priority system targets before providers are stopped.

---

src/Tester/StreamingTests/AQSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/SMSSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/SubscriptionMultiplicityTestRunner.cs

These were added as an attempt to reproduce github issue:
> "Can't get custom PersistentStreamProvider to work with any non-grain observer #1022"

Added tests to subscribe from streams (SMS and AQ) from client.

---

src/OrleansAzureUtils/Storage/AzureStorageUtils.cs
src/OrleansAzureUtils/Storage/AzureTableDataManager.cs
src/TesterInternal/App.config

Updated azure storage call patterns to be compatible with azure storage 6.1
The issue stemmed from the fact that the call signature for TableOperation.Retrieve<T> changed between azure storage 5.x and 6.x
< 6.x - public static TableOperation Retrieve<TElement>(string partitionKey, string rowkey) where TElement : ITableEntity
\> 6.x - public static TableOperation Retrieve<TElement>(string partitionKey, string rowkey, List<string> selectColumns = null) where TElement : ITableEntity
To address this, the table query call using Retrieve<T> was replaced with a newer azure storage call pattern using TableQuery.
There are a number of different ways to form such a query, but this one was selected because it demonstrated improved performance characteristics over some of the simpler patterns.  This …

AzureStorage 6.1 compatibility

---

src/Orleans/Logging/ErrorCodes.cs
src/OrleansRuntime/Silo/Silo.cs

This should enhance the original fix of https://github.com/dotnet/orleans/pull/1007 to also handle the case when OrleansDependencyInjection.dll is present but its dependencies (ASP.NET DI assemblies) are missing.
I didn't want to eat all exceptions, only FIleNotFoundExceptions. Any other exception will still fail silo startup. I'm not sure if there is a better option here.

Add special handling of FIleNotFoundException while trying to load DI startup builder

---

src/Orleans/CodeGeneration/GrainInterfaceData.cs
src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansCodeGenerator/SerializerGenerator.cs
src/TestGrainInterfaces/CodegenTestInterfaces.cs
src/TestGrains/SerializationGenerationGrain.cs
src/TestGrains/TestGrains.csproj
src/Tester/CodeGenTests/GeneratorGrainTest.cs

Currently the serializers use `FieldInfo.GetValue`/`FieldInfo.SetValue` to access/mutate inaccessible fields.
This PR introduces an IL-based method for getting/setting fields which allows us to avoid most boxing and access restrictions.
In the second commit, I remove the call to `RecordObject` in generated Deserializer methods becausei it is not applicable when deserializing a value type. Please correct me if I am wrong.

CodeGen: replace FieldInfo getters/setters with IL-based getters/setters

---

src/OrleansRuntime/GrainDirectory/AdaptiveGrainDirectoryCache.cs
src/OrleansRuntime/GrainDirectory/GrainDirectoryCacheFactory.cs
src/OrleansRuntime/GrainDirectory/IGrainDirectoryCache.cs
src/OrleansRuntime/GrainDirectory/LRUBasedGrainDirectoryCache.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs

List of grain activations in local cache are now read only.  This forces immutable treatment of these lists, preventing enumeration and modification of the list from occurring at the same time.
The reported manifestation of the problem was that the call `GetLocalCacheData` was throwing an exception because it was iterating over the list of activations while that list was being modified in another thread.  This was fairly rare.
The `GetLocalCacheData` call is made in a grains turn while making a grain call.  This means it may be commonly called by many threads and needs to be thread safe.  It was not thread safe because the calls `AdjustLocalCache`, `RegisterAsync`, and `InvalidateCacheEntry` all modified the inner list with no thread synchronization.
Rather than adding thread …

Grain activation local cache threading fix 

---

src/Orleans/Statistics/RuntimeStatisticsGroup.cs

For #1040 and related to #368 
Currently I've just ifdeffed my way around the incompatible `ManagementObject` code for getting total physical memory.
This means on Core CLR the value for `RuntimeStatisticsGroup.TotalPhysicalMemory` will always be 0. I thought this should be fine because the `RuntimeStatisticsGroup.AvailableMemory` can also be 0.

Ifdeffing non-coreclr RAM perf counter

---

src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs

Fire and forget delivery was defaulting to true in SimpleMessageStreamProvider when unspecified in the FireAndForgetDelivery attribute.

Fixed fire and forget delivery default in SimpleMessageStreamProvider

---

src/Local.testsettings

The relational tests could not be run because of missing
SQL scripts. This is fixed by adding them to Local.testsettings.

Fixed relational tests

---

src/Orleans/CodeGeneration/GrainInterfaceData.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/TesterInternal/General/InterfaceRules.cs

This is a fix for https://github.com/dotnet/orleans/issues/1044 which was a regression with codegen errors caused by violations of grain interface rules not appearing in the VS Error List window anymore.

Add back explicit grain interface validation to codegen

---

src/.nuget/packages.config
src/Tester/FSharpGrainTests.cs
src/Tester/SerializationTests.FSharpTypes.cs

- Remove from the Functional suite the F# test cases currently expected to fail.
- Cleanup of unused imports.
- VS2013 auto-added the FSharp.Compiler.Tools package to the .sln level nuget packages.config list.

Mark F# test cases currently expected to fail.

---

src/Orleans/Core/Grain.cs
src/Orleans/Orleans.csproj
src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Providers/DefaultServiceProvider.cs
src/Orleans/Providers/IProviderRuntime.cs
src/Orleans/Providers/StatisticsProviderManager.cs
src/Orleans/Runtime/GrainRuntime.cs
src/Orleans/Runtime/IGrainRuntime.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapterFactory.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/SimpleAzureQueueAdapterFactory.cs
src/OrleansDependencyInjection/ConfigureStartupBuilder.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Storage/StorageProviderManager.cs
src/Tester/TestStreamProviders/Controllable/ControllableTestStreamProvider.cs
src/Tester/TestStreamProviders/Generator/GeneratorAdapterFactory.cs

The plan is to have dependencies injected via property and/or constructor injection by the DI system.  Currently, `Microsoft.Framework.DependencyInjection` is in beta, so we can't rely on it in the framework.  This is preventing us from using any DI capabilities until it is released.
This change exposes the Service Provider to grains and providers so we can start using injected dependencies.  Once `Microsoft.Framework.DependencyInjection` is released, we can removed these framework hooks and let the DI system provide any dependencies, as planned.

Exposed ServiceProvider to Grains and Providers.

---

src/OrleansAzureUtils/Storage/AzureQueueDataManager.cs
src/Tester/StreamingTests/AQSubscriptionMultiplicityTests.cs

Two issues addressed:
1) AzureQueueDataManager initialization was not thread safe.
2) Until we fix issue #1069, tests accessing PersistentStreamProviders from clients must have gateways configured for all silos in the cluster.

Fixed intermittent failure of test AQSubscribeFromClientTest.

---

src/Orleans/Configuration/MessagingConfiguration.cs
src/Orleans/IDs/ActivationAddress.cs
src/Orleans/IDs/UniqueIdentifier.cs
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Serialization/BinaryFormatterSerializer.cs
src/Orleans/Serialization/OrleansJsonSerializer.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/packages.config
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueBatchContainer.cs
src/OrleansRuntime/Silo/Silo.cs
src/Tester/StreamingTests/DelayedQueueRebalancingTests.cs
src/Tester/StreamingTests/PullingAgentManagementTests.cs
src/TesterInternal/General/BuiltInSerializerTests.cs
src/TesterInternal/General/FallbackBuiltInSerializationTests.cs
src/TesterInternal/General/FallbackSerializationTests.cs
src/TesterInternal/OrleansRuntime/ExceptionsTests.cs
src/TesterInternal/TesterInternal.csproj

Related to #368.
Default fallback serializer is <code>BinaryFormatter</code>, using of the Json.Net one can be configured through boolean property "UseJsonFallbackSerializer".

 Implemented Json.Net fallback serializer

---

src/Orleans/Runtime/GrainReference.cs

Currently on each grain method call string with debug context is being [allocated](https://github.com/dotnet/orleans/blob/master/src/Orleans/Runtime/GrainReference.cs#L354). 
Sample run of 28k grain methods calls.
Before fix:
After:

Reduce number of allocations during grain method call

---

src/Tester/JsonFallbackSerializationTests.cs
src/Tester/Tester.csproj
src/TesterInternal/General/InternalSerializationTests.cs
src/TesterInternal/TesterInternal.csproj

Fixed ```Warning CS0436 The type 'SerializationTests' in TesterInternal\General\SerializationTests.cs' conflicts with the imported type 'SerializationTests' in 'Tester, Version=1.0.0.0,'``` that was caused by duplicate names of test classes SerializationTests.cs

Fixed build warning

---

src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs

On parallel invoking of the method of the reentrant generic grain the following exception is being thrown due to the parallel access to the non-concurrent dictionary ```cachedGenericInvokers ```. ![2015-11-29_18-02-32](https://cloud.githubusercontent.com/assets/5787619/11458224/d2ba4356-96c4-11e5-8407-5e986fdf5099.png)

Added locking around InvokeData: cachedGenericInvokers insert.

---

src/TesterInternal/General/Identifiertests.cs

Added a missing call to SerializationManager.InitializeForTesting(), absense of which was causing tests failures. For example, it caused a test failure in https://github.com/dotnet/orleans/pull/1082.

Added a missing call to SerializationManager.InitializeForTesting()

---

src/TestGrainInterfaces/SerializerExclusions.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TesterInternal/Serialization/SerializerGenerationTests.cs
src/TesterInternal/TesterInternal.csproj

The grain interfaces and types used in this test help catch issues with overly aggressive generation of serializers by codegen.

Migrated serialization exclusion test

---

src/Tester/FSharpGrainTests.cs
src/Tester/SerializationTests.FSharpTypes.cs

Some of the F# tests were failing due to incorrect checks. 
The remaining failing tests now have the ```Ignore``` attribute, pending the fix in #1080 (also included in  #1077)

Fixed F# tests to allow for null values. Ignore failing tests, pending #1080.

---

src/Orleans/AssemblyLoader/AssemblyProcessor.cs
src/Orleans/CodeGeneration/KnownAssemblyAttribute.cs
src/Orleans/CodeGeneration/KnownTypeAttribute.cs
src/Orleans/Orleans.csproj
src/Orleans/Serialization/TypeUtilities.cs
src/OrleansCodeGenerator/GrainReferenceGenerator.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs
src/Tester/CodeGenTests/IRuntimeCodeGenGrain.cs
src/Tester/CodeGenTests/RuntimeCodeGenerationTests.cs

I think I fixed https://github.com/dotnet/orleans/pull/1080 but adding back the logic of excluding from generating serializers types with fields of inaccessible types.
For some reason, `RuntimeCodeGenTest` is failing. I `[Ignor]`ed it for now.

Fixed CodeGen: Allow [KnownType] & [KnownAssembly] hints, fix AssemblyProcessor scanning

---

src/Build/GlobalAssemblyInfo.fs
src/Tester/FSharpGrainTests.cs
src/Tester/SerializationTests.FSharpTypes.cs

F# Option serialization now works - we can close #1056 once this is merged. I've also streamlined the F# roundtrip serialization tests.

Used [KnownAssembly] to generate F# serializers for testing

---

src/Orleans/Configuration/OrleansConfiguration.xsd

Update the configuration schema to contain the new telemetry configuration elements.

Adding Telemetry nodes to OrleansConfiguration.xsd

---

src/Orleans/Streams/QueueAdapters/IQueueAdapterCache.cs
src/Orleans/Streams/QueueAdapters/IQueueAdapterReceiver.cs
src/Orleans/Streams/QueueAdapters/IQueueCache.cs
src/OrleansProviders/Streams/Common/SimpleQueueAdapterCache.cs
src/OrleansProviders/Streams/Common/SimpleQueueCache.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

In preparation for the introduction of a rewindable persistent stream provider using EventHub as it's backend queue, I'm making a cleanup pass of the queue adapter interfaces.
This change reduces queue interfaces’ surface area by limiting them to core functionality.

Tighten up queue adapter interfaces

---

src/TestGrainInterfaces/IGeneratedEventReporterGrain.cs
src/TestGrains/GeneratedEventReporterGrain.cs
src/Tester/StreamingTests/ControllableStreamGeneratorProviderTests.cs
src/Tester/TestStreamProviders/Generator/GeneratorAdapterConfig.cs
src/Tester/TestStreamProviders/Generator/GeneratorAdapterFactory.cs
src/Tester/Tester.csproj

Updated GeneratorStreamProvider to support updating stream generation on command.
Tests can now create controlled stream generation for specific scenarios that start on command and do not require silo restart.  This will be used in recoverable stream processing tests.

GeneratorStreamProvider - stream generation on command

---

src/Tester/StreamingTests/StreamFilteringTests.cs

`TestInitialize` attribute can only be placed on class marked as `[TestClass]`. Therefore, moved `TestInitialize` attribute from the base class to the actual Test class.

Fixed wrongly placed TestInitialize attribute on StreamFilteringTests.

---

Samples/TicTacToe/OrleansXO.WorkerRole/WorkerRole.cs

Fixed starting Silo bug, I moved the logic to instantiate and start the
Silo into the Run() method.
It is IMPORTANT to start the silo not in OnStart but in Run. Azure may
not have the firewalls open yet (on the remote silos) at the OnStart
phase.

Fixed starting Silo bug

---

src/.nuget/packages.config
src/NuGet/Microsoft.Orleans.Core.nuspec
src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/NuGet/Microsoft.Orleans.Serialization.Bond.nuspec

Orleans.dll depends on Newtonsoft.Json.dll now, so this is needed.
Removed dependencies on Newtonsoft.Json from other nuspecs.
Also, removed the unneeded reference to Brutal.Dev.StrongNameSigner.
This also needs to go to the 1.1.0 branch.

Add json.net as a dependency for Orleans.Core

---

src/Orleans/Configuration/ConfigUtilities.cs

checks the name of the xml attribute instead of the value of the xml attribute

check name instead of value

---

src/TestGrainInterfaces/IExternalTypeGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/ExternalTypeGrain.cs
src/TestGrains/TestGrains.csproj
src/Tester/ExternalTypesTests.cs
src/Tester/Tester.csproj

Following #1064 and #1072.
It's worth noting that the tests fail only if the types are used in generics - the serialization for DoStuff(AbstractType p1) will work but for DoStuff(IEnumerable<AbstractType> p1) will fail.
Currently the tests have the Ignore attribute as they are failing until there will be a fix from @ReubenBond.

Added test for usage of abstract/enum types from external libraries

---

src/TestInternalGrainInterfaces/Properties/AssemblyInfo.cs
src/TestInternalGrainInterfaces/TestInternalGrainInterfaces.csproj
src/TestInternalGrains/ActivateDeactivateTestGrain.cs
src/TestInternalGrains/Properties/AssemblyInfo.cs
src/TestInternalGrains/TestInternalGrains.csproj
src/Tester/BasicActivationTests.cs
src/Tester/GrainActivateDeactivateTests.cs

Fix some minor outstanding glitches in PR #1013 project files.
- Link to GlobalAssemblyInfo.cs for "common" assembly properties.
- Add missing license text in some new source code files.
- Ensure Prefer32Bit = False
- Ensure WarningsAsErrors = 4014

Follow on changes from PR 1013

---

src/Orleans/Logging/TraceLogger.cs

I noticed that all our cloud deployments are failing and traced it back to this line.

missing argument to trace format in TraceLogger.Initialize

---

Build.cmd
Contributing.md
Test.cmd
index.md

Web Page : Contributing.md
- Some more detailed contribution guidelines for Project Orleans.
- Moving some existing developer contribution info
from the main project home page into separate Contributing.md web page,
and fleshing out that info with current working practices used by the dev team.
This is to address the follow-up action item we talked about previously during PR #1115 and PR #910 (among others) to document and fill in some of the more "hidden" / unexplained parts of the development process we have been and continue to follow on this project.
I think we might have osmosed so much of our current Orleans Team working practices into sub-conscious level over the years that I probably forgot something here! 
Feel free to remind me -- especially external non-MSFT observers that …

Web Page: Contributing.md

---

README.md

- This is a follow-on change from PR #1131
- Updated the main ReadMe with link to the new Contributing page on website http://dotnet.github.io/orleans/Contributing
- Fixed some broken content / layout, and cleaned up some crufty wording.

Updated ReadMe with links to the new Contributing page.

---

src/Orleans/Logging/TraceLogger.cs
src/OrleansCodeGenerator/GrainMethodInvokerGenerator.cs
src/OrleansCodeGenerator/GrainReferenceGenerator.cs
src/TestGrainInterfaces/IGenericInterfaces.cs
src/TestGrains/GenericGrains.cs
src/Tester/GenericGrainTests.cs

for scenarios where a generic grain type also has type constraints, the codegen file has compilation errors because it doesn't preserve the constraints. The case where we hit the issue:
```csharp
public interface IPageWorkerGrain<TCollection, TData> : IGrainWithStringKey where TCollection : ICollection<TData>
public class PageWorkerGrain<TCollection, TData> : Grain, IPageWorkerGrain<TCollection, TData> where TCollection: ICollection<TData>, new()
```

Add support for generic type constraints in codegen

---

Getting-Started-With-Orleans/Developing-a-Client.md

In this page:
http://dotnet.github.io/orleans/Getting-Started-With-Orleans/Developing-a-Client
The sample code should be:
GrainClient.Initialize();
instead of OrleansClient.Initialize();
Fixed other places in this page too.

documentation fix: OrleansClient -> GrainClient

---

src/OrleansVSTools/OrleansVSTools/source.extension.vsixmanifest
src/OrleansVSTools/VSProjectSiloHost/VSProjectSiloHost.vstemplate
src/OrleansVSTools/VSProjectTemplateGrainImplementation/VSProjectTemplateGrainImplementation.vstemplate
src/OrleansVSTools/VSProjectTemplateGrainInterface/VSProjectTemplateGrainInterface.vstemplate

Move embedded NuGet packages from the top level down to individual project templates
Remove VB and F# templates.
These were necessary changes to get the VSIX published to the VS Gallery. Fixes https://github.com/dotnet/orleans/issues/1162.
I already published the VSIX, so this needs to be merged as is.

Move embedded NuGet packages from the top level down to individual project templates

---

src/OrleansCodeGenerator/Utilities/SyntaxFactoryExtensions.cs
src/TestGrainInterfaces/CodegenTestInterfaces.cs
src/TestGrains/SerializationGenerationGrain.cs
src/Tester/CodeGenTests/GeneratorGrainTest.cs

Fix for #1177.
Generic types with a type constraint of `struct` were being incorrectly specified as having type constraints of `new()`, and `System.ValueType`, which are redundant and illegal when `struct` is specified.
This fixes that & adds a test :smile:
Thank you, @bstead for reporting!

Correctly specify struct type constraint in generated code

---

src/OrleansTestingHost/OrleansTestSecrets.cs
src/OrleansTestingHost/OrleansTestStorageKey.cs
src/OrleansTestingHost/OrleansTestingHost.csproj
src/OrleansTestingHost/StorageTestConstants.cs
src/OrleansTestingHost/packages.config
src/SetupTestScript.cmd

Added structured test settings overrides file OrleansTestSecrets to support more test settings overrides.
We will need local overrides for EventHub test settings and the existing OrleansTestStorageKeys.txt is not well structured.  Replacing it with structured file OrleansTestSecrets.json.  Leaving in OrleanTestStorageKeys.txt support for now to not break those using it, but it should be deprecated soon.

Structured test overrides file

---

src/Orleans/Serialization/SerializationManager.cs

in 
```csharp
SerializationManager.Register(Type, Type)
```
the delegates created for copy/serialize/deserialize with generic types all always call RegisterConcreteSerializer()
This is bad because every time RegisterConcreteSerializer is called, it uses reflection discover serializer/deserializer/copy methods, then re-registers the serializer (forced override) even if it hasn't changed.
The fix is to see if the concrete type has already been registered and use the existing serializer/deserializer/copier instead.

Performance tweak for generic types

---

src/Orleans/Statistics/AverageTimeSpanStatistic.cs
src/Orleans/Statistics/AverageValueStatistic.cs
src/Orleans/Statistics/FloatValueStatistic.cs
src/Orleans/Statistics/IntValueStatistic.cs
src/Orleans/Statistics/StringValueStatistic.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Added Delete method to all ICounters, to allow deleting the counter statistics in order to prevent any potential memory leaks.
The need for that was raised by #1160.

Added Delete method to all ICounters.

---

src/OrleansHost/Program.cs
src/OrleansRuntime/GrainTypeManager/SiloAssemblyLoader.cs

(I also fixed a couple of typos)
This change would allow Orleans to be installed as a command line tool (via chocolatey or similar). 
This enables the developer to have a quick dev environment up and running by executing SiloHost.exe with their `bin\debug` folder as the CWD.

Add the CWD to the DLL search path

---

src/TestGrainInterfaces/IGenericInterfaces.cs
src/TestGrains/GenericGrains.cs
src/Tester/GenericGrainTests.cs

Expanded `IGenericGrainWithConstraints` interface to include `struct` and `class` constraints to ensure that they are explicitly covered in testing. This is in response to #1192.

Improve coverage for type constraint usage in tests

---

src/Orleans/Telemetry/Consumers/ConsoleTelemetryConsumer.cs

Currently console output is duplicated: first with a color message, and then with a non-color message.
Example:
This change removes the non-color message in all but the default case (just in case we add new severity levels).

Output messages only once in ConsoleTelemetryConsumer.

---

src/Orleans/Logging/ConsoleText.cs

We see infrequent races in VSO tests when we try to write to already disposed console. This should hopefully fix the issue.

Make ConsoleText resilient to ObjectDisposedExceptions.

---

src/TestInternalGrains/StreamingGrain.cs

This mistake causes some of the remaining VSO tests to fail.

Fixed hardcoded test grain class namespace to match the reality

---

src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/OrleansZooKeeperUtils/OrleansZooKeeperUtils.csproj
src/OrleansZooKeeperUtils/packages.config

Main changes :
* New log system 
* Configuration is read from `ZooKeeperNetEx.config` when it's next to `ZooKeeperNetEx.dll`
* Added static method to redirect logs to 3rd party loggers
* Simplified and *better* tested
* Support the latest `dotnet5.4` framework moniker
* Tests converted from `nUnit` to `xUnit` and fully parallelized
* New build system - using `Sake` & `KoreBulid`

update ZooKeeperNetEx to 3.4.6.1009

---

Test.cmd

- Add back a no-op Test.cmd script for gh-pages branch, removed in error by PR #1191.

No-op Test.cmd script for gh-pages branch.

---

src/ClientGenerator/ClientGenerator.cs
src/Orleans/Serialization/SerializationManager.cs

Will help avoid issues with ```NullReferenceException``` when using ```SerializationManager``` without calling ```Initialize``` method first.

Added fallback serializer initialization to static ctor

---

src/TesterInternal/AssemblyLoaderTests.cs

Add SerializationManager.InitializeForTesting() to [ClassInitialize] of AssemblyLoaderTests.
Add one of the AssemblyLoaderTests tests to BVT to catch future regressions in CI.

Fix AssemblyLoaderTests tests.

---

src/OrleansSQLUtils/CreateOrleansTables_MySql.sql
src/TesterInternal/RemindersTest/MySqlRemindersTableTests.cs
src/TesterInternal/RemindersTest/ReminderTablePluginTests.cs
src/TesterInternal/RemindersTest/SqlServerRemindersTableTests.cs
src/TesterInternal/SqlStatisticsPublisherTests/DummyCounter.cs
src/TesterInternal/SqlStatisticsPublisherTests/DummyPerformanceMetrics.cs
src/TesterInternal/SqlStatisticsPublisherTests/MySqlStatisticsPublisherTests.cs
src/TesterInternal/SqlStatisticsPublisherTests/SqlServerStatisticsPublisherTests.cs
src/TesterInternal/SqlStatisticsPublisherTests/StatisticsPublisherProviderConfig.cs
src/TesterInternal/SqlStatisticsPublisherTests/StatisticsPublisherProviderRuntime.cs
src/TesterInternal/TesterInternal.csproj

This is a fix for #1169.
Important changes:
* [SELECT ... FOR UPDATE] (http://www.techonthenet.com/oracle/cursors/for_update.php) was changed to [INSERT ... ON DUPLICATE KEY UPDATE](http://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html)
* Removed column `ETag` from `OrleansMembershipVersionTable` because it's the same as `Version`(same can be done to the `MSSQL` script and then remove any references to it from relational code.)
* Added tests for `SqlStatisticsPublisher` for both `MSSQL` and `MySQL`
* Changed reminders upsert test to test in parallel

fix MySql script concurrency issues and add sql publisher tests

---

src/Orleans/Serialization/OrleansJsonSerializer.cs
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs

This is a smaller version of PR #1204.
Use the same JsonSerializerSettings  in the fallback Orleans serializer and in the Json serializer used in the storage provider.
The OrleansJsonSerializer.JsonSerializerSettings are still internal and not changeable by application code.

Use OrleansJsonSerializer.JsonSerializerSettings in Azure storage provider

---

src/OrleansCodeGenerator/RoslynCodeGenerator.cs

This is to help https://github.com/dotnet/orleans/pull/1060.
Today we generate serializers for grain state classes that extend GrainState. With https://github.com/dotnet/orleans/pull/1060 any POCO class can represent grain state. This change adds Ts of all classes that extend Grain<T> to consider for serializer generation.

Add Ts of grain classes that extend Grain<T> to consider for serializer generation

---

src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs

Add logging of AppDomain unloading events in the client, for easier troubleshooting/diagnostics.
Follow up from Gitter thread: 
https://gitter.im/dotnet/orleans?at=5683367a66a282570f904a4d

Log AppDomain unloading events in the client.

---

_includes/menu.html

- Add OrleansContrib name to the link to community add-ons.
- ~~Mark CodePlex links as "deprecated" - or can these be removed now?~~
- Removed link to old CodePlex discussion forum, and mark the old CodePlex Orleans home page link as "historical"
- List the @ProjectOrleans name in the Twitter link.
- Minor tweaks to link descriptions, for clarity.
CC: @richorama

Cleanup some menu items on Orleans website.

---

src/NuGet/Microsoft.Orleans.TestingHost.nuspec
src/Tester/UnitTestSiloHost.cs

Problem Description 
[from the perspective of someone trying to use the Orleans TestingSiloHost in their own project]
Adding NuGet package `Orleans.TestingHost` into a project adds `OrleansConfigurationForTesting.xml` file into that project. 
However, that config file contains an implicit runtime dependency on the `Orleans.Storage.MemoryStorage` class, which is in the `OrleansProviders.dll` assembly, but that assembly is not currently automatically added as dependency of `Orleans.TestingHost`. 
Therefore, the test silo will fail to start because it can't find the memory storage provider class to load.
``` xml
<StorageProviders>
<Provider Type="Orleans.Storage.MemoryStorage" Name="MemoryStore" />
<Provider Type="Orleans.Storage.MemoryStorage" Name="Default" />
</StorageProviders>
``` …

Orleans.TestingHost package depends on OrleansProviders.dll

---

src/NuGet/BondSerializerInstall.ps1
src/NuGet/BondSerializerUninstall.ps1

When testing out the Bond serializer support in the `Microsoft.Orleans.Serialization.Bond` 1.1.0 package I noticed that the type name for the serializer added to the configuration files was incorrect. It appears that the assembly name was changed but the `BondSerializerInstall.ps1` and `BondSerializerUninstall.ps1` files were not updated. I have updated the scripts to use the `OrleansBondUtils` assembly in the type name.

Fixed type name for BondSerializer in PowerShell install scripts

---

src/Tester/MembershipTests/LivenessTests.cs

This bug didn't manifest until test methods were uncommented in the tests class.

Remove duplicate [ClassInitialize] method from LivenessTests_SqlServer.

---

src/OrleansCodeGenerator/SerializerGenerationManager.cs

Improves Mono support, since Mono and .NET currently have different implementations of `MulticastDelegate`.
cc @bsmatt

Avoid serialization of Delegate fields

---

src/Orleans/Configuration/ClusterConfiguration.cs

Switch to using NetworkInterface.NetworkInterfaceType instead of NetworkInterface.LoopbackInterfaceIndex to detect loopback IP addresses
This is a fix for https://github.com/dotnet/orleans/issues/1243.

Switch to using NetworkInterface.NetworkInterfaceType

---

src/Orleans.sln
src/OrleansProviders/Streams/Common/EventSequenceToken.cs
src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Properties/AssemblyInfo.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventDataExtensions.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubBatchContainer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueMapper.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubSequenceToken.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubSettings.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubStreamProvider.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubStreamProviderConfig.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubSettings.cs
src/OrleansServiceBus/packages.config
src/OrleansTestingHost/OrleansTestSecrets.cs
src/OrleansTestingHost/StorageTestConstants.cs
src/Tester/StreamingTests/EHSubscriptionMultiplicityTests.cs
src/Tester/Tester.csproj

This is the initial prototype of a recoverable EventHubStreamProvider.
See: Recoverable Event Hub Persistent Stream Provider #1096
This is aproxamatly what is described in "1. Minimal non-recoverable EventHub stream provider"
>Minimal non-recoverable EventHub stream provider
◦Introduction of a new ServiceBus specific project. OrleansServiceBus. This will be comparable to the azure specific project OrleansAzureUtils.
◦Development of EventHubQueueAdapter comparable to AzureQueueAdapter, with similar limitations.
a.Non-rewindable
b.Will use simple queue cache.
◦Define an EventHubStreamProvider that is a persistent stream provider that uses the EventHubAdapter.
◦Add test coverage for EventHubStreamProvider comparable to that of AzureQueueStreamProvider.
This provider is not yet production …

EventHubStreamProvider Prototype

---

src/OrleansRuntime/Catalog/ActivationCollector.cs
src/OrleansRuntime/Messaging/OutboundMessageQueue.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansTestingHost/TestingSiloHost.cs
src/TesterInternal/BootstrapProviderTests.cs
src/TesterInternal/General/ConsistentRingProviderTests_Silo.cs
src/TesterInternal/GeoClusterTests/TestingClusterHost.cs
src/TesterInternal/MockStatsCollectors.cs
src/TesterInternal/StatsTests.cs
src/TesterInternal/StorageTests/PersistenceGrainTests.cs
src/TesterInternal/StorageTests/PersistenceGrainTests_AzureStore.cs
src/TesterInternal/StreamProvidersTests.cs
src/TesterInternal/StreamingTests/StreamPubSubReliabilityTests.cs

Renamed "hookup" to "hook".
Even though the project is for mature audience, I think this is more appropriate naming.

Move away from dating terminology

---

src/NuGet/BondSerializerInstall.ps1
src/NuGet/BondSerializerUninstall.ps1

made the bond serializer installer/uninstaller a bit more robust
* saves pending project changes, otherwise the operation will fail
* saves pending file changes to the configuration file being changed, otherwise the operation will fail
* writes a bit more info to the console
* doesn't write an error to the console if one of the config files doesn't exist
* made the ps1 files a bit more reusable by other serializer installers by moving checks in to the Register/Unregister functions

Adding checks to the bond serializer install/uninstall

---

src/TesterInternal/GatewaySelectionTest.cs
src/TesterInternal/LivenessTests/MembershipTablePluginTests.cs
src/TesterInternal/StatsTests.cs
src/TesterInternal/TimerTests/ReminderTests_SqlServer.cs

These tests are not currently run by automated builds and are intended for manual execution by developers. Removing "Functional" category will eliminate the discrepancy between the set of functional tests in Test Explorer and the set that actually gets executed by VSO builds.

Removed "Functional" category from tests that are ifdef'ed

---

src/OrleansTestingHost/TestingSiloHost.cs

Make `TestingSiloHost.ImportGeneratedAssemblies()` resilient to exceptions caused by expiration of proxies for MarshalByRefObjects in tests silo app domains. We see this happening sometimes in long running series of tests. This should be safe because `TestingSiloHost.ImportGeneratedAssemblies()` itself is just an optimization for faster initialization of test silos.

Make `TestingSiloHost.ImportGeneratedAssemblies()` more resilient

---

src/Orleans/CodeGeneration/TypeFormattingOptions.cs
src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/Orleans.csproj
src/Orleans/Serialization/TypeUtilities.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs
src/OrleansCodeGenerator/SerializerGenerator.cs
src/OrleansCodeGenerator/Utilities/SyntaxFactoryExtensions.cs

This fix enables serializer generation for nested types and cleans up the usage of `IsNested` vs `IsNestedPrivate`, etc.

Cleanup/fix usage of IsNested vs. IsNestedXXX & serialize nested types.

---

src/OrleansCodeGenerator/SerializerGenerator.cs
src/TestGrainInterfaces/IValueTypeTestGrain.cs
src/Tester/SerializationTests/DeepCopyTests.cs
src/Tester/Tester.csproj

As discussed in #1278, there was a bug in SerializerGenerator.cs causing shallow copying in cases where a field had an auto getter.
I fixed the bug and added unit tests for deep copy, to avoid regressions in the future.

fix deepcopy issue #1278

---

src/OrleansCodeGenerator/SerializerGenerator.cs
src/TestGrainInterfaces/CodegenTestInterfaces.cs
src/Tester/CodeGenTests/GeneratorGrainTest.cs

Fixes #1215: in generated code, all [Obsolete] properties/fields are accessed using the IL method instead of directly in order to avoid compiler warnings/errors.

Correctly serialize [Obsolete] fields and properties.

---

src/TesterInternal/ClientInitTests.cs
src/TesterInternal/General/RequestContextTest.cs
src/TesterInternal/MockStats_ServerConfiguration.xml
src/TesterInternal/StreamingTests/AQStreamingTests.cs
src/TesterInternal/StreamingTests/StreamLimitTests.cs
src/TesterInternal/StreamingTests/StreamReliabilityTests.cs
src/TesterInternal/TimerTests/ReminderTests_AzureTable.cs

This fixes some functional tests that are failing in VSO. Sometimes by restarting the silos for each tests, or sometimes by making sure tests are correctly set up.

Fix functional tests

---

src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProducer.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs

Fixes https://github.com/dotnet/orleans/issues/1272#issuecomment-171465129 where @centur pointed out that `SimpleMessageStreamProvider` does not currently allow to configure pub sub type.

Allow to configure PubSub for SMS.

---

src/NuGet/Microsoft.Orleans.OrleansAzureUtils.nuspec
src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansAzureUtils/packages.config
src/Tester/Tester.csproj
src/Tester/packages.config
src/TesterInternal/TesterInternal.csproj
src/TesterInternal/packages.config

OrleansAzureUtils.nuspec dependency changes:
- WindowsAzure.Storage is 5.0.2
- Removed dependency on Microsoft.WindowsAzure.ConfigurationManager
Updated WindowsAzure.Storage from 5.0.0 to 5.0.2 (as 5.0.0 is unlisted in nuget.org due to a bug).

Fixed dependencies in OrleansAzureUtils.nuspec

---

src/Orleans/Core/GrainAttributes.cs

Issue #1266 : update Namespace access modifier to public. Add Provider property and create constructor which takes it as a second parameter.

Make Namespace access modifier public in ImplicitStreamSubscriptionAttribute. Add Provider property.

---

src/Orleans/Serialization/TypeUtilities.cs

Fixes #1283.
I haven't run tests on this, it's just a quick fix, so we'll see what CI says.
The change is this: `IsTypeIsInaccessibleForSerialization` now has only one path which can return `false` (signifying that a type is accessible for serialization). Each check can trigger short-circuiting & return `true` if a type is inaccessible, but otherwise execution will fall through to the next check.
Hopefully the code is easier to reason about now that there is only one happy path.
We also check the accessibility of the declaring type to fix #1283.

Check declaring types when performing accessibility checks for code gen.

---

_includes/menu.html

Part of #1264.
I think that current documentation menu can be improved by this PR. I haven't removed any page (other than the link to Runtime Implementation Details - which only contains links which I've moved one level up).

two new top level sections: Configuration and Programmer's Guide

---

src/TestGrains/GeneratedEventCollectorGrain.cs
src/TestGrains/GeneratedEventReporterGrain.cs
src/TestGrains/GeneratedStreamTestConstants.cs
src/TestGrains/ImplicitSubscription_NonTransientError_RecoverableStream_CollectorGrain.cs
src/TestGrains/ImplicitSubscription_TransientError_RecoverableStream_CollectorGrain.cs
src/TestGrains/StreamCheckpoint.cs
src/TestGrains/TestGrains.csproj
src/Tester/StreamingTests/ControllableStreamGeneratorProviderTests.cs
src/Tester/StreamingTests/ControllableStreamProviderTests.cs
src/Tester/StreamingTests/GeneratedStreamRecoveryTests.cs
src/Tester/StreamingTests/ImplicitSubscritionRecoverableStreamTestRunner.cs
src/Tester/Tester.csproj

Added testing for some basic stream recovery tests.
Tests use test generated streams
Tests are limited to implicit subscriptions
Tests transient stream processing errors, exercising delivery retry and stream rewind logic.
Tests non-transient stream processing errors, exercising exhaustion of delivery retries and error notification.

Stream Recovery Tests

---

Advanced-Concepts/Timers-and-Reminders.md
Step-by-step-Tutorials/A-Service-is-a-Collection-of-Communicating-Actors.md

minor documentation updates, which can be previwed here: 
http://richorama.github.io/orleans/Advanced-Concepts/Timers-and-Reminders
http://richorama.github.io/orleans/Step-by-step-Tutorials/A-Service-is-a-Collection-of-Communicating-Actors
Annoyingly vscode has removed some whitespace too :¬/

update ActivateAsync -> OnActivateAsync

---

netci.groovy

Set of test results manually to avoid two publish steps, which may be causing issues with the test names.  Also do some refactoring of the CI file

Manually set up test results

---

README.md

We've settled on calling this Orleans, rather than the old moniker, Project Orleans.

Remove instances of "Project" from README

---

Step-by-step-Tutorials/Concurrency.md

Goal of this code snippet is to show where Reentrant attribute should go
on the class, so it is not needed to include Greeting method, which was
listed higher on the page.
Also repeated Greeting method could not be compiled as it was listed.

Update Concurrency.md to fix #1320

---

src/SetupTestScript.cmd

Updated SetupTestScript.cmd to find the credentials file in ancestor in the first ancestor directory from where it is running.
Previously it was going up a fixed numbers of directories and then going into the "TestVso" folder. This is not scalable and also differs if the tests are being run with MSTest or with xUnit, or Jenkins which deploy files differently.
Now it will look for the file somewhere up the path. For instance, if the script runs in `c:\projects\orleans\src\TestResults\testrun\out\` and the credentials file is located at `c:\projects\OrleansTestSecrets.json` (or somewhere up the chain from where the script runs), then it will be found

Updated SetupTestScript.cmd to find the credentials file in ancestor

---

src/Orleans/Core/Exceptions.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/TestGrainInterfaces/IActivateDeactivateTestGrain.cs
src/TestInternalGrains/ActivateDeactivateTestGrain.cs
src/Tester/GrainActivateDeactivateTests.cs

Take 2 on #1325.
We used to just ignore the `DeactivateOnIdle` call made inside OnActivateAsync.
As proposed by @sergeybykov in #1325, `DeactivateOnIdle`  should throw if called from within `OnActivateAsync`.
I disagree with this semantics (I think the right fix is to cause grain to Deactivate immediately, which will also call `OnDeactivateAsync`), but there appears to be a wider opinion that this is the right behavior and since this fix is better than just completely ignoring, I prefer a sub-optimal fix rather than leaving a hanging bug (I don't like leaving hanging bugs).

Fixed a bug of not properly handling DeactivateOnIdle inside OnActivateAsync by throwing Exception.

---

Getting-Started-With-Orleans/Developing-a-Grain.md
Getting-Started-With-Orleans/Grain-Persistence.md
Getting-Started-With-Orleans/Grains.md
Introduction.md
Samples-Overview/Presence-Service.md
_includes/menu.html

part of #1264.
main changes :
* moved grain persistence documentation from Developing-a-Grain.md to a new section Grain-Persistence.md under programmer`s guide
* moved documentation of presence service sample from Developing-a-Grain.md to Presence-Service.md
* moved "Grain interfaces" and "Grain reference" sections from Grains.md to Developing-a-Grain.md

refactored grain documentation

---

src/OrleansRuntime/Silo/Silo.cs

Initialize SerializationManager before CodeGeneratorManager

---

src/NuGet/Microsoft.Orleans.OrleansConsulUtils.nuspec
src/Orleans.sln
src/OrleansConsulUtils/ConsulBasedMembershipTable.cs
src/OrleansConsulUtils/OrleansConsulUtils.csproj
src/OrleansConsulUtils/Properties/AssemblyInfo.cs
src/OrleansConsulUtils/SerializableMembershipTypes.cs
src/OrleansConsulUtils/packages.config

Config Usage: <Globals><SystemStore SystemStoreType="Consul" DataConnectionString="http://localhost:8500/" DeploymentId="TestDeployment" /></Globals>

Added support for using Consul 0.6.0 as a Membership Provider

---

src/OrleansAzureUtils/Storage/RemindersTableManager.cs

There's a possibility to filter by partition key instead with the same results. This was timing out when the reminders table becomes too large.

Avoid unnecessary table scan when finding reminder entries to delete

---

src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubBatchContainer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubSequenceToken.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubStreamProviderConfig.cs
src/Tester/StreamingTests/EHImplicitSubscriptionStreamRecoveryTests.cs
src/Tester/StreamingTests/EHSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/GeneratedStreamRecoveryTests.cs
src/Tester/StreamingTests/ImplicitSubscritionRecoverableStreamTestRunner.cs
src/Tester/Tester.csproj

Added rewind/recoverability to EventHubStreamProvider
This work is related to "Recoverable Event Hub Persistent Stream Provider #1096"
It is the first part of stage 4.
Update EventHubStreamProvider to be recoverable.
- Update EventHubQueueAdapter to use PooledQueueCache.
- Add recoverable stream tests comparable to those built against GeneratorStreamProvider.
Does not include:
- EventHubQueueAdapter to persist state that tracks offset into EventHub partition.

Event hub stream provider recovery

---

src/Orleans/Async/TaskExtensions.cs

This is similar to Task.Done, but for our own boxing of tasks

Reused pre-created tasks for efficiency

---

src/Orleans/Streams/Predicates/FilterPredicateWrapperData.cs
src/OrleansRuntime/Core/GrainTimer.cs
src/OrleansRuntime/Scheduler/ClosureWorkItem.cs

#368; 
Even though `GetMethodInfo` is located in `System.Reflection` namespace, in .Net 4.5.* it's only a accessor of  del's `Method` property:

Coreclr compatibility: Delegate.Method -> Delegate.GetMethodInfo()

---

src/OrleansTestingHost/TestingSiloHost.cs
src/TesterInternal/StreamingTests/StreamReliabilityTests.cs

Stream reliability tests were failing because they were not allowing for expected cluster stability time.

Stream Reliability test fix

---

src/Orleans/CodeGeneration/IGrainMethodInvoker.cs
src/Orleans/Core/IGrainInvokeInterceptor.cs
src/Orleans/Core/InvocationMethodInfoMap.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansCodeGenerator/CodeGeneratorCommon.cs
src/OrleansCodeGenerator/GrainMethodInvokerGenerator.cs
src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Core/InsideGrainClient.cs
src/TestGrainInterfaces/IMethodInterceptionGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/MethodInterceptionGrain.cs
src/TestGrains/TestGrains.csproj
src/Tester/MethodInterceptionTests.cs
src/Tester/Tester.csproj

This feature allows users to override `Grain.Invoke(InvokeMethodRequest request, IGrainMethodInvoker invoker)` in order to perform request interception on a per-Grain-class level.
As requested by @yevhen in #749.
Example:
```C#
public class InterceptRequestGrain : Grain, ISomeGrain 
{
protected override Task<object> Invoke(InvokeMethodRequest request, IGrainMethodInvoker invoker)
{
RequestContext.Set("InterceptedValue", 74);
return base.Invoke(request, invoker);
}
// Other methods...
}
```

Feature: Per-Grain-class Request Interceptors

---

src/Orleans/Configuration/ClusterConfiguration.cs
src/OrleansAzureUtils/Hosting/AzureSilo.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Silo/SiloHost.cs
src/OrleansTestingHost/TestingSiloHost.cs
src/TestGrains/ImplicitSubscription_NonTransientError_RecoverableStream_CollectorGrain.cs
src/TestGrains/ImplicitSubscription_TransientError_RecoverableStream_CollectorGrain.cs
src/Tester/StreamingTests/ControllableStreamGeneratorProviderTests.cs
src/Tester/StreamingTests/ControllableStreamProviderTests.cs
src/Tester/StreamingTests/EHImplicitSubscriptionStreamRecoveryTests.cs
src/Tester/StreamingTests/EHSubscriptionMultiplicityTests.cs
src/Tester/StreamingTests/GeneratedStreamRecoveryTests.cs
src/Tester/StreamingTests/StreamGeneratorProviderTests.cs
src/TesterInternal/ConfigTests.cs
src/TesterInternal/LivenessTests/MembershipTablePluginTests.cs
src/TesterInternal/SchedulerTests/OrleansTaskSchedulerBasicTests.cs

This is another pass at addressing comments in Stream Recovery Tests #1289
First pass was GetOrAddConfigurationForNode #1313 
The issue here is that the silo nodes are optional in the configuration, so code that needs them tends to use a 'get or create' pattern.  This pattern was coded into the original GetConfigurationForNode call.  From the call name it's not clear that one would be creating the node if it does not exist, when all it appears to do is access it.
Since the actual behavior was 'get or create' the first pass at addressing this ( #1313) simply renamed the operation to GetOrAddConfigurationForNode, to make it more clear what the call was actually doing.  This change introduced no new capabilities, just made the existing behavior more clear.  There remained no means of …

Cleanup NodeConfig management in ClusterConfiguration.

---

src/TestGrainInterfaces/IExceptionGrain.cs
src/TestGrains/ExceptionGrain.cs
test/Tester/ExceptionPropagationTests.cs

Hi, this PR is mainly for discussion first, as fixing it would require a breaking change that might not be easy to catch for our users (no pun intended).
I did not fix the implementation in this PR, just created a bunch of tests on what would be my expectations about exception propagation (most test are failing, and some are passing but for the wrong reasons).
In a nutshell, when a grain throws an exception, the client will always get an `AggregateException` back instead of the original exception. Also, if the grain would return an aggregate exception (or many nested ones), Orleans would flatten all of those as if it was its reponsibility to do so, and then return the flattened exception inside this extra `AggregateException`.
```
BasicExceptionPropagation: Failed
Test method …
```

Discussion: Exception propagation doesn't look right

---

src/TestGrains/ChainedGrain.cs
src/TestInternalGrains/PersistenceTestGrains.cs
src/TesterInternal/Tester/OrleansTestingBase.cs
test/Tester/OrleansTestingBase.cs

In preparation for the migration to xUnit of TesterInternal

Avoid using Console.WriteLine from grain code

---

src/OrleansAzureUtils/Storage/AzureStorageUtils.cs
src/TesterInternal/StorageTests/AzureTableErrorCodeTests.cs

Return values of pure method `string.Replace` weren't used.

Fixed Azure table property being not sanitized.

---

src/Build/GlobalAssemblyInfo.fs
src/Orleans.sln
src/OrleansCodeGenerator/GrainReferenceGenerator.cs
src/OrleansCodeGenerator/Utilities/SyntaxFactoryExtensions.cs
src/TestFSharp/AssemblyInfo.fs
src/TestFSharpInterfaces/AssemblyInfo.fs
src/TestFSharpInterfaces/IFSharpBaseInterface.fs
src/TestFSharpInterfaces/TestFSharpInterfaces.fsproj
src/TestFSharpInterfaces/packages.config
src/TestGrainInterfaces/IGeneratorTestDerivedFromCSharpInterfaceInExternalAssemblyGrain.cs
src/TestGrainInterfaces/IGeneratorTestDerivedFromFSharpInterfaceInExternalAssemblyGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrains/GeneratorTestDerivedFromCSharpInterfaceInExternalAssemblyGrain.cs
src/TestGrains/GeneratorTestDerivedFromFSharpInterfaceInExternalAssemblyGrain.cs
src/TestGrains/TestGrains.csproj
src/TestInterfaces/ICSharpBaseInterface.cs
src/TestInterfaces/Properties/AssemblyInfo.cs
src/TestInterfaces/TestInterfaces.csproj
test/Tester/CodeGenTests/GeneratorGrainTest.cs
test/Tester/Tester.csproj

Fixes #1349, includes corresponding tests.
F# interface definitions do not require parameter names. It is idiomatic to omit parameter names for trivial interface methods:
```
type Interface1 =
abstract member Multiply : int -> int -> int
```
However, Orleans code generation requires parameter names to be present. The PR addresses this by generating such names when not present, by suffixing the string `"arg"` with the parameter's index (`arg0`, `arg1`, etc.).

CodeGen: Add support for F# interfaces

---

test/Tester/Tester.xunit.runner.json

This is so that our CI and PR builds include the entire test name instead of being empty or truncated

Display name including class to work well with Jenkins XSLT transform

---

src/Orleans/Statistics/IPerformanceMetrics.cs

Fixed a bug with mismatched arguments in DetailedGrainReport.ToString().

Fixed String.Format arguments in DetailedGrainReport.ToString()

---

src/OrleansManager/Program.cs

#1395 
The `RETRIES` parameter is no longer used:

Fixed string.Format arguments number error

---

src/TesterInternal/TimerOrleansTest.cs

`StopTimer` method was actually starting it.

Fixed stop timer method

---

src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/ClusterConfiguration.cs

We want to change samples and the Dev/Test Host template to use programmatic config instead of the config files. This adds a couple of static helper methods that simplify otherwise tedious task of programmatic configuration.
An usage example is in https://github.com/sergeybykov/orleans/blob/sample/Samples/HelloWorld/HelloWorld/OrleansHostWrapper.cs#L135 and https://github.com/sergeybykov/orleans/blob/sample/Samples/HelloWorld/HelloWorld/Program.cs#L29.
Note that we can't update samples until we publish NuGets with this feature and an updated VSIX.

Added helper methods for programmatic test configurations.

---

src/OrleansHost/app.config

We missed updating this file, so OrleansHost.exe.config is incorrect as the result.

Fix OrleansHost's app.config to reflect the upgrade of Newtonsoft.Json from 6 to 7

---

src/OrleansCodeGenerator/SerializerGenerationManager.cs

Long overdue (by about a year).

Update the custom serializer warning message to adequately reflect the OSS status of Orleans

---

src/TestGrainInterfaces/IExceptionGrain.cs
src/TestGrains/ExceptionGrain.cs
test/Tester/ExceptionPropagationTests.cs

- Synchronous exception thrown should result in faulted task

Added exception propagation test

---

index.md

0b2705da94841e5152 merged the `Core Concepts` section of the Getting Started Guide with the Introduction.

Fix broken link in `Where Next?`

---

src/TestGrainInterfaces/IExceptionGrain.cs
src/TestGrains/ExceptionGrain.cs
test/Tester/ExceptionPropagationTests.cs

Since AggregateExceptions are a little bit special, some more tests to cover scenarios like AggregateExceptions with multiple inner exceptions, as well as synchronous throws of these.
This is to fulfill user facing expectations in #1378

More AggregateException propagation tests

---

src/OrleansSQLUtils/Storage/RelationalOrleansQueries.cs
src/TesterInternal/RemindersTest/MySqlRemindersTableTests.cs
src/TesterInternal/RemindersTest/ReminderTablePluginTests.cs
src/TesterInternal/RemindersTest/SqlServerRemindersTableTests.cs

a solution for #1365.
At first this was a bit more complicated fix since I wanted to support both `uint` and `int`. IMHO, there's no need for that.

Relational Storage: reminders range queries: cast to int before range check

---

Documentation-Guidelines.md
Getting-Started-With-Orleans/Grain-Persistence.md
Step-by-step-Tutorials/Declarative-Persistence.md

The `SqlStorageProvider` is commented out for now, it's unclear to me how this should be configured.
Most of the changes made can be viewed on this page: http://richorama.github.io/orleans/Getting-Started-With-Orleans/Grain-Persistence

Update documentation to include storage provider configuration

---

src/Orleans/Streams/Internal/StreamConsumer.cs

Resulting from #1450. Make user aware if stream subscription is used incorrectly.

Throw exception if user subscribes to a stream using a GrainReference.

---

src/Orleans/Serialization/SerializationManager.cs

Flatten ReflectionTypeLoadException to display LoaderExceptions when calling SerializationManager.InitializeForTesting(), so that it's easily seen within tests.

Show LoaderExceptions in tests

---

src/Build.cmd

This is because if we run the build script from a non-command prompt, generating the VSIX fails

Define default VisualStudioVersion

---

src/OrleansRuntime/Silo/Silo.cs

As per Gitter discussion with @centur  and @galvesribeiro, this seems to be a common pitfall.
Added a warning informing users that ServerGC only works on multi-core systems, irrespective of settings/configuration.

ServerGC Warning: Add note on single-core systems

---

test/Tester/Tester.xunit.runner.json

This is so that the test assembly's binding redirects work as expected.
I believe there is some support for [config files in dotnet core also](https://github.com/dotnet/cli/issues/807), but we can deal with that later.

xUnit runner to use AppDomains.

---

src/Orleans/Messaging/GatewayClientReceiver.cs
src/Orleans/Messaging/IncomingMessageBuffer.cs
src/OrleansRuntime/Messaging/IncomingMessageAcceptor.cs

Client networking was getting in a bad state in rare cases where there was a networking error after a partial message had been read into the receive buffer.
This change refactors some of the buffer grow logic to help reduce partial messages being left in the buffer, as well as properly resets the buffer when socket errors occur.

Networking bug fix:  Reset receive buffer on error.

---

src/Orleans/Serialization/OrleansJsonSerializer.cs
test/Tester/SerializationTests/SerializationTests.JsonTypes.cs

Repro for the #1484; 
Also the [```GuidJsonTestConverter```](https://github.com/dotnet/orleans/blob/master/test/Tester/SerializationTests/SerializationTests.JsonTypes.cs#L74) is duplicate of the [```GuidJsonConverter```](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/OrleansJsonSerializer.cs#L239), and probably should be removed.

Repro for #1484; Json deserialization of POCO with object generic argument

---

src/Orleans/Streams/QueueAdapters/IQueueCacheCursor.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCache.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCacheCursor.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
test/Tester/TestStreamProviders/Generator/GeneratorPooledCache.cs

Addresses AzureQueueStreamProvider violates at-least-once delivery #1416 
Added RecordDeliveryFailure to IQueueCacheCursor.
Stored delivery failure flag in SimpleQueueCache's SimpleQueueCacheItem.
Use delivery failure flag to removed failed to delivered batches from those passed back to the receiver for deletion.

AzureQueueStreamProvider violates at-least-once delivery bug fix

---

src/OrleansAzureUtils/Storage/AzureTableDefaultPolicies.cs

Debugging Orleans in Compute Emulator almost always gives this error:
```
Exception thrown: 'System.TimeoutException' in Orleans.dll
Microsoft.WindowsAzure.ServiceRuntime Critical: 31337 : System.TimeoutException: Task.WaitWithThrow has timed out after 00:00:03.
at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
at Orleans.AzureUtils.OrleansSiloInstanceManager.RegisterSiloInstance(SiloInstanceTableEntry entry)
at Orleans.Runtime.Host.AzureSilo.Start(ClusterConfiguration config, String deploymentId, String connectionString)
at Example.Azure.Program.OnStart() in C:\Work\OSS\Orleankka\Source\Example.Azure.Cluster\Program.cs:line 26
at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
at …
```

Fix retry timeout when running under debugger

---

src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Serialization/TypeUtilities.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs
src/OrleansCodeGenerator/SerializerGenerator.cs

This PR contains a couple of small related fixes for serializer code generation.
Fix: Certain 'special' types cannot be used as generic constraints in C#, eg `Delegate`. This doesn't seem to be the case in F#, where the core library is doing precisely that.
Fix: When `KnownAssemblyAttribute` was in-use, assemblies were incorrectly intersected with referenced assemblies and not unioned with them.
Fix: Serializer accessibility checks for concrete generic types were not considering the fields of their generic type definition. The code has been simplified to recurse into the generic type definition, reducing duplication.
Fix: Multiple classes with the same name and differing numbers of generic arguments would cause serializer generation to break when generating the 'master' serializer …

Improve F# support, serializer generation accessibility checks, fix KnownAssembly

---

src/TestFSharpInterfaces/IFSharpParameters.fs
src/TestFSharpInterfaces/TestFSharpInterfaces.fsproj
src/TestGrainInterfaces/IFSharpParametersGrain.cs
src/TestGrainInterfaces/TestGrainInterfaces.csproj
src/TestGrainInterfaces/packages.config
test/Tester/FSharpGrainTests.cs
test/Tester/SerializationTests/SerializationTests.FSharpTypes.cs

Repro for #1346 
Test result (currently skipped for CI):
```
Test Name:	UnitTests.Serialization.SerializationTestsFsharpTypes.SerializationTests_FSharp_IntOption_Some
Test FullName:	UnitTests.Serialization.SerializationTestsFsharpTypes.SerializationTests_FSharp_IntOption_Some
Test Source:	C:\code\ca-ta\orleans\test\Tester\SerializationTests\SerializationTests.FSharpTypes.cs : line 28
Test Outcome:	Failed
Test Duration:	0:00:03.61
Result StackTrace:	
at valueSet(FSharpOption`1 , Int32 )
at UnitTests.GrainInterfaces.OrleansCodeGenMicrosoft_FSharp_Core_FSharpOptionSerializer`1.Deserializer(Type expected, BinaryTokenStreamReader stream) in C:\code\ca-ta\orleans\src\TestGrainInterfaces\Properties\orleans.codegen.cs:line 7760
at Orleans.Serialization.SerializationManager.DeserializeInner(Type …
```

Repro: F# option deserialization error

---

src/OrleansSQLUtils/OrleansRelationalDownloadStream.cs
src/OrleansSQLUtils/OrleansSQLUtils.csproj
src/OrleansSQLUtils/Storage/DbConstantsStore.cs
src/OrleansSQLUtils/Storage/DbExtensions.cs
src/OrleansSQLUtils/Storage/IRelationalStorage.cs
src/OrleansSQLUtils/Storage/RelationalOrleansQueries.cs
src/OrleansSQLUtils/Storage/RelationalStorage.cs
src/OrleansSQLUtils/Storage/RelationalStorageExtensions.cs
src/TesterInternal/StorageTests/RelationalStoreTests.cs
src/TesterInternal/TesterInternal.csproj
test/Tester/RelationalUtilities/MySqlStorageForTesting.cs
test/Tester/RelationalUtilities/RelationalStorageForTesting.cs
test/Tester/RelationalUtilities/SqlServerStorageForTesting.cs

Added CommandBehavior and CancellationToken to the relational
back-end implementation with tests. CommandBehavior is added
in anticipation of using streaming in state and streams provider
due to possibly large payload size.

CommandBehavior and CancellationToken added to relational back-end

---

src/Orleans/Logging/TraceLogger.cs
src/Orleans/Telemetry/Consumers/ConsoleTelemetryConsumer.cs
src/Orleans/Telemetry/Consumers/FileTelemetryConsumer.cs
src/Orleans/Telemetry/Consumers/TraceTelemetryConsumer.cs
src/Orleans/Telemetry/ITelemetryConsumer.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansTelemetryConsumers.AI/AITelemetryConsumer.cs
src/OrleansTelemetryConsumers.NewRelic/NRTelemetryConsumer.cs

Fix for bug #1471
- Added `Close()` and `Flush()` to `ITelemetryConsumer`.
- TraceLogger now properly closes the telemetry consumers.

Fix for bug #1471

---

src/OrleansRuntime/Silo/Silo.cs

Follow up on https://github.com/dotnet/orleans/pull/1494.

SiloTerminatedEvent.Set should be the last thing in the silo shutdown sequence.

---

src/OrleansVSTools/OrleansVSTools/OrleansVSTools.csproj
src/OrleansVSTools/OrleansVSTools/source.extension.vsixmanifest
src/OrleansVSTools/VSProjectSiloHost/VSProjectSiloHost.vstemplate
src/OrleansVSTools/VSProjectTemplateGrainImplementation/ProjectTemplate.csproj
src/OrleansVSTools/VSProjectTemplateGrainImplementation/VSProjectTemplateGrainImplementation.vstemplate
src/OrleansVSTools/VSProjectTemplateGrainInterface/ProjectTemplate.csproj
src/OrleansVSTools/VSProjectTemplateGrainInterface/VSProjectTemplateGrainInterface.vstemplate
src/SDK/UninstallOrleansVSTools.cmd

Switch C# project template in VSIX to use new CodeGen nuget.
Also, removed support for VS 2012 from the VSIX.

Switch C# project template in VSIX to use use new CodeGen nuget

---

src/Orleans/Messaging/Message.cs

Currently resizing of the `Message` headers dictionary are being conducted multiple times for a single grain call, and this leads to high memory traffic:
1:
2:
and CPU consumption:
Setting initial size of `headers` to 17 will reduce CPU consumption by ~ 200 ms (46%) per 1 million calls. ([used benchmark](https://gist.github.com/dVakulen/4c06da7a07121840098b)) for most common case of 14 items:
Method |      Median |    StdDev | InitialDictionarySize | ItemsCount |
------------------- |------------ |---------- |---------------- |------ |
DictionaryCreation |  51.6067 ms | 0.5801 ms |               0 |     1 |
DictionaryCreation | 444.2622 ms | 5.5458 ms |               0 |    14 |
DictionaryCreation | 198.1903 ms | 1.7021 ms |               0 |     5 |
DictionaryCreation |  79.7746 ms | …

Avoid resizing of Message headers dictionary

---

src/Orleans/Core/Exceptions.cs
src/Orleans/Messaging/Message.cs
src/Orleans/Messaging/RequestInvocationHistory.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Core/InsideGrainClient.cs

We had 2 headers (MethodId and InterfaceId) that duplicated information that is passed already via `InvokeMethodRequest`. They were only used for deadlock detection algorithm for diagnostics only. Changed the deadlock detection to use Debug Context instead.
This allows to save 2 headers on every msg. Was noticed as a result of @dVakulen 's comment https://github.com/dotnet/orleans/pull/1519#issuecomment-191907943.
Alternatively, we could remove those from `InvokeMethodRequest`, but that would require a much bigger change, this MethodId and InterfaceId in `InvokeMethodRequest` are used everywhere, including the generated code in the invokers.

Remove 2 redundant duplicate headers.

---

src/Orleans/Serialization/OrleansJsonSerializer.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
src/OrleansAzureUtils/Storage/AzureStorageUtils.cs

The main change in this PR is making OrleansJsonSerializer public.
This is a first step in https://github.com/dotnet/orleans/issues/1495 3): "Expose publicly settings of the JSON serializer used for A & C that app will have full control of."
That way any application code, and not only privileged Azure providers (that have internal control to the runtime assemblies) can use use Json settings.
In addition, small API improvements to the utility class, decoupling mutating the settings from where the default settings are stored.

Json serializer settings improvements.

---

src/Orleans/Logging/ErrorCodes.cs
src/OrleansRuntime/ReminderService/LocalReminderService.cs

This way the service will not block the silo from fully initializing before all the reminders are loaded.
Avoid reading and starting all the reminders if the Silo is stopped before finishing the first load.

Start ReminderService initial load in the background

---

src/Orleans/AssemblyLoader/AssemblyLoader.cs
src/Orleans/AssemblyLoader/AssemblyProcessor.cs
src/Orleans/CodeGeneration/TypeUtils.cs
src/OrleansRuntime/GrainTypeManager/SiloAssemblyLoader.cs

Trying to address the problem I've raised in https://github.com/dotnet/orleans/issues/1517 . If the failing assembly (in my case `Microsoft.CodeAnalysis.Scripting`) is loaded into `AppDomain` (so it is returned in `AppDomain.CurrentDomain.GetAssemblies()`), then the silo is crashing on start.

Safe load of types from failing assemblies in TypeUtils.GetTypes

---

src/OrleansVSTools/OrleansVSTools/OrleansVSTools.csproj
src/OrleansVSTools/VSProjectSiloHost/ProjectTemplate.csproj
src/OrleansVSTools/VSProjectSiloHost/VSProjectSiloHost.vstemplate
src/OrleansVSTools/VSProjectTemplateGrainImplementation/ProjectTemplate.csproj
src/OrleansVSTools/VSProjectTemplateGrainImplementation/VSProjectTemplateGrainImplementation.vstemplate
src/OrleansVSTools/VSProjectTemplateGrainInterface/ProjectTemplate.csproj
src/OrleansVSTools/VSProjectTemplateGrainInterface/VSProjectTemplateGrainInterface.vstemplate

Remove unnecessary NuGet references. Some of them cause build warnings.
Turn off deployment of the VSIX at the end of build.
Remove explicit references to Microsoft.Orleans.OrleansCodeGenerator.Build.targets from .csproj files that duplicate ones added by Microsoft.Orleans.OrleansCodeGenerator.Build NuGet package.

VSIX cleanup

---

src/Build/GlobalAssemblyInfo.cs
src/Build/GlobalAssemblyInfo.fs
src/OrleansCounterControl/app.manifest

We haven't updated assembly version in prior releases. We need to do that for releases with breaking changes, so that version mismatches are easier to detect.

Update assembly versions to match release version

---

src/Orleans/Streams/Predicates/FilterPredicateWrapperData.cs
src/Orleans/Streams/Predicates/OrFilter.cs

I believe it fixes https://github.com/dotnet/orleans/issues/836.
The filters were serialized correctly to Json, via defining ISerializable interface methods. There was just a missing declaration by the type as implementing ISerializable, so this serialization code was ignored.

Fixed Json serialization of  Stream Filter Predicates.

---

Samples/HelloWorld/HelloWorld/App.config
Samples/HelloWorld/Tests/App.config
Samples/HelloWorld/Tests/Tests.csproj

otherwise the test fails as it attempts to find JSON.NET v6

binding redirect required for the unit test to find json.net

---

src/Orleans/Orleans.nuget.targets

Everytime we build Orleans (from within VS or using scripts) we get that warning twice, that is harmless.
I believe this was added by mistake, as it was added in PR #832 (specifically commit 79ece4ba3a93970bae148d2a50284664dd22d7b6), that has nothing to do with the warning at hand.
Ping @jkonecki since he added that commit and maybe wants to keep the change.

Remove unnecessary NuGet warning

---

src/TesterInternal/Config_AzureStreamProviders.xml

Changed some selected streaming tests to `UseJsonFormat=true` for `PubSubStore`, to improve test coverage for Json pub sub state.

Use Json Format for PubSub storage in some Azure Queue streaming tests.

---

src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
test/TesterInternal/StorageTests/PersistenceGrainTests_AzureTableStore.cs
test/TesterInternal/StorageTests/PersistenceProviderTests.cs

This is a quick and easy change allowing `AzureTableStorage` to store larger amounts of binary data by using multiple columns. The use cases could be a large array, a long string etc when it exceeds the 64 KB limit, but is not enough reason by itself to use alternative storage providers. Note that the new code is backward-compatible with grain states persisted by previous versions of `AzureTableStorage`.
I know about the proposal outlined in https://github.com/dotnet/orleans/issues/1456 and quite similar `WidePersistent` attribute there. In my understanding the difference is that `WidePersistent` is supposed to tell that specific object properties should be stored in separate storage columns, while in my case it is done automatically judging by the data size. So, technically, these two …

Allow AzureTableStorage to store data larger than 64 KB

---

src/Orleans/Core/GrainClient.cs
src/Orleans/Core/InterceptedMethodInvoker.cs
src/Orleans/Core/InvocationMethodInfoMap.cs
src/Orleans/Orleans.csproj
src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Providers/IProviderRuntime.cs
src/Orleans/Providers/StatisticsProviderManager.cs
src/OrleansRuntime/Core/InsideGrainClient.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
src/OrleansRuntime/Storage/StorageProviderManager.cs
test/Tester/InvocationInterceptTests.cs
test/Tester/Tester.csproj
test/TesterInternal/SqlStatisticsPublisherTests/StatisticsPublisherProviderRuntime.cs

Based on the discussion in #749.

Feature: Server-side request interceptor (#749)

---

src/Orleans/Runtime/GrainReference.cs

Hello,
I've managed to uncover some bad calls to the `string.Substring()` method in `GrainReference.FromKeyString()`, which were being covered for by subsequent parsing methods in most cases (hence passing the provided roundtrip tests).
I only came across this when messing about with grain references in an attempt to test grain persistence within a silo - adding arbitrary characters to the end of existing key strings and then reparsing them exposed the problem, but only when generic arguments were included.

Fixed bad substring calls in GrainReference.FromKeyString

---

src/Orleans/CodeGeneration/GrainFactoryBase.cs
src/Orleans/CodeGeneration/GrainInterfaceUtils.cs
src/Orleans/Core/GrainFactory.cs
src/Orleans/Core/InvocationMethodInfoMap.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/GrainInterfaceMap.cs
src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs
src/OrleansCodeGenerator/CodeGeneratorCommon.cs
src/OrleansCodeGenerator/GrainMethodInvokerGenerator.cs
src/OrleansCodeGenerator/GrainReferenceGenerator.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs
src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeData.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs
src/OrleansRuntime/GrainTypeManager/SiloAssemblyLoader.cs
src/OrleansRuntime/Silo/SiloProviderRuntime.cs
test/TesterInternal/General/InterfaceRules.cs
test/TesterInternal/GrainReferenceCastTests.cs

Fixes #1570.
Renamed `Orleans.CodeGeneration.GrainInterfaceData` to `Orleans.CodeGeneration.GrainInterfaceUtils`, as realy more appropriate to this class - it has no data and only static helper/utility functions.
Moved `Orleans.Runtime.GrainInterfaceData` to be inside `Orleans.Runtime.GrainInterfaceMap`, as it is only used inside the  `GrainInterfaceMap`. So now it is: `Orleans.Runtime.GrainInterfaceMap.GrainInterfaceData`.

Solve duplication of GrainInterfaceData class name.

---

_includes/themes/twitter/default.html

Every page now has an edit link in the footer.
You can see the change here: http://richorama.github.io/orleans/

added link to edit page on github

---

src/Orleans/Configuration/MessagingConfiguration.cs
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/Constants.cs
src/Orleans/Runtime/GrainReference.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Serialization/BuiltInTypes.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Serialization/TypeUtilities.cs
src/Orleans/Threading/CancellationTokenHolderGrain.cs
src/Orleans/Threading/CancellationTokenManager.cs
src/Orleans/Threading/CancellationTokenWrapper.cs
src/Orleans/Threading/GCObserver.cs
src/Orleans/Threading/ICancellationTokenHolderGrain.cs
src/OrleansRuntime/Core/InsideGrainClient.cs
src/OrleansRuntime/Silo/Silo.cs
test/TestGrainInterfaces/IGenericInterfaces.cs
test/TestGrains/GenericGrains.cs
test/Tester/CancellationTests/CancellationTokenPassingTests.cs
test/Tester/Tester.csproj

#1516; 
Made through inspecting grain method arguments, wrapping found cancellation tokens and subscribing cancellation of tokens on crossing domain bounds. 
Added costs for general case - two grain method arguments array iterations with type checking. 
For consumer in case of in-silo token passing there's cost of 2 wrappers allocations, wich is neglectable. For remote case - mostly it will be the same as if user cancelled remote `TaskCompetitionSource` by himself: 1 grain call, but when token gets cancelled after grain call message serialization and before its deserialization there will be 2 grain calls (token holder grain will be allocated on different silo).

Cancellation token support

---

src/Orleans/Async/TaskExtensions.cs

https://github.com/dotnet/orleans/issues/1532#issuecomment-196405789;
This change does not affect current exception propagation behavior, but can become useful after TaskCompletionSource shuffling rework.

Set multiple inner exceptions to the resolver.

---

src/OrleansTestingHost/TestingSiloHost.cs

Track the correct additional silo when restarting it. Otherwise the original Secondary silo does not leak and stays running forever.
The `RestartSilo` method had a bug that if you restarted an "additional silo" (of type `Seconday` anyway), then the original Secondary silo would be leaked and running in the background, so clients that connected explicitly to it by adding a gateway to the secondary, were sometimes sending request to the old leaked silo of a different deployment.
I extracted the commit from PR #1583 as this one is safe to merge, where as whether we prevent reusing the same port might need some more discussion (or we might decide to not change the current behavior).

Avoid lingering silo in tests when restarting them

---

src/Build.cmd

~~~The `Build.cmd` script currently tries to check for MsBuild 14 (VS 2015) and stops / fails if it does not find it on the local machine, even though everything builds just fine with MsBuild 12 (VS 2013)~~~
~~~This change set is to tweak the logic in `Build.cmd` to allow either MsBuild 12 or 14, but still preferring to use 14 if installed.~~~
Also tweaks the logic about whether to build .vsix by using ev `BuildOrleansVsix` instead of overloading  `BuildOrleansNuGet` and defaults to not build .vsix unless `BuildOrleansVsix=true` so that things build cleanly on local machine for most developers who will only have Visual Studio / MsBuild installed and not the Visual Studio SDK.
~~~This change sets means that developers who have not yet upgraded to VS 2015 and are still using VS 2013 can …

Make Build.cmd support local build if VS SDK is not installed.

---

src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueStreamProviderUtils.cs
src/OrleansAzureUtils/Storage/AzureQueueDataManager.cs
test/TesterInternal/StreamingTests/HaloStreamSubscribeTests.cs

Clears all the messages in the queue between tests, and only deletes the queue after the entire fixture completes.
Otherwise it was trying to delete the queues without restarting the cluster, and sometimes would get conflicts (409) when trying to re-create the queues while it was still deleting.

Fix HaloStreamSubscribeTests concurrency issue

---

test/Tester/DeploymentTests/DeployTest.cs
test/Tester/TestUtils.cs
test/Tester/Tester.csproj
test/Tester/packages.config
test/TesterInternal/StorageTests/PersistenceGrainTests_AzureStore.cs
test/TesterInternal/StorageTests/RelationalStoreTests.cs
test/TesterInternal/TesterInternal.csproj
test/TesterInternal/TimerTests/ReminderTests_AzureTable.cs
test/TesterInternal/TimerTests/ReminderTests_Base.cs
test/TesterInternal/packages.config

Basically skip them without failing the build.
This is to allow for either some harmless non-determinism, or finding whether a certain runtime dependency is installed where the test is running.

Allow certain tests to finish inconclusive

---

src/OrleansVSTools/VSProjectSiloHost/OrleansHostWrapper.cs
src/OrleansVSTools/VSProjectSiloHost/VSProjectSiloHost.vstemplate

VS does not pull the dependency NuGets automatically. So we need to add them explicitly to the project template.

Add dependency NuGet packages to Dev/Test Host template

---

src/Orleans/Configuration/ProviderConfiguration.cs
src/OrleansProviders/ConfigExtensions.cs
src/OrleansProviders/OrleansProviders.csproj
src/OrleansVSTools/VSProjectSiloHost/OrleansHostWrapper.cs

Add an extension method for adding default "MemoryStore" persistence provider.
Update Dev/Test Host project template to use the extension method.
Allow null to be passed for provider properties.

Extension method for adding default "MemoryStore" persistence provider

---

src/Orleans/Orleans.csproj
src/Orleans/Streams/PersistentStreams/IStreamQueueCheckpointer.cs
src/Orleans/Streams/QueueAdapters/IQueueCache.cs
src/OrleansProviders/Streams/Common/PooledCache/CachedMessageBlock.cs
src/OrleansProviders/Streams/Common/PooledCache/CachedMessagePool.cs
src/OrleansProviders/Streams/Common/PooledCache/ICacheDataAdapter.cs
src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCache.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCacheCursor.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubCheckpointer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubPartitionCheckpointEntity.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubStreamProviderConfig.cs
src/OrleansServiceBus/Providers/Streams/EventHub/ICheckpointerSettings.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubQueueCache.cs
test/Tester/StreamingTests/EHImplicitSubscriptionStreamRecoveryTests.cs
test/Tester/StreamingTests/EHStreamProviderCheckpointTests.cs
test/Tester/StreamingTests/EHSubscriptionMultiplicityTests.cs
test/Tester/TestStreamProviders/Generator/GeneratorPooledCache.cs
test/TesterInternal/OrleansRuntime/Streams/CachedMessageBlockTests.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs
test/TesterInternal/StreamingTests/AzureQueueAdapterTests.cs
test/TesterInternal/StreamingTests/TestStreamIdentity.cs
test/TesterInternal/TesterInternal.csproj

This change allows application developers to provide their own stream failure handlers, checkpointing logic, and data adapters.
This should address feature "Modular Message format" in "Recoverable Event Hub Persistent Stream Provider - Part 2" #1454 
>Modular Message format. – For the EventHubStreamProvider to process a wide range of messages from EventHub, the cache data adapter must be a pluggable component that application developers can provide.

EventHubStreamProvider extensibility.

---

src/Orleans/Serialization/TypeUtilities.cs

Addresses https://github.com/dotnet/orleans/issues/1305, 
Checking for ability of shallow copying is taking considerable amount of CPU:
Benchmark, 3 000 000 repeats:
```ini
BenchmarkDotNet=v0.9.1.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz, ProcessorCount=4
Frequency=2435776 ticks, Resolution=410.5468 ns
HostCLR=MS.NET 4.0.30319.34209, Arch=32-bit RELEASE
Type=ShallowCopyableBench  Mode=Throughput  LaunchCount=1  
WarmupCount=1  TargetCount=3  
```
Method |        Median |      StdDev | ThreadsCount |
------------------------------ |-------------- |------------ |------------- |
CachedClass |   106.5624 ms |   3.1811 ms |            1 |
CachedDecimal |   106.4367 ms |   1.8021 ms |            1 |
CachedImmutable |   104.3393 ms |   1.7869 ms | …

Cached type shallow copy availability

---

src/Orleans/IDs/Interner.cs

The Count property takes a full lock on the concurrent dictionary and in the `Interner`'s `InternCacheCleanupTimerCallback` method it's being accessed twice but used only if logging level is set to `Verbose` or higher. 
I wouldn't expect this change to make any noticeable perf impact, but it's still nice to have.

Removed concurrent dictionary Count property accessing

---

src/Orleans/Runtime/GrainReference.cs
src/OrleansCodeGenerator/GrainReferenceGenerator.cs
test/TestGrainInterfaces/IGenericInterfaces.cs
test/TestGrains/GenericGrains.cs
test/Tester/GenericGrainTests.cs
test/TesterInternal/GrainReferenceCastTests.cs

Hello,
I've stumbled across another generics-related bug: calling `IGrain.AsReference()` to cast to another, generic grain interface results in an unusable `GrainReference` with the `genericArguments` field unchanged from that of the original reference.
I've had a go at a PR for fixing this, which gets the generated reference classes to override a protected `GenericArguments` property on the base `GrainReference`, much as the `InterfaceName` is overridden currently, but without the public surface.
Hopefully this is all reasonable - I'm a bit mindful of messing with internal components without prior discussion, but am also fairly eager to contribute, so thought I'd give it a go.

Generic reference casting

---

src/OrleansAzureUtils/Storage/AzureBasedReminderTable.cs
test/TesterInternal/TimerTests/ReminderTests_AzureTable.cs
test/TesterInternal/TimerTests/ReminderTests_Base.cs
test/TesterInternal/TimerTests/ReminderTests_SqlServer.cs
test/TesterInternal/TimerTests/ReminderTests_TableGrain.cs

Code was encountering a null reference exception from azure reminder service when requesting a reminder that did not exist.
Added test requesting a reminder that does not exist.
Updated code to return null rather then throw a null reference exception if reminder is not found.

Fix null reference exception in azure reminder service

---

src/Orleans/Streams/PubSub/ImplicitStreamPubSub.cs
test/TestGrains/ImplicitSubscription_TransientError_RecoverableStream_CollectorGrain.cs

When using implicit subscriptions, the subscription Id in handles returned by GetAllSubscriptionHandles was incorrect.
- Implicit subscription recovery test was updated to resume processing using GetAllSubscriptionHandles to exercise code path and reproduce the problem.
- Subscription Id generation was fixed.
Thanks @skalpin, @sergeybykov

GetAllSubscriptionHandles fix for implicit subscriptions

---

src/OrleansAzureUtils/Hosting/AzureClient.cs
src/OrleansAzureUtils/Hosting/AzureSilo.cs

Add AzureClient.DefaultAzureConfig() and AzureSilo.DefaultAzureConfig() helper methods.
Usage examples are in https://github.com/sergeybykov/orleans/blob/sample/Samples/AzureWebSample/WebRole/Default.aspx.cs#L16 and https://github.com/sergeybykov/orleans/blob/sample/Samples/AzureWebSample/OrleansAzureSilos/WorkerRole.cs#L49.

Add helper methods to AzureClient and AzureSilo for easier programmatic config

---

src/Orleans/Serialization/SerializationManager.cs
src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansAzureUtils/Providers/AzureConfigurationExtensions.cs
src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
src/OrleansTestingHost/Extensions/ConfigurationExtensions.cs
src/OrleansTestingHost/OrleansTestingHost.csproj
test/Tester/GenericGrainsInAzureStorageTests.cs
test/Tester/StreamingTests/EHStreamProviderCheckpointTests.cs

A few useful methods I found while doing a refactoring of the test infrastructure, which uses  programmatic config as a first class citizen (PR coming soon, but not just yet)

Extension methods for using programmatic config

---

src/Orleans/Streams/Internal/StreamConsumer.cs
src/Orleans/Streams/Internal/StreamConsumerExtension.cs
src/Orleans/Streams/Internal/StreamSubscriptionHandleImpl.cs
test/TestInternalGrains/StreamLifecycleTestGrains.cs
test/TestInternalGrains/StreamLifecycleTestInternalGrains.cs

As described in https://github.com/dotnet/orleans/issues/1615, Azure Queue Stream Provider was erroneously trying to establish and guarantee ordered delivery, which resulted in lost data.
Azure Queue Stream Provider does not guarantee ordered delivery (since the underlying Azure Queue does not), and thus should not even attempt to.
This fix conditions the delivery checks ("the handshake protocol") to only ordered stream providers.
I re-used the notion of Rewindable stream provider, since it seems that ordered and rewindable would always be the same - if provider does not guarantee order, it cannot be rewinded, and the opposite. At least as of now, AQST and SMS are both non rewindable and non ordered, while EHST is both rewindable and ordered, and thus I think there is no need (at least …

Fix to Azure Queue Stream provider ordering bug.

---

src/NuGet/Microsoft.Orleans.Client.nuspec
src/NuGet/Microsoft.Orleans.Server.nuspec
src/Orleans.sln

I see two reasons for removing config files from these NuGets.
1) When a config file is used a target project, an upgrade to these packages can overwrite its content.
2) We are moving to programmatic config in 1.2.0, and config files are being removed from all samples to avoid confusion.

Remove config filed from Server and Client NuGet packages

---

src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql

Some statistics can exceed the 250 characters, esp. with long domain
names, created for [#1628](https://github.com/dotnet/orleans/issues/1628)

Increased column Statistic in OrleansStatisticsTable to 512

---

src/Orleans/Configuration/MessagingConfiguration.cs
src/Orleans/Core/GrainClient.cs
src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Runtime/Constants.cs
src/Orleans/Runtime/IRuntimeClient.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Messaging/Gateway.cs
src/OrleansTestingHost/TestingSiloHost.cs
test/Tester/StreamingTests/AQClientStreamTests.cs
test/Tester/StreamingTests/ClientStreamTestRunner.cs
test/Tester/StreamingTests/EHClientStreamTests.cs
test/Tester/StreamingTests/SMSClientStreamTests.cs
test/Tester/Tester.csproj

Added tests to reproduce issues #1421, and #982
Issue only applies to SMS, but applied test to all supported stream providers for test coverage reasons.
- Updated test framework so tests could shutdown or hard kill grain client as well as initialize new grain client.
- Added client stream test runner with one test
- StreamProducerOnDroppedClientTest
- Will add more as needed.
- Added SMS stream client tests using test runner
- Added AzureQueue stream client tests using test runner
- Added EventHub stream client tests using test runner

Client Streaming Tests

---

src/Orleans/Orleans.csproj
src/Orleans/Streams/QueueAdapters/AggregatedQueueFlowController.cs
src/Orleans/Streams/QueueAdapters/IQueueCache.cs
src/Orleans/Streams/QueueAdapters/IQueueFlowController.cs
src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCache.cs
src/OrleansProviders/Streams/Generator/GeneratorPooledCache.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubSequenceToken.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubSettings.cs
src/OrleansServiceBus/Providers/Streams/EventHub/SegmentBuilder.cs

Introduced basic flow control mechanism to Persistent Stream Provider's adapter.
Added minimal flow control to EventHubStreamProvider that uses relative positions of cursors in cache to detect risk of cache miss errors, and reduces read rate in those cases.
Possible flow control mechanisms under consideration:
Load Shedding - Use silo load shedding detection to turn off queue readers.
Event/Second upper bound - Use configurable max event per second read rate.
This change minimally addresses Flow Control described in Recoverable Event Hub Persistent Stream Provider - Part 2 #1454

EventHubStreamProvider flow control

---

src/Orleans/Messaging/Message.cs
src/Orleans/Runtime/GrainReference.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs
test/Tester/StreamingTests/SMSClientStreamTests.cs

The pubsub system was unable to detect (and remove) dead producers on unavailable clients.  This would put the pubsub system in a non-recoverable state where all further subscriptions on a stream would fail.

Remove dead client producer from pub sub

---

src/OrleansTestingHost/Extensions/TestConfigurationExtensions.cs

Some tests in our private VSO started failing after #1641. This fixes the issue.

Avoid overwriting the connection string if it was already set

---

src/OrleansTestingHost/TestingSiloHost.cs
test/Tester/Tester.csproj
test/Tester/TestingHost/TestingSiloHostTests.cs

This was a regression since 1.1.3, where the GrainFactory was available for the first test method that runs, but not for the subsequent, when not starting a fresh Orleans cluster.

Copy GrainFactory to new TestingSiloHost instance when not starting fresh

---

src/OrleansTestingHost/OrleansTestingHost.csproj
src/OrleansTestingHost/Utils/AsyncResultHandle.cs
src/OrleansTestingHost/Utils/StorageEmulator.cs
src/OrleansTestingHost/Utils/TestingUtils.cs
test/Tester/ObserverTests.cs
test/Tester/SerializationTests/SerializationTests.DifferentTypes.cs
test/Tester/StreamingTests/ClientStreamTestRunner.cs
test/Tester/StreamingTests/ControllableStreamGeneratorProviderTests.cs
test/Tester/StreamingTests/DeactivationTestRunner.cs
test/Tester/StreamingTests/EHStreamProviderCheckpointTests.cs
test/Tester/StreamingTests/ImplicitSubscritionRecoverableStreamTestRunner.cs
test/Tester/StreamingTests/SampleStreamingTests.cs
test/Tester/StreamingTests/StreamFilteringTests.cs
test/Tester/StreamingTests/StreamGeneratorProviderTests.cs
test/Tester/StreamingTests/SubscriptionMultiplicityTestRunner.cs
test/Tester/TestUtils.cs
test/TesterInternal/General/Identifiertests.cs
test/TesterInternal/OrleansRuntime/ExceptionsTests.cs
test/TesterInternal/StorageTests/AzureTableDataManagerStressTests.cs
test/TesterInternal/StorageTests/AzureTableDataManagerTests.cs
test/TesterInternal/StreamingTests/HaloStreamSubscribeTests.cs
test/TesterInternal/StreamingTests/SingleStreamTestRunner.cs

Moved some utilities to a non-root namespace (TestingHost.Utils) that already existed.

TestingHost root namespace cleanup

---

test/TestGrainInterfaces/IPersistenceTestGrains.cs
test/TestInternalGrains/PersistenceTestGrains.cs
test/TesterInternal/StorageTests/PersistenceGrainTests.cs

Added a failing test demonstrating that generic grain state isn't being loaded with the correct ``grainType`` string on activation, as per #1579.
Applied the 'skip' attribute.

Repro for #1579 - loading of generic grain state on activation

---

src/OrleansTestingHost/OrleansTestingHost.csproj
src/OrleansTestingHost/TestingSiloHost.cs

Even though we'll endorse using the new test infrastructure in #1643, we are making easy to start a new silo without the need for config files.
The config files will be removed from the nuget spec in that other PR.

Fallback for initializing TestingSiloHost without config files

---

test/TestGrainInterfaces/IGenericInterfaces.cs
test/TestGrains/GenericGrains.cs
test/Tester/GenericGrainTests.cs
test/TesterInternal/CodeGeneratorTests.cs

Just spent an enjoyable evening writing out loads of pedantic generics tests, most of which are contrived edge cases, but are nevertheless in the spirit of normal .NET type behaviour. They all fail except for a couple, and all have been given the 'skip' argument. I've tried to generally cover concrete type resolution, and casting between references, both before and after activation.
I reckon they should all - in a perfect world - work. In an imperfect world, some should perhaps be "cleanly disallowed".
#1604 may interfere with many of them, but only one of the tests is solved by reverting it.
A point of interest is that one class declaration breaks the codegen, and has had to be commented out for any other tests to function. I've not looked into this properly, but suspect it's to do with …

Generic edge case tests

---

src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProducer.cs
src/Orleans/Streams/SimpleMessageStream/SimpleMessageStreamProducerExtension.cs
src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapterFactory.cs
src/OrleansAzureUtils/Providers/Streams/PersistentStreams/StreamDeliveryFailureEntity.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/OrleansServiceBus/Providers/Streams/EventHub/SegmentBuilder.cs
test/TestGrains/SampleStreamingGrain.cs
test/Tester/StreamingTests/AQClientStreamTests.cs
test/Tester/StreamingTests/ClientStreamTestRunner.cs
test/Tester/StreamingTests/EHClientStreamTests.cs
test/Tester/StreamingTests/SMSClientStreamTests.cs
test/Tester/TestStreamProviders/AzureQueue/TestAzureQueueStreamProvider.cs
test/Tester/TestStreamProviders/EventHub/TestEventHubStreamProvider.cs
test/Tester/TestStreamProviders/TestAzureTableStorageStreamFailureHandler.cs
test/Tester/Tester.csproj

Added basic tests demonstrating issues with losing clients that are consuming from streams.
Fixed sms and azure queue and event hub stream providers to handle delivery failures to loss clients.
Azure queue test is disabled as it does not work well yet due to issues unrelated to this PR or client stream consumers.

Stream consumers on lost clients

---

test/Tester/StreamingTests/DelayedQueueRebalancingTests.cs

Test was failing intermittently because silo was maturing too fast for test to catch the first stages.  Increased silo maturity time to fix.

DelayedQueueRebalancing test intermittent failure fix

---

src/Orleans/Core/GrainExtensions.cs
test/Tester/KeyExtensionTests.cs

This is only for API completion. `Guid GetPrimaryKey(this IAddressable grain, out string keyExt)` already does the same but in a cruder form.

Add GetPrimaryKeyString extension method for IAddressable

---

Orleans-Configuration-Guide/Server-Configuration.md

Correct me if I'm wrong but:
`PrimaryNode` and `ProxyGatewayEndpoint` must not be set in programmatic configuration for Azure. I spend half a day looking for incorrect config values (client and server were not able to talk to each other in local Azure Emulator) until figured out the culpit. 
It's still not clear for me when and why one need to configure these properties (do we need it for real deployment ? what functional load do these carry ? ) so I'd like to hear feedback from core devs about my 'guess' . Thanks in advance

fix: amending server programmatic configuration

---

src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
test/TesterInternal/StorageTests/PersistenceProviderTests.cs

Azure table storage provider was returning null state object by default after clearing the grains state.
Added test case to reproduce problem.
Modified azure table storage provider to return default grain state if no state was found in the entity.

Azure table storage provider returning null grain state - fixed

---

src/OrleansAzureUtils/OrleansAzureUtils.csproj
src/OrleansAzureUtils/Storage/AzureTableDataManager.cs
src/OrleansAzureUtils/Storage/TableQueryFilterBuilder.cs

Update Orleans azure utils to be compatible with WindowsAzure.Storeage 7.0.0
Addresses issue described in Error starting orleans on Azure with WindowsAzure.Storage 7.0.0 #1700 
The TableOperation.Retrieve api call arguments changed in 7.0.0 so we replaced retrieve call with a table query.

Azure storage 7.0 compatibility.

---

src/OrleansRuntime/Silo/SiloHost.cs

I ran across this a few times where StartOrleansSilo just returns false, and I don't get any info about why, so with this, we can choose to receive any exceptions that are thrown.

added ability to throw exceptions that occur when starting silo

---

Getting-Started-With-Orleans/Developing-a-Client.md

Fix heading of example to make it consistent with the rest of the documentation.
I believe there was a typo.

Fix example heading in Developing-a-Client.md

---

Samples-Overview/Hello-World.md
Step-by-step-Tutorials/Actor-Identity.md

Looks like GrainBase class was removed but documentation hasn't been updated
Put correct grain base class.

Fix grain base class in documentation

---

test/TesterInternal/StorageTests/PersistenceGrainTests_AzureBlobStore.cs
test/TesterInternal/StorageTests/PersistenceGrainTests_AzureTableStore.cs

Starts the Azure storage emulator for persistence tests on local
development. If the emulator is not on and persistence tests are
started individually, the tests hang quite a while without any
indication as of the reason while starting the silo.

Starts Azure storage emulator on local persistence tests

---

src/Orleans/SystemTargetInterfaces/IMembershipTable.cs

SupressDuplicateDeads: Use SiloAddress.Endpoint instead of InstanceName.

---

src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.Build.nuspec
src/Orleans.SDK.targets

See issue #1718 
Add build target to include Properties\orleans.codegen.cs in Compile ItemGroup if it's not already there.
Removed empty file from being added as content to Microsoft.Orleans.OrleansCodeGenerator.Build nuget package.

Remove content files from NuGet packages

---

src/OrleansSQLUtils/OrleansSQLUtils.csproj
test/Tester/MembershipTests/LivenessTests.cs
test/Tester/Tester.csproj

With these minor changes, liveness tests pass successfully on Sql Server, MySql and ZK.
I hope bugs like  #1725 are a thing of the past.

fix liveness tests for Sql Server, MySql and ZK

---

src/Orleans/CodeGeneration/TypeUtils.cs
test/Tester/GenericGrainTests.cs

Type resolution for instantiating a generic grain that is passed a generic argument with more than one parameter did not work.
Thus, I changed the type resolving algorithm to parse nested structures of generic types and argument lists.
I could add a few more edge test cases if required.

Added support for complex generic grain parameters

---

src/Orleans/AssemblyLoader/AssemblyLoaderPathNameCriterion.cs
src/Orleans/Logging/TraceLogger.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Streams/Internal/StreamSubscriptionHandleImpl.cs
src/Orleans/Streams/Predicates/FilterPredicateWrapperData.cs
src/OrleansCodeGenerator/SerializerGenerator.cs
src/OrleansCodeGenerator/Utilities/SyntaxFactoryExtensions.cs
test/TestGrains/GenericGrains.cs

Revert #1122 that uses Activator.CreateInstance() instead of FormatterServices.GetUninitializedObject().
Use reflection to get to this internal method when in CoreCLR.

Use GetUninitializedObject with Reflection in coreclr

---

src/Orleans/Streams/Core/StreamIdentity.cs
src/OrleansProviders/Streams/Common/PooledCache/CachedMessageBlock.cs
src/OrleansProviders/Streams/Common/PooledCache/CachedMessagePool.cs
src/OrleansProviders/Streams/Common/PooledCache/ICacheDataAdapter.cs
src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
src/OrleansProviders/Streams/Generator/GeneratorPooledCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventDataExtensions.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubBatchContainer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubSequenceToken.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubQueueCache.cs
test/Tester/StreamingTests/EHImplicitSubscriptionStreamRecoveryTests.cs
test/Tester/TestStreamProviders/EventHub/StreamPerPartitionEventHubStreamProvider.cs
test/TesterInternal/OrleansRuntime/Streams/CachedMessageBlockTests.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs

All data from EventHub EventData is now cached.
EventHubDataAdapter now supports a EventData-like data structure when converting data from cache for delivery.
Dequeue time has been added to cached data to track how long messages have been in the cache.

Event hub stream provider EventData to cached data mapping

---

src/Orleans/Streams/PersistentStreams/IDeploymentConfiguration.cs
src/Orleans/SystemTargetInterfaces/IMembershipTable.cs
src/OrleansAzureUtils/Hosting/AzureSilo.cs
src/OrleansAzureUtils/Hosting/ServiceRuntimeWrapper.cs
src/OrleansAzureUtils/Storage/AzureBasedMembershipTable.cs
src/OrleansAzureUtils/Storage/OrleansSiloInstanceManager.cs
src/OrleansConsulUtils/SerializableMembershipTypes.cs
src/OrleansRuntime/MembershipService/MembershipOracle.cs
src/OrleansRuntime/MembershipService/MembershipOracleData.cs
src/OrleansRuntime/Streams/QueueBalancer/DeploymentBasedQueueBalancer.cs
src/OrleansRuntime/Streams/QueueBalancer/StaticClusterDeploymentConfiguration.cs
src/OrleansZooKeeperUtils/MembershipSerializerSettings.cs
test/TesterInternal/StorageTests/SiloInstanceTableManagerTests.cs

Addresses https://github.com/dotnet/orleans/issues/1738.
One important issue to watch is backward compatibility: since InstanceName  is persisted, what will happen if we suddenly rename it to SiloName? Our clients should work without experiencing any pain, for example without needing to fully stop the cluster and delete the whole table.
I addressed backward compatibility issue on Azure. I kept both columns in the table. New silo will write its SiloName into both columns, and when reading entries of other silos it will try to parse SiloName from either of the columns. 
I believe this will allow a mixed cluster (with old and new version) to co-exist. However, I have not tested that. In general, in other systems, this is a rather complicated and delicate issue that has to be dealt with great …

Rename InstanceName to SiloName.

---

test/TesterInternal/TesterInternal.csproj

Was added by #1508 in an early iteration, but never removed. It was causing a build warning.

Remove nonexistent project reference

---

src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.nuspec
src/NuGet/Microsoft.Orleans.OrleansServiceBus.nuspec
src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/NuGet/Microsoft.Orleans.TestingHost.nuspec
src/OrleansCodeGenerator/OrleansCodeGenerator.csproj
src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/app.config
src/OrleansServiceBus/packages.config
src/OrleansTestingHost/OrleansTestingHost.csproj
src/OrleansZooKeeperUtils/OrleansZooKeeperUtils.csproj
test/Tester/Tester.csproj
test/Tester/packages.config

Fixes to include XML docs in the remaining nuget packages.
Also updated the dependency on WindowsAzure.ServiceBus package, since it's non-breaking but fixes some important bugs.

NuGet metadata fixes (and Servicebus package update)

---

src/Orleans/Core/Grain.cs

Hello,
Grain.ServiceProvider wasn't being set when the parameterless ctor was used. 
I've made the Grain.GrainFactory and Grain.ServiceProvider props delegate directly to the grain runtime, so that their values don't have to be set in two separate places.

Refactored grain props slightly, fixing null ServiceProvider problem

---

src/Orleans/Messaging/GatewayProviderFactory.cs

Fixes https://github.com/dotnet/orleans/issues/1769.
The client should now reconnect at most one minute after silos restart. This can be shortened by changing `GatewayListRefreshPeriod` in the client config.

Change StaticGatewayListProvider to be Updatable.

---

src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql

Following @sergeybykov's [comment](https://github.com/dotnet/orleans/pull/1682#issuecomment-213001965). Also, it seems [DateTime2](https://msdn.microsoft.com/en-us/library/bb677335.aspx) is supported from SQL Server 2008 and above, but Microsoft has [stopped support for SQL Server 2005](https://www.microsoft.com/en-us/server-cloud/products/sql-server-2005/). So this PR is for removing support for SQL Server 2005 too.

CreateOrleansTables_SqlServer.sql: Removed support for SQL Server 2000 and 2005

---

src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansCodeGenerator/SerializerGenerator.cs

Fixes #1782.
Simple change, we use `GetTypeInfo()` to when creating the field accessors for generated serializer classes.
Since `GetTypeInfo` is an extension method, we also import `System.Reflection`. This is not anticipated to cause any ambiguity since we use fully qualified type names everywhere. If this becomes a problem we can certainly call `GetTypeInfo` as a static/non-extension method.

CoreCLR Support: fix #1782 - use TypeInfo instead of Type in codegen

---

src/OrleansBondUtils/BondSerializer.cs

Sometimes, the static readonly members aren't initialized prior to being accessed in the IsSupportedType() method.  This shouldn't be possible as far as I know. This is a workaround to the problem.

Fix for strange bug

---

src/Orleans/SystemTargetInterfaces/IManagementGrain.cs
src/OrleansRuntime/Core/ManagementGrain.cs
test/Tester/ManagementGrainTests.cs

This returns an array of `MembershipEntry`, for either active, or all silos.
See issue #1789

Added ManagementGrain.GetDetailedHosts()

---

src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Statistics/RuntimeStatisticsGroup.cs

Log .NET Thread Pool size on the client (to help diagnose issues like https://github.com/dotnet/orleans/issues/1775#issuecomment-220758439).
Also, `RuntimeStatistics` are not printed on the client if it fails to load CPU & Memory perf counters. `RuntimeStatistics` has a lot of usefull statistics that can still be printed even if perf counters are not available. So added null protection for each and every individual perf counter instead of failing the all together.

Log more runtime statistics on the client.

---

src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Catalog/GrainCreator.cs
src/OrleansRuntime/OrleansRuntime.csproj

Added a grain creator class that further enables unit testing grains without the need for a full silo. This enables the same behavior of the test only constructor ` protected Grain(IGrainIdentity identity, IGrainRuntime runtime)` , but doesnt force developers to add test specific code to their production grains. I plan to add Grain<T> as well, but I wanted to get the discussion started.

Test helpers

---

src/OrleansProviders/Storage/MemoryStorage.cs
src/OrleansRuntime/Storage/MemoryStorageGrain.cs
test/TestGrainInterfaces/IPersistenceTestGrains.cs
test/TestInternalGrains/PersistenceTestGrains.cs
test/TesterInternal/StorageTests/PersistenceGrainTests.cs

MemoryStorage had eTag mismatch when clearing the state and subsequently writing to it.
Previous to 1.2.1 this was actually throwing a cryptic NullReferenceException instead, but commit a1d35959 partially addressed it (but not the etag mismatch).

MemoryStorage bug fix when calling Clear state

---

src/Orleans/Async/AsyncExecutorWithRetries.cs
src/Orleans/Messaging/SocketManager.cs
src/Orleans/Utils/Utils.cs
test/TestInternalGrains/StreamReliabilityTestGrains.cs
test/TesterInternal/CodeGeneratorTests.cs
test/TesterInternal/SerializerTests/MessageSerializerTests.cs

While doing the CoreCLR migration (prototype), I found a few items that could be cleaned up even if we don't port to it yet.

General code cleanup in preparation for CoreCLR

---

src/Orleans/Async/TaskExtensions.cs
src/Orleans/Runtime/GrainReference.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
test/Tester/ExceptionPropagationTests.cs
test/Tester/GenericGrainTests.cs

Preserve remote stacktrace when propagating exception to the caller.
Previous to this change the entire remote exception would be lost, making it very hard to troubleshoot issues. We broke the stacktrace propagation with change 3560de8b when we started propagating the original exception to the caller instead of AggregateException (included in 1.2.0).

Exception stacktrace preservation

---

src/OrleansAzureUtils/Storage/AzureTableDataManager.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventDataExtensions.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
test/Tester/StreamingTests/EHClientStreamTests.cs
test/Tester/StreamingTests/EHImplicitSubscriptionStreamRecoveryTests.cs
test/Tester/StreamingTests/EHStreamPerPartitionTests.cs
test/Tester/StreamingTests/EHStreamProviderCheckpointTests.cs
test/Tester/StreamingTests/EHSubscriptionMultiplicityTests.cs

The EventHub stream provider partition checkpoints were being corrupted due to a change to the way the offset was being stored in the cache.
Offset is now stored consistently and in an accessible way for the checkpointing.
This bug was masked by timing issues in the tests, so test cleanup and timeouts have been modified.

EventHub stream provider partition checkpoint corruption fix

---

src/OrleansTestingHost/TestClusterOptions.cs
test/Tester/MembershipTests/LivenessTests.cs

when creating the client configuration from the cluster config.
Also fixed the deployment name to separate date from time correctly

Allow liveness config in TestCluster

---

Getting-Started-With-Orleans/Grains.md

The link currently in the page resolves to '/orleans/Getting-Started-With-Orleans/Orleans/Getting-Stated-With-Orleans/Grain-Persistence', which is an invalid page. This changes it to resolve to '/orleans/Getting-Started-With-Orleans/Grain-Persistence'.

Correct URL in Grains.md

---

Advanced-Concepts/Relational-Storage-Design-Rationale.md
Advanced-Concepts/index.md
Runtime-Implementation-Details/Relational-Storage-Design-Rationale.md

*** **DO NOT MERGE THIS YET** ***
I add material and arrange the text during the next 24 hours.
The current documentation lacks explanation of the goals and the factors of the of the relational storage sub-system, OrleansSQLUtils, design. This lack of documentation makes it needlessly difficult to:
1. Realize the potential use cases in one’s problem domain.
2. Increases effort to make a contribution.
This patch addresses these problems and partially addresses #1810.

Add relational storage design rationale

---

src/Orleans/Streams/PubSub/ImplicitStreamSubscriberTable.cs

Hash codes used in implicit subscription id generation must be consistent.
This change replaces .net hash code generation with jenkins.

Consistent implicit subscription Id generation.

---

src/OrleansRuntime/Core/ManagementGrain.cs

Half-way down #610 it's quietly suggested that ``IManagementGrain.SendControlCommandToProvider`` could be exploited to message between silos in a slightly more chatty manner than initially intended - communicating cache invalidations, for instance.
This is all well and good, but the current implementation logs once per message, which has the potential to get quite noisy.
So - I've added an optional parameter to the signature to bypass logging.

Added option to perform provider commands quietly

---

Samples/StorageProviders/StorageProviders/BaseJSONStorageProvider.cs

Was just roaming around and saw this.
It's not a big deal since most of the times the conditions are met and this is only a sample but still i was reading it and felt changing it.
Previously it first was trying to get the type name resolved by splitting the string with "." and then check for DataManager to see if it's null or not and throw an exception if it was. Potentially it was wasted time doing string processing and it is always more clear to check pre-conditions before anything else.

Improved BaseJSONProvider in storage samples a bit

---

src/Orleans/Async/Cancellation/GrainCancellationToken.cs
src/Orleans/Async/Cancellation/GrainCancellationTokenSource.cs
src/Orleans/Async/Cancellation/ICancellationSourcesExtension.cs
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/GrainReference.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Async/CancellationSourcesExtension.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/OrleansRuntime.csproj
test/TestGrainInterfaces/IGenericInterfaces.cs
test/TestGrains/GenericGrains.cs
test/Tester/CancellationTests/GrainCancellationTokenTests.cs
test/Tester/Tester.csproj

Implemented using grain extensions accordingly to the https://github.com/dotnet/orleans/pull/1569#issuecomment-198843172

Support cancellation tokens in grain method signatures

---

changelog.md

Just copied what we have in our individual releases.
We should start filling out everything that was is not covered by the 1.2.X releases

Initial version of the changelog file

---

src/Orleans/Configuration/ConfigurationExtensions.cs
src/OrleansTestingHost/Extensions/ConfigurationExtensions.cs

Just what you'd expect from the title, I'd suppose.
I was moaning a little bit on #1765 about configuring the startup class being non-obvious, especially in the context of ``TestCluster``, which prepopulates overrides.
So - a small helper extension method to set the ``StartupTypeName`` property on all nodes.

ClusterConfiguration extension for setting Startup class

---

src/OrleansRuntime/Core/GrainTimer.cs
src/OrleansRuntime/Scheduler/OrleansTaskScheduler.cs

To prevent cases like https://github.com/dotnet/orleans/issues/1824

Throw meaningful exception if grain timer is created outside grain context

---

src/OrleansTestingHost/TestClusterOptions.cs
src/Test.cmd
src/TestAll.cmd
test/Tester/ObserverTests.cs
test/Tester/StreamingTests/GeneratedStreamRecoveryTests.cs
test/Tester/StreamingTests/SMSClientStreamTests.cs
test/Tester/TestingHost/TestingSiloHostTests.cs
test/TesterInternal/GatewaySelectionTest.cs
test/TesterInternal/General/Identifiertests.cs

* Default to 2 silos being started in the TestCluster.
This is to spot serialization issues that don't occur in a 1 silo deployment that just does deep copying.
* Demoted some very slow tests from BVT to Functional.
They are still being run by our CI server, just not every time a dev wants to run all BVTs or for every pull request.
This should shave off a couple of minutes from our BVT run

Default testcluster size

---

src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueMapper.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubQueueMapper.cs

- Making the provider config a protected member that can be accessed in derived factory types
- Making the QueueMapper public so custom implementations can be authored in derived types

Updating EventHubAdapterFactory for extensibility.

---

src/Orleans/Configuration/GlobalConfiguration.cs
src/Orleans/Configuration/OrleansConfiguration.xsd
src/Orleans/Logging/ErrorCodes.cs
src/OrleansRuntime/MembershipService/MembershipOracle.cs

Addresses https://github.com/dotnet/orleans/issues/1862.
Also added configuration that allows to disable ValidateInitialConnectivity . Still by default it is on for now.
One issue with the error msg is that it is currently logged in the place where the connectivity check fails, but this particular reason is not propagated back in the exception that eventually is thrown from Silo.Start. Doing this is a bit harder since the connectivity logic is executed fro within a general purpose async retry mechanism that has a time limit on the number of retries and eventuality it fails with Timeout Exception (and that is the exception that is thrown from Silo.Start). So if we wanted to throw out the original exception that caused lets say the last iteration of the retry loop to fail, it will require …

Log special error msg when silo fails to join due to initial connectivity problems.

---

src/ClientGenerator/ClientGenerator.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs

Tiny change to clean up the use of a singleton in `RoslynCodeGenerator` which was only referenced by `ClientGenerator`.
This just moves the static to the code which uses it.

Remove static singleton Instance property from RoslynCodeGenerator

---

test/TestGrainInterfaces/IStatelessWorkerGrain.cs
test/TestGrains/StatelessWorkerGrain.cs
test/Tester/StatelessWorkerTests.cs

Tests stopped working after we made the default to run with 2 silos in the test cluster (so we were seeing 2 activations: 1 per silo).
As I was fixing this, I noticed that there is some non-deterministic behavior when we enqueue several calls to the same stateless worker when it wasn't activated before. Did not fix the bug, just created the repro test.

StatelessWorkerTests working with more than 1 silo in cluster

---

src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs

Azure storage exception are being swallowed, and should be passed up the call stack.

update blob storage provider to throw on storage exceptions

---

src/OrleansRuntime/Catalog/GrainCreator.cs
src/OrleansRuntime/Startup/StartupBuilder.cs
test/TestGrainInterfaces/ISimpleDIGrain.cs
test/TestGrains/SimpleDIGrain.cs
test/Tester/DependencyInjectionGrainTests.cs

This is similar to MVC, where the framework is in charge of determining which concrete controller to resolve, and the user is not required to explicitly register the controller, only the dependencies used by the controller.
Grains in Orleans behave in a very similar way where as you can't explicitly register the mapping grain interface -> grain implementation in the container, and instead Orleans determines which concrete Grain implementation to instantiate. The user should not be responsible for registering all the grain implementations that were also already discovered by Orleans. This is boilerplate and non-intuitive (as you were forced to register the concrete type, not the mapping with the interface, which is not common when using DI and especially when you are implementing an …

Do not require explicitly registering grains in ServiceCollection

---

src/Orleans/CodeGeneration/ConsiderForCodeGenerationAttribute.cs
src/Orleans/CodeGeneration/KnownAssemblyAttribute.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs

This introduces the following changes, as discussed with @sergeybykov, @jdom, and @galvesribeiro.
* `[KnownType]` generates serializers for that type as if the type had `[Serializable]`
* `[GenerateSerializer]` is the same as `[KnownType]`, except that it throws if serializers wont be generated
* `[KnownAssembly]` has a property, `TreatTypesAsSerializable` to generate serializers for all types, equivalent to specifying `[KnownType]` for all types.

Improve codegen attributes KnownType, GenerateSerializer, KnownAssembly

---

src/Orleans/CodeGeneration/GrainFactoryBase.cs
src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/GrainInterfaceMap.cs
src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs
test/Tester/GenericGrainTests.cs
test/Tester/GenericGrainsInAzureStorageTests.cs
test/TesterInternal/StorageTests/PersistenceGrainTests.cs

After lots of debugging on an issue I have with a generic grain that uses storage, I think that this change fixes the issue. The genericArgument was used inconsistently, and sometimes contained the genericInterface value. Also the grainClass parameter did not include the genericArguments during setup of the state, causing the grainType parameter in the first ReadStateAsync to be incorrect.
I moved the location where the conversion was made from SetupActivationInstance() into catalog.GetOrCreateActivation(), passed genericArguments in some functions and fixed the naming.
I think this fixes several bugs, including #1579.
Please test thoroughly, this "works on my machine" but the change might do things that I don't really understand and this is my first pull request on orleans.

Fix bug with generic state parameter caused by inconsistent use of grainClassName / genericArgument / genericInterface

---

src/Orleans/CodeGeneration/IGrainMethodInvoker.cs
src/Orleans/Core/InterceptedMethodInvoker.cs
src/Orleans/Core/InterceptedMethodInvokerCache.cs
src/Orleans/Orleans.csproj
src/OrleansRuntime/Catalog/ActivationData.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
test/TestGrainInterfaces/IStreamInterceptionGrain.cs
test/TestGrainInterfaces/TestGrainInterfaces.csproj
test/TestGrains/StreamInterceptionGrain.cs
test/TestGrains/TestGrains.csproj
test/Tester/InvocationInterceptTests.cs

This PR addresses #1869, allowing method interception to function correctly when grain extensions (such as streams) are invoked.
Additionally, comments and naming were (hopefully) improved in the relevant code.
The approach is to give `ActivationData.ExtensionInvoker` a new interface, `IGrainExtensionMap`, which can then be queried when creating the `InterceptedMethodInvoker` for that extension. I've marked the crux of the change with a comment in the change list.
cc @gabikliot - I'd like your opinion on my approach here.

Fix #1869. Grain Extensions + method interception should function correctly

---

changelog.md
src/OrleansRuntime/Storage/MemoryStorageGrain.cs
test/Tester/MemoryStorageProviderTests.cs

Since memory storage keeps state in a grain that could be lost during silo crashes, it’s eTag enforcement has been reduced to allows state with etags to be written even if the grain has no knowledge of that state.

Memory Storage eTag enforcement less strict.

---

src/OrleansServiceBus/ErrorCode.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs

Pulling agent logs but ignores adapter receiver initialization errors.  Adapter receiver is expected to retry initialization on failure.  EventHub adapter receiver was not doing this, meaning that if initial EventHub receiver setup failed, adapter would never read data from the partition.

Retry EventHub receiver initialization on failure.

---

src/Orleans/Core/GrainFactory.cs
src/Orleans/Providers/ClientProviderRuntime.cs
src/Orleans/Runtime/GrainReference.cs
test/TesterInternal/ClientAddressableTests.cs

Minor cleanup to reduce some redundant Task usage.

Reduce Task<T>/continuation usage in GrainReference/GrainFactory

---

src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Runtime/GrainInterfaceMap.cs
src/Orleans/Runtime/ITypeManager.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs
src/OrleansRuntime/GrainTypeManager/TypeManager.cs

Trivial change to use the `IGrainTypeResolver` interface over the concrete `GrainInterfaceMap` where applicable.
There are many places where similar cleanups can be made. These changes may help with moving towards a more dependency-injection-friendly model.

Use IGrainTypeResolver instead of GrainInterfaceMap

---

src/Orleans/Logging/ErrorCodes.cs
src/OrleansProviders/Storage/MemoryStorage.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs
src/OrleansTestingHost/OrleansTestingHost.csproj
src/OrleansTestingHost/Properties/AssemblyInfo.cs
src/OrleansTestingHost/TestStorageProviders/FaultInjectionStorageProvider.cs
src/OrleansTestingHost/TestStorageProviders/FaultyMemoryStorage.cs
src/OrleansTestingHost/TestStorageProviders/IStorageFaultGrain.cs
src/OrleansTestingHost/TestStorageProviders/StorageFaultGrain.cs
test/TesterInternal/StreamingTests/PubSubRendezvousGrainTests.cs
test/TesterInternal/TesterInternal.csproj

Storage errors could previously put the grain into a bad state.
Now errors trigger the grain to deactivate and reload clean state in next call.
Added tests.
Note: Tests for adding/removing producers fail because pubsub system implementation does not respect interface.

Harden explicit subscription pubsub system

---

src/Orleans/Runtime/CallbackData.cs
src/Orleans/Runtime/Constants.cs

This is because it is the most common exception people see coming from the client when Orleans is misconfigured.
We can start adding these kind of changes in the future, but this is probably a good first step.
Currently https://aka.ms/orleans-troubleshooting is just pointing to the FAQ page, but we have @malavika1 working on a specific troubleshooting page and she'll have a PR shortly (and we plan to merge it before we release new nugets). Then I'll update aka.ms to redirect to that one.

Include troubleshooting link in SiloUnavailableException

---

test/Tester/CancellationTests/GrainCancellationTokenTests.cs

Until resolve of the https://github.com/dotnet/orleans/issues/1891.

Remove time inline data that was causing tests to fail.

---

src/OrleansProviders/Streams/Common/PooledCache/CachedMessageBlock.cs
src/OrleansProviders/Streams/Common/PooledCache/CachedMessagePool.cs
src/OrleansProviders/Streams/Common/PooledCache/FixedSizeBuffer.cs
src/OrleansProviders/Streams/Common/PooledCache/FixedSizeObjectPool.cs
src/OrleansProviders/Streams/Common/PooledCache/IObjectPool.cs
src/OrleansProviders/Streams/Common/PooledCache/ObjectPool.cs
src/OrleansProviders/Streams/Generator/GeneratorAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
test/Tester/TestStreamProviders/EventHub/StreamPerPartitionEventHubStreamProvider.cs
test/TesterInternal/OrleansRuntime/Streams/CachedMessageBlockTests.cs
test/TesterInternal/OrleansRuntime/Streams/FixedSizeBufferTests.cs
test/TesterInternal/OrleansRuntime/Streams/FixedSizeObjectPoolTests.cs
test/TesterInternal/OrleansRuntime/Streams/ObjectPoolTests.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs

Object pool was not resetting pool in the resource, so resources were only being reused once, then released.  Pooling was not pooling.
Special thanks to @dVakulen for finding this.

Object Pools not pooling fix.

---

src/Orleans/Core/InterceptedMethodInvokerCache.cs
test/TestGrainInterfaces/IMethodInterceptionGrain.cs
test/TestGrains/MethodInterceptionGrain.cs
test/Tester/MethodInterceptionTests.cs

When intercepting a grain method that's not defined directly on the grain interface, but rather on an interface that the grain interface "inherits" from (e.g. `interface IMyGrain : IOtherInterface, IGrainWithIntegerKey { }`), the `MethodInfo` that is supplied to the intercepting method is `null`.
This pull request changes the way methods are discovered via reflection to include all interfaces that are "inherited" (for lack of a better word) by the grain interface.
It also adds this test case to prevent regression.

Fixed null MethodInfo in Interceptors

---

Step-by-step-Tutorials/A-Service-is-a-Collection-of-Communicating-Actors.md
Step-by-step-Tutorials/Concurrency.md
Step-by-step-Tutorials/Declarative-Persistence.md
Step-by-step-Tutorials/Interaction-with-Libraries-and-Services.md
Step-by-step-Tutorials/My-First-Orleans-Application.md
Step-by-step-Tutorials/Running-in-a-Stand-alone-Silo.md

- Removing reference of old Visual Studio version
- Rephrase the Silo configuration and add a warning on NuGet package versions
- Adding missing port in client example
- Modify traces to show GUID and warn that timeout are longer when using a debugger
- Update example in 'Interaction with Libraries and Services'
- Fix typo in 'Declarative Persistence'

Corrections in Step-by-step Tutorials:

---

src/Orleans/Timers/SafeTimerBase.cs

String format in SafeTimer's method was causing memory allocations on each call, replaced with raw strings.

Remove allocations caused by string.Format in GetFullName method

---

src/Orleans/Runtime/GrainReference.cs

Debug context string allocations is one of the major memory traffic creators:
Adding of interning in https://github.com/dotnet/orleans/pull/1084 only partially mitigated the issue. 
Caching of this string will not only reduce memory pressure, but also reduce CPU time spent in this method (according to benchmarking of composing string every time vs getting it from <code>ConcurrentDictionary</code> - the latter shows 3x better performance) 
Profile results after change:
(The newly appeared dictionary initialize allocations on second result is due to first profile snapshot was created on build with https://github.com/dotnet/orleans/pull/1946, and the second one - without)

Remove debug context string allocations

---

Getting-Started-With-Orleans/Observers.md

`CreateObjectReference` uses a `WeakReference` for observers, so users should ensure they hold their own reference to each client object.
Unless I'm missing something.

Add note about WeakReference

---

src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Messaging/IncomingMessageAgent.cs

Due to virtual method calls on value type <code>ActivationState</code> instance is being boxed. 
(numbers per 10k grain method calls)

Remove ActivationState enum boxing

---

Advanced-Concepts/Interceptors.md

Fixed code formatting in the interceptors page. code blocks should have one line and one below blank and the lang code is csharp and not C#
Just writing this here for reference.
Let's see how GitHub handles recursive code blocks.
```
``` csharp
//code
```
```

Fixed code formatting in the interceptors page.

---

Advanced-Concepts/Interceptors.md

Just some more discrepancies between what I'm used to in Gitter/GH comments and what our docs use.

Docs: fix interceptors markdown syntax

---

_includes/menu.html

Currently we have an "Advanced Documentation" section in the side menu. That section has an "Advanced Concepts" link to a page containing more links.
This PR copies those links into the side menu to make them more discoverable.

Docs: move Advanced Concepts links into menu

---

changelog.md

Include comments about the upgrade to WindowsAzure Storage 7.0.0 (#1968) in the changelog, and also listed it as a known issue / constraint of previous versions (#1912).
/cc @benjaminpetit

Azure storage update in changelog

---

src/OrleansVSTools/OrleansVSTools/OrleansVSTools.csproj
src/OrleansVSTools/OrleansVSTools/packages.config
src/OrleansVSTools/OrleansVSTools/source.extension.vsixmanifest
src/OrleansVSTools/VSProjectSiloHost/VSProjectSiloHost.vstemplate
src/OrleansVSTools/VSProjectTemplateGrainImplementation/VSProjectTemplateGrainImplementation.vstemplate
src/OrleansVSTools/VSProjectTemplateGrainImplementationFSharp/ProjectTemplate.fsproj
src/OrleansVSTools/VSProjectTemplateGrainImplementationFSharp/VSProjectTemplateGrainImplementation.vstemplate
src/OrleansVSTools/VSProjectTemplateGrainImplementationVB/ProjectTemplate.vbproj
src/OrleansVSTools/VSProjectTemplateGrainImplementationVB/VSProjectTemplateGrainImplementationVB.vstemplate
src/OrleansVSTools/VSProjectTemplateGrainInterface/VSProjectTemplateGrainInterface.vstemplate
src/OrleansVSTools/VSProjectTemplateGrainInterfaceVB/ProjectTemplate.vbproj
src/OrleansVSTools/VSProjectTemplateGrainInterfaceVB/VSProjectTemplateGrainInterfaceVB.vstemplate

- Update OrleansVSTools to 1.3.0
- Also fix missing dependencies in OrleansVSTools.
They were only working before by piggybacking on Orleans solution packages which will be removed with project.json.

Update OrleansVSTools to 1.3.0

---

src/Orleans/Serialization/TypeUtilities.cs

On each <code>IsOrleansShallowCopyable</code> call closure was allocated because of delegate that captured <code>Type</code> variable.

Eliminate closure allocations

---

src/Orleans/Messaging/BufferPool.cs

Currently used <code>BlockingCollection</code> takes quite a portion of serialization time:
(results from mini benchmark of roundtrip serialization of POCO)
After replacing with <code>ConcurrentBag</code>:
(note, that <code>Release</code> method also disappeared from hot spots list)

Replace buffer pool underlying collection

---

src/OrleansRuntime/Catalog/Catalog.cs
src/OrleansRuntime/GrainTypeManager/GrainTypeManager.cs

On each grain activation dictionary was allocated, presumably for the sake of immutability,
but its only usage is at https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Catalog/Catalog.cs#L634.

Avoid dictionary allocation on creation of grain instance

---

Step-by-step-Tutorials/Running-in-a-Stand-alone-Silo.md

Inserted step of changing interface definition and clarifying that the client is Program.cs
Also made text more explicit about nuget versions. Initially I mistook this to mean make sure that all the orleans packages where the same version within the Grain project even though it does mention the solution.

Clarifying Help

---

src/Orleans/Runtime/SiloStatus.cs
src/Orleans/SystemTargetInterfaces/IMembershipTable.cs
src/OrleansRuntime/ConsistentRing/ConsistentRingProvider.cs
src/OrleansRuntime/ConsistentRing/VirtualBucketsRingProvider.cs
src/OrleansRuntime/Core/ManagementGrain.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs
src/OrleansRuntime/MembershipService/MembershipOracle.cs
src/OrleansRuntime/MembershipService/MembershipOracleData.cs
src/OrleansRuntime/Placement/DeploymentLoadPublisher.cs
src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs
src/OrleansRuntime/Streams/QueueBalancer/DeploymentBasedQueueBalancer.cs
test/Tester/MembershipTests/LivenessTests.cs

Using of the <code>Equals</code> on enum causes boxing:
Removed all instances of it's usages on <code>SiloStatus</code> enum.

Avoid SiloStatus enum boxing

---

src/Orleans/Serialization/BinaryTokenStreamReader.cs

BinaryTokenStreamReader's <code>CheckLength</code> method takes ~21% of deserialization time (tested on simple POCO) due to excessive usage of <code>ArraySegment</code>'s properties: <code>Offset</code>, <code>Array</code> and <code>Count</code>.
During rewrite was removed repeatable accessing of the properties and unnecessary construction of the <code>ArraySegment</code> on each call. 
Results after:

Optimize CheckLength method

---

src/Orleans/Telemetry/Consumers/FileTelemetryConsumer.cs

This is for CoreCLR compatibility.
Similar to #609 but in the new TelemetryConsumers API

Change TextWriter.Close to Dispose

---

src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs

Initialized PubSubGrainState fields at construction time to prevent null reference exceptions after clearing grain state.

Fix null reference in StreamPubSub grain.

---

src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs

Service Provider is no longer required by EventHubAdapter

---

src/Orleans.sln
src/OrleansPSUtils/GetGrain.cs
src/OrleansPSUtils/Orleans.psd1
src/OrleansPSUtils/OrleansPSUtils.csproj
src/OrleansPSUtils/Properties/AssemblyInfo.cs
src/OrleansPSUtils/StartGrainClient.cs
src/OrleansPSUtils/StopGrainClient.cs
src/OrleansPSUtils/project.json
test/Tester/PSClientTests/PSClientTests.cs
test/Tester/PSClientTests/PSClientTests.ps1
test/Tester/Tester.csproj
test/Tester/project.json

This initial implementation is part of a series of improvements on tooling.
Many people were asking on Gitter for a way to interact with grains from a console.
This initial push enables user to start and stop `GrainClient` and call any grain from Powershell.
Currently GrainObservers, Streams, interceptors are not implemented. This first step allow only direct calls to grain methods as in any other client that uses `GrainClient` does.
A page will be added to docs site on a separated PR explaining how to use it and more work will come to support other client scenarios.

PowerShell Client Module

---

src/NuGet/Microsoft.Orleans.OrleansAWSUtils.nuspec
src/Orleans.sln
src/Orleans/Properties/AssemblyInfo.cs
src/OrleansAWSUtils/AWSUtils.cs
src/OrleansAWSUtils/OrleansAWSUtils.csproj
src/OrleansAWSUtils/Properties/AssemblyInfo.cs
src/OrleansAWSUtils/Storage/DynamoDBStorage.cs
src/OrleansAWSUtils/Storage/Provider/DynamoDBStorageProvider.cs
src/OrleansAWSUtils/project.json
test/TestGrainInterfaces/IPersistenceTestGrains.cs
test/TestInternalGrains/PersistenceTestGrains.cs
test/TesterInternal/Config_AWS_DynamoDB_Storage.xml
test/TesterInternal/StorageTests/AWSUtils/AWSTestConstants.cs
test/TesterInternal/StorageTests/AWSUtils/Base_PersistenceGrainTests_AWSStore.cs
test/TesterInternal/StorageTests/AWSUtils/DynamoDBStorageProviderTests.cs
test/TesterInternal/StorageTests/AWSUtils/DynamoDBStorageStressTests.cs
test/TesterInternal/StorageTests/AWSUtils/DynamoDBStorageTestFixture.cs
test/TesterInternal/StorageTests/AWSUtils/DynamoDBStorageTests.cs
test/TesterInternal/StorageTests/AWSUtils/PersistenceGrainTests_AWSDynamoDBStore.cs
test/TesterInternal/StorageTests/AWSUtils/UnitTestDynamoDBStorage.cs
test/TesterInternal/TesterInternal.csproj
test/TesterInternal/project.json

Implementation of #2006 which is part of #2005

AWS DynamoDB Grain State Provider

---

src/OrleansPSUtils/OrleansPSUtils.csproj

Following #1990
Build using `Build.cmd` and VS will build as expected the project in a dedicated subfolder, but not in VSO (it will share the same output folder as the other projects)

Temp fix to make VSO build works

---

src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Persistent stream provider can timeout during initialization if many queues are configured.  To address this, we don't await receiver initialization any more.  Receiver initialization was always allowed to fail, in which case re-initialization was necessary.  Now we no longer await it since we don't handle the exception anyway.

Persistent Stream Provider initialization timeout fix.

---

src/Orleans/Logging/ErrorCodes.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Persistent stream pulling agent now uses exponential backoff when encountering errors when reading from queues.
This prevents agents from spamming backend queue services that are encountering transient errors.
If no data is read, usual retry timer is applied.  Exponential backoff is only triggered when errors occur.

Persistent stream pulling agent now uses exponential backoff

---

src/.nuget/packages.config
src/Orleans.sln

Looks like VSO builds do not find the xUnit VS test adapter if it's using a nuget v3 reference (as it searches for adapter inside the packages folder, which is no longer used with project.json).

Include test adapter as a packages.config reference

---

src/NuGet/Microsoft.Orleans.Core.nuspec
src/Orleans/Serialization/BuiltInTypes.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/project.json
test/Tester/SerializationTests/DeepCopyTests.cs
test/Tester/SerializationTests/SerializationTests.ImmutableCollections.cs
test/Tester/Tester.csproj

I have added support for Immutable Collections, it assumes that the content of the collection is immutable as well. I think that fits in with the Immutable<> wrapper semantics. I provided hand coded serialization and deserialization as well to avoid the default binary serializer.
I have also removed the hardcoded strings from the BuiltInTypes class and replaced them with build time checking via the "nameof" command.

#2056 #1464 Adding Immutable Collections and BuiltInTypes Cleanup

---

src/OrleansAWSUtils/OrleansAWSUtils.csproj
src/OrleansAWSUtils/Reminders/DynamoDBReminderTable.cs
src/OrleansAWSUtils/Storage/DynamoDBStorage.cs
test/TesterInternal/RemindersTest/DynamoDBRemindersTableTests.cs
test/TesterInternal/TesterInternal.csproj

Implementation of #2006 which is part of #2005

AWS DynamoDB Reminders

---

src/NuGet/Microsoft.Orleans.OrleansAWSUtils.nuspec
src/OrleansAWSUtils/OrleansAWSUtils.csproj
src/OrleansAWSUtils/Storage/SQSStorage.cs
src/OrleansAWSUtils/Streams/SQSAdapter.cs
src/OrleansAWSUtils/Streams/SQSAdapterFactory.cs
src/OrleansAWSUtils/Streams/SQSAdapterReceiver.cs
src/OrleansAWSUtils/Streams/SQSBatchContainer.cs
src/OrleansAWSUtils/Streams/SQSStreamProvider.cs
src/OrleansAWSUtils/Streams/SQSStreamProviderUtils.cs
src/OrleansAWSUtils/project.json
test/Tester/StreamingTests/SQSClientStreamTests.cs
test/Tester/StreamingTests/SQSSubscriptionMultiplicityTests.cs
test/Tester/Tester.csproj
test/TesterInternal/ClientConfig_SQSStreamProviders.xml
test/TesterInternal/Config_SQSStreamProviders.xml
test/TesterInternal/StorageTests/AWSUtils/AWSTestConstants.cs
test/TesterInternal/StreamingTests/SQSAdapterTests.cs
test/TesterInternal/StreamingTests/SQSStreamTests.cs
test/TesterInternal/TesterInternal.csproj

Implementation of #2006 which is part of #2005

AWS SQS Stream Provider

---

src/Orleans/Providers/ProviderLoader.cs
test/TesterInternal/Deployment/AzureSiloTests.cs
test/TesterInternal/StreamingTests/DynamicStreamProviderConfigurationTests.cs

Main issue was with some `async void` methods, especially in DynamicStreamProviderConfigurationTests.cs, which was actually exiting the entire test runner process abnormally on ocassions

Fix non-deterministic functional tests

---

src/NuGet/Microsoft.Orleans.OrleansServiceBus.nuspec
src/OrleansAzureUtils/Storage/AzureTableDataManager.cs
src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventDataExtensions.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubBatchContainer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
src/OrleansServiceBus/project.json
test/Tester/StreamingTests/EHImplicitSubscriptionStreamRecoveryTests.cs
test/Tester/project.json
test/TesterInternal/StorageTests/AzureTableDataManagerStressTests.cs

- Upgrade to SERVICEBUS 3.3.2
- New EventData keeps eventdata properties and user properties in different bags, which caused PartitionKey property to be lost when data passed through cache. - fixed
- Azure storage read table call was failing, but was never noticed because there was no testing.  Added testing and fixed storage layer.
- Azure clear table call expected single partition.  Didn't work if there were multiple partitions in the table. -fixed.
- EventHub reciever, when reading from 'now', was reading from the last data in the queue, rather than all future data.  -fixed
- EventHub recovery test was intermittently failing because it was using two silos, but poor fault injection requires that grains stay on same silo.  -fixed.

Upgrade to ServiceBus 3.3.2 and related changes.

---

src/.nuget/packages.config
src/OrleansGoogleUtils/project.json
test/Tester/SerializationTests/ProtobufSerializationTests/Addressbook.cs
test/Tester/SerializationTests/ProtobufSerializationTests/Counter.cs
test/Tester/SerializationTests/ProtobufSerializationTests/GenerateProtos.cmd
test/Tester/project.json

This PR updates the Google.Protobuf dependency to a non-prerelease version.
There is a problem with this PR, though. The "GenerateProtos.cmd" script has a hard coded dependency on the "protoc.exe" utility. In the prerelease versions, "protoc.exe" was included in the Google.Protobuf package. It appears They have split the utility into its own package, Google.Protobuf.Tools.
I am still learning about the changes that project.json brings to projects. In particular, it appears that adding Google.Protobuf.Tools as a dependency won't work as it had previously. The "protoc.exe" utility doesn't appear to be extracted into a packages folder within the solution. It's not clear to me how a tool can be called from a script with this new package structure. Any suggestions are welcome, and I am happy …

Updated Google.Protobuf dependency

---

src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/Configuration/ClientConfiguration.cs
src/Orleans/Configuration/ConfigUtilities.cs
src/Orleans/Logging/LogManager.cs
src/Orleans/Messaging/Message.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Messaging/SocketManager.cs
src/Orleans/Providers/ProviderLoader.cs
src/Orleans/Runtime/AsynchAgent.cs
src/Orleans/Serialization/BinaryFormatterSerializer.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Statistics/RuntimeStatisticsGroup.cs
src/Orleans/Utils/Utils.cs
src/OrleansCodeGenerator/SerializerGenerator.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Messaging/OutboundMessageQueue.cs
src/OrleansRuntime/Scheduler/WorkItemGroup.cs

Conditional compilation for some very minor differences between full .NET 4.5.1 and .NET Standard.
Some of these might no longer be needed when we upgrade to 4.6.*
Each fix is separated into its own commit so it's easier to review (and also track once it's merged, so please do not squash them)

Minor .NET Standard compatibility fixes

---

src/OrleansAWSUtils/project.json
src/OrleansAzureUtils/project.json
src/OrleansBondUtils/project.json
src/OrleansConsulUtils/project.json
src/OrleansPSUtils/project.json
src/OrleansSQLUtils/project.json
src/OrleansServiceBus/project.json
src/OrleansTestingHost/project.json
src/OrleansZooKeeperUtils/project.json
test/TestGrainInterfaces/project.json
test/TestGrains/project.json
test/TestInternalGrains/project.json
test/Tester/project.json
test/TesterInternal/project.json

Cleaned up the nuget dependencies from the project.json files where the dependent project does not care which nuget package version dependency to use, it just cares to transitively get the dependency.
for instance, no project really cares which version of NewtsonSoft.Json is set up, as long as they reference the same one as Orleans.dll
In the case of Tester and TesterInternal, they do not care about which version of almost all packages they use, as long as they match the same ones that the projects under test are using.
This is in preparation of the CoreCLR work, to avoid merge conflicts all over the place when we change a dependency here or there.

Remove Nuget transitive dependencies on dependent projects

---

src/OrleansProviders/Streams/Common/PooledCache/ICacheDataAdapter.cs
src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
src/OrleansProviders/Streams/Generator/GeneratorPooledCache.cs
src/OrleansProviders/Streams/Memory/MemoryPooledCache.cs
src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueCache.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubStreamProviderConfig.cs
src/OrleansServiceBus/Providers/Streams/EventHub/TimePurgePredicate.cs
test/Tester/StreamingTests/EHClientStreamTests.cs
test/Tester/StreamingTests/EHStreamProviderCheckpointTests.cs
test/Tester/StreamingTests/TimePurgePredicateTests.cs
test/Tester/TestStreamProviders/EventHub/StreamPerPartitionEventHubStreamProvider.cs
test/Tester/Tester.csproj
test/TesterInternal/OrleansRuntime/Streams/CachedMessageBlockTests.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs

Added time based message purge to EventHub stream provider message cache.
In addition to purging messages by cache size, a message are now purged if it is a configured period of time older than the newest data in the cache, and has been in the cache a minimum configured amount of time.

EventHub stream provider time based message purge

---

src/Tutorials/Concurrency.md

In this page - http://dotnet.github.io/orleans/Tutorials/Concurrency.html, the hyperlink to [Grains] in the 1st line is not correct.

Corrected Hyperlink in Concurrency.md

---

src/Orleans/IDs/GrainId.cs

Code contracts is an additional dependency when targeting .NET Standard that we should not pull into just for this random occurrence.
There are no other usages of code contracts in the solution

Remove Pure attribute usage

---

src/OrleansTestingHost/TestClusterOptions.cs

this caused the MySQL liveness tests to fail.

Copy AdoInvariant in BuildClientConfiguration

---

src/Orleans/Messaging/Message.cs
src/Orleans/Messaging/ProxiedMessageCenter.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Serialization/BinaryTokenStreamReader.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Statistics/MessagingStatisticsGroup.cs
src/OrleansRuntime/Core/Dispatcher.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
src/OrleansRuntime/Messaging/GatewayAcceptor.cs
src/OrleansRuntime/Messaging/OutboundMessageQueue.cs
src/OrleansRuntime/Messaging/SiloMessageSender.cs
test/TesterInternal/SerializerTests/MessageSerializerTests.cs

Instantiation of the two dictionaries per message is by far the top contributor to the memory pressure in many workloads: 
Plus as it one of the hottest code path in Orleans - usage of the dictionary consumes some chunk of CPU: 
After removal: memory footprint reduced by 4x, serialization time improved by ~10%, average serialized size reduced by ~11% (which can be 11% of whole serialized message in case of message with small payload). 
Adding of the new header will require bigger effort from now, but I think that it's justified.

Remove message headers & metadata dictionaries 

---

src/Orleans/Async/BatchWorker.cs

A rare race on the currentWorkCycle field can cause NullPointerException.
The reason is that the delegate does not properly capture the current value of currentWorkCycle under the lock, but the delegate executes after the lock is released, at which point the value of currentWorkCycle may have changed already. 
The fix is to manually capture the current value. This is more efficient anyway. Not sure why I ever used a delegate in the first place.

Fix synchronization bug in Orleans/Async/BatchWorker 

---

src/Orleans/Serialization/BinaryTokenStreamReader.cs
src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Serialization/SerializationTokenType.cs
test/TesterInternal/Serialization/BuiltInSerializerTests.cs

Currently we have optimizations for serializing certain types, including various array types.
Serialization is broken for `SByte[]`  because it is serialized without optimization, but erroneously deserialized with an optimization for `byte[]`. Since the optimized serialization occupies half the space, this results in incorrect deserialization.
This PR fixes that and expands test coverage to include this case.

Fix support for serializing SByte[]

---

src/Orleans/Serialization/SerializationContext.cs
src/OrleansCodeGenerator/SerializerGenerator.cs
test/TestGrainInterfaces/ICircularStateTestGrain.cs
test/TesterInternal/Serialization/BuiltInSerializerTests.cs

Currently generated `DeepCopy` method incorrectly calls `RecordObject` after copying fields instead of before. This results in circular references involving being incorrectly serialized, resulting in a loss of referential equality.
The fix is to simply emit the call to `RecordObject` before the field-copying calls.
This was not failing in our test suite (`Serialize_CircularReference`) because the assembly holding the recursively defined type has the `[SkipCodeGeneration]` attribute, so a serializer was not being generated and so the fallback serializer was being used.

CodeGen: fix generated DeepCopy method to call RecordObject earlier

---

src/OrleansServiceBus/OrleansServiceBus.csproj
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubCheckpointer.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubPartitionCheckpointEntity.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubQueueMapper.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubSequenceToken.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubSettings.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventHubStreamProviderSettings.cs
src/OrleansServiceBus/Providers/Streams/EventHub/ICheckpointerSettings.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubQueueMapper.cs
src/OrleansServiceBus/Providers/Streams/EventHub/IEventHubSettings.cs
src/OrleansServiceBus/Providers/Streams/EventHub/SegmentBuilder.cs
test/Tester/StreamingTests/EHClientStreamTests.cs
test/Tester/StreamingTests/EHImplicitSubscriptionStreamRecoveryTests.cs
test/Tester/StreamingTests/EHStreamPerPartitionTests.cs
test/Tester/StreamingTests/EHStreamProviderCheckpointTests.cs
test/Tester/StreamingTests/EHSubscriptionMultiplicityTests.cs
test/Tester/TestStreamProviders/EventHub/StreamPerPartitionEventHubStreamProvider.cs

Inconsistently named things "Settings" or "Config".  Now we consistently use "Settings"
Inconsistently used nameof vs. hard coded names in parameter validation.  Now we always use nameof.
Added more xml comments along the way.

Orleans ServiceBus naming consistency.

---

src/Orleans/Serialization/BinaryTokenStreamReader.cs

Continuation of the https://github.com/dotnet/orleans/pull/2001. 
On running of the serialization benchmark with  [IL based serializer](https://github.com/dotnet/orleans/tree/feature-il-serializer) the CheckLength method again appears at the top of the list:
Optimized for most common case of reading of the simple type from ArraySegment of 4 kilobytes size.
Benchmark shows 12% deserialization perfomance improvement.

Optimize deserialization

---

src/Orleans.sln

This is so it builds before TesterInternal, and the post build script executes with that assembly already created.
It was breaking our VSO builds

Add build dependency to ServiceFabric utilities project

---

src/OrleansAzureUtils/Hosting/AzureSilo.cs

Yes, it is a breaking change.
But currently if you do something like this:
````
var config = AzureSilo.DefaultConfiguration();
config.Globals.DeploymentId = "aca7e5e9105745a0b82be8c5a6b07215";
config.AddAzureTableStorageProvider("AzureStore");
orleansAzureSilo = new AzureSilo();
bool ok = orleansAzureSilo.Start(config);
````
The Start method will partially ignore the DeploymentId that is in the configuration which is confusing.

Remove confusing parameter from AzureSilo.Start

---

src/Orleans/Runtime/AsynchAgent.cs
src/Orleans/Statistics/ClientTableStatistics.cs

(and not supported in .NET Standard)

Remove MarshalByRefObject where it is not needed

---

src/Orleans/CodeGeneration/CodeGeneratorManager.cs
src/Orleans/CodeGeneration/GeneratedAssembly.cs
src/Orleans/CodeGeneration/ICodeGeneratorCache.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/RuntimeVersion.cs
src/OrleansCodeGenerator/CodeGeneratorCommon.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
src/OrleansRuntime/Silo/Silo.cs
src/OrleansTestingHost/TestCluster.cs
src/OrleansTestingHost/TestingSiloHost.cs

When using runtime code generation, currently assemblies are compiled and loaded without debug symbols.
In order to slightly improve the debugging situation, this PR causes the runtime code generator to emit debug symbols and load them alongside generated assemblies.
**Approach:** The crux of this change simply instructs Roslyn to emit debug symbols (see `compilation.Emit` calls in `CodeGeneratorCommon`) and then passes those debug symbols to `Assembly.Load`.
In order to make this work during test runs, where we are caching generated assemblies to improve performance, we need to alter `ICodeGeneratorCache` to work with symbols as well as just raw assemblies. To achieve this we change uses of `byte[]` to `GeneratedAssembly`, which holds assembly + symbols.

CodeGen: Emit & load debug symbols if built in Debug mode.

---

src/Orleans/Core/Exceptions.cs
src/Orleans/Providers/IOrleansProvider.cs
src/Orleans/Providers/IStorageProvider.cs
src/Orleans/Providers/ProviderStateManager.cs
src/Orleans/Streams/PersistentStreams/StreamEventDeliveryFailureException.cs
src/Orleans/Streams/Providers/IStreamProviderImpl.cs
src/Orleans/Streams/PubSub/FaultedSubscriptionException.cs
src/Orleans/Streams/QueueAdapters/DataNotAvailableException.cs
src/Orleans/Streams/QueueAdapters/QueueCacheMissException.cs
src/Orleans/Timers/IRemindable.cs
src/OrleansRuntime/Catalog/Catalog.cs

Support is in preview via the System.Runtime.Serialization.Formatters package, but system types such as exceptions do not implement ISerializable nor have the constructors for serialization.

Use the ISerializable subset available in .NET Standard

---

src/Orleans/Configuration/ConfigUtilities.cs
src/OrleansRuntime/Silo/Silo.cs

There was duplicate info being logged already, and it was also spread out in multiple files. This way it's in a single location that can be fixed in 1 go for .NET Standard

Centralize platform info logging

---

src/Orleans/Configuration/NodeConfiguration.cs

This was dead code and also causing issues in .NET Standard, since `Environment.SpecialFolder.LocalApplicationData` is not available

Remove WorkingStorageDirectory property

---

src/Orleans/AssemblyLoader/AssemblyLoaderReflectionCriterion.cs
src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/Providers/ProviderTypeLoader.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs

There are several places where we enumerate all types in an assembly.
When a type cannot be initialized for some reason, a `ReflectionTypeLoadException` is thrown. Types can fail to initialize for a variety of reasons including failure to load referenced types or static constructor exceptions.
Currently we bail out at that point and do not process any types for that assembly.
`ReflectionTypeLoadException` has a `Types` property which contains an array of the types which were successfully loaded.
This change salvages those types which were successfully loaded.

Recover types from ReflectionTypeLoadException

---

src/Orleans/AssemblyLoader/AssemblyProcessor.cs
src/Orleans/Configuration/MessagingConfiguration.cs
src/Orleans/Configuration/OrleansConfiguration.xsd
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansRuntime/Silo/Silo.cs
test/TesterInternal/OrleansRuntime/ExceptionsTests.cs
test/TesterInternal/Serialization/BuiltInSerializerTests.cs

Removes `UseStandardSerializer` option, which is designed to allow users to use BinaryFormatter instead of Orleans' serializer. BinaryFormatter is not available on .NET Core and users can use BinaryFormatter by providing an `IExternalSerializer` implementation.
Once this is merged, I'll propose a similar PR to remove the JSON fallback serialization option.

Remove UseStandardSerializer option

---

src/OrleansRuntime/Silo/Silo.cs
src/OrleansRuntime/Startup/StartupBuilder.cs
test/TestGrainInterfaces/ISimpleDIGrain.cs
test/TestGrains/SimpleDIGrain.cs
test/Tester/DependencyInjectionGrainTests.cs

Make IGrainFactory injectable. 
In the future we want to make more internal system types injectable through DI container, for application layer to use and for making orleans' DI better. This is the first step.

Make IGrainFactory injectable

---

src/index.md

Updating home page example to match closer to the one in the github readme

removing async from documentation example

---

src/Orleans/Configuration/MessagingConfiguration.cs
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansRuntime/Silo/Silo.cs
test/Tester/SerializationTests/SerializationTests.JsonTypes.cs
test/TesterInternal/OrleansRuntime/ExceptionsTests.cs
test/TesterInternal/Serialization/BuiltInSerializerTests.cs

Follow-on from #2193.
Json.NET is not a suitable fallback serializer. It does not handle the complex types which it needs to handle.

Remove UseJsonFallbackSerializer

---

src/Orleans/Streams/PersistentStreams/PersistentStreamProvider.cs
src/OrleansProviders/Streams/Memory/MemoryAdapterFactory.cs

Was causing some EventHub tests to fail because providerRuntime.ServiceProvider was null, and not the providerRuntime itself (which was the path being tested for null). I believe this would have meant that if someone uses the EventHubStreamProvider from the client, they would have hit this bug.
Also replaced `MemoryAdapterFactory` to depend on `IGrainFactory` instead of the `GrainFactory` concrete class and updated hack accordingly. And since IGrainFactory is now currently being injected in the silo side, rely on that first and only fall back if it is not set.

Fix bug in GrainFactoryServiceProvider

---

src/Orleans/Serialization/SerializationManager.cs

It broke due to a PR for the main solution. We are currently working on having CI build this .NET Standard solution, so that these issues are less frequent in the future, because they are very easy to miss.

Fix SerializationManager.GetFallbackSerializer() in .NET Standard

---

src/Orleans/project.json
src/OrleansCodeGenerator/project.json
src/OrleansPSUtils/project.json
test/Benchmarks/OrleansBenchmarks/App.config

Updated Microsoft.CodeAnalysis.*, System.Collections.Immutable, and System.Reflection.Metadata NuGets
System.Collections.Immutable 1.1.36 -> 1.1.37
System.Reflection.Metadata 1.0.21 -> 1.2.0
Microsoft.CodeAnalysis.CSharp 1.0.0 -> 1.3.2
Microsoft.CodeAnalysis.Analyzers 1.0.0 -> 1.1.0
Microsoft.CodeAnalysis.Common 1.0.0 -> 1.3.2
This eliminates build warnings about crashing unneeded C# analyzer and updates the codegen related dependencies. IMO these dependencies are fine to upgrade even if we technically don't have to, because they are Roslyn related and can be treated somewhat differently from normal dependencies used by application code, such as Newtonsoft.Json and Azure Storage.
Added a binding redirect for Newtonsoft.Json to OrleansBenchmarks to eliminate a build warning.

Update codegen related dependency NuGets

---

src/Orleans/Serialization/OrleansJsonSerializer.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansAWSUtils/Storage/Provider/DynamoDBStorageProvider.cs
src/OrleansAzureUtils/Providers/AzureConfigurationExtensions.cs
src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs
src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs
src/OrleansSQLUtils/Storage/Provider/AdoNetStorageProvider.cs

This is a (minorly) breaking change which moves `GetDefaultJsonSerializerSettings` & `UpdateSerializerSettings` out of `SerializationManager` and into `OrleansJsonSerializer`.
It also makes `OrleansJsonSerializer` public so that external providers can reference it.

Move JSON serialization methods into OrleansJsonSerializer

---

test/Tester/CancellationTests/GrainCancellationTokenTests.cs

Remove CancellationTokenCallbacksThrow_ExceptionShouldBePropagated test from BVT/Functional sets, as it's failing intermittently on a regular basis.
/cc @dVakulen.

Remove CancellationTokenCallbacksThrow_ExceptionShouldBePropagated test from BVT/Functional sets

---

src/OrleansCodeGenerator/GrainMethodInvokerGenerator.cs
test/TestGrainInterfaces/IExceptionGrain.cs
test/TestGrains/ExceptionGrain.cs
test/Tester/ExceptionPropagationTests.cs

When code generation was originally ported from CodeDOM to Roslyn, the initial goal was to keep the emitted code close to the previous generator's.
Currently, generated `IGrainMethodInvoker.Invoke` methods have a try/catch wrapping the body.
This try/catch is needless and this PR removes it.
Example old body:
```C#
global::System.Int32 interfaceId = @request.@InterfaceId;
global::System.Int32 methodId = @request.@MethodId;
global::System.Object[] arguments = @request.@Arguments;
try
{
if (@grain == null)
throw new global::System.ArgumentNullException("grain");
switch (interfaceId)
{
case -831689659:
switch (methodId)
{
case -1573596583:
return ((global::Orleans.IRemindable)@grain).@ReceiveReminder((global::System.String)arguments[0], …
```

CodeGen: Avoid wrapping IGrainMethodInvoker.Invoke body in try/catch

---

vNext/src/Orleans/Shims/AppDomain.cs
vNext/test/NonSiloTests/Orleans.NonSiloTests.csproj
vNext/test/NonSiloTests/project.json

Port part of serialization tests to vNext. 
remaining serialization tests cannot be ported over because missing of TestGrainInterface project. @jdom teach me how to create the correct csproj for vNext? 
and also, do we want a non-silo-test-internal, regards of the accessibility to test internal types? More clean this way.

port Serialization test to vNext

---

vNext/src/Orleans.vNext.sln
vNext/test/NonSiloTests/Orleans.NonSiloTests.csproj
vNext/test/TestGrainInterfaces/TestGrainInterfaces.csproj
vNext/test/TestGrainInterfaces/project.json

Kept separate commits to show exactly how I am migrating 1 project at a time from the main solution (at request by @xiazen). Can be squashed into 1 commit

Add TestGrainInterfaces project to .NET Standard solution

---

src/Orleans/Core/GrainCasterFactory.cs
src/Orleans/Core/GrainExtensions.cs
src/Orleans/Core/GrainFactory.cs
src/Orleans/Orleans.csproj
src/Orleans/Runtime/GrainReference.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansRuntime/Core/InsideRuntimeClient.cs
test/TesterInternal/GrainReferenceCastTests.cs

Three commits with the same purpose: replacing usage of [LINQ Expression Tree](https://msdn.microsoft.com/en-us/library/mt654263.aspx) compilation with IL, since [this blog post about .NET Standard](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) indicates that Expression.Compile will be interpreted (rather than compiled to IL) in upcoming versions of the platform:
> In some cases we’ll emulate their behavior (e.g. interpreting expression trees instead of compiling them) while in other cases we’ll throw (e.g. when compiling regexes).
The mixed use of LINQ Expressions & IL has also been bugging me for a while.
As a part of this work, this change removes `GrainFactory.CastInternal` and instead calls `GrainExtensions.AsReference<T>` as needed. I removed that …

Replace Expression Trees with IL

---

src/OrleansRuntime/Scheduler/OrleansTaskScheduler.cs
src/OrleansRuntime/Scheduler/WorkerPool.cs
src/OrleansRuntime/Scheduler/WorkerPoolThread.cs

It would be interesting to know if this saves any perf.
We maintain this semaphore and counter only for the case that we inject more threads dynamically. We don't actually do that any more, for years (its a separate discussion why). Did not want to fully remove the thread injection, but sure no need to pay the semaphore and interlocked exchange price, on a very hot path.
It is one of those things that is hard to predict how perf. will be impacted. I won't be surprised if it does not help at all (semaphore was never blocking, it always had enough room), or saves a ton (since it still inc/dec the semaphore on every task)!

Optimize the scheduler, remove redundant semaphore and interlocked exchange.

---

src/Orleans/CodeGeneration/TypeUtils.cs
src/Orleans/Configuration/MessagingConfiguration.cs
src/Orleans/Configuration/OrleansConfiguration.xsd
src/Orleans/Orleans.csproj
src/Orleans/Runtime/OutsideRuntimeClient.cs
src/Orleans/Serialization/ILBasedFallbackSerializer.cs
src/Orleans/Serialization/IlBasedSerializerGenerator.cs
src/Orleans/Serialization/IlBasedSerializerTypeChecker.cs
src/Orleans/Serialization/IlBasedSerializers.cs
src/Orleans/Serialization/IlCodeGenerationException.cs
src/Orleans/Serialization/IlDelegateBuilder.cs
src/Orleans/Serialization/ReflectedSerializationMethodInfo.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansRuntime/Silo/Silo.cs
test/TestGrainInterfaces/CodegenTestInterfaces.cs
test/Tester/CodeGenTests/GeneratorGrainTest.cs
test/TesterInternal/Serialization/BuiltInSerializerTests.cs
test/TesterInternal/Serialization/IlBasedSerializerTests.cs
test/TesterInternal/StorageTests/PersistenceGrainTests.cs
test/TesterInternal/TesterInternal.csproj
vNext/src/Orleans/Orleans.csproj

This is an implementation of a *fallback* serializer which is intended to replace `BinaryFormatter` as a part of the .NET Core initiative.
This serializer is very similar to the current Roslyn-based serializers except that instead of emitting C# code, it emits IL directly at runtime, allowing it to access private members and types.
The bulk of the logic is in `IlBasedSerializerGenerator`, which I hope is easy enough to follow.
IL generation is abstracted via a simple facade called `IlDelegateBuilder<TDelegate>` which is based on on .NET's `ILGenerator`.
The usage of the class is as follows:
1. Instantiate the builder with the type of delegate being built (eg, `DeepCopier`).
2. Call methods on the builder to add instructions to it.
3. Call `Build()` to create the final delegate.
Please let …

IL-based fallback serializer

---

src/Orleans/Configuration/NodeConfiguration.cs
src/OrleansRuntime/Scheduler/OrleansTaskScheduler.cs
src/OrleansRuntime/Scheduler/WorkerPool.cs

This is a minor follow-up for #2218.
Renamed InjectMoreWorkerThreads to EnableWorkerThreadInjection in config for better clarity.

Renamed InjectMoreWorkerThreads to EnableWorkerThreadInjection

---

src/OrleansGoogleUtils/ProtobufSerializer.cs
test/Tester/SerializationTests/ProtobufSerializationTests/ProtobufSerializationTests.cs

The Protobuf serializer currently returns null for a zero-length message. This causes a message with all default values to deserialize as null rather than a default message since Protobuf doesn't serialize
default values. As far as I can tell, there's no case where you would want null here... the tests all pass without the length check.
Removed the length check and added a unit test to demonstrate the issue (my new test fails without the change). Also fixed spelling on the other unit tests. :)

Remove zero length check in Protobuf serializer

---

src/Orleans/CodeGeneration/ActivationAttribute.cs
src/Orleans/Core/GrainFactory.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansCodeGenerator/GrainMethodInvokerGenerator.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs
test/TesterInternal/General/InternalSerializationTests.cs

Currently code generation attributes such as `[MethodInvoker]` and `[GrainReference]` can be instantiated using either the name of the `IGrain` type which they were generated for, or the `Type` itself.
This removes the string property, which is unnecessary.
Before:
```c#
[MethodInvoker("global::Orleans.IMembershipTableGrain", -1256503757, typeof (global::Orleans.IMembershipTableGrain))]
```
After:
```C#
[MethodInvoker(typeof(IMembershipTableGrain), -1256503757)]
```
Renames `GrainType` to `TargetType`, since the property is used for both generated serializers and grain interfaces.
Removes the unnecessary code analysis suppression, since [CA1813:AvoidUnsealedAttributes](https://msdn.microsoft.com/en-us/library/ms182267.aspx) does not apply to abstract classes.
Edit: this simplifies the …

Simplify code generation attributes to always use Type

---

test/TesterInternal/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs

The non-determinism was in the test itself, not the scheduler

Avoid race condition in scheduler test

---

src/Chocolatey/orleans.nuspec
src/NuGet/Microsoft.Orleans.Client.nuspec
src/NuGet/Microsoft.Orleans.Core.nuspec
src/NuGet/Microsoft.Orleans.CounterControl.nuspec
src/NuGet/Microsoft.Orleans.EventSourcing.nuspec
src/NuGet/Microsoft.Orleans.OrleansAWSUtils.nuspec
src/NuGet/Microsoft.Orleans.OrleansAzureUtils.nuspec
src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.Build.nuspec
src/NuGet/Microsoft.Orleans.OrleansCodeGenerator.nuspec
src/NuGet/Microsoft.Orleans.OrleansHost.nuspec
src/NuGet/Microsoft.Orleans.OrleansManager.nuspec
src/NuGet/Microsoft.Orleans.OrleansProviders.nuspec
src/NuGet/Microsoft.Orleans.OrleansRuntime.nuspec
src/NuGet/Microsoft.Orleans.OrleansServiceBus.nuspec
src/NuGet/Microsoft.Orleans.OrleansSqlUtils.nuspec
src/NuGet/Microsoft.Orleans.OrleansTelemetryConsumers.AI.nuspec
src/NuGet/Microsoft.Orleans.OrleansTelemetryConsumers.Counters.nuspec
src/NuGet/Microsoft.Orleans.OrleansTelemetryConsumers.NewRelic.nuspec
src/NuGet/Microsoft.Orleans.OrleansZooKeeperUtils.nuspec
src/NuGet/Microsoft.Orleans.Serialization.Bond.nuspec
src/NuGet/Microsoft.Orleans.Server.nuspec
src/NuGet/Microsoft.Orleans.ServiceFabric.nuspec
src/NuGet/Microsoft.Orleans.Templates.Grains.nuspec-NoSymbols
src/NuGet/Microsoft.Orleans.Templates.Interfaces.nuspec-NoSymbols
src/NuGet/Microsoft.Orleans.TestingHost.nuspec

Since the project moved out of MSR awhile ago.
Need to cherry-pick this to 1.3.0 final.

Replace "Microsoft Research" with "Microsoft" in the nuspecs

---

test/Tester/DependencyInjectionGrainTests.cs
test/Tester/TestDefaultConfiguration.cs

I believe I unintentionally changed our default to trace to console when running our tests (#2223), and since we are tracing to a log file already, this is unnecessarily increasing our log file, and I believe in some cases it might be failing the build, as errors written to the console are treated as build failures in jenkins (I think it's related to the cryptic error we recently started to see: `Failure to restore a package: Unable to resolve service for type 'System.String' while attempting to activate 'UnitTests.Grains.ExplicitlyRegisteredSimpleDIGrain`).

Do not trace to the console by default when running tests

---

src/Orleans/Core/GrainCasterFactory.cs
src/Orleans/Serialization/SerializationManager.cs

`Marshal.SizeOf(Type)` is obsolete in `System.Runtime.InteropServices` as of version 4.1.0.0, so this PR replaces its usage with a set of if/else statements.
Also fixes a documentation issue with `Type.IsAssignableFrom(Type)` which exists on .NET Standard as `TypeExtensions.IsAssignableFrom(Type, Type)`

Fix some .NET Standard warnings

---

src/Orleans/Serialization/IlBasedSerializerGenerator.cs
src/Orleans/Serialization/SerializationManager.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs
src/OrleansCodeGenerator/SerializerGenerator.cs

Fields in .NET Standard do not have a `FieldInfo.IsNotSerialized` property but the corresponding `[NonSerialized]` attribute is supported, so currently we are serializing fields which are marked as `[NonSerialized]`.
This PR fixes that.
An upcoming PR adds additional testing for non-serialized fields, such coverage exists today, but only for `IlBasedFallbackSerializer`. The new PR is blocked by #2253 & #2261.

.NET Standard support non-serialized fields via NonSerializedAttribute

---

src/OrleansManager/OrleansManager.csproj
src/OrleansManager/Program.cs
src/OrleansManager/RuntimeInterfaceConstants.cs
test/TestInternalGrains/EchoTaskGrain.cs
test/TestInternalGrains/PlacementTestGrain.cs
test/Tester/ManagementGrainTests.cs
test/Tester/MembershipTests/LivenessTests.cs
test/Tester/OrleansTestingBase.cs
test/Tester/PSClientTests/PSClientTests.cs
test/Tester/TestUtils.cs
test/Tester/Tester.csproj
test/TesterInternal/ActivationsLifeCycleTests/ActivationCollectorTests.cs
test/TesterInternal/General/ElasticPlacementTest.cs
test/TesterInternal/General/RequestContextTest.cs
test/TesterInternal/GeoClusterTests/BasicMultiClusterTest.cs
test/TesterInternal/GeoClusterTests/GlobalSingleInstanceClusterTests.cs
test/TesterInternal/GeoClusterTests/MultiClusterNetworkTests.cs
test/TesterInternal/StreamingTests/DynamicStreamProviderConfigurationTests.cs
test/TesterInternal/StreamingTests/StreamLimitTests.cs
test/TesterInternal/StreamingTests/StreamReliabilityTests.cs
test/TesterInternal/StreamingTests/StreamTestHelperClasses.cs
test/TesterInternal/TesterInternal.csproj

As per #2252, this inlines the constant id for IManagementGrain and removed test project dependencies on OrleansManager

Remove test dependency on OrleansManager (#2252)

---

src/Orleans/CodeGeneration/GeneratedAssembly.cs
src/OrleansCodeGenerator/RoslynCodeGenerator.cs

I've seen exceptions thrown because of this. They are transmitted across AppDomain boundaries.

Mark GeneratedAssembly/CachedAssembly serializable

---

src/OrleansRuntime/Core/Dispatcher.cs

Make the "No target activation" warning easier to troubleshoot in the case of a client disconnection, otherwise it could mislead into thinking that there is no *grain* activation available.

Make the "No target activation" warning easier to troubleshoot

---

test/NonSiloTests/SerializationTests/IlBasedSerializerTests.cs

These tests are irrelevant because IlBasedFallbackSerializer is explicitly intended to be a fallback serializer and not an external serializer (which is what the removed tests test for).
Additionally, this was the source of some non-determinism in test runs, since SerializationManager was not isolated in these tests.

Remove irrelevant IlBasedSerializerTests methods

---

test/NonSiloTests/SerializationTests/IlBasedSerializerTests.cs

In #2277 I removed the call to initialize SerializationManager, which resulted in the test only passing if another test had already initialized SerializationManager.
This change adds the call back.

Initialize SerializationManager in IlBasedSerializerTests

---

src/Orleans/Serialization/SerializationManager.cs
src/Orleans/Serialization/TypeUtilities.cs
src/OrleansCodeGenerator/SerializerGenerationManager.cs
test/NonSiloTests/SerializationTests/BuiltInSerializerTests.cs

Fixes for 3 serialization issues:
1. A recent change (by myself) resulted in generated `GrainReference` classes being passed through the fallback serializer.
2. Due to an inadequacy in `TypeUtilities.AreInternalsVisibleTo`, serializers were not being generated for types referencing internals from another assembly. For example, `ActivationInfo` in `OrleansRuntime` would not have a serializer generated because it has a field whose type is internal to `Orleans`. The change adds support for `[assembly: InternalsVisibleTo("xxx")]` where "xxx" is the short name of an assembly (eg, `"OrleansRuntime"`, rather than only supporting fully qualified assembly names.
3. The check to determine if a type is accessible for serialization involves recursively checking all serialized fields in that type. The …

Serialization fixes

---

src/Orleans/Core/GrainClient.cs
test/TesterInternal/General/RequestContextTest.cs

We are seeing failures related to this in functional test runs recently.
One of the test cases is not resetting ClientInvokeCallback.
This PR wraps each of those tests in try/finally blocks to reset `GrainClient.ClientInvokeCallback` and also resets it in the classes `Dispose()` method.

ClientInvokeCallback tests should always reset ClientInvokeCallback

---

src/NuGet/Microsoft.Orleans.OrleansConsulUtils.nuspec
src/NuGet/Microsoft.Orleans.OrleansSqlUtils.nuspec

It looks like two package icons are not updated to
the new one. Also, one image in OrleansContrib,
Microsoft.Orleans.ServiceFabric.Client, still
uses the old one.
See at https://www.nuget.org/packages?q=microsoft.orleans.*.

Updates the Nuget icons to the new one

---

test/TesterInternal/StorageTests/Relational/CommonStorageTests.cs
test/TesterInternal/StorageTests/Relational/CommonStorageUtilities.cs
test/TesterInternal/StorageTests/Relational/MySqlStorageTests.cs
test/TesterInternal/StorageTests/Relational/RandomUtilities.cs
test/TesterInternal/StorageTests/Relational/RelationalStorageTests.cs
test/TesterInternal/StorageTests/Relational/SqlServerStorageTests.cs

In ADO.NET tests when parallel test execution became possible,
it was possible for the the hash test grain IDs and types
collide with the ones used in testing 100 parallel insertions
and reads.

Removes InconsistentStateException from parallel tests

---

src/Documentation/Advanced-Concepts/Dependency-Injection.md

This PR corrects a mistake in the docs. See https://github.com/dotnet/orleans/issues/2309.

Issue #2309: The 'Startup' tag must be placed into the 'Defaults' section

---

src/Orleans/Messaging/GatewayClientReceiver.cs

Networking receiver buffer must be reset on socket error or reset.  Since this can happen on a send rather than a receive, it is now possible for the socket to be reset by the send without the receive buffer being cleared, which can lead to buffer corruption.
This change resets the receive buffer whenever the socket changes.

Reset client gateway reciever buffer on socket reset.

---

src/OrleansRuntime/ConsistentRing/ConsistentRingProvider.cs
src/OrleansRuntime/GrainDirectory/LocalGrainDirectory.cs

On each <code>Catalog</code> local lookup the delegate was allocated.

Remove delegate allocation

---

src/Orleans/Core/GrainCasterFactory.cs

Fixes an issue which @jdom encountered on .NET Core where the incorrect opcode is being used in `GrainCasterFactory`.
Why does a different opcode need to be emitted? That's because of this line:
```C#
private static readonly MethodInfo IsAssignableFromMethodInfo =
TypeUtils.Method((Type t) => t.IsAssignableFrom(default(Type)));
```
On full .NET, `Type` has a virtual `IsAssignableFrom(Type)` instance method. On .NET Core, that method is a (non-virtual) extension method.

GrainCasterFactory: emit correct call/callvirt opcodes

---

src/Orleans/IDs/GrainId.cs
src/Orleans/IDs/SiloAddress.cs
src/Orleans/IDs/UniqueKey.cs
src/Orleans/Serialization/OrleansJsonSerializer.cs
src/OrleansAzureUtils/Providers/Streams/PersistentStreams/StreamDeliveryFailureEntity.cs
src/OrleansServiceBus/Providers/Streams/EventHub/EventDataExtensions.cs

I'm not certain how useful this change is, since I haven't profiled the difference.
There are several cases where we are taking buffers from the buffer pool and not returning them. This PR eliminates several of those cases.
`BinaryTokenStreamWriter.ToByteArray()` allocates a new byte array and copies the result, whereas `ToBytes()` returns the underlying `List<ArraySegment<byte>>` directly. Hence it is safe to free the buffers after the former (assuming no further use), but not after the latter. `ToBytes()` should be called `AsBytes()` or `GetBuffers()` to reduce any confusion.
Adding an overload to `JenkinsHash.ComputeHash` which took a `List<ArraySegment<byte>>` instead of just the current `byte[]` would further help to reduce allocations.

Release BinaryTokenStreamWriter buffers after use in more cases.

---

src/OrleansTestingHost/AppDomainSiloHandle.cs
vNext/src/Orleans/Shims/AppDomain.cs
vNext/test/Tester/App.config
vNext/test/Tester/Tester.csproj
vNext/test/Tester/project.json

AppDomain shim loads all assemblies in local folder.
Added all references from Orleans and OrleansRuntime into Tester since because of the csproj hack, it looks like the nuget dependencies are not transitively passed on to Tester

Make basic silo tests run with .NET Standard version of Orleans
