src/Orleans.Core/Lifecycle/ServiceLifecycleStage.cs
src/Orleans.Runtime/Silo/Silo.cs
test/TesterInternal/ActivationsLifeCycleTests/DeactivateOnIdleTests.cs

Currently in rc1, grain can be activated on a silo not really ready. This PR tries to fix this behavior

Fix silo startup

---

src/OrleansProviders/Storage/MemoryStorage.cs
test/DefaultCluster.Tests/MemoryStorageProviderTests.cs
test/TestGrainInterfaces/INullStateGrain.cs
test/TestGrains/NullStateGrain.cs

Fix MemoryStorage - etag mismatch

---

Samples/2.0/AccountTransfer.NetCore/src/OrleansClient/Program.cs
Samples/2.0/AccountTransfer.NetCore/src/SiloHost/Program.cs
Samples/2.0/Adventure/AdventureClient/Program.cs
Samples/2.0/Adventure/AdventureSetup/Program.cs
Samples/2.0/HelloWorld/src/OrleansClient/Program.cs
Samples/2.0/HelloWorld/src/SiloHost/Program.cs
Samples/2.0/docker-aspnet-core/API/Startup.cs
Samples/2.0/docker-aspnet-core/Silo/Program.cs

Some breaking changes in SiloHostBuilder and ClientBuilder

Update samples to rc2

---

Community/Who-Is-Using-Orleans.html
src/Community/Who-Is-Using-Orleans.md

MRI has a deployment of around 17vm's (4-8 core, 4-16GB of ram) and 3 instances of IIS.

Add MRI community company blurb

---

src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets

CodeGen when a file is removed from @(Compile), reevaluate MSBuild target

---

src/AdoNet/Orleans.Clustering.AdoNet/Oracle-Clustering.sql
src/AdoNet/Orleans.Persistence.AdoNet/Oracle-Persistence.sql
src/AdoNet/Orleans.Reminders.AdoNet/Oracle-Reminders.sql

Change Oracle SQL parameter casing for Turkish language binding support on ODP.NET Managed

---

test/TesterInternal/GeoClusterTests/MultiClusterRegistrationTests.cs

I opened #4265 to investigate the test.

Skip intermittently failing ThreeClusterBattery test

---

src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubCheckpointer.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubCheckpointerOptions.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubPartitionCheckpointEntity.cs
test/ServiceBus.Tests/Streaming/EHClientStreamTests.cs
test/ServiceBus.Tests/Streaming/EHImplicitSubscriptionStreamRecoveryTests.cs
test/ServiceBus.Tests/Streaming/EHProgrammaticSubscribeTests.cs
test/ServiceBus.Tests/Streaming/EHStreamPerPartitionTests.cs
test/ServiceBus.Tests/Streaming/EHStreamProviderCheckpointTests.cs
test/ServiceBus.Tests/Streaming/EHSubscriptionMultiplicityTests.cs

- checkpoints new uses serviceid for partitioning
- table name has default

Clean up EH checkpointing

---

test/ServiceBus.Tests/PluggableQueueBalancerTests.cs
test/Tester/StreamingTests/PlugableQueueBalancerTests/PluggableQueueBalancerTestsWithMemoryStreamProvider.cs

Will be addressed with https://github.com/dotnet/orleans/issues/4317.

Skip ShouldUseInjectedQueueBalancerAndBalanceCorrectly tests.

---

test/Tester/StreamingTests/SystemTargetRouteTests.cs
test/TesterAzureUtils/Reminder/ReminderTests_AzureTable.cs
test/TesterInternal/TimerTests/ReminderTests_TableGrain.cs

Skip:
- PersistentStreamingOverSingleGatewayTest
- Rem_Grain_1J_MultiGrainMultiReminders
- Rem_Azure_GT_1F1J_MultiGrain

Skip some tests

---

test/TesterAzureUtils/Streaming/DelayedQueueRebalancingTests.cs

Somewhere between 1.5 and 2.0, the set up for `DelayedQueueRebalancingTests` changed. 
In 1.5, the test cluster size is 4, but only 2 silo started at the beginning. There's another 2 started later in `DelayedQueueRebalancingTests_2` . Hence the name -- delayed... I guess it means delayed silo starting. 
Before I thought there's a bug in `DynamicClusterConfigDeploymentBalancer`. But now I think the failure before is caused by `StartAdditionalSilos` behave differently between 1.5 and 2.0. and also the test set up was different.

Fix DelayedQueueRebalancingTests test set up

---

src/Documentation/Advanced-Concepts/Reentrant-Grains.md
src/Documentation/Advanced-Concepts/toc.yml

cc @dVakulen, if you want to take a look.

Update Reentrancy docs

---

src/Orleans.Streaming.GCP/Orleans.Streaming.GCP.csproj

PackageId should start with "Microsoft".

---

src/Documentation/Deployment-and-Operations/Monitoring/Runtime-Monitoring.md

Annoying typo in header

---

src/Documentation/Advanced-Concepts/Powershell-Client.md

Fix broken link to ManagementGrain.cs

Fix broken link in Powershell-Client.md

---

src/Documentation/Deployment-and-Operations/Service-Fabric.md

Fix a link pointing to the repo

Update Service-Fabric.md - fix a link

---

src/Orleans.Runtime/Scheduler/InvokeWorkItem.cs

Avoiding of `ContinueWith` removes few additional allocations per synchronous call.

Avoid continuation in synchronous case

---

src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorage.cs
test/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureBlobStore_Json.cs

Fixes #4439 
Submitted for testing

Azure blob storage provider: respect UseJson setting

---

test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerBasicTests.cs

Improve reliability of Sched_Task_SubTaskExecutionSequencing test

---

test/TesterAzureUtils/Streaming/StreamReliabilityTests.cs

Fix SMS_AllSilosRestart_UnsubscribeConsumer

---

src/Orleans.Runtime/Messaging/Gateway.cs

Fix routing in Silo Gateway

---

test/DependencyInjection.Tests/Autofac/DependencyInjectionDisambiguationTestsUsingAutofac.cs
test/DependencyInjection.Tests/Autofac/DependencyInjectionGrainTestsUsingAutofac.cs
test/DependencyInjection.Tests/DefaultServiceProvider/DependencyInjectionDisambiguationTestsUsingDefaultServiceProvider.cs
test/DependencyInjection.Tests/DefaultServiceProvider/DependencyInjectionGrainTestsUsingDefaultServiceProvider.cs
test/DependencyInjection.Tests/DependencyInjection.Tests.csproj
test/DependencyInjection.Tests/DependencyInjectionDisambiguationTests.cs
test/DependencyInjection.Tests/StructureMap/DependencyInjectionDisambiguationTestsUsingStructureMap.cs

both internal and external customer has reported they are using Autofac with Orleans. In theory Orleans should work with Autofac, after fix #4453 , I just want to ensure it really works,by adding DI tests running against Autofac DI container.

Add autofac DI tests

---

src/Documentation/Core-Features/Observers.md

This is to update the Observer doc to show the necessity of mitigating for the OrleansException that is thrown if you try to subscribe/unsubscribe an observer that is already added to/removed from the observer manager. #4061

Update Observers doc page for handling case of already subbed/unsubbed (#4061)

---

README.md

Include instructions to use MyGet feed on both NuGet.config and new .csproj.

Include instructions to use MyGet feed.

---

src/Documentation/Orleans-Streams/Streams-Extensibility.md

fix for #4434 . the section is outdated, still in the 1.5 and before state.

Update stream-extensibility section docs

---

src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs

Fix NRE on AWS DynamoDB storage provider. #4482

Fix NRE on AWS DynamoDB storage provider

---

src/Documentation/Core-Features/Dependency-Injection.md

Fixed incorrect sample in DI docs

---

src/Azure/Orleans.Transactions.AzureStorage/Storage/AzureTransactionArchiveLogOptions.cs
src/Azure/Orleans.Transactions.AzureStorage/Storage/AzureTransactionLogOptions.cs
src/Azure/Orleans.Transactions.AzureStorage/Storage/AzureTransactionLogStorage.cs
test/Benchmarks/Benchmarks/TransactionManager/TransactionManagerBentchmarks.cs
test/Transactions/Orleans.Transactions.Azure.Test/AzureTransactionLogTests.cs
test/Transactions/Orleans.Transactions.Azure.Test/GoldenPathTransactionManagerTest.cs

- Archive transaction logs
- Add minimum query API
- Add minimum testing on the feature
Since no enough information for me to know which queries will be most useful, so I didn't add any specific query API, just the general API which takes a `TableQuery`

Archive transaction logs

---

src/Documentation/Deployment-and-Operations/Configuration-Guide/Server-Configuration.md

Fixed couple of typos (Microsoft people love their search engine)

---

Directory.Build.props
src/Azure/Directory.Build.props
src/Azure/Orleans.Hosting.ServiceFabric/Directory.Build.props
src/Azure/Orleans.Streaming.EventHubs/Directory.Build.props

Bump up version of Azure extension packages and fix versions of some references.

Fix tests on partial builds

---

src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/AzureTableTransactionalStateStorageFactory.cs
src/Orleans.Core/Runtime/GrainReferenceExtensions.cs
test/Benchmarks/Benchmarks.csproj
test/Benchmarks/Program.cs
test/Benchmarks/Transactions/TransactionBenchmark.cs
test/Grains/BenchmarkGrainInterfaces/Transaction/ITransactionGrain.cs
test/Grains/BenchmarkGrains/Transaction/LoadGrain.cs
test/Grains/BenchmarkGrains/Transaction/TransactionGrain.cs
test/TestInfrastructure/Orleans.TestingHost.Legacy/Orleans.TestingHost.Legacy.csproj
test/TestInfrastructure/TestExtensions/TestExtensions.csproj

Added transaction benchmark that runs against azure storage.
Fixed bugs in transaction bentchmark.

Azure transaction benchmark

---

test/Transactions/Orleans.Transactions.Azure.Test/TransactionRecoveryAzureTests.cs
test/Transactions/Orleans.Transactions.Tests/Memory/TransactionRecoveryMemoryTests.cs

I forgot to enable these tests..

Enable tx recovery tests

---

test/Transactions/Orleans.Transactions.Azure.Test/TransactionConcurrencyTests.cs
test/Transactions/Orleans.Transactions.Azure.Test/TransactionRecoveryAzureTests.cs
test/Transactions/Orleans.Transactions.Tests/Hosting/TransactionTestExtensions.cs
test/Transactions/Orleans.Transactions.Tests/Memory/TransactionConcurrencyTests.cs
test/Transactions/Orleans.Transactions.Tests/Memory/TransactionRecoveryMemoryTests.cs
test/Transactions/Orleans.Transactions.Tests/Runners/TransactionConcurrencyTestRunner.cs
test/Transactions/Orleans.Transactions.Tests/TransactionTestConstants.cs

- failing against memory storage, unclear why.  Tests disabled, will open bug

Transaction concurrency tests

---

src/Orleans.Core.Abstractions/IDs/GrainId.cs
src/Orleans.Core.Abstractions/IDs/UniqueKey.cs
src/Orleans.Core/Messaging/Message.cs
src/Orleans.Core/Runtime/Constants.cs
src/Orleans.Core/SystemTargetInterfaces/IMembershipTable.cs
src/Orleans.Runtime/Catalog/ActivationData.cs
src/Orleans.Runtime/Catalog/Catalog.cs
src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
src/Orleans.Runtime/MembershipService/MembershipOracle.cs
src/Orleans.Runtime/MembershipService/SystemTargetBasedMembershipTable.cs
src/Orleans.TestingHost/TestClusterHostFactory.cs

Addresses https://github.com/dotnet/orleans/issues/3129.

 Convert IMembershipTableGrain into a SystemTarget

---

src/Orleans.Core/Statistics/CounterStatistic.cs
src/Orleans.Core/Statistics/FloatValueStatistic.cs

Fixes #4607
cc @SebastianStehle are you able to verify this?

Convert counter values before calling ITelemetryProducer.TrackMetric

---

src/Orleans.Core/Messaging/IncomingMessageBuffer.cs

Remove O(n^2) buffer cleanup logic.

Optimize removing consumed buffers from read buffer

---

src/Orleans.Core/Transactions/OrleansTransactionException.cs
src/Orleans.Transactions/DistributedTM/TransactionAgent.cs
src/Orleans.Transactions/DistributedTM/TransactionOverloadDetector.cs
src/Orleans.Transactions/Hosting/SiloBuilderExtensions.cs
test/Transactions/Orleans.Transactions.Tests/TransactionOverloadDetectorTests.cs

Transaction load shedding based on txStartedPerSecond. 
Configurable through TransactionLoadShuddingOptions

Transaction load shedding based on txStartedPerSecond

---

src/Orleans.Core.Abstractions/IDs/GrainId.cs
src/Orleans.Core.Abstractions/IDs/UniqueKey.cs
src/Orleans.Core/Runtime/Constants.cs

Addresses https://github.com/dotnet/orleans/issues/4666.

Fix wire backward compatibility

---

src/Orleans/Configuration/OrleansConfiguration.xsd
src/Orleans/Logging/ErrorCodes.cs
src/Orleans/Messaging/GatewayManager.cs
src/Orleans/Messaging/SocketManager.cs
src/OrleansCodeGenerator/Utilities/StringExtensions.cs
src/OrleansRuntime/Messaging/IncomingMessageAcceptor.cs
src/OrleansRuntime/Messaging/IncomingMessageAgent.cs
test/TestGrains/MultipleGenericParameterInterfaceImpl.cs
test/Tester/ClientConnectionTests/StallConnectionTests.cs

#4667 got squash-merged, which is not good for tracking history. I reset the 1.5.4 branch, so that these fixes can be re-merged without getting squashed.

Resubmitting #4667 for an unsquashed merge

---

src/AdoNet/Orleans.Persistence.AdoNet/MySQL-Persistence.sql
src/AdoNet/Orleans.Persistence.AdoNet/Oracle-Persistence.sql
src/AdoNet/Orleans.Persistence.AdoNet/PostgreSQL-Persistence.sql
src/AdoNet/Orleans.Persistence.AdoNet/SQLServer-Persistence.sql
src/AdoNet/Orleans.Reminders.AdoNet/MySQL-Reminders.sql
src/AdoNet/Orleans.Reminders.AdoNet/Oracle-Reminders.sql
src/AdoNet/Orleans.Reminders.AdoNet/PostgreSQL-Reminders.sql
src/AdoNet/Orleans.Reminders.AdoNet/SQLServer-Reminders.sql
src/AdoNet/Shared/MySQL-Main.sql
src/AdoNet/Shared/Oracle-Main.sql
src/AdoNet/Shared/PostgreSQL-Main.sql
src/AdoNet/Shared/SQLServer-Main.sql

Updates reference links to working

udpate reference links in sql files

---

src/Azure/Orleans.Reminders.AzureStorage/Storage/AzureBasedReminderTable.cs

Removing internal to allow for extensions

remove internal

---

Samples/2.0/docker-aspnet-core/API/Startup.cs

Use filters instead of the current method.
The current method wont work because the client must be reconstructed if it fails to initialize.

Docker sample: fix client connection retry logic

---

src/Orleans.Core/Lifecycle/LifecycleSubject.cs
src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs
test/Extensions/TesterAdoNet/StorageTests/Relational/CommonFixture.cs

Make LifecycleSubject logging less verbose

---

src/Orleans.Core/Configuration/ConfigUtilities.cs

Do not use ip address from interface not operational

---

test/Extensions/TesterAzureUtils/Persistence/PersistenceProviderTests.cs

Fix azure tests

---

Samples/2.0/HelloWorld/src/OrleansClient/Program.cs

Removed unnecessary parts configuration

---

src/Orleans.Core.Abstractions/Async/PublicOrleansTaskExtensions.cs

https://github.com/dotnet/orleans/issues/4728

Updated Ignore(this Task) method

---

Samples/2.0/Adventure/AdventureClient/Program.cs

Program.cs file for Client had a typo "What's you name" - changed to "What's your name?"

Fixed typo

---

src/Documentation/Samples-Overview/Adventure.md

fixed typos, shortened heading for readability
@jason-bragg

Another update for Adventure.md

---

Documentation/Orleans-Streams/index.html

Updated link to SampleStreamingGrain.cs.

---

src/Orleans.CodeGeneration/GrainReferenceGenerator.cs
src/Orleans.Core.Abstractions/CodeGeneration/InvokeMethodRequest.cs
src/Orleans.Core.Abstractions/Transactions/TransactionAttribute.cs
src/Orleans.Core/CodeGeneration/GrainInterfaceUtils.cs
src/Orleans.Core/Messaging/MessageFactory.cs
src/Orleans.Transactions/Abstractions/ITransactionParticipantExtension.cs
test/Grains/BenchmarkGrainInterfaces/Transaction/ITransactionGrain.cs
test/Grains/BenchmarkGrainInterfaces/Transaction/ITransactionRootGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionAttributionGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionCoordinatorGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionTestGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionalBitArrayGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/TransactionAttributionGrain.cs
test/Transactions/Orleans.Transactions.Tests/Memory/TransactionAttributionTest.cs
test/Transactions/Orleans.Transactions.Tests/Runners/SkewedClock.cs
test/Transactions/Orleans.Transactions.Tests/Runners/TransactionAttributionTestRunner.cs

Added test cases to ensure transaction attribute options (NotSupported, Required, RequiredNew) properly maintain transaction context.

Transaction attribution test

---

test/Benchmarks/Benchmarks.csproj
test/Benchmarks/GrainStorage/GrainStorageBenchmark.cs
test/Benchmarks/Program.cs
test/Grains/BenchmarkGrainInterfaces/GrainStorage/IPersistentGrain.cs
test/Grains/BenchmarkGrains/GrainStorage/PersistentGrain.cs

Added a grain storage benchmark to help track down #4612.
Unfortunately, not able to repro the issue (yet).

Added grain storage to benchmarks

---

src/Documentation/Deployment-and-Operations/Heterogeneous-Silos.md

some very small spelling fixes

Small spelling fix in Heterogeneous-Silos.md

---

src/Documentation/Deployment-and-Operations/Docker-Deployment.md

just small changes which eliminate some errors and should make reading a little easier

Fixed some spellings/sentences in Docker-Deployment.md

---

src/Documentation/Advanced-Concepts/Activation-Garbage-Collection.md

Modify activation garbage collection code

Modify activation garbage collection code

---

src/Azure/Orleans.Reminders.AzureStorage/Storage/RemindersTableManager.cs

Cleanup Reminders PartitionKey

---

src/Orleans.Core/Async/BatchWorker.cs
src/Orleans.EventSourcing/Common/PrimaryBasedLogViewAdaptor.cs
src/Orleans.Transactions/State/TransactionalState.cs

No functional change, just a minor cleanup and minor reduction of API surface

Clean up BatchWorker

---

src/Documentation/Core-Features/Grain-Persistence.md

Update Grain-Persistence.md - fix typo

---

src/Documentation/Event-Sourcing/GrainStateAPI.md
src/Documentation/Grain-Versioning/Compatible-grains.md

Correction to small issues discovered when reading documentation

Documentation correction

---

test/Transactions/Orleans.Transactions.Tests/Runners/TransactionRecoveryTestsRunner.cs

Updated transaction correctness/recoverability tests to not check results against client expectations if transaction success was ambiguous.

Ignore ambiguous transactions in correctness testing.

---

src/Orleans.Core/Streams/PubSub/ImplicitStreamSubscriberTable.cs

ImplicitStreamSubscription Attribute inherit = false #1909

Allow implicit subscription attribute to be inheritable

---

src/Documentation/Getting-Started-With-Orleans/Developing-a-Client.md

As per gitter message the client is safe to reuse in the application as a singleton. 
https://gitter.im/dotnet/orleans?at=5b69947204436a1ae62a0d3c

Clarification on Client lifetime

---

src/Documentation/Runtime-Implementation-Details/Cluster-Management.md

Repair typesetting error

---

src/Orleans.Runtime/Placement/StatelessWorkerDirector.cs

Do not place stateless worker locally if the silo is stopping

---

test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionalBitArrayGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/MultiStateTransactionalBitArrayGrain.cs
test/Transactions/Orleans.Transactions.Tests/Runners/TransactionRecoveryTestsRunner.cs

Improve diagnostics & fix JSON serialization issue with `BitArrayState`

TransactionRecovery test fixes

---

src/Orleans.Core/Providers/LegacyProviderConfigurator.cs
src/OrleansProviders/Hosting/MemoryGrainStorageSiloBuilderExtensions.cs

Addresses - IGrainStorage null implementation registerd in DI container #4710

No default grains storage added to container if one is not configured.

---

src/Orleans.Transactions/Hosting/SiloBuilderExtensions.cs
test/Benchmarks/Transactions/TransactionBenchmark.cs
test/Transactions/Orleans.Transactions.Azure.Test/TestFixture.cs
test/Transactions/Orleans.Transactions.Tests/Memory/MemoryTransactionsFixture.cs

Rename UseDistributedTM to UseTransactions

---

src/Documentation/toc.yml

Part 1 of 2 changes to restore links to Streaming

Put Streaming back into toc file

---

src/Documentation/grains/toc.yml

This change depends on the change renaming "Developing a grain" to index.md

Adding missing files in Grains directory

---

src/Orleans.Core/Serialization/OrleansJsonSerializer.cs
test/NonSilo.Tests/Serialization/OrleansJsonSerializerTests.cs

Fix DI cycle involving OrleansJsonSerializer

---

src/Orleans.Core/Transactions/TransactionContext.cs
src/Orleans.Transactions/DistributedTM/ParticipantId.cs
src/Orleans.Transactions/DistributedTM/TransactionAgent.cs
src/Orleans.Transactions/TOC/TocTransactionQueue.cs
src/Orleans.Transactions/TOC/TransactionCommitter.cs
test/Transactions/Orleans.Transactions.Tests/Consistency/ConsistencyTestGrain.cs

- Constructor mismatches
- Adde CurrentTransactionId to transaction context

Fixed build breaks from bad merge:

---

src/Orleans.Clustering.Consul/ConsulBasedMembershipTable.cs
src/Orleans.Clustering.Consul/ConsulGatewayListProvider.cs
src/Orleans.Clustering.Consul/Options/ConsulClusteringClientOptions.cs
src/Orleans.Clustering.Consul/Options/ConsulClusteringSiloOptions.cs
src/Orleans.Clustering.Consul/SerializableMembershipTypes.cs

Following changes have been included in this PR.
1. Consul ACL integration.
2. Creating the cluster folder under a specific folder at the root of KV store.
Consul ACL integration
************************
The current orleans clustering consul package is not having an import feature i.e ACL integration, which is a security features of Consul that restricts unauthorized access on the cluster KV folder. 
Sample code
var client = new ClientBuilder().Configure<ClusterOptions>(options =>
{
options.ClusterId = ConfigurationManager.AppSettings["ClusterId"];
options.ServiceId = ConfigurationManager.AppSettings["ServiceId"];
})
.UseConsulClustering(gatewayOptions =>
{
gatewayOptions.Address =
new Uri(ConfigurationManager.AppSettings["ServiceDiscoverEndPoint"]);
gatewayOptions.AclClientToken = …

Consul clustering enhancements

---

src/Documentation/clusters_and_clients/configuration_guide/typical_configurations.md

Corrected information was received, upon review. 
Previous change involving line 129 ".UseStaticClustering(gateways)" has been reverted and different changes have been made.
This fixes issue #4692.

Change new ip end point 11111

---

src/Orleans.Core/Transactions/TransactionalStatus.cs
src/Orleans.Transactions/State/TransactionQueue.cs
src/Orleans.Transactions/TOC/TocTransactionQueue.cs
test/Transactions/Orleans.Transactions.Azure.Test/TocFaultTransactionTests.cs
test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionCommitterTestGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionCoordinatorGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/RemoteCommitService.cs
test/Transactions/Orleans.Transactions.Tests/Grains/TransactionCommitterTestGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/TransactionCoordinatorGrain.cs
test/Transactions/Orleans.Transactions.Tests/Memory/TocFaultTransactionMemoryTests.cs
test/Transactions/Orleans.Transactions.Tests/Runners/TOCGoldenPathTestRunner.cs
test/Transactions/Orleans.Transactions.Tests/Runners/TocFaultTransactionTestRunner.cs

Fixed TOC aborts under service failure
Added minimal failure testing for TOC.

TOC aborts under service failure

---

test/Transactions/Orleans.Transactions.Azure.Test/FaultInjection/ControlledInjection/TransactionFaultInjectionTests.cs
test/Transactions/Orleans.Transactions.Tests/FaultInjection/ControlledInjection/FaultInjectionTransactionReource.cs
test/Transactions/Orleans.Transactions.Tests/FaultInjection/ControlledInjection/FaultInjectionTransactionState.cs
test/Transactions/Orleans.Transactions.Tests/FaultInjection/ControlledInjection/SingleStateDeactivatingTransactionalGrain.cs
test/Transactions/Orleans.Transactions.Tests/Runners/ControlledFaultInjectionTransactionTestRunner.cs

Didn't know confirm would be retried on failure, so I didn't reset fault injection control after confirmed once, which cause some of the tests failing.
This pr fixes it.

Enable fault injection tests

---

src/Orleans.Transactions/State/TransactionManager.cs
src/Orleans.Transactions/State/TransactionQueue.cs
src/Orleans.Transactions/State/TransactionalResource.cs
test/Transactions/Orleans.Transactions.Azure.Test/FaultInjection/ControlledInjection/SimpleAzureStorageExceptionInjector.cs
test/Transactions/Orleans.Transactions.Azure.Test/FaultInjection/ControlledInjection/TransactionFaultInjectionTests.cs
test/Transactions/Orleans.Transactions.Tests/FaultInjection/ControlledInjection/FaultInjectionTransactionReource.cs
test/Transactions/Orleans.Transactions.Tests/FaultInjection/ControlledInjection/SingleStateDeactivatingTransactionalGrain.cs
test/Transactions/Orleans.Transactions.Tests/Runners/ControlledFaultInjectionTransactionTestRunner.cs

- Addressed transaction recovery issues.
- Fixed minor test issues.
- Still not added to functional, because they take too long to run.  Need to fix the abort issue, then we can remove delays and to functional

Fixed TransactionFaultInjectionTests

---

src/Documentation/deployment/toc.yml
src/Documentation/deployment/troubleshooting_deployments.md

Add troubleshooting deployments page

---

src/Documentation/grains/grainservices.md
src/Documentation/grains/toc.yml

Adds new grainServices.md file.
Fixes issues #4675 and #3122

Add new file: grainServices.md

---

src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorageOptions.cs
src/Azure/Shared/Storage/AzureStorageUtils.cs
test/Extensions/TesterAzureUtils/AzureTableErrorCodeTests.cs

PR for: Azure Blob storage provider does not sanitize blob names (https://github.com/dotnet/orleans/issues/1496)

Added Validations for Blob Names and refactored the ContianerName & TableName validations

---

src/Orleans.Runtime/Messaging/OutboundMessageQueue.cs

avoid lazy initialization when disposing OutboundMessageQueue

---

src/Orleans.CodeGenerator/CodeGenerator.cs

Filter static types from list of types known to serializer

---

src/Documentation/whats_new_in_orleans.md

Also made a few minor grammatical and formatting changes.

Updates page up to v2.1.0

---

test/Transactions/Orleans.Transactions.Azure.Test/FaultInjection/ControlledInjection/TransactionFaultInjectionTests.cs

Disable fault injection tx test, will turn it on after investigation on its failures

Disable fault injection tx test

---

src/Orleans.CodeGenerator/Utilities/SymbolSyntaxExtensions.cs

#5067 Adding global alias for binding flags in generator

---

src/Orleans.Runtime/Core/InsideRuntimeClient.cs
src/Orleans.Transactions/DistributedTM/TransactionRecord.cs
src/Orleans.Transactions/State/TransactionQueue.cs
test/Transactions/Orleans.Transactions.Tests/Runners/TransactionRecoveryTestsRunner.cs

- May still be an issues need to run test 19289 more times in a row to find it :/
- Still looking

Partial fix for transaction recovery tests

---

src/Orleans.CodeGenerator/CodeGenerator.cs
src/Orleans.CodeGenerator/Generators/SerializerGenerator.cs
src/Orleans.CodeGenerator/Utilities/SymbolExtensions.cs
src/Orleans.CodeGenerator/WellKnownTypes.cs

CodeGen: Warn users when a type inherits from a type defined in a ref asm

---

src/Documentation/implementation/testing.md

Also added reference around dependency injection after a conversation
with @ReubonBond.
Fixes #5083.
Signed-off-by: Mike Lloyd <mike@reboot3times.org>

Added testing reference from 1.5 for 2.0.

---

src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/AzureTableTransactionalStateStorage.cs
src/Orleans.Transactions/DistributedTM/TransactionRecord.cs
src/Orleans.Transactions/State/ConfirmationWorker.cs
src/Orleans.Transactions/State/TransactionQueue.cs
test/Transactions/Orleans.Transactions.Tests/Grains/MultiStateTransactionalBitArrayGrain.cs
test/Transactions/Orleans.Transactions.Tests/Hosting/TransactionTestExtensions.cs
test/Transactions/Orleans.Transactions.Tests/Runners/TransactionRecoveryTestsRunner.cs

- Refactored confirmation management.
- Confirmation task only resoved after write to storage.

Fixed bug in transaction confirmation logic

---

Samples/2.0/AccountTransfer.NetCore/src/AccountTransfer.Grains/AccountGrain.cs
Samples/2.0/AccountTransfer.NetCore/src/AccountTransfer.Interfaces/IATMGrain.cs
Samples/2.0/AccountTransfer.NetCore/src/AccountTransfer.Interfaces/IAccountGrain.cs
Samples/2.0/AccountTransfer.NetCore/src/OrleansClient/Program.cs
Samples/2.0/AccountTransfer.NetCore/src/SiloHost/Program.cs
src/Orleans.Core/Transactions/TransactionContext.cs

* Update sample to the newer version of the transaction interface.
* Add ReadKey in sample client after an exception is thrown to keep the window open long enough to read the exception
* Fix an exception to remove reference to deprecated functionality.

Update AccountTransfer sample 

---

Samples/2.1/HelloWorld/BuildAndRun.ps1
Samples/2.1/HelloWorld/BuildAndRun.sh
Samples/2.1/HelloWorld/HelloWorld.sln
Samples/2.1/HelloWorld/Readme.md
Samples/2.1/HelloWorld/src/HelloWorld.Grains/HelloArchiveGrain.cs
Samples/2.1/HelloWorld/src/HelloWorld.Grains/HelloGrain.cs
Samples/2.1/HelloWorld/src/HelloWorld.Grains/HelloWorld.Grains.csproj
Samples/2.1/HelloWorld/src/HelloWorld.Interfaces/HelloWorld.Interfaces.csproj
Samples/2.1/HelloWorld/src/HelloWorld.Interfaces/IHello.cs
Samples/2.1/HelloWorld/src/HelloWorld.Interfaces/IHelloArchive.cs
Samples/2.1/HelloWorld/src/OrleansClient/OrleansClient.csproj
Samples/2.1/HelloWorld/src/OrleansClient/Program.cs
Samples/2.1/HelloWorld/src/SiloHost/Program.cs
Samples/2.1/HelloWorld/src/SiloHost/SiloHost.csproj

Migrated HelloWorld to dotnet core 2.1 #2359

#2359 Migrated HelloWorld to dotnet core 2.1

---

src/Orleans.Clustering.Consul/SerializableMembershipTypes.cs

Fix rootKvFolder is not backward compatible

Fix Consul rootKvFolder option is not backward compatible

---

src/Documentation/tutorials_and_samples/index.md
src/Documentation/tutorials_and_samples/toc.yml
src/Documentation/tutorials_and_samples/tutorial_1_helloworld.md

This tutorial ties in with the Hello World sample.

Tutorial 1 for Orleans 2.0

---

src/Documentation/tutorials_and_samples/tutorial_1_helloworld.md

I removed a blank line just to see if everything is working correctly.

Test "Improve this Doc" link and functionality

---

src/Orleans.Transactions/State/TransactionalState.cs

Internal transactional states are now immutable outside transactional operations.

Internal transactional states are now immutable

---

test/Transactions/Orleans.Transactions.Tests/Grains/ITransactionCoordinatorGrain.cs
test/Transactions/Orleans.Transactions.Tests/Grains/TransactionCoordinatorGrain.cs
test/Transactions/Orleans.Transactions.Tests/Runners/GoldenPathTransactionTestRunner.cs

Added golden path tests for multiple transactional reads and writes within a single transaction

 transactional multiple read/write tests

---

src/Orleans.Transactions/DistributedTM/TransactionAgent.cs
src/Orleans.Transactions/TOC/TransactionCommitter.cs
test/Transactions/Orleans.Transactions.Azure.Test/ConsistencySkewedClockTests.cs
test/Transactions/Orleans.Transactions.Azure.Test/ConsistencyTests.cs
test/Transactions/Orleans.Transactions.Azure.Test/FaultInjection/RandomInjection/ConsistencyFaultInjectionTests.cs
test/Transactions/Orleans.Transactions.Tests/Memory/ConsistencySkewedClockTests.cs
test/Transactions/Orleans.Transactions.Tests/Memory/ConsistencyTests.cs

- Reduced linq usages and allocations.

Cleanup Transaction Agent

---

src/Orleans.Core/Threading/ThreadPoolExecutor.cs

It seems that when `DrainAfterCancel` is set to true, the `ThreadPoolExecutor` will never return, which can cause some leak if for some reason the client or the silo is restarted without terminating the process

Fix drain logic in ThreadPoolExecutor

---

src/Orleans.Runtime/Services/GrainService.cs

I did edit in github editor and it seems added new line. so I am trying to enforce documentation by some ide tricks.

trying to hide something which leads to errors

---

src/AWS/Orleans.Streaming.SQS/Streams/SQSStreamBuilder.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueStreamBuilder.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubStreamBuilder.cs
src/Orleans.Streaming.GCP/Providers/Streams/PubSub/PubSubStreamConfigurator.cs

Fixes #5172 for all streams providers
Thanks for being patient, @galvesribeiro :)

Ensure OrleansProviders is added as an ApplicationPart in streams providers

---

src/AWS/Orleans.Streaming.SQS/Streams/SQSStreamBuilder.cs
src/Azure/Orleans.Hosting.AzureCloudServices/Hosting/AzureSilo.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueStreamBuilder.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubStreamBuilder.cs
src/Orleans.Core/Messaging/RequestInvocationHistory.cs
src/Orleans.Runtime/Core/Dispatcher.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
src/Orleans.Runtime/GrainTypeManager/TypeManager.cs
src/Orleans.Streaming.GCP/Providers/Streams/PubSub/PubSubStreamConfigurator.cs

Fix AzureSilo startup (#5213)
Remove added type to fix backward compatibility (#5225)

Cherry-pick post 2.2.0-rc1 fixes for 2.2.0 final

---

Directory.Build.props
src/Orleans.Core/Streams/SimpleMessageStream/SimpleMessageStreamProducerExtension.cs
src/Orleans.Runtime.Legacy/Configuration/LegacyClusterConfigurationExtensions.cs
src/Orleans.Runtime/Core/Dispatcher.cs
src/Orleans.Runtime/Hosting/EndpointOptionsExtensions.cs
src/Orleans.Runtime/Silo/LocalSiloDetails.cs
src/Orleans.Runtime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Update ZooKeeperNetEx package to 3.4.12.1 (#5236)
Include exception in TryForwardRequest info log (#5238)
Improve logging of stream delivery errors. (#5230)
Support ProxyGatewayEndpoint from legacy configuration (#5214)

Cherry-pick post 2.2.0-rc1 fixes for 2.2.0 final #2

---

src/Orleans.Core.Abstractions/Runtime/GrainLifecycleStage.cs
src/Orleans.Core/Lifecycle/ServiceLifecycleStage.cs

Added first and last stages to grain lifecycle stages, to align with service lifecycle stages

Added 'first' and 'last' to grain lifecycle stages.

---

src/AWS/Directory.Build.props
src/AdoNet/Directory.Build.props
src/Azure/Orleans.Hosting.AzureCloudServices/Directory.Build.props
src/Azure/Orleans.Transactions.AzureStorage/Directory.Build.props
src/Orleans.Client/Directory.Build.props
src/Orleans.Clustering.Consul/Directory.Build.props
src/Orleans.Clustering.ZooKeeper/Directory.Build.props
src/Orleans.CodeGeneration.Build/Directory.Build.props
src/Orleans.CodeGeneration/Directory.Build.props
src/Orleans.CodeGenerator.MSBuild/Directory.Build.props
src/Orleans.CodeGenerator/Directory.Build.props
src/Orleans.Core.Abstractions/Directory.Build.props
src/Orleans.Core.Legacy/Directory.Build.props
src/Orleans.Core/Directory.Build.props
src/Orleans.EventSourcing/Directory.Build.props
src/Orleans.PowerShell/Directory.Build.props
src/Orleans.Runtime.Abstractions/Directory.Build.props
src/Orleans.Runtime.Legacy/Directory.Build.props
src/Orleans.Runtime/Directory.Build.props
src/Orleans.Server/Directory.Build.props
src/Orleans.Streaming.GCP/Directory.Build.props
src/Orleans.TestingHost/Directory.Build.props
src/Orleans.Transactions/Directory.Build.props
src/OrleansCounterControl/Directory.Build.props
src/OrleansManager/Directory.Build.props
src/OrleansProviders/Directory.Build.props
src/Serializers/Directory.Build.props
src/TelemetryConsumers/Directory.Build.props

Remove redundant SourceLink settings

---

src/Documentation/grains/transactions.md

Updates content with new information

Replaces previous Transaction page.

---

src/Orleans.Transactions/DistributedTM/TransactionAgent.cs

Addresses https://github.com/dotnet/orleans/issues/5250
I didn't add any checks for priority managers since they are kind of special, but perhaps we should.

Transaction Manager must be a write participant

---

src/Documentation/clusters_and_clients/index.md

Updates previous references to legacy API for client configuration

---

src/Documentation/grains/index.md

Clarifies Setup section of "Developing a Grain" document. 

---

src/Documentation/clusters_and_clients/configuration_guide/client_configuration.md
src/Documentation/clusters_and_clients/index.md

Updates sample code and removes "Awesome" from name of Orleans service in sample code source: http://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/client_configuration.html.

Update grain init info

---

src/Azure/Orleans.ServiceFabric/Orleans.ServiceFabric.csproj

Thanks to @kingboyk for pointing this out.

Fix typo in Orleans.ServiceFabric.csproj

---

src/Orleans.Runtime/Catalog/ActivationCollector.cs
src/Orleans.Runtime/Configuration/Validators/CollectionAgeLimitValidator.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
test/Grains/TestInternalGrains/ActivationGCTestGrains.cs
test/Tester/Forwarding/ShutdownSiloTests.cs
test/Tester/StreamingTests/SMSDeactivationTests.cs
test/TesterInternal/ActivationsLifeCycleTests/ActivationCollectorTests.cs

Add CollectionAge validation to GrainCollectionOptions

---

src/Orleans.CodeGeneration/Utilities/SyntaxFactoryExtensions.cs

Tested against the sample which @jbrestan provided in #5342

Fix #5342: Incorrect specification of global alias

---

src/Orleans.Runtime/Hosting/GenericHostExtensions.cs

See https://github.com/dotnet/orleans/pull/5261#issuecomment-461685114

Move UseOrleans extension method to Microsoft.Extensions.Hosting

---

test/Extensions/ServiceBus.Tests/Streaming/EHStreamProviderCheckpointTests.cs

There's couple streaming test failing intermittently in vso. Since I'm still investigating them and don't know why it is happening, so skip them for now.

Skip intermitent failing test

---

test/Extensions/TesterAzureUtils/Persistence/PersistenceProviderTests.cs

ConvertJsonToFromStorageFormatWithCustomJsonProperties test fix

---

Samples/1.x/GPSTracker/GPSTracker.Web/Views/Home/Index.cshtml

- Changed to wait until the map script is loaded.  Microsoft.Maps namespace should be used after the map control script is loaded. 
- Changed the code to make V8 map script loads asynchronously.

resolved the issue #5377

---

src/Orleans.Core/Configuration/Validators/ApplicationPartValidator.cs
test/NonSilo.Tests/ClientBuilderTests.cs
test/NonSilo.Tests/NonSilo.Tests.csproj
test/NonSilo.Tests/SiloHostBuilderTests.cs

Throw during startup if no grain classes/interfaces in app parts

---

src/Documentation/grains/event_sourcing/immediate_vs_delayed_confirmation.md

Fix a link in the docs

---

src/Orleans.Core.Abstractions/Streams/Core/IAsyncBatchObservable.cs
src/Orleans.Core.Abstractions/Streams/Core/IAsyncBatchObserver.cs
src/Orleans.Core.Abstractions/Streams/Core/IAsyncStream.cs
src/Orleans.Core.Abstractions/Streams/Core/StreamSubscriptionHandle.cs
src/Orleans.Core.Abstractions/Streams/Extensions/AsyncBatchObservableExtensions.cs
src/Orleans.Core.Abstractions/Streams/Extensions/GenericBatchAsyncObserver.cs
src/Orleans.Core/Streams/Internal/IInternalAsyncObservable.cs
src/Orleans.Core/Streams/Internal/StreamConsumer.cs
src/Orleans.Core/Streams/Internal/StreamConsumerExtension.cs
src/Orleans.Core/Streams/Internal/StreamImpl.cs
src/Orleans.Core/Streams/Internal/StreamSubscriptionHandleImpl.cs
src/Orleans.Core/Streams/PersistentStreams/PersistentStreamProducer.cs
src/OrleansProviders/Streams/Generator/GeneratorAdapterFactory.cs
src/OrleansProviders/Streams/Generator/Generators/SimpleGenerator.cs
src/OrleansProviders/Streams/Generator/IStreamGenerator.cs
test/Grains/TestGrains/GeneratedEventCollectorGrain.cs
test/Grains/TestInternalGrains/StreamLifecycleTestGrains.cs
test/Grains/TestInternalGrains/StreamLifecycleTestInternalGrains.cs
test/Grains/TestInternalGrains/StreamingGrain.cs
test/Tester/StreamingTests/StreamGeneratorProviderTests.cs

Only supported by persistent streams.

Refactored stream batch behaviors to support batch consumption.

---

src/AWS/Orleans.Streaming.SQS/Streams/SQSStreamBuilder.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueStreamBuilder.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubStreamBuilder.cs
src/Orleans.Core/Configuration/IComponentConfigurator.cs
src/Orleans.Core/Configuration/NamedServiceConfigurator.cs
src/Orleans.Core/Streams/ClientStreamExtensions.cs
src/Orleans.Core/Streams/ClusterClientPersistentStreamConfigurator.cs
src/Orleans.Core/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans.Core/Streams/SimpleMessageStreamConfigurator.cs
src/Orleans.Runtime.Abstractions/Hosting/StreamHostingExtensions.cs
src/Orleans.Runtime.Abstractions/Streams/ISiloPersistentStreamConfigurator.cs
src/Orleans.Runtime.Abstractions/Streams/SiloPersistentStreamConfigurator.cs
src/Orleans.Streaming.GCP/Providers/Streams/PubSub/PubSubStreamConfigurator.cs
src/OrleansProviders/Streams/Memory/MemoryStreamBuilder.cs

- Added IComponentConfigurator as a general configurator for components with subcomponents.and/or multiple options.
- Added NamesServiceConfigurator base class for configuring named services with subcomponents and/or multiple options.
- Refactors stream configurators to use names service configurator configurator pattern.

Introduced general component configurator pattern.

---

src/Orleans.Runtime/MembershipService/MembershipOracle.cs

Thanks @jinhong- for catching this!
Previous PR: #5389

Fix catch exception condition in cleaning of dead entries

---

src/Azure/Orleans.Streaming.AzureStorage/Hosting/ClientBuilderExtensions.cs
src/Azure/Orleans.Streaming.AzureStorage/Hosting/SiloBuilderExtensions.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueAdapter.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueAdapterFactory.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueAdapterReceiver.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueStreamBuilder.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueStreamOptions.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/IAzureQueueDataAdapter.cs
src/Orleans.Core.Abstractions/Streams/PersistentStreams/IQueueDataAdapter.cs
src/Orleans.Core/Configuration/NamedServiceConfigurator.cs
src/OrleansProviders/Streams/Common/RecoverableStreamConfigurator.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCacheOptions.cs
test/Extensions/TesterAzureUtils/Streaming/AQClientStreamTests.cs
test/Extensions/TesterAzureUtils/Streaming/AQProgrammaticSubscribeTest.cs
test/Extensions/TesterAzureUtils/Streaming/AQStreamFilteringTests.cs
test/Extensions/TesterAzureUtils/Streaming/AQStreamingTests.cs
test/Extensions/TesterAzureUtils/Streaming/AQSubscriptionMultiplicityTests.cs
test/Extensions/TesterAzureUtils/Streaming/AQSubscriptionObserverWithImplicitSubscribingTests.cs
test/Extensions/TesterAzureUtils/Streaming/AzureQueueAdapterTests.cs
test/Extensions/TesterAzureUtils/Streaming/DelayedQueueRebalancingTests.cs
test/Extensions/TesterAzureUtils/Streaming/HaloStreamSubscribeTests.cs
test/Extensions/TesterAzureUtils/Streaming/SampleAzureQueueStreamingTests.cs
test/Extensions/TesterAzureUtils/Streaming/StreamLifecycleTests.cs
test/Extensions/TesterAzureUtils/Streaming/StreamLimitTests.cs
test/Extensions/TesterAzureUtils/Streaming/StreamReliabilityTests.cs
test/Tester/StreamingTests/PullingAgentManagementTests.cs

- Updated AzureQueueStream to use IQueueDataAdapter, replacing IAzureQueueDataAdapter.
- Cleaned up azure queue stream provider configuration to support IQueueDataAdapter as a configurable component.

Added IQueueData adapter for persistent streams.

---

src/Documentation/implementation/load_balancing.md

Documentation: Fixed link to powerpoint

---

src/TelemetryConsumers/Orleans.TelemetryConsumers.Linux/HostBuilderExtensions.cs

Add UseLinuxEnvironmentStatistics method for ISiloBuilder

---

src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs

Fix #5519: use local silo as default primary silo

---

src/Orleans.Core.Abstractions/Streams/Core/IAsyncBatchProducer.cs
src/Orleans.Core.Abstractions/Streams/Core/IAsyncStream.cs
src/Orleans.Core/Streams/Internal/IInternalAsyncObservable.cs
src/Orleans.Core/Streams/Internal/StreamImpl.cs
src/Orleans.Core/Streams/PersistentStreams/PersistentStreamProducer.cs
test/Extensions/ServiceBus.Tests/Streaming/EHStreamBatchingTests.cs
test/Extensions/TesterAzureUtils/Streaming/AQStreamsBatchingTests.cs
test/Grains/TestGrainInterfaces/IStreamBatchingTestConsumerGrain.cs
test/Grains/TestGrains/StreamBatchingTestConsumerGrain.cs
test/Tester/StreamingTests/MemoryStreamBatchingTests.cs
test/Tester/StreamingTests/SMSBatchingTests.cs
test/Tester/StreamingTests/StreamBatchingTestRunner.cs

-Added testing for batch behaviors for EH, AQ, Memory and SMS.  Works for all but SMS.
-SMS tests skipped until we fix.
Surfaces are asymmetric though.  Will discuss with team before merging.

Added batch stream production back in.

---

src/Documentation/core_concepts/what_are_orleans_packages.md

Fix Reminders.AzureStorage package description

---

src/AWS/Orleans.Persistence.DynamoDB/Hosting/DynamoDBSiloBuilderExtensions.cs
src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs
src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/SiloBuilderExtensions.cs
src/Azure/Orleans.Persistence.AzureStorage/Hosting/AzureBlobSiloBuilderExtensions.cs
src/Azure/Orleans.Persistence.AzureStorage/Hosting/AzureTableSiloBuilderExtensions.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorage.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/AzureTableTransactionalStateStorageFactory.cs
src/Orleans.Core/Configuration/OptionLogger/DefaultOptionsFormatter.cs
src/Orleans.Core/Configuration/OptionsOverrides.cs
src/Orleans.Core/Streams/PersistentStreams/PersistentStreamProvider.cs
src/Orleans.Core/Streams/SimpleMessageStream/SimpleMessageStreamProvider.cs
src/Orleans.Core/Utils/NamedOptionExtension.cs
src/Orleans.EventSourcing/CustomStorage/LogConsistencyProvider.cs
src/Orleans.Runtime/Configuration/Validators/EndpointOptionsValidator.cs
src/Orleans.Runtime/Silo/Silo.cs
src/Orleans.Runtime/Streams/QueueBalancer/DeploymentBasedQueueBalancer.cs
src/Orleans.Runtime/Streams/QueueBalancer/LeaseBasedQueueBalancer.cs
src/Orleans.Runtime/Streams/QueueBalancer/PersistentStreamConfiguratorExtension.cs
src/Orleans.TestingHost/TestCluster.cs
src/Orleans.TestingHost/TestStorageProviders/FaultInjectionStorageProvider.cs
src/Orleans.Transactions.TestkitBase/FaultInjection/ControlledInjection/FaultInjectionAzureTableTransactionStateStorage.cs
src/OrleansProviders/Storage/MemoryStorage.cs
src/OrleansProviders/Streams/Generator/Generators/SimpleGeneratorConfig.cs
test/Extensions/TesterAzureUtils/Streaming/AzureQueueAdapterTests.cs
test/Tester/LogFomatterTests.cs

Fix DI scope issue in azure blob

---

src/Orleans.Core/Logging/ErrorCodes.cs
src/Orleans.Core/Messaging/ClientMessageCenter.cs
src/Orleans.Core/Messaging/GatewayManager.cs
test/TesterInternal/GatewaySelectionTest.cs

On the client, close gateway connection to dead silos

---

src/Orleans.Core/Logging/ErrorCodes.cs
src/Orleans.Core/Messaging/ClientMessageCenter.cs
src/Orleans.Core/Messaging/GatewayManager.cs
test/TesterInternal/GatewaySelectionTest.cs

On the client, close gateway connection to dead silos (#5561)

Cherry-pick #5561 for 2.3.2

---

src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
src/Orleans.Core/CodeGeneration/IGrainState.cs
src/Orleans.EventSourcing/LogStorage/LogStateWithMetaData.cs
src/Orleans.EventSourcing/StateStorage/GrainStateWithMetaData.cs
src/OrleansProviders/Storage/MemoryStorageGrain.cs
test/DefaultCluster.Tests/MemoryStorageProviderTests.cs

Fixes #5569 
The change has been tested in a real cluster.

Prevent NullReferenceException with some storage providers when state is Nullable<T>

---

src/Orleans.Core/Async/TaskExtensions.cs

Fixes #5565
When a `Task` returns `null`, that value cannot be cast to `T` using a hard-cast because that will cause a `NullReferenceException`.
Also adds `ConfigureAwait(false)` inside some private Task helpers for cleanliness.
I am hoping this builds on the build servers, but the `is` syntax I'm using may not be supported there.
cc @SebastianStehle

Fix #5565 - NullReferenceException caused by call filter

---

Orleans.sln
Test.cmd
src/Orleans.Analyzers/AlwaysInterleaveDiagnosticAnalyzer.cs
src/Orleans.Analyzers/Orleans.Analyzers.csproj
test/Analyzers.Tests/AlwaysInterleaveDiagnosticAnalyzerTests.cs
test/Analyzers.Tests/Analyzers.Tests.csproj
test/Analyzers.Tests/Analyzers.Tests.xunit.runner.json
test/Analyzers.Tests/DiagnosticAnalyzerTestBase.cs

- Setup basic Analyzer project
- Setup basic Tests project
- Create analyzer for AlwaysInterleaveAttribute

Add Analyzers to Orleans

---

src/Orleans.CodeGenerator/Compatibility/OrleansLegacyCompat.cs
src/Orleans.CodeGenerator/Utilities/SymbolExtensions.cs
test/CodeGeneration/CodeGenerator.Tests/RoslynTypeNameFormatterTests.cs

Should hopefully fix #5482. I'm going to do some testing locally using this build of the code generator to see if it does solve the issue.

Improve Roslyn TypeCode generation

---

Directory.Build.props
src/Orleans.Transactions.Testkit.Xunit/Orleans.Transactions.Testkit.Xunit.csproj
test/Analyzers.Tests/Analyzers.Tests.csproj
test/CodeGeneration/CodeGenerator.Tests/CodeGenerator.Tests.csproj
test/DefaultCluster.Tests/DefaultCluster.Tests.csproj
test/DependencyInjection.Tests/DependencyInjection.Tests.csproj
test/Directory.Build.props
test/Extensions/AWSUtils.Tests/AWSUtils.Tests.csproj
test/Extensions/Consul.Tests/Consul.Tests.csproj
test/Extensions/PSUtils.Tests/PSUtils.Tests.csproj
test/Extensions/Serializers/BondUtils.Tests/BondUtils.Tests.csproj
test/Extensions/Serializers/GoogleUtils.Tests/GoogleUtils.Tests.csproj
test/Extensions/Serializers/ProtoBuf.Serialization.Tests/ProtoBuf.Serialization.Tests.csproj
test/Extensions/ServiceBus.Tests/ServiceBus.Tests.csproj
test/Extensions/TestServiceFabric/TestServiceFabric.csproj
test/Extensions/TesterAdoNet/Tester.AdoNet.csproj
test/Extensions/TesterAzureUtils/Tester.AzureUtils.csproj
test/Extensions/TesterZooKeeperUtils/Tester.ZooKeeperUtils.csproj
test/NetCore.Tests/NetCore.Tests.csproj
test/NetCore.Tests/NetCore.Tests.xunit.runner.json
test/NonSilo.Tests/NonSilo.Tests.csproj
test/RuntimeCodeGen.Tests/RuntimeCodeGen.Tests.csproj
test/TestInfrastructure/Orleans.TestingHost.Tests/Orleans.TestingHost.Tests.csproj
test/Tester/Tester.csproj
test/TesterInternal/TesterInternal.csproj
test/Transactions/Orleans.Transactions.Azure.Test/Orleans.Transactions.Azure.Test.csproj
test/Transactions/Orleans.Transactions.Tests/Orleans.Transactions.Tests.csproj

The version of the `dotnet-xunit` package diverged from the main `xunit` package

Update xUnit & fix minor test project issues

---

src/Orleans.Core/Runtime/CallbackData.cs

Contention on this lock was apparent while profiling load tests

Remove lock from CallbackData

---

src/Orleans/Streams/PersistentStreams/StreamConsumerCollection.cs
src/OrleansRuntime/Streams/PersistentStream/PersistentStreamPullingAgent.cs

Please manually compare diff in https://github.com/dotnet/orleans/pull/5354/files
and https://github.com/dotnet/orleans/pull/5372/files
to see if I made the right change

Port Pr 5354 and 5372 to 1.5.8

---

test/Extensions/ServiceBus.Tests/Streaming/EHClientStreamTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHSubscriptionMultiplicityTests.cs
test/Extensions/TesterAzureUtils/Persistence/PersistenceGrainTests_AzureBlobStore.cs
test/Extensions/TesterAzureUtils/Streaming/AQStreamingTests.cs
test/Tester/CancellationTests/GrainCancellationTokenTests.cs
test/Tester/StreamingTests/ProgrammaticSubscribeTests/ProgrammaticSubcribeTestsRunner.cs
test/Tester/StreamingTests/StreamBatchingTestRunner.cs

EHMultipleSubscriptionTest_AddRemove AQ_07_ManyDifferent_ManyProducerClientsManyConsumerGrains
SingleSendBatchConsume
StreamingTests_Consumer_Producer_SubscribeToTwoStream_MessageWithPolymorphism
Grain_AzureBlobStore_SiloRestart

Skip more intermittently failing tests

---

src/Orleans.Core/Async/TaskExtensions.cs
test/DefaultCluster.Tests/EchoTaskGrainTests.cs
test/Grains/TestGrainInterfaces/IEchoTaskGrain.cs
test/Grains/TestInternalGrains/EchoTaskGrain.cs

Fix Nullable<T>

---

src/Orleans.Core/Async/TaskExtensions.cs
test/DefaultCluster.Tests/EchoTaskGrainTests.cs
test/Grains/TestGrainInterfaces/IEchoTaskGrain.cs
test/Grains/TestInternalGrains/EchoTaskGrain.cs

(cherry picked from commit f698e348da6cda9f2437b0e87b2858ba0d9acf30)

Cherry-pick #5663 "Fix Nullable<T>" for 2.3.4

---

Directory.Build.props
src/AWS/Orleans.Persistence.DynamoDB/Options/DynamoDBStorageOptions.cs
src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
src/AdoNet/Orleans.Persistence.AdoNet/Options/AdoNetGrainStorageOptions.cs
src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorage.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorageOptions.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorageOptions.cs
src/Orleans.Core/Serialization/OrleansJsonSerializer.cs
src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
src/Orleans.Runtime/Hosting/GrainCallFilterExtensions.cs
src/Orleans.Runtime/MembershipService/MembershipOracle.cs
src/Orleans.Transactions/State/ReaderWriterLock.cs
src/Orleans.Transactions/State/TransactionalStateOptions.cs

Fixes #5661 by allowing configuration to pass in value of MetadataPro… (#5662)
Make transaction log group max size configurable (#5656)
Reduce delay local directory when cluster membership is not stable (#5677)

Cherry-picked fixes for 2.3.5

---

src/Orleans.CodeGenerator/Analysis/CompilationAnalyzer.cs
test/Grains/TestGrainInterfaces/RecursiveType.cs

Fix #5473 - StackOverflowException in codegen for recursively defined types

---

src/Orleans.CodeGenerator.MSBuild/CodeGeneratorCommand.cs

CodeGenerator: skip empty projects

---

test/NonSilo.Tests/Serialization/MessageSerializerTests.cs

Skip flaky MessageTest_TtlUpdatedOnSerialization test

---

src/Orleans.Core/Lifecycle/LifecycleSubject.cs
src/Orleans.Runtime/Catalog/GrainLifecycle.cs
src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs

Log lifecycle levels using stage names rather than numeric values.
Use structured logging

Improve lifecycle logging

---

src/AWS/Shared/Storage/DynamoDBStorage.cs

**Symptom**
Not all registered reminders were received when having a large set of registered reminders in a DynamoDBReminderTable.
**Reason**
DynamoDBReminderTable.ReadRows calls DynamobDBStorage.ScanAsync which in turn calls AmazonDynamoDBClient.ScanAsync once. Calling AmazonDynamoDBClient.ScanAsync only once is the problem, because in certain cases it bails out and needs to be called again to continue the scan from where it left off. Those cases are listed here: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/MDynamoDBScanAsyncScanRequestCancellationToken.html
**Solution**
Call AmazonDynamoDBClient.ScanAsync until the scan has completed.

Fixed reminder issue.

---

src/Orleans.Transactions/Hosting/SiloBuilderExtensions.cs

Fixes #5742
Reported by @Ilchert [via gitter](https://gitter.im/dotnet/orleans?at=5d249f5f17cc7b05ca9be318).

Configure application parts in UseTransactions

---

src/Orleans.TestingHost/TestCluster.cs

Some of our tests modify the test cluster during operation & this can result in an exception like the following:

Fix concurrency bug in TestCluster

---

src/Orleans.Core/Configuration/Options/MessagingOptions.cs
src/Orleans.Core/Messaging/Message.cs
src/Orleans.Core/Networking/ClientOutboundConnection.cs
src/Orleans.Core/Runtime/CallbackData.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
src/Orleans.Core/Runtime/SharedCallbackData.cs
src/Orleans.Runtime/Core/Dispatcher.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
src/Orleans.Runtime/Networking/GatewayInboundConnection.cs
src/Orleans.Runtime/Networking/SiloConnection.cs

Resolves #5667.
Automatic message resend was a bad idea. We forgot to remove the logic in 2.0.

Remove options and logic for automatic resending of messages

---

src/Orleans.Core/Runtime/CallbackData.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs

Fix potential NullReferenceException in CallbackData

---

src/TelemetryConsumers/Orleans.TelemetryConsumers.Counters/Statistics/HostBuilderExtensions.cs

Add UsePerfCounterEnvironmentStatistics overload for ISiloBuilder

---

src/Orleans.Core/Streams/Internal/StreamSubscriptionHandleImpl.cs
test/Grains/TestGrains/MultipleSubscriptionConsumerGrain.cs

Fixed bug in SMS streams where events were not being delivered to batch observers.

SMS streams batch delivered fix

---

src/Orleans.Core/Runtime/MembershipTableSnapshot.cs
src/Orleans.Runtime/MembershipService/ClusterHealthMonitor.cs
src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
test/NonSilo.Tests/Membership/ClusterHealthMonitorTests.cs
test/NonSilo.Tests/Membership/MembershipAgentTests.cs
test/NonSilo.Tests/Membership/MembershipTableManagerTests.cs
test/NonSilo.Tests/Membership/MembershipTableSnapshotTests.cs

Remove LocalSilo from MembershipTableSnapshot. Detect death in gossip

---

src/Orleans.Core/Streams/Internal/StreamSubscriptionHandleImpl.cs

Fixed bug preventing OnError from being called on batch consumers.

---

test/Tester/StreamingTests/SubscriptionMultiplicityTestRunner.cs

At least two tests fail frequently because of this

Fix *ActiveSubscriptionTest sequencing

---

src/Orleans.Runtime/Networking/SiloConnectionMaintainer.cs

This is expected to slightly reduce the noise while a silo is shutting down

Wait before aborting connections to defunct silos

---

src/Orleans.Core/Networking/Connection.cs

Use simple await in Connection

---

src/Orleans.Runtime/Core/HostedClient.cs

Use simple await in HostedClient.RunClientMessagePump

---

src/Orleans.Runtime/GrainDirectory/AdaptiveDirectoryCacheMaintainer.cs
src/Orleans.Runtime/GrainDirectory/AdaptiveGrainDirectoryCache.cs
src/Orleans.Runtime/GrainDirectory/GrainDirectoryCacheFactory.cs
src/Orleans.Runtime/GrainDirectory/IGrainDirectoryCache.cs
src/Orleans.Runtime/GrainDirectory/LRUBasedGrainDirectoryCache.cs
src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs

Remove generics from grain directory caching

---

src/Orleans.Core.Abstractions/Concurrency/GrainAttributeConcurrency.cs
src/Orleans.Core/DistributedTracing/EventSourceEvents.cs
src/Orleans.Core/DistributedTracing/TraceContext.cs
src/Orleans.Core/Messaging/Message.cs
src/Orleans.Core/Messaging/MessageFactory.cs
src/Orleans.Core/Runtime/CallbackData.cs
src/Orleans.Core/Runtime/GrainReferenceRuntime.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
src/Orleans.Runtime/Core/Dispatcher.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
src/Orleans.Runtime/DistributedTracing/EventSourceEvents.cs
src/Orleans.Runtime/Messaging/GatewayAcceptor.cs
src/Orleans.Runtime/Messaging/IncomingMessageAcceptor.cs
src/Orleans.Runtime/Messaging/IncomingMessageAgent.cs

(cherry picked from commit a8abc360d572246a794cb14ff594656c275fe0e1)

Cherry-pick #5691 (Add core tracing events) for 2.4.0

---

src/Orleans.Core/Configuration/Options/ClientMessagingOptions.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs

added ClientMessagingOptions.LocalAddress to specify cluster client binding address

---

src/Orleans.Core/Runtime/MembershipTableSnapshot.cs
src/Orleans.Runtime/MembershipService/ClusterMembershipService.cs
src/Orleans.Runtime/MembershipService/MembershipSystemTarget.cs
src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
src/Orleans.Runtime/MembershipService/SiloStatusListenerManager.cs

Fix for Clustering providers that does not implement extended Membership Protocol

---

Directory.Build.props

To make the default version higher than the last published release.

Increase VersionPrefix to 2.5.0

---

test/Tester/EventSourcingTests/AccountGrainTests.cs

Skip flaky AccountWithLog EventSourcing test

---

src/Orleans.Runtime/Messaging/IncomingMessageAcceptor.cs

Remove pooling of `SocketAsyncEventArg`s. We suspect there's a bug there that occasionally leads to corruption of read data.

[@ReubenBond] [2.4.2] Remove SAEA pooling

---

src/Orleans.Core/Configuration/Options/MessagingOptions.cs
src/Orleans.Core/Core/DefaultClientServices.cs
src/Orleans.Core/Messaging/MessageSerializer.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
test/NonSilo.Tests/Serialization/MessageSerializerTests.cs

Add hard limits for message header and body size

---

src/Orleans.Core/Async/BatchWorker.cs
src/Orleans.Core/Timers/TimerManager.cs
src/Orleans.Transactions/State/ActivationLifetime.cs
src/Orleans.Transactions/State/ConfirmationWorker.cs
src/Orleans.Transactions/State/ReaderWriterLock.cs
src/Orleans.Transactions/State/TransactionQueue.cs

Cherry pick from #5887 for 2.4.2

[2.4.2] Improve graceful deactivation of grains performing transaction work

---

src/Azure/Orleans.Hosting.AzureCloudServices/QueueBalancers/AzureDeploymentQueueBalancer.cs
src/Azure/Orleans.Streaming.AzureStorage/Hosting/SiloBuilderExtensions.cs
src/Azure/Orleans.Streaming.AzureStorage/Options/AzureBlobLeaseProviderOptions.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Lease/AzureBlobLeaseProvider.cs
src/Orleans.Core/Streams/PersistentStreams/IStreamQueueBalancer.cs
src/Orleans.Runtime/Streams/PersistentStream/PersistentStreamPullingManager.cs
src/Orleans.Runtime/Streams/QueueBalancer/ConsistentRingQueueBalancer.cs
src/Orleans.Runtime/Streams/QueueBalancer/DeploymentBasedQueueBalancer.cs
src/Orleans.Runtime/Streams/QueueBalancer/IResourceSelector.cs
src/Orleans.Runtime/Streams/QueueBalancer/LeaseBasedQueueBalancer.cs
src/Orleans.Runtime/Streams/QueueBalancer/LeaseBasedQueueBalancerOptions.cs
src/Orleans.Runtime/Streams/QueueBalancer/PersistentStreamConfiguratorExtension.cs
src/Orleans.Runtime/Streams/QueueBalancer/QueueBalancerBase.cs
src/Orleans.Runtime/Streams/QueueBalancer/QueueBalancerBaseClass.cs
src/Orleans.Runtime/Streams/QueueBalancer/RoundRobinSelector.cs
src/Orleans.TestingHost/TestCluster.cs
test/Extensions/TesterAzureUtils/Lease/AzureBlobLeaseProviderTests.cs
test/Extensions/TesterAzureUtils/Lease/LeaseBasedQueueBalancerTests.cs
test/NonSilo.Tests/OrleansRuntime/Streams/RoundRobinSelectorTests.cs
test/Tester/StreamingTests/PlugableQueueBalancerTests/LeaseBasedQueueBalancer.cs

No longer uses deployment configuration.
Serialize changes to avoid interleaving.
More configuration options.
Conformed configuration patterns to Orleans common patterns, including replacing the azure blob lease settings with options.

Lease based queue balancer refactor.

---

src/Orleans.Runtime/MembershipService/SiloHealthMonitor.cs

In the case that multiple probe attempts fail in a short period of time we should not attempt to mark the silo as dead multiple times concurrently

ClusterHealthMonitor: ignore superseded probes

---

src/Orleans.Core/Messaging/ClientMessageCenter.cs
src/Orleans.Core/Messaging/GatewayManager.cs
src/Orleans.Core/Networking/Connection.cs
src/Orleans.Core/Networking/ConnectionFactory.cs
src/Orleans.Core/Networking/ConnectionManager.cs
src/Orleans.Runtime/Messaging/Gateway.cs

This PR (#5893) appears to have destabilized our reliability tests. Let's revert and redo it.

Revert "Bound retries for failed send in ClientMessageCenter and simplify (#5893)"

---

Directory.Build.props
src/Orleans.Analyzers/AlwaysInterleaveDiagnosticAnalyzer.cs
src/Orleans.CodeGenerator/Compatibility/OrleansLegacyCompat.cs

Update Microsoft.CodeAnalysis packages

---

Samples/OneBoxDeployment/src/OneBoxDeployment.Api/OneBoxDeployment.Api.csproj
Samples/OneBoxDeployment/src/OneBoxDeployment.GrainInterfaces/OneBoxDeployment.GrainInterfaces.csproj
Samples/OneBoxDeployment/src/OneBoxDeployment.Grains/OneBoxDeployment.Grains.csproj
Samples/OneBoxDeployment/src/OneBoxDeployment.OrleansHost/OneBoxDeployment.OrleansHost.csproj
Samples/OneBoxDeployment/src/OneBoxDeployment.OrleansUtilities/OneBoxDeployment.OrleansUtilities.csproj
Samples/OneBoxDeployment/src/OneBoxDeployment.Utilities/OneBoxDeployment.Utilities.csproj
Samples/OneBoxDeployment/test/OneBoxDeployment.IntegrationTests/OneBoxDeployment.IntegrationTests.csproj

Just updates the OneBoxDeployment Nuget libraries to the newest ones. The tests pass.

Updates  OneBoxDeployment Nuget libraries

---

src/Orleans.Runtime/MembershipService/IMembershipOracle.cs

Remove unused IMembershipOracle interface

---

src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/MembershipService/ClusterHealthMonitor.cs
src/Orleans.Runtime/MembershipService/MembershipAgent.cs
src/Orleans.Runtime/MembershipService/MembershipTableCleanupAgent.cs
src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
src/Orleans.Runtime/Scheduler/OrleansTaskScheduler.cs
src/Orleans.Runtime/Silo/Silo.cs
src/Orleans.Runtime/Timers/AsyncTimer.cs

Add additional internal health checks for membership

---

src/Orleans.Core.Abstractions/Streams/Predicates/RegexStreamNamespacePredicate.cs
test/Grains/TestGrains/GeneratedEventCollectorGrain.cs

Add serializer for RegexStreamNamespacePredicate

---

src/Orleans.Runtime/ConsistentRing/ConsistentRingProvider.cs
src/Orleans.Runtime/ConsistentRing/VirtualBucketsRingProvider.cs
src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
src/Orleans.TestingHost/Utils/AsyncResultHandle.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests.cs
test/TesterInternal/GeoClusterTests/MultiClusterRegistrationTests.cs

Remove most instances of MarshalByRefObject

---

src/Orleans.TestingHost/TestClusterBuilder.cs

Make TestClusterBuilder.AddSiloBuilderConfigurator and TestClusterBuilder.AddClientBuilderConfigurator fluent style APIs

---

src/Orleans.CodeGenerator/Generators/GrainMethodInvokerGenerator.cs
src/Orleans.Core/Core/InterfaceToImplementationMappingCache.cs
test/Grains/Directory.Build.props
test/Grains/TestGrainInterfaces/IMethodInterceptionGrain.cs
test/Grains/TestGrains/MethodInterceptionGrain.cs
test/Tester/GrainCallFilterTests.cs

Improve MethodInfo resolution for grain call filters

---

test/Grains/TestGrainInterfaces/CodegenTestInterfaces.cs

Add regression test for #5243

---

src/Orleans.Core/DistributedTracing/TraceContext.cs
src/Orleans.Core/Streams/QueueAdapters/BatchContainerBatch.cs
src/Orleans.Transactions.TestkitBase/Grains/ITransactionAttributionGrain.cs
src/Orleans.Transactions/DistributedTM/ParticipantId.cs
test/Grains/TestGrains/ProgrammaticSubscribe/TypedProducerGrain.cs
test/Grains/TestGrains/ReentrancyCorrelationIdGrains.cs

These are being masked by the presence of the ILBasedFallbackSerializer

Add missing serializers on internal types

---

src/Orleans.CodeGenerator/Generators/GrainInterfaceCommon.cs

Avoid generating duplicate method id switch labels

---

src/Orleans.Core/Networking/ConnectionManager.cs
src/Orleans.Runtime/Networking/ConnectionListener.cs

Fixing in response to feedback from @davidfowl

Simplify ConnectionListener.RunAsync

---

src/Orleans.Core/Core/ClientBuilderExtensions.cs
src/Orleans.Core/Core/DefaultClientServices.cs
src/Orleans.Core/DistributedTracing/TraceContext.cs
src/Orleans.Core/Streams/QueueAdapters/BatchContainerBatch.cs
src/Orleans.Runtime.Abstractions/Hosting/Generic/SiloHostBuilderExtensions.cs
src/Orleans.Runtime.Abstractions/Hosting/SiloBuilderExtensions.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Transactions.TestkitBase/Grains/ITransactionAttributionGrain.cs
src/Orleans.Transactions/DistributedTM/ParticipantId.cs
test/Grains/TestGrains/ProgrammaticSubscribe/TypedProducerGrain.cs
test/Grains/TestGrains/ReentrancyCorrelationIdGrains.cs

We will re-address this in 3.1.0 time frame with additional modifications to support rolling-upgrade from older versions
See #6009
See #6018
Re-opens #5729
Please rebase on top of master

Revert #6009 & #6018

---

src/Documentation/grains/external_tasks_and_grains.md

... with async delegates. Fixes #5977

Add section on use of Task.Factory.StartNew()

---

src/OrleansProviders/Storage/MemoryStorage.cs
src/OrleansProviders/Storage/MemoryStorageGrain.cs
src/OrleansProviders/Streams/Common/PooledCache/ChronologicalEvictionStrategy.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCache.cs
src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCacheCursor.cs
src/OrleansProviders/Streams/Generator/GeneratorAdapterFactory.cs
src/OrleansProviders/Streams/Memory/MemoryAdapterFactory.cs
src/OrleansProviders/Streams/Memory/MemoryAdapterReceiver.cs

Implemented structured logging (see #5865) for the project OrleansProviders. Doing it project by project makes it a bit more manageable than to do the whole lot in one changeset.

Added structured logging

---

src/Documentation/grains/grain_persistence/index.md

Clarified docs about Azure Table Storage Limits

---

src/Orleans.Clustering.Consul/ConsulBasedMembershipTable.cs
test/Extensions/Consul.Tests/ConsulMembershipTableTest.cs
test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs

Implemented IMembershipTable.CleanupDefunctSiloEntries for Consul.
Fixes #5546.

Implement CleanupDefunctSiloEntries for Consul membership provider

---

src/Documentation/implementation/streams_implementation.md

just a few improvements to the doc to aid readability

Update streams_implementation.md - spelling, format and readability

---

README.md

Trying to remove entropy from this here universe.

Fix spelling error.

---

src/Documentation/grains/event_sourcing/event_sourcing_configuration.md

wrapped in code block of `Grain Class Attributes` section.

warpped in code block.

---

src/AWS/Orleans.Streaming.SQS/Streams/SQSAdapter.cs

"currebtly" changed to "currently"

Fixed typo in exception

---

src/Orleans.Clustering.Consul/ConsulBasedMembershipTable.cs
src/Orleans.Clustering.Consul/ConsulGatewayListProvider.cs
src/Orleans.Clustering.Consul/SerializableMembershipTypes.cs
test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs

Implements the extended membership protocol (with monotonic versioning) for Consul.
Should fix #6089 - needs verification

Consul: support extended membership protocol

---

Samples/OneBoxDeployment/Readme.md

Fix small typo in readme

---

src/Documentation/grains/event_sourcing/journaledgrain_basics.md

Removes extra angle bracket in `<JournaledGrain<StateType,EventType>`

Removing Extra Angle Bracket

---

src/Documentation/grains/event_sourcing/event_sourcing_configuration.md

Adds some missing ticks on the page

Adding Missing Ticks

---

src/Documentation/grains/grain_persistence/index.md

Fix an error in storage provider name.
Add a second provider for cart store.

Improve persistence doc page

---

Samples/3.0/HelloWorld/BuildAndRun.ps1
Samples/3.0/HelloWorld/BuildAndRun.sh
Samples/3.0/HelloWorld/HelloWorld.sln
Samples/3.0/HelloWorld/Readme.md
Samples/3.0/HelloWorld/src/HelloWorld.Grains/HelloArchiveGrain.cs
Samples/3.0/HelloWorld/src/HelloWorld.Grains/HelloGrain.cs
Samples/3.0/HelloWorld/src/HelloWorld.Grains/HelloWorld.Grains.csproj
Samples/3.0/HelloWorld/src/HelloWorld.Interfaces/HelloWorld.Interfaces.csproj
Samples/3.0/HelloWorld/src/HelloWorld.Interfaces/IHello.cs
Samples/3.0/HelloWorld/src/HelloWorld.Interfaces/IHelloArchive.cs
Samples/3.0/HelloWorld/src/OrleansClient/ClusterClientHostedService.cs
Samples/3.0/HelloWorld/src/OrleansClient/HelloWorldClientHostedService.cs
Samples/3.0/HelloWorld/src/OrleansClient/OrleansClient.csproj
Samples/3.0/HelloWorld/src/OrleansClient/Program.cs
Samples/3.0/HelloWorld/src/SiloHost/Program.cs
Samples/3.0/HelloWorld/src/SiloHost/SiloHost.csproj

Switch HelloWorld to using IPersistentState instead of Grain<T>.
Add configuration of a storage provider.
Add grain calls for IHelloArchive grain to excercise persistence.

Migrate HelloWorld sample to 3.0

---

src/Documentation/clusters_and_clients/configuration_guide/adonet_configuration.md
src/Documentation/clusters_and_clients/configuration_guide/toc.yml

Add information about Shared/Main SQL scripts

---

src/Orleans.Core/CodeGeneration/GrainInterfaceUtils.cs
test/Grains/TestGrainInterfaces/IMethodInterceptionGrain.cs
test/NonSilo.Tests/General/TypeCodeOverrideTests.cs

That need to be cherry-picked into 2.4 branch. BTW, what is the workflow for merging PRs into multiple branches? Should I create another PR or is that done only by maintainers?

Allow negative values in TypeCodeAttribute. Fixes #6114

---

src/Orleans.Core/Networking/Shared/SocketConnectionFactory.cs

Specify endpoint AddressFamily in Socket constructor

---

Samples/3.0/Presence/BuildAndRun.ps1
Samples/3.0/Presence/BuildAndRun.sh
Samples/3.0/Presence/Presence.sln
Samples/3.0/Presence/readme.md
Samples/3.0/Presence/src/Grains.Interfaces/Grains.Interfaces.csproj
Samples/3.0/Presence/src/Grains.Interfaces/IGameGrain.cs
Samples/3.0/Presence/src/Grains.Interfaces/IGameObserver.cs
Samples/3.0/Presence/src/Grains.Interfaces/IPlayerGrain.cs
Samples/3.0/Presence/src/Grains.Interfaces/IPresenceGrain.cs
Samples/3.0/Presence/src/Grains.Interfaces/Models/GameStatus.cs
Samples/3.0/Presence/src/Grains.Interfaces/Models/HeartbeatData.cs
Samples/3.0/Presence/src/Grains.Interfaces/Models/HeartbeatDataDotNetSerializer.cs
Samples/3.0/Presence/src/Grains/GameGrain.cs
Samples/3.0/Presence/src/Grains/Grains.csproj
Samples/3.0/Presence/src/Grains/PlayerGrain.cs
Samples/3.0/Presence/src/Grains/PresenceGrain.cs
Samples/3.0/Presence/src/LoadGenerator/CancellationTokenExtensions.cs
Samples/3.0/Presence/src/LoadGenerator/LoadGenerator.csproj
Samples/3.0/Presence/src/LoadGenerator/LoadGeneratorHostedService.cs
Samples/3.0/Presence/src/LoadGenerator/Program.cs
Samples/3.0/Presence/src/PlayerWatcher/LoggerGameObserver.cs
Samples/3.0/Presence/src/PlayerWatcher/PlayerWatcher.csproj
Samples/3.0/Presence/src/PlayerWatcher/PlayerWatcherHostedService.cs
Samples/3.0/Presence/src/PlayerWatcher/Program.cs
Samples/3.0/Presence/src/Shared/ClusterClientHostedService.cs
Samples/3.0/Presence/src/Silo/Program.cs
Samples/3.0/Presence/src/Silo/Silo.csproj

All the references and code have been updated and now the sample is working with Orleans 3.0
I added a new "Presence" folder to /Samples/3.0

Updated Presence Sample added to Samples/3.0 folder

---

src/Orleans.Core/Networking/ConnectionManagerLifecycleAdapter.cs
src/Orleans.Runtime/Networking/GatewayConnectionListener.cs
src/Orleans.Runtime/Networking/SiloConnectionListener.cs

Close ConnectionManager later in shutdown stage

---

src/Orleans.Core/Messaging/GatewayManager.cs
src/Orleans.Core/Messaging/IGatewayListProvider.cs

Also minor cleanup to use async instead of blocking calls
Fixes #6177

Obsolete IGatewayListProvider.IsUpdatable

---

src/AdoNet/Shared/Storage/AdoNetInvariants.cs
src/AdoNet/Shared/Storage/DbConnectionFactory.cs
src/AdoNet/Shared/Storage/DbConstantsStore.cs

Add support Microsoft.Data.SqlClient provider, fix #6229

---

src/Orleans.CodeGenerator.MSBuild/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets

Fix codegen incremental rebuild

---

src/Orleans.Core/Configuration/Options/ClusterMembershipOptions.cs
src/Orleans.Runtime/MembershipService/ClusterHealthMonitor.cs
src/Orleans.Runtime/MembershipService/ClusterMembershipService.cs
src/Orleans.Runtime/MembershipService/MembershipAgent.cs
src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
src/Orleans.Runtime/MembershipService/SiloStatusListenerManager.cs
src/Orleans.Runtime/Streams/QueueBalancer/QueueBalancerBase.cs

Also use `await foreach` instead of our manually coded solution

Membership: allow a minimum grace period during ungraceful shutdown

---

src/AWS/Shared/Storage/DynamoDBStorage.cs

Adds support for `PAY_PER_REQUEST` `BillingMode` for DynamoDB if you set `ReadCapacityUnits` and `WriteCapacityUnits` to `0`

Add support for DynamoDB Pay Per Request Billing Mode

---

Samples/3.0/HelloWorld/src/SiloHost/SiloHost.csproj

Add missing reference to Microsoft.Orleans.Persistence.AzureStorage package

---

src/Orleans.Core/Logging/ErrorCodes.cs
src/TelemetryConsumers/Orleans.TelemetryConsumers.Linux/HostBuilderExtensions.cs

Added OS Error Code
Replaced throwing Exception to Logger.Warn

Replaced throwing Exception to Logger.Warn

---

src/Orleans.CodeGenerator/Orleans.CodeGenerator.csproj
src/Orleans.Core.Abstractions/Orleans.Core.Abstractions.csproj

Add System.Threading.Tasks.Extensions dependency to Abstractions

---

src/Orleans.Connections.Security/Hosting/HostingExtensions.IClientBuilder.cs
src/Orleans.Connections.Security/Security/TlsClientConnectionMiddleware.cs
src/Orleans.Connections.Security/Security/TlsOptions.cs
test/Orleans.Connections.Security.Tests/CertificateCreator.cs
test/Orleans.Connections.Security.Tests/TlsConnectionTests.cs

Added ability to skip client TLS authentication.

---

src/Documentation/grains/grain_placement.md
src/Documentation/grains/toc.yml
src/Documentation/index.md

Show the minimum amount required to add a custom placement strategy, and link to another example in the main Orleans code repo

Add summary documentation for custom grain placements

---

src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Networking/GatewayConnectionListener.cs
test/DependencyInjection.Tests/Autofac/DependencyInjectionGrainTestsUsingAutofac.cs

Avoid registering Gateway in DI since it can be null

---

src/Documentation/implementation/streams_implementation/azure_queue_streams.md

Update the doc to Orleans 3.0.2. Previous code was for Orleans 2.4.x

Azure queue streams configuration for Orleans 3.0.2

---

src/Orleans.Core.Abstractions/GrainDirectory/IGrainDirectory.cs
src/Orleans.Core/GrainDirectory/IGrainLocator.cs
src/Orleans.Core/GrainDirectory/IInClusterGrainDirectory.cs
src/Orleans.Core/SystemTargetInterfaces/IRemoteGrainDirectory.cs
src/Orleans.Runtime/Catalog/Catalog.cs
src/Orleans.Runtime/Core/Dispatcher.cs
src/Orleans.Runtime/GrainDirectory/GrainLocator.cs
src/Orleans.Runtime/GrainDirectory/GrainLocatorFactory.cs
src/Orleans.Runtime/GrainDirectory/ILocalGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/InClusterGrainLocator.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Placement/ClientObserversPlacementDirector.cs
src/Orleans.Runtime/Placement/IPlacementRuntime.cs
src/Orleans.Runtime/Placement/RandomPlacementDirector.cs
test/Grains/TestInternalGrains/TestGrain.cs

Out of scope for this PR;
- Per grain type directory (will come in another PR)
- CosmosDB implementation

Basic support for pluggable grain directory

---

src/Documentation/clusters_and_clients/index.md
src/Documentation/implementation/toc.yml

Expand documentation on client connectivity and dependency injection.

---

src/Orleans.Runtime/Catalog/Catalog.cs
src/Orleans.Runtime/Core/SystemTarget.cs
src/Orleans.Runtime/GrainDirectory/ClientObserverRegistrar.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/ReminderService/LocalReminderService.cs
src/Orleans.Runtime/Silo/Silo.cs
src/Orleans.Runtime/Timers/GrainTimer.cs

Avoid using GrainTimer in non-grain contexts

---

src/Orleans.Core.Abstractions/GrainDirectory/IGrainDirectory.cs
src/Orleans.Core/GrainDirectory/IDhtGrainDirectory.cs
src/Orleans.Core/SystemTargetInterfaces/IRemoteGrainDirectory.cs
src/Orleans.Runtime/Catalog/Catalog.cs
src/Orleans.Runtime/GrainDirectory/DhtGrainLocator.cs
src/Orleans.Runtime/GrainDirectory/GrainLocator.cs
src/Orleans.Runtime/GrainDirectory/GrainLocatorFactory.cs
src/Orleans.Runtime/GrainDirectory/ILocalGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/InClusterGrainLocator.cs

Add UnregisterMany to IGrainDirectory to support batch unregistrations.
Rename InCluster to Dht.
This is a followup to #6340.

Add UnregisterMany to IGrainDirectory to support batch unregistrations 

---

Directory.Build.props
src/TelemetryConsumers/Orleans.TelemetryConsumers.Counters/Orleans.TelemetryConsumers.Counters.csproj

Update performance counter dependencies

---

src/Documentation/grains/timers_and_reminders.md

IOrleansReminder has been renamed IGrainReminder

Reflect interface name change in docs

---

src/Orleans.Runtime/Scheduler/WorkItemGroup.cs

This is always logging "System.Threading.Thread" now

Fix log message

---

src/Azure/Orleans.Streaming.AzureStorage/Storage/AzureQueueDataManager.cs

Addresses intermittent test failure - https://github.com/dotnet/orleans/issues/6416

Ignore not foud exception when clearing azure queues

---

src/Orleans.Runtime/MembershipService/MembershipTableCleanupAgent.cs
src/Orleans.Runtime/ReminderService/LocalReminderService.cs

MembershipTableCleanupAgent: dispose timer if cleanup is unsupported

---

src/Documentation/clusters_and_clients/configuration_guide/client_configuration.md

Added nuget package that should be used with the client along with the using statement in the code.

Additional information

---

src/Orleans.Core/Runtime/OutgoingCallInvoker.cs
src/Orleans.Runtime/Core/GrainMethodInvoker.cs
test/Grains/TestGrainInterfaces/IMethodInterceptionGrain.cs
test/Grains/TestGrains/MethodInterceptionGrain.cs
test/Tester/GrainCallFilterTests.cs

Allow grain call filters to retry calls

---

src/Documentation/tutorials_and_samples/tutorial_1.md

It seemed like it would be easier to find and read in a table format rather than text.

Added projects and associated nuget packes to a table.

---

src/Orleans.Connections.Security/Security/OrleansApplicationProtocol.cs
src/Orleans.Connections.Security/Security/TlsClientAuthenticationOptions.cs
src/Orleans.Connections.Security/Security/TlsClientConnectionMiddleware.cs
src/Orleans.Connections.Security/Security/TlsServerAuthenticationOptions.cs
test/Orleans.Connections.Security.Tests/TlsConnectionTests.cs

TLS: specify an application protocol to satisfy ALPN

---

src/Orleans.Runtime/MembershipService/MembershipTableCleanupAgent.cs

Change the error about not supported membership table cleanup functionality into a warning.

Change the error about not supported membership table cleanup functionality into a warning

---

src/Azure/Orleans.Reminders.AzureStorage/Storage/RemindersTableManager.cs
test/Extensions/TesterAzureUtils/AzureRemindersTableTests.cs
test/TesterInternal/RemindersTest/ReminderTableTestsBase.cs

Consistently sanitize properties for Azure Table Storage reminders implementation

---

src/Documentation/implementation/streams_implementation/azure_queue_streams.md

Collecting input from @jason-bragg and issue [6345](https://github.com/dotnet/orleans/issues/6345#issuecomment-595419498) about tuning azure queue streams. I found it very interesting and helpful to better understand how the system works. I thought was smart to share it in the docs.

Tuning Azure Queue Streams

---

src/Orleans.Runtime/MembershipService/MembershipAgent.cs

Gossip that the silo is dead before the outbound queue gets closed

---

src/Orleans.Core/Lifecycle/LifecycleSubject.cs

Fix a race condition in `LifecycleSubject` when calling `Dispose` on the observer.

Fix a race condition in LifecycleSubject

---

src/Azure/Orleans.GrainDirectory.AzureStorage/AzureTableGrainDirectory.cs
src/Azure/Orleans.GrainDirectory.AzureStorage/Hosting/AzureTableGrainDirectoryExtensions.cs
src/Azure/Orleans.GrainDirectory.AzureStorage/Options/AzureTableGrainDirectoryOptions.cs
src/Orleans.Core.Abstractions/GrainDirectory/GrainDirectoryAttribute.cs
src/Orleans.Core.Abstractions/GrainDirectory/IGrainDirectory.cs
src/Orleans.Core/Runtime/GrainInterfaceMap.cs
src/Orleans.Runtime/Catalog/Catalog.cs
src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs
src/Orleans.Runtime/GrainDirectory/GrainDirectoryResolver.cs
src/Orleans.Runtime/GrainDirectory/GrainLocatorSelector.cs
src/Orleans.Runtime/GrainTypeManager/GrainTypeData.cs
src/Orleans.Runtime/GrainTypeManager/GrainTypeManager.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
test/Extensions/TesterAzureUtils/AzureGrainDirectoryTests.cs
test/Grains/TestGrainInterfaces/Directories/IAzureTableDirectoryGrain.cs
test/Grains/TestGrainInterfaces/Directories/ICommonDirectoryGrain.cs
test/Grains/TestGrainInterfaces/Directories/IDefaultDirectoryGrain.cs
test/Grains/TestGrains/Directories/AzureTableDirectoryGrain.cs
test/Grains/TestGrains/Directories/DefaultDirectoryGrain.cs
test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs
test/NonSilo.Tests/Directory/GrainDirectoryResolverTests.cs
test/Tester/Directories/MultipleGrainDirectoriesTests.cs
test/Tester/Tester.csproj

* Apply suggestions from code review
Co-authored-by: Reuben Bond <203839+ReubenBond@users.noreply.github.com>

[3.2.0] Directory per grain

---

src/Orleans.GrainDirectory.Redis/RedisGrainDirectory.cs

Log exceptions in RedisGrainDirectory and throw `OrleansException` to avoid serialization exceptions in the client.

Log exceptions in RedisGrainDirectory

---

src/Orleans.Core.Abstractions/IDs/ActivationAddress.cs
src/Orleans.Core/Messaging/Message.cs

Also improve `Message.ToString()` & `ActivationAddress.ToString()` readability

Remove Message.TargetObserverId

---

src/Orleans.Core/Transactions/OrleansTransactionException.cs
src/Orleans.Core/Transactions/TransactionalStatus.cs
src/Orleans.Runtime.Abstractions/Transactions/ITransactionAgent.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
src/Orleans.Runtime/Transactions/DisabledTransactionAgent.cs
src/Orleans.Transactions/DistributedTM/TransactionAgent.cs
src/Orleans.Transactions/DistributedTM/TransactionInfo.cs
src/Orleans.Transactions/State/ReaderWriterLock.cs
src/Orleans.Transactions/State/TransactionManager.cs
src/Orleans.Transactions/State/TransactionQueue.cs
src/Orleans.Transactions/State/TransactionalResource.cs

Propagate additional transaction abort exceptions

---

src/OrleansProviders/Streams/Memory/MemoryPooledCache.cs

Fix SequenceNumber for MemoryStream

---

src/OrleansProviders/Streams/Memory/MemoryPooledCache.cs

[3.2.1] Fix SequenceNumber for MemoryStream

---

src/Orleans.CodeGenerator/Compatibility/RoslynTypeNameFormatter.cs
test/CodeGeneration/CodeGenerator.Tests/RoslynTypeNameFormatterTests.cs

(Partial?) fix for issue raised by #6578

Fix named tuples in codegen

---

src/Orleans.Runtime/Messaging/Gateway.cs

Rebases #6655 on master (was 3.2.2)

Avoid race in GatewaySender.Send

---

src/Documentation/resources/Presentations/index.md

Adding "Orleans at Microsoft by Reuben Bond - August 2020 (video)" link to Presentations page.

Adding "Orleans at Microsoft by Reuben Bond - August 2020 (video)" link to Presentations page.

---

src/Orleans.Core/ClientObservers/ClientGatewayObserver.cs
src/Orleans.Core/ClientObservers/ClientObserver.cs
src/Orleans.Core/Messaging/ClientMessageCenter.cs
src/Orleans.Core/Messaging/GatewayManager.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
src/Orleans.Runtime/Messaging/Gateway.cs
src/Orleans.Runtime/Networking/ConnectionListener.cs
src/Orleans.Runtime/Networking/GatewayConnectionListener.cs
src/Orleans.Runtime/Silo/Silo.cs
test/Tester/Forwarding/ShutdownSiloTests.cs

First commit is just a port of what has been done for 3.2.1.

Use "static" client observer to notify from the gateway when the silo is shutting down

---

src/Orleans.Runtime/Configuration/Options/SiloMessagingOptions.cs
src/Orleans.Runtime/Messaging/Gateway.cs

Make delay after GW shutdown notification configurable

---

src/Orleans.Core/Runtime/GrainInterfaceData.cs
src/Orleans.Core/Runtime/GrainInterfaceMap.cs
test/Grains/TestGrainInterfaces/IHeterogeneousGrain.cs
test/Grains/TestInternalGrains/HeterogeneousGrain.cs
test/Tester/HeterogeneousSilosTests/HeterogeneousTests.cs

Fix for #6765
I was not able to repro in master, but I will port the test anyway

Fix bad merge of GrainInterfaceMap

---

Samples/3.1/GenericHost/BuildAndRun.ps1
Samples/3.1/GenericHost/BuildAndRun.sh
Samples/3.1/GenericHost/GenericHost.sln
Samples/3.1/GenericHost/Readme.md
Samples/3.1/GenericHost/src/HelloWorld.Grains/HelloArchiveGrain.cs
Samples/3.1/GenericHost/src/HelloWorld.Grains/HelloGrain.cs
Samples/3.1/GenericHost/src/HelloWorld.Grains/HelloWorld.Grains.csproj
Samples/3.1/GenericHost/src/HelloWorld.Interfaces/HelloWorld.Interfaces.csproj
Samples/3.1/GenericHost/src/HelloWorld.Interfaces/IHello.cs
Samples/3.1/GenericHost/src/HelloWorld.Interfaces/IHelloArchive.cs
Samples/3.1/GenericHost/src/OrleansClient/OrleansClient.csproj
Samples/3.1/GenericHost/src/OrleansClient/Program.cs
Samples/3.1/GenericHost/src/SiloHost/Program.cs
Samples/3.1/GenericHost/src/SiloHost/SiloHost.csproj

Migrated GenericHost to dotnet core 3.1 #2359

2359 Update GenericHost to dotnet core 3.1

---

Samples/3.3/Directory.Build.props
Samples/3.3/Streaming/Common/Common.csproj
Samples/3.3/Streaming/Common/Constants.cs
Samples/3.3/Streaming/Common/Secrets.cs
Samples/3.3/Streaming/CustomDataAdapter/CustomDataAdapter.sln
Samples/3.3/Streaming/CustomDataAdapter/GrainInterfaces/GrainInterfaces.csproj
Samples/3.3/Streaming/CustomDataAdapter/GrainInterfaces/IConsumerGrain.cs
Samples/3.3/Streaming/CustomDataAdapter/Grains/ConsumerGrain.cs
Samples/3.3/Streaming/CustomDataAdapter/Grains/Grains.csproj
Samples/3.3/Streaming/CustomDataAdapter/NonOrleansClient/NonOrleansClient.csproj
Samples/3.3/Streaming/CustomDataAdapter/NonOrleansClient/Program.cs
Samples/3.3/Streaming/CustomDataAdapter/Silo/CustomDataAdapter.cs
Samples/3.3/Streaming/CustomDataAdapter/Silo/Program.cs
Samples/3.3/Streaming/CustomDataAdapter/Silo/Silo.csproj
Samples/3.3/Streaming/Secrets.json
Samples/3.3/Streaming/Simple/Client/Client.csproj
Samples/3.3/Streaming/Simple/Client/Program.cs
Samples/3.3/Streaming/Simple/GrainInterfaces/GrainInterfaces.csproj
Samples/3.3/Streaming/Simple/GrainInterfaces/IConsumerGrain.cs
Samples/3.3/Streaming/Simple/GrainInterfaces/IProducerGrain.cs
Samples/3.3/Streaming/Simple/Grains/ConsumerGrain.cs
Samples/3.3/Streaming/Simple/Grains/Grains.csproj
Samples/3.3/Streaming/Simple/Grains/ProducerGrain.cs
Samples/3.3/Streaming/Simple/SiloHost/Program.cs
Samples/3.3/Streaming/Simple/SiloHost/SiloHost.csproj
Samples/3.3/Streaming/Simple/Streaming.sln

- One simple example, with implicit and explicit subscriptions
- One with a custom implementation of `EventHubDataAdapter`, with a client without any Orleans dependency that push event to a stream

Add two samples that use Event Hub streaming

---

.github/workflows/docs.yml

This will take a few goes to get right and I don't know of a better way to iteratively develop GitHub Actions

[CI] Build & publish docs on push to docs branch

---

README.md

Fix broken links as per #6821

---

src/Orleans.Core/SystemTargetInterfaces/IManagementGrain.cs
src/Orleans.Runtime/Core/ManagementGrain.cs
test/TesterInternal/OrleansRuntime/ManagementGrainTests.cs

This PR add to `IManagementGrain` the ability to query the `Catalog` for a given `IAddressable`.
Closes: #6809

Add IManagementGrain.GetActivationAddress()

---

src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubStreamOptions.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/IEventHubReceiver.cs

Allows configuration of EventHubsTransportType when using EventHub stream

Support EventHubsTransportType on EventHub streams

---

src/AdoNet/Shared/Storage/DbConnectionFactory.cs

Backport of #6831
Pinging @veikkoeeva to check if I did not miss anything

Add ADO.NET Provider support MySqlConector 0.x and 1.x. (#6831)

---

src/Orleans.Core/Core/ClusterClient.cs
src/Orleans.Runtime/Silo/Silo.cs

* Log silo shutdown message earlier
* Add message for when silo shutdown completes
* Log shutdown messages for client
* Clean up wording

Correctly log silo and client shutdown initiation and completion

---

src/Orleans.Core.Abstractions/CodeGeneration/InvokeMethodRequest.cs
src/Orleans.Core.Abstractions/IDs/GrainId.cs
src/Orleans.Core.Abstractions/IDs/GrainTypePrefix.cs
src/Orleans.Core.Abstractions/IDs/Legacy/UniqueKey.cs
src/Orleans.Core.Abstractions/Logging/IdLoggingHelper.cs
src/Orleans.Core/Core/DefaultClientServices.cs
src/Orleans.Core/Logging/BaseLoggingHelper.cs
src/Orleans.Core/Logging/ClientLoggingHelper.cs
src/Orleans.Core/Messaging/Message.cs
src/Orleans.Core/Runtime/CallbackData.cs
src/Orleans.Core/Runtime/Constants.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Logging/SiloLoggingHelper.cs
src/Orleans.Runtime/Silo/Silo.cs

Improve output of GrainId.ToString(), InvokeMethodRequest.ToString() and Message.ToString()

---

src/Orleans.TestingHost/Logging/FileLogger.cs

Previously, if Flush or Dispose threw, the Dispose method would try again the next time, even though the output may have actually been closed.

Ensure proper closure of file logging output

---

src/Orleans.Core/Utils/LRU.cs
src/Orleans.Runtime/Catalog/Catalog.cs
src/Orleans.Runtime/Core/Dispatcher.cs
test/DefaultCluster.Tests/BasicActivationTests.cs
test/DefaultCluster.Tests/GenericGrainTests.cs
test/DefaultCluster.Tests/StatelessWorkerTests.cs
test/DependencyInjection.Tests/DependencyInjectionGrainTestsRunner.cs
test/Grains/TestGrainInterfaces/ITestGrain.cs
test/Grains/TestInternalGrains/TestGrain.cs
test/NonSilo.Tests/General/LruTest.cs

Try to limit forwarding when a grain activation throws an exception in OnActivateAsync()

---

src/Orleans.Runtime/GrainDirectory/GrainDirectoryPartition.cs

Throw an exception when trying to register an activation on an invalid silo

---

src/Orleans.Runtime/Core/Dispatcher.cs

Only log that a message is being forwarded if it is being forwarded 

---

src/Orleans.Core.Abstractions/Core/IStorage.cs

I pulled out the non-generic related functionality out of `IStorage`

Added a base class to IStorage that is not generic

---

NuGet.Config

Update NuGet.Config (#6873)

---

Directory.Build.props
src/Azure/Orleans.Streaming.EventHubs/Orleans.Streaming.EventHubs.csproj

Workaround for https://github.com/Azure/azure-sdk-for-net/issues/17835

EventHubs: Force latest version of Microsoft.Azure.Amqp

---

src/Orleans.Core/Networking/Connection.cs
src/Orleans.Core/Networking/ConnectionManager.cs
src/Orleans.Core/Runtime/HashRing.cs
src/Orleans.Core/Runtime/RingRange.cs
src/Orleans.Core/Streams/QueueAdapters/HashRingBasedStreamQueueMapper.cs
src/Orleans.Runtime/ConsistentRing/ConsistentRingProvider.cs
src/Orleans.Runtime/ConsistentRing/EquallyDividedRangeRingProvider.cs
src/Orleans.Runtime/ConsistentRing/VirtualBucketsRingProvider.cs
src/Orleans.Runtime/ReminderService/LocalReminderService.cs
test/DefaultCluster.Tests/ReminderTest.cs
test/Grains/TestGrainInterfaces/IReminderTestGrain.cs
test/Grains/TestGrains/ReminderTestGrain.cs
test/TestInfrastructure/TestExtensions/DefaultClusterFixture.cs
test/TesterInternal/LivenessTests/ConsistentRingProviderTests.cs

This optimizes RingRange handling and compacts multi-ranges so that LocalReminderService has to do fewer storage queries.

Optimize and cleanup RingRange handling

---

src/Orleans.Runtime/Core/Dispatcher.cs

We should not respond to a response :)

Only send a rejection if the message is a request

---

src/Orleans.Runtime/Core/InsideRuntimeClient.cs

In some (very) corner case, it's possible to execute a wrong message callback, since they are identified only with the `CorrelationId` of the message.
In this PR, the callback dictionary is indexed by a `ValueTuple<GrainId,CorrelationId>` to avoid collision.

Avoid Message.Id collision in the message callback dictionary lookup

---

src/Orleans.CodeGenerator.MSBuild/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets

I introduced this issue during the move to .NET 5 tooling
Fixes #6948

Fix codegen NuGet package

---

src/Orleans.Runtime/Messaging/IncomingMessageHandler.cs

Only send a rejection if the message is a request (#6946)

---

src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubCheckpointer.cs

The old EventHub SDK used in 3.x uses `string` offset to create the starting `EventPosition` used in `PartitionReceiver` constructor.
If the stored offset value is corrupted, Streaming Pulling Agents will not be capable of receiving message anymore, and all calls to `ReceiveAsync` will throw an `InvalidOperationException`.
In reality, this offset should always be convertible to a `long`. To avoid corruption before writing to/reading from the `EventHubCheckpointer`, we check if the conversion is possible.
EventHub SDK 5.x switched this offset type to `long`, so this fix isn't applicable for master.
EDIT: I forgot to add, but we don't want to change the implementation and store `long` instead of `string` to not break backward compatibility.

Check if offset is a long in EventHubCheckpointer

---

src/Orleans.Runtime/Timers/AsyncTimer.cs

@ReubenBond as you mentioned in https://github.com/dotnet/orleans/pull/6640#issuecomment-664014606 the new logic causes first-chance exceptions during shutdown. I noticed about 10 happening while investigating a shutdown issue in another component (unrelated to Orleans), so I propose this workaround.

Avoid exceptions from AsyncTimer cancellation

---

test/Tester/CancellationTests/GrainCancellationTokenTests.cs

Adds a test for concurrent LongWait tasks and cancellations with GrainCancellationTokens. See #6964
This test fails with on `v3.4.1` but works on `master` so looks like y'all already fixed it.
```
```
```
Message: 
Expected TaskCancelledException, but message completed
Expected: True
Actual:   False
Stack Trace: 
<<GrainTaskMultipleCancellations>b__0>d.MoveNext() line 71
--- End of stack trace from previous location where exception was thrown ---
GrainCancellationTokenTests.GrainTaskMultipleCancellations(Int32 delay) line 76
--- End of stack trace from previous location where exception was thrown ---
```

Add test for concurrent GrainCancellationTokens

---

src/Orleans.Core/Messaging/Message.cs
test/NonSilo.Tests/General/MessageTests.cs

Co-authored-by: Reuben Bond <203839+ReubenBond@users.noreply.github.com>

[Backport] Return zero elapsed time for unstarted Messages (#6969)

---

src/Orleans.Runtime/Catalog/Catalog.cs

Call ScheduleCollection before starting processing requests

---

src/Orleans.Runtime/Catalog/Catalog.cs

Fix count check when trying to create new stateless workers

---

src/Orleans.Core/Logging/ILoggerExtensions.cs
src/Orleans.Core/Scheduler/TaskSchedulerAgent.cs

We could do more here, but this is a start.

Remove unused code in TaskSchedulerAgent

---

src/Orleans.Runtime/Catalog/ActivationData.cs

I've fixed a typo in AnalyzeWorkload.cs

Fix a typo in AnalyzeWorkload

---

src/Orleans.Core/GrainDirectory/IDhtGrainDirectory.cs
src/Orleans.Core/GrainDirectory/IGrainLocator.cs
src/Orleans.Core/Statistics/IPerformanceMetrics.cs
src/Orleans.Runtime/Catalog/Catalog.cs
src/Orleans.Runtime/Core/InsideRuntimeClient.cs
src/Orleans.Runtime/Core/ManagementGrain.cs
src/Orleans.Runtime/GrainDirectory/AdaptiveDirectoryCacheMaintainer.cs
src/Orleans.Runtime/GrainDirectory/AdaptiveGrainDirectoryCache.cs
src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs
src/Orleans.Runtime/GrainDirectory/ClientGrainLocator.cs
src/Orleans.Runtime/GrainDirectory/DhtGrainLocator.cs
src/Orleans.Runtime/GrainDirectory/GrainDirectoryCacheFactory.cs
src/Orleans.Runtime/GrainDirectory/GrainDirectoryHandoffManager.cs
src/Orleans.Runtime/GrainDirectory/GrainDirectoryPartition.cs
src/Orleans.Runtime/GrainDirectory/GrainLocator.cs
src/Orleans.Runtime/GrainDirectory/IGrainDirectoryCache.cs
src/Orleans.Runtime/GrainDirectory/ILocalGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/IRemoteGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/LRUBasedGrainDirectoryCache.cs
src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/RemoteGrainDirectory.cs
test/Grains/TestInternalGrains/TestGrain.cs
test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs
test/NonSilo.Tests/Directory/MockLocalGrainDirectory.cs
test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs
test/TesterInternal/General/ConsistentRingProviderTests_Silo.cs

This completes item two in #6880

Remove support for multiple activations in grain directory

---

src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubQueueCache.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubQueueCacheFactory.cs
src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs
src/Orleans.Streaming/Common/RecoverableStreamOptions.cs
src/Orleans.Streaming/Core/StreamIdentity.cs
src/Orleans.Streaming/PersistentStreams/StreamConsumerCollection.cs
test/Extensions/ServiceBus.Tests/EvictionStrategyTests/TestMocks.cs
test/Extensions/ServiceBus.Tests/Streaming/EHCustomBatchContainerTests.cs
test/Extensions/ServiceBus.Tests/TestStreamProviders/EHStreamProviderWithCreatedCacheList.cs
test/Grains/TestGrainInterfaces/IImplicitSubscriptionCounterGrain.cs
test/Grains/TestGrains/ImplicitSubscriptionCounterGrain.cs
test/Tester/StreamingTests/MemoryStreamCacheMissTests.cs
test/Tester/StreamingTests/StreamingCacheMissTests.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs

In PooledQueueCache, avoid cache miss if we know that we didn't missed any event

---

src/Orleans.Core.Abstractions/GrainDirectory/IGrainDirectory.cs
src/Orleans.Core/Runtime/MembershipVersion.cs
src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs
src/Orleans.Runtime/GrainDirectory/LRUBasedGrainDirectoryCache.cs
test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs

Partial port of #7118 for 3.5.0.
Should fix #7054

Add MembershipVersion in GrainAddress

---

src/Orleans.CodeGenerator/Generators/GrainReferenceGenerator.cs
src/Orleans.CodeGenerator/Orleans.CodeGenerator.csproj
src/Orleans.Core/CodeGeneration/GenericMethodInvoker.cs
test/CodeGeneration/CodeGenerator.Tests/CodeGenerator.Tests.csproj
test/CodeGeneration/CodeGenerator.Tests/GenericMethodInvokerTests.cs

backport PR #6844 to 3.5.0: generic overloads selection bugfix

---

src/Orleans.Hosting.Kubernetes/KubernetesClientExtensions.cs

Co-authored-by: ghamos <ghamos@itron.com>

[Backport] Fix unhandled exception on k8s watcher background task (#7168)

---

src/Orleans.Runtime/Counters/OrleansCounterManager.cs
test/Tester/StreamingTests/DeactivationTestRunner.cs
test/Tester/StreamingTests/SMSDeactivationTests.cs

Trivial PR
Contributes to #7099

Clean up Counters logging

---

src/Orleans.Core/Configuration/Options/ClusterOptions.cs
test/NonSilo.Tests/ClientBuilderTests.cs
test/NonSilo.Tests/SiloBuilderTests.cs

Set a default ClusterId and ServiceId

---

src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/IEventHubReceiver.cs

In EventHubReceiverProxy, if the starting offset isn't valid, log an error and ignore the value

EventHubReceiverProxy: ignore if offset isn't valid

---

src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorage.cs

Backporting as per https://github.com/dotnet/orleans/pull/7147#issuecomment-904735786

[3.5.0] Updated AzureBlobStorage to use state type during JSON deserialization (#7147)

---

src/Orleans.Core.Abstractions/Activation/IGrainContext.cs
src/Orleans.Core/GrainDirectory/IGrainLocator.cs
src/Orleans.Runtime/Core/GrainRuntime.cs
src/Orleans.Runtime/Core/ManagementGrain.cs
src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs
src/Orleans.Runtime/GrainDirectory/ClientGrainLocator.cs
src/Orleans.Runtime/GrainDirectory/DhtGrainLocator.cs
src/Orleans.Runtime/GrainDirectory/GrainLocator.cs
src/Orleans.Runtime/Placement/PlacementService.cs
test/Grains/TestInternalGrains/TestGrain.cs
test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs

Remove IGrainLocator.TryLocalLookup and rename TryCacheOnlyLookup

---

Directory.Build.props

Updated Newtonsoft library to address vulnerability.
Tests run locally.

#7189 Updated Newtonsoft JSON library

---

src/Orleans.Serialization/Configuration/DefaultTypeManifestProvider.cs
src/Orleans.Serialization/Hosting/ServiceCollectionExtensions.cs
src/Orleans.Serialization/ISerializableSerializer/DotNetSerializableCodec.cs
src/Orleans.Serialization/ISerializableSerializer/ExceptionCodec.cs
src/Orleans.Serialization/ISerializableSerializer/SerializationCallbacksFactory.cs
src/Orleans.Serialization/ISerializableSerializer/SerializationConstructorFactory.cs
src/Orleans.Serialization/ISerializableSerializer/SerializationConstructorNotFoundException.cs
src/Orleans.Serialization/ISerializableSerializer/SerializationEntryCodec.cs
src/Orleans.Serialization/ISerializableSerializer/SerializationEntrySurrogate.cs
src/Orleans.Serialization/ISerializableSerializer/ValueTypeSerializer.cs
src/Orleans.Serialization/ISerializableSerializer/ValueTypeSerializerFactory.cs
test/Orleans.Serialization.UnitTests/ISerializableTests.cs

Just a stylistic change to remove that namespace segment

Remove ISerializableSupport namespace segment

---

src/Orleans.Core/Providers/IMemoryStorageGrain.cs
src/Orleans.Persistence.Memory/Storage/MemoryStorage.cs
src/Orleans.Persistence.Memory/Storage/MemoryStorageGrain.cs
test/DefaultCluster.Tests/MemoryStorageProviderTests.cs

Merge #7265 first.
Removed a parameter that wasn't really useful, and renamed another for more consistency.

Simplify IMemoryGrainStorage

---

src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubQueueCache.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubQueueCacheFactory.cs
src/Orleans.Core/Streams/Core/StreamIdentity.cs
src/Orleans.Core/Streams/PersistentStreams/StreamConsumerCollection.cs
src/Orleans.Runtime/Core/SystemTarget.cs
src/Orleans.Runtime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
src/Orleans.Runtime/Timers/GrainTimer.cs
src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
src/OrleansProviders/Streams/Common/RecoverableStreamOptions.cs
test/Extensions/ServiceBus.Tests/EvictionStrategyTests/TestMocks.cs
test/Extensions/ServiceBus.Tests/Streaming/EHCustomBatchContainerTests.cs
test/Extensions/ServiceBus.Tests/TestStreamProviders/EHStreamProviderWithCreatedCacheList.cs
test/Grains/TestGrainInterfaces/IImplicitSubscriptionCounterGrain.cs
test/Grains/TestGrains/ImplicitSubscriptionCounterGrain.cs
test/Tester/StreamingTests/MemoryStreamCacheMissTests.cs
test/Tester/StreamingTests/StreamingCacheMissTests.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs

Backport only streaming related improvement without SDK upgrade to 3.4.4

Backports to 3.4.4

---

src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs

Fix token comparison in SetCursor

---

src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs

Fix token comparison in SetCursor (#7308)

---

src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubAdapterFactory.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubAdapterReceiver.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubStreamOptions.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/IEventHubReceiver.cs
test/Extensions/ServiceBus.Tests/EventHubConfigurationExtensions.cs
test/Extensions/ServiceBus.Tests/EvictionStrategyTests/EHPurgeLogicTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHBatchedSubscriptionMultiplicityTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHClientStreamTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHImplicitSubscriptionStreamRecoveryTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHProgrammaticSubscribeTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHStreamBatchingTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHStreamCacheMissTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHStreamPerPartitionTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHStreamProviderCheckpointTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHSubscriptionMultiplicityTests.cs
test/Extensions/ServiceBus.Tests/Streaming/EHSubscriptionObserverWithImplicitSubscribingTests.cs
test/Extensions/ServiceBus.Tests/TestStreamProviders/EHStreamProviderForMonitorTests.cs
test/Extensions/ServiceBus.Tests/TestStreamProviders/EHStreamProviderWithCreatedCacheList.cs

This is a follow-up to #7300, extending support for the new configuration methods to the Event Hubs streams provider

Support additional authentication options for Azure Event Hub streams provider

---

README.md

Fix Discord server status button link

---

src/Orleans.Clustering.Consul/SerializableMembershipTypes.cs
src/Orleans.CodeGenerator/CopierGenerator.cs
src/Orleans.CodeGenerator/InvokableGenerator.cs
src/Orleans.CodeGenerator/SerializerGenerator.cs
src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
src/Orleans.Streaming/QueueAdapters/BatchContainerBatch.cs
src/Orleans.TestingHost/TestCluster.cs
src/Orleans.Transactions.TestKitBase/TestRunners/ControlledFaultInjectionTransactionTestRunner.cs

Replace First and Last with indexer and FirstOrDefault with Find when available

---

src/Orleans.GrainDirectory.Redis/RedisGrainDirectory.cs

Fix in Redis GrainDirectory: when deleting, check only the ActivationId

---

Directory.Build.props
src/Orleans.Core/Core/ClientBuilderExtensions.cs
src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs
src/Orleans.Core/Orleans.Core.csproj
src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
test/Grains/TestGrainInterfaces/IActivityGrain.cs
test/Grains/TestGrains/ActivityGrain.cs
test/Tester/DiagnosticTests.cs

Related issue: #6853
This pr also added baggage propagation.

Use DistributedContextPropagator to propagate Activities

---

src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs
test/Tester/DiagnosticTests.cs

Updated the filter to correctly create an activity if traceParent is present in the context

Small telemetry correlation fix 

---

.editorconfig
samples/Adventure/AdventureClient/AdventureClient.csproj
samples/Adventure/AdventureClient/Program.cs
samples/Adventure/AdventureGrainInterfaces/AdventureGrainInterfaces.csproj
samples/Adventure/AdventureGrainInterfaces/IMonsterGrain.cs
samples/Adventure/AdventureGrainInterfaces/IPlayerGrain.cs
samples/Adventure/AdventureGrainInterfaces/IRoomGrain.cs
samples/Adventure/AdventureGrainInterfaces/MonsterInfo.cs
samples/Adventure/AdventureGrainInterfaces/PlayerInfo.cs
samples/Adventure/AdventureGrainInterfaces/Thing.cs
samples/Adventure/AdventureGrains/AdventureGrains.csproj
samples/Adventure/AdventureGrains/MonsterGrain.cs
samples/Adventure/AdventureGrains/PlayerGrain.cs
samples/Adventure/AdventureGrains/RoomGrain.cs
samples/Adventure/AdventureServer/AdventureGame.cs
samples/Adventure/AdventureServer/AdventureServer.csproj
samples/Adventure/AdventureServer/Program.cs

Upgrade to .NET 6 and modernize

---

README.md

Removes last reference to discord and makes badge match existing style.

Remove last reference to gitter.

---

samples/README.md

Adding more examples to the samples README page.

Adding Road to Orleans and end to end F# Example to samples README

---

src/Orleans.Core/Messaging/ClientMessageCenter.cs
src/Orleans.Core/Networking/ClientOutboundConnection.cs
src/Orleans.Core/Networking/ClientOutboundConnectionFactory.cs
src/Orleans.Core/Networking/Connection.cs
src/Orleans.Core/Networking/ConnectionManager.cs
src/Orleans.Core/Networking/ConnectionPreamble.cs
src/Orleans.Core/Networking/NetworkProtocolVersion.cs
src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
src/Orleans.Runtime/Networking/GatewayInboundConnection.cs
src/Orleans.Runtime/Networking/SiloConnection.cs
test/Tester/ClientConnectionTests/GatewayConnectionTests.cs

Refuse connections with different ClusterId

---

src/Orleans.Sdk/Orleans.Sdk.csproj

Package description is blank.
Fixes #7563
Please directly suggest verbiage change and commit.

Add description element to Orleans.Sdk.csproj

---

src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs

In CachedGrainLocator.Unregister, remove from cache using the address

---

src/Orleans.Core.Abstractions/Runtime/GrainReference.cs
test/Tester/ExceptionPropagationTests.cs

Enable skipped exception serializer test & apply DebuggerHidden to methods

---

src/Orleans.Core/GrainDirectory/IGrainLocator.cs
src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs
src/Orleans.Runtime/GrainDirectory/GrainDirectoryResolver.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
test/Tester/Directories/MultipleGrainDirectoriesTests.cs

Fix custom grain directory registration

---

.azure/pipelines/pr.yaml

Add task to explicitly use the correct SDK version

---

src/Orleans.Core/Utils/LRU.cs

Expand LRU acronym in LRU.cs

---

src/Orleans.Runtime/Catalog/ActivationData.cs

This fixes a bug which can occur when a grain is deactivating while it has messages enqueued.
When messages are enqueued on a grain which is deactivating, the grain will (erroneously) try to forward those messages to a new activation. However, since the grain has not completed deactivation, the messages will usually be forwarded to the same activation. They will continue to be forwarded to the same activation until forwarding fails due to exceeding the hop threshold (defaults to 2).
We see this in CI test runs frequently.

Do not forward messages while an activation is deactivating

---

test/TesterInternal/TimerTests/ReminderTests_Base.cs

To account for some non-determinism.
Also converts Thread.Sleep to Task.Delay in test code.

[Tests] Increase leeway in ReminderTests from 100ms to 500ms

---

src/Orleans.Core.Abstractions/Core/Grain.cs
src/Orleans.Core.Abstractions/Timers/IReminderRegistry.cs
src/Orleans.Runtime/ReminderService/ReminderRegistry.cs
src/Orleans.Runtime/Services/GrainServiceClient.cs
test/Grains/TestInternalGrains/ReminderTestGrain2.cs
test/Tester/GrainServiceTests/TestGrainService.cs

Changing IReminderRegistry to accept GrainId

---

src/Orleans.Core/CodeGeneration/GenericMethodInvoker.cs
test/CodeGeneration/CodeGenerator.Tests/GenericMethodInvokerTests.cs

Fix generic method

---

src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDBReminderTable.cs
src/AWS/Shared/Storage/DynamoDBStorage.cs

This is a port of #7437 from 3.x to 4.x

DynamoDB Reminders load using GSI (#7437)

---

src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBGatewayListProvider.cs
src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBMembershipTable.cs
src/AWS/Orleans.Clustering.DynamoDB/Options/DynamoDBClusteringOptions.cs
src/AWS/Orleans.Clustering.DynamoDB/Options/DynamoDBGatewayOptions.cs
src/AWS/Orleans.Persistence.DynamoDB/Options/DynamoDBStorageOptions.cs
src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDBReminderTable.cs
src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDbReminderStorageOptions.cs
src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDbReminderStorageOptionsExtensions.cs
src/AWS/Shared/Storage/DynamoDBStorage.cs

This is a port of #7681 from 3.x to 4.x

DynamoDB optional table create / update and update corner cases (#7681)

---

src/Orleans.Core/Messaging/GatewayManager.cs

Regarding issue #7099: fixes "Logging noise: Gateway refresh notifications on client"

---

samples/HelloWorld/HelloWorld.csproj

https://github.com/dotnet/orleans/issues/7760
I update .net to 6 and orleans package to 3.6.2

Update hello word sample to .Net6

---

.github/workflows/ci.yml

Suppress CredScan warnings for ci.yml file

---

.azure/pipelines/pr.yaml

Migrate to new pool

---

.azure/pipelines/pr.yaml

Force installation of 3.1 and 5.0 sdk

---

src/Azure/Orleans.Clustering.AzureStorage/AzureBasedMembershipTable.cs
src/Azure/Orleans.Clustering.AzureStorage/OrleansSiloInstanceManager.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorage.cs
src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
src/Azure/Orleans.Reminders.AzureStorage/Storage/AzureBasedReminderTable.cs
src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueAdapterReceiver.cs
src/Azure/Orleans.Streaming.AzureStorage/Storage/AzureQueueDataManager.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/EventDataGeneratorStreamProvider/EventDataGeneratorAdapterFactory.cs
src/Azure/Orleans.Streaming.EventHubs/Providers/EventDataGeneratorStreamProvider/EventHubPartitionDataGenerator.cs
src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/AzureTableTransactionalStateStorage.cs
src/Azure/Shared/Storage/AzureTableDataManager.cs
src/Azure/Shared/Storage/AzureTableUtils.cs

Based on #7025 and #5865, refactor logging messages across various Azure
providers to be more modern. Specifically:
- Used named parameters in logging messages for Structured
Logging/MessageTemplate support
- Favor `Microsoft.Extensions.Logging` methods rather than custom shims
- Remove duplicative exception details from log messages, favor
associating the exception object with the log message
Happy to get feedback on especially the last point, it seems kind of
opinionated.
If this approach is solid, I'd like to work on other providers and parts
of the code over the next few weeks as time permits me to.

First pass at Structured Logging updates

---

src/Orleans.Core.Abstractions/IDs/IdSpanCodec.cs

Closes #7531
We can reintroduce such an optimization later, if it's deemed necessary

Remove leaky cache in IdSpanCodec

---

src/Orleans.Core/Core/GrainInterfaceTypeToGrainTypeResolver.cs

Correctly identify default grain type for an interface

---

src/Orleans.Core/Utils/LRU.cs

Remove LRU assert statements which rightly don't hold under concurrency

---

src/Orleans.Runtime/Configuration/Options/GrainCollectionOptions.cs

I believe this is a more appropriate default. Open to opinions @benjaminpetit.

Change default idle activation collection age to 15 minutes

---

src/Orleans.Core.Abstractions/Runtime/MembershipVersion.cs
src/Orleans.Core/Core/InterfaceToImplementationMappingCache.cs
src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs
src/Orleans.Core/Messaging/CachingIdSpanCodec.cs
src/Orleans.Core/Messaging/CachingSiloAddressCodec.cs
src/Orleans.Core/Networking/Shared/IOQueue.cs
src/Orleans.Runtime/Activation/IGrainContextActivator.cs
src/Orleans.Runtime/Catalog/StatelessWorkerGrainContext.cs
src/Orleans.Runtime/MembershipService/SiloHealthMonitor.cs
src/Orleans.Serialization/ISerializableSerializer/SerializationCallbacksFactory.cs

Replace some custom structs with ValueTuples.

Cleanup some unnecessary structs

---

src/Directory.Build.props
src/Orleans.Runtime/Networking/SiloConnection.cs
test/DefaultCluster.Tests/GenericGrainTests.cs
test/DefaultCluster.Tests/GrainActivateDeactivateTests.cs
test/DefaultCluster.Tests/GrainReferenceCastTests.cs
test/DefaultCluster.Tests/GrainReferenceTest.cs
test/DefaultCluster.Tests/MemoryStorageProviderTests.cs
test/DefaultCluster.Tests/RequestContextTest.cs
test/Extensions/AWSUtils.Tests/StorageTests/Base_PersistenceGrainTests_AWSStore.cs
test/Extensions/TesterAzureUtils/Reminder/ReminderTests_AzureTable.cs
test/Extensions/TesterAzureUtils/Streaming/StreamReliabilityTests.cs
test/TestInfrastructure/TestExtensions/OrleansTestingBase.cs
test/Tester/ActivityPropagationTests.cs
test/Tester/GrainCallFilterTests.cs
test/Tester/ManagementGrainTests.cs
test/Tester/MembershipTests/LivenessTests.cs
test/TesterInternal/General/ConsistentRingProviderTests_Silo.cs
test/TesterInternal/General/LoadSheddingTest.cs
test/TesterInternal/MessageScheduling/ReentrancyTests.cs
test/TesterInternal/StorageTests/PersistenceGrainTests.cs
test/TesterInternal/TestRunners/GrainPersistenceTestRunner.cs

The last PR broke the build after it was merged due to changes in main. This fixes it.

Increase warning/analysis level and fix warnings

---

samples/GPSTracker/GPSTracker.Service/Program.cs

Discussion #7867 suggest to move the  `WebApplicationBuilder`
#7868
#7867

Move gps tracker sample to WebApplicationBuilder

---

samples/ShoppingCart/README.md

As title, in README, Sil**e** should be Sil**o**

Fix typo in ShoppingCart sample README

---

src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubDataAdapter.cs
src/Orleans.BroadcastChannel/ChannelId.cs
src/Orleans.BroadcastChannel/SubscriberTable/ImplicitChannelSubscriberTable.cs
src/Orleans.Core.Abstractions/IDs/ActivationId.cs
src/Orleans.Core.Abstractions/IDs/JenkinsHash.cs
src/Orleans.Core.Abstractions/IDs/SiloAddress.cs
src/Orleans.Core.Abstractions/Utils/Utils.cs
src/Orleans.Core/CodeGeneration/GrainInterfaceUtils.cs
src/Orleans.Core/Messaging/CachingSiloAddressCodec.cs
src/Orleans.Core/Runtime/RingRange.cs
src/Orleans.Runtime/ConsistentRing/ConsistentRingProvider.cs
src/Orleans.Runtime/Messaging/Gateway.cs
src/Orleans.Serialization/Codecs/FloatCodec.cs
src/Orleans.Serialization/Codecs/IPAddressCodec.cs
src/Orleans.Streaming/Common/SegmentBuilder.cs
src/Orleans.Streaming/MemoryStreams/MemoryAdapterFactory.cs
src/Orleans.Streaming/PubSub/ImplicitStreamSubscriberTable.cs
src/Orleans.Streaming/PubSub/SubscriptionMarker.cs
src/Orleans.Streaming/StreamId.cs

Remove all allocations from deterministic hashing and use more pre-computed hash values.

Optimize hashing

---

.azure/pipelines/pr.yaml

Add azure pipeline yaml file for 3.x to build and test PR

---

Directory.Build.props
Directory.Build.targets
build.ps1
global.json
src/Directory.Build.targets
test/Benchmarks/Benchmarks.csproj
test/DistributedTests/DistributedTests.Client/DistributedTests.Client.csproj
test/DistributedTests/DistributedTests.Common/DistributedTests.Common.csproj
test/DistributedTests/DistributedTests.Server/DistributedTests.Server.csproj
test/TestInfrastructure/Orleans.TestingHost.AppDomain/Orleans.TestingHost.AppDomain.csproj

Fixes #7916
Tested in CI: produces packages with the correct SourceLink references

Fix Source Link and packaging

---

src/Orleans.CodeGenerator/SerializerGenerator.cs
test/Orleans.Serialization.UnitTests/RecordHierarchyTests.cs

Support serialization of record types in hierarchies with empty layers

---

src/AWS/Orleans.Streaming.SQS/Orleans.Streaming.SQS.csproj

Enable codegen on Orleans.Streaming.SQS

---

src/Orleans.Serialization/Buffers/Reader.cs

Passing `[ReadOnly]Span<T>` by reference limits RyuJIT's ability to optimize its use and has very limited benefits.
More importantly, it will require breaking changes for the public API when moving to C# 11 to use `scoped` - better to make the API change now.

Avoid passing Spans by reference

---

.azure/pipelines/build.yaml

- Install .net 2.1 runtime for codesigning
- Add scheduled nightly build
- Add version suffix
- Increase test timeout
- Avoid uploading nuget in PR builds

Various fixes in build.yaml

---

src/Orleans.Core/Async/MultiTaskCompletionSource.cs

This PR changes the implementation of `MultiTaskCompletionSource` from `lock` based to an `Interlocked` based. As the behavior requires a simple decrement and acting on zero, it can be supported by `Interlocked.Decrement`

Interlocked MultiTaskCompletionSource

---

Directory.Build.props

Bump version to 7

---

Directory.Build.props
src/Orleans.Analyzers/Orleans.Analyzers.csproj
src/Orleans.CodeGenerator.MSBuild/Orleans.CodeGenerator.MSBuild.csproj
src/Orleans.GrainDirectory.Redis/RedisGrainDirectory.cs
test/Extensions/TesterAdoNet/StorageTests/Relational/AdotNetProviderFunctionalityTests.cs
test/TesterInternal/OrleansRuntime/Streams/CachedMessageBlockTests.cs

Update package refs and fix build issues

---

src/Orleans.Streaming/PubSub/PubSubRendezvousGrain.cs

Addresses https://github.com/dotnet/orleans/issues/8021

In PubSubRendezvousGrain, initialize storage before logging

---

src/Orleans.Streaming/Core/IAsyncStream.cs
src/Orleans.Streaming/Hosting/StreamingServiceCollectionExtensions.cs
src/Orleans.Streaming/Internal/StreamImpl.cs
src/Orleans.Streaming/Internal/StreamSubscriptionHandleImpl.cs
src/Orleans.Streaming/JsonConverters/StreamImplConverter.cs
src/Orleans.Streaming/JsonConverters/StreamingConverterConfigurator.cs

Make StreamImpl and StreamSubscriptionHandleImpl Json.NET friendly

---

global.json

Update build SDK to .NET 7.0.0-rc2

---

.azure/pipelines/build.yaml

Currently we have a schedule but no triggers on this pipeline (we have CI triggers on another pipeline which we will retire)

Update build.yaml to perform CI build

---

.azure/pipelines/build.yaml

Enable CodeQL on Azure DevOps Pipeline

---

src/Orleans.Analyzers/GenerateGenerateSerializerAttributeAnalyzer.cs
src/Orleans.Analyzers/GenerateSerializationAttributesAnalyzer.cs
test/Analyzers.Tests/GenerateGenerateSerializerAttributeAnalyzerTest.cs
test/Analyzers.Tests/GenerateSerializationAttributesAnalyzerTest.cs

Analyzers: add explicit support for record types

---

src/Orleans.BroadcastChannel/BroadcastChannelOptions.cs
src/Orleans.BroadcastChannel/BroadcastChannelProvider.cs
src/Orleans.BroadcastChannel/BroadcastChannelWriter.cs
src/Orleans.BroadcastChannel/Hosting/ChannelHostingExtensions.cs
test/Tester/StreamingTests/BroadcastChannels/BroadcastChannelTests.cs

Fix typo and add comments in Broadcast Channel

---

samples/Blazor/BlazorServer/BlazorServer.csproj
samples/Blazor/BlazorServer/Grains/TodoGrain.cs
samples/Blazor/BlazorServer/Grains/TodoManagerGrain.cs
samples/Blazor/BlazorServer/Models/TodoItem.cs
samples/Blazor/BlazorServer/Models/TodoNotification.cs
samples/Blazor/BlazorServer/Models/WeatherInfo.cs
samples/Blazor/BlazorServer/Program.cs
samples/Blazor/BlazorServer/Services/TodoService.cs
samples/Blazor/BlazorWasm/BlazorWasm.Client/BlazorWasm.Client.csproj
samples/Blazor/BlazorWasm/BlazorWasm.Server/BlazorWasm.Server.csproj
samples/Blazor/BlazorWasm/BlazorWasm.Server/Grains/TodoGrain.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Grains/TodoManagerGrain.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Models/TodoItem.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Models/TodoNotification.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Models/WeatherInfo.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Program.cs

Upgrade Blazor sample to rc2

---

samples/Streaming/Common/Common.csproj
samples/Streaming/CustomDataAdapter/GrainInterfaces/GrainInterfaces.csproj
samples/Streaming/CustomDataAdapter/Grains/ConsumerGrain.cs
samples/Streaming/CustomDataAdapter/Grains/Grains.csproj
samples/Streaming/CustomDataAdapter/NonOrleansClient/NonOrleansClient.csproj
samples/Streaming/CustomDataAdapter/Silo/CustomDataAdapter.cs
samples/Streaming/CustomDataAdapter/Silo/Program.cs
samples/Streaming/CustomDataAdapter/Silo/Silo.csproj
samples/Streaming/Simple/Client/Client.csproj
samples/Streaming/Simple/Client/Program.cs
samples/Streaming/Simple/GrainInterfaces/GrainInterfaces.csproj
samples/Streaming/Simple/Grains/ConsumerGrain.cs
samples/Streaming/Simple/Grains/Grains.csproj
samples/Streaming/Simple/Grains/ProducerGrain.cs
samples/Streaming/Simple/SiloHost/Program.cs
samples/Streaming/Simple/SiloHost/SiloHost.csproj

Upgrade Streaming samples to rc2

---

src/Orleans.Serialization/Serializers/CodecProvider.cs

I believe this was introduced by #8014. I noticed it via a benchmark run which had unusually high allocations.
cc @pentp

Fix regression where CodecProvider.TryGetCodec never stores the result

---

test/Extensions/TesterAdoNet/StorageTests/Relational/CommonFixture.cs

Do not skip tests if the connection to the storage provider cannot be created

---

.azure/pipelines/build.yaml

Add version prefix option in build.yaml

---

test/Tester/StreamingTests/BroadcastChannels/BroadcastChannelTests.cs

Fix MultipleSubscribersOneBadActorChannelTest

---

src/Orleans.Streaming/MemoryStreams/MemoryAdapterFactory.cs
src/Orleans.Streaming/MemoryStreams/MemoryPooledCache.cs

Pass purgeMetadataInterval in MemoryPooledCache

---

src/Orleans.Core/Diagnostics/Metrics/Instruments.cs

For consistency with our ActivitySource names

Change meter name to Microsoft.Orleans

---

.azure/pipelines/build.yaml
.github/workflows/ci.yml
Directory.Build.props
global.json
src/Orleans.CodeGenerator/Model/InvokableInterfaceDescription.cs

Update to .NET 7.0.0

---

.azure/pipelines/build.yaml

Exclude samples folder from PR trigger

---

.azure/pipelines/build.yaml

Enable 3.x scheduled builds

---

samples/Adventure/AdventureClient/AdventureClient.csproj
samples/Adventure/AdventureClient/Program.cs
samples/Adventure/AdventureGrainInterfaces/AdventureGrainInterfaces.csproj
samples/Adventure/AdventureGrainInterfaces/IMonsterGrain.cs
samples/Adventure/AdventureGrainInterfaces/IPlayerGrain.cs
samples/Adventure/AdventureGrainInterfaces/IRoomGrain.cs
samples/Adventure/AdventureGrainInterfaces/MonsterInfo.cs
samples/Adventure/AdventureGrainInterfaces/PlayerInfo.cs
samples/Adventure/AdventureGrainInterfaces/Thing.cs
samples/Adventure/AdventureGrains/AdventureGrains.csproj
samples/Adventure/AdventureGrains/MonsterGrain.cs
samples/Adventure/AdventureGrains/PlayerGrain.cs
samples/Adventure/AdventureGrains/RoomGrain.cs
samples/Adventure/AdventureServer/AdventureGame.cs
samples/Adventure/AdventureServer/AdventureServer.csproj
samples/Adventure/AdventureServer/Program.cs

Contributes to https://github.com/dotnet/orleans/issues/8035

Upgraded 'Adventure' samples

---

samples/Blazor/BlazorServer/BlazorServer.csproj
samples/Blazor/BlazorServer/Grains/ITodoGrain.cs
samples/Blazor/BlazorServer/Grains/ITodoManagerGrain.cs
samples/Blazor/BlazorServer/Grains/IWeatherGrain.cs
samples/Blazor/BlazorServer/Grains/TodoGrain.cs
samples/Blazor/BlazorServer/Grains/TodoManagerGrain.cs
samples/Blazor/BlazorServer/Grains/WeatherGrain.cs
samples/Blazor/BlazorServer/Models/TodoItem.cs
samples/Blazor/BlazorServer/Models/TodoNotification.cs
samples/Blazor/BlazorServer/Models/WeatherInfo.cs
samples/Blazor/BlazorServer/Program.cs
samples/Blazor/BlazorServer/Services/TodoService.cs
samples/Blazor/BlazorServer/Services/WeatherForecastService.cs

Upgrade 'Blazor Server' sample

---

samples/Blazor/BlazorWasm/BlazorWasm.Client/BlazorWasm.Client.csproj
samples/Blazor/BlazorWasm/BlazorWasm.Client/Properties/launchSettings.json
samples/Blazor/BlazorWasm/BlazorWasm.Server/Api/TodoController.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Api/WeatherController.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/BlazorWasm.Server.csproj
samples/Blazor/BlazorWasm/BlazorWasm.Server/Grains/ITodoGrain.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Grains/ITodoManagerGrain.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Grains/IWeatherGrain.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Grains/TodoGrain.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Grains/TodoManagerGrain.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Grains/WeatherGrain.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Models/TodoItem.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Models/TodoNotification.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Models/WeatherInfo.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Program.cs
samples/Blazor/BlazorWasm/BlazorWasm.Server/Properties/launchSettings.json

Related to https://github.com/dotnet/orleans/issues/8035

Upgrade 'Blazor Wasm' sample

---

samples/FSharpHelloWorld/Grains/Grains.fsproj
samples/FSharpHelloWorld/Grains/HelloGrain.fs
samples/FSharpHelloWorld/HelloWorld/HelloWorld.csproj
samples/FSharpHelloWorld/HelloWorld/Program.cs
samples/FSharpHelloWorld/HelloWorldInterfaces/HelloWorldInterfaces.csproj
samples/FSharpHelloWorld/HelloWorldInterfaces/IHelloGrain.cs

Upgrade 'F# Hello World' sample (compiles but exception when ran)
Related to #8035

Upgrade 'F# Hello World' sample

---

samples/TicTacToe/Controllers/GameController.cs
samples/TicTacToe/Controllers/HomeController.cs
samples/TicTacToe/Grains/GameGrain.cs
samples/TicTacToe/Grains/IGameGrain.cs
samples/TicTacToe/Grains/IPairingGrain.cs
samples/TicTacToe/Grains/IPlayerGrain.cs
samples/TicTacToe/Grains/PairingGrain.cs
samples/TicTacToe/Grains/PlayerGrain.cs
samples/TicTacToe/Program.cs
samples/TicTacToe/TicTacToe.csproj

Upgrade 'Tic Tac Toe' sample

---

samples/TransportLayerSecurity/TLS.Client/Program.cs
samples/TransportLayerSecurity/TLS.Client/TLS.Client.csproj
samples/TransportLayerSecurity/TLS.Contracts/TLS.Contracts.csproj
samples/TransportLayerSecurity/TLS.Server/HelloGrain.cs
samples/TransportLayerSecurity/TLS.Server/Program.cs
samples/TransportLayerSecurity/TLS.Server/TLS.Server.csproj

Upgrade 'TLS' sample

---

samples/Presence/src/Grains/PresenceGrain.cs

Fix a typo

---

src/Orleans.BroadcastChannel/Hosting/ChannelHostingExtensions.cs

Fix configuration of BroadcastChannel

---

samples/Streaming/Common/Common.csproj
samples/Streaming/CustomDataAdapter/GrainInterfaces/GrainInterfaces.csproj
samples/Streaming/CustomDataAdapter/GrainInterfaces/IConsumerGrain.cs
samples/Streaming/CustomDataAdapter/Grains/ConsumerGrain.cs
samples/Streaming/CustomDataAdapter/Grains/Grains.csproj
samples/Streaming/CustomDataAdapter/NonOrleansClient/NonOrleansClient.csproj
samples/Streaming/CustomDataAdapter/Silo/CustomDataAdapter.cs
samples/Streaming/CustomDataAdapter/Silo/Program.cs
samples/Streaming/CustomDataAdapter/Silo/Silo.csproj
samples/Streaming/Simple/Client/Client.csproj
samples/Streaming/Simple/Client/Program.cs
samples/Streaming/Simple/GrainInterfaces/GrainInterfaces.csproj
samples/Streaming/Simple/GrainInterfaces/IConsumerGrain.cs
samples/Streaming/Simple/GrainInterfaces/IProducerGrain.cs
samples/Streaming/Simple/Grains/ConsumerGrain.cs
samples/Streaming/Simple/Grains/Grains.csproj
samples/Streaming/Simple/Grains/ProducerGrain.cs
samples/Streaming/Simple/SiloHost/Program.cs
samples/Streaming/Simple/SiloHost/SiloHost.csproj

Upgrade 'Streaming' samples

---

.azure/pipelines/build.yaml

[3.x] Fix version prefix during nuget pack

---

samples/Stocks/IStockGrain.cs
samples/Stocks/Program.cs
samples/Stocks/StockGrain.cs
samples/Stocks/Stocks.csproj
samples/Stocks/StocksHostedService.cs

Upgrade 'Stocks' sample

---

samples/Chirper/Chirper.Grains/Chirper.Grains.csproj

Fix the bug in the Chirper sample code

---

test/Transactions/Orleans.Transactions.Azure.Test/FaultInjection/ControlledInjection/TransactionFaultInjectionTests.cs

Add TransactionFaultInjectionTests to Functional runs

---

samples/README.md

Fix images, use raw URLs from dependent repo

---

.azure/pipelines/build.yaml

[3.x] Always run scheduled build

---

.azure/pipelines/build.yaml

Always run scheduled build

---

src/Orleans.Runtime/Silo/Watchdog.cs

When the watchdog detects a stalled heartbeat, it currently says the cause of the delay is "Possibly GC?". With this PR, we'll instead show the actual GC pause time since the last tick.

Report GC pause duration when heartbeat is stalled

---

.azure/pipelines/build.yaml

Set VersionPrefix in nuget pack step

---

src/Redis/Orleans.Clustering.Redis/Providers/RedisClusteringOptions.cs
src/Redis/Orleans.Reminders.Redis/Providers/RedisReminderTableOptions.cs

Fix Issue #8325 redis options-validators unable to resolve options

---

src/Orleans.Serialization/TypeSystem/ITypeConverter.cs

xref https://github.com/dotnet/orleans/issues/8276#issuecomment-1440802377

Improve doc comments for ITypeFilter and ITypeNameFilter

---

src/Orleans.Core/Serialization/OrleansJsonSerializer.cs

Fix for Issue #8322 Questionable test/cast pair in OrleansJsonSerializer.cs

---

.azure/pipelines/build.yaml
build.ps1

[3.x] Include executables in code signing process

---

src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorage.cs

Fixes break introduced by #7849

Fix construction of AzureBlobGrainStorage

---

samples/README.md

Adding:  Link to an example of a F# reminder grain

Update samples README

---

src/Orleans.Runtime/MembershipService/LocalSiloHealthMonitor.cs

Adding missing display character

---

src/Orleans.Core/Configuration/Options/ClusterMembershipOptions.cs

Documentation fix

---

src/Orleans.Transactions/State/TransactionQueue.cs

[3.x] In TransactionQueue, ensure `readyTask` failures are recovered from

---

src/Orleans.Core.Abstractions/Placement/HashBasedPlacement.cs
src/Orleans.Core.Abstractions/Placement/PlacementAttribute.cs

Drive-by change to improve doc comments on placement strategies.

Clean up doc comments for placement strategies

---

README.md

Make discord links more prominent

---

test/Orleans.Serialization.UnitTests/PooledBufferTests.cs

Add regression test for #8503

---

src/Orleans.Serialization/Buffers/PooledBuffer.cs

Also adds some additional comments and deduplicates some code.

Fix double-free when returning pooled buffers

---

src/Azure/Orleans.Persistence.Cosmos/CosmosGrainStorage.cs
test/Extensions/Tester.Cosmos/PersistenceGrainTests_CosmosGrainStorage.cs
test/Extensions/Tester.Cosmos/PersistenceProviderTests_Cosmos.cs

Fix Cosmos DB grain storage constructor for DI

---

test/Orleans.Serialization.UnitTests/GeneratedSerializerTests.cs
test/Orleans.Serialization.UnitTests/Models.cs

Add test for serializing types derived from Dictionary<K,V>

---

src/Orleans.Analyzers/GenerateSerializationAttributesCodeFix.cs

Fix `UsingDirective` insertion in `[NonSerialized]` codefix

---

src/Orleans.CodeGenerator/Model/SerializableTypeDescription.cs
src/Orleans.Runtime/Catalog/GrainTypeSharedContext.cs
test/Orleans.Serialization.UnitTests/GeneratedSerializerTests.cs
test/Orleans.Serialization.UnitTests/Models.cs
test/Orleans.Serialization.UnitTests/Properties/IsExternalInit.cs
test/Orleans.Serialization.UnitTests/Properties/RequiredMemberAttribute.cs

Add serializer support for `required` members

---

src/Orleans.Core/GrainDirectory/IDhtGrainDirectory.cs
src/Orleans.Runtime/Catalog/GrainTypeSharedContext.cs
src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
src/Orleans.Runtime/GrainDirectory/RemoteGrainDirectory.cs
src/Orleans.Streaming/PubSub/PubSubPublisherState.cs
test/NonSilo.Tests/Directory/MockLocalGrainDirectory.cs

Fix capitalization and formatting for PubSubPublisherState

---

src/Orleans.BroadcastChannel/SubscriberTable/Predicates/ImplicitChannelSubscriptionAttribute.cs
src/Orleans.Streaming/Predicates/StreamSubscriptionAttributes.cs

Highlight regex syntax in `[RegexImplicitChannelSubscription(...)]` and `[RegexImplicitStreamSubscription(...)]`

---

src/Orleans.Runtime/Catalog/GrainTypeSharedContext.cs

Fix nullability compiler warning on new SDKs

---

src/Orleans.CodeGenerator/LibraryTypes.cs

Supersedes part of https://github.com/dotnet/orleans/pull/8471

Address all IDE0044. Readonly fields where applicable.

---

src/Redis/Orleans.Reminders.Redis/Hosting/SiloBuilderReminderExtensions.cs

Fixes #8446
Thank you for pointing this out, @snovak7

Ensure reminder services are added when adding Redis reminders

---

src/Orleans.Runtime/Catalog/ActivationData.cs

* Do not overwrite the more specific `DeactivationReason` set when there is an activation race with a generic (exception path) reason.
* Only log a warning message if registration failed due to an exception. If there was an activation race, do not log a warning (only a log a debug-level message)

Do not override deactivation reason when activation registration fails due to existing activation

---

src/Orleans.Analyzers/GenerateGenerateSerializerAttributeAnalyzer.cs

ORLEANS0005 message arg fix

---

src/Orleans.Runtime/Storage/StateStorageBridge.cs
src/Orleans.Serialization/Activators/DefaultActivator.cs
src/Orleans.Serialization/Serializers/CodecProvider.cs
test/DefaultCluster.Tests/SerializationTests/SerializationTests.cs
test/Grains/TestGrainInterfaces/IValueTypeTestGrain.cs
test/Grains/TestInternalGrains/PersistenceTestGrains.cs
test/TesterInternal/StorageTests/PersistenceGrainTests.cs

Add value type support to IActivator #8682

---

src/Orleans.EventSourcing/Hosting/CustomStorageSiloBuilderExtensions.cs
src/Orleans.EventSourcing/Hosting/LogConsistencyProtocolSiloBuilderExtensions.cs
src/Orleans.EventSourcing/Hosting/LogStorageSiloBuilderExtensions.cs
src/Orleans.EventSourcing/Hosting/StateStorageSiloBuilderExtensions.cs

Add ILogConsistencyProtocolServices factory for all log consistency providers (#8157)

---

src/Orleans.Runtime/Facet/Persistent/PersistentStateAttribute.cs

Throw if PersistentStateAttribute.StateName is null (#8708)

---

src/Orleans.Runtime/Catalog/ActivationData.cs

small refactoring grain delay activation

Simplify `DelayDeactivation` logic

---

src/Orleans.Analyzers/AnalyzerReleases.Shipped.md
src/Orleans.Analyzers/GenerateAliasAttributesAnalyzer.cs

Add ORLEANS0010 to AnalyzerReleases.Shipped

---

src/Orleans.Core/Utils/LRU.cs
test/NonSilo.Tests/General/LruTest.cs

[7.x] Correctly count number of items in LRU (#8742)

---

src/Orleans.Runtime/Silo/Silo.cs

[7.x] Fix exception caused by a log message (#8558) (#8701)

---

src/Orleans.Serialization/Codecs/StackCodec.cs
test/Orleans.Serialization.UnitTests/BuiltInCodecTests.cs

Fix stack deserialization order

---

Directory.Packages.props

NuGet will complain at us if we try to create a stable package which references prerelease packages.

Update to stable build packages

---

src/Orleans.Core.Abstractions/Concurrency/GrainAttributeConcurrency.cs

Clarify [AlwaysInterleave] interleaves with anything, including itself

---

README.md

Update README.md to include new nightly build feed details

---

src/Redis/Orleans.Clustering.Redis/Hosting/RedisClusteringProviderBuilder.cs
src/Redis/Orleans.GrainDirectory.Redis/Hosting/RedisGrainDirectoryProviderBuilder.cs
src/Redis/Orleans.Persistence.Redis/Hosting/RedisGrainStorageProviderBuilder.cs
src/Redis/Orleans.Reminders.Redis/Hosting/RedisRemindersProviderBuilder.cs

Add default Redis options when Redis is configured via keyed service

---

Directory.Packages.props
src/Orleans.Analyzers/AliasClashAttributeAnalyzer.cs
src/Orleans.Analyzers/IdClashAttributeAnalyzer.cs
src/Orleans.Analyzers/IncorrectAttributeUseAnalyzer.cs

Fixes #8806.
We can consider updating again later. Until then, this is a papercut for some users.

Downgrade Microsoft.CodeAnalyis to v4.5.0

---

src/Orleans.Core/Lifecycle/MigrationContext.cs
src/Orleans.Runtime/Catalog/ActivationMigrationManager.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Serialization/Codecs/ByteArrayCodec.cs
test/DefaultCluster.Tests/Migration/MigrationTests.cs
test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs
test/Orleans.Serialization.UnitTests/PooledBufferTests.cs

Fix `PooledBuffer` serialization

---

src/Orleans.Serialization/Buffers/Writer.cs

Supersedes part of https://github.com/dotnet/orleans/pull/8471

Address IDE0038. Use pattern matching.

---

src/Orleans.Core.Abstractions/Runtime/RuntimeContext.cs
src/Orleans.Runtime/Activation/ActivationDataActivatorProvider.cs
src/Orleans.Runtime/Core/SystemTarget.cs
src/Orleans.Runtime/Scheduler/ActivationTaskScheduler.cs
src/Orleans.Runtime/Scheduler/ClosureWorkItem.cs
src/Orleans.Runtime/Scheduler/RequestWorkItem.cs
src/Orleans.Runtime/Scheduler/TaskSchedulerUtils.cs
src/Orleans.Runtime/Scheduler/WorkItemGroup.cs

[Backport] Always reset RuntimeContext to previous value after use (#8864)

---

SUPPORT.md

Update SUPPORT.md to reflect the fact that Orleans is now officially supported by Microsoft

Orleans is now officially supported by Microsoft

---

src/Orleans.Runtime/Catalog/StatelessWorkerGrainContext.cs

Avoid over-counting stateless worker activations

---

src/Orleans.Runtime/Placement/PlacementStrategyResolver.cs

Fix StatelessWorker MaxLocal for Orleans 7.x

---

src/Orleans.Runtime/Scheduler/WorkItemGroup.cs
test/NonSilo.Tests/Directory/DhtGrainLocatorTests.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs
test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerBasicTests.cs
test/NonSilo.Tests/SchedulingHelper.cs

This is a test code fix to fix `MultipleMixedDeactivations` and guards against the issue.

Guard against null grain context in test code

---

src/Orleans.Runtime/Catalog/StatelessWorkerGrainContext.cs

(cherry picked from commit 9ee8817dc23412f4f0a9865c50f6295c4390d58e)

[7.x] Avoid over-counting stateless worker activations (#8886)

---

.azure/pipelines/build.yaml
.azure/pipelines/nightly-main.yaml
.azure/pipelines/templates/build.yaml
.github/workflows/ci.yml
test/Tester/LogFomatterTests.cs

Migrate to build template

---

.azure/pipelines/nightly-main.yaml
.azure/pipelines/templates/build.yaml

Fix build template for nightly

---

.azure/pipelines/github-mirror.yaml

Add mirror pipeline

---

.azure/pipelines/templates/build.yaml

Fix nightly nuget publishing

---

.azure/pipelines/github-mirror.yaml

Fix mirror pipeline

---

.azure/pipelines/github-mirror.yaml

Do not trigger mirror for PR

---

test/Orleans.Serialization.UnitTests/GeneratedSerializerTests.cs
test/Orleans.Serialization.UnitTests/InvokableTestInterfaces.cs
test/Orleans.Serialization.UnitTests/Models.cs
test/Orleans.Serialization.UnitTests/TypeEncodingTests.cs

Add more tests for [Alias("x")] attribute

---

src/AdoNet/Orleans.Persistence.AdoNet/Options/AdoNetGrainStorageOptions.cs
src/AdoNet/Shared/Storage/OrleansRelationalDownloadStream.cs
src/Orleans.EventSourcing/CustomStorage/ICustomStorageInterface.cs
src/Orleans.EventSourcing/CustomStorage/LogConsistencyProvider.cs
src/Orleans.EventSourcing/JournaledGrain.cs
src/Orleans.EventSourcing/LogConsistency/ILogViewAdaptorFactory.cs
src/Orleans.EventSourcing/LogStorage/LogStateWithMetaData.cs
src/Orleans.EventSourcing/StateStorage/GrainStateWithMetaData.cs
src/Orleans.EventSourcing/StateStorage/LogConsistencyProvider.cs
src/Orleans.Reminders/Hosting/SiloBuilderReminderMemoryExtensions.cs
src/Orleans.Runtime/Configuration/Options/SiloMessagingOptions.cs

This PR fixes some reference documentation API warnings and cleans up some issues found along the way.

Fix some reference documentation warnings

---

src/Orleans.Core/Timers/SafeTimerBase.cs
src/Orleans.Runtime/Core/SystemTarget.cs
src/Orleans.Runtime/Timers/GrainTimer.cs
src/Orleans.Runtime/Timers/TimerRegistry.cs

Port of #8950 to 7.x
(cherry picked from commit 2b50ea158d71a8460e5a613558dbe5c203a524f1)

Fix potential grain timer deadlock during disposal

---

Directory.Packages.props
NuGet.Config

Use dotnet-public instead of nuget.org

---

src/Orleans.Sdk/build/Microsoft.Orleans.Sdk.targets

Add Orleans.Runtime to implicit usings

---

src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Silo/Silo.cs
src/Orleans.Runtime/Silo/Watchdog.cs

Stop watchdog when container is disposed

---

src/Orleans.Runtime/Silo/Silo.cs

Stop silo on Dispose

---

src/Orleans.Runtime/MembershipService/ClusterHealthMonitor.cs
src/Orleans.Runtime/MembershipService/IRemoteSiloProber.cs
src/Orleans.Runtime/MembershipService/MembershipAgent.cs
src/Orleans.Runtime/MembershipService/MembershipSystemTarget.cs
src/Orleans.Runtime/MembershipService/RemoteSiloProber.cs
src/Orleans.Runtime/MembershipService/SiloHealthMonitor.cs
test/NonSilo.Tests/Membership/SiloHealthMonitorTests.cs

Dispose cluster & silo health monitors are disposed when host is disposed, and clean up code

---

src/Orleans.Runtime/ConsistentRing/ConsistentRingProvider.cs
src/Orleans.Runtime/ConsistentRing/VirtualBucketsRingProvider.cs
src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
src/Orleans.Runtime/Silo/Silo.cs
test/NonSilo.Tests/General/RingTests_Standalone.cs
test/TesterInternal/LivenessTests/ConsistentRingProviderTests.cs

Unsubscribe `ConsistentRingProvider` & `VirtualBucketsRingProvider` from `ISiloStatusOracle` on shutdown

---

src/Orleans.Runtime/Versions/SingleWaiterAutoResetEvent.cs

Avoid unnecessary `Interlocked.Or` in `SingleWaiterAutoResetEvent`

---

src/Orleans.Serialization/Codecs/DictionaryCodec.cs
src/Orleans.Serialization/Codecs/HashSetCodec.cs
src/Orleans.Serialization/Codecs/ListCodec.cs
test/Orleans.Serialization.UnitTests/BuiltInCodecTests.cs
test/Orleans.Serialization.UnitTests/GeneratedSerializerTests.cs

Add serialization support for types derived from `List<T>` and `HashSet<T>`

---

samples/README.md

Update samples README.md to point to samples repo & explorer

---

src/Orleans.Runtime/Catalog/ActivationMigrationManager.cs

Fix termination condition in ActivationMigrationManager.AcceptMigratingGrains

---

src/AdoNet/Orleans.Streaming.AdoNet/Orleans.Streaming.AdoNet.csproj

Mark Orleans.Streaming.AdoNet as alpha

---

Directory.Packages.props
test/Extensions/TesterAdoNet/Tester.AdoNet.csproj

Update Microsoft.Build dependency and Force System.Drawing.Common version because of MySql.Data

Update Microsoft.Build dependency

---

src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs

Fixes https://github.com/dotnet/orleans/issues/9044

Avoid logging error monitoring k8s pods on restart

---

src/Orleans.Runtime/Catalog/ActivationData.cs

ActivationData: get IGrainActivator from shared components consistently

---

src/Orleans.Runtime/Catalog/StatelessWorkerGrainContext.cs

There are some places in `StatelessWorkerGrainContext` where a work item is enqueued, but the pump task is not signaled. The result is that there may be a long delay before the work item is processed or it may never be processed.

StatelessWorker: pump work item queue consistently

---

.azure/pipelines/nightly-main.yaml
.azure/pipelines/templates/build.yaml

Enable nightly on dnceng

---

.azure/pipelines/templates/vars.yaml

Disable warning for GitHub PR builds

Set GDN_SUPPRESS_FORKED_BUILD_WARNING to true

---

src/Orleans.Core.Abstractions/IDs/IdSpan.cs

Throw exception on null/empty/whitespace key for `IGrainWithStringKey`

---

src/Orleans.Runtime/Catalog/ActivationData.cs
test/DefaultCluster.Tests/Migration/MigrationTests.cs

This PR lets grains declare that they want to migrate to a different host while they are in the process of being deactivated.

 Support triggering migration during deactivation

---

src/Orleans.TestingHost/InMemoryTransport/InMemoryTransportConnection.cs

InMemoryTransportConnection: graceful tear down

---

src/Orleans.Serialization/Codecs/ByteArrayCodec.cs
test/Orleans.Serialization.UnitTests/BuiltInCodecTests.cs

Add BitArray serialization codec

---

src/Orleans.Runtime/Silo/SiloControl.cs

#9120 introduced a NullReferenceException which was caught by private CI

Fix NRE in SiloControl introduced by #9120

---

.azure/pipelines/nightly-main.yaml

Enable TSA upload

---

src/Orleans.Core/Lifecycle/LifecycleSubject.cs
src/Orleans.Runtime/Catalog/ActivationData.cs
src/Orleans.Runtime/Catalog/Catalog.cs
src/Orleans.Runtime/Core/ManagementGrain.cs
src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs
src/Orleans.Runtime/MembershipService/ClusterMembershipSnapshot.cs
src/Orleans.Runtime/MembershipService/MembershipAgent.cs
src/Orleans.Runtime/MembershipService/MembershipSystemTarget.cs
src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
src/Orleans.Runtime/Silo/SiloControl.cs

This PR reduces inactionable log noise and improves the formatting of some logs

Reduce log noise and improve formatting

---

src/Orleans.Core/Statistics/EnvironmentStatistics.cs

Change EventCounterIntervalSec to 1 sec to fix issue caused in dotnet-counters

---

src/Orleans.TestingHost/TestClusterHostFactory.cs

Disable warning in TestClusterHostFactory

---

.azure/pipelines/templates/build.yaml

Use PME service connection for signing

---

.azure/pipelines/build.yaml
.azure/pipelines/nightly-main.yaml

Move nuget publishing to the 'nightly' build pipeline
