dotnet/orleans

- test/Benchmarks/Benchmarks.csproj
No need to target 2.2 at this point as that increases friction with compiling sources.
> Downgrade Benchmark to target netcoreapp2.1 instead of 2.2

- test/Extensions/TesterAzureUtils/Persistence/PersistenceStateTests_AzureBlobStore.cs
- test/Extensions/TesterAzureUtils/Persistence/PersistenceStateTests_AzureTableGrainStorage.cs
- test/Grains/TestInternalGrains/PersistentStateTestGrains.cs
Fixed function persistence tests broken when IPersistentState facet was introduced.
> Fixed function persistence tests

- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBMembershipTable.cs
- src/AdoNet/Orleans.Clustering.AdoNet/Messaging/AdoNetClusteringTable.cs
- src/Azure/Orleans.Clustering.AzureStorage/AzureBasedMembershipTable.cs
- src/Azure/Orleans.Clustering.AzureStorage/OrleansSiloInstanceManager.cs
- src/Orleans.Clustering.Consul/ConsulBasedMembershipTable.cs
- src/Orleans.Clustering.ZooKeeper/ZooKeeperBasedMembershipTable.cs
- src/Orleans.Core/Configuration/Options/ClusterMembershipOptions.cs
- src/Orleans.Core/Logging/ErrorCodes.cs
- src/Orleans.Core/SystemTargetInterfaces/IMembershipTable.cs
- src/Orleans.Runtime/MembershipService/MembershipOracle.cs
- src/Orleans.Runtime/MembershipService/SystemTargetBasedMembershipTable.cs
- test/Extensions/TesterAzureUtils/SiloInstanceTableManagerTests.cs
- test/NonSilo.Tests/SiloHostBuilderTests.cs
Right now, we don't delete old entries in the membership table, and that can be an issue since it will grow forever. 
This PR enable deleting old silo entries, and implement it in the azure membership provider. Other providers still need to implement this logic.
> Enable "cleaning" of all dead entries in the membership table

- src/Orleans.Core/Messaging/Message.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Runtime/Core/Dispatcher.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- test/Grains/TestGrainInterfaces/ITestGrain.cs
- test/Grains/TestInternalGrains/TestGrain.cs
- test/Tester/OneWayDeactivationTests.cs
Fixes #4896
When a OneWay message is destined for a defunct activation, send a rejection response for the purpose of cache invalidation. This rejection is sent even though the message may be forwarded on to a new activation simultaneously. The rejection is ignored by the receiver after the cache invalidation headers have been inspected.
> Fix OneWay cache invalidation

- test/NonSilo.Tests/SiloHostBuilderTests.cs
- Had not set up the `LoadSheddingValidator` in `SiloHostBuilder_LoadSheddingValidatorPassesWhenLoadSheddingDisabled`
- `SiloHostBuilder_LoadSheddingValidatorFailsWithNoRegisteredHostEnvironmentStatistics` was failing expectedly, but for the wrong reason. Corrected test to pass under `LoadSheddingOptions` configuration, but to fail under the lack of a registered `IHostEnvironmentStatistics` - which was the intention of the test.
> Correcting arrangement in a few LoadSheddingValidator tests

- src/Documentation/clusters_and_clients/configuration_guide/server_configuration.md
In the source version of this document under the header Orleans Clustering Information the documentation described the ClusterId as being set to "my-first-cluster", but the example code above this documentation was setting ClusterId to "orleans-docker". The example code has been updated to set the ClusterId to "my-first-cluster" in line with the documentation. 
In the same section ServiceId was being described as set to "AspNetSampleApp", but in the Server Configuration section the example code was setting ServiceId to "MyAwesomeOrleansService". This example code has been updated to set the ServiceId to "AspNetSampleApp" in line with the documentation.
> Fix inconsistencies between docs and examples

- Samples/2.2/Chirper/Chirper.Client/Chirper.Client.csproj
- Samples/2.2/Chirper/Chirper.Client/ChirperConsoleViewer.cs
- Samples/2.2/Chirper/Chirper.Client/Program.cs
- Samples/2.2/Chirper/Chirper.Client/Shell.cs
- Samples/2.2/Chirper/Chirper.Grains.Interfaces/Chirper.Grains.Interfaces.csproj
- Samples/2.2/Chirper/Chirper.Grains.Interfaces/EnumerableExtensions.cs
- Samples/2.2/Chirper/Chirper.Grains.Interfaces/IChirperAccount.cs
- Samples/2.2/Chirper/Chirper.Grains.Interfaces/IChirperPublisher.cs
- Samples/2.2/Chirper/Chirper.Grains.Interfaces/IChirperSubscriber.cs
- Samples/2.2/Chirper/Chirper.Grains.Interfaces/IChirperViewer.cs
- Samples/2.2/Chirper/Chirper.Grains.Interfaces/Models/ChirperMessage.cs
- Samples/2.2/Chirper/Chirper.Grains/Chirper.Grains.csproj
- Samples/2.2/Chirper/Chirper.Grains/ChirperAccount.cs
- Samples/2.2/Chirper/Chirper.Grains/StringExtensions.cs
- Samples/2.2/Chirper/Chirper.Silo/Chirper.Silo.csproj
- Samples/2.2/Chirper/Chirper.Silo/Program.cs
- Samples/2.2/Chirper/Chirper.sln
This PR implements the v1.x Chirper sample on Orleans v2.2.
- .NET Core 2.1.
- The newer host builder components are used but not the generic host integration yet.
- Command line client rebuilt for simplicity.
- ChirperAccount grain key changed to string (for username) for demo simplicity.
- Legacy ObserverManager replaced with an internal collection.
- Network load generators *not* migrated as they appear to depend on windows-only performance counters.
Legacy files from 1.x have not been touched. Only new files for v2.2 are added.
There's more improvements that could be done, e.g. removing aged-out observers, but not sure it is warranted on a sample. That said, happy to apply fixes or improvements as needed.
> Implementing Chirper Sample on v2.2

- Directory.Build.props
Reverts dotnet/orleans#5441
For some reason it seems to break our code signing infra...
> Revert "Stop packing *.symbols.nupkg packages"

- src/Documentation/implementation/index.md
the file was referring to streams_implementation and had appropriate text although the description was about testing. Added proper link and copy
> - fixed index.md in /implementation

- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
> Fix upper-case typo in warning log

- src/Orleans.Runtime/Hosting/GrainCallFilterExtensions.cs
Following the changes in 2.3.0, ISiloBuilder had no extension methods to add incoming grain filters.
> Add Incoming grain call filter extensions for ISiloBuilder

- src/Orleans.Core.Abstractions/Streams/Extensions/StreamSubscriptionHandleExtensions.cs
- test/Grains/TestGrains/GeneratedEventCollectorGrain.cs
Updated stream subscription handle extension functions to handle batch consumption, complerable to what is supported for subscribe.
> Subscription handle extensions for batch consumption

- src/Documentation/grains/grain_lifecycle.md
Removed redundant white-space and fixed case of a method's name.
> Remove redundant white-space from grain_lifecycle.md

- src/AdoNet/Shared/SQLServer-Main.sql
Add square bracket delimiters to allow database names that contain special characters.
> Add square bracket delimiters

- test/Extensions/TesterAzureUtils/Streaming/AQClientStreamTests.cs
- test/Extensions/TesterAzureUtils/Streaming/AQProgrammaticSubscribeTest.cs
- test/Extensions/TesterAzureUtils/Streaming/AQStreamFilteringTests.cs
- test/Extensions/TesterAzureUtils/Streaming/AQSubscriptionMultiplicityTests.cs
- test/Extensions/TesterAzureUtils/Streaming/AQSubscriptionObserverWithImplicitSubscribingTests.cs
- test/Extensions/TesterAzureUtils/Streaming/AzureQueueAdapterTests.cs
- test/Extensions/TesterAzureUtils/Streaming/DelayedQueueRebalancingTests.cs
- test/Extensions/TesterAzureUtils/Streaming/HaloStreamSubscribeTests.cs
- test/Extensions/TesterAzureUtils/Streaming/SampleAzureQueueStreamingTests.cs
- test/Extensions/TesterAzureUtils/Streaming/StreamLifecycleTests.cs
- test/Extensions/TesterAzureUtils/Streaming/StreamLimitTests.cs
- test/Extensions/TesterAzureUtils/Streaming/StreamReliabilityTests.cs
When a test is skipped due to a precondition check failure there is a `NullReferenceException` thrown in `Dispose` because initialization has not occurred.
This avoids the Dispose logic in some streaming tests when initialization did not occur.
> Skip Dispose for skipped streaming tests

- src/index.md
I just noticed there was a missing paren; this PR adds it.
> Fix link to Message Delivery Guarantees in docs.

- src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
- src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs
- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
- src/Orleans.Core/CodeGeneration/IGrainState.cs
- src/Orleans.Core/Core/ClusterClient.cs
- src/Orleans.EventSourcing/LogStorage/LogStateWithMetaData.cs
- src/Orleans.EventSourcing/StateStorage/GrainStateWithMetaData.cs
- src/OrleansProviders/Storage/MemoryStorageGrain.cs
- test/DefaultCluster.Tests/MemoryStorageProviderTests.cs
Prevent NullReferenceException with some storage providers when state is Nullable<T> (#5570)
Accommodate existing RequestContext.PropagateActivityId value in ClusterClient (#5575)
> Cherry-pick #5570 and #5575 for 2.3.2

- src/Orleans.CodeGenerator.MSBuild/Orleans.CodeGenerator.MSBuild.csproj
The `.Tasks.*` files are already included and including them multiple times causes a packaging warning
> Fix packaging warning in Orleans.CodeGenerator.MSBuild

- src/Orleans.Core.Legacy/Configuration/NodeConfiguration.cs
- src/Orleans.Core/Configuration/Options/PerformanceTuningOptions.cs
- src/Orleans.Runtime.Legacy/Configuration/LegacyClusterConfigurationExtensions.cs
- src/Orleans.Runtime/Silo/Silo.cs
Set defaults to 0 (no minimum set)
During development of #5436, the default value for these thread pools was found to be a detrimental to throughput.
It is better to avoid setting a minimum and instead allow users to follow general .NET guidance on setting thread pool limits.
> Provide separate options for worker & IO pool min thread counts

- src/Orleans.Core/Core/ClientBuilder.cs
- src/Orleans.Core/Core/ClusterClient.cs
- src/Orleans.Core/Hosting/ApplicationLifetime.cs
- src/Orleans.Runtime/Hosting/Generic/SiloHostBuilder.cs
- src/Orleans.Runtime/Hosting/Generic/SiloWrapper.cs
This is a pre-requisite for #5436, which uses `IApplicationLifetime` (from shared Hosting package) to ensure all connections are closed during shutdown.
This aligns `ClusterClient` and `SiloHostBuilder` more closely with the generic `HostBuilder` from `Microsoft.Extensions.Hosting`.
> Implement IApplicationLifetime for ClientBuilder/SiloHostBuilder

- src/Orleans.Core/Serialization/BuiltInTypes.cs
- test/NonSilo.Tests/Serialization/SerializationTests.ImmutableCollections.cs
`ImmutableArray<T>` is a value type and the default value will throw `NullReferenceException` when the `Length` property is read. The serializer will read this property to determine how many elements in the array should be written to the stream making it impossible to serialize `default(ImmutableArray<T>)`.
This change ensures that `default(ImmutableArray<T>)` can be serialized without throwing a `NullReferenceException`. The value `default(ImmutableArray<T>)` is indicated by writing `-1` as the length of the array to the stream. Note that `ImmutableArray<T>.Empty` has a length of `0` so the code is able to distinguish between the two values.
The deserializer will make a call to `context.RecordObject`. I do not quite understand the purpose of this call and if it is meaningful to do with a …
> Allow default(ImmutableArray<T>) to be serialized

- src/Orleans.TestingHost/TestCluster.cs
```await this.InternalClient?.Close();``` and similar causes NRE when ```InternalClient``` is null, because we are trying to await null Task.
> Fix NRE in TestCluster.cs

- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
This is to prevent exceptions from Azure Storage SDK when Delete is called with `Etag=null`, i.e. when state for that grain hasn't been written to the storage.
Closes #5219
> NoOp delete when ETag is null in AzureTableStorage provider

- src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
A [recent change](https://github.com/aspnet/Extensions/pull/1100) in `Microsoft.Extensions.Hosting.Abstractions` caused our Generic Host support to [fail during startup](https://github.com/dotnet/orleans/issues/5431) with a `MissingMethodException`, requiring a [workaround](https://gist.github.com/ReubenBond/ce04b0c662e622f29382cd620210bf7d) to remove the code which referenced the changed method.
This PR removes the code which relied on that method, resolving the breakage.
> Fix breakage in Microsoft.Extensions.Hosting.Abstractions

- src/Orleans.Core.Abstractions/Serialization/IBinaryTokenStreamReader.cs
- src/Orleans.Core.Abstractions/Serialization/IBinaryTokenStreamWriter.cs
- src/Orleans.Core/Messaging/IncomingMessageBuffer.cs
- src/Orleans.Core/Messaging/Message.cs
- src/Orleans.Core/Serialization/BinaryTokenStreamReader.cs
- src/Orleans.Core/Serialization/BinaryTokenStreamWriter2.cs
- src/Orleans.Core/Serialization/ILBasedExceptionSerializer.cs
- src/Orleans.Core/Serialization/ILSerializerGenerator.cs
- src/Orleans.Core/Serialization/OrleansJsonSerializer.cs
- src/Orleans.Core/Serialization/SerializationContext.cs
- src/Orleans.Core/Serialization/SerializationContextBase.cs
- test/NonSilo.Tests/Serialization/ILBasedExceptionSerializerTests.cs
- test/NonSilo.Tests/Serialization/ILBasedSerializerTests.cs
- test/Tester/SerializationTests/SerializationTestsUtils.cs
This is a pre-requisite for #5436 and lays some groundwork for a more span-friendly serializer (networking replat is based on pipes which use Span<byte>/Memory<byte>)
> Groundwork for span-friendly serialization

- src/TelemetryConsumers/Orleans.TelemetryConsumers.Linux/LinuxEnvironmentStatistics.cs
Don't know how I missed this (been using a different implementation internally).
Has coincidentally worked for `MemTotal` since it's at the top of the file but doesnt work for `MemAvailable`.
Sorry about this
> Fix ReadLineStartingWithAsync for LinuxEnvironmentStatistics

- src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets
This PR targets the reflection-based code generator.
When a file is removed from a project, we should re-run code generation.
We should also ignore the generated `$(ProjectName).orleans.g.cs` file when determining whether or not to run code generation.
The focus of the PR is the added text, but I also updated the naming conventions to be inline with the Roslyn-based code generator's targets file.
> Rebuild when files are removed from a project

- src/Orleans.Core/Logging/ErrorCodes.cs
- src/Orleans.Core/Timers/ValueStopwatch.cs
- src/Orleans.Runtime/Configuration/Options/SchedulingOptions.cs
- src/Orleans.Runtime/Core/GrainRuntime.cs
- src/Orleans.Runtime/Scheduler/OrleansSchedulerAsynchAgent.cs
- src/Orleans.Runtime/Scheduler/OrleansTaskScheduler.cs
- src/Orleans.Runtime/Scheduler/WorkItemGroup.cs
- src/Orleans.Runtime/Storage/StateStorageBridge.cs
- test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests.cs
- test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs
- test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerBasicTests.cs
- test/NonSilo.Tests/TestInternalHelper.cs
Currently, `Task`s which are scheduled against an activation's `TaskScheduler` will be ignored if that activation has become defunct. This is generally not a problem and ignoring these tasks is fine (eg, it could be a non-awaited task from a grain method call). However, there are some cases where not executing these tasks can lead to larger issues. For example, we have encountered a library which captures an activation's `TaskScheduler` and use it for servicing a work queue.
This PR changes the behavior of `WorkItemGroup` so that `Task`s scheduled after an activation has terminated are still executed.
A warning will still be emitted and that warning will be upgraded to an error after 1 minute (configurable via `SchedulingOptions.StoppedWorkItemGroupWarningInterval`). The error will then …
> Execute tasks scheduled against defunct activations

- test/Extensions/ServiceBus.Tests/Streaming/EHClientStreamTests.cs
- test/Extensions/ServiceBus.Tests/Streaming/EHImplicitSubscriptionStreamRecoveryTests.cs
- test/Tester/StreamingTests/ProgrammaticSubscribeTests/ProgrammaticSubcribeTestsRunner.cs
- test/Tester/StreamingTests/StreamBatchingTestRunner.cs
BatchSendBatchConsume 
Recoverable100EventStreamsWithTransientErrorsTest
EHStreamConsumerOnDroppedClientTest
StreamingTests_Consumer_Producer_UnSubscribe
> Skip intermittently failing tests

- test/Extensions/ServiceBus.Tests/Streaming/EHImplicitSubscriptionStreamRecoveryTests.cs
- test/Extensions/TesterAzureUtils/Streaming/AQClientStreamTests.cs
Recoverable100EventStreamsWith1NonTransientErrorTest
AQStreamProducerOnDroppedClientTest
> Skip intermittently failing tests 2

- src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets
Revert the build change for now because it is breaking code signing. We'll bring it back in when it works properly with code signing.
This reverts commit 74cdce26cf46afa358c8ce5646fae8c83ccfa1c8.
> Revert "Rebuild when files are added or removed from a project (#5594)

- src/Orleans.Core.Abstractions/IDs/SiloAddress.cs
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
- src/Orleans.Runtime/MembershipService/MembershipOracleData.cs
3 targeted commits:
1: Consider any silo for which we have seen a successor (same endpoint, higher generation) to be `Dead`.
2 & 3: when adding/removing a silo, consider any predecessor to be dead.
Previously, only seeing a silo as dead would result in cleanup, but it has been extended to the on-add case
> Improve cleanup of activations on dead silos

- src/Orleans.Transactions/State/ReaderWriterLock.cs
- src/Orleans.Transactions/State/TransactionalStateOptions.cs
When trying to determine cause of broken lock exceptions this was useful.
I can also see it being used to adapt to different storage latencies.
> Make transaction log group max size configurable

- src/Orleans.Core/Lifecycle/LifecycleSubject.cs
- test/Tester/Lifecycle/LifecycleTests.cs
These exceptions significantly detract from the debugging experience
> Avoid wrapping exceptions thrown during lifecycle

- src/Orleans.Core/Configuration/Options/ClusterMembershipOptions.cs
The default timeout (and interval) setting for cluster membership pings of 10 seconds is very conservative and hasn't changed since early versions of Orleans. It adds up to the default detection time for a dead silo of 30 seconds. This puts a lower limits on node failure recovery time because recovery cannot start before a failure is detected.
We believe in today's cloud environments we can half the default detection time by lowering this setting to 5 seconds, and this will lead to a better experience for most Orleans users. If somebody isn't comfortable with the new default, they can explicitly set it to the old value.
> Reduce default liveness probe timeout from 10 seconds to 5

- Directory.Build.props
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
- src/Orleans.Runtime/MembershipService/MembershipOracle.cs
When the `LocalGrainDirectory` receives a register/unregister request that needs to be forwarded (it can happen when all silos doesn't have the same view of the cluster membership), it currently wait 5 seconds before forwarding, to allow some time for the membership changes to propagate.
200ms seems to be a better value since with gossip the membership change should propagate quickly.
> Reduce delay localdirectory when cluster membership is not stable

- src/Orleans.CodeGenerator/Analysis/CompilationAnalyzer.cs
- test/Grains/TestGrainInterfaces/RecursiveType.cs
Fix #5473 - codegen fails on recursively defined types (#5688)
> Cherry-pick #5473 for 2.3.5

- src/Orleans.Core/Core/ClusterClient.cs
Fixes some benign exceptions during shutdown now that ClusterClient is also used on silos
> ClusterClient: only call IRuntimeClient.Reset for OutsideRuntimeClient

- src/Orleans.TestingHost/Utils/TestingUtils.cs
Use the correct path separator on Unix systems, otherwise it creates files with names like 'logs\testcluster-2019-06-25t15-34-58-179_MainClient.log'
> Fix the test trace file name on Unix systems

- test/Grains/TestInternalGrains/AgentTestGrain.cs
- test/TesterInternal/AgentTests.cs
I'm not sure how this test was passing, but `TryAddSingleton` for a type which is supposed to have many registrations like `ILifecycleParticipant<T>` isn't right.
> Fix AgentTests

- Samples/2.3/UnitTesting/README.md
Just a typo fix. Note to self: proof-read thrice.
> Fixed typo on readme

- src/Orleans.Core/Core/ClusterClient.cs
- src/Orleans.Runtime/Core/HostedClient.cs
- src/Orleans.Runtime/Hosting/Generic/SiloWrapper.cs
- src/Orleans.Runtime/Silo/Silo.cs
* Check for `OutsideRuntimeClient` in `ClusterClient` before calling Dispose (which arguably should be removed anyway...)
* Pulse `incomingMessages` queue to give `HostedClient` to gracefully terminate
* Avoid Dispose in `Silo` (it exists in `SiloWrapper`)
* Capture a weal reference to `Silo` in `AppDomain.CurrentDomain.ProcessExit` to fix memory leak (apparent during long test runs)
* Don't await Terminated/Stopped tasks during shutdown (doing so could cause deadlocks)
> Minor client/silo teardown tweaks

- src/Documentation/grains/grain_persistence/index.md
Found a single-character typo in the documentation.
> Typo: persitence

- src/Orleans.Runtime/Core/InternalClusterClient.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
Instead of re-using `ClusterClient`, use a purpose-built `IClusterClient` implementation on silos.
This simplifies behavior by avoiding `ClusterClient`, which was intended for use with external clients & performs a bunch of work which is not needed on the silo (eg, connect/disconnect from the cluster).
> HostedClient - use a slim IClusterClient implementation

- src/Orleans.Core/Logging/ILoggerExtensions.cs
On some machine,  `Environment.FailFast` triggers a popup "xxx has stopped working". We believe it can stalls some deployments when they encounter this error.
> Replace Environment.FailFast with Environment.Exit

- src/Orleans.Core/Streams/Internal/StreamImpl.cs
Fixes #5697.
Fix NullRreferenceException thrown in OnCompletedAsync & OnErrorAsync.
> Fix OnCompleteAsync & OnErrorAsync in StreamImpl

- src/AdoNet/Orleans.Persistence.AdoNet/PostgreSQL-Persistence.sql
fixes #5686
replace jsonb columns by text, to ensure the properties ordering is not modified.
> Fix #5686 - Json serialization with Postgres

- src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
- test/Extensions/AWSUtils.Tests/StorageTests/DynamoDBStorageProviderTests.cs
- test/Extensions/AWSUtils.Tests/StorageTests/PersistenceGrainTests_AWSDynamoDBStore.cs
The current DynamoDB storage provider assumes that type information is included in the json via the Json.NET `TypeNameHandling` option. This PR matches the behavior of other storage providers, allowing plain json objects to be stored and deserialized based on the state's type.
> Added better type serialization support to DynamoDB Storage Provider

- src/Documentation/deployment/grain_versioning/grain_versioning.md
spelling fixes
and added proper links to articles mentioned (previously just plain text)
> docs: small spelling fixes and added links

- src/Orleans.Runtime/Versions/GrainVersionStore.cs
- src/Orleans.Runtime/Versions/Selector/LatestVersionDirector.cs
Also throw in GrainVersionStore when versioning is not enabled.
> Fix exception in LatestVersionSelector when there are no deployed versions of a grain

- test/Analyzers.Tests/AssemblyInfo.cs
- test/CodeGeneration/CodeGenerator.Tests/Properties/AssemblyInfo.cs
- test/DefaultCluster.Tests/Properties/AssemblyInfo.cs
- test/DependencyInjection.Tests/Properties/AssemblyInfo.cs
- test/Extensions/AWSUtils.Tests/Properties/AssemblyInfo.cs
- test/Extensions/Consul.Tests/Properties/AssemblyInfo.cs
- test/Extensions/PSUtils.Tests/Properties/AssemblyInfo.cs
- test/Extensions/Serializers/BondUtils.Tests/Properties/AssemblyInfo.cs
- test/Extensions/Serializers/GoogleUtils.Tests/Properties/AssemblyInfo.cs
- test/Extensions/Serializers/ProtoBuf.Serialization.Tests/Properties/AssemblyInfo.cs
- test/Extensions/ServiceBus.Tests/Properties/AssemblyInfo.cs
- test/Extensions/TestServiceFabric/Properties/AssemblyInfo.cs
- test/Extensions/TesterAdoNet/Properties/AssemblyInfo.cs
- test/Extensions/TesterAzureUtils/Properties/AssemblyInfo.cs
- test/Extensions/TesterZooKeeperUtils/Properties/AssemblyInfo.cs
- test/NetCore.Tests/Properties/AssemblyInfo.cs
- test/RuntimeCodeGen.Tests/Properties/AssemblyInfo.cs
- test/Tester/Properties/AssemblyInfo.cs
- test/TesterInternal/Properties/AssemblyInfo.cs
- test/Transactions/Orleans.Transactions.Azure.Test/AssemblyInfo.cs
- test/Transactions/Orleans.Transactions.Tests/AssemblyInfo.cs
I noticed in some stack traces that Xunit was running tests under a `MaxConcurrencySynchronizationContext`.
Tests may behave differently (eg, potentially hitting a deadlock), so this PR removes the limit by setting it to -1 for all test assemblies
> Remove concurrency cap for Xunit

- src/Orleans.Core/Networking/ClientOutboundConnection.cs
- src/Orleans.Core/Networking/ConnectionPreambleHelper.cs
- src/Orleans.Runtime/Networking/GatewayInboundConnection.cs
- src/Orleans.Runtime/Networking/SiloConnection.cs
- src/Orleans.Runtime/Networking/SiloConnectionFactory.cs
- src/Orleans.Runtime/Networking/SiloConnectionListener.cs
This PR upgrades the networking protocol in a backwards-compatible manner to add support for full-duplex silo-to-silo connections.
Currently silos establish outgoing connections to each other in order to send messages. This results in each silo pair having two connections between them, where each connection is used for traffic in a single direction.
By sending a `SiloAddress` along with the connection preamble, we can support full-duplex connections & save on connections.
> Implement full-duplex silo-to-silo connections

- Samples/2.3/Blazor/Sample.ClientSide/App.razor
- Samples/2.3/Blazor/Sample.ClientSide/Models/TodoItem.cs
- Samples/2.3/Blazor/Sample.ClientSide/Pages/Counter.razor
- Samples/2.3/Blazor/Sample.ClientSide/Pages/FetchData.razor
- Samples/2.3/Blazor/Sample.ClientSide/Pages/Todo.razor
- Samples/2.3/Blazor/Sample.ClientSide/Sample.ClientSide.csproj
- Samples/2.3/Blazor/Sample.ClientSide/Shared/NavMenu.razor
- Samples/2.3/Blazor/Sample.ClientSide/Shared/SurveyPrompt.razor
- Samples/2.3/Blazor/Sample.ClientSide/libman.json
- Samples/2.3/Blazor/Sample.Grains.Interfaces/Sample.Grains.Interfaces.csproj
- Samples/2.3/Blazor/Sample.Grains/Sample.Grains.csproj
- Samples/2.3/Blazor/Sample.Grains/TodoGrain.cs
- Samples/2.3/Blazor/Sample.ServerSide/Pages/Counter.razor
- Samples/2.3/Blazor/Sample.ServerSide/Pages/FetchData.razor
- Samples/2.3/Blazor/Sample.ServerSide/Pages/Todo.razor
- Samples/2.3/Blazor/Sample.ServerSide/Sample.ServerSide.csproj
- Samples/2.3/Blazor/Sample.Silo/Api/ApiService.cs
- Samples/2.3/Blazor/Sample.Silo/Program.cs
- Samples/2.3/Blazor/Sample.Silo/Sample.Silo.csproj
- Samples/2.3/Blazor/readme.md
This updates the Blazor sample to .NET 3.0 Preview 7 requirements, as per the chat on gitter and #5788.
I expect this to break again but for the time being it appears to function.
> Updating Blazor Sample

- src/Orleans.CodeGenerator.MSBuild/runtimeconfig.template.json
Fixes #5793 using @ReubenBond 's instructions.
Successfully compiles a minimal netstandard2.0 project on Linux .NET Core 2.2, 3.0 Preview 7 and a combination of the 2.
Previously this would fail on the 3.0 variant.
> Improve codegen's .NET Core 3 compatibility

- src/Orleans.Core/Messaging/MessageSerializer.cs
The networking replat PR was supposed to be compatible with the 2.x messaging format, but at some point it diverged. Specifically, the way that message headers are now being serialized includes some extra data (a type token) which should not be there. This PR modifies message serialization to line up with 2.x.
> Fix message header serialization to align with 2.x

- src/Documentation/resources/Migration/MigrationAzure2.0.md
Trying to fill some gaps that I found trying to follow migration guides and pages.
> Fix a code typo in migration guide

- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
This helps to improve stability in tests which involve shutdowns. Other membership providers already perform gossip (that's the normal path)
> Gossip status change on shutdown for SystemTargetBasedMembershipTable

- src/Orleans.Core/Networking/ClientOutboundConnection.cs
- src/Orleans.Core/Networking/ClientOutboundConnectionFactory.cs
- src/Orleans.Core/Networking/ConnectionFactory.cs
- src/Orleans.Core/Networking/ConnectionManager.cs
- src/Orleans.Core/Networking/ConnectionOptions.cs
- src/Orleans.Core/Networking/ConnectionPreamble.cs
- src/Orleans.Core/Networking/NetworkProtocolVersion.cs
- src/Orleans.Runtime/Networking/ConnectionListener.cs
- src/Orleans.Runtime/Networking/GatewayConnectionListener.cs
- src/Orleans.Runtime/Networking/GatewayInboundConnection.cs
- src/Orleans.Runtime/Networking/SiloConnection.cs
- src/Orleans.Runtime/Networking/SiloConnectionFactory.cs
- src/Orleans.Runtime/Networking/SiloConnectionListener.cs
This PR modifies the connection preamble which is sent whenever a connection is established in order to support network protocol versioning in a forward- and backward-compatible manner.
For end-users, the protocol versions can only be incremented or decremented by one per deployment (i.e, no skipping ahead until all nodes are updated to at least version 1 on Orleans 3.0).
The current Orleans protocol does not send a preamble in both directions. Instead, the client/silo establishing the connection sends a preamble and the listening side receives it. This PR expands that behavior so that both sides send a preamble as long as the connecting node's protocol version is at least `Version2`.
This is a 3.0-only change and does not need to be back-ported to 2.x
> Introduce support for network protocol versioning

- src/Orleans.Runtime/Messaging/MessageCenter.cs
The intent here it to make it more obvious when a message is being dropped without a response
> Log a warning when blocking application messages in MessageCenter

- src/Orleans.Core/Networking/ConnectionManager.cs
- src/Orleans.Runtime/Messaging/MessageCenter.cs
- src/Orleans.Runtime/Messaging/OutboundMessageQueue.cs
- src/Orleans.Runtime/Networking/GatewayConnectionListener.cs
- src/Orleans.Runtime/Networking/GatewayInboundConnection.cs
- src/Orleans.Runtime/Networking/SiloConnection.cs
- src/Orleans.Runtime/Networking/SiloConnectionFactory.cs
- src/Orleans.Runtime/Networking/SiloConnectionListener.cs
This also removes checks for dead silos from other locations, since those are not needed & can cause issues during shutdown in test scenarios (where SystemTargetBasedMembership is used)
> Check that a silo is not known to be dead before attempting a connection

- src/Orleans.Transactions.TestkitBase/FaultInjection/ControlledInjection/FaultInjectionTransactionStateAttribute.cs
- src/Orleans.Transactions/State/ActivationLifetime.cs
- src/Orleans.Transactions/State/ConfirmationWorker.cs
- src/Orleans.Transactions/State/IActivationLifetime.cs
- src/Orleans.Transactions/State/TransactionQueue.cs
- src/Orleans.Transactions/State/TransactionalState.cs
- src/Orleans.Transactions/State/TransactionalStateFactory.cs
- src/Orleans.Transactions/TOC/TocTransactionQueue.cs
- src/Orleans.Transactions/TOC/TransactionCommitter.cs
- src/Orleans.Transactions/TOC/TransactionCommitterFactory.cs
An implicit assumption in the ConfirmationWorker (part of Transactions) was that async tasks would stop executing when a grain was deactivated. However, since #5588 we are continuing to execute Tasks scheduled against deactivated grains.
This resulted in tasks continually being scheduled against a deactivated grain, causing a significant amount of log noise.
> Terminate ConfirmationWorker loop on deactivation

- src/Orleans.Transactions/State/ReaderWriterLock.cs
- src/Orleans.Transactions/State/TransactionQueue.cs
Several parts of the transaction processing system rely on background workers for transaction servicing. For example, there is a storage worker, a lock worker, and a confirmation worker.
When an activation terminates, these workers must be made aware so that they can also gracefully terminate.
This PR is a follow-up to #5821, extending the termination to the storage worker & lock worker
> Stop background transaction processing when a grain deactivates

- src/Orleans.Core/Logging/ErrorCodes.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Catalog/ActivationState.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/Core/Dispatcher.cs
- src/Orleans.Runtime/Core/GrainRuntime.cs
- Add another terminal state for activation to reject messages when `OnActivateAsync`failed
- Unregister failed activation from the directory before marking it as `Invalid` to avoid forwarding messages to the same activation
- Do not forward messages if the activation is in the `Deactivating` state. All pending messages will be forwarded after the activation has been unregistered from the directory
> Reject failed activations and fix possible race condition

- src/Orleans.Analyzers/Orleans.Analyzers.csproj
Fixes packaging of analyzers. Tested locally and works now.
Trick is to add assemblies in `analyzers\dotnet\cs` as per https://roslyn-analyzers.readthedocs.io/en/latest/create-nuget-package.html. Also made the package a development dependency. This will make sure it `<PrivateAssets>all</PrivateAssets>` is added when installed via package manager.
//cc @ReubenBond @bddckr
> Fixes packaging of analyzers

- src/Orleans.Runtime/GrainDirectory/ILocalGrainDirectory.cs
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
- src/Orleans.Runtime/Utilities/ImmutableCollectionExtensions.cs
We've identified a potential silo deadlock:
* `LocalGrainDirectory.RemoveServer` (called on membership change) **locks** `membershipCache` and calls into the catalog which deactivates grains (taking a **lock** on each activation it's deactivating)
* `Catalog.RecoverFailedInitActivation` (called when a new activation cannot be added to the directory, eg because that silo just shut down) is executed under the activation's **lock** and calls into `LocalGrainDirectory.CalculateGrainDirectoryPartition` which tries to **lock** `membershipCache`
This PR is an attempt to fix that.
> Fix potential deadlock between Catalog and LocalGrainDirectory

- src/Documentation/grains/event_sourcing/event_sourcing_configuration.md
Fixed the documentation on how to add a LogConsistencyProvider programmatically post 2.0 Orleans release.
> Fixed programmatic addition of LogConsistencyProvider

- src/Orleans.Core/Configuration/Options/ClientMessagingOptions.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
Added ClientMessagingOptions.LocalAddress to ignore ConfigUtilities.GetLocalIPAddress that automatic pickups network interfaces. (#5838)
> Cherry-pick #5838 for 2.4.1

- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Runtime/MembershipTableSnapshot.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/MembershipService/ClusterMembershipService.cs
- src/Orleans.Runtime/MembershipService/MembershipSystemTarget.cs
- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
- src/Orleans.Runtime/MembershipService/SiloStatusListenerManager.cs
Log options on silo and client startup (#5859)
Handle the case where the clustering provider does not support TableVersion (#5863)
> Cherry-pick #5859 and #5863 for 2.4.1

- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Runtime/MembershipTableSnapshot.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/MembershipService/ClusterMembershipService.cs
- src/Orleans.Runtime/MembershipService/MembershipSystemTarget.cs
- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
- src/Orleans.Runtime/MembershipService/SiloStatusListenerManager.cs
Log options on silo and client startup (#5859)
Handle the case where the clustering provider does not support TableVersion (#5863)
> Resubmit #5862 (Cherry-pick #5859 and #5863 for 2.4.1)

- src/Orleans.Core/Networking/ConnectionManager.cs
This change records the connection failure starting when the connection attempt completed rather than when the attempt began
> Change connection attempt failure timestamp

- src/BootstrapBuild/Orleans.CodeGeneration.Build/runtimeconfig.template.json
- src/BootstrapBuild/Orleans.CodeGenerator.MSBuild.Bootstrap/runtimeconfig.template.json
- src/Orleans.CodeGeneration.Build/runtimeconfig.template.json
fixes #5880 
The fix allows the codegen for dotnet to use a runtime >= 3.0.0 as fallback if the 2.0 runtime cannot be found. This allow code generation in only dotnet 3.0 environments.
The changes are the same as for #5799 for the MSBuild codegenerator.
I also included the codegenerator in Bootstrap, so that building Orleans itself is now possible only with a dotnet 3.0 runtime.
It maybe a good idea to do that for the MSBuild codegen in Bootstrap, too. Should I include the change in this pull request?
Thanks,
Frank
> Improve codegen's .NET Core 3 compatibility 2

- src/Orleans.Core/Async/BatchWorker.cs
- src/Orleans.Core/Timers/TimerManager.cs
- src/Orleans.Transactions/State/ActivationLifetime.cs
- src/Orleans.Transactions/State/ConfirmationWorker.cs
- src/Orleans.Transactions/State/ReaderWriterLock.cs
- src/Orleans.Transactions/State/TransactionQueue.cs
This PR is mostly intended to reduce log noise since this behavior is benign. Nevertheless, I believe it's worthwhile to clean up the behavior here.
If a grain fails to fully activate and has some transaction processing work which need to be performed then it's possible for the grain to get into a state where the background transaction workers will never terminate.
Additionally, when a grain deactivates while it's performing background transaction work, we may emit a warning to the effect of `"Enqueuing task {Task} to a work item group which should have terminated. Likely reasons are that the task is not being 'awaited' properly or a TaskScheduler was captured and is being used to schedule tasks after a grain has been deactivated."`
This PR attempts to prevent this situation by blocking …
> Improve graceful deactivation of grains performing transaction work

- src/Orleans.Core/Messaging/GatewayClientReceiver.cs
Close client connection on serialization error, to avoid data corruption from client.
> Close client connection on serialization error.

- src/Orleans.Core/Messaging/IncomingMessageBuffer.cs
- src/Orleans.Runtime/Messaging/IncomingMessageAcceptor.cs
In `IncomingMessageBuffer.TryDecodeMessage`, do not set the `out` parameter `msg` if headers deserialization fails.
Otherwise, since `Message.Headers` is never `null`, we do not clear the buffer and close the socket. It might provoke some `NullReferenceException` later too.
> [2.4.2] Fix header deserialization error handling

- src/Orleans.Runtime/Core/Dispatcher.cs
This can cause corruption in messaging. 
The component that actually send the data via the socket the one responsible for this body & header release.
> Do not call release header/body on a message in the dispatcher

- src/Orleans.Runtime/Placement/StatelessWorkerDirector.cs
- test/Tester/HeterogeneousSilosTests/HeterogeneousTests.cs
This changes the placement of stateless workers to not just blindly choose the local silo as the target. Instead we check if the local silo is compatible first, if it is then we choose it, otherwise we back off to the random logic which we previously used when the silo was shutting down.
> Stateless worker local compatibility check

- src/AWS/Orleans.Streaming.SQS/Streams/SQSStreamBuilder.cs
- src/Azure/Orleans.Hosting.AzureCloudServices/QueueBalancers/AzureDeploymentQueueBalancer.cs
- src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueStreamBuilder.cs
- src/Azure/Orleans.Streaming.EventHubs/Hosting/ClientBuilderExtensions.cs
- src/Azure/Orleans.Streaming.EventHubs/Hosting/DeveloperExtensions.cs
- src/Azure/Orleans.Streaming.EventHubs/Hosting/SiloBuilderExtensions.cs
- src/Azure/Orleans.Streaming.EventHubs/Providers/EventDataGeneratorStreamProvider/EventHubPartitionGeneratorReceiver.cs
- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventDataGeneratorStreamConfigurator.cs
- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubStreamBuilder.cs
- src/Orleans.Core/Configuration/NamedServiceConfigurator.cs
- src/Orleans.Core/Streams/ClusterClientPersistentStreamConfigurator.cs
- src/Orleans.Core/Streams/SimpleMessageStreamConfigurator.cs
- src/Orleans.Runtime.Abstractions/Streams/ISiloPersistentStreamConfigurator.cs
- src/Orleans.Runtime.Abstractions/Streams/SiloPersistentStreamConfigurator.cs
- src/Orleans.Runtime/Streams/QueueBalancer/PersistentStreamConfiguratorExtension.cs
- src/Orleans.Streaming.GCP/Providers/Streams/PubSub/PubSubStreamConfigurator.cs
- src/OrleansProviders/Streams/Common/RecoverableStreamConfigurator.cs
- src/OrleansProviders/Streams/Memory/MemoryStreamBuilder.cs
- test/Extensions/Serializers/GoogleUtils.Tests/Streaming/PubSubStreamTests.cs
- test/Extensions/ServiceBus.Tests/PluggableQueueBalancerTests.cs
- test/Extensions/ServiceBus.Tests/Streaming/EHBatchedSubscriptionMultiplicityTests.cs
- test/Extensions/ServiceBus.Tests/Streaming/EHImplicitSubscriptionStreamRecoveryTests.cs
- test/Tester/StreamingTests/ControllableStreamProviderTests.cs
- test/Tester/StreamingTests/MemoryStreamProviderBatchedClientTests.cs
- test/Tester/StreamingTests/MemoryStreamProviderClientTests.cs
- test/Tester/StreamingTests/PlugableQueueBalancerTests/PluggableQueueBalancerTestsWithMemoryStreamProvider.cs
- test/Tester/StreamingTests/ProgrammaticSubscribeTests/ProgrammaticSubscribeTestSMSStreamProvider.cs
- test/Tester/StreamingTests/ProgrammaticSubscribeTests/SubscriptionObserverWithImplicitSubscribingTestsUsingSMS.cs
- test/TesterInternal/StreamProvidersTests.cs
- test/TesterInternal/StreamingTests/SMSStreamingTests.cs
Inconsistent name spaces harm configuration discoverability.
- Move all configurators in Orleans.Streams namespace to Orleans.Hosting
- Move all configurators in Orleans.Configuration namespace to Orleans.Hosting
- Added developer extension functions for EventDataGeneratorStream
- Cleaned up naming issues with Memory Stream Configurator.
> Stream configuration namespace cleanup.

- src/1.5/Documentation/Orleans-Streams/index.md
Seems like SampleStreamingGrain.cs was moved, so the current link in the documentation is returning 404.
> Fix wrong link in stream documentation

- src/Orleans.Core/Messaging/ClientMessageCenter.cs
- src/Orleans.Core/Messaging/GatewayManager.cs
- src/Orleans.Core/Networking/ClientOutboundConnection.cs
- src/Orleans.Core/Networking/ClientOutboundConnectionFactory.cs
- src/Orleans.Core/Networking/Connection.cs
- src/Orleans.Core/Networking/ConnectionFactory.cs
- src/Orleans.Core/Networking/ConnectionManager.cs
- src/Orleans.Runtime/Messaging/Gateway.cs
It's possible for the client to get into a loop when it's unable to find an available gateway. This PR bounds the number of send attempts and attempts to simplify the ClientMessageCenter code for managing gateways by using a lock instead of CompareExchange
> Bound retries for failed send in ClientMessageCenter and simplify

- src/Orleans.Core/Networking/Shared/SocketConnectionOptions.cs
This was always supposed to be enabled but looks like it was missed in one of the refactorings.
> Set Socket.NoDelay = true by default

- Samples/OneBoxDeployment/OneBoxDeployment.sln
- Samples/OneBoxDeployment/UsefulQueries.sql
Before this sample was committed to the repository, it was
renamed from BigSample to OneBoxDeployment. However, these queries
had the previous name. This commit fixes that.
> Fix useful queries database name

- Samples/OneBoxDeployment/Readme.md
Adds the main purpose disclaimer as the first thing so it's clearer.
Also adds BenchmarkDotNet as a desirable item to the to-do list.
> Amends to-do items with BenchmarkDotNet and adds purpose

- src/Orleans.Runtime/Catalog/Catalog.cs
- test/DefaultCluster.Tests/StatelessWorkerTests.cs
- test/Grains/TestGrainInterfaces/IStatelessWorkerExceptionGrain.cs
- test/Grains/TestGrains/StatelessWorkerExceptionGrain.cs
Fix for #5947
`StatelessWorker` and "regular" `Grain` are in fact impacted by this bug. We never saw this behavior for `Grains` since if the constructor throw, they are not registered in the directory, whereas `StatelessWorker` doesn't use the directory.
> Remove activation from message target list if constructor threw an exception

- src/AdoNet/Orleans.Clustering.AdoNet/SQLServer-Clustering.sql
In OneBoxDeployment sample if there are approximately 8-16 siloes starting
simultaneously, one or a few can end up in a primary key constraint
violation since the IF NOT EXISTS check followed by INSERT is not atomic.
This commit remedies that situation according to OneBoxDeployment
(it already has this fix).
Notable that it's not optimal to enforce the query engine with hints like
this and there is a better way, but it would require a larger change.
> Improves queries by adding lock hinting to membership protocol

- test/Analyzers.Tests/AlwaysInterleaveDiagnosticAnalyzerTests.cs
These tests appear to be blocking test execution on a regular basis. Let's disable them for now.
> Disable analyzer tests

- src/Orleans.Core/Networking/Connection.cs
- src/Orleans.Core/Networking/ConnectionManager.cs
This was causing reliability issues because new connections could occasionally be started due to a Ping message, which has a `"Ping"` `RequestContext` header set. The connection would then capture that `RequestContext` and would import it into messages created by the `SiloConnection` itself. These messages would then be treated as though they were Ping messages by the remote silo.
Examples of such messages are:
* Rejections for messages destined to an old silo generation
* Directory lookups - this is trickier, it relies on an optimization whereby `IncomingMessageAgent.ReceiveMessage` is called synchronously from the connection 
This would result in timeouts (which can prevent a silo from starting), active silos being declared dead, obscure exceptions such as `Unrecoverable Rejection …
> Clear RequestContext when spawning connections

- src/Orleans.Core/Messaging/SocketManager.cs
Fix for #5158
Acccodring to [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.connectasync?view=netcore-2.2), `ConnectAsync(SocketAsyncEventArgs)` will return bool 
> true if the I/O operation is pending. The Completed event on the e parameter will be raised upon completion of the operation.
> 
> false if the I/O operation completed synchronously. In this case, The Completed event on the e parameter will not be raised and the e object passed as a parameter may be examined immediately after the method call returns to retrieve the result of the operation.
In windows, looks like `ConnectAsync` will alwasy return true (pending) even if operation is done immediately https://github.com/dotnet/corefx/blob/d391103/src/System.Net.Sockets/src/System/Net/Sockets/So …
> Fix Connect blocked when ConnectAsync completed synchronously

- Directory.Build.props
- src/AdoNet/Orleans.Clustering.AdoNet/Orleans.Clustering.AdoNet.csproj
- src/AdoNet/Orleans.Persistence.AdoNet/Orleans.Persistence.AdoNet.csproj
- src/AdoNet/Orleans.Reminders.AdoNet/Orleans.Reminders.AdoNet.csproj
- src/Azure/Orleans.Clustering.AzureStorage/Orleans.Clustering.AzureStorage.csproj
- src/Azure/Orleans.Persistence.AzureStorage/Orleans.Persistence.AzureStorage.csproj
- src/Azure/Orleans.Reminders.AzureStorage/Orleans.Reminders.AzureStorage.csproj
- src/Azure/Orleans.Streaming.AzureStorage/Orleans.Streaming.AzureStorage.csproj
- src/Azure/Orleans.Streaming.EventHubs/Orleans.Streaming.EventHubs.csproj
- src/BootstrapBuild/Orleans.CodeGeneration/Orleans.CodeGeneration.Bootstrap.csproj
- src/BootstrapBuild/Orleans.CodeGenerator.MSBuild.Bootstrap/Orleans.CodeGenerator.MSBuild.Bootstrap.csproj
- src/BootstrapBuild/Orleans.Core/Orleans.Core.Bootstrap.csproj
- src/Orleans.CodeGeneration.Build/CodeGenerator.cs
- src/Orleans.CodeGeneration/Orleans.CodeGeneration.csproj
- src/Orleans.CodeGenerator.MSBuild/Orleans.CodeGenerator.MSBuild.csproj
- src/Orleans.CodeGenerator.MSBuild/Program.cs
- src/Orleans.CodeGenerator/Orleans.CodeGenerator.csproj
- src/Orleans.Core.Abstractions/Orleans.Core.Abstractions.csproj
- src/Orleans.Core/Core/ClientBuilder.cs
- src/Orleans.Core/Core/ClusterClient.cs
- src/Orleans.Core/Hosting/ApplicationLifetime.cs
- src/Orleans.Core/Logging/FileLogger.cs
- src/Orleans.Core/Orleans.Core.csproj
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/Hosting/Generic/SiloHostBuilder.cs
- src/Orleans.Runtime/Hosting/Generic/SiloWrapper.cs
- test/Extensions/TestServiceFabric/TestOutputLogger.cs
- test/Misc/TestInterfaces/TestInterfaces.csproj
- test/NonSilo.Tests/SiloHostBuilderTests.cs
Upgrades packages to 3.0-preview9 and fixes some associated issues:
Fixes #5925 - Unable to use TestSilo on 3.0 (Removal of internal `NullScope.Instance` from logging)
Fixes #5611 - Exceptions when using aspnetcore preview 5 (Dependency Injection validation issue)
> Upgrade to .NET Core 3.0-preview9 release train

- src/Orleans.Core/Configuration/CollectionAgeLimitAttribute.cs
- src/Orleans.Runtime/Configuration/Options/GrainCollectionOptions.cs
- src/Orleans.Runtime/Configuration/Options/SiloMessagingOptions.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
This PR make CollectionAgeLimitAttribute user friendly . 
```C#
// This grain has 10 hours age limit
[CollectionAgeLimit(Hours = 10)]
class SampleGrainClass1 : Grain ...
{
}
// This grain has 1 day +10 hours + 30 minutes age limit
[CollectionAgeLimit(Days = 1, Hours = 10 , Minutes = 30)]
class SampleGrainClass2 : Grain ...
{
}
//This grains has 32767 days age limit
[CollectionAgeLimit(AlwaysActive = true)]
class SampleGrainClass3 : Grain ...
{
}
```
> Make CollectionAgeLimitAttribute easy to use!

- src/Orleans.CodeGeneration/RoslynCodeGenerator.cs
The condition type.IsSerializable already exists. Need to replace it with TypeHasKnownBase.
> Fixed wrong condition for getting logContext

- src/Orleans.Core/Logging/ErrorCodes.cs
- src/Orleans.Core/Networking/ClientOutboundConnection.cs
- src/Orleans.Core/Networking/Connection.cs
- src/Orleans.Runtime/Networking/GatewayInboundConnection.cs
- src/Orleans.Runtime/Networking/SiloConnection.cs
- test/Grains/TestGrainInterfaces/IExceptionGrain.cs
- test/Grains/TestGrains/MessageSerializationGrain.cs
- test/Tester/ExceptionPropagationTests.cs
Currently when deserialization fails for a response message we do not propagate that deserialization exception to the caller. This PR adds behavior to propate such exceptions back to the original caller.
Fixes #4748
Fixes #5397
xref #5978
> Propagate message [de]serialization exceptions to callers

- src/TelemetryConsumers/Orleans.TelemetryConsumers.Linux/LinuxEnvironmentStatistics.cs
On Windows WSL1, there is no MemAvailable line in meminfo file.
Use MemFree which gives similiar information.
> Use MemFree when MemAvailable is not present

- src/Orleans.Core/Serialization/BuiltInTypes.cs
Quick drive-by PR. I noticed that the `List<T>`/`ReadOnlyCollection<T>` deep copiers are allocating a closure. This removes that allocation.
> Improve List<T>/ReadOnlyCollection<T> deep copy performance

- src/Orleans.CodeGenerator/Generators/GrainReferenceGenerator.cs
- test/Grains/TestGrains/GeneratorTestDerivedFromFSharpInterfaceInExternalAssemblyGrain.cs
- test/Misc/TestFSharpInterfaces/IFSharpBaseInterface.fs
Disambiguate parameters with duplicate names (eg, `Task Foo(int value, int value)`)
Fixes #5936 
Closes #5937
> CodeGen: disambiguate parameters with duplicate names

- src/Orleans.Core/Core/ClientBuilderExtensions.cs
- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Runtime.Abstractions/Hosting/Generic/SiloHostBuilderExtensions.cs
- src/Orleans.Runtime.Abstractions/Hosting/SiloBuilderExtensions.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
Fixes #5729
Users can re-enable `ILBasedSerializer` by calling `siloBuilder.EnableLegacyILBasedSerializer()` and `clientBuilder.EnableLegacyILBasedSerializer()`
> Disable ILBasedSerializer by default

- src/Orleans.CodeGenerator.MSBuild/CodeGeneratorCommand.cs
- src/Orleans.CodeGenerator.MSBuild/Program.cs
- src/Orleans.CodeGenerator.MSBuild/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets
- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/CodeGeneratorOptions.cs
- src/Orleans.CodeGenerator/Generators/GrainMethodInvokerGenerator.cs
- src/Orleans.CodeGenerator/Generators/GrainReferenceGenerator.cs
- src/Orleans.CodeGenerator/Generators/SerializerGenerator.cs
- src/Orleans.CodeGenerator/WellKnownTypes.cs
Fixes #5001
Enable by adding this to your csproj:
``` xml 
<PropertyGroup>
<OrleansCodeGenDebuggerStepThrough>true</OrleansCodeGenDebuggerStepThrough>
</PropertyGroup>
```
With this enabled, all generated `GrainReference`, serializer, and `IGrainMethodInvoker` implementations will be decorated with `[DebuggerStepThrough]`.
> Support adding [DebuggerStepThrough] to generated classes via project option

- src/Orleans.Core/Networking/Connection.cs
- src/Orleans.Runtime/Networking/SiloConnection.cs
This change is required to support rolling upgrades from pre-v3.0 silos. Those silos abort outgoing connections when the remote endpoint sends data.
> Use half-duplex connections when accepting pre-v3 silo connections

- Samples/2.0/docker-aspnet-core/API/API.csproj
- Samples/2.0/docker-aspnet-core/Makefile
- Samples/2.0/docker-aspnet-core/README.md
- Samples/2.0/docker-aspnet-core/Silo/Program.cs
- Samples/2.0/docker-aspnet-core/Silo/Silo.csproj
- Samples/2.0/docker-aspnet-core/deploy.yaml
This is a WIP PR to add support for Kubernetes on the Docker sample. I played with the sample myself, wrote a simple Makefile to test and I thought of PR'ing it to get some feedback whether you want something like that. E.g. want the Kubernetes sample combined with the Docker one or maybe we should create a separate Kubernetes sample? I'm open to suggestions :)
Btw, whereas deployment works (tested locally with Docker for Windows and remotely using Azure Kubernetes Service), I'm getting an Exception after some time and the silo dies. Any hints?
```
orleans-silo-6988656b9-jh5wz orleans-silo Silo started
orleans-silo-6988656b9-jh5wz orleans-silo warn: Orleans.Runtime.MembershipService.MembershipOracleData[100618]
orleans-silo-6988656b9-jh5wz orleans-silo       I should be Dead according to …
```
> Add Kubernetes support to Docker sample

- src/Orleans.Core/Configuration/Options/ClusterMembershipOptions.cs
> Default to cleaning up dead silo entries in the cluster membership table after 7 days

- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Core/Runtime/SharedCallbackData.cs
- src/Orleans.Runtime/Configuration/Options/SiloMessagingOptions.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
This PR adds an option to set the response timeout for `SystemTarget` messages sent from a silo. The default value is 30s but in future that may be changed to a lower value, such as 2s.
> Add separate SiloMessagingOptions.SystemResponseTimeout option

- src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/StateEntity.cs
This implementation retains backwards compatibility with existing stored data while adding support for states which are too large to fit into a single Azure Table Storage column (which holds a maximum of 32 * 1024 chars)
> Transactions: support larger state sizes in Azure Table Storage

- src/Orleans.Runtime/Silo/Silo.cs
Adding warning message at startup if debug level logging is set and recommends setting log level to info for production.
Addresses #5873
> Add warning message at startup

- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Networking/ClientOutboundConnectionFactory.cs
- src/Orleans.Runtime.Abstractions/Configuration/SiloConnectionOptions.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/Networking/GatewayConnectionListener.cs
- src/Orleans.Runtime/Networking/SiloConnectionFactory.cs
- src/Orleans.Runtime/Networking/SiloConnectionListener.cs
This is a quick fix for #6040. Ideally we will implement something more robust and configurable but this will suffice for 3.0.0
Fixes #6040
Note that this is based on top of #6035, so that comes first after which I will rebase this.
>  Prevent Orleans + Kestrel from interfering with each other's networking services

- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
- src/Azure/Orleans.Persistence.AzureStorage/Storage/StorageExceptionExtensions.cs
Azure table grain storage returns inconsistent state if modifying state that does not exist.
> Azure table grain storage inconsistent state on not found

- Samples/OneBoxDeployment/Readme.md
The `ArtifactReference` and `HintPath` in `OneBoxDeployment.Database.sqlproj` assume that Visual Studio 2019 **Enterprise** edition are installed.
If the user is using Visual Studio 2019 Community edition, she will observe ~115 build errors, where the first is:
`SQL72027: File "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\150\SqlSchemas\master.dacpac" does not exist.`
I understand if this PR is not merged *as-is*, but I just spent ~1h and went through adding a bunch of options to my Visual Studio 2019 Community Edition, before actually figuring out what the issue was.
It is my hope that this single line can help at least my future self.
> Add note about Visual Studio Community Edition

- src/Orleans.Runtime/Streams/PubSub/PubSubRendezvousGrain.cs
In the constructor of PubSubRendezvousGrain, it requests an ILogger using category name based on the grain identifier. This might not be an issue depending on the ILoggerFactory implementation, but the one in Microsoft.Extensions.Logging caches them all in a dictionary based on that category name.
> Do not include grain identifier in the ILogger category name

- Directory.Build.props
- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBMembershipTable.cs
- src/AWS/Orleans.Clustering.DynamoDB/Membership/SiloInstanceRecord.cs
- src/AWS/Shared/Storage/DynamoDBStorage.cs
- test/Extensions/AWSUtils.Tests/MembershipTests/DynamoDBMembershipTableTest.cs
Implements the extended membership protocol for DynamoDB.
Fixes #6099 
Still need to go through testing.
I noticed a few things while implementing this:
1. `ReadAll` isn't guaranteed to return all silo entries at the same version. It seemed like other implementations can also be inconsistent, but I'm not familiar enough to say for certain.
2. The Azure implementation seems to be more aggressive at throwing exceptions when rows don't exist than other implementations. I'm not sure what the preference is.
3. `DynamoDBMembershipTable` is getting a bit hard to read with all the low level dynamo db. It could be broken up, but it may be better to use a higher level api. That type of refactoring seems outside the scope of this PR though.
> DynamoDB: support extended membership protocol

- src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs
> Redact logged connection string in ADO storage provider during init

- src/Orleans.CodeGenerator.MSBuild/AssemblyResolver.cs
In ```.dotnetcore 3.x``` , the ```Orleans.CodeGenerator.MSBuild``` may be incorrect resolve custom type , that will be cause   ``` TypeAccessException``` ,  because the symbol is still .NETCOREAPP2.0 , this PR has been verified in my project !
> Fixed CodeGenerator.MSBuild cannot ResolveAssembly in .NetCore 3.0

- src/Orleans.CodeGenerator.MSBuild/AssemblyResolver.cs
Fixed CodeGenerator.MSBuild cannot ResolveAssembly in .NetCore 3.0 (#6143)
(cherry picked from commit 2b0e9e6496ad5c9190100f8b6048e58a987feb36)
> One more fix for 3.0.1

- src/Orleans.Runtime/Core/IFatalErrorHandler.cs
This can be useful for troubleshooting
> Make IFatalErrorHandler public so that it can be replaced by users

- src/Orleans.CodeGenerator/Generators/GrainReferenceGenerator.cs
Fixes #6165
I didn't spot any other instances of the same bug, so hopefully this is it.
> CodeGen: fix ambiguous reference to Orleans namespace

- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Core/Statistics/MessagingProcessingStatisticsGroup.cs
- src/Orleans.Core/Statistics/MessagingStatisticsGroup.cs
- src/Orleans.Core/Statistics/NetworkingStatisticsGroup.cs
- src/Orleans.Core/Statistics/SchedulerStatisticsGroup.cs
When running multiple TestClusters in the same process (and same AppDomain), it's possible that there can be a `NullReferenceException` caused by a call to one of the `Init()` methods in the statistics groups while those groups are being accessed by an existing node.
> Avoid potential NullReferenceException when re-initializing statistics

- src/Orleans.CodeGenerator.MSBuild/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets
Fixes #6073
@pechkarus @turowicz are either of you able to build this PR and test it? I tested locally with the repro sln I posted on the issue thread.
The fix is to use AfterTargets instead of DependsOnTargets. DependsOnTargets will invoke the requisite targets, whereas AfterTargets just signifies sequencing.
> Fix 'dotnet pack --no-build'

- src/Orleans.Runtime/GrainTypeManager/GrainTypeData.cs
This fixes an exception that occures when the MayInterleaveAttirbute is defined for a base grain.
> Allow MayInterleaveAttribute on base grains. Fix for issue #6189

- src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs
- src/Orleans.Core/Serialization/BinaryTokenStreamWriter2.cs
String serialization:
```md
|   Method |      Mean |  Gen 0 | Allocated |
|--------- |----------:|-------:|----------:|
|   Before |  94.83 ns | 0.0194 |     112 B |
|    After |  68.11 ns |      - |         - |
```
String deserialization:
``` md
|   Method |      Mean |  Gen 0 | Allocated |
|--------- |----------:|-------:|----------:|
|   Before | 134.18 ns | 0.0527 |     304 B |
|    After | 109.08 ns | 0.0334 |     192 B |
```
> Serialization optimizations for .NET Core 3.1

- src/Documentation/grains/transactions.md
A documentation has been extended with the note related to transactions & `onactivateasync` based on the discussion inside of https://github.com/dotnet/orleans/issues/6115.
> 6115: add note about onactivateasync to transactions part

- src/Orleans.Runtime/Utilities/OrleansDebuggerHelper.cs
- test/DefaultCluster.Tests/DebuggerHelperTests.cs
- test/Grains/TestGrainInterfaces/IEchoTaskGrain.cs
- test/Grains/TestInternalGrains/EchoTaskGrain.cs
Fixes #6220 
cc @OracPrime
Example usage (from Immediate Window in VS debugger):
```C#
Orleans.Runtime.Utilities.OrleansDebuggerHelper.GetGrainInstance(myGrainReference)
```
> Add OrleansDebuggerHelper.GetGrainInstance to aid in local debugging

- src/Documentation/resources/toc.yml
The public page [exists](https://dotnet.github.io/orleans/Documentation/resources/nuget_packages.html?q=packages), but there was no way to get to it, this fixes it.
Signed-off-by: Mike Lloyd <mike@reboot3times.org>
> docs: fixed dead page link.

- src/Orleans.Core/Timers/AsyncTaskSafeTimer.cs
- src/Orleans.Core/Timers/NonCapturingTimer.cs
- src/Orleans.Core/Timers/SafeTimer.cs
- src/Orleans.Core/Timers/SafeTimerBase.cs
- src/Orleans.Core/Timers/TimerManager.cs
Fixes #5563
This means that `RequestContext` will not automatically flow into timers, etc. My belief is that this is the correct behavior and that the current behavior is a likely source of bugs.
> Avoid capturing ExecutionContext in GrainTimer and other timers

- src/Orleans.Core.Abstractions/Runtime/RequestContext.cs
When removing the last entry from a RequestContext, set the value to null instead of creating a new dictionary with a copy of the current context and removing the last item.
> Minor perf tweak for RequestContext when removing last item

- src/Orleans.Runtime/Catalog/Catalog.cs
#6240 The myriads of messages will now only appear if debug logging is enabled
> Change duplicate activation to a debug-level message

- src/AdoNet/Shared/Storage/AdoNetInvariants.cs
- src/AdoNet/Shared/Storage/DbConnectionFactory.cs
- src/AdoNet/Shared/Storage/DbConstantsStore.cs
- test/Extensions/TesterAdoNet/Tester.AdoNet.csproj
This adds support for MySqlConnector library using MySql.Data.MySqlConnector
invariant string.
Note: MySql.Data.MySqlConnector library uses the same namespace as the
official Oracle library 'MySql.Data.MySql' which has traditionally
interpreted as the invariant name also. Hence in Orleans the invariant
string is different than in the library used. Likely support for
DbProviderFactory changes this as using that one can use load library
separate from the invariant.
Fixes #6230.
> Adds MySqlConnector library using invariant MySql.Data.MySqlConnector

- src/TelemetryConsumers/Orleans.TelemetryConsumers.Counters/Statistics/PerfCounterEnvironmentStatistics.cs
This exposes the exception thrown when failing to connect to performance counters. This is to help troubleshoot the underlying issue when repairing the counter config does not work. Note that I couldn't find any test class to update. Do you want one? And is there a cleaner solution than this?
> Expose exception when initializing PerfCounterEnvironmentStatistics

- test/Extensions/ServiceBus.Tests/StatisticMonitorTests/EHStatisticMonitorTests.cs
This test has been flaky for a long time. See #4594
> Skip flaky EHStatistics_MonitorCalledAccordingly test

- src/Orleans.Runtime/Core/FatalErrorHandler.cs
This allows proper error report bucketing.
> Provide exception to FailFast in FatalErrorHandler

- src/AWS/Shared/AWSUtils.cs
- src/AWS/Shared/Storage/DynamoDBStorage.cs
Why is `us-west-2` the default btw?
> Use RegionEndpoint.GetBySystemName() to resolve AWS region

- src/Orleans.CodeGenerator/Generators/GrainReferenceGenerator.cs
- src/Orleans.CodeGenerator/WellKnownTypes.cs
Currently `ValueTask<T>` is supported for grain interfaces, but `ValueTask` isn't because it generates a return. This PR just removes the return in that case.
> Fixing code gen for ValueTask

- src/Orleans.CodeGenerator/Orleans.CodeGenerator.csproj
Fix for #6296
Add System.Threading.Tasks.Extensions as a dependency to Orleans.CodeGenerator
> Add missing dependency to Orleans.CodeGenerator

- src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCache.cs
- src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCacheCursor.cs
Fixes #6298 
Fixes #6281
For brevity I am `using SQC = SimpleQueueCache; using SQCC = SimpleQueueCacheCursor;`, within this post.
The whole idea of this change is to chance SQCC so that its `Element` value always points to the cursors current element, rather than its next value. This change is remarkably small, especially if you do not count the comment changes.
Specifically it has the invariant that: whenever a method is not currently executing, if `current` is not null, then it always equals `Element.Value.Batch`. (Note: Invariant does not need to hold at end of re-entrant calls while some other `SQCC` method is running.) I will informally prove that invariant holds a little further below. I will also informally argue as to why this change is safe.
While there are further changes or …
> Use current element for SimpleQueueCacheCursor.Element

- test/Extensions/TesterAdoNet/StorageTests/Relational/TestEnvironmentInvariant.cs
The new .NET Core SQL Server connector library has made
has removed the obsolote "asynchronous processing = true"
attribute and the tests crash to exception that tells this
keyword is unsupported. Removing it from the connection string
allows the tests run green again.
> Fix SQL Server connection string

- src/Orleans.Core.Abstractions/Exceptions/DeadlockException.cs
- src/Orleans.Core/Messaging/Message.cs
- src/Orleans.Core/Messaging/MessageFactory.cs
- src/Orleans.Core/Messaging/RequestInvocationHistory.cs
- src/Orleans.Core/Runtime/GrainReferenceRuntime.cs
- src/Orleans.Core/Runtime/IRuntimeClient.cs
- src/Orleans.Core/Runtime/OutgoingCallInvoker.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Runtime/Core/Dispatcher.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- src/Orleans.Runtime/Scheduler/InvokeWorkItem.cs
- src/Orleans.Runtime/Scheduler/RequestWorkItem.cs
- src/Orleans.Runtime/Scheduler/ResponseWorkItem.cs
This has been disabled via hard-coded switch for a long, long time. It's time we removed it.
> Remove Message.DebugContext and related code

- src/Orleans.Core.Abstractions/IDs/GrainId.cs
- test/NonSilo.Tests/General/Identifiertests.cs
As of #6305, the code removed by this PR is no longer useful.
> Remove GrainId clusterId constructor parameter and associated code

- src/Orleans.TestingHost/TestClusterOptions.cs
Propagate `TestClusterOptions.GatewayPerSilo` value in `TestClusterOptions.ToDictionary()`
> Fix GatewayPerSilo setting in TestClusterOptions

- src/AWS/Shared/Storage/DynamoDBStorage.cs
For reference, setting `RegionEndpoint` overwrites the `ServiceUrl` setting anyway,
and the only reason it works now is because of the order the
properties are set.
> [AWS:DynamoDB] Don't set `ServiceUrl` when region is provided.

- src/AWS/Orleans.Persistence.DynamoDB/Options/DynamoDBStorageOptions.cs
- src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
- src/AWS/Shared/Storage/DynamoDBStorage.cs
This fixes a previous issue where a Read/Write capacity of `0` would imply a non-provisioned strategy. Setting `UseProvisionedThroughput` to `false` now changes the `BILLING_MODE` to `PAY_PER_REQUEST` as expected.
Defaults are kept (`UseProvisionedThroughput = true`) to not change or break existing behavior.
> [AWS:DynamoDB] Explicit setting for `UseProvisionedThroughput`

- Directory.Build.props
- test/Analyzers.Tests/Analyzers.Tests.csproj
- test/DependencyInjection.Tests/DependencyInjection.Tests.csproj
- test/Extensions/ServiceBus.Tests/ServiceBus.Tests.csproj
- test/Extensions/TestServiceFabric/TestServiceFabric.csproj
- test/Extensions/TesterAdoNet/Tester.AdoNet.csproj
- test/Grains/TestInternalGrains/TestInternalGrains.csproj
- test/Grains/TestVersionGrains/TestVersionGrains.csproj
- test/Grains/TestVersionGrains2/TestVersionGrains2.csproj
- test/RuntimeCodeGen.Tests/RuntimeCodeGen.Tests.csproj
- test/TestInfrastructure/Orleans.TestingHost.Tests/Orleans.TestingHost.Tests.csproj
- test/Tester/Tester.csproj
- test/TesterInternal/TesterInternal.csproj
- test/Transactions/Orleans.Transactions.Azure.Test/Orleans.Transactions.Azure.Test.csproj
- test/Transactions/Orleans.Transactions.Tests/Orleans.Transactions.Tests.csproj
Add explicit references to System.Diagnostics.EventLog and System.Security.Cryptography.Cng to fix build warnings.
> Fix build warnings

- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBMembershipTable.cs
- test/Extensions/AWSUtils.Tests/StorageTests/DynamoDBStorageProviderTests.cs
- test/Extensions/AWSUtils.Tests/StorageTests/PersistenceGrainTests_AWSDynamoDBStore.cs
- test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs
So I got DynamoDB running locally in a Docker container so that I could run the AWSUtils.Tests and verify my change.
It seems that for DynamoDB-related things, these tests are mostly broken. The constructors for DynamoDBGrainStorage and SiloLifecycleSubject have changed, so the attempts to instantiate these fail in DynamoDBStorageProviderTests.cs. I fixed this, but then also found that the maximum size DynamoDB allows for an item is 400KB and some of those tests are trying to write items considerably larger than that. 
Other AWSUtils.Tests are failing too. I may take a stab at fixing these later in the week, but this is what I had time for today. The Membership ones pass, and that's the code I was changing.
> Fix CleanupDefunctSiloMembership & MembershipTableTests

- src/Orleans.Core/Configuration/Options/ClusterMembershipOptions.cs
- src/Orleans.Runtime/MembershipService/MembershipTableCleanupAgent.cs
* Set default `DefunctSiloCleanupPeriod` to 1 hour (currently 7 days)
* Add random 5 minute jitter around cleanup period on each iteration
* Schedule first cleanup for a random time within the first 10 minutes of a silo starting
> Schedule IMembershipTable.CleanupDefunctSiloEntries more frequently

- src/AdoNet/Orleans.Persistence.AdoNet/MySQL-Persistence.sql
Set isolation level to `READ COMMITED` to avoid Gap Lock issues
Fixes #6316
> Fix deadlocks with MySQL Storage

- src/AdoNet/Orleans.Persistence.AdoNet/MySQL-Persistence.sql
- src/AdoNet/Orleans.Persistence.AdoNet/Oracle-Persistence.sql
- src/AdoNet/Orleans.Persistence.AdoNet/PostgreSQL-Persistence.sql
- src/AdoNet/Orleans.Persistence.AdoNet/SQLServer-Persistence.sql
This table is the odd one out:
```
test=# \d
List of relations
Schema |             Name              | Type  | Owner
--------+-------------------------------+-------+-------
public | orleansmembershiptable        | table | test
public | orleansmembershipversiontable | table | test
public | orleansquery                  | table | test
public | orleansreminderstable         | table | test
public | storage                       | table | test
```
This shouldn't affect existing deployments, I think, since the queries that access the table are all written into the `OrleansQuery` table in these scripts in the first place.
> AdoNet: Rename Storage table to OrleansStorage for consistency with other tables.

- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/Generators/GrainReferenceGenerator.cs
- src/Orleans.CodeGenerator/Generators/SerializerGenerator.cs
- src/Orleans.CodeGenerator/Utilities/SymbolExtensions.cs
- src/Orleans.CodeGenerator/WellKnownTypes.cs
- test/CodeGeneration/CodeGenerator.Tests/RoslynTypeNameFormatterTests.cs
We're in the process of upgrading to Orleans 3.x and trying out the new code generator (again).
I discovered several bugs and regressions compared to the legacy code-gen:
* Fix `ValueTask` type loading to be optional (for netstandard 2.0).
* Fix `ImmutableAttribute` to actually work.
* Don't generate (invalid) serializer types for enums.
* Don't record invalid (empty) copies of value types using `RecordCopy`.
Theoretically this might result in observable changes in behavior, but the current logic is invalid anyway.
Probably should remove `RecordCopy` calls from `BuiltInTypes` also for value types (but the copies are at least valid objects there).
`ILSerializerGenerator.EmitCopier` has the same bug - it boxes and records invalid (empty) objects for value types.
* For shallow copyable types …
> CodeGenerator fixes

- src/Orleans.TestingHost/TestClusterHostFactory.cs
The test client was trying to connect to gateways that were disabled.
> Fix DependencyInjectionSiloStartsUsingAutofac.ClusterStart 

- src/Orleans.Core.Abstractions/Core/Grain.cs
- src/Orleans.Core.Abstractions/Core/IStorage.cs
- src/Orleans.Core.Abstractions/Runtime/IGrainRuntime.cs
- src/Orleans.Runtime.Abstractions/Facet/Persistent/IPersistentState.cs
- src/Orleans.Runtime.Abstractions/Facet/Persistent/IPersistentStateFactory.cs
- src/Orleans.Runtime/Core/GrainRuntime.cs
- src/Orleans.Runtime/Facet/Persistent/PersistentStateStorageFactory.cs
- src/Orleans.Runtime/Storage/StateStorageBridge.cs
See #6334 - though I don't believe this fully resolves the issue
This is a compilation-breaking change for anyone who has a custom IPersistentState/IStorage/IGrainRuntime implementation, but the fix is simple (remove the constraint from the implementation)
I don't consider accepting this PR a given - we can discuss it and decide whether to merge or close it.
> Remove new() constraint for grain persistence

- src/Orleans.Runtime/Networking/ConnectionListener.cs
This was seen to cause an issue in #6314
> Avoid destructuring in log templates

- src/Orleans.Core/SystemTargetInterfaces/IReminderTable.cs
- src/Orleans.Runtime/ReminderService/GrainBasedReminderTable.cs
Drive-by because of some code which was being referenced (ActivationData.Address)
EDIT: Let's merge https://github.com/dotnet/orleans/pull/6315 first, since it does much of the same. After that, I'll rebase and reassess.
> Cleanup GrainBasedReminderTable

- src/Orleans.Core/AssemblyLoader/CachedTypeResolver.cs
- src/Orleans.Core/CodeGeneration/TypeUtils.cs
- src/Orleans.Core/Serialization/TypeUtilities.cs
- src/Orleans.Runtime/Core/ManagementGrain.cs
- src/Orleans.Runtime/ReminderService/GrainBasedReminderTable.cs
- src/Orleans.Runtime/ReminderService/InMemoryReminderTable.cs
- src/OrleansProviders/Storage/HierarchicalKeyStore.cs
- src/OrleansProviders/Storage/MemoryStorage.cs
- src/OrleansProviders/Storage/MemoryStorageGrain.cs
- test/TesterInternal/StorageTests/HierarchicalKeyStoreTests.cs
* Replace two-level dictionary in `MemoryStorageGrain` with a single flat dictionary.
* Remove one level of indirection/code-duplication from `GrainBasedReminderTable`
* Streamline dictionary method use and remove some dead code.
> Streamline MemoryStorage and InMemoryReminderTable

- src/OrleansProviders/Storage/MemoryStorageWithLatency.cs
Failure mode:
```
Write: Expected minimum latency = 00:00:00.2000000 Actual = 00:00:00.1975619
at Tester.AzureUtils.Persistence.PersistenceProviderTests_Local.PersistenceProvider_Memory_FixedLatency_WriteRead()
in C:\agent\_work\2\s\test\Extensions\TesterAzureUtils\Persistence\PersistenceProviderTests.cs:line 237
```
This looks to be caused by a simple system clock resolution / rounding error edge case glitch in the test code.
This is a fix for a test glitch encountered with running Functional tests for PR #6374
> Fix test glitch in PersistenceProvider_Memory_FixedLatency_WriteRead

- src/Orleans.Core/Configuration/ServiceCollectionExtensions.cs
- src/TelemetryConsumers/Orleans.TelemetryConsumers.Linux/HostBuilderExtensions.cs
* Added `AddFromExisting` overload to support `Type`s for service and implementation instead of generics.
* Reverted `LinuxEnvironmentStatisticsValidator` since it fails on other OSes after warning is thrown.
* Consolidated `UseLinuxEnvironmentStatistics` registrations.
* Added platform check in `UseLinuxEnvironmentStatistics` to avoid registrations in other OSes.
> Amended LinuxEnvironmentStatistics registration to register services on Linux only

- Build.cmd
- Ensure-DotNetSdk.cmd
- Parallel-Tests.ps1
- Samples/1.x/AzureWebSample/WebRole/Web.config
- Samples/1.x/GPSTracker/GPSTracker.Web/Views/Web.config
- Samples/1.x/GPSTracker/GPSTracker.Web/Web.config
- Samples/1.x/HelloGeoSample/WebRole/Web.config
- Samples/1.x/Presence/Host/packages.config
- Samples/1.x/Presence/LoadGenerator/packages.config
- Samples/1.x/Presence/PlayerWatcher/packages.config
- Samples/1.x/Presence/PresenceGrainInterfaces/packages.config
- Samples/1.x/Presence/PresenceGrains/packages.config
- Samples/1.x/ReplicatedChatGrainSample/WebRole/Web.config
- Samples/1.x/ReplicatedEventSample/WebRole/Web.config
- Samples/1.x/ReplicatedEventSample/WebRole2/Web.config
- Samples/1.x/TicTacToe/Host/packages.config
- Samples/1.x/TicTacToe/OrleansXO.GrainInterfaces/packages.config
- Samples/1.x/TicTacToe/OrleansXO.Grains/packages.config
- Samples/1.x/TicTacToe/OrleansXO.Web/Web.config
- Samples/1.x/TicTacToe/OrleansXO.Web/packages.config
- Samples/1.x/TicTacToe/OrleansXO.WorkerRole/packages.config
- Samples/1.x/TwitterSentiment/TwitterWebApplication/Views/Web.config
- Samples/1.x/TwitterSentiment/TwitterWebApplication/Web.config
- Samples/2.0/docker-aspnet-core/API/API.csproj
- Test.cmd
- init-tools.cmd
- src/Orleans.Runtime/MembershipService/MembershipAgent.cs
- src/Orleans.Transactions.TestKitBase/Consistency/ConsistencyTestGrain.cs
https://lgtm.com/projects/g/dotnet/orleans/?mode=list&severity=error
Fix errors reported by GitHub Semmle code analysis tools:
- Missing X-Frame-Options HTTP header - https://lgtm.com/rules/1506102236348/
- Using a package with a known vulnerability - https://lgtm.com/rules/1506697777412/
- Possible loss of precision - https://lgtm.com/rules/1506096756023/
Ensure Test.cmd clears the `Platform` environment variable (same as in Build.cmd) in case it is run on separate cmd session (eg Appveyor builds)
Remove unused $outDir param from Parallel-Tests.ps1 script.
> Fix errors reported by GitHub Semmle code analysis tools.

- Parallel-Tests.ps1
- Test.cmd
- src/Orleans.CodeGenerator/Compatibility/RoslynTypeNameFormatter.cs
- test/CodeGeneration/CodeGenerator.Tests/CodeGenerator.Tests.csproj
- test/CodeGeneration/CodeGenerator.Tests/RoslynTypeNameFormatterTests.cs
- test/Tester/ExceptionPropagationTests.cs
This is a fix for the regression discussed in https://github.com/dotnet/orleans/issues/6392
The fix allows users of Orleans versions prior to 3.1.0 to upgrade without breaking compatibility.
Users of Orleans 3.1.0 and 3.1.2 will experience a degraded rolling upgrade experience.
> Omit assembly name for all types from System namespace during codegen

- src/OrleansProviders/Streams/Memory/MemoryAdapterFactory.cs
I was just browsing the code, and noticed this randomly.
It seems like it wasn't actually useful previously, as the dictionary seems to be an attempt to not have to call `GenerateDeterministicGuid` every time it tries to get the queue grain.
> Use the overload of ConcurrentDictionary.GetOrAdd that takes a method

- src/Documentation/clusters_and_clients/heterogeneous_silos.md
- src/Documentation/grains/grain_persistence/relational_storage.md
* Added new limitation in heterogeneous silos setup (https://github.com/dotnet/orleans/issues/5557)
* Fixed ADO.NET link in Relational Storage documentation
> Added limitation in heterogeneous silos setup and fixed ADO.NET link in docs

- src/Documentation/grains/toc.yml
Grain Identity and Grain placement topics got confused in the TOC.
Currently on the documentation site, the table of contents shows
a label that says "Grain Placement", but links to the grain Identity page.
This should fix that.
> DOCS: Fix TOC entry

- src/TelemetryConsumers/Orleans.TelemetryConsumers.Linux/LinuxEnvironmentStatistics.cs
as it causes the silo to think its using 100% cpu when its not
iowait (since Linux 2.5.41)
(5) Time waiting for I/O to complete.  This
value is not reliable, for the following rea‐
sons:
1. The CPU will not wait for I/O to complete;
iowait is the time that a task is waiting for
I/O to complete.  When a CPU goes into idle
state for outstanding task I/O, another task
will be scheduled on this CPU.
2. On a multi-core CPU, the task waiting for I/O
to complete is not running on any CPU, so the
iowait of each CPU is difficult to calculate.
3. The value in this field may decrease in cer‐
tain conditions.
http://man7.org/linux/man-pages/man5/proc.5.html
> Dont use iowait in cpu calcs on linux

- src/Orleans.Core/Messaging/GatewayManager.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- test/TesterInternal/GatewaySelectionTest.cs
Fixes #6458 
* Avoid canary call to `IGatewayListProvider` and instead perform the pertinent call asynchronously inside `GatewayManager`
* Remove blocking `GetGateways` call from `GatewayManager` ctor
* Minor cleanup
> Allow GatewayManager initialization to be retried

- src/TelemetryConsumers/Orleans.TelemetryConsumers.AI/AITelemetryConsumer.cs
We needed to override the Consumer to prefix metric names, and it seems reasonable that others would too.
Took the chance to bring the file to compliance with the styles.
> make methods on AiTelemetryConsumer virtual; clean-up

- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubDataAdapter.cs
Setting EventIndex in FromQueueMessage method. In our use case we get a message from eventhub and then duplicate that message to go to multiple grains, while duplicating we set different EventIndex for each message. 
So, setting EventIndex in FromQueueMessage method will cause us to copy and modify one less function from orleans code to support our use case, if this doesn't cause any other issue in orleans
> Setting eventIndex

- src/Orleans.Core/Diagnostics/MessagingTrace.cs
- src/Orleans.Runtime/Messaging/MessageCenter.cs
- src/Orleans.Runtime/Messaging/OutboundMessageQueue.cs
- src/Orleans.Runtime/Networking/SiloConnection.cs
We shouldn't drop messages, unless they are expired or we have no reasonable action to take on them.
In this case, I think we can reject messages sent to a stopped OutboundMessagingQueue (which happens during shutdown), to make some problems easier to debug.
> Send rejections for messages enqueued on stopped outbound queue

- src/Orleans.Runtime/Scheduler/WorkItemGroup.cs
This tries to add some more context to the warning about incorrect use of a stopped scheduler.
This will turn `Task.AsyncState: System.Action` into something like `Task.AsyncState: ContinuationWrapper.Invoke: MoveNextRunner.Run: DummyTest+<RunSomethingAsync>d__1`.
Not sure if this is the reasonable way to get this data, maybe @stephentoub knows how to do this more cleanly? Using `Task.GetDelegatesFromContinuationObject(task.AsyncState)` maybe?
> Stopped WorkItemGroup logging enhanchement

- Samples/2.0/Adventure/AdventureGrainInterfaces/IRoomGrain.cs
This PR fixes a small typo I noticed while studying the source of the Adventure sample.
> Fix typo in Adventure sample

- Samples/2.0/Adventure/AdventureSetup/AdventureMap.json
This PR fixes unquoted members in `AdventureMap.json` that's part of the [Adventure sample](https://github.com/dotnet/orleans/tree/cbae60b57629ccb1d699adb9469f7ddfe7461ef2/Samples/2.0/Adventure):
https://github.com/dotnet/orleans/blob/cbae60b57629ccb1d699adb9469f7ddfe7461ef2/Samples/2.0/Adventure/AdventureSetup/AdventureMap.json#L13-L16
> Fix unquoted members in adventure map JSON

- src/Documentation/grains/grainservices.md
Previous name is LightstreamerDataService, but we register DataService in Silo. Looks like the correct name is DataService
> Fix name of data service

- src/Azure/Shared/Storage/AzureStoragePolicyOptions.cs
- src/Azure/Shared/Storage/AzureTableDataManager.cs
`AzureStoragePolicyOptions.CreationTimeout` and `OperationTimeout` should be the timeouts for individual attempts, not the maximum overall timeout. When there is contention, as we see in some tests, the behavioral change introduced in #6462 can lead to flakiness.
> Fix flakiness in Azure Storage providers introduced by #6462

- src/Documentation/grains/reentrancy.md
>Grain activations are single-threaded and, by default, process each request from beginning to completion before the next request can begin ***being*** processing. In some circumstances, it may be desirable for ....
Removed ***being*** above.
> Grammar in Reentrancy docs.

- src/Documentation/implementation/streams_implementation/azure_queue_streams.md
This PR follows the already merged [PR 6441](https://github.com/dotnet/orleans/pull/6441). It fixes the confusion between `ConfigureCacheSize` and `GetQueueMsgsTimerPeriod` in the code example.
Collecting input from @jason-bragg and issue [6345](https://github.com/dotnet/orleans/issues/6345#issuecomment-595419498) about tuning azure queue streams. I found it very interesting and helpful to better understand how the system works. I thought was smart to share it in the docs.
> configures cache by size

- src/OrleansProviders/Streams/Common/PooledCache/ChronologicalEvictionStrategy.cs
- src/OrleansProviders/Streams/Common/PooledCache/IEvictionStrategy.cs
We are seeing some cases where some items from cache are purged before they get delivered to a grain, as they satisfy the time purge criteria. It could also be because of some customizations we have done to Orleans streaming. 
So, just making ShouldPurge as public method so that we can customize it, like only purge cache messages whose sequence token is less than min read sequence token in last 15 mins or something.
> Made ShouldPurge protected and virtual in eviction strategy.

- src/AdoNet/Shared/Storage/OrleansRelationalDownloadStream.cs
- src/Orleans.Core/Async/AsyncPipeline.cs
- src/Orleans.Core/Async/AsyncSerialExecutor.cs
- src/Orleans.Core/Async/BatchWorker.cs
- src/Orleans.Core/Async/MultiTaskCompletionSource.cs
- src/Orleans.Core/Async/TaskExtensions.cs
See https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#always-create-taskcompletionsourcet-with-taskcreationoptionsruncontinuationsasynchronously
> Use TaskCompletionSource.RunContinuationsAsynchronously

- src/Orleans.Core.Abstractions/Async/PublicOrleansTaskExtensions.cs
- src/Orleans.Runtime/MembershipService/SiloHealthMonitor.cs
Always observe ping task results, even if they are discarded (canceled).
> Observe discarded ping task results

- src/Orleans.Core/Async/BatchWorker.cs
Currently `BatchWorker.Start` runs arbitrary code under the lock by invoking `Work()`.
Also, if `Work()` throws an exception, then  `currentWorkCycle` can be null and Start can fail with a NRE.
And because all of this is done under a lock, `startingCurrentWorkCycle` can never be observed to be true and there is no need for volatile as a full memory barrier is implied by lock anyway.
> Constrain work done under a lock in BatchWorker

- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBMembershipTable.cs
- src/Azure/Orleans.Clustering.AzureStorage/OrleansSiloInstanceManager.cs
- test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs
In environments like Kubernetes, if a silo fails to join cluster, its `Joining` records stays in the table even if cleanup of old records is enabled because the cleanup logic only deletes `Dead` entries. This change makes it include `Joining` records as well.
I didn't find an easy way to add an Azure Table tests because the cleanup logic uses `Timestamp` field to select old entries, and the test code doesn't have a way to override it.
> Delete old Joining records as part of cleanup of defunct entries

- src/Orleans.Core.Abstractions/IDs/GrainId.cs
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
- test/DefaultCluster.Tests/GrainReferenceTest.cs
- test/NonSilo.Tests/General/Identifiertests.cs
Fixes an issue with GrainId.GetUniformHashCode which was causing distributed tests to fail.
> Use stable hash in GrainId

- src/Orleans.Core/Diagnostics/EventSourceEvents.cs
Change from related activity ids to actually setting the activity id for the current event being logged.
Updated EventLevel to be more consistent with the frequency of the individual events being generated.
This is related to #6617
> Fix call pattern that throws.

- src/Orleans.Runtime/Timers/AsyncTimer.cs
Reminders are allowed to have dueTime/period > int.MaxValue milliseconds (about 24 days) which causes `AsyncTimer.NextTick` to call `Task.Delay` with invalid arguments, the result isn't observed and the next reminder tick is immediately run...
> Fix unobserved ArgumentOutOfRangeException from Task.Delay

- src/Orleans.Core/Networking/Shared/SocketConnectionListener.cs
This behavior changed with the move to Bedrock, but it causes issues for some users upon fast restart.
This PR reintroduces allowing address reuse for listen sockets
> SocketConnectionListener: allow address reuse

- src/Orleans.Core/Configuration/Options/MessagingOptions.cs
- src/Orleans.Core/Messaging/Message.cs
- src/Orleans.Core/Messaging/MessageFactory.cs
- src/Orleans.Core/Messaging/StatusResponse.cs
- src/Orleans.Core/Runtime/CallbackData.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Core/Utils/ReferenceEqualsComparer.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/Catalog/IncomingRequestMonitor.cs
- src/Orleans.Runtime/Configuration/Options/SiloMessagingOptions.cs
- src/Orleans.Runtime/Core/Dispatcher.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/Messaging/OutboundMessageQueue.cs
- src/Orleans.Runtime/Scheduler/WorkItemGroup.cs
Adds a new `ActivationWorkloadMonitor` type that periodically scans active activations to analyze running and blocked requests. Requests which have been running or blocked for a configurable period of time are responded to with a status update message that is printed as a warning. Eventual timeout exceptions also include the latest status messages.
The hope is that this will improve debuggability for some users and make persistent issues more apparent.
Also adds the ability to tier timeouts based upon the most recent status update. Eg, for messages with no response, we can timeout early. For messages which are running, we can allow them to keep running past the usual 30s timeout (although we would need to also consider this when performing message expiry).
> Analyze running activations and report back status to callers for long-running and blocked requests

- Samples/3.0/AspNetCoreCohosting/API/Program.cs
Fixes #6688 by extending timeout (Only matters in more modern versions, but samples are copy/pasted.
> Set longer timeout for ASP.NET core example to match modern versions

- src/Azure/Orleans.Clustering.AzureStorage/Orleans.Clustering.AzureStorage.csproj
- src/Azure/Orleans.GrainDirectory.AzureStorage/Orleans.GrainDirectory.AzureStorage.csproj
- src/Azure/Orleans.Persistence.AzureStorage/Orleans.Persistence.AzureStorage.csproj
- src/Azure/Orleans.Reminders.AzureStorage/Orleans.Reminders.AzureStorage.csproj
- src/Azure/Orleans.Streaming.AzureStorage/Orleans.Streaming.AzureStorage.csproj
- src/Azure/Orleans.Streaming.EventHubs/Orleans.Streaming.EventHubs.csproj
- src/Azure/Orleans.Transactions.AzureStorage/Orleans.Transactions.AzureStorage.csproj
Otherwise users could encounters this error at build:
> error NU1605: Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0
> Force System.Net.NameResolution version in project with Azure dependencies

- Directory.Build.props
- Orleans.sln
- src/Orleans.Hosting.Kubernetes/ConfigureKubernetesHostingOptions.cs
- src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs
- src/Orleans.Hosting.Kubernetes/KubernetesHostingExtensions.cs
- src/Orleans.Hosting.Kubernetes/KubernetesHostingOptions.cs
- src/Orleans.Hosting.Kubernetes/KubernetesHostingOptionsValidator.cs
- src/Orleans.Hosting.Kubernetes/Orleans.Hosting.Kubernetes.csproj
- src/Orleans.Runtime/MembershipService/ClusterMember.cs
- src/Orleans.Runtime/MembershipService/ClusterMembershipService.cs
- src/Orleans.Runtime/MembershipService/ClusterMembershipSnapshot.cs
- src/Orleans.Runtime/MembershipService/IClusterMembershipService.cs
- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
- src/Orleans.Runtime/MembershipService/MembershipTableSnapshotExtensions.cs
- test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs
- test/NonSilo.Tests/Directory/MockClusterMembershipService.cs
This PR adds experimental support for integrating more deeply with Kubernetes.
Users make a call to `siloBuilder.UseKubernetesHosting()` to enable the following:
* Early in the startup process and at runtime, the silo will probe Kubernetes to find which silos do not have corresponding pods and mark those silos as dead
* Configure `ClusterOptions.ServiceId` and `ClusterOptions.ClusterId` based on labels set on the pod in Kubernetes
* Configure `SiloOptions.SiloName` based on the pod name
* Configure `EndpointOptions.AdvertisedIPAddress`, `EndpointOptions.SiloListeningEndpoint`, and `EndpointOptions.GatewayListeningEndpoint` based upon the pod's PodIP and the configured SiloPort and GatewayPort (default values 11111, 30000)
In a future update, we could consider optionally instructing …
> Kubernetes hosting integration

- Directory.Build.props
- Orleans.sln
- src/Orleans.Hosting.Kubernetes/ConfigureKubernetesHostingOptions.cs
- src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs
- src/Orleans.Hosting.Kubernetes/KubernetesHostingExtensions.cs
- src/Orleans.Hosting.Kubernetes/KubernetesHostingOptions.cs
- src/Orleans.Hosting.Kubernetes/KubernetesHostingOptionsValidator.cs
- src/Orleans.Hosting.Kubernetes/Orleans.Hosting.Kubernetes.csproj
- src/Orleans.Runtime/MembershipService/ClusterMember.cs
- src/Orleans.Runtime/MembershipService/ClusterMembershipService.cs
- src/Orleans.Runtime/MembershipService/ClusterMembershipSnapshot.cs
- src/Orleans.Runtime/MembershipService/IClusterMembershipService.cs
- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
- src/Orleans.Runtime/MembershipService/MembershipTableSnapshotExtensions.cs
- test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs
- test/NonSilo.Tests/Directory/MockClusterMembershipService.cs
* Add IClusterMembershipService.TryKill method for unilaterally declaring a silo dead
* Add Orleans.Hosting.Kubernetes extension
* Use PostConfigure for configuring EndpointOptions
* Extras
* Scope pod labels
* Mark Orleans.Hosting.Kubernetes package as beta
Co-authored-by: Benjamin Petit <bpetit@microsoft.com>
> Kubernetes hosting integration (#6707)

- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubAdapterFactory.cs
- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubDataAdapter.cs
- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/IEventHubDataAdapter.cs
* Fixes #6675: Include stream Namespace in PartitionKey for Event Hub messages
* Update IEventHubDataAdapter to support partition to StreamId mapping
@alexmg
> Fixes #6675: Update IEventHubDataAdapter to support StreamId to partition mapping (#6676)

- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
Fixes https://github.com/dotnet/orleans/issues/6758
Please guide me if any tests could/should be written.
> Make Activation Data AsyncDisposable

- src/Orleans.Core.Abstractions/CodeGeneration/InvokeMethodRequest.cs
- src/Orleans.Core.Abstractions/IDs/GrainId.cs
- src/Orleans.Core.Abstractions/IDs/UniqueKey.cs
- src/Orleans.Core.Abstractions/Logging/IdLoggingHelper.cs
- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Logging/BaseLoggingHelper.cs
- src/Orleans.Core/Logging/ClientLoggingHelper.cs
- src/Orleans.Core/Messaging/Message.cs
- src/Orleans.Core/Runtime/CallbackData.cs
- src/Orleans.Core/Runtime/Constants.cs
- src/Orleans.Core/Runtime/GrainTypeResolver.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/Logging/SiloLoggingHelper.cs
- src/Orleans.Runtime/Silo/Silo.cs
Currently, when we log a `GrainId`, you see this in your logs:
`[...] Request *cli/2cea48bd@c0bcfeac->S127.0.0.1:40960:0*grn/1688AE7A/bdcdc9a6 [...]`
With this PR, it will be
`[...] Request *cli/cb9755b0@3437749e->S127.0.0.1:40406:0*grn/UnitTests.Grains.EchoTaskGrain/7aef23f0-713b-451c-97de-ac0dbc629f71 [...]`
It should greatly improve the logging/debugging experience.
Related issue: #3852
> In GrainId.ToString(), display the grain type name and format the key properly

- src/Orleans.Core.Abstractions/IDs/SiloAddress.cs
- src/Orleans.Core/Configuration/Options/ClusterMembershipOptions.cs
- src/Orleans.Core/Networking/ConnectionManager.cs
- src/Orleans.Core/Runtime/IHealthCheckable.cs
- src/Orleans.Core/Runtime/MembershipTableSnapshot.cs
- src/Orleans.Core/Timers/ValueStopwatch.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/MembershipService/ClusterHealthMonitor.cs
- src/Orleans.Runtime/MembershipService/IRemoteSiloProber.cs
- src/Orleans.Runtime/MembershipService/LocalSiloHealthMonitor.cs
- src/Orleans.Runtime/MembershipService/MembershipAgent.cs
- src/Orleans.Runtime/MembershipService/MembershipGossiper.cs
- src/Orleans.Runtime/MembershipService/MembershipSystemTarget.cs
- src/Orleans.Runtime/MembershipService/MembershipTableCleanupAgent.cs
- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
- src/Orleans.Runtime/MembershipService/SiloHealthMonitor.cs
- src/Orleans.Runtime/Networking/ProbeRequestMonitor.cs
- src/Orleans.Runtime/Networking/SiloConnection.cs
- src/Orleans.Runtime/Networking/SiloConnectionFactory.cs
- src/Orleans.Runtime/Networking/SiloConnectionListener.cs
- src/Orleans.Runtime/Scheduler/WorkItemGroup.cs
- src/Orleans.Runtime/Silo/Watchdog.cs
- src/Orleans.Runtime/Timers/AsyncTimer.cs
- src/Orleans.Runtime/Timers/AsyncTimerFactory.cs
- test/NonSilo.Tests/Membership/ClusterHealthMonitorTests.cs
- test/NonSilo.Tests/Membership/MembershipAgentTests.cs
- test/NonSilo.Tests/Utilities/DelegateAsyncTimer.cs
This PR implements some of the ideas from Lifeguard ([paper](https://arxiv.org/abs/1707.00788), [talk](https://www.youtube.com/watch?v=u-a7rVJ6jZY), [blog](https://www.hashicorp.com/blog/making-gossip-more-robust-with-lifeguard)) which can help during times of catastrophe, where a large portion of a cluster is in a state of partial failure. One cause for these kinds of partial failures is large scale thread pool starvation, which can cause a node to run slowly enough to not process messages in a timely manner. Slow nodes can therefore suspect healthy nodes simply because the slow node is not able to process the healthy node's timely response. If a sufficiently proportion of nodes in a cluster are slow (eg, due to an application bug), then healthy nodes may have trouble joining and …
> Perform self-health checks before suspecting other nodes

- src/Orleans.Runtime/Catalog/Catalog.cs
- test/DefaultCluster.Tests/StatelessWorkerTests.cs
- test/Grains/TestGrainInterfaces/IStatelessWorkerGrain.cs
- test/Grains/TestGrains/StatelessWorkerGrain.cs
When too many activations of a stateless worker grain are created due to many concurrent invocations on a not-yet-activated grain that has a small activation limit, redirect messages from surplus activations to random valid activations, and not to any random activation. The latter would result in redirecting to another invalid activation too many times, triggering message redirect limit exceeded exceptions.
> Avoid race for stateless worker grains with activation limit #6795

- src/Orleans.Runtime/Catalog/Catalog.cs
- test/DefaultCluster.Tests/StatelessWorkerTests.cs
- test/Grains/TestGrainInterfaces/IStatelessWorkerGrain.cs
- test/Grains/TestGrains/StatelessWorkerGrain.cs
* Fix issue #6795
Co-authored-by: Benjamin Petit <bpetit@microsoft.com>
> Port: Avoid race for stateless worker grains with activation limit #6795

- src/Orleans.Core/CodeGeneration/GrainInterfaceUtils.cs
- src/Orleans.Core/CodeGeneration/TypeUtils.cs
- test/CodeGeneration/CodeGenerator.Tests/RoslynTypeNameFormatterTests.cs
- test/Grains/TestGrains/ConcreteGrainsWithGenericInterfaces.cs
- test/Grains/TestGrains/SpecializedSimpleGenericGrain.cs
- test/NonSilo.Tests/General/GrainInterfaceUtilsTests.cs
Fixed half generic naming and nested generic naming. Related to #6766 and #6777.
The correct name for half-open generic: `IHalfOpenGrain<T1,int>` for  `HalfOpenGrain1` and `IHalfOpenGrain<int,T2>` for `HalfOpenGrain2`.
``` //C#
public interface IHalfOpenGrain<T1, T2> : IGrainWithGuidKey
{ }
public class HalfOpenGrain1<T> : IHalfOpenGrain<T, int>
{ }
public class HalfOpenGrain2<T> : IHalfOpenGrain<int, T>
{ }
``` 
Fixed ArgumentOutOfRange for `Root<>.G<,,,>`. Also, I strongly recommend avoiding the usage of grains in generic types.
```//C#
public interface IG<T> : IGrain
{
}
public class G1<T1, T2, T3, T4> : Grain, Root<T1>.IA<T2, T3, T4>
{
}
public class Root<TRoot>
{
public interface IA<T1, T2, T3> : IGrainWithIntegerKey
{
}
public class G<T1, T2, T3> : Grain, IG<IA<T1, T2, T3>>
{
}
} …
```
> Fix for half and nested generics.

- src/Orleans.Core/Configuration/Options/ClusterMembershipOptions.cs
- src/Orleans.Core/SystemTargetInterfaces/IMembershipService.cs
- src/Orleans.Runtime/Core/SystemTargetExtensions.cs
- src/Orleans.Runtime/MembershipService/ClusterHealthMonitor.cs
- src/Orleans.Runtime/MembershipService/ClusterMembershipService.cs
- src/Orleans.Runtime/MembershipService/IRemoteSiloProber.cs
- src/Orleans.Runtime/MembershipService/MembershipSystemTarget.cs
- src/Orleans.Runtime/MembershipService/RemoteSiloProber.cs
- src/Orleans.Runtime/MembershipService/SiloHealthMonitor.cs
- test/NonSilo.Tests/Membership/ClusterHealthMonitorTests.cs
- test/NonSilo.Tests/Membership/MembershipAgentTests.cs
- test/NonSilo.Tests/Membership/SiloHealthMonitorTests.cs
* Probe silos indirectly before submitting a vote
* Improve tests
* Remove no-longer necessary cases in SiloHealthMonitor, since concurrency has been removed.
> [Backport] Probe silos indirectly before submitting a vote (#6800)

- src/TelemetryConsumers/Orleans.TelemetryConsumers.Linux/LinuxEnvironmentStatistics.cs
Avoid exceptions when shutdown a silo where the monitoring task wasn't completed yet.
> Avoid disposing uncompleted task in LinuxEnvironmentStatistics

- src/Azure/Orleans.Clustering.AzureStorage/OrleansSiloInstanceManager.cs
- src/Orleans.Core/Utils/Utils.cs
- test/NonSilo.Tests/General/UtilsTests.cs
#6823 changed some behavior slightly. This PR undoes that.
> Fix ToGatewayUri after #6823

- src/Orleans.CodeGenerator/Generators/GrainReferenceGenerator.cs
- src/Orleans.CodeGenerator/Orleans.CodeGenerator.csproj
- src/Orleans.Core/CodeGeneration/GenericMethodInvoker.cs
- test/CodeGeneration/CodeGenerator.Tests/CodeGenerator.Tests.csproj
- test/CodeGeneration/CodeGenerator.Tests/GenericMethodInvokerTests.cs
- added code to select correct overload for generic methods; previously was always selecting first overload, regardless of parameters provided.
- invokers cache now caches with a compound key of generic type parameter(s) + argument type(s). Before it was caching by type parameter(s) only, which would collapse all overloads sharing type parameters into one entry, e.g.
```C#
Task<int> Method<T>(int x);
Task<int> Method<T>(int x, string y);
```
If these two methods were invoked with the same `T`, then the callsite cache would only ever invoke the first match, even if two params were passed.
- improve error message on failure to find suitable overload (it now shows the actual type parameters, and not just the arity)
- added tests for invoker
Closes …
> fix: genericmethodinvoker now correctly handles generic methods with overloads

- src/Orleans.Core/Configuration/Options/ReminderOptions.cs
- src/Orleans.Core/Logging/ErrorCodes.cs
- src/Orleans.Core/Logging/ILoggerExtensions.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/ReminderService/ReminderRegistry.cs
- src/Orleans.Runtime/Silo/Silo.cs
- test/Grains/TestInternalGrains/ReminderTestGrain2.cs
- test/Tester/MinimalReminderTests.cs
One minute minimum restriction on Reminder period
- Added configurable options via ISiloHostBuilder
- Added Unit Tests to verify smaller reminder period no longer causes Silo to not start
- Resolved Tests to allow for new smaller interval
Fixes #4218 
**Log Entry**
[2020-12-09 16:50:11.014 GMT 11	Warning	0	Orleans.Runtime.Silo]	A Minimal Reminder Interval of 0:00:00.1 has been set. High-Frequency reminders are dangerous for production use.
> Added ability to configure reminder period

- src/AdoNet/Shared/Storage/DbConnectionFactory.cs
MySqlConnector 1.x introduces two breaking changes, which prevents Orleans from using the new version of the driver. This modification will enable the factory class loader to support multiple assemblies and class names to be compatible with versions 0.x and 1.x.
> Add ADO.NET Provider support MySqlConector 0.x and 1.x.

- src/Orleans.Core/Utils/LRU.cs
LRU is using ConcurrentDictionary to keep elements in memory. The Add method is using ConcurrentDictionary.Count which may create contention if multiple threads are trying to use the object.
This change wraps CurrentDictionary in a ConcurrentDictionary-like object providing faster count updated on additions and removals.
Plus a few cosmetic changes.
> Improve performance of LRU.Add()

- src/Orleans.Core/Utils/LRU.cs
LRU is using ConcurrentDictionary to keep elements in memory. The Add method is using ConcurrentDictionary.Count which may create contention if multiple threads are trying to use the object.
This change wraps CurrentDictionary in a ConcurrentDictionary-like object providing faster count updated on additions and removals.
Plus a few cosmetic changes.
> [Backport] Improve performance of LRU.Add() (#6870)

- src/Orleans.Core/Messaging/GatewayManager.cs
- src/Orleans.Core/Messaging/IGatewayListProvider.cs
Fixes #6869
I see no strong need to deprecate the functionality first, since it is likely unused. Thankfully, `IGatewayListObservable` was an optional interface, with no implementers.
> Remove IGatewayListListener and IGatewayListObservable

- src/Orleans.Connections.Security/Security/DuplexPipeStream.cs
- src/Orleans.Connections.Security/Security/DuplexPipeStreamAdapter.cs
- src/Orleans.Connections.Security/Security/TlsClientConnectionMiddleware.cs
- src/Orleans.Connections.Security/Security/TlsServerConnectionMiddleware.cs
- src/Orleans.Core/Messaging/GatewayManager.cs
- src/Orleans.Core/Networking/Connection.cs
- src/Orleans.Core/Networking/ConnectionFactory.cs
- src/Orleans.Core/Networking/ConnectionManager.cs
- src/Orleans.Core/Networking/IUnderlyingTransportFeature.cs
- src/Orleans.Runtime/Messaging/Gateway.cs
- src/Orleans.Runtime/Networking/ConnectionListener.cs
- src/Orleans.Runtime/Networking/SiloConnectionMaintainer.cs
~Lock around connection cleanup so we don't call .Complete() and .CancelPendingFlush()/.CancelPendingRead() on the same pipe which results in an ObjectDisposedException.~
Fixes #6747 
EDIT by @ReubenBond:
Updated PR description
* Add `Connection.CloseAsync(Exception)` method, which closes the connection asynchronously, completing the returned task once it has
* Clean up logging around expected termination cases
* Migrate to newer version of DuplexPipeStream.cs from dotnet/aspnetcore codebase (we are still running a fork until Bedrock is upstreamed into .NET itself or forked into a standalone lib)
> Close connections asynchronously and improve gracefulness

- src/Orleans.Runtime/Core/Dispatcher.cs
To print when actually forwarding a message to another silo
> [Dispatcher] Moving the forwarding message

- src/Orleans.Core/SystemTargetInterfaces/IRemoteGrainDirectory.cs
- src/Orleans.Runtime/GrainDirectory/GrainDirectoryHandoffManager.cs
- src/Orleans.Runtime/GrainDirectory/ILocalGrainDirectory.cs
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
- src/Orleans.Runtime/GrainDirectory/RemoteGrainDirectory.cs
- src/Orleans.Runtime/Silo/Silo.cs
- test/NonSilo.Tests/Directory/MockLocalGrainDirectory.cs
The in-cluster directory has a mechanism for handing off partition segments during graceful shutdown. This functionality does not prevent grains which were registered on the now-dead silo from being destroyed, however, because there are no guarantees which are strong enough to maintain the desired invariants (every activation is registered, at most one activation is registered for each grain).
Therefore, this PR removes that functionality. We can consider other options to reduce the impact of silo shutdown in future, such as directory replication. Note that external grain directories do not have this attribute.
> Do not hand off grain directory during shutdown

- src/Orleans.Core/Utils/LRU.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/Core/Dispatcher.cs
- test/DefaultCluster.Tests/BasicActivationTests.cs
- test/DefaultCluster.Tests/GenericGrainTests.cs
- test/DefaultCluster.Tests/StatelessWorkerTests.cs
- test/DependencyInjection.Tests/DependencyInjectionGrainTestsRunner.cs
- test/Grains/TestGrainInterfaces/ITestGrain.cs
- test/Grains/TestInternalGrains/TestGrain.cs
- test/NonSilo.Tests/General/LruTest.cs
The goal of this PR is to reduce the occurrence of forwarding failure because a grain cannot be activated due to a failure in `OnActivateAsync()`.
When a grain has no activation, it's possible that multiple silos will _try_ to create multiple activations for the same grain identity at the same time. But only one activation will win the race, and all other silos will then forward the requests to the winning activation.
If this winning activation throws during `OnActivateAsync()`, it might trigger another potential race for activation creation, and additional forwarding. As a result, the user might see several "Forwarding failed" exceptions instead of the exception that was thrown during the activation process.
> Try to limit forwarding when a grain activation throws an exception in OnActivateAsync()

- src/Orleans.Runtime/GrainDirectory/GrainDirectoryPartition.cs
In `GrainDirectoryPartition` we return `null` if we are trying to register a grain on an invalid silo". Instead, we should throw an exception that clearly says the reason of the rejection.
Related issue: #6894
> Throw an exception when trying to register an activation on an invalid silo

- test/TestInfrastructure/Orleans.TestingHost.AppDomain/AppDomainSiloHost.cs
> Hack to force TLS 1.2 when using AppDomain based test silo

- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Serialization/DotNetSerializableSerializer.cs
- src/Orleans.Core/Serialization/ILBasedExceptionSerializer.cs
- src/Orleans.Core/Serialization/KeyedSerializerId.cs
- src/Orleans.Core/Serialization/UnavailableExceptionFallbackException.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- test/Grains/TestInternalGrains/SerializationTestTypes.cs
- test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs
- test/NonSilo.Tests/Serialization/DotNetSerializableTests.cs
- test/NonSilo.Tests/Serialization/ILBasedExceptionSerializerTests.cs
Implements a new serializer specifically for conforming `ISerializable` implementations. This is intended to replace most of the use case that we currently have for `BinaryFormatter`, which is blocked in .NET 5
This also adds fallback exception serialization so that exception types which are unknown by the deserializing party (eg, the caller of a method which throws) can be deserialized into a special type, maintaining the stack.
Additionally, this supports deserializing exception types which do not expose a protected deserialization constructor (because they did not correctly implement the `ISerializable` pattern)
> Implement ISerializable fallback serializer

- src/Orleans.CodeGenerator/Utilities/SymbolSyntaxExtensions.cs
Poking around this code area and a warning for this not doing anything popped up. I don't have the context here to know why it was being called but not returned, @ReubenBond?
> Fixing potential oversight of immutable code call

- src/Orleans.CodeGenerator.MSBuild/Program.cs
Replacing the stale and unused PrintUsage with a current one. This is mostly for code documentation but does also improve the command-line output however unlikely to be seen.
> Updating Orleans.CodeGenerator.MSBuild with better documentation

- src/Orleans.Analyzers/AnalyzerReleases.Shipped.md
- src/Orleans.Analyzers/InheritFromGrainBaseAnalyzer.cs
- src/Orleans.Analyzers/InheritFromGrainBaseCodeFixProvider.cs
- test/Analyzers.Tests/InheritFromGrainBaseAnalyzerTests.cs
Closing #6194
From the feedback, it might be helpful to have an analyzer check to see if a non-abstract class implements `IGrain`, but doesn't inherit from `Grain`.
Previously, there was no message from the compiler when a user forgets to derive an implementation from the base `Grain` class, so this analyzer will generate ORLEANS0003 and inform the user that "Non-abstract classes that implement IGrain should derive from the base class Orleans.Grain".
Example, using [HelloWorld](https://github.com/dotnet/orleans/tree/master/Samples/3.3/HelloWorld) from the Samples, where `HelloGrain` implements `IHello`, which implements the interface `IGrainWithIntegerKey`:
Another addition is the CodeFixProvider, which provides the user with a potential fix:
Also works on classes that derive from an …
> Adding analyzer to notify user classes that implement IGrain should inherit from Grain

- Directory.Build.props
- src/Azure/Orleans.Streaming.EventHubs/Orleans.Streaming.EventHubs.csproj
Updating the Event Hubs client library to v5.3.0 (GA) which resolves the AMQP dependency issue with .NET 5.  This requires updating the `Azure.Core` package due to transitive dependences.  Both libraries guarantee backwards compatibility and should not introduce breaking changes as a result of the update.
Also Removing the direct reference to `Microsoft.Azure.Amqp`, as it was needed only as a workaround to the .NET 5 compatibility issue.
> Event Hubs: Update to the latest GA package

- src/Orleans.Core/Utils/LRU.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/GrainDirectory/AdaptiveGrainDirectoryCache.cs
- src/Orleans.Runtime/GrainDirectory/LRUBasedGrainDirectoryCache.cs
- test/NonSilo.Tests/General/LruTest.cs
* Fix race condition in `AddOrUpdate` use from #6870.
* Remove dictionary wrapper that had redundant (4) generic type arguments.
* Trim `RaiseFlushEvent` overhead (only used by tests).
* Remove unused `fetcher` logic.
> Fix LRU race conditions and remove dead code

- src/Orleans.Core/Networking/ConnectionManager.cs
- src/Orleans.Core/Runtime/GrainCancellationTokenRuntime.cs
- src/Orleans.Runtime/Catalog/ActivationCollector.cs
- src/Orleans.Runtime/Catalog/ActivationDirectory.cs
- src/Orleans.Runtime/Messaging/Gateway.cs
- src/Orleans.Runtime/Networking/ConnectionListener.cs
- src/Orleans.Runtime/Placement/ActivationCountPlacementDirector.cs
- src/Orleans.Runtime/Scheduler/OrleansTaskScheduler.cs
- src/Orleans.Streaming/Generator/GeneratorAdapterFactory.cs
- src/Orleans.Streaming/Internal/StreamConsumerExtension.cs
- src/Orleans.Streaming/SimpleMessageStream/SimpleMessageStreamProducerExtension.cs
- src/Orleans.TestingHost/Logging/FileLogger.cs
- src/Serializers/Orleans.Serialization.ProtobufNet/ProtobufNetSerializer.cs
- src/Serializers/Orleans.Serialization.ProtobufNet/ProtobufTypeCacheItem.cs
- test/NonSilo.Tests/TestInternalHelper.cs
* Reduce global locking when accessing `ConcurrentDictionary` by reducing use of `Keys/Values/Count/IsEmpty`.
* Remove some dead code.
Inspider by #6870.
> Reduce global lock use for ConcurrentDictionary

- src/Azure/Orleans.Streaming.EventHubs/Orleans.Streaming.EventHubs.csproj
Rename of the Microsoft.Orleans.OrleansServiceBus package based on #6954
> Rename Microsoft.Orleans.OrleansServiceBus package to Microsoft.Orleans.Streaming.EventHubs

- src/Orleans.Core/Messaging/Message.cs
- test/NonSilo.Tests/General/MessageTests.cs
If `Message.Start()` is never called, `Message.Elapsed` throws a
`NullReferenceException` because `timeInterval` is never set.
Return `TimeSpan.Zero` if `timeInterval` is null.
I discovered this when the logging framework we use attempted to
serialize the Message object that is included in some log messages, like
the one emitted from /src/Orleans.Runtime/Core/Dispatcher.cs line 445 as
of commit cd8fcd745 (Implement C# Source Generator (#6925), 2021-02-18):
logger.LogError(
(int)ErrorCode.Dispatcher_ErrorCreatingActivation,
ex,
"Error creating activation for grain {TargetGrain} (interface: {InterfaceType}). Message {Message}",
msg.TargetGrain,
msg.InterfaceType,
msg);
Yes, the logging framework we're using is trying to serialize too much.
----------------
A different approach: the timing …
> Return zero elapsed time for unstarted Messages

- src/Orleans.Core/Networking/Connection.cs
- src/Orleans.Core/Networking/ConnectionManager.cs
- src/Orleans.Core/Networking/Shared/SocketConnectionFactory.cs
- src/Orleans.Runtime/Networking/ConnectionListener.cs
- src/Orleans.Runtime/Networking/GatewayConnectionListener.cs
- src/Orleans.Runtime/Networking/SiloConnectionListener.cs
This improves the error message for connection opening timeouts.
Also updated `SocketConnectionFactory.ConnectAsync` to properly support cancellation (mostly copied from dotnet/runtime repo).
Message diff for OrleansMessageRejectionException looks similar to this:
```diff
+Exception while sending message: Orleans.Runtime.Messaging.ConnectionFailedException: Connection attempt to endpoint S10.0.0.4:11111:332519906 timed out after 00:00:03
-Exception while sending message: Orleans.Runtime.Messaging.ConnectionFailedException: Unable to connect to endpoint S10.0.0.4:11111:332519906. See InnerException ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
-   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
-   at …
```
> Improve error message for OpenConnectionTimeout

- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
Fixes a race causing some messages to not be terminated when a silo shuts down, leaving them to timeout instead
> Fix breaking of outstanding messages when a silo shuts down

- src/Orleans.Persistence.Memory/Hosting/MemoryGrainStorageSiloBuilderExtensions.cs
`MemoryGrainStorageOptionsValidator` was previously unused. We could alternatively delete it.
> Configure MemoryGrainStorageOptionsValidator

- Directory.Build.targets
- src/Orleans.CodeGenerator/Orleans.CodeGenerator.csproj
- src/Orleans.CodeGenerator/OrleansSourceGenerator.cs
- src/Orleans.CodeGenerator/build/Microsoft.Orleans.CodeGenerator.props
- src/Orleans.CodeGenerator/buildMultiTargeting/Microsoft.Orleans.CodeGenerator.props
The first part of #6999 is simply to not run the C# Source Generator during IDE-builds. This also requires correctly packaging the source generator.
> Prevent source generator from running during design time

- src/Orleans.Core.Abstractions/Timers/IRemindable.cs
Reminder functionality is not unit tests friendly because TickStatus has only internal constructor.
Changing accessing modifier to `public` will allow to cover Reminder functionality of grain with unit tests without hacks like using reflection to access constructor or creating virtual methods for deconstruction of tick status in grain.
> TickStatus constructor access modifier changed to public

- test/Benchmarks/Benchmarks.csproj
- test/Benchmarks/GrainStorage/GrainStorageBenchmark.cs
- test/Benchmarks/Program.cs
- test/Grains/BenchmarkGrainInterfaces/GrainStorage/IPersistentGrain.cs
- test/Grains/BenchmarkGrains/GrainStorage/PersistentGrain.cs
I wanted a better benchmark for AdoNet to compare concurrent read/writes and payloads that exceed maximum column sizes for various datastores. 
1. Add GrainStorage.AdoNet benchmark
2. Add concurrency to all GrainStorageBenchmark
3. Add configurable payload to PersistentGrain
4. Accurately time PersistentStore by isolating it's Read/Write call separate of Orleans overhead
5. Force Read and Write and avoid etag/cache.
Please advise for concurrency number and payload sizes. I just guessed at either 10 or 100 concurrent requests, and 10000 byte payloads.
> Add GrainStorage.AdoNet benchmark along with concurency and larger payloads

- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubQueueCache.cs
- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubQueueCacheFactory.cs
- src/Orleans.Core/Streams/Core/StreamIdentity.cs
- src/Orleans.Core/Streams/PersistentStreams/StreamConsumerCollection.cs
- src/Orleans.Runtime/Streams/PersistentStream/PersistentStreamPullingAgent.cs
- src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
- src/OrleansProviders/Streams/Common/RecoverableStreamOptions.cs
- test/Extensions/ServiceBus.Tests/EvictionStrategyTests/TestMocks.cs
- test/Extensions/ServiceBus.Tests/Streaming/EHCustomBatchContainerTests.cs
- test/Extensions/ServiceBus.Tests/TestStreamProviders/EHStreamProviderWithCreatedCacheList.cs
- test/Grains/TestGrainInterfaces/IImplicitSubscriptionCounterGrain.cs
- test/Grains/TestGrains/ImplicitSubscriptionCounterGrain.cs
- test/Tester/StreamingTests/MemoryStreamCacheMissTests.cs
- test/Tester/StreamingTests/StreamingCacheMissTests.cs
- test/TesterInternal/OrleansRuntime/Streams/PooledQueueCacheTests.cs
In the current implementation of `PooledQueueCache` (the cache used notably by the EventHub streaming provider), in order to advance a cursor from event `N` to event `N+1`, both events need to be in cache, to ensure that nothing was missed between the two.
That means that if event `N` was evicted, trying to move the cursor will throw a `QueueCacheMissException`, even if the subscriber already consumed this event and is waiting for event `N+1`. This behavior can be really confusing for streaming users.
In this PR, the `PooledQueueCache` keeps a dictionary of `StreamId` -> `StreamSequenceToken` to keep track of the token from the last evicted event for a given stream. 
If the consumer already processed event `N` and this event is not in cache:
- If event `N` was the last evicted event for …
> In PooledQueueCache, avoid cache miss if we know that we didn't missed any event

- src/AWS/Orleans.Clustering.DynamoDB/Options/DynamoDBClusteringOptions.cs
- src/AWS/Orleans.Clustering.DynamoDB/Options/DynamoDBGatewayOptions.cs
- src/AWS/Orleans.Clustering.DynamoDB/Orleans.Clustering.DynamoDB.csproj
- src/AWS/Orleans.Persistence.DynamoDB/Options/DynamoDBStorageOptions.cs
- src/AWS/Orleans.Persistence.DynamoDB/Orleans.Persistence.DynamoDB.csproj
- src/AWS/Orleans.Reminders.DynamoDB/Orleans.Reminders.DynamoDB.csproj
- src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDbReminderStorageOptions.cs
- src/AWS/Shared/Storage/DynamoDBClientOptions.cs
In preparation for https://github.com/dotnet/orleans/pull/7082, as a result of feedback I received https://github.com/dotnet/orleans/pull/7082#pullrequestreview-659888375 and inspired by the PR referenced in the feedback: https://github.com/dotnet/orleans/pull/7019 I am first consolidating all `DynamoDBClientOptions` in order not to repeat reused properties.
In order to complete https://github.com/dotnet/orleans/pull/7082 my goal is to eventually extend `DynamoDBClientOptions` with two more properties:
* `string Token` (holding one's AWS authentication token) - this is to support DynamoDB connections requiring not only access key and secret key, but also a token. This is not supported today.
* `string ProfileName` (name of one's named profile used to authenticate with AWS) - this is to …
> Consolidated DynamoDBClientOptions

- src/Orleans.CodeGenerator/Generators/SerializerGenerator.cs
- test/DefaultCluster.Tests/SerializationTests/RoundTripSerializerTests.cs
- test/Grains/TestGrainInterfaces/IValueTypeTestGrain.cs
- test/Grains/TestGrainInterfaces/IsExternalInit.cs
- test/Grains/TestGrains/RoundtripSerializationGrain.cs
Enables support for serialization of c# 9 records for grain method return values and parameters. 
Thanks to @ReubenBond for the guiding hand.
> Add c#9 record support to serializer

- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBGatewayListProvider.cs
- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBMembershipTable.cs
- src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
- src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDBReminderTable.cs
- src/AWS/Shared/Storage/DynamoDBClientOptions.cs
- src/AWS/Shared/Storage/DynamoDBStorage.cs
As a follow up to https://github.com/dotnet/orleans/pull/7083, I'm introducing tokens in dynamodb client configuration. This resolves problems where authentication relies not only on:
* access key
* secret key
but also on tokens. At the moment:
* orleans documentation does not describe such situations: https://dotnet.github.io/orleans/docs/grains/grain_persistence/dynamodb_storage.html
* token-based dynamodb authentication is not supported
This change allows for both types of authentication credentials:
* access key & secret key
* access key & secret key & token
Usage:
```csharp
siloBuilder.AddDynamoDBGrainStorage(
name: "profileStore",
configureOptions: options =>
{
options.UseJson = true;
options.AccessKey = "***";
options.SecretKey = "***";
options.Token = "***";
options.Service = …
```
> Added token to DynamoDB client configuration.

- src/Azure/Orleans.GrainDirectory.AzureStorage/AzureTableGrainDirectory.cs
- src/Orleans.Core.Abstractions/GrainDirectory/IGrainDirectory.cs
- src/Orleans.Core.Abstractions/IDs/GrainId.cs
- src/Orleans.Core.Abstractions/IDs/SiloAddress.cs
- src/Orleans.Core.Abstractions/Runtime/MembershipVersion.cs
- src/Orleans.GrainDirectory.Redis/RedisGrainDirectory.cs
- src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs
- src/Orleans.Runtime/GrainDirectory/LRUBasedGrainDirectoryCache.cs
- test/Extensions/TesterAzureUtils/AzureGrainDirectoryTests.cs
- test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs
- test/Tester/Directories/GrainDirectoryTests.cs
The field `MembershipVersion` in the `GrainId` struct will help with address invalidation
> In GrainId, use concrete types instead of string and store the MembershipVersion

- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorage.cs
Currently the `AzureBlobStorage` persistence provider doesn't use the state type when deserializing JSON. As a result, this makes it so that the provider requires `TypeNameHandling.All` in order to work.
The other providers all use the state type during JSON deserialization, which allows you to use `TypeNameHandling.None`.
> Updated AzureBlobStorage to use state type during JSON deserialization

- src/Orleans.Runtime/Hosting/GrainCallFilterExtensions.cs
an AddIncomingGrainCallFilter overload mistakenly had IOutgoingGrainCallFilter in its summary.
> Fix summary reference on GrainCallFilterExtensions

- src/Orleans.Hosting.Kubernetes/KubernetesClientExtensions.cs
Fix unawaited background task to suppress any exception from the ChannelReader's Completion task.
The channel reader's Completion task would re-raise the exception set on the channel writer and cause an unhandled exception in the unawaited task and crash silo.
We have witnessed multiple cases when the HTTPS connection between the k8s watcher and the k8s API was lost, and it caused a silo crash. The investigation led to this unawaited background task. (See attached exception.)
```
[12:04:14 FTL] An unhandled exception occurred during the execution of ***-silo on ******.svc.cluster.local <s:******.Platform.Hosting.UnhandledExceptionHandler>
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the …
```
> Fix unhandled exception on k8s watcher background task

- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBGatewayListProvider.cs
- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBMembershipTable.cs
- src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
- src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDBReminderTable.cs
- src/AWS/Shared/Storage/DynamoDBClientOptions.cs
- src/AWS/Shared/Storage/DynamoDBStorage.cs
This is third and last PR of a series of changes resulting from an issue I reported in May:
https://github.com/dotnet/orleans/issues/7077
Previous PRs: 
1. groundwork refactoring: https://github.com/dotnet/orleans/pull/7083
2. add aws credentials token: https://github.com/dotnet/orleans/pull/7104
In this PR I'm taking the dynamodb client options one step further allowing for non-default aws profile names (like e.g. `sts`, which I've been using myself for a while). This change should enrich the spectrum of dynamodb connectivity options further for more people.
Depending on the feedback this PR receives, a follow-up documentation change will have to be made:
https://dotnet.github.io/orleans/docs/grains/grain_persistence/dynamodb_storage.html
which I'm happy to do.
> Added AWS profile name support to DynamoDBStorage.

- src/Orleans.CodeGenerator/OrleansSourceGenerator.cs
There's no first-class way to prevent a Source Generator from running within non-build processes yet, so we will filter those out for now.
> Improve code generator editor experience

- src/Orleans.Connections.Security/Security/TlsClientAuthenticationOptions.cs
- src/Orleans.Connections.Security/Security/TlsClientConnectionMiddleware.cs
- src/Orleans.Connections.Security/Security/TlsOptions.cs
Adds the ability to use a certificate selector for client connections. See issue #7143 .
> Add selector for the client

- src/Orleans.Runtime/ConsistentRing/VirtualBucketsRingProvider.cs
Fixes #7193
I've described a rationale behind it in code comment - since hash collisions are rare, I'm optimizing for number of lookups in general case.
> VirtualBucketsRingProvider.RemoveServer: check if removed buckets belonged to removed silo

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/library-scripts/azcli-debian.sh
This PR adds the basic files to support newcomers to open Orleans repo into the new GitHub CodeSpaces reducing the friction for contributions since people wouldn't even need to clone the repo.
The container can be used in a browser or in VSCode. It contains initially just the .Net SDK, capable of build, tests, and run the samples. Further more, we can add emulators to the image like Azure Storage, SQL, Cosmos, etc.
One thing that would perhaps be good is to remove `.vscode` from the `.gitignore` file. That would allow us to have all the samples pre-configured there allowing people to just hit Run on them. Otherwise, every single person who open this, will be required to create the build/run files (tasks.json and launch.json) and configure each file. It is not a requirement but would be …
> Initial support to CodeSpaces and Dev Container

- src/Orleans.Core.Abstractions/Core/Grain.cs
- src/Orleans.Core.Abstractions/Runtime/RuntimeContext.cs
- src/Orleans.Core/Statistics/MessagingProcessingStatisticsGroup.cs
- src/Orleans.Runtime/Activation/GrainContextAccessor.cs
- src/Orleans.Runtime/Core/GrainRuntime.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- src/Orleans.Runtime/Core/SystemTarget.cs
- src/Orleans.Runtime/Scheduler/ActivationTaskScheduler.cs
- src/Orleans.Runtime/Scheduler/SchedulerExtensions.cs
- src/Orleans.Runtime/Services/GrainServiceClient.cs
- src/Orleans.Runtime/Timers/GrainTimer.cs
- src/Orleans.Streaming/Providers/SiloProviderRuntime.cs
- test/Benchmarks/Ping/PingBenchmark.cs
- test/Benchmarks/Serialization/MessageBenchmark.cs
- test/Benchmarks/Serialization/Models/Orleans/BenchmarkActivationAddress.cs
- test/Benchmarks/Serialization/Models/Orleans/BenchmarkMessage.cs
- test/DefaultCluster.Tests/HostedClientTests.cs
- test/Grains/TestInternalGrains/ErrorGrain.cs
- test/Grains/TestInternalGrains/PersistenceTestGrains.cs
- test/Grains/TestInternalGrains/TimerGrain.cs
- test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests.cs
Reduces the indirection in `RuntimeContext` so that instead of a `[ThreadStatic]` pointing to an object with an `IGrainContext` property on it, the `[ThreadStatic]` points directly to the `IGrainContext`
> Reduce indirection in RuntimeContext

- src/Orleans.Core.Abstractions/IDs/IdSpan.cs
This aligns `.Equals(other)` with `.IsDefault`, which treats null backing arrays as equal to empty backing arrays
> Change equality for IdSpan so that empty and null values are identical

- src/Orleans.Core.Abstractions/IDs/ActivationAddress.cs
- src/Orleans.Core.Abstractions/IDs/ActivationId.cs
- src/Orleans.Core/Messaging/Message.cs
- src/Orleans.Core/Messaging/MessageFactory.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
- src/Orleans.Core/Networking/Connection.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs
- src/Orleans.Runtime/GrainDirectory/RemoteGrainDirectory.cs
- src/Orleans.Runtime/Messaging/Gateway.cs
- src/Orleans.Runtime/Messaging/MessageCenter.cs
- test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs
- test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs
This PR makes `ActivationId` a simple `Guid`-backed struct, rather than a class backed by the (rather large) `UniqueKey` class.
> Make ActivationId a struct backed by a Guid

- src/Orleans.Core/Messaging/Message.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
- src/Orleans.Core/Networking/Connection.cs
- src/Orleans.Runtime/Networking/SiloConnection.cs
This PR merges the `HeadersContainer` class into the `Message` class.
The two types have identical lifetimes and are never used separately.
The benefit of merging them are:
* Less code
* Improved performance due to fewer allocations and less indirection.
> Merge HeadersContainer into Message

- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
When a lookup lands on the local grain directory, consulting the cache before consulting the local grain directory partition can reduce contention. Essentially, the cache is designed for concurrent lookups, while the directory needs to pay some additional consistency cost. 
This made a significant impact in local benchmarking.
> LocalGrainDirectory: reduce lookup contention by consulting cache before partition

- src/Orleans.Core.Abstractions/Activation/IGrainContext.cs
- src/Orleans.Core/Messaging/Message.cs
- src/Orleans.Core/Networking/SocketDirection.cs
- src/Orleans.Core/Statistics/MessagingProcessingStatisticsGroup.cs
- src/Orleans.Core/Statistics/MessagingStatisticsGroup.cs
- src/Orleans.Core/Timers/CheapStopwatch.cs
- src/Orleans.Core/Utils/LRU.cs
- src/Orleans.Runtime/Catalog/ActivationCollector.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/GrainDirectory/AdaptiveGrainDirectoryCache.cs
We currently use our custom `ValueStopwatch` struct in many places where we want a non-allocating stopwatch to measure durations with high precision. `ValueStopwatch` is suitable for measuring very short durations infrequently, but it can be expensive on hot paths because it uses `Stopwatch.GetTimestamp()`, which involves a system call.
`CoarseStopwatch` uses `Environment.TickCount64` ("milliseconds since the system started") instead, which is much cheaper but has the downside of being less accurate and less precise. It's more suitable for use on hot paths when timing longer running events where accuracy is not critical. For example, LRU cache ages, message age/queueing duration, and activation idleness.
Note that this PR is should be merged after #7245, since both make changes to …
> Add `CoarseStopwatch` using `Environment.TickCount64` and use on hot paths

- src/Orleans.Serialization/Cloning/IDeepCopier.cs
- src/Orleans.Serialization/Invocation/Pools/ConcurrentObjectPool.cs
- src/Orleans.Serialization/Invocation/Pools/DefaultConcurrentObjectPoolPolicy.cs
- src/Orleans.Serialization/Invocation/Pools/InvokablePool.cs
- src/Orleans.Serialization/Invocation/Pools/ResponseCompletionSourcePool.cs
- src/Orleans.Serialization/Invocation/Pools/ResponsePool.cs
- src/Orleans.Serialization/Session/SerializerSessionPool.cs
In local benchmarks, `DefaultObjectPool` became a dominator. This implementation improved TPS by 20% in one scenario (in-proc messaging) by relying on thread-local stacks.
> Add and use `ConcurrentObjectPool` instead of `DefaultObjectPool`

- src/Orleans.Core/Core/ClientBuilderExtensions.cs
- src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs
- src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
- test/Grains/TestGrainInterfaces/IActivityGrain.cs
- test/Grains/TestGrains/ActivityGrain.cs
- test/Tester/DiagnosticTests.cs
Added distributed tracing support: added grain filters for activity propagation.
#4992
> Added distributed tracing support: activity and diagnostic listener.

- src/Orleans.Core/Utils/LRU.cs
I broke `LRU` in #7246. This PR fixes it by flipping the condition in `RemoveExpired`
> Fix break to LRU.RemoveExpired()

- src/Orleans.Core.Abstractions/Runtime/GrainReference.cs
- src/Orleans.Core.Abstractions/Runtime/IAddressable.cs
- src/Orleans.Core.Abstractions/Runtime/IGrainExtension.cs
- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Transactions/TransactionAttribute.cs
- test/Grains/TestGrainInterfaces/IEchoTaskGrain.cs
`NewGrainReference` was intended as a temporary class in the `GrainReference` hierarchy while works were ongoing. This PR removes it by flattening it into `GrainReference`.
> Remove NewGrainReference

- src/Orleans.CodeGenerator/Model/InvokableInterfaceDescription.cs
- src/Orleans.CodeGenerator/ProxyGenerator.cs
- src/Orleans.Core.Abstractions/Runtime/GrainReference.cs
- src/Orleans.Core.Abstractions/Runtime/IAddressable.cs
- src/Orleans.Core.Abstractions/Runtime/IGrainExtension.cs
- src/Orleans.Core.Abstractions/Runtime/IGrainReferenceRuntime.cs
- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs
- src/Orleans.Core/Runtime/GrainReferenceRuntime.cs
- src/Orleans.Core/Runtime/OutgoingCallInvoker.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Serialization/Invocation/Response.cs
- src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs
- src/Orleans.Transactions/TransactionAttribute.cs
- test/Benchmarks/Ping/ConcurrentLoadGenerator.cs
- test/Benchmarks/Ping/PingBenchmark.cs
- test/Grains/BenchmarkGrainInterfaces/Ping/IPingGrain.cs
- test/Grains/BenchmarkGrains/Ping/LoadGrain.cs
- test/Grains/BenchmarkGrains/Ping/PingGrain.cs
- test/Grains/TestGrainInterfaces/IEchoTaskGrain.cs
- test/Orleans.Serialization.UnitTests/InvokableTestInterfaces.cs
Currently, `ValueTask` returning methods incur unnecessary memory allocations internally compared with `ValueTask<T>` and return types which necessarily allocate, such as `Task`/`Task<T>`.
This PR removes those unnecessary allocations by adding explicit support for non-value returning methods in the runtime.
> Improve performance for `ValueTask` methods

- Directory.Build.props
This fixes some incompatibility issues on .NET 5 with Azure Event Hubs
Fixes #7057
> [3.5.0] Upgrade Azure EventHubs

- src/Orleans.Core.Abstractions/Core/GrainExtensions.cs
- test/Tester/GrainServiceTests/TestGrainService.cs
Fixes #7055 by adding support for calling `GetPrimaryKey` variants from classes which inherit from `jSystemTarget`, such as `GrainService` implementations.
Note that this targets the `3.x` branch, which is currently even with `3.5.0`
> [3.x] Implement GetGrainId() for SystemTargets & GrainService

- src/Orleans.Serialization/Buffers/Adaptors/MemoryStreamBufferWriter.cs
This code existed for debugging purposes, but it's a no-op now.
> Remove unused code in `MemoryStreamBufferWriter`

- Directory.Build.props
The focus of these changes is to update the Event Hubs and Azure.Core package references. The currently referenced versions are roughly ~8 months old, during which time each has received a number of improvements.  The current generation of Azure SDKs has a strong commitment to avoid breaking changes; there should be no cascading changes needed.
- [Event Hubs Changelog](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/CHANGELOG.md)
- [Azure.Core Changelog](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/CHANGELOG.md)
> [Dependencies] Updating Event Hubs SDK

- src/TelemetryConsumers/Orleans.TelemetryConsumers.AI/AITelemetryConsumer.cs
- src/TelemetryConsumers/Orleans.TelemetryConsumers.AI/AITelemetryConsumerConfigurationExtensions.cs
- src/TelemetryConsumers/Orleans.TelemetryConsumers.AI/ApplicationInsightsTelemetryConsumerOptions.cs
This PR fixes a current gap in AITelemetryConsumer, which no longer picks up a TelemetryConfiguration that was registered via Dependency Injection. This means custom configurations through TelemetryInitializers, TelemetryProcessors, or TelemetrySinks will not be applied to Orleans metrics. Today, AITelemetryConsumer uses a configuration built by default by TelemetryConfiguration.Active, which is not recommended by the AppInsights team.
This behavior changed because as of 2.15.0-beta3 of Application Insights, a preconfigured TelemetryConfiguration through DI is no longer copied over to the TelemetryConfiguration.Active singleton, and it now requires a feature flag. It is unclear how long this feature flag will be supported in future versions of the AppInsights SDK …
> Add TelemetryConfiguration support for AITelemetryConsumer

- Directory.Build.props
The focus of these changes is to update the Azure Storage package references. The currently referenced versions are more than a year old, during which time each has received a number of improvements. The current generation of Azure SDKs has a strong commitment to avoid breaking changes; there should be no cascading changes needed.
- [Azure.Storage.Blobs Changelog](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md)
- [Azure.Storage.Queues Changelog](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Queues/CHANGELOG.md)
> [Dependencies] Updating Azure Storage Versions

- src/Orleans.Streaming/Common/PooledCache/PooledQueueCache.cs
> Fix: wrong parameter used when throwing QueueCacheMissException

- src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
- src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs
- src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/IStorageHashPicker.cs
- src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/IStorageSerializationPicker.cs
- src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/StorageHasherPicker.cs
- src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/StorageSerializationPicker.cs
- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorage.cs
- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
- src/Orleans.Core/CodeGeneration/IGrainState.cs
- src/Orleans.Core/Providers/IGrainStorage.cs
- src/Orleans.Core/Providers/IMemoryStorageGrain.cs
- src/Orleans.EventSourcing/LogStorage/LogStateWithMetaData.cs
- src/Orleans.EventSourcing/StateStorage/GrainStateWithMetaData.cs
- src/Orleans.Persistence.Memory/Storage/MemoryStorage.cs
- src/Orleans.Persistence.Memory/Storage/MemoryStorageGrain.cs
- src/Orleans.Persistence.Memory/Storage/MemoryStorageWithLatency.cs
- src/Orleans.TestingHost/TestStorageProviders/FaultInjectionStorageProvider.cs
- test/DefaultCluster.Tests/MemoryStorageProviderTests.cs
- test/Extensions/AWSUtils.Tests/StorageTests/DynamoDBStorageProviderTests.cs
- test/Extensions/AWSUtils.Tests/StorageTests/PersistenceGrainTests_AWSDynamoDBStore.cs
- test/Extensions/TesterAdoNet/StorageTests/Relational/AdotNetProviderFunctionalityTests.cs
- test/Extensions/TesterAdoNet/StorageTests/Relational/StreamingTestRelationalStoragePicker.cs
- test/Extensions/TesterAzureUtils/Persistence/PersistenceProviderTests.cs
- test/TestInfrastructure/TestExtensions/MockStorageProvider.cs
- test/TesterInternal/ErrorInjectionStorageProvider.cs
- test/TesterInternal/StorageTests/StorageProviders/BaseJSONStorageProvider.cs
Avoid `typeof` call where possible and will simplify some serialization calls
> Make IGrainState and IGrainStorage methods generic

- src/Orleans.Serialization/Invocation/Response.cs
`Response.ToString()` would throw since the logic in `GetValueOrDefault()` was wrong
> Fix `Response.ToString()`

- src/OrleansProviders/Streams/Common/PooledCache/PooledQueueCache.cs
> Fix: wrong parameter used when throwing QueueCacheMissException (#7295)

- src/Orleans.Core/Core/ClientBuilder.cs
- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/Hosting/GenericHostExtensions.cs
- src/Orleans.Runtime/Hosting/SiloBuilder.cs
- src/Orleans.TestingHost/TestClusterHostFactory.cs
The Minimal API host builder runs `ConfigureServices` delegates inline, whereas `HostBuilder` defers their execution until `Build()` is called. This difference causes an issue today and neither of the two options (passthru vs defer) will work in all cases:
1. If we pass-thru `ConfigureServices` calls in the `HostBuilder`, then the delegate passed to `UseOrleans(Action<HostBuilderContext, ISiloBuilder>)` will cause `HostBuilder` to throw when that delegate calls `ConfigureServices` itself (which is almost guaranteed to happen).
2. If we queue calls for later execution like we do today, then there is no opportunity for them to be invoked by the Minimal API builder, since there is no way to enqueue a delegate on it to be invoked when `Build` is called.
So the solution I've taken in this PR …
> [3.x] Support Minimal API host builder

- global.json
- src/Orleans.Core/CodeGeneration/GenericMethodInvoker.cs
- test/CodeGeneration/CodeGenerator.Tests/GenericMethodInvokerTests.cs
- add support for generic overloads with constraints on grain methods
- add tests 
Closes https://github.com/dotnet/orleans/issues/7309
> #7309 - add support for generic constraints on grain methods

- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Runtime/Catalog/IncomingRequestMonitor.cs
- src/Orleans.Runtime/Configuration/Options/SiloMessagingOptions.cs
Fixes #7330
Removes some log chattiness, increases the scan duration, and adds a doc comment on disabling the scan.
> Clarify comment on disabling workload analysis and log unknown status updates as debug

- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Serialization/BinaryFormatterISerializableSerializer.cs
- src/Orleans.Core/Serialization/BinaryFormatterSerializer.cs
- src/Orleans.Core/Serialization/IKeyedSerializer.cs
- src/Orleans.Core/Serialization/ILBasedExceptionSerializer.cs
- src/Orleans.Core/Serialization/ILBasedSerializer.cs
- src/Orleans.Core/Serialization/ILSerializerGenerator.cs
- src/Orleans.Core/Serialization/RemoteNonDeserializableException.cs
- src/Orleans.Core/Serialization/SerializationConstructorFactory.cs
- src/Orleans.Core/Serialization/SerializationManager.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- test/Benchmarks/Serialization/SerializationBenchmarks.cs
- test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs
- test/NonSilo.Tests/Serialization/ILBasedExceptionSerializerTests.cs
- test/NonSilo.Tests/Serialization/ILBasedSerializerTests.cs
Fixes #7328
We should not use ILBasedSerializer preferentially to the configured fallback serializer. This PR deprioritizes it.
> Support ILBasedSerializer as a fallback only after trying the configured fallback

- src/AWS/Orleans.Persistence.DynamoDB/Hosting/DynamoDBSiloBuilderExtensions.cs
- src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/SiloBuilderExtensions.cs
- src/Azure/Orleans.Persistence.AzureStorage/Hosting/AzureBlobSiloBuilderExtensions.cs
- src/Azure/Orleans.Persistence.AzureStorage/Hosting/AzureTableSiloBuilderExtensions.cs
- src/Orleans.Persistence.Memory/Hosting/MemoryGrainStorageSiloBuilderExtensions.cs
This can cause issues when:
* Using Autofac
* Registering storage providers with custom names
* Not registering a default provider (a provider with the name "Default")
The error which users will see can include an exception with the message: `A delegate registered to create instances of 'Orleans.Storage.IGrainStorage' returned null` and a stack trace containing `GrainVersionStore.OnStart`
> Do not register `IGrainStorage` in DI unless there is a provider named "Default"

- src/AdoNet/Orleans.Clustering.AdoNet/PostgreSQL-Clustering.sql
- src/AdoNet/Orleans.Reminders.AdoNet/PostgreSQL-Reminders.sql
Starting with Npgsql 6.0, date-time handling got more strict (https://www.npgsql.org/doc/types/datetime.html#timestamps-and-timezones). Using Npgsql 6.0 with Orleans broke some clustering queries, in particular when trying to mark previous versions of the same silo as dead when the previous version did not shutdown gracefully.
The issue is that when loading current cluster members, the DateTimes were loaded with type `unspecified`, because the table uses `datetime without time zone`. Then when reusing those date objects for update queries, Npgsql would not allow this anymore.
My solution is to follow the general advice for Postgres to always use `timestamp with time zone` (`timestamptz`) for storing date-times. By doing so, the membership DateTime gets loaded with type `utc`, and …
> Support Npgsql 6.0 for clustering and reminders

- src/Orleans.Core/CodeGeneration/GenericMethodInvoker.cs
- test/CodeGeneration/CodeGenerator.Tests/GenericMethodInvokerTests.cs
When the number of check constraints was greater than the number of type parameters, an index of of range exception was thrown. In fact, the nth generic constraint was matched against the nth type parameter, rather than the type parameter it applies to, so this would never work properly for multiple type parameters.
Note this bug was introduced in 3.5.1, and forced us to downgrade back to 3.5.0.
> Fix bug in validating generic constraints for method invocation

- src/AdoNet/Shared/Storage/AdoNetFormatProvider.cs
- src/Azure/Orleans.Hosting.AzureCloudServices/Hosting/ServiceRuntimeWrapper.cs
- src/Orleans.Analyzers/SyntaxHelpers.cs
- src/Orleans.CodeGenerator/SyntaxGeneration/FSharpUtils.cs
- src/Orleans.Core/Configuration/ConfigUtilities.cs
- src/Orleans.Serialization/Hosting/ReferencedAssemblyHelper.cs
- src/Orleans.Serialization/ISerializableSerializer/ExceptionCodec.cs
- src/Orleans.Serialization/TypeSystem/DefaultTypeFilter.cs
- src/Orleans.TestingHost/StandaloneSiloHandle.cs
- src/TelemetryConsumers/Orleans.TelemetryConsumers.Linux/LinuxEnvironmentStatistics.cs
`StartsWith` and `EndsWith` use the culture-culture to compare strings. It is slower and may lead to unexpected results.
I did not change methods that use `Ordinal` by default such as `Contains`. If you want, I can change them in this PR or in another PR.
> Use Ordinal comparisons instead of culture sensitive comparisons

- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubAdapterFactory.cs
- src/Orleans.Serialization/ISerializableSerializer/SerializationCallbacksFactory.cs
- src/Orleans.Serialization/TypeSystem/CachedTypeResolver.cs
- src/Orleans.Streaming/Internal/StreamDirectory.cs
- src/Orleans.Streaming/MemoryStreams/MemoryAdapterFactory.cs
Remove closures by using the `factoryArgument` parameter. This reduces allocations and is slightly faster.
> Remove closures when using ConcurrentDictionary

- src/Orleans.Core/Serialization/BinaryFormatterISerializableSerializer.cs
- src/Orleans.Core/Serialization/ILBasedSerializer.cs
- src/Orleans.Core/Serialization/SerializationManager.cs
- test/NonSilo.Tests/Serialization/ILBasedSerializerTests.cs
This allows a developer to configure `ILBasedSerializerOptions` or `BinaryFormatterISerializableSerializerOptions` and set their respective `IsFallbackOnly` properties to `false` to revert serializer behavior to pre-3.5.0.
The optimum solution if you are considering this is to add `[Serializable]` to your types and ensure that the code generator is generating code for your types, but this PR gives you an alternative route.
> Support configuring ILBasedSerializer and BinaryFormatterISerializableSerializer as pre-fallback serializers

- src/Orleans.Core/Networking/Shared/IOQueue.cs
> Porting IOQueue lock free implementation

- test/Grains/TestInternalGrains/PersistenceTestGrains.cs
- test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs
I see a test run for #7443 crashed with [this output](https://orleans.visualstudio.com/GitHub%20-%20PR%20Builds/_build/results?buildId=48989&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=64c999b4-06f1-59fa-9b80-6eac5fccdd35):
```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. 
System.InvalidOperationException: There is no currently active test.
+ CategoryInfo          : NotSpecified: (The active test...ly active test.:String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
+ PSComputerName        : localhost
at Xunit.Sdk.TestOutputHelper.GuardInitialized() in C:\Dev\xunit\xunit\src\xunit.execution\Sd
k\Frameworks\TestOutputHelper.cs:line 51
at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in …
```
> Fix some test code crashes caused by logging from unawaited background tasks

- src/AdoNet/Shared/Storage/DbExtensions.cs
- src/AdoNet/Shared/Storage/DbStoredQueries.cs
Context:
In my project, we are using Npgsql, NodaTime and Npgsql.NodaTime. As a result of this combination, the postgres date/time types (such as those used in the AdoNet membership table) get mapped to NodaTime types instead of BCL types by default, unless you explicitly request the column as DateTime via `IDataRecord.GetDateTime(...)` or similar. 
Without the changes here, I am getting an invalid cast exception at runtime because the Instant type returned by Npgsql is being cast to DateTime by the Orleans AdoNet code.
> AdoNet - be more explicit when extracting DateTime from IDataRecord

- src/AdoNet/Shared/Storage/DbExtensions.cs
- src/AdoNet/Shared/Storage/DbStoredQueries.cs
> [3.x] Backport #6968: AdoNet - be more explicit when extracting DateTime from IDataRecord

- src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDBReminderTable.cs
- src/AWS/Shared/Storage/DynamoDBStorage.cs
Fixes https://github.com/dotnet/orleans/issues/7434
> DynamoDB Reminders load using GSI

- src/AdoNet/Orleans.Clustering.AdoNet/Migrations/PostgreSQL-Clustering-3.6.0.sql
- src/AdoNet/Orleans.Persistence.AdoNet/Migrations/PostgreSQL-Persistence-3.6.0.sql
- src/AdoNet/Orleans.Reminders.AdoNet/Migrations/PostgreSQL-Reminders-3.6.0.sql
* Create PostgreSQL migrations for version 3.6.0
The changes in https://github.com/dotnet/orleans/pull/7402 are fine for new deployments, but existing deployments need a way to migrate tables and routines in order to apply the same changes.
Users can run the SQL in the 3 migration files when upgrading to 3.6.0
> [Backport] Create PostgreSQL migrations for version 3.6.0 (#7490)

- src/Azure/Orleans.Streaming.AzureStorage/Storage/AzureQueueDataManager.cs
Addresses unhandled intermittent 404 failure in DeleteQueueMessage as described in https://github.com/dotnet/orleans/issues/7461#issue-1093743910.
> Add a catch block in Azure DeleteQueueMessage for 404 error (#7461)

- src/Orleans.Serialization/ISerializableSerializer/ExceptionCodec.cs
- test/Orleans.Serialization.UnitTests/PolymorphismTests.cs
We added an API in .NET 6.0 which allows us to set the RemoteStackTrace on Exception objects (see https://github.com/dotnet/runtime/pull/50392). This PR makes use of that where supported.
> Use ExceptionDispatchInfo.SetRemoteStackTrace API in .NET 6.0 builds

- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubCheckpointer.cs
It seems that #6960 was overridden by mistake when merging #7363
> Ignore value loaded in EventHubCheckpointer if it's obviously corrupted

- src/Orleans.Serialization/ISerializableSerializer/ExceptionCodec.cs
#7513 was not as defensive as it should have been and there were some test failures as a result. I believe this was not caught because our build definitions were not updated to run .NET 6.0 tests yet.
> Fix serialization of exceptions with a null stack trace

- src/Orleans.CodeGenerator.MSBuild/Orleans.CodeGenerator.MSBuild.csproj
- src/Orleans.CodeGenerator/Orleans.CodeGenerator.csproj
- src/Orleans.Sdk/Orleans.Sdk.csproj
- src/Orleans.Serialization.FSharp/Orleans.Serialization.FSharp.csproj
- src/Orleans.Serialization.NewtonsoftJson/Orleans.Serialization.NewtonsoftJson.csproj
- src/Orleans.Serialization.TestKit/Orleans.Serialization.TestKit.csproj
- src/Orleans.Serialization/Orleans.Serialization.csproj
Some packages do not yet have the `Microsoft.` prefix
> Add the Microsoft prefix for newly added packages

- src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/StorageSerializationPicker.cs
- test/Extensions/TesterAdoNet/StorageTests/Relational/StreamingTestRelationalStoragePicker.cs
Fix parameter misspelling from `servideId` -> `serviceId`.
> Fix parameter misspelling from `servideId` -> `serviceId`

- samples/Chirper/Chirper.Client/ShellHostedService.cs
`fuchisa` -> `fuchsia` and added an `[/]` to close the Spectre.Console tag.
> Fix Spectre.Console format and color spelling.

- src/Orleans.Serialization/Codecs/WellKnownStringComparerCodec.cs
- test/Orleans.Serialization.UnitTests/BuiltInCodecTests.cs
We added method in .NET 6.0 to read the properties of well-known string comparers (see https://github.com/dotnet/runtime/pull/50312). This PR makes use of those where available to enhance how string comparers are serialized.
> Improve StringComparer serialization for well-known comparers

- src/Orleans.Core.Abstractions/Providers/ProviderConstants.cs
- src/Orleans.Streaming.Abstractions/StreamId.cs
- src/Orleans.Streaming/Hosting/SiloBuilderStreamingExtensions.cs
- src/Orleans.Streaming/InternalStreamId.cs
- src/Orleans.Streaming/PubSub/PubSubRendezvousGrain.cs
- src/Orleans.Streaming/SiloPersistentStreamConfigurator.cs
- test/Tester/StreamingTests/MemoryProgrammaticSubcribeTests.cs
- test/TesterInternal/StreamingTests/PubSubRendezvousGrainTests.cs
Issue #7474
Instead of relying on the state of `Grain<T>`, we can pass in the constructor of `PubSubRendezvousGrain` a storage factory or locator, that will try to return, in this order, a storage provider named:
- Like the stream provider (if the stream provider configured is "MyStreamingProvider" it will try to find a storage provider named "MyStreamingProvider"
- Otherwise it will fallback to the default "PubSubStore".
Initial storage read will be done during `OnActivateAsync`.
The solution isn't ideal since we rely on parsing the key of  `PubSubRendezvousGrain` to extract the provider name, but the benefit of this solution is that it can be easily backported in 3.x if needed.
In the future we could change the key of `PubSubRendezvousGrain` so user could inject their own logic to …
> Streaming: make PubSubStore configurable per provider

- src/Orleans.Core.Abstractions/Core/IGrainFactory.cs
- src/Orleans.Core/Core/ClusterClient.cs
- src/Orleans.Core/Core/GrainFactory.cs
- src/Orleans.Runtime/Core/InternalClusterClient.cs
- test/DefaultCluster.Tests/CodeGenTests/GeneratorGrainTest.cs
- test/DefaultCluster.Tests/HostedClientTests.cs
- test/DefaultCluster.Tests/ObserverTests.cs
- test/DefaultCluster.Tests/OneWayCallTests.cs
- test/TesterInternal/MembershipTests/ClientIdPartitionDataRebuildTests.cs
Related issue #7528
Make `IGrainFactory.CreateObjectReference` and `IGrainFactory.DeleteObjectReference` synchronous
> Make `IGrainFactory.CreateObjectReference` and `IGrainFactory.DeleteObjectReference` synchronous

- src/Orleans.Core/Configuration/Options/ClusterMembershipOptions.cs
- test/NonSilo.Tests/Membership/ClusterHealthMonitorTests.cs
This changes the defaults to enable two cluster membership stability improvements which were inspired by the lifeguard paper.
For more information, see #6745 and #6800.
> Enable lifeguard improvements by default

- src/Orleans.Analyzers/GenerateSerializationAttributesAnalyzer.cs
- src/Orleans.Analyzers/SerializationAttributesHelper.cs
- src/Orleans.Analyzers/SyntaxHelpers.cs
- src/Orleans.CodeGenerator/SyntaxGeneration/SyntaxFactoryUtility.cs
- test/DefaultCluster.Tests/GenericGrainTests.cs
- test/Grains/TestGrains/GenericGrains.cs
- test/Grains/TestGrains/TestGrains.csproj
Fixes #7039
Adds support for grains with the new constraints, `unmanaged` and `notnull`
Example:
``` C#
public interface IUnmanagedArgGrain<T> : IGrainWithGuidKey where T : unmanaged
{
ValueTask<T> Echo(T value);
ValueTask<U> EchoNonNullable<U>(U value) where U : notnull;
ValueTask<U> EchoReference<U>(U value) where U : class;
ValueTask<U> EchoValue<U>(U value) where U : struct;
}
```
> Support unmanaged and notnull constraints for grain interfaces

- src/Orleans.Core/Hosting/GenericHostExtensions.cs
- src/Orleans.Runtime/Hosting/GenericHostExtensions.cs
- src/Orleans.TestingHost/TestClusterHostFactory.cs
- test/Benchmarks/Ping/PingBenchmark.cs
- test/DefaultCluster.Tests/HostedClientTests.cs
- test/DistributedTests/DistributedTests.Client/Commands/CounterCaptureCommand.cs
- test/DistributedTests/DistributedTests.Client/LoadGeneratorScenario/LoadGeneratorScenarioRunner.cs
- test/DistributedTests/DistributedTests.Server/ServerRunner.cs
- test/Extensions/TesterAdoNet/LivenessTests.cs
- test/Extensions/TesterAdoNet/Persistence/PersistenceGrainTests_AdoNetSql.cs
- test/Extensions/TesterAdoNet/Reminders/ReminderTests_AdoNet_SqlServer.cs
- test/Grains/TestVersionGrains/VersionGrainsSiloBuilderConfigurator.cs
- test/NonSilo.Tests/ClientBuilderTests.cs
- test/NonSilo.Tests/Directory/GrainDirectoryResolverTests.cs
- test/NonSilo.Tests/Serialization/OrleansJsonSerializerTests.cs
- test/NonSilo.Tests/SiloBuilderTests.cs
- test/Orleans.Connections.Security.Tests/TlsConnectionTests.cs
- test/TestInfrastructure/TestExtensions/SerializationTestEnvironment.cs
- test/Tester/ClientConnectionTests/ClusterClientTests.cs
- test/Tester/ClientConnectionTests/GatewayConnectionTests.cs
- test/Tester/LocalhostSiloTests.cs
- test/TesterInternal/ActivationsLifeCycleTests/ActivationCollectorTests.cs
We should be providing access to `HostBuilderContext` in the extension methods which hang off `IHostBuilder`
These are the APIs which change:
``` diff
- IHostBuilder.UseOrleans(Action<ISiloBuilder>)
+ IHostBuilder.UseOrleans(Action<HostBuilderContext, ISiloBuilder>)
```
``` diff
- IHostBuilder.UseOrleansClient(Action<IClientBuilder>)
+ IHostBuilder.UseOrleansClient(Action<HostBuilderContext, IClientBuilder>)
```
> Plumb HostBuilderContext into IHostBuilder extension methods

- .azure/pipelines/pr.yaml
Currently we use the "classic" azure pipelines, that call the `build.ps1` and the `tests.ps1` scripts.
Switching to the yaml format will be easier to maintain, and allow us to run tests that target different framework in parallel.
> Initial yaml pipeline for PR build/tests

- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- test/Tester/GrainLevelCallFilterTests.cs
> Fix grain level call filter not invoked without global filters

- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- test/TesterInternal/ErrorInjectionStorageProvider.cs
- test/TesterInternal/StorageTests/PersistenceGrainTests.cs
- test/TesterInternal/StreamingTests/StreamPubSubReliabilityTests.cs
... and forward them instead.
The current behavior is to deactivate a grain when an `InconsistentStateException` is allowed to propagate from a request.
When this occurs, we're setting a `DeactivationException`, which is then propagated to all pending calls until the grain completes deactivation.
This PR changes that by not setting the exception, and therefore fixes the flaky `Persistence_Provider_InconsistentStateException_DeactivatesOnlyCurrentGrain` & `Persistence_Provider_InconsistentStateException_DeactivatesGrain` tests.
As a drive-by, it also removes some synchronous blocking from test code.
> Avoid rejecting pending messages when an InconsistentStateException occurs

- src/Orleans.Runtime/Catalog/ActivationData.cs
- test/TesterInternal/MessageScheduling/ReentrancyTests.cs
If the user-defined `MayInterleave` predicate throws, the grain will be sent into a loop of bad behavior, instead of rejecting the message which resulted in that fault back to the caller.
> Protect grain against failures in MayInterleave predicate

- test/Benchmarks/Ping/PingBenchmark.cs
Since we now validate ClusterId on connection, the PingBenchmark is failing as the client sets a different ClusterId from the silos.
> Fix cluster configuration in PingBenchmark

- src/Orleans.CodeGeneration/RoslynCodeGenerator.cs
Fix this issue : https://github.com/dotnet/orleans/issues/7645
> Check [KnownBaseType] by Type.FullName rather than reference

- src/Orleans.CodeGenerator/Analysis/CompilationAnalyzer.cs
Fixes #7642
Ignores `[KnownAssembly]` in the event that the assembly of the `Type` argument is `null`, indicating that it's referring to the containing assembly and is hence self-referential.
> Ignore KnownAssembly attribute which points to the containing assembly

- src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDBReminderTable.cs
- src/AWS/Shared/Storage/DynamoDBStorage.cs
Fixes: https://github.com/dotnet/orleans/issues/7657
The `scan` operation is inefficient especially as the table size increases. This is because the `scan` operation reads the entire table (therefore consumes RCUs for all the data in the table) and filters out rows based on the expression.
On the other hand, the `query` operation is very efficient as it pulls out only the specific records that match the HashKey and the SortKey without wasting any RCUs.
> Orleans.Reminders.DynamoDB use the Query operation for ReadRows

- src/Orleans.Runtime/Networking/SiloConnection.cs
There is a call to `TryDeliverToProxy` in `SiloConnection` which is superfluous since `messageCenter.ReceiveMessage` makes the same call.
> Simplify SiloConnection

- Directory.Build.props
- src/Directory.Build.props
- src/Directory.Build.targets
I suppose it's not common to mirror a repository into another repository and build official packages from there, so this is the price we pay.
This trickery was nabbed from the dotnet/arcade repo here: https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L43-L82
As suggested by @tmat here: https://github.com/dotnet/sourcelink/issues/820
> Fix Source Link build for CI

- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
Currently, users are presented with a `Grain directory is stopping` exception when a shutdown is occurring and there are no directories to forward a request to. In the single silo case, this is benign and in the multiple-silo case, this will not occur (since another silo will have been chosen instead)
I believe it's safe for us to just accept those requests since they can only occur if this is the last silo in the cluster and therefore the world is ending anyway (we're shutting down).
> Allow `LocalGrainDirectory` calls while shutting down

- src/Orleans.CodeGenerator/InvokableGenerator.cs
- src/Orleans.CodeGenerator/SyntaxGeneration/SymbolExtensions.cs
- src/Orleans.Core.Abstractions/Runtime/GrainReference.cs
- src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs
- src/Orleans.Core/Runtime/OutgoingCallInvoker.cs
- src/Orleans.Serialization/Invocation/IInvokable.cs
- test/Orleans.Serialization.UnitTests/Request.cs
- test/Tester/ActivityPropagationTests.cs
Fixes #4992
Contributes to #7480
We have support for Open Telemetry already, via `System.Diagnostics.Activity` support (from #6853 and #7443).
This PR enhances that support to include more details and hopefully conform more to the Open Telemetry guidelines surrounding span names and tags for RPC.
One thing which is missing is `net.peer.name`/`.ip`/`.port`. That should be set to the address of the remote endpoint. That information isn't known at the time that the integration executes and the `Activity` isn't in context when the remote peer is resolved or the message is transported to the remote endpoint. I think it's fine to omit this information, despite what the spec says: the remote service will emit a matching trace (with the trace parent set), and if there's a failure, it will be made …
> Enhance distributed tracing support

- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBGatewayListProvider.cs
- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBMembershipTable.cs
- src/AWS/Orleans.Clustering.DynamoDB/Options/DynamoDBClusteringOptions.cs
- src/AWS/Orleans.Clustering.DynamoDB/Options/DynamoDBGatewayOptions.cs
- src/AWS/Orleans.Persistence.DynamoDB/Options/DynamoDBStorageOptions.cs
- src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
- src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDBReminderTable.cs
- src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDbReminderStorageOptions.cs
- src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDbReminderStorageOptionsExtensions.cs
- src/AWS/Shared/Storage/DynamoDBStorage.cs
Issues:
- #7682
- #7683
- #7684
Fixes / Improvements in this PR:
- Ability to disable automatic table create or update via the configuration properties `CreateIfNotExists` and `UpdateIfExists` respectively. This is important as in a production environment the infrastructure is provisioned and maintained via other solutions (e.g.: CloudFormation, Terraform etc). Not having this ability means that when a grain starts, it will observe that the DynamoDB capacity has changed and update it back to what the Orleans configuration dictates. This change is **essential** for a production environment (required after the Orleans library also gained the ability to update existing tables via the `UpdateTableAsync` method).
- Added a missing configuration parameter `UseProvisionedThroughput` to the …
> DynamoDB optional table create / update and update corner cases

- src/Orleans.CodeGenerator.MSBuild/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets
We noticed an issue with our local dev incremental builds where after a file was changed in a project using the msbuild code generator targets it would always run the code generator, even when no files have changed build-to-build. I investigated and tracked this down to the code generator not updating the timestamp of the output file when it runs. I propose the following solution: when the code generator is executed we touch the output file afterward to ensure its timestamp is updated, and thus the output timestamp will always end up being newer than the input args file.
> 3.x - Ensure timestamp is updated on codegen output for incremental builds

- Directory.Build.props
Consul version 0.7.2.3 has vulnerable dependencies and this would fix them
> Updating ConsulVersion for 3.x to match main

- src/Orleans.Core.Abstractions/Core/GrainExtensions.cs
Fix for #7702
It is possible that someone made behavior based on this exception.
> Remove exception from IsPrimaryKeyBasedOnLong when key is not integer

- src/Orleans.Core/Configuration/Options/ClusterMembershipOptions.cs
- src/Orleans.Runtime/MembershipService/MembershipAgent.cs
- src/Orleans.Runtime/MembershipService/MembershipTableEntryExtensions.cs
This PR removes `ValidateInitialConnectivity` 
This setting allowed to skip the initial connectivity when a silo tries to join a cluster but introduces a lot of issues just after.
> What may be happening is this: 
> - Old silo A was killed ungracefully, so in the membership table it's still `Active`. 
> - Silo B tries to join the cluster, but with `ValidateInitialConnectivity` set to false, it doesn't try to ping A before joining.
> - Silo B tries to activate some grain. It chooses to place it on silo A, since it's still alive in the membership table
> - These requests fail (timeout) or just wait, until B decide to vote silo A dead (by default it can take few mins)
> - Once this vote occurred, pending request will throw `SiloUnavailableException`
It can cause issues with the distributed …
> Remove ValidateInitialConnectivity

- src/Orleans.Clustering.ZooKeeper/ZooKeeperBasedMembershipTable.cs
- test/Extensions/TesterZooKeeperUtils/LivenessTests.cs
- test/Extensions/TesterZooKeeperUtils/ZookeeperMembershipTableTests.cs
- test/Extensions/TesterZooKeeperUtils/ZookeeperTestUtils.cs
ZooKeeper tests were broken due to the cluster options not being passed to `ZooKeeperGatewayListProvider`
> Fix ZooKeeper tests

- test/Extensions/Consul.Tests/ConsulMembershipTableTest.cs
- test/Extensions/Consul.Tests/ConsulTestUtils.cs
- test/Extensions/Consul.Tests/LivenessTests.cs
Use `TestDefaultConfiguration` for Consul tests so that the connection string can be configured via command line or environment variables
> Unify configuration for Consul tests

- test/Extensions/Consul.Tests/ConsulTestUtils.cs
Skip Consul tests when a connection string has not been specified
> Skip Consul tests when a connection string has not been specified

- src/Orleans.Runtime/ConsistentRing/VirtualBucketsRingProvider.cs
- changed log level from info to trace for lowest level logging cases
- changed log level from info to debug for minimal viable startup feedback
- made trace and debug logging conditional to avoid string formatting overhead
> Reduce logging noise on VirtualBucketsRingProvider

- test/Extensions/TesterAzureUtils/AzureGrainDirectoryTests.cs
- test/Extensions/TesterAzureUtils/AzureTableDataManagerTests.cs
The following issues are affecting these tests:
* https://github.com/Azure/Azurite/issues/1465 (fixed)
* https://github.com/Azure/Azurite/issues/1493
Once a new container image is released which fixes these issues, we can remove the code added by this PR and similar calls to skip tests when the Azure storage emulator is in use
> Skip some `AzureGrainDirectory` and `AzureTableDataManager` tests in emulator

- src/Orleans.Serialization.Abstractions/Annotations.cs
This helps prevent  CS0579 errors triggering in use cases where code generation is needed across multiple assemblies.
> Allow multiple GenerateCodeForDeclaringAssemblyAttributes per assembly

- build.ps1
Currently, locally built packages are not having their versions suffixed with the date, which is frustrating for local dev.
> Fix build.ps1 not suffixing local package builds with date

- .github/workflows/ci.yml
Azure Storage tests are disabled for now since they were proving flaky on the hosted runners and there are some Azurite-related issues (see https://github.com/dotnet/orleans/pull/7729).
> Enable test suites for most dependencies in GitHub Actions

- src/Orleans.TestingHost/TestCluster.cs
- src/Orleans.TestingHost/TestClusterBuilder.cs
- src/Orleans.TestingHost/TestClusterOptions.cs
- src/Orleans.TestingHost/UnixSocketTransport/UnixSocketConnectionExtensions.cs
- src/Orleans.TestingHost/UnixSocketTransport/UnixSocketConnectionFactory.cs
- src/Orleans.TestingHost/UnixSocketTransport/UnixSocketConnectionListener.cs
- src/Orleans.TestingHost/UnixSocketTransport/UnixSocketConnectionListenerFactory.cs
- src/Orleans.TestingHost/UnixSocketTransport/UnixSocketConnectionOptions.cs
- test/Tester/ClientConnectionTests/ClusterClientTests.cs
- test/Tester/ClientConnectionTests/GatewayConnectionTests.cs
- test/Tester/ClientConnectionTests/InvalidPreambleConnectionTests.cs
- test/Tester/ClientConnectionTests/StallConnectionTests.cs
- test/Tester/TransportTests/TransportTestsBase.cs
- test/Tester/TransportTests/UnixSocketTransportTests.cs
- test/TesterInternal/GeoClusterTests/BasicLogTestGrainTests.cs
Can be useful to test with multiple out of process silos.
I was able to reuse `SocketConnection` but not `SocketConnectionListener` since it has some logic relying on the endpoint beeing an `IPEndPoint`. Since this Unix socket support is limited to the testing host, I didn't want to modify `SocketConnectionListener`.
> Add Unix socket support to TestingHost

- src/Orleans.Core/Lifecycle/LifecycleSubject.cs
- src/Orleans.Core/Messaging/GatewayManager.cs
- src/Orleans.Core/Networking/ConnectionManager.cs
- src/Orleans.Core/Networking/NetworkingTrace.cs
- src/Orleans.Core/Scheduler/TaskSchedulerAgent.cs
- src/Orleans.Core/Statistics/LogStatistics.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/Core/HostedClient.cs
- src/Orleans.Runtime/Counters/CountersStatistics.cs
- src/Orleans.Runtime/Hosting/SiloHostedService.cs
- src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs
- src/Orleans.Runtime/MembershipService/MembershipAgent.cs
- src/Orleans.Runtime/MembershipService/MembershipGossiper.cs
- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
- src/Orleans.Runtime/Silo/Silo.cs
- test/Tester/Lifecycle/LifecycleTests.cs
- Focused on silo shutdown code path and reducing verbosity of LogLevel.Information
- Changed many LogLevels from Information to Debug
- Added IsEnabled conditional around modified code blocks to mitigate string build overhead
- Cleaned up a small number of logging related ctors, fields and logging context/type strings
[Shutdown log before](https://gist.github.com/MarkNickeson/33b1472a923c193fb935ab6a2f462c67)
[Shutdown log after](https://gist.github.com/MarkNickeson/24e9fd759503be7a19fc858d84b732b6)
> Fix papercuts issue #7099 - silo spew on shutdown

- test/NonSilo.Tests/Membership/ClusterHealthMonitorTests.cs
> Account for non-determinism in ClusterHealthMonitor_NoIndirectProbes

- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/MetadataGenerator.cs
- src/Orleans.CodeGenerator/SyntaxGeneration/Identifier.cs
> Code Generator: sanitize assembly name when generating target namespace

- src/Orleans.Core/Runtime/OutgoingCallInvoker.cs
- src/Orleans.Runtime/Core/GrainMethodInvoker.cs
- test/Grains/TestGrainInterfaces/IMethodInterceptionGrain.cs
- test/Grains/TestGrains/MethodInterceptionGrain.cs
- test/Tester/GrainCallFilterTests.cs
When a call fitler does not properly call the `Invoke` method on the
provided context object, a `NullReferenceException` is thrown. While
correct, this behavior is not the most intuitive and doesn't point users
to the underlying issue well.
This PR changes the behavior to throw an `InvalidOperationException` with
a helpful error message including the name of the call filter which is
buggy. Added some unit tests to verify the functionality works.
Should address #7610
> Fix Null Reference exception in call filters

- src/Orleans.Core/Messaging/PrefixingBufferWriter.cs
- src/Orleans.Serialization/Buffers/Adaptors/BufferSegment.cs
- src/Orleans.Serialization/Buffers/Adaptors/BufferWriterBox.cs
- src/Orleans.Serialization/Buffers/Adaptors/MemoryBufferWriter.cs
- src/Orleans.Serialization/Buffers/Adaptors/PooledArrayBufferWriter.cs
- src/Orleans.Serialization/Buffers/Adaptors/PooledBufferStream.cs
- src/Orleans.Serialization/Buffers/Reader.cs
- src/Orleans.Serialization/Buffers/Writer.cs
- src/Orleans.Serialization/Utilities/VarIntReaderExtensions.cs
- src/Orleans.Serialization/Utilities/VarIntWriterExtensions.cs
* Fix a bug in PrefixingBufferWriter when requesting a span with a `sizeHint` of `0` when the current buffer is full. The [doc comments](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.ibufferwriter-1.getspan?view=net-6.0#parameters) say it should always return a non-empty buffer.
* Add methods to rent & return a pooled `ReadOnlySequence<byte>` from `PooledArrayBufferWriter` to allow writing without allocation.
* Add `Reader.ReadBytes` overload which accepts an `IBufferWriter<byte>` to support copying from a reader to a writer
* Allocate an unspecified number of bytes in `Writer.WriteMultiSegment` to prevent it from requesting potentially arbitrarily large buffers (which might not be able to be satisfied).
* Add `PooledBufferStream` which implements `Stream` on top of pooled …
> Performance and behavior improvements for serializations buffers

- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Serialization/Configuration/TypeManifestOptions.cs
- src/Orleans.Serialization/Hosting/ServiceCollectionExtensions.cs
- src/Orleans.Serialization/TypeSystem/CachedTypeResolver.cs
- src/Orleans.Serialization/TypeSystem/DefaultTypeFilter.cs
- src/Orleans.Serialization/TypeSystem/ITypeConverter.cs
- src/Orleans.Serialization/TypeSystem/RuntimeTypeNameRewriter.cs
- src/Orleans.Serialization/TypeSystem/TypeCodec.cs
- src/Orleans.Serialization/TypeSystem/TypeConverter.cs
Adds functionality to inspect types using `Type` instead of only `string` names for assembly/type.
This is useful because it allows general-purpose serializers (JSON, etc) to opt-in to allowing types based on what they support.
Also adds an `AllowAllTypes` option, defaulting (for now) to `false`.
I'm not against defaulting that to `true`, since it can make people's lives easier.
> Add ITypeFilter interface for opting-in/out of allowing CLR types

- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/LibraryTypes.cs
- src/Orleans.CodeGenerator/MetadataGenerator.cs
- src/Orleans.CodeGenerator/Model/MetadataModel.cs
- src/Orleans.Serialization.Abstractions/Annotations.cs
- src/Orleans.Serialization.TestKit/ValueTypeFieldCodecTester.cs
- src/Orleans.Serialization/Cloning/IDeepCopier.cs
- src/Orleans.Serialization/Codecs/IFieldCodec.cs
- src/Orleans.Serialization/Codecs/IntegerCodec.cs
- src/Orleans.Serialization/Codecs/ReferenceTypeSurrogateCodec.cs
- src/Orleans.Serialization/Configuration/TypeManifestOptions.cs
- src/Orleans.Serialization/Serializer.cs
- src/Orleans.Serialization/Serializers/CodecProvider.cs
- src/Orleans.Serialization/Serializers/IGeneralizedCodec.cs
- src/Orleans.Serialization/Serializers/SurrogateCodec.cs
- src/Orleans.Serialization/Serializers/ValueTypeSurrogateCodec.cs
- src/Orleans.Serialization/TypeSystem/TypeConverter.cs
- test/Benchmarks/Serialization/Comparison/ClassSerializeBenchmark.cs
- test/Orleans.Serialization.UnitTests/ConverterTests.cs
- test/Orleans.Serialization.UnitTests/Models.cs
Fixes #7635
Fixes #7593
Adds support for serialization surrogates and converters.
There are two interfaces introduced and one attribute:
``` C#
/// <summary>
/// When applied to a type, indicates that the type is a converter and that it should be automatically registered.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
public sealed class RegisterConverterAttribute : Attribute
{
}
/// <summary>
/// Functionality for converting between two types.
/// </summary>
public interface IConverter<TValue, TSurrogate> where TSurrogate : struct
{
/// <summary>
/// Converts a surrogate value to the value type.
/// </summary>
/// <param name="surrogate">The surrogate.</param>
/// <returns>The value.</returns>
TValue ConvertFromSurrogate(in TSurrogate surrogate);
/// …
```
> Add support for serialization converters/surrogates

- .azure/pipelines/pr.yaml
- .github/workflows/ci.yml
- src/Directory.Build.props
- test/Directory.Build.props
- test/Grains/TestFSharp/TestFSharp.fsproj
- test/Grains/TestFSharpGrainInterfaces/TestFSharpGrainInterfaces.csproj
- test/Grains/TestGrainInterfaces/TestGrainInterfaces.csproj
- test/Grains/TestGrains/ConsumerEventCountingGrain.cs
- test/Grains/TestGrains/ProducerEventCountingGrain.cs
- test/Grains/TestGrains/TestGrains.csproj
- test/Grains/TestInternalGrainInterfaces/TestInternalGrainInterfaces.csproj
- test/Grains/TestInternalGrains/TestInternalGrains.csproj
- test/Misc/TestInternalDtosRefOrleans/TestInternalDtosRefOrleans.csproj
- test/Tester/HeterogeneousSilosTests/UpgradeTests/UpgradeTestsBase.cs
net5.0 has already reached EOL, and 3.1 should reach EOL shortly after 4.0 release, it doesn't make sense to keep them for our main branch.
> Remove netcoreapp3.1 and net5.0 support in main

- Orleans.sln
- src/Orleans.BroadcastChannel/BroadcastChannel.cs
- src/Orleans.BroadcastChannel/BroadcastChannelConsumerExtension.cs
- src/Orleans.BroadcastChannel/BroadcastChannelOptions.cs
- src/Orleans.BroadcastChannel/BroadcastChannelProvider.cs
- src/Orleans.BroadcastChannel/BroadcastChannelSubscription.cs
- src/Orleans.BroadcastChannel/BroadcastChannelWriter.cs
- src/Orleans.BroadcastChannel/ChannelId.cs
- src/Orleans.BroadcastChannel/Hosting/ChannelHostingExtensions.cs
- src/Orleans.BroadcastChannel/IdMapping/DefaultChannelIdMapper.cs
- src/Orleans.BroadcastChannel/IdMapping/IChannelIdMapper.cs
- src/Orleans.BroadcastChannel/Orleans.BroadcastChannel.csproj
- src/Orleans.BroadcastChannel/SubscriberTable/ImplicitChannelSubscriberTable.cs
- src/Orleans.BroadcastChannel/SubscriberTable/Predicates/AllStreamNamespacesPredicate.cs
- src/Orleans.BroadcastChannel/SubscriberTable/Predicates/DefaultStreamNamespacePredicateProvider.cs
- src/Orleans.BroadcastChannel/SubscriberTable/Predicates/ExactMatchStreamNamespacePredicate.cs
- src/Orleans.BroadcastChannel/SubscriberTable/Predicates/IChannelNamespacePredicate.cs
- src/Orleans.BroadcastChannel/SubscriberTable/Predicates/ImplicitChannelSubscriptionAttribute.cs
- src/Orleans.BroadcastChannel/SubscriberTable/Predicates/RegexChannelNamespacePredicate.cs
- src/Orleans.Core.Abstractions/Manifest/GrainProperties.cs
- src/Orleans.Core/Properties/AssemblyInfo.cs
- src/Orleans.Streaming/GrainStreamingExtensions.cs
- src/Orleans.Streaming/SimpleMessageStream/SimpleMessageStreamProvider.cs
- test/Grains/TestGrains/SimpleStreams/SimpleSubscriberGrain.cs
- test/Grains/TestGrains/StreamInterceptionGrain.cs
- test/Grains/TestGrains/TestGrains.csproj
- test/Tester/GrainCallFilterTests.cs
- test/Tester/StreamingTests/BroadcastChannels/BroadcastChannelTests.cs
- test/Tester/StreamingTests/SampleStreamingTests.cs
- test/Tester/Tester.csproj
This PR introduces "Broadcast channels" that will be removed in 4.x (#7475)
The interface for consuming and publishing is more streamlined, but it should behave just like SMS
For now, only implicit subscriptions are supported, but we could add explicit later on.
> Broadcast channel to replace SMS

- src/Orleans.Core/Runtime/CallbackData.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Core/Runtime/SharedCallbackData.cs
- src/Orleans.Core/Timers/CoarseStopwatch.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
`ValueStopwatch` is a struct-based `Stopwatch` alternative, using the same underlying APIs (high-precision timer).
`CoarseStopwatch` is also a struct-based Stopwatch alternative, but it uses `Environment.TickCount64` instead of high-precision APIs.
`Environment.TickCount64` is much cheaper than the method `Stopwatch`/`ValueStopwatch` use:
```
|                 Method |      Mean |     Error |    StdDev |
|----------------------- |----------:|----------:|----------:|
|  StopwatchGetTimestamp | 19.814 ns | 0.0535 ns | 0.0474 ns |
|    DateTimeUtcNowTicks | 28.477 ns | 0.1351 ns | 0.1197 ns |
| EnvironmentTickCount64 |  1.669 ns | 0.0106 ns | 0.0094 ns |
```
Where the imprecision is tolerable (typically anything measuring times over about a second), `CoarseStopwatch` can be substantially …
> Use CoarseStopwatch in CallbackData

- src/Orleans.Core/Messaging/CachingIdSpanCodec.cs
- src/Orleans.Core/Messaging/CachingSiloAddressCodec.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
Follow-up to #7816, extending the same optimization to `IdSpan` for the two abovementioned types which are backed by `IdSpan`
I verified that there are no changes to `CachingSiloAddressCodec`, it's just a move into a separate file for organization.
> Messaging: cache encoded `GrainType` and `GrainInterfaceType`

- src/Orleans.Core.Abstractions/IDs/ActivationId.cs
- src/Orleans.Core.Abstractions/IDs/GrainId.cs
- src/Orleans.Core.Abstractions/IDs/SiloAddress.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
- src/Orleans.Core/Utils/Utils.cs
- src/Orleans.Runtime/GrainDirectory/GrainDirectoryResolver.cs
- src/Orleans.Runtime/GrainDirectory/GrainLocatorResolver.cs
- src/Orleans.Runtime/Messaging/Gateway.cs
- src/Orleans.Runtime/Placement/PlacementStrategyResolver.cs
* Reduce transcoding of UTF16 to UTF8 by writing UTF8 directly using `WriteStringValue`.
* Reduce allocations when preparing and parsing serialized values.
> Reduce transcoding and allocations for JSON serializer

- src/Orleans.Core.Abstractions/IDs/GrainAddress.cs
- src/Orleans.Core/Messaging/Message.cs
- src/Orleans.Core/Messaging/MessageFactory.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
- src/Orleans.Core/Networking/ClientOutboundConnection.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Runtime/Catalog/ActivationDirectory.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- src/Orleans.Runtime/Core/SystemTarget.cs
- src/Orleans.Runtime/GrainDirectory/AdaptiveGrainDirectoryCache.cs
- src/Orleans.Runtime/GrainDirectory/LRUBasedGrainDirectoryCache.cs
- src/Orleans.Runtime/Messaging/MessageCenter.cs
- src/Orleans.Runtime/Networking/GatewayInboundConnection.cs
- src/Orleans.Runtime/Networking/SiloConnection.cs
- src/Orleans.Runtime/Placement/PlacementService.cs
Fixes #6880
This performance improvement PR removes 48 bytes per message object in memory (2x ActivationId + 2x cached GrainAddress refs), and ~32 bytes on the wire (2x ActivationId).
> Remove GrainAddress and ActivationId from Message to reduce overhead

- src/Orleans.Core/Lifecycle/LifecycleSubject.cs
- src/Orleans.Runtime/Core/HostedClient.cs
- src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs
- src/Orleans.Runtime/MembershipService/ClusterMembershipService.cs
- src/Orleans.Runtime/MembershipService/MembershipAgent.cs
- src/Orleans.Runtime/MembershipService/MembershipSystemTarget.cs
- src/Orleans.Runtime/MembershipService/MembershipTableCleanupAgent.cs
- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
- src/Orleans.Runtime/MembershipService/SiloStatusListenerManager.cs
- src/Orleans.Runtime/Networking/ConnectionListener.cs
- src/Orleans.Runtime/Networking/SiloConnectionMaintainer.cs
- src/Orleans.Runtime/ReminderService/LocalReminderService.cs
- src/Orleans.Runtime/Scheduler/WorkItemGroup.cs
- test/Grains/TestGrains/ImplicitSubscriptionCounterGrain.cs
We should not log exceptions as regular parameters, but instead always pass them directly to the log call.
> Use preferred exception logging pattern

- src/Orleans.Core.Abstractions/IDs/GrainAddress.cs
- src/Orleans.Runtime/GrainDirectory/GrainDirectoryHandoffManager.cs
- src/Orleans.Runtime/GrainDirectory/GrainDirectoryPartition.cs
- src/Orleans.Runtime/GrainDirectory/ILocalGrainDirectory.cs
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
The existing code in `ProcessSiloAddEvent` implies that it tries to check all successors, while in fact it only checks the immediate successor. I cleaned up the grain directory code around this to match the actual logic.
> GrainDirectory simplification

- src/AWS/Orleans.Reminders.DynamoDB/DynamoDBServiceCollectionReminderExtensions.cs
- src/AdoNet/Orleans.Reminders.AdoNet/SiloBuilderReminderExtensions.cs
- src/Azure/Orleans.Reminders.AzureStorage/AzureStorageReminderServiceCollectionExtensions.cs
- src/Orleans.Reminders/Hosting/SiloBuilderReminderExtensions.cs
- src/Orleans.Reminders/ReminderService/LocalReminderService.cs
- test/Grains/TestGrainInterfaces/IReminderTestGrain2.cs
- test/Grains/TestInternalGrains/ReminderTestGrain2.cs
- test/TesterInternal/TimerTests/ReminderTests_Base.cs
* Reminders providers should be calling `AddReminders`
* `LocalReminderService` should compensate for clock resolution issues to prevent double-firing reminders
* Compute expected min/max reminder calls programmatically in tests
cc @ElanHasson
> Fix reminder providers, `LocalReminderService`, and tests

- src/Orleans.Core/CodeGeneration/GenericMethodInvoker.cs
- test/CodeGeneration/CodeGenerator.Tests/GenericMethodInvokerTests.cs
Validate constraints that are themselves generic correctly in GenericMethodInvoker.
Fixes #7875.
> Validate constraints that are themselves generic correctly in GenericMethodInvoker.

- src/Orleans.Core/Runtime/RuntimeVersion.cs
Exception encountered when running a client in Kubernetes
` System.ArgumentException: The path is empty. (Parameter 'path') 
at System.IO.Path.GetFullPath(String path) 
at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName) 
at Orleans.Runtime.RuntimeVersion.get_Current() in /_/src/Orleans.Core/Runtime/RuntimeVersion.cs:line 17 
at Orleans.OutsideRuntimeClient.ConsumeServices(IServiceProvider services) in /_/src/Orleans.Core/Runtime/OutsideRuntimeClient.cs:line 156 
at Orleans.ClientBuilder.Build() in /_/src/Orleans.Core/Core/ClientBuilder.cs:line 63`
The application is built as follows:
`dotnet publish my.csproj -c Release  --runtime linux-musl-x64 -p:PublishSingleFile=true --self-contained -p:PublishReadyToRun=true   -o /app/publish`
Error seems related to …
> Avoid accessing Assembly file path when publishing as a single file

- src/Orleans.Runtime/GrainDirectory/GrainDirectoryPartition.cs
- test/TesterInternal/GrainDirectoryPartitionTests.cs
Fix for #7902, and add some tests.
`GrainDirectoryPartition` should allow overwriting an invalid entry.
> Fix: GrainDirectoryPartition should allow overwriting an invalid entry

- samples/Chirper/Chirper.Grains/ChirperAccount.cs
Noticed a copy/paste error in the Chirper sample when I was reviewing the code.
> Trim the correct queue on Chirper account state

- src/Orleans.Runtime/GrainDirectory/GrainDirectoryHandoffManager.cs
- src/Orleans.Runtime/GrainDirectory/ILocalGrainDirectory.cs
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
- src/Orleans.Runtime/GrainDirectory/RemoteGrainDirectory.cs
- src/Orleans.Runtime/Silo/Silo.cs
- test/NonSilo.Tests/Directory/MockLocalGrainDirectory.cs
The grain directory handoff on silo shutdown was useless since Orleans will deactivate all the grains that were in the directory partition of the stopped silo.
The handoff manager also tried to keep a copy of the partition of its successor, but the logic wasn't really useful and might introduce more invalid directory entries, so I removed it too.
> Remove Directory handoff on silo shutdown

- src/Orleans.Serialization/Orleans.Serialization.csproj
The new Microsoft.Orleans.Serialization NuGet package pulls in the Microsoft.DotNet.PlatformAbstractions NuGet package when targeting .NET 6. However, it looks to be unused. The only reference I can find is on [line 142 of `ReferencedAssemblyHelper.cs`](https://github.com/dotnet/orleans/blob/339bf24cd6d7946e99b946567d0655916a62b6d5/src/Orleans.Serialization/Hosting/ReferencedAssemblyHelper.cs#L133-L153), but this is conditionally compiled based on a .NET 5 or greater check.
The proposed change removes the Microsoft.DotNet.PlatformAbstractions dependency when targeting .NET 6.
> Remove PlatformAbstractions on .NET 6

- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBGatewayListProvider.cs
- src/AWS/Orleans.Clustering.DynamoDB/Membership/DynamoDBMembershipTable.cs
- src/AWS/Orleans.Clustering.DynamoDB/Membership/SiloInstanceRecord.cs
- src/AdoNet/Shared/Storage/DbStoredQueries.cs
- src/Azure/Orleans.Clustering.AzureStorage/AzureBasedMembershipTable.cs
- src/Azure/Orleans.Clustering.AzureStorage/OrleansSiloInstanceManager.cs
- src/Azure/Orleans.Clustering.AzureStorage/SiloInstanceTableEntry.cs
- src/Orleans.Clustering.Consul/ConsulGatewayListProvider.cs
- src/Orleans.Clustering.ZooKeeper/ZooKeeperGatewayListProvider.cs
- src/Orleans.Core.Abstractions/IDs/SiloAddress.cs
- src/Orleans.Core.Abstractions/IDs/SiloAddressCodec.cs
- src/Orleans.Core.Abstractions/Utils/Interner.cs
- src/Orleans.Core.Abstractions/Utils/Utils.cs
- src/Orleans.Core/Messaging/CachingSiloAddressCodec.cs
- src/Orleans.Core/Messaging/ClientMessageCenter.cs
- src/Orleans.Runtime/Hosting/EndpointOptions.cs
- src/Orleans.Runtime/Hosting/EndpointOptionsExtensions.cs
- src/Orleans.Runtime/Silo/LocalSiloDetails.cs
- src/Orleans.Serialization/Codecs/IPEndPointCodec.cs
- src/Orleans.Serialization/WireProtocol/Field.cs
This removes unnecessary `IPEndPoint` allocations when creating `SiloAddress` instances.
> Optimize SiloAddress creation

- src/Orleans.Runtime/Catalog/Catalog.cs
We've seen one or two reports of this biting people. This appears to be the root issue.
Fixes #7918
> [3.x] Fix `NullReferenceException` when too many instances of a `[StatelessWorker]` are created and `Debug` logging is enabled

- build.ps1
- global.json
- src/Orleans.CodeGenerator/Diagnostics/InvalidGrainMethodReturnTypeDiagnostic.cs
- src/Orleans.CodeGenerator/InvokableGenerator.cs
- src/Orleans.CodeGenerator/ProxyGenerator.cs
- src/Orleans.CodeGenerator/Resources.Designer.cs
- src/Orleans.CodeGenerator/Resources.resx
Fixes #7907 by adding an analyzer to fail the build on unsupported grain interface method types.
Note that this is based on #7926, which therefore comes first.
> Add build-time analyzer for unsupported grain interface method return types

- src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs
- test/Extensions/ServiceBus.Tests/Streaming/EHStreamingResumeTests.cs
- test/Grains/TestGrainInterfaces/IImplicitSubscriptionCounterGrain.cs
- test/Grains/TestGrains/ImplicitSubscriptionCounterGrain.cs
- test/Grains/TestGrains/ImplicitSubscription_TransientError_RecoverableStream_CollectorGrain.cs
- test/Grains/TestGrains/SlowConsumingGrains/SlowConsumingGrain.cs
- test/Tester/StreamingTests/MemoryStreamResumeTests.cs
- test/Tester/StreamingTests/StreamingResumeTests.cs
Fix for #7686
When creating a cursor from the stream cache, when starting from an event already processed, we should immediately call ` MoveNext()` to avoid sending a duplicate event.
> Fix duplicate streaming event on resume

- Directory.Build.props
With the latest VS preview, there are build breaks otherwise because it will try to use C# 11.
> Use explicit C# LangVersion

- src/Orleans.Connections.Security/Security/DuplexPipeStream.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
- src/Orleans.Core/Utils/LRU.cs
- src/Orleans.Runtime/Catalog/ActivationDirectory.cs
- src/Orleans.Runtime/Silo/SiloControl.cs
Removed unused old code and cleaned up a few related code paths.
I didn't touch anything under Orleans.Serialization - there are lots of old ifdefs, but there's still some plan to support netstandard2.0 for Orleans.Serialization?
> Remove obsolete net48 & netcoreapp3.1 code

- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/CopierGenerator.cs
- src/Orleans.CodeGenerator/InvokableGenerator.cs
- src/Orleans.CodeGenerator/LibraryTypes.cs
- src/Orleans.CodeGenerator/Model/IGeneratedInvokerDescription.cs
- src/Orleans.CodeGenerator/Model/ISerializableTypeDescription.cs
- src/Orleans.CodeGenerator/Model/InvokableInterfaceDescription.cs
- src/Orleans.CodeGenerator/Model/SerializableTypeDescription.cs
- src/Orleans.CodeGenerator/ProxyGenerator.cs
- src/Orleans.CodeGenerator/SerializerGenerator.cs
- src/Orleans.Core.Abstractions/Core/IGrainCallContext.cs
- src/Orleans.Core.Abstractions/Runtime/GrainReference.cs
- src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs
- src/Orleans.Core/Runtime/GrainReferenceRuntime.cs
- src/Orleans.Core/Runtime/InvokableObjectManager.cs
- src/Orleans.Core/Runtime/OutgoingCallInvoker.cs
- src/Orleans.Runtime/Cancellation/CancellationSourcesExtension.cs
- src/Orleans.Runtime/Core/GrainMethodInvoker.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs
- src/Orleans.Serialization/ISerializableSerializer/SerializationCallbacksFactory.cs
- src/Orleans.Serialization/ISerializableSerializer/SerializationConstructorFactory.cs
- src/Orleans.Serialization/Invocation/IInvokable.cs
- src/Orleans.Serialization/TypeSystem/TypeConverter.cs
- src/Orleans.Serialization/Utilities/FieldAccessor.cs
- src/Orleans.Transactions/TransactionAttribute.cs
- test/Grains/TestGrains/MethodInterceptionGrain.cs
- test/Grains/TestGrains/ReentrantGrain.cs
- test/Orleans.Serialization.UnitTests/Request.cs
- test/Tester/GrainCallFilterTests.cs
* Use specialized field getters for struct fields that pass instances by reference.
* Change generated dynamic method signatures to avoid argument shuffling delegate thunks.
* Don't generate unused property setters for settable properties.
* Don't generate copier fields for shallow-copyable types.
* In struct copiers set only fields that need deep-copying and use the input parameter directly for everything else.
* Replace generic methods on `IInvokable` with untyped methods.
* Remove unused properties from `IInvokable`.
* Replace generated properties with methods to reduce metadata size.
> Optimize serializer generated code

- src/Orleans.CodeGenerator/Utilities/SymbolExtensions.cs
- test/CodeGeneration/CodeGenerator.Tests/CodeGenerationTests.cs
- test/CodeGeneration/CodeGenerator.Tests/CodeGenerator.Tests.csproj
Fixes #7962.
I also did some minor refactoring in `CodeGenerator.Tests` to add some coverage on `CodeGenerator.GenerateCode`. Looks like this wasn't covered previously, unless I missed a better location to add this test.
> Fix serializer classes not being generated for types in methods external to grain implementations.

- src/Orleans.Reminders/GrainReminderExtensions.cs
- src/Orleans.Runtime/Storage/StateStorageBridge.cs
Fixes
```
StateStorageBridge.cs(49,58): error CS0121: The call is ambiguous between the following methods or 
properties:'ArgumentNullException.ThrowIfNull(object?, string?)' and
'ArgumentNullException.ThrowIfNull(void*, string?)'
```
when I update orleans to net7.0 locally. It happens because of new overload added in net7.0 - https://github.com/dotnet/runtime/pull/61633
> Fix net7.0 compilation

- src/Orleans.Streaming/Core/StreamSubscriptionManager.cs
- src/Orleans.Streaming/Internal/IStreamGrainExtensions.cs
- src/Orleans.Streaming/Internal/StreamConsumerExtension.cs
- src/Orleans.Streaming/Internal/StreamDirectory.cs
- src/Orleans.Streaming/Internal/StreamImpl.cs
- src/Orleans.Streaming/Internal/StreamSubscriptionHandleImpl.cs
- src/Orleans.Streaming/InternalStreamId.cs
- src/Orleans.Streaming/PersistentStreams/PersistentStreamProvider.cs
- src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs
- src/Orleans.Streaming/PersistentStreams/QueueStreamDataStructures.cs
- src/Orleans.Streaming/PersistentStreams/StreamConsumerCollection.cs
- src/Orleans.Streaming/PersistentStreams/StreamEventDeliveryFailureException.cs
- src/Orleans.Streaming/Providers/IStreamProviderRuntime.cs
- src/Orleans.Streaming/PubSub/FaultedSubscriptionException.cs
- src/Orleans.Streaming/PubSub/GrainBasedPubSubRuntime.cs
- src/Orleans.Streaming/PubSub/IPubSubRendezvousGrain.cs
- src/Orleans.Streaming/PubSub/ImplicitStreamPubSub.cs
- src/Orleans.Streaming/PubSub/ImplicitStreamSubscriberTable.cs
- src/Orleans.Streaming/PubSub/PubSubPublisherState.cs
- src/Orleans.Streaming/PubSub/PubSubRendezvousGrain.cs
- src/Orleans.Streaming/PubSub/PubSubSubscriptionState.cs
- src/Orleans.Streaming/PubSub/StreamPubSubImpl.cs
- test/Grains/TestInternalGrains/StreamLifecycleTestGrains.cs
- test/Grains/TestInternalGrains/StreamLifecycleTestInternalGrains.cs
- test/TesterInternal/StreamingTests/PubSubRendezvousGrainTests.cs
- test/TesterInternal/StreamingTests/SingleStreamTestRunner.cs
- test/TesterInternal/StreamingTests/StreamTestUtils.cs
Right now, `InternalStreamId` is internal only. Making it public will help pluggability.
`QualifiedStreamId` is also a better name for this struct.
> Rename InternalStreamId to QualifiedStreamId and make it public

- src/Orleans.Runtime/Catalog/StatelessWorkerGrainContext.cs
- test/DefaultCluster.Tests/StatelessWorkerTests.cs
- test/Grains/TestGrainInterfaces/IStatelessWorkerScalingGrain.cs
- test/Grains/TestGrains/StatelessWorkerScalingGrain.cs
- test/Tester/StatelessWorkerActivationTests.cs
This implements changing the activation strategy for StatelessWorker in accordance with: https://github.com/dotnet/orleans/issues/7966
> Change the activation strategy for StatelessWorkers from round-robin to on-demand

- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/InvokableGenerator.cs
- src/Orleans.CodeGenerator/Model/IGeneratedInvokerDescription.cs
- src/Orleans.CodeGenerator/Model/ISerializableTypeDescription.cs
- src/Orleans.CodeGenerator/Model/SerializableTypeDescription.cs
- src/Orleans.Serialization/Serializers/CodecProvider.cs
Don't generate activators for simple invokables and value types.
> Don't generate activators for simple invokables

- src/Orleans.CodeGenerator/ActivatorGenerator.cs
- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/CopierGenerator.cs
- src/Orleans.CodeGenerator/InvokableGenerator.cs
- src/Orleans.CodeGenerator/LibraryTypes.cs
- src/Orleans.CodeGenerator/MetadataGenerator.cs
- src/Orleans.CodeGenerator/Model/IGeneratedInvokerDescription.cs
- src/Orleans.CodeGenerator/Model/ISerializableTypeDescription.cs
- src/Orleans.CodeGenerator/Model/MetadataModel.cs
- src/Orleans.CodeGenerator/Model/SerializableTypeDescription.cs
- src/Orleans.CodeGenerator/ProxyGenerator.cs
- src/Orleans.CodeGenerator/SerializerGenerator.cs
- src/Orleans.CodeGenerator/SyntaxGeneration/FSharpUtils.cs
- src/Orleans.CodeGenerator/SyntaxGeneration/SyntaxFactoryUtility.cs
- src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs
- src/Orleans.Serialization/Utilities/FieldAccessor.cs
- test/Benchmarks/Serialization/Comparison/CopierBenchmark.cs
- test/Benchmarks/Serialization/ComplexTypeBenchmarks.cs
- test/Benchmarks/Serialization/Models/Vector3.cs
- test/Grains/TestGrainInterfaces/IExceptionGrain.cs
* Make field accessors static.
* Use concrete codec/copier types for base types.
* Use concrete codec/copier types in more places (by fixing the assembly comparison condition).
* Don't generate activators for enum types.
* Don't generate a copier for shallow-copyable types (only register a dummy copier).
* Don't generate unreachable copier code paths for abstract types.
* Reduce metadata size by using more generic names for codec fields and parameters.
Using concrete codec/copier has the side-effect of creating multiple instances of the codec/copier classes because only the generic interface variant is cached in ServiceProvider. Making field accessors static here helps somewhat with that overhead.
> Optimize serializer generated code (p2)

- src/Orleans.CodeGenerator/SerializerGenerator.cs
- src/Orleans.Serialization/Codecs/ObjectCodec.cs
- src/Orleans.Serialization/Exceptions.cs
- src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs
- src/Orleans.Serialization/Invocation/PooledResponse.cs
- src/Orleans.Serialization/Serializers/CodecProvider.cs
- src/Orleans.Serialization/Serializers/ConcreteTypeSerializer.cs
- src/Orleans.Streaming/Internal/StreamHandshakeToken.cs
- src/Orleans.Transactions/Abstractions/ITransactionalStateStorage.cs
- src/Orleans.Transactions/DistributedTM/ParticipantId.cs
- src/Orleans.Transactions/DistributedTM/TransactionInfo.cs
- src/Orleans.Transactions/OrleansTransactionException.cs
- src/Orleans.Transactions/TOC/TransactionCommitter.cs
Abstract type codecs are identical for `IFieldCodec`, and for types with no serializable fields also for `IBaseCodec`.
Removed the type specific (de)serialization code path from `WriteField/ReadValue` for abstract types since they can never be created anyway.
> Generate less code for abstract type codecs

- src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs
- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Providers/StorageSerializer/JsonGrainStorageSerializer.cs
- src/Orleans.Core/Serialization/OrleansJsonSerializer.cs
- src/Orleans.Core/Serialization/OrleansJsonSerializerOptions.cs
- src/Orleans.Core/Serialization/OrleansJsonSerializerSettings.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Transactions/State/TransactionalStateFactory.cs
- test/DefaultCluster.Tests/GrainReferenceTest.cs
- test/NonSilo.Tests/Serialization/OrleansJsonSerializerTests.cs
The current pattern isn't great, so I tried to rely as much as possible on DI capabilities to refactor how `OrleansJsonSerializer` is configured today.
Related PR: #8011 
cc @niblak
> Allow configuration of OrleansJsonSerializer settings

- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/CopierGenerator.cs
- src/Orleans.CodeGenerator/FieldIdAssignmentHelper.cs
- src/Orleans.CodeGenerator/InvokableGenerator.cs
- src/Orleans.CodeGenerator/LibraryTypes.cs
- src/Orleans.CodeGenerator/Model/IGeneratedInvokerDescription.cs
- src/Orleans.CodeGenerator/Model/ISerializableTypeDescription.cs
- src/Orleans.CodeGenerator/Model/SerializableTypeDescription.cs
- src/Orleans.CodeGenerator/SerializerGenerator.cs
- src/Orleans.CodeGenerator/SyntaxGeneration/SymbolExtensions.cs
- src/Orleans.Core.Abstractions/Placement/PlacementStrategy.cs
- src/Orleans.Core.Abstractions/Runtime/GrainReference.cs
- src/Orleans.Core.Abstractions/Versions/Compatibility/ICompatibilityDirector.cs
- src/Orleans.Core.Abstractions/Versions/Selector/IVersionSelector.cs
- src/Orleans.Serialization.Abstractions/Annotations.cs
- src/Orleans.Transactions/DistributedTM/ParticipantId.cs
- test/Orleans.Serialization.UnitTests/GeneratedSerializerTests.cs
- test/Orleans.Serialization.UnitTests/Models.cs
* Make `ImmutableAttribute` non-inheritable.
* Add new `SerializerTransparentAttribute` for abstract classes.
This is very effective on all invokable types where it effectively removes two empty abstract classes from the type hierarchy for each invokable.
> Add new SerializerTransparentAttribute for abstract classes

- src/Orleans.Core/Providers/StorageSerializer/JsonGrainStorageSerializer.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- test/Extensions/TesterAzureUtils/Persistence/PersistenceProviderTests.cs
Until now, if the developer didn't explicitly setup a `IGrainStorageSerializer`, the default was to use the Orleans internal serializer.
With this change, the Json one will be used instead.
> Make Json the default serializer for grain state

- Directory.Build.props
... and update other packages to latest stable version.
The omissions are KubernetesClient, since the API has changed again and it will require more work to upgrade, and Google.Cloud.PubSub.V1, also since the API is substantially different from the current version.
> Update packages to .NET 7 RC2

- src/Orleans.Core/Hosting/GenericHostExtensions.cs
- src/Orleans.Runtime/Hosting/GenericHostExtensions.cs
As suggested by @IEvangelist, one papercut when migrating from Orleans 3.x to 7.0 is that the signature for the hosting extensions changed. This PR adds the original `UseOrleans` `IHostBuilder` overload back.
> Add overloads to hosting extensions which do not include HostBuilderContext

- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
- src/Orleans.Core/Networking/Connection.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Serialization/Codecs/FieldHeaderCodec.cs
- src/Orleans.Serialization/Codecs/GeneralizedReferenceTypeSurrogateCodec.cs
- src/Orleans.Serialization/Codecs/GeneralizedValueTypeSurrogateCodec.cs
- src/Orleans.Serialization/Codecs/IPAddressCodec.cs
- src/Orleans.Serialization/Codecs/ReferenceCodec.cs
- src/Orleans.Serialization/Codecs/TypeSerializerCodec.cs
- src/Orleans.Serialization/Codecs/UnknownFieldMarker.cs
- src/Orleans.Serialization/Session/ReferencedObjectCollection.cs
- src/Orleans.Serialization/Session/ReferencedTypeCollection.cs
- src/Orleans.Serialization/TypeSystem/TypeCodec.cs
- src/Orleans.Serialization/TypeSystem/TypeConverter.cs
- test/Orleans.Serialization.UnitTests/GeneratedSerializerTests.cs
- test/Orleans.Serialization.UnitTests/Models.cs
`SchemaType.Referenced` is currently unsupported and although there looks to be some code for it, it's actually non-working and any such type references would fail on deserialization.
> Implement SchemaType.Referenced

- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
There is no need for OutsideRuntimeClient to log when it is being terminated. We already have a log line for when shutdown begins and completes. The red box shows what noise this PR removes.
> Reduce logging noise from OutsideRuntimeClient on shutdown

- src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs
- test/Tester/ActivityPropagationTests.cs
This allows for selectively choosing activity for runtime grains (like `IMembershipTable`, `IRemoteGrainDirectory`, or `IDeploymentLoadPublisher`) or only user created grains (what the user has created for their system/application).
It is assumed that consumers will primarily want the user grain Activity and not also the runtime/internal grain calls.
Mechanically, this is achieved by looking to see if the namespace of the grain starts with "Orleans". There is the possibility that a user can create their own grain in a namespace starting with "Orleans" (ex. `Orleans.MyCompany.MyApp`) but this is not an idiomatic pattern for namespace naming so it may be sufficient to document this behavior.
This does introduce a breaking change for current consumers of ActivitySources. 
For example, users …
> Activity source split for User/Runtime grain calls

- src/Orleans.CodeGenerator/SerializerGenerator.cs
- src/Orleans.Core.Abstractions/IDs/SiloAddressCodec.cs
- src/Orleans.Core/Manifest/ImplementedInterfaceProvider.cs
- src/Orleans.Core/Manifest/TypeNameGrainPropertiesProvider.cs
- src/Orleans.Core/Messaging/RejectionResponse.cs
- src/Orleans.Core/Runtime/RuntimeVersion.cs
- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
- src/Orleans.Serialization/Codecs/FieldHeaderCodec.cs
- src/Orleans.Serialization/Codecs/ReferenceCodec.cs
- src/Orleans.Serialization/Configuration/DefaultTypeManifestProvider.cs
- src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs
- src/Orleans.Serialization/ISerializableSerializer/ExceptionCodec.cs
- src/Orleans.Serialization/Session/WellKnownTypeCollection.cs
- src/Orleans.Serialization/TypeSystem/CachedTypeResolver.cs
- src/Orleans.Serialization/TypeSystem/RuntimeTypeNameFormatter.cs
- test/Orleans.Serialization.UnitTests/GeneratedSerializerTests.cs
* Make null reference encoding more compact.
* Add more well-known types.
* Add caches for some metadata values.
Depends on #8052 (only the last commit is meant for this PR).
> Optimize type encoding

- src/Orleans.Serialization.FSharp/FSharpCodecs.cs
- src/Orleans.Serialization/Codecs/ArrayCodec.cs
- src/Orleans.Serialization/Codecs/DictionaryCodec.cs
- src/Orleans.Serialization/Codecs/FieldHeaderCodec.cs
- src/Orleans.Serialization/Codecs/HashSetCodec.cs
- src/Orleans.Serialization/Codecs/IntegerCodec.cs
- src/Orleans.Serialization/Codecs/ListCodec.cs
- src/Orleans.Serialization/Codecs/NullableCodec.cs
- src/Orleans.Serialization/Codecs/QueueCodec.cs
- src/Orleans.Serialization/Codecs/StackCodec.cs
- src/Orleans.Serialization/Codecs/WellKnownStringComparerCodec.cs
- src/Orleans.Serialization/ISerializableSerializer/DotNetSerializableCodec.cs
- src/Orleans.Serialization/ISerializableSerializer/ValueTypeSerializer.cs
* Add a specialized codec for `FSharpOption<T>` to avoid value type serialization for `FSharpOption<T>.None`.
* Fix `FSharpResult<T, TError>` encoding.
* Fix `ArraySegment<T>` and `[ReadOnly]Memory<T>` reference encoding.
* Use `UInt32Codec` to encode collection lengths.
* Use field IDs instead of separate tag fields for choice types.
> Fix F# codecs and some array codecs.

- test/Orleans.Serialization.UnitTests/GeneratedSerializerTests.cs
- test/Orleans.Serialization.UnitTests/Models.cs
If a record's primary constructor has explicit property ids specified, we do not use the two-layer serialization which records otherwise use. This allows records to be serialized identically to a regular class. This PR adds a test showing that the results are bitwise identical.
> Add a test to ensure records can be serialized identically to classes

- Directory.Build.targets
- src/Orleans.CodeGenerator.MSBuild/Orleans.CodeGenerator.MSBuild.csproj
- src/Orleans.CodeGenerator.MSBuild/buildMultiTransitive/Microsoft.Orleans.CodeGenerator.MSBuild.targets
- src/Orleans.CodeGenerator/buildTransitive/Microsoft.Orleans.CodeGenerator.props
- src/Orleans.Sdk/Orleans.Sdk.csproj
- src/Orleans.Sdk/buildTransitive/Microsoft.Orleans.Sdk.targets
- test/Directory.Build.props
- test/Orleans.Serialization.UnitTests/Orleans.Serialization.UnitTests.csproj
This PR fixes the SDK package such that it correctly configures global usings even when included transitively (eg, via the *Microsoft.Orleans.Server* metapackage)
> Fix SDK packaging

- src/Orleans.Core.Abstractions/IDs/IdSpanCodec.cs
- src/Orleans.Core.Abstractions/IDs/SiloAddressCodec.cs
- src/Orleans.Core/Messaging/CachingIdSpanCodec.cs
- src/Orleans.Core/Messaging/CachingSiloAddressCodec.cs
- src/Orleans.Core/Messaging/Message.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
- src/Orleans.Serialization/Codecs/IPAddressCodec.cs
- src/Orleans.Serialization/Codecs/IntegerCodec.cs
- src/Orleans.Serialization/Serializer.cs
- src/Orleans.Serialization/Session/SerializerSessionPool.cs
- src/Orleans.Serialization/Utilities/VarIntWriterExtensions.cs
* Remove unnecessary wrapping from `CachingIdSpanCodec` and optimize `IdSpanCodec`.
* Simplify `CachingSiloAddressCodec` and `IPAddress` codecs.
* Fix some expected vs actual type encoding issues and simplify serializer helpers.
> Optimize message header encoding

- src/Orleans.CodeGenerator/AnalyzerReleases.Shipped.md
- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/Diagnostics/CanNotGenerateImplicitFieldIdsDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/InaccessibleSerializableTypeDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/InaccessibleSetterDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/IncorrectProxyBaseClassSpecificationDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/InvalidRpcMethodReturnTypeDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/RpcInterfacePropertyDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/UnhandledCodeGenerationExceptionDiagnostic.cs
- src/Orleans.CodeGenerator/FieldIdAssignmentHelper.cs
- src/Orleans.CodeGenerator/InvokableGenerator.cs
- src/Orleans.CodeGenerator/LibraryTypes.cs
- src/Orleans.CodeGenerator/Model/InvokableInterfaceDescription.cs
- src/Orleans.CodeGenerator/Model/MethodDescription.cs
- src/Orleans.CodeGenerator/OrleansSourceGenerator.cs
- src/Orleans.CodeGenerator/ProxyGenerator.cs
- src/Orleans.CodeGenerator/Resources.Designer.cs
- src/Orleans.CodeGenerator/Resources.resx
- src/Orleans.CodeGenerator/SyntaxGeneration/SymbolExtensions.cs
- test/TesterInternal/StreamingTests/PubSubRendezvousGrainTests.cs
* Add a catch-all diagnostic for unhandled exceptions so that users do not need to look through build logs
* Fail the build when a type is marked `[GenerateSerializer]` but it is inaccessible from generated code (#8085)
* Add diagnostics for known user errors. Some of these overlap with Orleans.Analyzers diagnostics, but since Orleans.CodeGenerator is not Orleans-specific (knows nothing about grains, for example), they use different wording.
Addresses https://github.com/dotnet/orleans/issues/8080#issuecomment-1294389308
Fixes #8085
> Add diagnostic for unexpected codegen exceptions and known user errors

- src/Orleans.Streaming/Hosting/ClientBuilderStreamingExtensions.cs
- src/Orleans.Streaming/Hosting/SiloBuilderMemoryStreamExtensions.cs
Since I don't expect a lot of people to change the message body serializer, I think providing these overrides will make configuration easier.
> Add configuration methods for memory stream

- src/Orleans.Core/Providers/IGrainStorage.cs
- src/Orleans.Runtime/Core/GrainRuntime.cs
- src/Orleans.Runtime/Facet/Persistent/PersistentStateStorageFactory.cs
- src/Orleans.Transactions/State/TransactionalStateStorageProviderWrapper.cs
- test/TesterInternal/StorageTests/PersistenceGrainTests.cs
In `IGrainStorage`, the first parameter shouldn't be the grain type, but the grain state name.
The grain type is already included in the `GrainId` and including the CLR type in storage will make renaming type very difficult without losing state.
> Do not use grainType in IGrainStorage

- src/Orleans.Runtime/GrainDirectory/ClientDirectory.cs
- src/Orleans.Runtime/MembershipService/LocalSiloHealthMonitor.cs
- src/Orleans.Runtime/MembershipService/MembershipTableCleanupAgent.cs
- src/Orleans.Runtime/MembershipService/SiloHealthMonitor.cs
- src/Orleans.Runtime/Timers/AsyncTimer.cs
Currently, we will count time spent firing the timer itself towards overshoot, so if the callback is slower than the `TimerDelaySlack` (hard coded to 3s), that will count as a health degradation. We shouldn't do this, since we do not know how much work the timer callback has to do or whether it is ever supposed to fire again (eg, maybe it will decide it doesn't need to wait for any more ticks and it's complete).
> AsyncTimer monitoring: measure overshoot only when waiting for timer

- src/Orleans.Core/GrainReferences/GrainReferenceActivator.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
- src/Orleans.Core/Networking/Connection.cs
- src/Orleans.Core/Networking/ConnectionFactory.cs
- src/Orleans.Serialization/Invocation/Response.cs
* Don't encode PooledResponse<T> wrapper types for normal response messages, only encode T.
Fixed the issues that caused #8093.
> Optimize raw message body encoding

- src/Orleans.CodeGenerator/LibraryTypes.cs
- src/Orleans.Serialization.TestKit/CopierTester.cs
- src/Orleans.Serialization.TestKit/FieldCodecTester.cs
- src/Orleans.Serialization.TestKit/ValueTypeFieldCodecTester.cs
- src/Orleans.Serialization/Buffers/Reader.cs
- src/Orleans.Serialization/Cloning/IDeepCopier.cs
- src/Orleans.Serialization/Codecs/FloatCodec.cs
- src/Orleans.Serialization/Codecs/IntegerCodec.cs
- src/Orleans.Serialization/Configuration/DefaultTypeManifestProvider.cs
- src/Orleans.Serialization/Hosting/ServiceCollectionExtensions.cs
- src/Orleans.Serialization/Utilities/VarIntReaderExtensions.cs
- test/Orleans.Serialization.UnitTests/BuiltInCodecTests.cs
- test/Orleans.Serialization.UnitTests/ConverterTests.cs
- test/Orleans.Serialization.UnitTests/JsonSerializerTests.cs
- test/Orleans.Serialization.UnitTests/NewtonsoftJsonCodecTests.cs
- test/Orleans.Serialization.UnitTests/NumericsWideningAndNarrowingTests.cs
This PR adds codecs for some standard library numeric types, `Int128`, `UInt128`, and `Half`.
It also adds widening & narrowing tests for all existing supported types: the current versioning rules allow numeric fields to be widened and narrowed (with a runtime exception for overflow) but do not allow changing signedness or between integer & floating point types.
> Add codecs for Int128, UInt128, and Half

- .azure/pipelines/build.yaml
> Remove default version suffix for Azure DevOps pipeline

- .azure/pipelines/build.yaml
Since parameters cannot be empty, the solution is to add another flag to disable the version suffix entirely.
> Fix version suffix in build.yaml

- .azure/pipelines/build.yaml
> [3.x] Fix version suffix in build.yaml

- samples/VBHelloWorld/HelloWorld/HelloWorld.csproj
- samples/VBHelloWorld/HelloWorld/Program.cs
- samples/VBHelloWorld/Interfaces/Interfaces.vbproj
- samples/VBHelloWorld/VBGrains/VBGrains.vbproj
> Upgrade 'VB Hello World' sample

- src/Azure/Orleans.GrainDirectory.AzureStorage/AzureTableGrainDirectory.cs
- src/Azure/Orleans.GrainDirectory.AzureStorage/Properties/AssemblyInfo.cs
- test/Extensions/TesterAzureUtils/AzureGrainDirectoryTests.cs
- test/Tester/Directories/GrainDirectoryTests.cs
Fix #8148 
`MembershipVersion` is missing from the entity stored in table, so when Orleans is reading it from storage, `MembershipVersion` is set to its default value.
After inserting an entry to the directory, Orleans will check that the entry in storage is equal to the entry it expected to insert. Since `MembershipVersion` was always set to the default value when reading from storage, the equality check failed.
> Add MembershipVersion to GrainDirectoryEntity

- src/Orleans.CodeGenerator/Orleans.CodeGenerator.csproj
This allows properties defined in csproj files to be propagated to the code generator for customization, etc
> Fix packaging of CodeGenerator to accept project properties

- samples/ChatRoom/ChatRoom.Client/ChatRoom.Client.csproj
- samples/ChatRoom/ChatRoom.Client/ClientContext.cs
- samples/ChatRoom/ChatRoom.Client/Program.cs
- samples/ChatRoom/ChatRoom.Client/StreamObserver.cs
- samples/ChatRoom/ChatRoom.Common/ChatMsg.cs
- samples/ChatRoom/ChatRoom.Common/ChatRoom.Common.csproj
- samples/ChatRoom/ChatRoom.Common/IChannelGrain.cs
- samples/ChatRoom/ChatRoom.Service/ChannelGrain.cs
- samples/ChatRoom/ChatRoom.Service/ChatRoom.Service.csproj
- samples/ChatRoom/ChatRoom.Service/Program.cs
> Upgrade 'Chat Room' sample

- samples/ShoppingCart/Abstractions/CartItem.cs
- samples/ShoppingCart/Abstractions/Orleans.ShoppingCart.Abstractions.csproj
- samples/ShoppingCart/Abstractions/ProductDetails.cs
- samples/ShoppingCart/Grains/InventoryGrain.cs
- samples/ShoppingCart/Grains/Orleans.ShoppingCart.Grains.csproj
- samples/ShoppingCart/README.md
- samples/ShoppingCart/Silo/Orleans.ShoppingCart.Silo.csproj
- samples/ShoppingCart/Silo/Program.cs
> Upgrade 'Shopping Cart' sample

- samples/GPSTracker/GPSTracker.Common/DeviceMessage.cs
- samples/GPSTracker/GPSTracker.Common/GPSTracker.Common.csproj
- samples/GPSTracker/GPSTracker.Common/IDeviceGrain.cs
- samples/GPSTracker/GPSTracker.Common/IPushNotifierGrain.cs
- samples/GPSTracker/GPSTracker.Common/VelocityMessage.cs
- samples/GPSTracker/GPSTracker.FakeDeviceGateway/GPSTracker.FakeDeviceGateway.csproj
- samples/GPSTracker/GPSTracker.FakeDeviceGateway/Program.cs
- samples/GPSTracker/GPSTracker.Service/GPSTracker.Service.csproj
- samples/GPSTracker/GPSTracker.Service/Grains/DeviceGrain.cs
- samples/GPSTracker/GPSTracker.Service/Grains/HubListGrain.cs
- samples/GPSTracker/GPSTracker.Service/Grains/IHubListGrain.cs
- samples/GPSTracker/GPSTracker.Service/Grains/IRemoteLocationHub.cs
- samples/GPSTracker/GPSTracker.Service/Grains/PushNotifierGrain.cs
- samples/GPSTracker/GPSTracker.Service/Grains/RemoteLocationHub.cs
- samples/GPSTracker/GPSTracker.Service/HubListUpdater.cs
- samples/GPSTracker/GPSTracker.Service/Hubs/LocationHub.cs
- samples/GPSTracker/GPSTracker.Service/Program.cs
- samples/GPSTracker/GPSTracker.Service/Properties/launchSettings.json
> Upgrade 'GPS Tracker' sample

- src/Azure/Shared/Storage/AzureBlobUtils.cs
- src/Azure/Shared/Storage/AzureTableUtils.cs
- src/Orleans.CodeGenerator/PropertyUtility.cs
- src/Orleans.CodeGenerator/SyntaxGeneration/Identifier.cs
- src/Orleans.TestingHost/UnixSocketTransport/UnixSocketConnectionOptions.cs
This PR replaces all regular expression usages in the project with source generated or at least dynamically compiled ones. It should increase performance a bit, especially in code generator which is now using source generators, isn't it? Also projects using Orleans will have more room for their regexps' cache because global Regex cache's size is quite small (15) and Orleans will not use it now.
As it is my first contribution to Orleans, I still have questions:
* I have doubts about using source generated regexps due to the fact that classes containing regexps need to be made partial. Is this OK? Should I change that usages to ordinary regexps with Compiled option?
* I have some more low-hanging fruits in mind to fix. Should I create an issue for that (including this PR)?
I'm planning to …
> Use code generated or compiled regular expressions where possible

- .azure/pipelines/build.yaml
- .config/tsaoptions.json
- `cherry-pick` from #8159 branch, with slight adjustments
- enable CodeQL in this branch
- use explicit tasks to enable manual builds of any branch
- add a new top-level parameter to enable CodeQL3000 in manual builds
- tag CodeQL3000 builds that do actual CodeQL3000 work
- add a tsaoptions.json file
- initial area path value is certainly wrong
- other values may be incorrect too
> [main] Add CodeQL3000 tasks

- .azure/pipelines/build.yaml
- .config/tsaoptions.json
- enable CodeQL in this branch
- use explicit tasks because this is not the repo's default branch
- add a new top-level parameter to enable CodeQL3000 in manual builds
- tag CodeQL3000 builds that do actual CodeQL3000 work
- add a tsaoptions.json file
- initial area path value is certainly wrong = other values may be incorrect too
> [3.x] Add CodeQL3000 tasks

- src/Azure/Orleans.Streaming.AzureStorage/Providers/Streams/AzureQueue/AzureQueueAdapterFactory.cs
- src/Orleans.CodeGenerator/Model/MetadataModel.cs
- src/Orleans.Core/Networking/Shared/MemoryPoolSlab.cs
- src/Orleans.Serialization/TypeSystem/CompoundTypeAliasTree.cs
- src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs
- src/Orleans.TestingHost/TestStorageProviders/FaultInjectionStorageServiceCollectionExtensions.cs
- test/DefaultCluster.Tests/GrainReferenceCastTests.cs
- test/Extensions/TesterAdoNet/StorageTests/Relational/AdotNetProviderFunctionalityTests.cs
- test/Grains/TestInternalGrains/ReminderTestGrain2.cs
Empty statements (just extra semicolon) after return statements are treated as errors by ReSharper so one should always silence them. Some other analyzers such as SonarCube can also be triggered by statements like these so it is better to just delete them.
This PR deletes all empty semicolon statements.
> Delete empty statements as they are treated as errors by some analyzers

- .github/workflows/ci.yml
- test/Extensions/TesterAdoNet/RelationalUtilities/MySqlStorageForTesting.cs
- test/Extensions/TesterAdoNet/RelationalUtilities/PostgreSqlStorageForTesting.cs
- test/Extensions/TesterAdoNet/RelationalUtilities/RelationalStorageForTesting.cs
- test/Extensions/TesterAdoNet/RelationalUtilities/SqlServerStorageForTesting.cs
- test/Extensions/TesterAdoNet/StorageTests/MySqlRelationalStoreTests.cs
- test/Extensions/TesterAdoNet/StorageTests/RelationalStoreTests.cs
- test/TesterInternal/ConnectionStringFixture.cs
- test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs
- Some tests were skipped if the setup failed. Tests should fail, not skip in this case.
- Failures started when 10.10 was released. I think we should target our tests against the latest LTS version (currently 10.6)
> Fix mariadb tests

- Directory.Packages.props
- src/Orleans.Hosting.Kubernetes/KubernetesClientExtensions.cs
- src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs
- src/Orleans.Hosting.Kubernetes/KubernetesHostingExtensions.cs
Fix for #8193
The `KubernetesClient` version in use is stale and does not work with current versions of Kubernetes.
I tested this against Kubernetes 1.25.2 (AKS).
> Bumped KubernetesClient to v9.0.38

- src/Orleans.CodeGenerator/InvokableGenerator.cs
Fixes cases where the C# analyzer isn't able to run (eg, building code for an F# project) and an unsupported grain interface return type is being used.
Fixes: #8233
> Fix diagnostic for invalid grain method return types

- src/Orleans.Serialization/Codecs/CollectionCodec.cs
- test/Orleans.Serialization.UnitTests/BuiltInCodecTests.cs
Fixes #8237 by adding a codec for `System.Collections.ObjectModel.Collection<T>`
> Add `Collection<T>` serialization codec

- src/Redis/Orleans.Persistence.Redis/Hosting/RedisGrainStorageServiceCollectionExtensions.cs
- src/Redis/Orleans.Persistence.Redis/Hosting/RedisSiloBuilderExtensions.cs
The Redis provider for Orleans 7.0 was based on the Azure blob storage provider, a handful of code documentation was copied without modification and still refer to azure blob storage. This PR changes those to refer to Redis.
> correct code documentation which incorrectly refers to azure blob storage

- Directory.Build.props
- src/Orleans.Hosting.Kubernetes/KubernetesClientExtensions.cs
- src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs
- src/Orleans.Hosting.Kubernetes/KubernetesHostingExtensions.cs
Following discussion on #8199 this is an attempt to upgrade KubernetesClient to v9.0.38 on Orleans 3.x.
I have tried to follow #8199 as much as possible to keep a standard therefore I have also removed the named `HttpClient` `Orleans.Kubernetes.Agent` and `TypedClient` `IKubernetes`
I would be very glad if someone could help me test this:
- I do not have a Kubernetes 1.25.2 cluster
- Testing on .NET Standard 2
- It's my first time contributing to a big project
> Bumped KubernetesClient to v9.0.38 on Orleans 3.x

- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubSequenceToken.cs
- src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubSequenceTokenV2.cs
- src/Orleans.Persistence.Memory/Hosting/MemoryGrainStorageSiloBuilderExtensions.cs
- src/Orleans.Persistence.Memory/Options/MemoryGrainStorageOptions.cs
- src/Orleans.Persistence.Memory/Storage/MemoryStorage.cs
- src/Orleans.Persistence.Memory/Storage/MemoryStorageWithLatency.cs
- src/Orleans.Streaming/Common/EventSequenceToken.cs
- src/Orleans.Streaming/Common/EventSequenceTokenV2.cs
- test/DefaultCluster.Tests/BasicActivationTests.cs
- test/DefaultCluster.Tests/ObserverTests.cs
- test/DefaultCluster.Tests/SerializationTests/SerializationTests.cs
- test/DefaultCluster.Tests/TimerOrleansTest.cs
- test/Extensions/TesterAzureUtils/Persistence/PersistenceProviderTests.cs
- test/Grains/TestGrainInterfaces/IValueTypeTestGrain.cs
- test/Grains/TestGrains/ImplicitSubscription_TransientError_RecoverableStream_CollectorGrain.cs
- test/NonSilo.Tests/General/Identifiertests.cs
- test/Tester/HeterogeneousSilosTests/UpgradeTests/RuntimeStrategyChangeTests.cs
- test/Tester/HeterogeneousSilosTests/UpgradeTests/UpgradeTests.cs
- test/Tester/HeterogeneousSilosTests/UpgradeTests/VersionPlacementTests.cs
- test/Tester/StreamingTests/GeneratedStreamRecoveryTests.cs
- test/Tester/StreamingTests/MemoryStreamResumeTests.cs
- test/TesterInternal/ActivationsLifeCycleTests/DeactivateOnIdleTests.cs
A lightweight code change to implement the IStorageProviderSerializerOptions interface to MemoryGrainStorageOptions. Issue: https://github.com/dotnet/orleans/issues/8101
> Support `IGrainStorageSerializer` for memory grain storage

- src/Orleans.Core/Properties/AssemblyInfo.cs
- test/Extensions/Tester.Redis/Clustering/RedisMembershipTableTests.cs
- test/Extensions/Tester.Redis/CollectionFixtures.cs
- test/Extensions/Tester.Redis/GrainDirectory/RedisGrainDirectoryTests.cs
- test/Extensions/Tester.Redis/GrainDirectory/RedisMultipleGrainDirectoriesTests.cs
- test/Extensions/Tester.Redis/Persistence/RedisPersistenceGrainTests.cs
- test/Extensions/Tester.Redis/Persistence/RedisPersistenceSetupTests.cs
- test/Extensions/Tester.Redis/Persistence/RedisStorageTests.cs
- test/Extensions/Tester.Redis/Persistence/RedisStorageTestsOrleansSerializer.cs
- test/Extensions/Tester.Redis/Reminders/RedisReminderTableTests.cs
- test/Extensions/Tester.Redis/Utility/CommonFixture.cs
- test/TestInfrastructure/TestExtensions/Properties/AssemblyInfo.cs
- test/TesterInternal/Properties/AssemblyInfo.cs
- test/TesterInternal/StorageTests/CommonStorageTests.cs
- test/TesterInternal/StorageTests/CommonStorageUtilities.cs
This adds additional functional tests based on `CommonStorageTests` for the `RedisGrainStorage` provider.
@ReubenBond  These tests will currently fail as I have not fixed the issues they highlight in the `RedisGrainStorage` , as I know there are changes to that in PR #8261 and I wanted to avoid conflicts - we will need to rebase one of these PRs onto the other I presume?
> Add Redis storage tests based on CommonStorageTests

- Directory.Packages.props
- Bumped KubernetesClient to v10.0.16
- Bumped StackExchange.Redis to 2.6.90
- Bumped Newtonsoft.Json to v13.0.2
> [Maintenance] Bumping version of some external dependencies

- src/Orleans.Core/Diagnostics/Metrics/CatalogInstruments.cs
- src/Orleans.Core/Diagnostics/Metrics/InstrumentNames.cs
- src/Orleans.Core/Diagnostics/Metrics/MessagingInstruments.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Catalog/ActivationDirectory.cs
- src/Orleans.Runtime/Catalog/ActivationWorkingSet.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
This should resolve https://github.com/dotnet/orleans/issues/8279.
> Expose activation working set as a metric

- src/Orleans.Serialization.TestKit/FieldCodecTester.cs
- src/Orleans.Serialization/Buffers/Adaptors/PooledArrayBufferWriter.cs
- src/Orleans.Serialization/Serializers/CodecProvider.cs
- test/Orleans.Serialization.UnitTests/JsonSerializerTests.cs
- test/Orleans.Serialization.UnitTests/Models.cs
* `PooledArrayBufferWriter.AsMemory` was broken, breaking JSON serialization
* Added more test coverage (thank you to @andtii for the repro code)
* Fixed an F# serialization bug discovered after adding test coverage
Fixes #8252
> Fix `PooledArrayBufferWriter.AsMemory`

- src/Orleans.Core/Core/GrainInterfaceTypeToGrainTypeResolver.cs
> Fix `IGrainFactory.GetGrain<T>` for unimplemented generic interfaces

- test/Grains/BenchmarkGrainInterfaces/GrainStorage/IPersistentGrain.cs
- test/Grains/BenchmarkGrainInterfaces/Transaction/ILoadGrain.cs
Added GenerateSerializer and Id to Report class in IPerstentGrain.cs and ILoadGrain.cs so Benchmark map reduce runs.
> Fix Benchmark map Reduce 

- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Catalog/ActivationWorkingSet.cs
The current logic in `ActivationWorkingSet` will remove a grain from the working set if it is visited twice consecutively and was idle both times. This does not account for cases where the grain was busy between those visits. The improved logic in this PR uses the idle duration to cover the period and reduce the chance of a would-be active grain being evicted from the working set.
I also increased the scan interval, since 100ms is needlessly aggressive for what is essentially a rolling window.
> Improve accuracy and stability of `ActivationWorkingSet`

- src/Azure/Orleans.Streaming.AzureStorage/Storage/AzureQueueDataManager.cs
Backport of https://github.com/dotnet/orleans/pull/7508 to V3
Addresses unhandled intermittent 404 failure in DeleteQueueMessage as described in https://github.com/dotnet/orleans/issues/7461#issue-1093743910.
> [Backport] Add a catch block in Azure DeleteQueueMessage for 404 error (#7461) (#7508) 

- src/Orleans.Serialization/TypeSystem/RuntimeTypeNameParser.cs
- test/DefaultCluster.Tests/GenericGrainTests.cs
- test/Grains/TestGrainInterfaces/IGenericInterfaces.cs
- test/Grains/TestGrains/GenericGrains.cs
- test/NonSilo.Tests/RuntimeTypeNameFormatterTests.cs
Fixes #8330
This is a generics corner case which was stumping the type parser when parsing a formatted unconstructed generic type.
For example, this type would not round-trip successfully:
`typeof(List<>).MakeGenericType(typeof(Inner<>.Middle).MakeArrayType())`
Concretely, this behavior was being hit when compiling the grain manifest for a type like `IGenericArrayRegisterGrain<T>`, since the manifest would contain the implemented interfaces, which contains `IGenericRegisterGrain<T[]>` (with no concrete `T`):
``` C#
public interface IGenericRegisterGrain<T> : IGrainWithIntegerKey
{
Task Set(T value);
Task<T> Get();
}
public interface IGenericArrayRegisterGrain<T> : IGenericRegisterGrain<T[]>
{
}
```
The fix is to check that we are indeed looking at a formatted generic type, versus an …
> Fix type parsing of type names with generic array parameter

- src/Orleans.CodeGenerator/SyntaxGeneration/Identifier.cs
Fixes #7592
Filters out any non-alphanumeric/non-`_` character and prefixes assembly names with a `_` if they start with a digit.
Verified using [@asos-stefanzilik](https://github.com/asos-stefanzilik)'s repo: https://github.com/asos-stefanzilik/BenchmarkOrleansCodeGenIssueRepro
xref #8311 & #7751
> Fix assembly name sanitization in code generator

- src/Orleans.Analyzers/SyntaxHelpers.cs
- test/Grains/TestGrains/StuckGrain.cs
- test/TesterInternal/OrleansRuntime/StuckGrainTests.cs
Adds support to Orleans.Analyzers for generic attributes a new feature in C# 11.0.
Currently, if you use a generic attribute in your code, the the orleans analyzers will fail during the analysis phase and throw a "NotSupportedException" when encountering a usage of a generic attribute. This causes a AD0001 analysis error to appear.
A temporary work around for this is to simply use `<NoWarn>AD0001</NoWarn>` on the project. However, this can potentially hide other base level analyzer exception errors and is therefore not a long-term work around.
> Adds support to Orleans.Analyzers for generic attributes

- src/Orleans.Core.Abstractions/Core/IGrainObserver.cs
Observer interfaces have the same restrictions as grain interfaces
> Remove inaccurate note on observer method return types

- src/Orleans.Analyzers/SyntaxHelpers.cs
- test/Analyzers.Tests/AbstractPropertiesCannotBeSerializedAnalyzerTest.cs
This prevents the analyzers which use the `IsAttribute` syntax helper from throwing an exception when an aliased namespace is used. It also adds a few very simple tests to catch regression.
I've also changed the helper to a Try pattern so that an exception is never thrown.
This does mean the analyzer would silently miss some cases if new syntax is introduced, but I think blocking consuming projects from building is probably worse. Happy to undo though.
> Prevent analyzer exception on aliased attribute names

- src/Orleans.Core/Utils/ObserverManager.cs
When wiring up a sample with `IGrainObservers`, I discovered that when passing null values here results in very bad behavior downstream.
> ObserverManager: Guard against `null` in constructor

- src/Orleans.CodeGenerator/LibraryTypes.cs
- src/Orleans.CodeGenerator/Model/SerializableTypeDescription.cs
- src/Orleans.Serialization/Activators/DefaultActivator.cs
- src/Orleans.Serialization/ISerializableSerializer/DotNetSerializableCodec.cs
- src/Orleans.Serialization/ISerializableSerializer/ExceptionCodec.cs
See: https://github.com/dotnet/designs/pull/293
Move from `FormatterServices.GetUninitializedObject` to `RuntimeHelpers.GetUninitializedObject`. The former is implemented by the latter anyway.
> Migrate from `FormatterServices` to `RuntimeHelpers` in preparation for .NET 8

- src/Serializers/Orleans.Serialization.Protobuf/ProtobufCodec.cs
The `ProtobufCodec` will try to claim ownership of `IMessage` serialization. The result is an exception when trying to access the parser as it isn't a concrete class.
This PR will allow the `IMessage` interface serialization to instead be handled by another serializer (`AbstractTypeSerializer` by default).
It also adds a case `IMessage<T>` since `T` is the concrete type.
> Don't overstep on IMessage serialization

- src/Orleans.Core/Configuration/OptionLogger/DefaultOptionsFormatter.cs
The `new()` constraint is not required and can cause a crash during startup
> Fix type constraints on `DefaultOptionsFormatter` and `DefaultOptionsFormatterResolver`

- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorage.cs
- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureBlobStorageOptions.cs
- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/IBlobContainerFactory.cs
Allows blob containers to be customised based on grainType and grain id. This is wrapped in an interface to allow injection of dependencies and state to be maintained.
Fixes #7831
> Add a blob container client factory for customisation

- src/Orleans.Core/Utils/RandomTimeSpan.cs
> Use .NextInt64() when computing random TimeSpan.

- src/Orleans.Analyzers/GrainInterfaceMethodReturnTypeDiagnosticAnalyzer.cs
- test/Analyzers.Tests/GrainInterfaceMethodReturnTypeDiagnosticAnalyzerTest.cs
Fix for #8377 @ReubenBond 
Included accompanying test that now that passes.
> Fix: ORLEANS0009 - Skip Static Interface Methods

- src/Orleans.CodeGenerator/InvokableGenerator.cs
- src/Orleans.CodeGenerator/LibraryTypes.cs
- src/Orleans.CodeGenerator/Model/IGeneratedInvokerDescription.cs
- src/Orleans.CodeGenerator/Model/InvokableInterfaceDescription.cs
- src/Orleans.CodeGenerator/ProxyGenerator.cs
- src/Orleans.CodeGenerator/SyntaxGeneration/SymbolExtensions.cs
- src/Orleans.Core.Abstractions/Concurrency/GrainAttributeConcurrency.cs
- src/Orleans.Core.Abstractions/Orleans.Core.Abstractions.csproj
- src/Orleans.Core.Abstractions/Runtime/GrainReference.cs
- src/Orleans.Core.Abstractions/Runtime/IGrainReferenceRuntime.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
- src/Orleans.Core/Orleans.Core.csproj
- src/Orleans.Core/Runtime/ClientGrainContext.cs
- src/Orleans.Core/Runtime/GrainReferenceRuntime.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Core/HostedClient.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- src/Orleans.Serialization.Abstractions/Annotations.cs
- src/Orleans.Serialization/Invocation/Response.cs
- test/Grains/TestGrainInterfaces/TestGrainInterfaces.csproj
- test/Grains/TestGrains/TestGrains.csproj
- test/Orleans.Serialization.UnitTests/Orleans.Serialization.UnitTests.csproj
This PR adds support for extending the set of supported grain return types.
This allows us to support calling patterns beyond request-response. For example, `IAsyncEnumerable<T>`.
A subsequent PR will add initial support for returning `IAsyncEnumerable<T>` from grains, based on this functionality.
To use this, a developer would start by annotating a request base type with `[ReturnValueProxy(initializerMethodName)]`. Doing so prevents the code generator from relying on .NET's `AsyncMethodBuilder` to create the instances of the return type and instead allows the value returned from the method with the name specified by `initializerMethodName` to provide that value.
> Support custom grain call return types

- src/Orleans.Streaming/Predicates/RegexStreamNamespacePredicate.cs
> Fix parameter null check in RegexStreamNamespacePredicate

- src/Orleans.Reminders/GrainReminderExtensions.cs
- src/Orleans.Reminders/ReminderService/ReminderRegistry.cs
- test/TesterInternal/TimerTests/ReminderTests_Base.cs
In unit testing libraries (such as [OrleansTestKit](https://github.com/OrleansContrib/OrleansTestKit)) the `RuntimeContext` check for reminder-based grain calls proves very challenging.
Because `RuntimeContext` uses a thread-local mechanism, it becomes non-trivial to ensure the unit test runs on the same thread as the calling code (imagine some IO-bound async behavior happening between the unit test & the Reminder call)
This is related to some of the conversation going on in https://github.com/OrleansContrib/OrleansTestKit/issues/134
Also related to https://github.com/dotnet/orleans/issues/8387 - RuntimeContext hard to test
Move the `RuntimeContext` check into the `ReminderRegistry` so that it sits behind a stubbable testing seam interface instead of residing in an extension method.  This …
> Moving RuntimeContext check inside ReminderRegistry

- src/Orleans.Hosting.Kubernetes/ConfigureKubernetesHostingOptions.cs
- src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs
- src/Orleans.Hosting.Kubernetes/KubernetesHostingOptions.cs
- src/Orleans.Hosting.Kubernetes/KubernetesHostingOptionsValidator.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
This PR simplifies the procedure of using the `Microsoft.Orleans.Hosting.Kubernetes` package by automating more of the process. With this PR, users will no longer need to specify labels or environment variables in their pod specs.
It manages this by:
* Inferring pod name from `Environment.MachineName` if not configured via env vars
* Inferring pod namespace from `/var/run/secrets/kubernetes.io/serviceaccount/namespace` if not configured via env vars
* Updating labels on the pod spec during startup to match the internally configured (eg, default) `ServiceId` & `ClusterId` if they are not configured via labels
* Selecting the most appropriate PodIp based on the IANA private IPv4 address ranges if not configured via env vars
Additionally, it filters out non-`Active` members when performing …
> Automate more of the Kubernetes hosting experience

- src/Orleans.Serialization/TypeSystem/CachedTypeResolver.cs
This is a port of a PR 7851 from 3.7.X to orleans 7.
Currently when Orleans fails to load a type, the exception only contains information of missing assembly.
This PR catches exception on Assembly.Load and attach the failed type information in message so it is more helpful.
See an example issue  from #8450 and
the old PR from https://github.com/dotnet/orleans/pull/7851.
I just did a copy pas of @wangjia184 changes.
> Improve : throw TypeLoadException on failing to load a type

- src/Orleans.Core.Abstractions/Runtime/GrainReference.cs
This currently fails a debug assert for `void` methods
> Fix debug assert added for `void` methods: `VoidRequest` implies `OneWay`

- src/Orleans.Core/Hosting/OrleansClientGenericHostExtensions.cs
- src/Orleans.Core/Orleans.Core.csproj
- src/Orleans.Runtime/Hosting/OrleansSiloGenericHostExtensions.cs
- test/DefaultCluster.Tests/HostedClientTests.cs
- test/NonSilo.Tests/ClientBuilderTests.cs
- test/NonSilo.Tests/SiloBuilderTests.cs
In this PR (related to #8465):
- The _Orleans.Core.csproj_ now depends on `Microsoft.Extensions.Hosting`, instead of just the `Microsoft.Extensions.Hosting.Abstractions`.
- Exposed an `UseOrleans/UseOrleansClient` extension on the `HostApplicationBuilder` API.
- Update the unit tests to use the new extension, see _test/DefaultCluster.Tests/HostedClientTests.cs_.
- Use `ArgumentNullException.ThrowIfNull` in updated _src/Orleans.Runtime/Hosting/GenericHostExtensions.cs_.
> Added `HostApplicationBuilder` extensions

- src/Orleans.Core/Utils/ObserverManager.cs
I made a few adjustments:
- In the `Unsubscribe` method, I added a missing `if` clause with `_log.IsEnabled(LogLevel.Debug)` and moved the log message **after** the `Remove` call to ensure that the `Count` property gets updated correctly. Previously, the message could be misleading because it displayed the count before the removal.
- I addressed the [CA2253](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2253): Named placeholders should not be numeric values.
- I also added a `where TIdentity : notnull` constraint. Although nullable is not enabled, the `Dictionary` uses this constraint, so I applied it for consistency.
- Additionally, I replaced **{Observer}** with **{Id}** in one of the log message, as it aligns with the rest of the code and reflects …
> ObserverManager: nits

- src/Redis/Orleans.Clustering.Redis/Orleans.Clustering.Redis.csproj
- src/Redis/Orleans.GrainDirectory.Redis/Orleans.GrainDirectory.Redis.csproj
- src/Redis/Orleans.Persistence.Redis/Orleans.Persistence.Redis.csproj
- src/Redis/Orleans.Reminders.Redis/Orleans.Reminders.Redis.csproj
This PR marks the Redis providers as stable
> Mark Redis providers as stable

- src/Azure/Orleans.Clustering.AzureStorage/AzureTableClusteringExtensions.cs
- src/Azure/Orleans.Clustering.AzureStorage/Options/AzureStorageClusteringOptions.cs
- src/Azure/Orleans.Clustering.AzureStorage/Options/AzureStorageGatewayOptions.cs
- src/Azure/Orleans.GrainDirectory.AzureStorage/Hosting/AzureTableGrainDirectoryServiceCollectionExtensions.cs
- src/Azure/Orleans.GrainDirectory.AzureStorage/Options/AzureTableGrainDirectoryOptions.cs
- src/Azure/Orleans.Reminders.AzureStorage/AzureStorageReminderServiceCollectionExtensions.cs
- src/Azure/Orleans.Reminders.AzureStorage/Storage/AzureTableReminderStorageOptions.cs
- src/Azure/Orleans.Transactions.AzureStorage/Hosting/AzureTableTransactionServicecollectionExtensions.cs
- src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/AzureTableTransactionalStateOptions.cs
These validators surface configuration errors on-startup so that developers do not experience a confusing `NullReferenceException` later on.
> Add missing configuration validators for Azure Table Storage providers

- src/Orleans.Core/Statistics/SiloRuntimeStatistics.cs
- src/Orleans.Core/SystemTargetInterfaces/IDeploymentLoadPublisher.cs
- src/Orleans.Runtime/Placement/DeploymentLoadPublisher.cs
- src/Orleans.Runtime/Silo/SiloControl.cs
* `UpdateRuntimeStatistics` is a notification method and since we use it with `Task.WhenAll`, waiting for its completion before continuing can result in one (eg, dead) silo delaying others from receiving updates: a slow silo will prevent the next round of updates from being collected and sent. Additionally, we do not care if this method fails, so we do not need to track its completion. Therefore, I have marked the method `[OneWay]`.
* Statistics are ignored if they are not the latest, but we are using `DateTime.UtcNow`, so we are susceptible to clock changes. Setting the clock on a host backwards can prevent other hosts from applying updates for some period of time. Therefore, I changed the logic to use a monotonic clock which always proceeds on every cycle, even if the clock has been set …
> Improve DeploymentLoadPublisher logic and cleanup

- src/Orleans.Runtime/Silo/Watchdog.cs
In the application of our organization, we noticed sporadically some `.NET Runtime Platform stalled for...` warnings, even with very small GC object counts, so after a code review we suspect that the additional checks in `WatchdogHeartbeatTick` may be responsible for a false-positive GC delay.
> Fix for possible false-positive GC delays

- src/Orleans.Core/SystemTargetInterfaces/IRemoteGrainDirectory.cs
- src/Orleans.Runtime/GrainDirectory/AdaptiveDirectoryCacheMaintainer.cs
- src/Orleans.Runtime/GrainDirectory/GrainDirectoryCacheFactory.cs
- src/Orleans.Runtime/GrainDirectory/GrainDirectoryPartition.cs
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
There are some cases today where a grain directory/cache entry for a defunct silo can persist in 3.x, causing messages to be sent to silos which have since been evicted from membership and had their tombstone entries cleaned up from membership.
This PR adds some fixes to more eagerly clean up these entries and nullify them where possible.
> [3.x] Fix directory/cache validation for defunct silos

- src/Orleans.Analyzers/GrainInterfaceMethodReturnTypeDiagnosticAnalyzer.cs
- src/Orleans.Analyzers/GrainInterfacePropertyDiagnosticAnalyzer.cs
- src/Orleans.Analyzers/NoRefParamsDiagnosticAnalyzer.cs
- src/Orleans.Serialization/Hosting/SerializerConfigurationAnalyzer.cs
- test/Analyzers.Tests/GrainInterfaceMethodReturnTypeDiagnosticAnalyzerTest.cs
- test/Analyzers.Tests/GrainInterfacePropertyDiagnosticAnalyzerTest.cs
- test/Analyzers.Tests/NoRefParamsDiagnosticAnalyzerTest.cs
- test/DefaultCluster.Tests/CodeGenTests/IRuntimeCodeGenGrain.cs
Relax diagnostic analyzers for static members of grain interfaces. I.e. never issue `ORLEANS0002`, `ORLEANS0008` and `ORLEANS0009` for static members.
> Relax diagnostic analyzers for static members of grain interfaces

- src/Orleans.Serialization.TestKit/FieldCodecTester.cs
- src/Orleans.Serialization/Buffers/PooledBuffer.cs
- src/Orleans.Serialization/Buffers/Writer.cs
- test/Benchmarks/Serialization/MegaGraphBenchmark.cs
- test/Orleans.Serialization.UnitTests/PooledBufferTests.cs
#8508 included a defensive measure against a double-free bug which was triggered by improper (but intuitive!) use of `Writer<TBufferWriter>.Output`. The PR comments contain an explanation of the issue.
This PR this effectively reverts the defensive measure taken in #8508, replacing it with a `Debug.Assert`, and exposes `Output` as a mutable field directly, allowing for the intuitive (but incorrect) use which triggered the bug to be correct. It does expose a potential issue: developers would be free to re-assign the output buffer.
That could be an issue, so there is a doc comment warning against direct mutation, but we have no other protection against it. As this saga demonstrated, the issue is present already and possibly more nefarious/hidden.
> Expose Writer<>.Output directly instead of via property

- Directory.Packages.props
Azure Pipelines is recording the following security vulnerability:
CST-E has determined that this component is not generally safe to use.|Azure.Data.Tables 12.6.1                |Critical 
This PR updates that NuGet (and its dependent package Azure.Core. It also updates System.Data.SqlClient, which is being flagged in Visual Studio as a security risk.
> Security: Upgrade two NuGets (and one dependency) that have been flagged

- src/Orleans.Runtime/Catalog/ActivationMigrationManager.cs
- test/DefaultCluster.Tests/Migration/MigrationTests.cs
There is some test flakiness caused by a race in the grain migration process. This PR fixes that race by polling the grains to make sure that they enter an active or terminal state before returning from migration.
The second commit also fixes a test case issue. The issue is that telling a grain to migrate by calling `MigrateOnIdle` does not guarantee that subsequent messages will be enqueued instead of executed on the activation (i.e, migration is async). The fix is to check that we're dealing with a new activation before continuing with the test.
> Wait for migrating activations to become active or terminated

- src/Orleans.Core/Runtime/OutgoingCallInvoker.cs
- src/Orleans.Core/Utils/AsyncEnumerable.cs
- src/Orleans.Serialization.FSharp/FSharpCodecs.cs
- src/Orleans.Serialization/Codecs/ArrayCodec.cs
- src/Orleans.Serialization/Codecs/CollectionCodec.cs
- src/Orleans.Serialization/Codecs/DictionaryCodec.cs
- src/Orleans.Serialization/Codecs/GeneralizedValueTypeSurrogateCodec.cs
- src/Orleans.Serialization/Codecs/HashSetCodec.cs
- src/Orleans.Serialization/Codecs/ListCodec.cs
- src/Orleans.Serialization/Codecs/MultiDimensionalArrayCodec.cs
- src/Orleans.Serialization/Codecs/NullableCodec.cs
- src/Orleans.Serialization/Codecs/QueueCodec.cs
- src/Orleans.Serialization/Codecs/StackCodec.cs
- src/Orleans.Serialization/Codecs/TupleCodec.cs
- src/Orleans.Serialization/Serializers/SurrogateCodec.cs
- src/Orleans.Serialization/Serializers/ValueSerializer.cs
Static members in generic types are expensive, especially fields in singleton classes.
> Avoid static members in generic types

- src/Orleans.Serialization/Codecs/ConcurrentDictionaryCodec.cs
- src/Orleans.Serialization/Codecs/ConcurrentQueueCodec.cs
- src/Orleans.Serialization/Codecs/HashSetCodec.cs
- src/Orleans.Serialization/Codecs/MultiDimensionalArrayCodec.cs
- src/Orleans.Serialization/Codecs/QueueCodec.cs
- src/Orleans.Serialization/Codecs/ReadOnlyCollectionCodec.cs
- src/Orleans.Serialization/Codecs/ReadOnlyDictionaryCodec.cs
- src/Orleans.Serialization/Codecs/SortedDictionaryCodec.cs
- src/Orleans.Serialization/Codecs/SortedListCodec.cs
- src/Orleans.Serialization/Codecs/SortedSetCodec.cs
- src/Orleans.Serialization/Codecs/StackCodec.cs
- src/Orleans.Serialization/Codecs/TupleCodec.cs
- src/Orleans.Serialization/GeneratedCodeHelpers/OrleansGeneratedCodeHelper.cs
- src/Orleans.Serialization/ISerializableSerializer/SerializationCallbacksFactory.cs
- src/Orleans.Serialization/Serializer.cs
- src/Orleans.Serialization/Serializers/CodecProvider.cs
- src/Orleans.Serialization/Serializers/ConcreteTypeSerializer.cs
- src/Orleans.Serialization/Serializers/SurrogateCodec.cs
Follow-up for https://github.com/dotnet/orleans/pull/8526#discussion_r1254881749
Instance field access is fast, unlike getting types potentially through lookups from generic type parameters.
> Lift typeof(T) to an instance field where possible

- src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs
- src/AdoNet/Shared/Storage/IRelationalStorage.cs
- src/AdoNet/Shared/Storage/RelationalStorage.cs
- src/AdoNet/Shared/Storage/RelationalStorageExtensions.cs
- src/Orleans.Core/Async/TaskExtensions.cs
- src/Orleans.Reminders/ReminderService/LocalReminderService.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Silo/Silo.cs
- src/Orleans.Transactions.TestKit.Base/FaultInjection/ControlledInjection/FaultInjectionTransactionState.cs
- src/Orleans.Transactions/State/TransactionalState.cs
- test/Extensions/TesterAdoNet/StorageTests/RelationalStoreTests.cs
Hi friends from Orleans,
Taking on one class of IDE warning at a time, this PR moves the CancellationToken argument to the end of the signature for methods not in the public API (internal and private only).
> Move CancellationToken arguments to the end

- src/Orleans.Runtime/Activation/IGrainContextActivator.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- test/Grains/TestGrainInterfaces/IReentrancyGrain.cs
- test/Grains/TestGrains/ReentrantGrain.cs
- test/TesterInternal/MessageScheduling/DisabledCallChainReentrancyTestRunner.cs
- test/TesterInternal/MessageScheduling/DisabledCallChainReentrancyTests.cs
- test/TesterInternal/MessageScheduling/ReentrancyTests.cs
> Added support for instanced versions of MayInterleave predicates

- test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs
- test/NonSilo.Tests/Serialization/SerializationTests.DifferentTypes.cs
I noticed these while doing #8565. 
These were flagged because of #3531 but since Orleans now only targets net7.0+ this should be able to be un-skipped.
> Un-Skip ValueTuple tests

- src/Orleans.Core.Abstractions/IDs/GrainId.cs
- test/NonSilo.Tests/General/Identifiertests.cs
While working on a client library I noticed that `GrainId` was not `ISpanParsable` but it did have implementations for parsing from a string.
This adds the interface and makes the existing string parse methods conform with the `IParsable` interface too.
Adding as draft as I need to check if some unit tests need to be added for this.
> Add ISpanParsable on to GrainId

- src/Azure/Orleans.GrainDirectory.AzureStorage/AzureTableGrainDirectory.cs
- src/Azure/Shared/Storage/AzureTableDataManager.cs
- src/Orleans.Core.Abstractions/GrainDirectory/IGrainDirectory.cs
- src/Redis/Orleans.GrainDirectory.Redis/RedisGrainDirectory.cs
I noticed that during #7692 the nullable pragma was added to `IGrainDirectory` which now had incorrect semantics exposed.
I updated the obvious implementers of this interface to what I hope is the correct nullable values.
I wasn't sure how `ILocalGrainDirectory` plays into this since it doesn't implement the interface and so wanted to open a PR to start a conversation over it.
> Update nullability on IGrainDirectory and implementers.

- Directory.Packages.props
The focus of these changes is to bump the reference for `Azure.Messaging.EventHubs` to the latest version.   There have been a number of fixes and enhancements in the 9 months since the previously version was released.  Of particular note, there were two important fixes in the AMQP transport library which could cause corruption in the connection state until the process was restarted.  
No breaking changes were made to the Event Hubs library in this time.
- [Event Hubs Changelog](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.EventHubs_5.9.2/sdk/eventhub/Azure.Messaging.EventHubs/CHANGELOG.md)
> [Dependencies] Bump Event Hubs version

- src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs
- test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs
When a grain directory experiences high latency it's possible that we hold a bad cached value in memory longer than desired. This can result in silos that retry due to NonExistantActivation exceptions continuing to retry to the same silo that does not own a grain. Instead, if we remove from the local cache first no matter how long the Unregister takes other calls will be able to re-read the grain directory to find the new grain location.
> CachedGrainLocator Unregister Ordering

- Directory.Packages.props
The arguments to .ListNamespacedPodAsync() have changed.
> Update the KubernetesClient NuGet package.

- src/Orleans.Core/GrainDirectory/IDhtGrainDirectory.cs
- src/Orleans.Runtime/Catalog/GrainTypeSharedContext.cs
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
- src/Orleans.Runtime/GrainDirectory/RemoteGrainDirectory.cs
- test/NonSilo.Tests/Directory/MockLocalGrainDirectory.cs
Changing the signature of `RegisterAsync` was a breaking change, so this PR adds the original signature back as an overload.
> Fix wire break for IRemoteGrainDirectory API

- src/Orleans.Streaming/Core/IStreamIdMapper.cs
- src/Orleans.Streaming/Predicates/StreamSubscriptionAttributes.cs
> Allow `ImplicitStreamSubscriptionAttribute.StreamIdMapper` to be initialized by subclasses

- src/Orleans.CodeGenerator/InvokableGenerator.cs
- src/Orleans.CodeGenerator/LibraryTypes.cs
- src/Orleans.CodeGenerator/Model/MethodDescription.cs
- src/Orleans.Core.Abstractions/Runtime/GrainReference.cs
- src/Orleans.Core/Runtime/CallbackData.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- src/Orleans.Serialization.Abstractions/Annotations.cs
- src/Orleans.Serialization/Invocation/IInvokable.cs
- test/DefaultCluster.Tests/EchoTaskGrainTests.cs
- test/Grains/TestGrainInterfaces/IEchoTaskGrain.cs
- test/Grains/TestInternalGrains/EchoTaskGrain.cs
- test/Orleans.Serialization.UnitTests/Request.cs
> Support specifying timeouts on a per-grain-call basis

- src/AdoNet/Orleans.Persistence.AdoNet/Migrations/PostgreSQL-Persistence-3.6.0.sql
- src/AdoNet/Orleans.Persistence.AdoNet/MySQL-Persistence.sql
- src/AdoNet/Orleans.Persistence.AdoNet/Oracle-Persistence.sql
- src/AdoNet/Orleans.Persistence.AdoNet/PostgreSQL-Persistence.sql
- src/AdoNet/Orleans.Persistence.AdoNet/SQLServer-Persistence.sql
- src/AdoNet/Orleans.Reminders.AdoNet/MySQL-Reminders.sql
- src/AdoNet/Orleans.Reminders.AdoNet/Oracle-Reminders.sql
- src/AdoNet/Orleans.Reminders.AdoNet/PostgreSQL-Reminders.sql
- src/AdoNet/Orleans.Reminders.AdoNet/SQLServer-Reminders.sql
- src/AdoNet/Shared/MySQL-Main.sql
- src/AdoNet/Shared/Oracle-Main.sql
- src/AdoNet/Shared/PostgreSQL-Main.sql
- src/AdoNet/Shared/SQLServer-Main.sql
- src/Azure/Orleans.Streaming.AzureStorage/Providers/Lease/AzureBlobLeaseProvider.cs
- src/Azure/Orleans.Streaming.AzureStorage/Storage/AzureQueueDataManager.cs
- src/Azure/Shared/Cosmos/CosmosOptions.cs
- src/Azure/Shared/Storage/AzureTableUtils.cs
- test/Grains/TestGrains/SimpleObserverableGrain.cs
Supersedes part of https://github.com/dotnet/orleans/pull/8471
> Replace all out of date links, and remove locale segment

- src/Azure/Shared/Storage/AzureTableDataManager.cs
- src/Orleans.Core/Async/AsyncExecutorWithRetries.cs
- src/Orleans.Runtime/Catalog/ActivationCollector.cs
- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
- src/Orleans.TestingHost/Utils/TestingUtils.cs
- src/Orleans.Transactions.TestKit.Base/Consistency/ConsistencyTestHarness.cs
- src/Orleans.Transactions.TestKit.Base/TestRunners/TransactionRecoveryTestsRunner.cs
- src/Orleans.Transactions/State/ReaderWriterLock.cs
- src/Orleans.Transactions/State/TransactionalState.cs
- src/Orleans.Transactions/TOC/TransactionCommitter.cs
- test/Benchmarks/GrainStorage/GrainStorageBenchmark.cs
- test/Extensions/Consul.Tests/ConsulClusteringOptionsTests.cs
- test/Extensions/ServiceBus.Tests/TestStreamProviders/EHStreamProviderForMonitorTests.cs
- test/Extensions/TesterAzureUtils/AsyncPipelineTests.cs
- test/Grains/TestInternalGrains/ActivateDeactivateTestGrain.cs
- test/Grains/TestInternalGrains/StreamingGrain.cs
- test/NonSilo.Tests/Membership/MembershipAgentTests.cs
- test/NonSilo.Tests/Membership/SiloHealthMonitorTests.cs
- test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerAdvancedTests_Set2.cs
- test/NonSilo.Tests/SchedulerTests/OrleansTaskSchedulerBasicTests.cs
- test/TesterInternal/ActivationsLifeCycleTests/ActivationCollectorTests.cs
- test/TesterInternal/General/RequestContextTest.cs
- test/TesterInternal/GeoClusterTests/BasicLogTestGrainTests.cs
- test/TesterInternal/StorageTests/PersistenceGrainTests.cs
- test/TesterInternal/StreamingTests/SingleStreamTestRunner.cs
Supersedes part of https://github.com/dotnet/orleans/pull/8471
> Fix all IDE0039 warnings, prefer local functions

- src/Orleans.Runtime/Core/GrainRuntime.cs
- src/Orleans.Runtime/Facet/Persistent/PersistentStateStorageFactory.cs
- src/Orleans.Runtime/Storage/StateStorageBridge.cs
- src/Orleans.Streaming/PubSub/PubSubRendezvousGrain.cs
- src/Orleans.Transactions/State/NamedTransactionalStateStorageFactory.cs
- src/Orleans.Transactions/State/TransactionalStateStorageProviderWrapper.cs
- test/Grains/TestGrainInterfaces/IPersistenceTestGrains.cs
- test/Grains/TestInternalGrains/PersistenceTestGrains.cs
- test/TesterInternal/StorageTests/PersistenceGrainTests.cs
> Update state storage to use IActivator<T> instead of Activator.CreateInstance to handle unserializable types

- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/GrainDirectory/GrainDirectoryResolver.cs
- src/Orleans.Runtime/GrainDirectory/GrainLocatorResolver.cs
- test/NonSilo.Tests/Directory/GrainLocatorResolverTests.cs
Fix #8632
`HasNonDefaultDirectory` was used to check if the directory was the default builtin (DHT) directory but was causing some logic issue when the default directory was overridden during config.
I renamed the method name and changed the logic, so it returns `true` only if the DHT directory is used for the target grain type.
> In GrainDirectoryResolver, replace HasNonDefaultDirectory with IsUsingDhtDirectory

- src/Orleans.Runtime/Configuration/Validators/SiloClusteringValidator.cs
- test/NonSilo.Tests/SiloBuilderTests.cs
xref #8678
Ensures that:
* `ClusterMembershipOptions.NumVotesForDeathDeclaration` <= `ClusterMembershipOptions.NumProbedSilos`
* `ClusterMembershipOptions.NumVotesForDeathDeclaration` > `0`
> Ensure that `ClusterMembershipOptions.NumVotesForDeathDeclaration` is not greater than `NumProbedSilos` on startup

- src/Orleans.Core/Configuration/CollectionAgeLimitAttribute.cs
- test/DefaultCluster.Tests/EchoTaskGrainTests.cs
- test/Grains/TestInternalGrains/EchoTaskGrain.cs
> Fix regression in `CollectionAgeLimitAttribute`

- src/AdoNet/Orleans.Clustering.AdoNet/Messaging/AdoNetClusteringTable.cs
- src/Azure/Orleans.Clustering.AzureStorage/AzureBasedMembershipTable.cs
- src/Orleans.Core.Abstractions/Manifest/MajorMinorVersion.cs
- src/Orleans.Core/Manifest/ClientClusterManifestProvider.cs
- src/Orleans.Core/SystemTargetInterfaces/IMembershipTable.cs
- src/Orleans.Core/Utils/AsyncEnumerable.cs
- src/Orleans.Runtime/Manifest/ClusterManifestProvider.cs
- src/Orleans.Runtime/MembershipService/ClusterMembershipService.cs
- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
- test/DefaultCluster.Tests/AsyncEnumerableGrainCallTests.cs
- test/DefaultCluster.Tests/BasicActivationTests.cs
- test/Grains/TestGrainInterfaces/ITestGrain.cs
- test/NonSilo.Tests/Directory/MockClusterMembershipService.cs
- test/TesterInternal/MembershipTests/MembershipTableTestsBase.cs
When publishing cluster membership updates to local subscribers, we currently have clauses which allow overwriting the cluster membership snapshot with an initial version, but this is not necessary and can introduce bugs, since several of the consumers expect cluster membership to be monotonically versioned.
> Prevent progress reversal in cluster membership

- src/Orleans.Core/Messaging/InvalidMessageFrameException.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
- src/Orleans.Core/Networking/Connection.cs
- test/NonSilo.Tests/Serialization/MessageSerializerTests.cs
This fixes an issue which was preventing connections from being closed when invalid framing was encountered.
> Close connection when invalid framing is detected

- src/Azure/Orleans.Persistence.Cosmos/CosmosGrainStorage.cs
- src/Azure/Orleans.Persistence.Cosmos/CosmosStorageOptions.cs
- src/Azure/Orleans.Reminders.Cosmos/CosmosReminderTable.cs
- src/Azure/Shared/Cosmos/CosmosOptions.cs
Allows customization of the retry logic used by Cosmos DB grain persistence and reminder storage.
Sets `CosmosOptions.ClientOptions` by default.
> Cosmos DB: allow customization of retry logic

- src/Azure/Orleans.Persistence.Cosmos/CosmosGrainStorage.cs
- src/Azure/Orleans.Persistence.Cosmos/HostingExtensions.cs
- src/Orleans.Core/Utils/KeyedService.cs
> Cosmos DB: support custom partition key value providers

- src/Orleans.Core.Abstractions/IDs/GrainAddress.cs
- src/Orleans.Core.Abstractions/IDs/GrainAddressCacheUpdate.cs
- src/Orleans.Core/GrainDirectory/IGrainLocator.cs
- src/Orleans.Core/Messaging/Message.cs
- src/Orleans.Core/Messaging/MessageSerializer.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- src/Orleans.Runtime/GrainDirectory/AdaptiveGrainDirectoryCache.cs
- src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs
- src/Orleans.Runtime/GrainDirectory/ClientGrainLocator.cs
- src/Orleans.Runtime/GrainDirectory/DhtGrainLocator.cs
- src/Orleans.Runtime/GrainDirectory/GrainLocator.cs
- src/Orleans.Runtime/GrainDirectory/ILocalGrainDirectory.cs
- src/Orleans.Runtime/GrainDirectory/LRUBasedGrainDirectoryCache.cs
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
- src/Orleans.Runtime/Messaging/MessageCenter.cs
- src/Orleans.Runtime/Networking/SiloConnection.cs
- src/Orleans.Runtime/Placement/PlacementService.cs
- test/NonSilo.Tests/Directory/MockLocalGrainDirectory.cs
- test/NonSilo.Tests/Serialization/MessageSerializerTests.cs
Addresses https://github.com/dotnet/orleans/issues/8646 as described in https://github.com/dotnet/orleans/issues/8646#issuecomment-1787620237
* Consistently invalidate cache entries via `GrainLocator`, rather than via `ILocalGrainDirectory`
* When invalidating cache entries, allow updated cache values to be specified. For example, when a grain loses the activation race, rather than merely invalidating the cache on the target silo, update it to include the successfully registered address. This reduces potential load on the directory.
* When removing an entry from the cache, only consider the `GrainId` and `SiloAddress` (if present), not the `ActivationId`.
* Test for backwards & forwards compatibility of `CacheInvalidationHeader` change
> Improve grain directory cache consistency

- src/Azure/Orleans.Persistence.Cosmos/CosmosGrainStorage.cs
Currently, when `DeleteStateOnClear` is set, deleting state which is expected to not exist (eg, deleting state twice in succession) is a no-op. Instead, for consistency, we should perform a read when state is expected to not exist.
> Cosmos DB: perform read for consistency when deleting state which is expected to not exist

- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/Messaging/MessageCenter.cs
- test/Grains/TestGrainInterfaces/ITestGrain.cs
- test/Grains/TestInternalGrains/TestGrain.cs
- test/TesterInternal/GrainLocatorActivationResiliencyTests.cs
This PR fixes an issue where activation fails repeatedly during directory registration because the grain directory contains an existing entry for a different activation on the same silo. The fix handles this case by retrying registration, passing the previous address so that the registration will be updated instead of rejected.
> Nullify directory entries of defunct local predecessors during grain activation

- src/Orleans.Core.Abstractions/Runtime/GrainReference.cs
- src/Orleans.Runtime/Services/GrainService.cs
- test/Orleans.Serialization.UnitTests/Request.cs
Currently, we obscure the stack in too many places.
In future (up for grabs!), it would likely be better for us to use:
* [`[DebuggerStepThrough]`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerstepthroughattribute?view=net-7.0), and/or
* [`[DebuggerNonUserCode]`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggernonusercodeattribute?view=net-7.0) & [`[DebuggerStepperBoundary]`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerstepperboundaryattribute?view=net-7.0)
> Avoid hiding the stack of exceptions thrown from user code

- src/Orleans.Core/Core/GrainInterfaceTypeToGrainTypeResolver.cs
- src/Orleans.Core/IDs/GenericGrainInterfaceType.cs
- src/Orleans.Core/IDs/GenericGrainType.cs
- src/Orleans.Core/Manifest/GrainTypeResolver.cs
- src/Orleans.Core/Utils/TypeConverterExtensions.cs
- test/DefaultCluster.Tests/GenericGrainTests.cs
- test/Grains/TestGrains/GenericGrains.cs
Throws earlier when trying to construct a generic type using types from another generic type with different arity.
Enables previously skipped "generic corner case" tests for scenarios which are now supported.
General cleanup of the relevant test code.
> Improve error checking around constructing and parsing generic grain types and clean up tests

- src/Orleans.Serialization/Buffers/Reader.cs
- test/Orleans.Serialization.UnitTests/ReaderWriterTests.cs
Fix bug in Reader skip. When the skip count + current position is 1 >than the current buffer size, skip will "overread" the buffer, setting the position to a point > the buffer size.
This causes the next read to advance the buffer and consume the first byte which the skip should have already consumed but didn't.
> Fix overread bug in Reader Skip

- src/Orleans.Runtime/Catalog/ActivationData.cs
grain.DelayDeactivation(Timeout.InfiniteTimeSpan) work incorrect
> Support Timeout.InfiniteTimeSpan in grain delay deactivation

- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
Fixes #8655
This expands on the condition added in #5747, so that silos do not retry attempts to update the membership table during shutdown when using development clustering. Previously, we were only checking for the terminal state (`Dead`), but this expands it to all terminal states (`ShuttingDown`, `Stopping`, and `Dead`)
> Do not retry membership updates during shutdown with dev clustering

- src/Orleans.Core.Abstractions/Runtime/RequestContext.cs
- test/DefaultCluster.Tests/RequestContextTest.cs
> Enable enumeration of the keys and entries in RequestContext (#8674)

- test/Tester/OneWayDeactivationTests.cs
This test is flaky now because of a change in cache invalidation logic, but the current behavior is correct.
What we want to check is that the cache was updated to reflect the grain being re-activated, possibly on a new silo
> Fix flaky OneWay_Deactivation_CacheInvalidated test

- src/Orleans.CodeGenerator/Model/SerializableTypeDescription.cs
- src/Orleans.Serialization/Exceptions.cs
- src/Orleans.Serialization/ISerializableSerializer/ExceptionCodec.cs
- src/Orleans.Serialization/Serializers/SurrogateCodec.cs
- test/Orleans.Serialization.UnitTests/GeneratedSerializerTests.cs
- test/Orleans.Serialization.UnitTests/ISerializableTests.cs
- test/Orleans.Serialization.UnitTests/Models.cs
- test/Orleans.Serialization.UnitTests/PolymorphismTests.cs
This adds the two suggestions @ReubenBond makes in [this issue](https://github.com/dotnet/orleans/issues/8628#issuecomment-1714199599).
When we have an `Exception`-derived type that has been serialized as a reference, we should throw an exception when trying to deserialize it with the `ExceptionCodec`, rather than silently returning `null` in it's place.
This scenario could (prior to this PR) come about when an exception is serialized using the code-gen serializer - say you add `[GenerateSerializer]` for your custom exception type, which is valid if you have certain fields you need serialized -, but this is stored in a field of type `Exception`. In that case, the code-gen serializer would by default (absent the `SuppressReferenceTrackingAttribute`) serialize the exception as a reference …
> Throw when deserializing Exceptions by reference, and avoid reference tracking for all Exception-derived types (#8628)

- src/Orleans.Core/Utils/LRU.cs
- test/NonSilo.Tests/General/LruTest.cs
> Correctly count number of items in LRU

- src/Orleans.Runtime/Catalog/ActivationCollector.cs
1) now1: var now = DateTime.UtcNow; at ScanStale (ActivationCollector line 214)
2) now2: DateTime.UtcNow at MakeTicketFromTimeSpan (ActivationCollector line 364)
if now2 > now1 and activation.KeepAliveUntil == DateTime.MaxValue  - we have exception (System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime. (Parameter 't'))
> Fix exception while collecting activations

- src/Orleans.CodeGenerator/SyntaxGeneration/FSharpUtils.cs
- test/DefaultCluster.Tests/SerializationTests/SerializationTests.cs
- test/Grains/TestFSharp/Types.fs
Unlike discriminated unions with more than two cases, single case discriminated unions do not inherit from an abstract base class, thus, for single case discriminated unions we need to look for the CompilationMappingAttribute on the type itself.
Single case discriminated unions do have a declared instance member named "Item", so the `FSharpUnionCaseTypeDescription` [correctly identifies this](https://github.com/dotnet/orleans/blob/main/src/Orleans.CodeGenerator/SyntaxGeneration/FSharpUtils.cs#L110).
Fixes #8715
> Identify F# single case discriminated unions as SumType

- src/AWS/Shared/Storage/DynamoDBClientOptions.cs
Hey, really appreciate the work on this amazing package. I was recently trying to set it up and was quite confused why `Service` is used to denote the AWS region name, and the only reference I could find explaining it was:
https://learn.microsoft.com/en-us/dotnet/orleans/grains/grain-persistence/dynamodb-storage#configuration
I added the comment for more context and hope it can help to make the configuration options clearer for others!
> chore: update dynamodb client options `Service` comment

- src/Orleans.Runtime/Catalog/ActivationCollector.cs
> [7.x] Fix exception while collecting activations when activation.KeepAliveUntil = DateTime.MaxValue (#8740)

- src/Orleans.CodeGenerator/SyntaxGeneration/FSharpUtils.cs
- test/DefaultCluster.Tests/SerializationTests/SerializationTests.cs
- test/Grains/TestFSharp/Types.fs
> [7.x] Identify F# single case discriminated unions as SumType (#8739)

- src/Orleans.Runtime/Placement/PlacementService.cs
With the current configuration, it's possible for `PlacementService.PlacementWorker.ProcessLoop()` to resume execution on an unintended scheduler, which can have unintended consequences. This PR fixes that. I noticed this as test flakiness when certain tests were run in conjunction with each other.
> Prevent PlacementWorker.ProcessLoop from running on foreign schedulers

- src/Orleans.Serialization.TestKit/CopierTester.cs
- src/Orleans.Serialization/Codecs/ImmutableSortedDictionaryCodec.cs
- src/Orleans.Serialization/Codecs/ImmutableStackCodec.cs
- src/Orleans.Serialization/Codecs/SortedListCodec.cs
- src/Orleans.Serialization/Codecs/ValueTupleCodec.cs
- test/Orleans.Serialization.UnitTests/BuiltInCodecTests.cs
As evidenced by #8766 (PR: #8768), not all codecs & copiers have tests currently.
Hence, this PR adds tests for the missing codecs & copiers, fixes the issues which doing so uncovered, and adds an additional test which checks that all built-in codecs & copiers have tests.
> Ensure that all in-built codecs and copiers have corresponding tests, fix issues found

- src/Orleans.CodeGenerator/CodeGenerator.cs
> Avoid generating IActivator<T> for abstract types

- src/Orleans.Core.Abstractions/Manifest/ClusterManifest.cs
- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Core/InterfaceToImplementationMappingCache.cs
- src/Orleans.Core/Manifest/ClientClusterManifestProvider.cs
- src/Orleans.Core/Manifest/ClientManifestProvider.cs
- src/Orleans.Core/Manifest/GrainVersionManifest.cs
- src/Orleans.Core/Manifest/IClusterManifestProvider.cs
- src/Orleans.Core/Manifest/IClusterManifestSystemTarget.cs
- src/Orleans.Core/Messaging/ClientMessageCenter.cs
- src/Orleans.Core/Runtime/LocalClientDetails.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Core/Utils/StandardExtensions.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- src/Orleans.Runtime/GrainTypeManager/ClusterManifestSystemTarget.cs
- src/Orleans.Runtime/Manifest/ClusterManifestProvider.cs
- test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs
> Avoid sending cluster manifest to client if client already has the latest version

- src/Orleans.Core/Manifest/ClientClusterManifestProvider.cs
- src/Orleans.Core/Manifest/IClusterManifestSystemTarget.cs
There was no newer cluster manifest, so wait for the next refresh interval and try again.
GetClusterManifestUpdate() may be return null  and needs to be processed.
> ClientClusterManifestProvider: fix case where gateway returns no update

- src/Orleans.Core.Abstractions/Manifest/ClusterManifest.cs
- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Core/InterfaceToImplementationMappingCache.cs
- src/Orleans.Core/Manifest/ClientClusterManifestProvider.cs
- src/Orleans.Core/Manifest/ClientManifestProvider.cs
- src/Orleans.Core/Manifest/GrainVersionManifest.cs
- src/Orleans.Core/Manifest/IClusterManifestProvider.cs
- src/Orleans.Core/Manifest/IClusterManifestSystemTarget.cs
- src/Orleans.Core/Messaging/ClientMessageCenter.cs
- src/Orleans.Core/Runtime/LocalClientDetails.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Core/Utils/StandardExtensions.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- src/Orleans.Runtime/GrainTypeManager/ClusterManifestSystemTarget.cs
- src/Orleans.Runtime/Manifest/ClusterManifestProvider.cs
- test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs
Backport of #8728
cc @453873 @HermesNew if you want a 7.x version of the PR to try, try this one
> [7.x] Avoid resending unchanged ClusterManifest to clients

- src/Orleans.Core/Diagnostics/Metrics/GrainInstruments.cs
Fix for #8753
UpDownCounter and Counter have the same implementation but they are interpreted differently by the .Net OTel SDK. UpDownCounter supports reporting negative values and is suitable to keep track of the number of active grains per type. The metric will be exported by the OTel SDK as a cumulative value instead of a delta for Counter.
> Use UpDownCounter for grain and system target counts

- src/Orleans.Persistence.Memory/Storage/MemoryStorage.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
> Reduce logging noise from MemoryStorage, InsideRuntimeClient, and LocalGrainDirectory

- src/Orleans.Serialization/TypeSystem/CompoundTypeAliasTree.cs
> Fixes duplicate code-gen for `CompoundTypeAliasTree` with isolated base interface(s)

- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Core/IClientConnectionRetryFilter.cs
> Adds `LinearBackoffClientConnectionRetryFilter` in the default client services

- src/Orleans.Core/Manifest/ClientClusterManifestProvider.cs
- src/Orleans.Core/Messaging/GatewayManager.cs
- test/TesterInternal/GatewaySelectionTest.cs
> Avoid constant try/catch on a non-existing gateway for external cluster client

- src/Orleans.Analyzers/AliasClashAttributeAnalyzer.cs
- src/Orleans.Analyzers/AliasClashAttributeCodeFix.cs
- src/Orleans.Analyzers/AnalyzerReleases.Shipped.md
- src/Orleans.Analyzers/Constants.cs
- src/Orleans.Analyzers/GenerateAliasAttributesAnalyzer.cs
- src/Orleans.Analyzers/IdClashAttributeAnalyzer.cs
- src/Orleans.Analyzers/IncorrectAttributeUseAnalyzer.cs
- src/Orleans.Analyzers/IncorrectAttributeUseCodeFix.cs
- src/Orleans.Analyzers/Resources.Designer.cs
- src/Orleans.Analyzers/Resources.resx
- src/Orleans.Analyzers/SyntaxHelpers.cs
- test/Analyzers.Tests/AliasClashAttributeAnalyzerTest.cs
- test/Analyzers.Tests/DiagnosticAnalyzerTestBase.cs
- test/Analyzers.Tests/GenerateAliasAttributesAnalyzerTest.cs
- test/Analyzers.Tests/IdClashAttributeAnalyzerTest.cs
- test/Analyzers.Tests/IncorrectAttributeUseAnalyzerTest.cs
cc @ReubenBond 
close #8661 
Analyzer:
Fixer:
Tests:
> Add Analyzer and CodeFix for duplicate method aliases (ORLEANS0011)

- src/AdoNet/Orleans.Clustering.AdoNet/Migrations/SQLServer-Clustering-3.7.0.sql
- src/AdoNet/Orleans.Clustering.AdoNet/SQLServer-Clustering.sql
- src/AdoNet/Orleans.Persistence.AdoNet/SQLServer-Persistence.sql
- src/AdoNet/Orleans.Reminders.AdoNet/SQLServer-Reminders.sql
- src/AdoNet/Shared/SQLServer-Main.sql
Multiple execution of .sql scripts during the first startup of software with multiple replicas causes primary key violations and existing table errors.
For example: scripts may be executed via sqlcmd within initcontainer during deployment, if the software has more than one replica they will run multiple times, one per replica.
Add a check that checks whether objects (tables, indexes and queries) already exist before creating them.
- https://github.com/dotnet/orleans/issues/8676#issuecomment-1778993297
> Make repeatable the execution of SQLServer Ado scripts without errors

- src/Orleans.Analyzers/GenerateAliasAttributesAnalyzer.cs
> `GenerateAliasAttribtuesAnalyzer` needs to account for file-scoped namespaces

- .azure/pipelines/build.yaml
- .azure/pipelines/nightly-main.yaml
- .azure/pipelines/templates/build.yaml
- .azure/pipelines/templates/vars.yaml
This adds a CI pipeline which publishes nightly builds of Orleans from the main branch.
- We cannot specify parameters or variables in YAML schedules, therefore we need something else.
- To avoid duplicating the main pipeline yaml, I moved the guts of `build.yaml` into a template, `templates/build.yaml` and reference that from the root `build.yaml`.
- Since templates cannot have schedules or triggers, those go into the base `build.yaml` as well as the template, and they're passed through explicitly as template parameters.
- `nightly-main.yaml` contains the nightly build publishing pipeline and it references `templates/build.yaml`, setting a `publish_nightly` parameter.
- Since you apparently cannot specify variables in templates which also have jobs, the variables go into …
> Add nightly feed publishing

- Directory.Packages.props
Builds are failing due to:
`Error NU1903: Warning As Error: Package 'System.Data.SqlClient' 4.8.5 has a known high severity vulnerability, https://github.com/advisories/GHSA-98g6-xh36-x2p7`
PR bumps version of 'System.Data.SqlClient' 4.8.**6**
> Upgrade `System.Data.SqlClient`

- src/Orleans.Core.Abstractions/Statistics/IEnvironmentStatisticsProvider.cs
- src/Orleans.Core/Statistics/EnvironmentStatistics.cs
- src/Orleans.Runtime/Placement/ActivationCountPlacementDirector.cs
- src/Orleans.Runtime/Placement/ResourceOptimizedPlacementDirector.cs
The cooperative dual-mode Kalman filtering is moved from `ResourceOptimizedPlacementDirector` to `EnvironmentStatisticsProvider`, this achieves 3 things:
1. Centralizes the filtering logic of the `EnvironmentStatistics` so when they are published, every receiver already has the filtered data.
2. Allows not only for `ResourceOptimizedPlacementDirector` but also `ActivationCountPlacementDirector` and `OverloadDetector` to make use of the filtered data.
3. Reduces the need to allocate **(N + n)<sup>2</sup>** filters to **N**.
Where **N** is the number of silos, and **n** is the number of components within a silo, that may decide to use the data.
For example: `ResourceOptimizedPlacementDirector, ActivationCountPlacementDirector, OverloadDetector`, potentially others 
in the future.
> Centralize environment statistics filtering

- src/Orleans.Core/Core/DefaultClientServices.cs
- src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
This is prompted by the Aspire integration, where we want distributed tracing enabled by default during development time
> Add support for enabling distributed tracing via configuration switch

- src/Orleans.Runtime/Catalog/ActivationMigrationManager.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Serialization/Codecs/ByteArrayCodec.cs
- test/DefaultCluster.Tests/Migration/MigrationTests.cs
- test/NonSilo.Tests/Serialization/BuiltInSerializerTests.cs
- test/Orleans.Serialization.UnitTests/PooledBufferTests.cs
> Fix `PooledBuffer` serialization & initialize ActivationMigrationManager on startup

- src/Orleans.Core.Abstractions/Runtime/RuntimeContext.cs
- src/Orleans.Runtime/Activation/ActivationDataActivatorProvider.cs
- src/Orleans.Runtime/Core/SystemTarget.cs
- src/Orleans.Runtime/Scheduler/ActivationTaskScheduler.cs
- src/Orleans.Runtime/Scheduler/ClosureWorkItem.cs
- src/Orleans.Runtime/Scheduler/RequestWorkItem.cs
- src/Orleans.Runtime/Scheduler/TaskSchedulerUtils.cs
- src/Orleans.Runtime/Scheduler/WorkItemGroup.cs
Fixes #8854
This PR ensures that we are consistently resetting `RuntimeContext` after every usage. This prevents the access violations from the above issue.
> Always reset `RuntimeContext` to previous value after use

- src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs
In particular, for status & error stack traces.
Fixes #8831
> Distributed Tracing: Use recommended conventions

- src/Orleans.Core.Abstractions/Core/IGrainContext.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Core/SystemTarget.cs
- src/Orleans.Runtime/Scheduler/ActivationTaskScheduler.cs
- src/Orleans.Runtime/Scheduler/ClosureWorkItem.cs
- src/Orleans.Runtime/Scheduler/IWorkItem.cs
- src/Orleans.Runtime/Scheduler/RequestWorkItem.cs
- src/Orleans.Runtime/Scheduler/TaskSchedulerUtils.cs
- src/Orleans.Runtime/Scheduler/WorkItemGroup.cs
Follow-up to #8864 to clean up some of the scheduling logic:
* Reduce the places where `RuntimeContext` is set to 2:
1. In Catalog when constructing a grain instance
2. In WorkItemGroup when executing tasks on an activation
* Remove unnecessary logs and logic
* Use `Environment.TickCount64` to measure task run durations instead of `Stopwatch.GetTimestamp()` for performance, also reduce calls to once or twice per task, versus multiple more.
> Clean up WorkItemGroup and ActivationTaskScheduler logic

- src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs
- src/Orleans.Runtime/GrainDirectory/GrainDirectoryCacheFactory.cs
- test/NonSilo.Tests/Directory/CachedGrainLocatorTests.cs
use GrainDirectoryCacheFactory to construct a IGrainDirectoryCache instead of hardcoded value. 
#8843
> Use GrainDirectoryCacheFactory to construct a IGrainDirectoryCache

- src/Orleans.Runtime/GrainDirectory/GrainDirectoryResolver.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/Hosting/DirectorySiloBuilderExtensions.cs
- src/Orleans.Runtime/Hosting/NamedService.cs
- src/Orleans.Runtime/Hosting/PlacementStrategyExtensions.cs
- src/Orleans.Runtime/Placement/PlacementStrategyResolver.cs
- test/Grains/TestGrainInterfaces/IPlacementTestGrain.cs
- test/Grains/TestInternalGrains/PlacementTestGrain.cs
- test/Tester/StatelessWorkerActivationTests.cs
- test/TesterInternal/General/GrainPlacementClusterChangeTests.cs
- test/TesterInternal/General/GrainPlacementTests.cs
> Ensure `StatelessWorkerAttribute.MaxLocal` property is accounted for

- README.md
build.sh was removed in 6b01cefba but README.md hasn't been updated.
> Remove mention of build.sh from README.md

- src/Orleans.Core/Networking/Shared/SocketConnectionFactory.cs
- src/Orleans.Core/Networking/Shared/SocketConnectionListener.cs
- src/Orleans.Core/Networking/Shared/SocketConnectionOptions.cs
- src/Orleans.Core/Networking/Shared/SocketExtensions.cs
This PR adds support for enabling TCP keep-alive on all sockets and enables it by default with a relatively aggressive 90s idle period before the first keep-alive probe is sent, 30s between retries, and 10 unacknowledged retries before a connection is declared dead.
The value of 90s was chosen because Orleans generally establishes relatively few sockets (under a few hundred per host for a large cluster) and some routers aggressively prune connections after a couple of minutes.
> Enable TCP keep-alive on all sockets by default

- src/AWS/Orleans.Streaming.SQS/Storage/SQSStorage.cs
- src/AWS/Orleans.Streaming.SQS/Streams/SQSAdapterReceiver.cs
- test/Extensions/AWSUtils.Tests/Streaming/SQSAdapterTests.cs
I was going through the source trying to figure out how SQS streaming works and found some typos along the way. Also took the opportunity to apply some quick code suggestions.
> Fix typos in SQSStorage.cs

- src/Orleans.Runtime/Core/GrainRuntime.cs
- src/Orleans.Runtime/Facet/Persistent/PersistentStateStorageFactory.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/Hosting/StorageProviderHostExtensions.cs
- src/Orleans.Runtime/Storage/StateStorageBridge.cs
- src/Orleans.Streaming/PubSub/PubSubRendezvousGrain.cs
- src/Orleans.Transactions/State/NamedTransactionalStateStorageFactory.cs
- src/Orleans.Transactions/State/TransactionalStateStorageProviderWrapper.cs
Fixes #8936
This fixes the issue identified in #8936 where accessing state in the grain's constructor would cause it to not be loaded during activation. Additionally, trying to access `RecordExists` before a successful read has been issued will result in an `InvalidOperationException` being thrown.
This also reduces the number of fields in `StateStorageBridge<T>` by moving fields which can be shared between multiple instances to a shared object.
> Always read grain state during activation if it has not been rehydrated

- src/Orleans.Core/Timers/SafeTimerBase.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Timers/GrainTimer.cs
Fixes #7865
To prevent the deadlock, we yield before invoking the timer callback. See [comment](https://github.com/dotnet/orleans/pull/8949#discussion_r1573380779).
> [3.x] Fix potential grain timer deadlock during disposal

- src/Orleans.Core.Abstractions/Statistics/IEnvironmentStatisticsProvider.cs
- src/Orleans.Core/Async/AsyncLock.cs
- src/Orleans.Runtime/Configuration/Options/ResourceOptimizedPlacementOptions.cs
- src/Orleans.Runtime/MembershipService/LocalSiloHealthMonitor.cs
Per the guidance at https://learn.microsoft.com/dotnet/csharp/language-reference/xmldoc/recommended-tags#list, a `<description>` node is required for bulleted lists. This PR resolves the list item display issues on Learn API ref pages. For example: 
/cc: @mikekistler
> Add missing description node to XML docs

- src/Orleans.Core/Messaging/GatewayManager.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- test/TesterInternal/StreamingTests/StreamTestHelperClasses.cs
1ms is the minimum valid value (other than -1ms) for `PeriodicTimer`. There were some cases where we were not ensuring that it received valid values.
> Ensure PeriodicTimer period >= 1ms

- src/Azure/Orleans.Reminders.AzureStorage/Storage/AzureBasedReminderTable.cs
- src/Azure/Orleans.Reminders.AzureStorage/Storage/RemindersTableManager.cs
- src/Orleans.Reminders/ReminderService/LocalReminderService.cs
- src/Orleans.Reminders/SystemTargetInterfaces/IReminderTable.cs
- test/Extensions/Tester.Cosmos/ReminderTests_Cosmos_Standalone.cs
- test/Extensions/TesterAzureUtils/Reminder/ReminderTests_Azure_Standalone.cs
- test/TesterInternal/RemindersTest/ReminderTableTestsBase.cs
It is possible that the `IReminderTable` implementation might be accessed before it has been successfully initialized. This PR ensures that is not the case for `LocalReminderService` by initializing the table before starting the `LocalReminderService` and before grains are allowed to start.
While doing so, I also implemented support for `CancellationToken` in `IReminderTable` for startup/shutdown, obsoleting the existing `Init()` method and replacing it with `StartAsync(CancellationToken)`, adding a new `StopAsync(CancellationToken)`.
> Ensure reminder table is initialized before access

- src/Azure/Orleans.Reminders.AzureStorage/Storage/AzureBasedReminderTable.cs
- src/Azure/Orleans.Reminders.AzureStorage/Storage/RemindersTableManager.cs
- src/Orleans.Runtime/ReminderService/LocalReminderService.cs
- src/Orleans.Runtime/Silo/Silo.cs
This is a port of #8982 to Orleans 3.x
The 3.x initialization logic differs from 7.x+, so the port is not 1:1. Generally, I also tried to minimize unnecessary changes (clean up).
> [3.x] Ensure reminder service is initialized before access

- src/Orleans.Serialization/Codecs/DictionaryCodec.cs
- test/Orleans.Serialization.UnitTests/BuiltInCodecTests.cs
Fixes https://github.com/dotnet/orleans/issues/8989
> Fix serialization of types inheriting from `Dictionary<K,V>` which add values in their constructor

- src/Orleans.CodeGenerator/ActivatorGenerator.cs
- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/CopierGenerator.cs
- src/Orleans.CodeGenerator/InvokableGenerator.cs
- src/Orleans.CodeGenerator/MetadataGenerator.cs
- src/Orleans.CodeGenerator/ProxyGenerator.cs
- src/Orleans.CodeGenerator/SerializerGenerator.cs
Adds `[EditorBrowsable(EditorBrowsableState.Never)]` to generated types.
> Prevent generated types from appearing in IDE

- src/Orleans.Runtime/Catalog/ActivationDirectory.cs
Fixes #8899
Disposes all activations, including SystemTargets, when the host is disposed.
> Dispose all activations when host is disposed

- test/Orleans.Serialization.UnitTests/GeneratedSerializerTests.cs
We're migrating from Orleans 3.7.1 to Orleans 8.0.0. 
We have this issue, which a class inherits from a generic list. Currently, the codegen is skipping this and on runtime, it's throwing an error: Could not find a base type serializer. I've added a simple unit test so you have an easy repro of this issue.
> test(codegen): add derived from list

- src/Orleans.Streaming/ISiloPersistentStreamConfigurator.cs
- src/Orleans.Streaming/QueueBalancer/LeaseBasedQueueBalancer.cs
- src/Orleans.Streaming/QueueBalancer/LeaseBasedQueueBalancerOptions.cs
- src/Orleans.Streaming/QueueBalancer/QueueBalancerBase.cs
- test/Extensions/TesterAzureUtils/Lease/LeaseBasedQueueBalancerTests.cs
`LeaseBasedQueueBalancer` is not a grain and therefore it should not use a grain timer. This PR changes it to use a `PeriodicTimer` instead and cleans up some of the code.
> Use `PeriodicTimer` instead of `GrainTimer` in `LeaseBasedQueueBalancer`

- src/Orleans.Streaming/SiloPersistentStreamConfigurator.cs
Since the migration to Keyed-DI, the Streaming options validator was not called.
> Fix streaming config validator registration

- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/InvokableGenerator.cs
- src/Orleans.CodeGenerator/Model/InvokableMethodDescription.cs
- src/Orleans.CodeGenerator/Model/InvokableMethodId.cs
- src/Orleans.CodeGenerator/Model/ProxyInterfaceDescription.cs
- src/Orleans.CodeGenerator/Model/ProxyMethodDescription.cs
- src/Orleans.CodeGenerator/ProxyGenerator.cs
- src/Orleans.Core.Abstractions/Core/IGrainCallContext.cs
- src/Orleans.Core.Abstractions/Placement/ResourceOptimizedPlacement.cs
- test/DefaultCluster.Tests/GrainInterfaceHierarchyTests.cs
- test/DefaultCluster.Tests/PolymorphicInterfaceTest.cs
- test/Grains/TestGrainInterfaces/UnitTestGrainInterfaces.cs
- test/Grains/TestGrains/PolymorphicTestGrain.cs
- test/Grains/TestGrains/ServiceType.cs
- test/Tester/GrainCallFilterTests.cs
In #8749, we changed how we generate invokers (essentially, closure classes which represent grain method invocations) so that we only generate one invoker for each original method definition. That was in response to an issue uncovered by one of the analyzers which @ledjon-behluli added: https://discord.com/channels/333727978460676096/922948121619751012/1179628138490232923, where it was previously impossible to add aliases to some types.
Unfortunately, that caused an issue, which @oising hit: for grain extensions, we need to know which extension interface to fetch from the grain so that we can execute the right method against it.
The following code snippet corresponds to the grain extension test interface added in this PR.
Notice that the `target` field is typed based on the original …
> [CodeGen] Always specify grain extension interface for grain extension calls

- src/Orleans.Runtime/Silo/Silo.cs
Avoid logging on subsequent calls to StopAsync
> Fix silo shutdown logging when silo is already shutting down.

- src/Orleans.Core.Abstractions/Core/DeactivationReason.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Catalog/ActivationMigrationManager.cs
- src/Orleans.Runtime/Catalog/ActivationState.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
When migrating, update the cache speculatively before performing the migration. This reduces the window where the local silo will route messages to the current instance instead of to the new instance.
Set `GrainInstance` to null in `DisposeAsync()`, not `UnregisterMessageTarget()`.
Call `DisposeAsync()` before `UnregisterMessageTarget()`
> Improve `ActivationData` shutdown process

- src/Orleans.CodeGenerator/Model/ProxyInterfaceDescription.cs
- test/DefaultCluster.Tests/CodeGenTests/IRuntimeCodeGenGrain.cs
Fix https://github.com/dotnet/orleans/issues/8991
> Exclude explicitly implemented interface methods from proxy

- src/Orleans.CodeGenerator/InvokableGenerator.cs
- test/DefaultCluster.Tests/CodeGenTests/IRuntimeCodeGenGrain.cs
Fixes https://github.com/dotnet/orleans/issues/8973 (partially)
> Consider interface method accessibility when generating the invoker

- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorageOptions.cs
- test/Extensions/TesterAzureUtils/Persistence/PersistenceProviderTests.cs
Currently the Azure Table Storage provider saves the grain state (*encoded JSON*) but in binary format- Regardless if the orleans serializer or one of the two json serializer are used. And while it can be decoded as UTF-8, its cumbersome to do that when someone wants to manually intervene and change the data in ATS. Let alone just a quick way to simply **look** at the data.
This PR brings back `StringData` but with the difference that its does NOT use `Newtonsoft.Json` to serialize the data as it was previously, but instead uses the `GrainStorageSerializer` and converts the `BinaryData` to a string format. This allows the data to follow what ever grain storage serializer is configured by the user i.e.: Newtonsoft.Json` or `System.Text.Json`.
AFAIK this is not a breaking change, as we'll …
> Brings back support for `StringData` in ATS provider

- src/Orleans.Core.Abstractions/Core/Grain.cs
- src/Orleans.Core.Abstractions/Timers/ITimerRegistry.cs
- src/Orleans.Runtime/Timers/TimerRegistry.cs
- test/Grains/TestInternalGrains/TimerGrain.cs
#8954 changed the public API for RegisterTimer. This broke OrleansTestKit in 8.2.0-preview1. This PR undoes that change. In the future, we will deprecate this API anyway, but this keeps things compatible.
> Avoid changing soon-to-be-deprecated RegisterTimer method return type

- src/Orleans.Serialization.NewtonsoftJson/NewtonsoftJsonCodec.cs
- src/Orleans.Serialization.SystemTextJson/JsonCodec.cs
- test/Orleans.Serialization.UnitTests/JsonSerializerTests.cs
- test/Orleans.Serialization.UnitTests/Models.cs
- test/Orleans.Serialization.UnitTests/NewtonsoftJsonCodecTests.cs
This enables serializing objects of type:
**System.Text.Json**: `JsonArray`, `JsonElement`, `JsonObject`, `JsonDocument`, `JsonNode`, `JsonValue`
**Newtonsoft.Json**: `JObject`, `JArray`, `JProperty`, `JRaw`, `JValue`, `JConstructor`, `JContainer`, `JToken`
Fixes #7607
> Add support to JSON codecs to serialize their generic JSON types

- src/Orleans.Streaming/ISiloPersistentStreamConfigurator.cs
- src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs
- src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingManager.cs
- src/Orleans.Streaming/Providers/IBackoffProviders.cs
- src/Orleans.Streaming/Providers/SiloStreamProviderRuntime.cs
This PR adds support for custom back-off providers from `PersistentStreamPullingAgent`, mainly for:
1. Message Delivery
2. Queue Reading (to be consistent, but may prove useful for others)
Each provider is keyed to the respective Stream Provider, and allows for different (stream)providers to have different back-off providers.
cc @benjaminpetit
> Allow custom back-off providers for `PersistentStreamPullingAgent`

- src/Orleans.Runtime/Catalog/StatelessWorkerGrainContext.cs
- test/DefaultCluster.Tests/StatelessWorkerTests.cs
- test/Grains/TestGrainInterfaces/IStatelessWorkerWithMayInterleaveGrain.cs
- test/Grains/TestGrains/StatelessWorkerWithMayInterleaveGrain.cs
Since `MayInterleave` predicate is handled as a *component*, and components are not allowed in SW grain context. Using `MayInterleaveAttribute`, orleans throws an exception as detailed here #9049 - It is understandable to not allow components to be registered with SW's, since they may interplay with the grain's state, and SW use-case is not to dealing with state.
I think the constraint can be relaxed here since the interleaving operation is determined on every message invocation, and the method that determines that is defined as `static` and is purely functional, there should not be any problems AFAIK.
Personally I would go with a custom thread-safe singleton, but I can understand people using `StatelessWorker**(1)**` as a means to have a single worker-per-silo that is inherently …
> Adds support to use `MayInterleave` with `StatelessWorker` grains

- src/Orleans.Core.Abstractions/Logging/ErrorCodes.cs
- src/Orleans.Core/Runtime/CallbackData.cs
- src/Orleans.Core/Runtime/IRuntimeClient.cs
- src/Orleans.Core/Runtime/OutsideRuntimeClient.cs
- src/Orleans.Core/Runtime/SharedCallbackData.cs
- src/Orleans.Runtime/Core/InsideRuntimeClient.cs
- test/DefaultCluster.Tests/HostedClientTests.cs
- test/TesterInternal/TimeoutTests.cs
Callbacks for timed-out request messages in `InsideRuntimeClient` were never removed because they were unregistered by `msg.TargetGrain`, instead of `msg.SendingGrain`.
> Fix leaking timed-out callbacks in InsideRuntimeClient

- src/Azure/Orleans.GrainDirectory.AzureStorage/Hosting/AzureTableStorageGrainDirectoryProviderBuilder.cs
- src/Azure/Orleans.Reminders.AzureStorage/AzureTableStorageRemindersProviderBuilder.cs
It seems Reminders and GrainDirectory providers for AzureTableStorage are improperly registered.
It should fix this issue that i've been able to reproduce https://github.com/dotnet/aspire/issues/4010 . It's currently impossible to use Table Storage for both reminders and grain state with Aspire.
> Fix table storage Reminders and GrainDirectory providers registration

- Orleans.sln
- src/Orleans.Serialization.FSharp/FSharpCodecs.cs
- test/DefaultCluster.Tests/SerializationTests/SerializationTests.cs
- test/Orleans.Serialization.FSharp.Tests/Orleans.Serialization.FSharp.Tests.fsproj
- test/Orleans.Serialization.FSharp.Tests/SerializationTests.fs
- test/Orleans.Serialization.UnitTests/BuiltInCodecTests.cs
When using `Unit` in Grain interfaces defined in F#, the Silo startup fails with the message `Orleans.Serialization.CodecNotFoundException Could not find a codec for type Microsoft.FSharp.Core.Unit.` We have previously gotten around this by creating a Surrogate like this in C#
```
[GenerateSerializer]
public struct UnitSurrogate;
[RegisterConverter]
public sealed class UnitSurrogateConverter : IConverter<Unit, UnitSurrogate>
{
public Unit ConvertFromSurrogate(in UnitSurrogate surrogate) => null;
public UnitSurrogate ConvertToSurrogate(in Unit value) => new();
}
```
This PR tries to add support for serializing `Unit` directly by creating a `Unit` codec. The implementation is based on the implementation of the `null`-case in `NullableCodec<T>`. I'm note sure the `Copier` implementation is …
> Adding codec to serialize F# Unit

- samples/README.md
- src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs
As discussed in #9011, create `ActivityContext` from `traceparent` and set `isRemote: true` to correctly propagate the `Recorded` flag.
> Fix for Recorded flag not propagated between activities

- src/Orleans.Serialization/Serializers/CodecProvider.cs
- src/Orleans.Serialization/Serializers/SurrogateCodec.cs
- test/Orleans.Serialization.UnitTests/ConverterTests.cs
- test/Orleans.Serialization.UnitTests/Models.cs
Fix and unit test for https://github.com/dotnet/orleans/issues/8879
Only select IConverter<,> interfaces whose types arguments matches the searched type.
Unit test also submitted separately as a fail test in https://github.com/dotnet/orleans/pull/8880
> Support implementing multiple IConverter<,> in single converter class

- src/Orleans.EventSourcing/Common/PrimaryBasedLogViewAdaptor.cs
The additional pos++ causes the loop to behave like pos += 2.  Removing the additional pos++ so that each submission entry will be checked.
> [Orleans.EventSourcing] Fix double-increment in `RemoveStaleConditionalUpdates`

- src/Orleans.Core/Networking/Connection.cs
- src/Orleans.Core/Placement/Repartitioning/IMessageStatisticsSink.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/Messaging/MessageCenter.cs
- src/Orleans.Runtime/Placement/Repartitioning/ActivationRepartitioner.MessageSink.cs
- src/Orleans.Runtime/Placement/Repartitioning/RepartitionerMessageFilter.cs
This is a minor perf tweak to avoid interface dispatch when the newly-added activation repartitioner is not enabled
> Activation repartitioner: use `null` for no-op message observer to avoid interface call

- Directory.Packages.props
- Orleans.sln
- src/Orleans.Serialization.MessagePack/MessagePackCodec.cs
- src/Orleans.Serialization.MessagePack/MessagePackCodecOptions.cs
- src/Orleans.Serialization.MessagePack/Orleans.Serialization.MessagePack.csproj
- src/Orleans.Serialization.MessagePack/SerializationHostingExtensions.cs
- test/Orleans.Serialization.UnitTests/MessagePackSerializerTests.cs
- test/Orleans.Serialization.UnitTests/Models.cs
- test/Orleans.Serialization.UnitTests/Orleans.Serialization.UnitTests.csproj
- test/Orleans.Serialization.UnitTests/ProtobufSerializerTests.cs
This PR adds ability to use MessagePack serialization with either MessagePack-specific marked contracts or using DataContract attributes (requires explicit opt-in).
NOTE: quick benchmarking showed that this performs worse than both default Orleans serializer and default MessagePack serializer (since there is more "boilerplate" code required to integrate Orleans <-> MessagePack) so I've put a note in the comments.
> MessagePack codec 

- Orleans.sln
- src/Orleans.Runtime/GrainDirectory/AdaptiveDirectoryCacheMaintainer.cs
The sleep time between refreshes in `AdaptiveDirectoryCacheMaintainer` is set to 5 minutes. This PR fixes the logic to ensure that the application promptly terminates without needing to wait that long.
> Promptly terminate AdaptiveDirectoryCacheMaintainer

- src/Orleans.Runtime/Timers/GrainTimer.cs
- test/DefaultCluster.Tests/TimerOrleansTest.cs
- test/Grains/TestGrainInterfaces/ITimerGrain.cs
- test/Grains/TestInternalGrains/TimerGrain.cs
> Allow GrainTimers to dispose themselves from their own callback

- README.md
> Update nightly feed to point to dnceng

- Directory.Packages.props
Bump Azure.Core to 1.41.0
Update to 8.1 for Aspire
> Bump Aspire and Azure.Core versions

- src/Orleans.Core/Runtime/MembershipTableSnapshot.cs
- src/Orleans.Core/SystemTargetInterfaces/IMembershipTable.cs
- src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
- test/NonSilo.Tests/Membership/MembershipTableSnapshotTests.cs
While validating #9103, I uncovered this bug in membership which allows inconsistent membership views between replicas. 
Currently, membership always reflected the silo's local view of its own status (eg `ShuttingDown` vs `Active`) and incorporates that into any membership snapshot it receives. For algorithms relying on consistent membership snapshots, this cannot be allowed. This PR changes the behavior so that each silo sees what every other silo sees for a given membership version.
> Clustering: ensure snapshots are globally uniform

- src/Orleans.Core.Abstractions/Core/IGrainBase.cs
- src/Orleans.Core/Async/TaskExtensions.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Catalog/ActivationMigrationManager.cs
- src/Orleans.Runtime/Catalog/ActivationState.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/Catalog/GrainLifecycle.cs
- src/Orleans.Runtime/Catalog/GrainTypeSharedContext.cs
- src/Orleans.Runtime/Core/GrainRuntime.cs
- test/DefaultCluster.Tests/GrainActivateDeactivateTests.cs
This PR cleans up activation lifecycle around shutdown, removing some duplication and improving hygiene around cancellation.
It enables deactivation to be triggered while a grain is still activating, eliminating the `"Calling DeactivateOnIdle from within OnActivateAsync is not supported"` message. When deactivation is triggered, the `CancellationToken` passed to the ongoing `OnActivateAsync` will be canceled.
This PR also fixes a possible `NullReferenceException` when a silo is shutting down ungracefully and a grain is disposed without first being deactivated, which can happen during ungraceful shutdown.
> Allow deactivation to be triggered during activation, clean up deactivation flow

- src/Orleans.Core.Abstractions/Core/IGrainContext.cs
- src/Orleans.Core.Abstractions/Exceptions/OrleansLifecycleCanceledException.cs
- src/Orleans.Core.Abstractions/Lifecycle/ILifecycleParticipant.cs
- src/Orleans.Core/Lifecycle/LifecycleSubject.cs
- src/Orleans.Runtime/Catalog/ActivationCollector.cs
- src/Orleans.Runtime/Catalog/ActivationData.cs
- src/Orleans.Runtime/Catalog/Catalog.cs
- src/Orleans.Runtime/GrainDirectory/ClientDirectory.cs
- src/Orleans.Runtime/GrainDirectory/LocalGrainDirectory.cs
- src/Orleans.Runtime/Hosting/CoreHostingExtensions.cs
- src/Orleans.Runtime/Hosting/DefaultSiloServices.cs
- src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs
- src/Orleans.Runtime/MembershipService/MembershipSystemTarget.cs
- src/Orleans.Runtime/MembershipService/SystemTargetBasedMembershipTable.cs
- src/Orleans.Runtime/Placement/DeploymentLoadPublisher.cs
- src/Orleans.Runtime/Silo/Silo.cs
- src/Orleans.Runtime/Silo/SiloControl.cs
- test/Grains/TestVersionGrains/VersionTestGrain.cs
- test/NonSilo.Tests/Directory/ClientDirectoryTests.cs
This PR moves some of the hard-coded lifecycle logic out of `Silo`, leveraging the lifecycle system instead. This is a continuation of work started when the silo lifecycle system was first introduced.
> Simplify Silo lifecycle logic

- .azure/pipelines/templates/build.yaml
- src/Orleans.Core/Messaging/CorrelationId.cs
- src/Orleans.Core/Messaging/MessageFactory.cs
This PR introduces per-host randomization for message identifiers.
This serves two purposes:
1. It makes it easier to search diagnostic logs for instances of a message, since the ids are practically unique.
2. It allows us to use the message id in subsequent messages to a given grain. In particular, to implement cancellation support cheaply (see #9127 by @koenbeuk)
> Randomize CorrelationId generation per host

- src/AWS/Orleans.Persistence.DynamoDB/Provider/DynamoDBGrainStorage.cs
- src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs
- test/Extensions/AWSUtils.Tests/StorageTests/DynamoDBStorageProviderTests.cs
- test/Extensions/TesterAzureUtils/Persistence/PersistenceProviderTests.cs
resolve #9154 
The ClearStateAsync funcction doesn't remove the entry from storage by default.
Instead it only sets the state value to null,
If ReadStateAsync() is invoked when the value is null,
then it occurs an error from Serializer. `Insufficient data present in buffer.`
This error happens during the process of restarting our cluster.
1. The default value of [DeleteStateOnClear](https://github.com/dotnet/orleans/blob/0804e05b417e1ded3aa02d9e2727fbea3b19838b/src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorageOptions.cs#L20) is false.
2. The PubSubRendezvousGrain activates upon stream registration. 
3. [It calls `ClearStateAsync()` if there are no producers.](https://github.com/dotnet/orleans/blob/ae262c8f12f037898a30b4e46c0acba036d4fad9/src/Orleans.Streaming/P …
> Enable to activate Grain after clearing its state

- src/Azure/Shared/Storage/AzureTableDataManager.cs
This avoids unnecessary exceptions for non-existent entities when using any of the Azure Table Storage providers (clustering, persistence, etc).
> Azure Table Storage: Use GetEntityIfExistsAsync to avoid exceptions for 404s

- src/Directory.Build.targets
Candidate build for 3.x migration tooling did not have a proper source link due to not having a proper source link translation
> fix(3.x): source link translation visualstudio.com to dev.azure.com

- src/Azure/Orleans.Persistence.Cosmos/Orleans.Persistence.Cosmos.csproj
3.8.0-previewX version is missing due to `IsPackable=false` property: https://www.nuget.org/packages/Microsoft.Orleans.Persistence.Cosmos/3.8.0-preview2
> [3.x] turn on packaging for Orleans.Persistence.Cosmos

- src/Azure/Orleans.Persistence.AzureStorage.Migration/AzureBlobSiloBuilderExtensions.cs
- src/Azure/Orleans.Persistence.AzureStorage.Migration/Reminders/MigrationAzureTableReminderStorage.cs
- src/Azure/Orleans.Persistence.AzureStorage.Migration/Reminders/Storage/AzureTableMigrationReminderStorageOptions.cs
- src/Orleans.Persistence.Migration/DataMigrator.cs
- src/Orleans.Persistence.Migration/HostingExtensions.cs
- src/Orleans.Persistence.Migration/MigrationGrainStorage.cs
- test/Extensions/Tester.AzureUtils.Migration/Abstractions/MigrationBaseTests.cs
- test/Extensions/Tester.AzureUtils.Migration/MigrationAzureTableRemindersTests.cs
There are 2 problems I spotted with NuGet usage:
1) reminders cant be used with `UseMigrationAzureTableReminderStorage` registration, because `MigrationAzureTableReminderStorage` should be registered as `IReminderTable` instead of `IReminderMigrationTable` (otherwise resolve does not work)
2) I added a `ReminderMigrationMode` which controls what invocation is used in `MigrationAzureTableReminderStorage` (and in which priority). Something similar to `GrainMigrationMode`
> fix(3x): fix reminders usage

- src/Azure/Orleans.Persistence.Cosmos.Migration/ReferenceExtractorGrainStateTypeInfoProvider.cs
- src/Orleans.Persistence.Migration/DataMigrator.cs
- src/Orleans.Persistence.Migration/HostingExtensions.cs
- test/Extensions/Tester.AzureUtils.Migration/Abstractions/MigrationBaseTests.cs
- test/Extensions/Tester.AzureUtils.Migration/Abstractions/MigrationTableStorageToCosmosTestsWithStorageRegistrations.cs
- test/Extensions/Tester.AzureUtils.Migration/MigrationAzureStorageTableToCosmosDbTests_StorageRegistrations.cs
- test/Grains/TestGrainsNet8/MigrationTestGrain.cs
The ask was to support different underlying storage registrations if grains explicitly define what storage they are using via `Orleans.Providers.StorageProviderAttribute` like:
```csharp
[StorageProvider(ProviderName = "migration1")]
public class MigrationTestGrainStorage1 : MigrationTestGrain
{
...
}
[StorageProvider(ProviderName = "migration2")]
public class MigrationTestGrainStorage2 : MigrationTestGrain
{
...
}
```
I have added tests for such a case and noted that `DataMigrator` does not allow multiple registrations, so I have added a "name" to it, meaning user will need to register one `DataMigrator` per each pair of source-destination storages:
```csharp
siloBuilder
.AddDataMigrator(Source1, Destination1, name: Migration1)
.AddMigrationGrainStorage(Migration1, options => ...) …
```
> feat(3.x): support multiple underlying storage registrations

- src/Orleans.Persistence.Migration/DataMigrator.cs
- src/Orleans.Persistence.Migration/OperationsRateLimiter.cs
- test/Extensions/Tester.AzureUtils.Migration/Abstractions/MigrationBaseTests.cs
- test/Extensions/Tester.AzureUtils.Migration/Abstractions/MigrationGrainsReadonlyOriginalStorageTests.cs
- test/Extensions/Tester.AzureUtils.Migration/Abstractions/MigrationTableStorageToCosmosLegacySerializationTests.cs
- test/Extensions/Tester.AzureUtils.Migration/Abstractions/MigrationTableStorageToCosmosTests.cs
- test/Extensions/Tester.AzureUtils.Migration/Abstractions/MigrationTableStorageToCosmosTests_DataMigratorAsBackground.cs
1) Adding ratelimiting for operations per minute against source and destination storage option for DataMigrator. Added a runtime override possibility as well.
2) Fixing test failures after merging https://github.com/dotnet/orleans/pull/9454
> chore(3.x): add dataMigrator operation rate limiter & test fixes

- .azure/pipelines/templates/build.yaml
Currently CI for `main` fails with error: "Stage build_test must contain at least one job with no dependencies.". That happens because first job is not unconditional:
```yml
- ${{ if and(eq(parameters.codesign, true), eq(parameters.publish_nuget, true)) }}:
- job: PreDeploymentApprovalJob
```
I fixed to run job agentlessly (see `pool: server`) with manualValidation task; or on our pool with a simple echo of "Skipping pre-deployment approval". It takes 1 min to run this dummy-job, so not impacting the overall duration much.
related #9461
> fix: correct CI to run if no approval is required

- src/Orleans.Core.Abstractions/IDs/GrainId.cs
- test/DefaultCluster.Tests/SerializationTests/JsonSerializerTests.cs
- test/Grains/TestGrainInterfaces/IValueTypeTestGrain.cs
- test/TestInfrastructure/TestExtensions/HostedTestClusterBase.cs
Serialization of type containing a member of type `Dictionary<GrainId, T>` fails with 
> NotSupportedException: 'Orleans.Runtime.GrainId' is not a supported dictionary key using converter of type 'Orleans.Runtime.GrainIdJsonConverter'.
I added implementation of [ReadAsPropertyName](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverter-1.readaspropertyname?view=net-9.0) and [WriteAsPropertyName](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverter-1.writeaspropertyname?view=net-9.0) methods to `GrainIdJsonConverter`
Fixes #9491
> feat: support serialization of `GrainId` as `PropertyName`

- src/Orleans.TestingHost/TestClusterHostFactory.cs
> Remove TypeNameHandling option in the serialization/deserialization of IConfiguration in TestingHost

- src/Orleans.CodeGenerator/AnalyzerReleases.Unshipped.md
- src/Orleans.CodeGenerator/CodeGenerator.cs
- src/Orleans.CodeGenerator/Diagnostics/CanNotGenerateImplicitFieldIdsDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/DiagnosticRuleId.cs
- src/Orleans.CodeGenerator/Diagnostics/GenerateCodeForDeclaringAssemblyAttribute_NoDeclaringAssembly_Diagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/InaccessibleSerializableTypeDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/InaccessibleSetterDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/IncorrectProxyBaseClassSpecificationDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/InvalidRpcMethodReturnTypeDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/MultipleCancellationTokenParametersDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/ReferenceAssemblyWithGenerateSerializerDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/RpcInterfacePropertyDiagnostic.cs
- src/Orleans.CodeGenerator/Diagnostics/UnhandledCodeGenerationExceptionDiagnostic.cs
- src/Orleans.CodeGenerator/Orleans.CodeGenerator.csproj
- test/Misc/TestSerializerExternalModels/TestSerializerExternalModels.csproj
- test/Orleans.CodeGenerator.Tests/OrleansSourceGeneratorTests.cs
We suspect inability to serialize private fields because of the ref assembly. Therefore I am adding a check on code generator, which will emit a diagnostic if the target model is coming from the ref assembly.
Also moved ruleIds to separate file to easily nagivate accross different existing diagnosticIds.
Example: 
Fixes #9265
> Report error when generating serializer for model from ref assembly
